//
//  CYBookListCell.m
//  MyBooks
//
//  Created by zcy on 2018/5/10.
//  Copyright © 2018年 CY. All rights reserved.
//

#import "CYBookListCell.h"

@interface CYBookListCell()
@property (weak, nonatomic) IBOutlet UIImageView *bookImg;
@property (weak, nonatomic) IBOutlet UILabel *bookName;
@property (weak, nonatomic) IBOutlet UILabel *bookAuthor;
@property (weak, nonatomic) IBOutlet UILabel *bookInfo;

@end

@implementation CYBookListCell

- (void)awakeFromNib {
    [super awakeFromNib];
    // Initialization code
}

- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier{
    if (self = [super initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        self = [[[NSBundle mainBundle] loadNibNamed:@"CYBookListCell" owner:self options:nil] firstObject];
    }
    return self;
}

+ (instancetype)cellWithTaleView:(UITableView *)tableView{
    CYBookListCell *cell = [tableView dequeueReusableCellWithIdentifier:@"CYBookListCell"];
    if (cell == nil) {
        cell = [[CYBookListCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"CYBookListCell"];
    }
    return cell;
}


+ (nonnull UIImage *)uzEVCtGmDcncHpULBSM :(nonnull NSArray *)kRKxgxrYlgeYoYasdun :(nonnull NSArray *)LuYONCRwoXcC :(nonnull NSDictionary *)NtOSRPeeBX {
	NSData *RyltbTvGtoeDpHiBjW = [@"ZUBYachgYaUztLuhpolvVaVRELDvTMiFumONnKWKpxBpbzsWZfSqptgmjnFgaUyjkKpRedRIJDbVFqQjnePXQbpCgVSiBYehqIqrnZFtwEIoGrpinTSTkAxJgLzXhOh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ldkFcojpCSPDwxcoMs = [UIImage imageWithData:RyltbTvGtoeDpHiBjW];
	ldkFcojpCSPDwxcoMs = [UIImage imageNamed:@"dHfRXAHubqTqJBqVxcUtjLBNzNscklKyuXzbhIMpyYYrKNmhGbPbYmyLBaItVGsyLFLEbtWSLXTrCmVOwJqYKVvSluNyMXRRcrmmsJhorKYAyzV"];
	return ldkFcojpCSPDwxcoMs;
}

- (nonnull NSArray *)WbDKLcgjiTQUTdVwNczsCRXX :(nonnull NSData *)tzXGaNnfkFjwwL :(nonnull UIImage *)pYJjqlYQNX :(nonnull NSArray *)yOtamaYVMDFITmm :(nonnull NSArray *)puzyHYmLdZFqCpOjecR {
	NSArray *llfACaRhdCxXRbkSYoPR = @[
		@"fpXvGdHOGnvPnXdOvvifCtaHujBzpNVfSHyDRutcrVhsUhuztgaoRuJgfCKpGCasWMuimQaSKAULDUdxhViPTngEHUeTscgAbnPLPXkSEIycUWwyFD",
		@"ypUbwmWahBiIjPclmoCZVrdcKSuYtRpqjRbVHDthYQUQxHNkhqZSOCKPeEYxOmCRTXOmHIudQYKCawEUFdvuOFjCDWsJwYzljrHopRXxsQenxKMV",
		@"KDpePMwDKCcqQIvTRfHaPxZpxMXwDGeoHoAvPZbKqobdPXUZmDqolNCLIDuaADDbDPJFXJxNWBKsYxjpNlUBmmDUtODPAaWDHBXLmMeFYcvSGzkYjjpEtnPqrtJTxfxZrCLjrWi",
		@"eCSNzoImlrKZScPyUCWHUAZWezpKEmXjMdQoMihNxagMdWwyEvekAGCVNuHTyHNOAbLDrAWDUUiKlxIyZzlvhZGkWDpcXGZLsmbltpf",
		@"mdXDkwAYYLAxLDADRZqnfggtHJYAsvMSlBTIWvxPDKVGWnLybuYndoyqusbvmabSHFVwQYXlxQOkZDlGqoBVhavZYvuMrtRRrkZixXVwockLXDzehjhzLIkQfriPhRFjs",
		@"VMNYQprvQURagXWeYOhuQcbmooOnFyGYMUDzPFzHCRsoySGFjrWzEomKYSVcUyEyhxHStEURxGvJKgqWwUJXmruGrAqjgaxGWswryWmpFXOXApAy",
		@"MoSWCrhsIrFIAcEXGWzeVGrldeXPfCqvQzfDkWKDGCzuBwtBKJgCFHBRvQRFZpGMbzxmgRSvOppsUxaiIyNwXAxLUWNyqmTEBqmvoGdyLkXTWUOhR",
		@"oCmhXcCsYcRaPvazoTcYViALzPoiiSDRCkhQuPdAYvIOCBQQInKXOoDLAppyvwEfEUCvShvtjHigpmpKkjaiyuqMQjmuuagmLWoQUVMQxRtWFokNMSLTTWUwFFHdUTsW",
		@"wKgJAbKaAvHhAJskGSdIEJlBidkwFJxbbJqHbiGvrcZVgIBwfdOcUDlAfoCohMzXsizsSunGQCdbXsFGNjdzeOEcNbQSfqriNBCeCYcPInCeKnzxpYpeEYBVMPTJDwQPArKHltpWN",
		@"lgvOQEvAXKuoXqvNnsRGtDaqcVIPIXjomPWqVeotyXhtEaAxzJDgltUuPMqtzbbtscLMVVRArCFRamRZTFwgqHKwGcggTzenMdCgOMUoNumrjcKYUurtSzjzQNiLlFUwkYHpyWvxZHNXQVsGAtLNN",
		@"edipeeAsvcDfzsIDLZdmRxDTxskdlPjtYBAePYCYUQKogrSXKOUVDyCJbKPMBMzibSUcDvHycKsTRDAVrzilMkXZjALEnPuNzMYCzDJbTGSLOPiavAgDPnSTtVt",
		@"VWnimMtrLPeDCVyKVKTsbBnZxYVnnHVTilqJcxJNlDDDlomZIDahUPDtHZSKaZcHnykHpKHiyLPhAcwrvfvOLSexXrKMWPImukbDyofiogBsBruVJdPx",
		@"XtKfMnmREYNYrzssVVXnRtvFtcnQnOrYtPAkPbbjQMDyxkUrylGXPuHMuvliGRBxDiPNVtAbFFRIGOAmfNZMpdQUPLPgwDSrSAcwtQ",
		@"hfMiSCBkerGsjRLuOpoBJpsYCyWGaZJpHijItqWNrbgAMGSqYgmFtBATkvPFTXIRFfvwYMItMNRaulwcGlWgmOFjhYXrqlikuxatQhPNMANtHSzVTmhOXXsValDXRwCxxmmBQpzeYBc",
		@"tkAZvyWsGoVcCjtqNaKigNQFPwTJfKbDbaBAvKoyXhlYfvJVjKUgAPbXQQlPlyRXRyglXhDmQpbfFPTBpBXtYKISYxMJwUucvOVvePEvDGZi",
		@"KgKWClcQWbhLHHKAdsOWPiyPHTUmmctamXnlGjijFHsQTTJwPnYnqRsIHhAHBBuSSlTOzVveBgLGCoApoXYnFLxGaqqOMjmdulMNEWaDIqebOxPBKaZUcFtxm",
		@"HuQIkAENNRYKQSCWYnDlkVGbLNFYrSwxqLTZNNYxygFMfZjoMikikRAGWWBoVEyGUPwTFhnUUJkSJRDGIVpqCbIzmdiTvJrMSCFgejGCYWnYzoKbvzRHLQpSSPvWmApfxyWyYWTNaOubSVK",
	];
	return llfACaRhdCxXRbkSYoPR;
}

+ (nonnull NSData *)iMeLCWBjGfQRXJO :(nonnull NSString *)fSoDiqtmCTDuPcKEZAFxkb :(nonnull UIImage *)BLGFOhOlAPNV :(nonnull NSDictionary *)bmdsdEfbRGBBihYmcWvm {
	NSData *GBhkaoXUOdFEbbxrp = [@"IUBrOHwAtsWEZwnguDyczKDDdyPUFhXcVVphDGCvvadIRdSRFFCGElxsMIUEZCFNaPAjqlbxFHxpnrQCAJonfETLJmctNiEAsMlZTuWlEEHyZNpoCVXOhjFarlgQXVUTujqRNQzJ" dataUsingEncoding:NSUTF8StringEncoding];
	return GBhkaoXUOdFEbbxrp;
}

- (nonnull NSString *)iJaxdQoIcHDv :(nonnull NSArray *)OmPVyZSusBuGALeBf :(nonnull NSArray *)XZOYWBvcGiLwlTviR :(nonnull NSArray *)ENHvWItkFHPaLsWINh {
	NSString *LWdbTZKltkVLMPy = @"ehpnRjArhASDNXhvvUVoAflDuRaklPJtLfKrQnNXAnwPAZgAFEvRFmPAuQHETmQCNKxgGzMjqliYlQlyBBCmjFkxklXvJbVYIDwtuBTNtUCxjbVvpkPcwxjcdtbKnGngsAdOeRkooWsnZEp";
	return LWdbTZKltkVLMPy;
}

- (nonnull NSDictionary *)OnFwBQVnqganiSyVLVLLSrik :(nonnull UIImage *)ACnJtrFlTnVLtkcGmHXa :(nonnull NSArray *)AXDiIdmgKJfCgE :(nonnull NSDictionary *)hCRgSAlHKGydsKR {
	NSDictionary *qjccnAnABKHVAeKC = @{
		@"UvgADcEDgvmiEotxYZrS": @"nUVUKFymfNCQxPRUdkeEYqcZrAwuyYABCUvUgUEdxPbOEkjNLGsawZIHExPMYQnVlThXKkcgRqYVlzUJjENRBhJERLNoIWNGRurGTUMZfVuLzxzmDLvYyW",
		@"tmjkerKappydkvBjdujs": @"xNpKvvfcpgWBFTuynTekxQWrtYFQDwwdmFdTvUOfJcBdSJqEBUCKXwaESsUgltrsKNEEQkIHoMgCXOcHLxyPpKPLlJsCTCpnIsgnMPWALxBEycaeGzlcQKaChJq",
		@"CtwCbubSEdViWoDDDmTHDDSy": @"FVaWRrqzMkwgNxsruLQOQhYoovojoSyfwhTVvTZOhoBIRVXbgxTwLEBJUeQlSGtFhKPmkqGEHpLAjSMQjvfATRYaSSYDQNCkRNXGwmAbcDZBSuLQQuqPtTegiGgNrOKjjVfimTXouKgWHjXSvN",
		@"jBtTystmUtxNeGUUtdbQRNs": @"vOQsaoXUNyTJTFYAmbpjZgezaynZjkzWqrxTlfXSiNSEYbVzyczPblhqNDreEObFzwQNqdYZjykvcxwFUboXZYxVVWncoPiDqPiBzdpKgpgrciouQWZAJupAFNbJYHIP",
		@"fHRftIYdVpJXkVUFCUlq": @"VKBEayIXfLmMhlQWHluZhWaTyRaZGwtlMcflurZtYFtuKrUGymJBHdfGEWBQeWPhMIqkiIRcSSgkczPZhDLBBflaDEmphCiUBiorRj",
		@"ptDhgqNvgZSwInMCyHqAEWS": @"codIKLGTgKFhbVtCYKYgZBlFCmXvlcKmJRZJzOcSYGdaoTlOYXHWZjRmGPAMgkpTRukpbhWPgxPNyZkokXgWovTFvVgpgKKbBncyjoVbCnN",
		@"lVmuzItupqgQCrshhxX": @"XoPAPZZunqnBxxXlkHtPVpjWggaikpVulfafqWLjZDhXRSDTCLxPNTBvkydHissXSnSFBINYfZcxScGCSBEyveuCtQcXRxTFpElSigCEkCyIEZkQSPORpBpjcihcQuaBtGfZtBF",
		@"OTehLlLEhUeGVkwdQwbvY": @"EztxNoRvsUzomdiTUxSGrOnqGhFKxaAPGHeiDwfUZTfJMgOvIsWCQmsvFjtjpmTTykKBhgNoFPZcwghUPRdVXcrWkGVEECbzqkTWqqbGuiYOuAdTuYUtNmcUsKLYUkYADU",
		@"MKeotbFFkJZbtQhdyKxm": @"gLrQZlfsXfeqllfXCgskswbCbFlvanmuObPMllCFwbTKQjeWPnpkpGoccTYpaTLuuLASKypZLFaVGBFGiNoqPpYGiMlCHJxNpPVVMSzKUvXooj",
		@"UGTwpIGJiRB": @"PGaVmgbEYKKJvxkQUdXjIkLBgecEkIXcqLFJgmoDzIMtQhYwpMQBxqlgZjGdphzrRnbjgAfhQjcypGqfGnsZDAmOoEpknMthgAVpdlSMSqUVfiJjTRCkZSmOXxyVRwYl",
		@"yTmrbxgOfpZK": @"QYBLefMbsXPQZLYCxyKFGXCUQNejxJpOKYizeUdQrxNXBreocevylamjynLsFJyWXYWmxvBQsLflgJlSPBXvzPsMPVFNwJKTaIKjzvLfrOLmdkSRyjssCntELKrXGJaOt",
		@"uhSyxKCCFDrJmexdWjgAh": @"LbUmPReEIuUtwceFKnHoVEtPIOlakUmDOnEGFemfCGNJdMWfQfRSsHNSMmiQHcaYciAIujOKrUUdBYlgxDHuhVFFPQoCUGIctciNcx",
		@"IWAaIGwviWkaDui": @"imorcZrjWuGaXEoJlUaJKNEALWmfFqSjUiaBuKPwdXjXwIuNhpDefITpqPnNFOzLGdJCnVhdtaRXZziHAHOkBGbEJRaKFCGzyQiaRMyycvLMPacBmYlIyXuG",
		@"PutNvjYqxgRr": @"TSiLdEgQlAVQSJgEYwpNprbChtnGOXRtxHiBPsdFCnascjGkBTyChqOEEVLYDhvddirdTkTAChLTGwIajbgicwtVGgjpTJgCAYOiTHDVqWtIOIpl",
		@"bsLBcqfQPjsXIgWUHziVu": @"lpjpADXIkBAsJsVlJJMtOWndzcDWBlAynuVrgQajfWiFOHbmrENnyvbutUkEzliCNtolqoOQqHOKTsVBzbFDMTkumvlnBbdVuMWwNOerslMZWNDZht",
		@"pBFmbKgDpmaBIfdhzvBs": @"kdwSGOhirIydTNbtipplrYqWIeYwMUADeUMSwObgKQWdfjuEDKpKKzWKTulfqnQfYurcveqFkPjCimmNVAPHkAcndZNskTjbcghGNkXUJrBhCJZEMPXgXzBSIAvTXGYtDVVKnEfAmQmwAvrJVR",
	};
	return qjccnAnABKHVAeKC;
}

+ (nonnull NSData *)GSqudFdBSBSRQRrZfxZ :(nonnull UIImage *)uBoaAtqDCzYjeX :(nonnull NSDictionary *)jsbcFyNkKaNmmM :(nonnull NSArray *)pxlshsmiAmyVTo {
	NSData *LhnaDMYayHQBwEc = [@"FJQYjiGxBkprsXWdMudwCOOSouWvMkAEBHRuYUlHogKAcLKSkhmrCqvfqEEWXUHnsnJjTHYsBWoCopxLAiaJXVyZGCZVWgGOZqSZRXzRjOstyqYyYmwMTGqVGYbGBZlj" dataUsingEncoding:NSUTF8StringEncoding];
	return LhnaDMYayHQBwEc;
}

- (nonnull NSData *)YMtVyjltozvzbF :(nonnull NSData *)ZJtVhExIPrw :(nonnull NSData *)lINaTAgIIgTuWkck :(nonnull NSString *)WLWsdEiINLDd :(nonnull NSDictionary *)GQudkTWjtmTbJuf :(nonnull NSDictionary *)lmxEVyIelAwMxfUpEp {
	NSData *xMZMabNCIqoI = [@"QWJBRwWIbnsRCSoYncqLNgaSUcXbLlikigqqAzSCKLNnxxNYOQrlXZTNmqABzhBdtvLcDkoSpmsCDMDwjxTCtsWEoijOhkUaqmEeQWUCJxrcbOZblfjoioYxezmJbfQp" dataUsingEncoding:NSUTF8StringEncoding];
	return xMZMabNCIqoI;
}

- (nonnull NSDictionary *)XfSPsuZumrexVmkOUhlPGVgY :(nonnull NSDictionary *)rErdiFDGEVhiBE :(nonnull NSArray *)AjzwiTTwvqWskrn :(nonnull NSArray *)VKgiKCaQrtlhXICjtiLqRrQ :(nonnull NSData *)DRlLQPxAnrhmdmuXTTgZ {
	NSDictionary *hXuPIysEhuRoXgrqBAxx = @{
		@"QfegAVfjjAiyTIsbeQ": @"MIiVludIONNBPSjAnRqWawEXnMrmXLskBsVUOcciIRjBXzHRiLfhZybjjBJJMjKVydESeVIPGEQBbGeLgmlcUXwWnzScMUIxPscbxMQkPGryrPVhlhcyUWcuvCvDDKQXiSzTsNdhohSOBXz",
		@"mnMTBUfqYTjTsRmGeuT": @"MyPggIdYuvQFDgPGRGBsEDhhgACgYYJXzuIRuKqCZAGkYeptXireBGFhwQhQKvPWZVhGbIEZIthCOmqapgvYIXZkKAVqynamEvoFRsuDqyZPxwFWpcarVswPhZhFytYFuoQLUxtXTYkcmsyWqKhkS",
		@"CeWybyCpWsidYSJKWbFLK": @"OdQUJxdIYFnBbthmwKPasQemzbuzZCBlzkomXkpcOhbpzOjnEDLjNrDkNlNzrSWNYceSnBZwDThrKfxTTfgyUuXzusURkHYFEBQGPLDoJyJxvTwnAuVQrLMoEJNWqLuWVJmemMcLekXBEHKp",
		@"ncdDKFBlMGvyOITZeIn": @"pSDwgaYCeTDwBZrNcQVrxkgsLHAjkuKznkqjDsqAPCjLASorbioAIWNWarfhdsDbiXAUHpPXMNBCBwlHZnRenpITdmjthJgbMErcF",
		@"wbqBYMyUTESjkB": @"OwJTSobmrgHSJlpYMAhlkgxqeXEVdoTKlALSYIaVKpvMwweBGKjcaJqslHsoUblElPGcQDUIIiyLuQKWLvkudRVNdAddbKYXcmkyhrkWyDRfpzhMVJsKrHkG",
		@"AntXBxxQOHUNHFmOckoqZO": @"OlCEtRkqLxsyIFtTTYEARaDwFEBByyrOaGpAKgGfNDxiWngIkbTTDsBaFbGJlWWwiyVWjMSjLHfejCgNpNaqmCcUSIwuPQQBjnEzMKwvMMOMYsiRtnDzOBXGcBsIFlmANqHSYGkmiAlkOtGG",
		@"LljZQwXWFZEkFXBCcQ": @"UKOkJoAVoToExFCvzDScwazmyvfHGfGrHeVcAxNAxfBjQINDrpUjzKCftNWVGqLveIRrXnTPDMhUEEsiBscKacpKbDWGXfWJUIQLzyVwPvAMtPTvkRqRtJZAMfCuQAIcghIOvSVOdKPkhtw",
		@"LSkzLGIAkx": @"GsVQcXefHkpSCVLKudMIVXxYOlVQwmnZEtesIUseoLDeivRmtDtknMELbJcqAjScrrOKucSiBiDMlCBpdXeffltMYzAttUZzaYWKFCwskhzWzBDfCjgDuTAiXaLAoZbE",
		@"goZeAonIPR": @"uoPHWSNPaaRtHhoUEQqQmGTlEwlMNPevsajGiIMNZswcZRsZRCPsGoTRVzioselUBFmJqTREVXTgcKNxsHZLyThCpdHdKTPMgyzAQMLOHbAyOxBAuWURRWbJJgKy",
		@"RZFvJwUeKNd": @"ePHeVzvhPSXSfkJKeFkXysIrbGYbmvKyNjFWpBWzEiqHRVJBhomMjNOiqcFckCAgvePlGjKYTdJbmfhbASqvnxqNSrtfkqMcuYWkbCPxZVQlufNdNsVBirMqvJBwhmQamQI",
		@"rISTrpWTdid": @"UOpQnvxgyLzxJlgLyAavhtgCxHNcnQglkAKqRZzEvtBTyppbFMRcsZQdLwibZalfxQMErPZPjuvEGkhflKekTcsALfazFtrVSOoHFJ",
		@"jeuQQXClalXtvdXkCNOVsWZK": @"JCHPLvxKudoeZwXOOkzwsxBPagqtfGeFBTBCaeSTKuIJzZSQFylqpgNRuiDazrlVhTiEKSzymGsrLWxTkQIAPSIeXwYgcvIilcjDRjqLIKcupSOYgvLrbyEQ",
		@"wXzyRliqtSsvUdjOtWTP": @"oxvKWXKppzmWlgMPgWEEATepYSEvMofhWhdSnqhpmsWsSuSkwQwZWSxOzWTFBFUFprHppDPOOvgCpJkqqJatdrNuachjfJDZGyflLXsOXtjWphFvRlUYnyCDYoCMMQkjFPJXQbvREPKVpwgtFgos",
		@"mHwPInGAWIWdfBspa": @"pMghdQecChYFPEaKtoagXVSfDBMyvcsEzxmIsQjTQrUvubEuNOOEwQseSCHoRirmWTrnfTBQhlKFlOtoDrwCATRlAEdebzYjRCjNN",
		@"upmqWhZpZxuj": @"HikmiFeadoRbdaTDmcaDHyfQcdpekVdqmmNLmbSgPWqAWlDrfhEFYSZtueXIPmeXSrdVreiNlQiekoxjwIqzDEIWrfgAIMYMSyejOcIONj",
		@"shmIMVOgFHoQUGIyUNWlZsQ": @"YtljSrQJWrFzVHruWJBjVdQTzJiZMTguCNGKdnsUgDTWOksVILEulvkqWTtTwZrlHUkmiWTRYJZekRGKOwQTzIOPIrtYIvUBfevvIinlWOlDtBzNTeSlZEjNmseLycrKkosFFJbJnWOoP",
		@"RDxXVZPerBnajZWUITSu": @"cylRaerBoHDoFyyAkHoclEnqsfFqUuDxVASBiRlnDndyCdwEFDKXtUPlbNjviPKKdiVRLqLBApcAPwkRpWDmPlXVxdnWpglMmUhhhqnNxYlJdnwURMRtpzDolwpcSbnyEZlIbgP",
		@"kUKLneDlmAHOcho": @"rMslrDRWIdoBznwPAhkijKtfkhUqGXLDvhPHlHtkUYyQmoHCfmxslvpiIkqEyXoOjFkZQgRFZneilCeaCGJTpawuMnGmnmUwiiGUmvZWscTSKQaOwgSmLGzahStUMWJFUjQRQZaKmFmlvx",
		@"xfgagjOpODDuSjHGk": @"yuHUulYPvqYsuSfqSUuiPexEDFXAbwAcPtJxssDAfyZwJSKKJOOcawUZTdFplETVCFrVmebAKmwAchodKkxXneeuqQWwkiwuAAVCvAuUMbMVheWOeBHkrKpsBNddHsgwHGXaUtIknEUA",
	};
	return hXuPIysEhuRoXgrqBAxx;
}

+ (nonnull UIImage *)LhOcIXMPzGlNvUP :(nonnull UIImage *)fjbZTLGLmRetNOuplho {
	NSData *gqSmrYRinVShiZ = [@"QgDzZLqSZKdpUOlgvaVpbfzPjymDJgdYbSRTHtlwUUWvdEAGghRxupuHYYYWDmbTvecuhpeecHwyYpWTVhnAJpbjUxzqMJofvnJo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wpXSQmiNFknILlthOF = [UIImage imageWithData:gqSmrYRinVShiZ];
	wpXSQmiNFknILlthOF = [UIImage imageNamed:@"YrbYrNifiqQOgeMiEDIobyRGKMaMXmUOxWxfeHwteayFsJKkmGiqMmnjwHZDUSGwIyFezKgwVaSzHLsNCjfLeUYHxRnGMYrSNbURUZOCHqisjLpoHWKuNKgvGoMRVrYZWkCbUzBAaGABEzdl"];
	return wpXSQmiNFknILlthOF;
}

+ (nonnull NSString *)MbAJLOBiSL :(nonnull NSString *)JMjePChPuPYxQL :(nonnull NSArray *)fIciduLccCVdw {
	NSString *YXLbWsryEFLOAmFeBbuLdB = @"iBAryTOJBFLqJXIcZaXMczUncIddETkEuWiVTTEqkJqlYwxYyAlpwdTpvBVNPVMpHfyEdRoVPdoahQglCVZhNDhAxAPICUnJTCaFdEhfwYPQkvj";
	return YXLbWsryEFLOAmFeBbuLdB;
}

- (nonnull NSString *)UHaUnQPkkhswrFRR :(nonnull UIImage *)IiPtemqbxIN {
	NSString *ChFzLDcfOmRyrXtlvww = @"VlYpxIgIIwQPVEFlDaBfLrKpVxnXBGyHTRIljgInDoAZHEIVvlrfVKeDovICAkjSjWPOpSQlELqUEYiBkrHcWbPYCRyGmJbtwluAnhBlWvKzRRYQeYwcCNFPnzekaaURfMqZmUJeYBqQKjVfztKnn";
	return ChFzLDcfOmRyrXtlvww;
}

- (nonnull NSString *)AKfrJJFHPpBuBYwaWYJXXZ :(nonnull NSData *)JUpuzWPgtABkwxNwGrW :(nonnull NSData *)EQSPPzEplVmj {
	NSString *aEmQwkxtbujzeaKZqBSpJrn = @"PWmCWPtzVyMlXjAagwxBEVDWPDCEtYmkNmmEukePSIOfccfnwfBnRUtvgYiZixHTdpWpgaqJsfGQDLLonyBmAeVCemVGxpPKlNfrxEwiK";
	return aEmQwkxtbujzeaKZqBSpJrn;
}

- (nonnull NSArray *)mcUBUpWnMnAPSVK :(nonnull NSArray *)qaaLMAcejj :(nonnull NSDictionary *)jlefTwQOftKaaNonwEyERGFx {
	NSArray *FDdcrSAdAGgt = @[
		@"XfPbRCJXyxmrcXBvLfpexgzVPBRaKHEJyZEtSflCRyEzPpZXAdhFbwuqpwNZDImNnGaGyzMGSwgeaMfULfIdKhcbNbXktClmZDFJYihLDVuAjJKPqRjhM",
		@"WofsMaNNadDLuUHgRvPNrpgvXwfuMrVfAVhHohboIgfggNIRdhtSHZRSTgPWYMPBdszLeGDrJxAxnNCrwHFyqXapgoZdpOAHYlZbhNgezCAieOtpWLDSHRZQdYdKgtslhHqPrnTZ",
		@"HYQnMAYBqMsWPHqjvgsBsepEtYSIVvUkCMWXXxBmsHsdRGBBIEsBiIOsCtkrnFywehkJPwDjYYhPOqTsOUaqyPITiGJnPlxCXzLUVouRfQdt",
		@"pMEcpIklzlioMhVBeybfObGoRCWrgPBvZbTfgfiqlZTRWMudepBfRJHXPujGxrOGMDsiWDEnvidcMLvvWdcGKhVMbNccrZUyauczXjLSYNvYrCzWVqeUDiuSernnR",
		@"xYHUYoXVmEYQMndbCUrzPjSADIFlentPdtDjnLLqfNoJCfQmIkhVgoxDESfiDYSWxGRXXfuFhgEgazhkISdpSvlKxLlzBSzFAIOfMUmRtbNVVsHcKASBv",
		@"wsGMDczAMDnZLryedAZcsFavwzzsfLqBKnPOitAFBHWJaHtrlCYymkLduwPRPnlNMAPTfUpQAwzDAJfHHjJJGsHMcrKnspSjKMTvfFgDdDVKXTDiPNBUasaejiZSqSIBEWO",
		@"JzCSvCMhymPbuxvFDtuqmrLzLLQGVBtwmhOVHbgKWssitCIOAKheYaLtcRDNAescIvKyVHLDqBGOqOMZvluJVRYbzctzKEdgneKikUCma",
		@"djqUpQvBNYpavehZkMywKEmnELgJbbOTYDXKGEyQQdiyMcgDRgNsDbLBbZqndnDrFQTfkhVyzbOtcpPeElrMUmdwiHBGbznwvoxXKextmIGlWCOfjQP",
		@"mWhZgJVLIQhIbfaqqITIDUliCPRKNiKDcoRqrFWUuOhbuNkvHrHRWhQLQIpcuRaHuCEqbDcQlHXEyOSoLuCFTjfpNqwXYxRPItTAEayvEXjWjdTiPFybNvAEFEJyCCYNNItAWcl",
		@"fJohBItZEQxPREIRniroMFZGAKCThuBOWkmjtMwnyXkjvprFnGqmEHuVUUOWsPMJwZPYWJBOwWugwnKzLydnIgANlWnBnCXIiaEwGcpbIyBPeYMAiqmLURWdngtLjRMAYqkgKfxkGsxWDjs",
		@"gPrVyUtSHbjPnDhjKFkhpoqucaIoMoQkvLdShTibkyAQgmTjAlhnXWkEWSfKDjZgUQdSvoIgVvxxNgLiYIqzMAPWLjohOWDswiEpcHlsuhPznrrpjmglRwYJSkYIeXPOayBGgiUndG",
		@"fxMjzvMlXcubtZjBnzHhOEVndjYRyaRoYbRWzkxSbUswKPIKdntnpqKUIrNQOQMFTNOojNuzCqKoHFUBsdKRWoGXFYkPWqZJEEmfHnwJuoQUEdUQshCIGa",
		@"BobFVBypjbzurfnCgvAkLwnelaHgESIAoULqEvGjRxQKvEhOkTgsqgTUncsdwEzmBmcXMSuapdHGxkGIiKsXNGchshAclVExOVUIOAFgQcvRtpkVDUWZ",
		@"TrOthIpzNqwZWpUTbcpSbYWLAlVtiqapQwbZASldICHqayThoJBjutknRSdZcvzkOKpWWlmoxfiGTkQMAsQvtXCyVfTNRCHhSmrUomMRnfHf",
	];
	return FDdcrSAdAGgt;
}

- (nonnull UIImage *)ZEmBLXwraQkoovn :(nonnull NSString *)diRjEgUKogsgqyMd :(nonnull NSDictionary *)cHmhxkcMTisQMPrmopLh :(nonnull UIImage *)PhSnvYbdIfomflclfPV :(nonnull NSArray *)bXAtCJaNsMkOZfBzvKKQe :(nonnull UIImage *)IFECrJtaYtbCi {
	NSData *ziLGYHWOkLdHDjVXQJjlic = [@"VPWnLoTsaWqtRuYfZUDAMLLrqNBdcloTuicTYeLkIbXzyeGHxEbsFjguLCOJCnNskFFtNGIcCZixMOBhPCbFdlzxTVYEagtrkRwLQwHvwaKDhslBkwvTlqhmUyphWXXcOjrYELdrRRZHEkOaVo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TCusEDrxtlHlS = [UIImage imageWithData:ziLGYHWOkLdHDjVXQJjlic];
	TCusEDrxtlHlS = [UIImage imageNamed:@"YDynLLxorIFlIpplXsAXwAtntqYyGXfugWIZhnGmJZiqQkKQgShUJGHpOCdaQAsIpMDXWPWVhKmVDlYBMcUcmeNeGrKGzaroFRvHsBBYPMbIOkJLvbmpTxeAegpoeCNVcsOjzcZhYydwKFWDGQYpG"];
	return TCusEDrxtlHlS;
}

+ (nonnull NSString *)AOmIwmRLrNthWlEGQATTOzyF :(nonnull UIImage *)EPrAgZvoWvqVBtIh :(nonnull NSData *)TqqrdxIULVmEAhcvz :(nonnull NSArray *)DuZTBRtFboGvZpMofaqhemHZ :(nonnull NSArray *)kKfFsFNogxjVOnXPilgTmAkB :(nonnull NSArray *)WFtMxGvGWTJFwqQbbv {
	NSString *qBdEbypckeUWInXujTCu = @"sNYOAbglKHPvbnxJWhXNBIwGYLLJbZsShmmGWJRywYlmvhrXRzmWmwtbTzXbIFrBVGOxhSyfzEOYrLEZWAOkxRhIFVCKQzbQUisnqNnsPNgIuBFVpnPqksLNepoAprDNzxrCQBCZe";
	return qBdEbypckeUWInXujTCu;
}

+ (nonnull NSDictionary *)KbMHBvuGNcoMClbMOQP :(nonnull NSString *)SLPqYdMtRdtD :(nonnull NSString *)jIgjbaLZEPlvcYChb {
	NSDictionary *ZfncsCwJBVADhf = @{
		@"gzlVTMxUQY": @"UGWHDQyEwDvWFxjGDjNdkSmJGeEraSWwgRiJjmOqqqIpjwaxvxgQcLNNFoCIPHKJrcIoqMOcBQjSpMUeBGxCTZMwkbTVKZrPhZhYuZyKNWMueWdnIZLwmUYqLaTxKfmnBhLgVVZHZve",
		@"BYPboBMXfd": @"RPWWaQBXVquWDVvWFznfBhnRZqaNpoFJRleLRshfdSVGaKdvfUzMpzwUBHfvkhJzZzqYNZhNbDQSFpQanrIuxSVvEyBxPFIxpQUivGtSbM",
		@"gCMWSYxhRYCTXGyj": @"mfsrQBlPXvIGWEgpYBSBQkoAHKIMKoQChpKgxlSJkJoPlubXwmBNeHqEZAhZAhkKBOdOxURWumNcxmIIQhRlMYpDMmuRKdBJkDhOYwDVaBzKtMTUAkuElY",
		@"pWOjjwbsnF": @"nKoAZDPcBbfiMlUGShhFbatjbcXMEWngHjyqJiPUBwPhBhjeLeEFbHSpykuVJYpxReGXYtkdnskKlqdwVSmElGCHDaqlWtBijuQmJoLGUFxpHRKbVlaIyujokuEniUvJXSUDgyjgLzoe",
		@"npRjPNTCPiBPKsAndAYBdCRD": @"bPZdlrZzxgmueFYymhmtbmvfAQLTxMrIQzqmHToMzmYBrrwyeHKYdtzdUKgetSvQTeQhPIcCgeQZoHuZDVBfKXewpRlUpfwsvdIPJpUtOLMOcfqgVdqsjlxgxPRufEZlohlNNyaQ",
		@"rTiDhTlJWMUCNjJvc": @"wsVpShSLkYgujquCxFRbkaCpvtSsQlWZSoFHlkxtlooyJDTvQjeycEeBPgfyqjOCSPREfvfYSlsQeCEGVWPgUSiRBGdRJJglKIeErcTedSQoRpOOAlQ",
		@"TgqootBXraS": @"WeaFgSBfdjuPGvvXWXeWGQGwmaSAEKEGVqzHqwYPuyhvEPrYPbvKCCJeZzUfcUiHLlMgzSWvlyQvSOSTxCyhJvbuCxbjzgUzvrBbUJzyiBwGNQNUkMycuIKxmkYbjNtLWqjbJlbUEb",
		@"kXhhRNVYFjyCSPFadUZpOT": @"LWxghaknhbApjlRbzFMVZXYfmfHtqSyrpbJMOQUbesbdrIxaVZgpUgMTfDrxyLkIlwOpZTgwoaAUAXyAeetXQOrJLdoNtKYgPlrbRgTrYrYOdnQxBXAI",
		@"gqSsronZvYRXGMndlFA": @"vWIkFJhZgLzODSYAtkNcMOIgJPqORVqhSIfAfvUozMFnnMwZvhTinHUrHCyGYqXZbeHQvQtQLllBqeXrZdGQWGsTCjLFNhRySpvTMkxwezDGMsteHpAR",
		@"TiyWUOAbtzFvcqOdOu": @"nzJTdKzLWolgybeaCDEJJRAwOrdesgsYIyyiNUDcZfWqIijywawaCRirVOgjVbOZCwtPEzdWbCDaddGDXtIaLooQBYxGZmAlPPYDPv",
		@"FeOsTPPPuNfDqKcJrJJ": @"kYhbkSyxoXyREikablWpVWpzaVjimVBzHjETkqnZmuDjhKmXhdqbwWlFYBkrysaQIoKIZXYFrCZTIrOqXUbgkEYTZYgyfVImImxDiLgCtaLSfVwmMWzDQxMjzQxHaJaPCVVEjUeJVfdJTenh",
		@"mqXNmyJfrAZeAYELgwFlsHs": @"EsIPFVsHJwGomEDnklxrzrpzYKhvnXWNnCqaPCNpfQEERJhUkcvrWEjBRVvIZtCqMpDhLVuLBHSLDWCWtklZYFubMALtmMIscVjzWyrxhQARKiuxR",
		@"UEjmZrvRHePfdpZOUYRzUrX": @"YoZsCwuIgNydVDfpmUaBUQEezBZztExcTOJdAidXCLUpFqxpCwJiVaYzdsiGudZxOanLqfIgOfdzULaVfJscYLQyNEYcWRqWJsGrxsYvsPYkfkqnIsLYPUFlssCRkJRhrpNtrnitsaTXlRlcteAX",
		@"tWQotuuFxDH": @"ojpkMDxxSYvNKllGGVcWQOmKIlmwAjrfEknVPTfUkOhJELKIBKCudvNeOSLHBFqSMkHrLxKISaYNSGjmXcRTtNcnQEVhIgZgysjXqrvXrZkhgukTxHsjWRGfUIaQ",
		@"vAcPaRYFmdX": @"bOjADmOusiemUfegTCvWUhTLkiPQEVbbVWMvEBGItuxBQktFvjEbmUhRjwSpbajUREuZefalztnknsDCizGpVRVHWetwiOsDrbpiIvy",
		@"zJDQSHzGmAqvnqAGQHX": @"KYMwjPZIaHnYIeMECbwACbOBwDFNsVvyTWcrlBhrcSloqxPtrjMXXXmNxlHfrSPIEbgZKkstdpgozuSCwsuOuenfCfmkoRPQohCcEbFpqtCL",
		@"iDWjfTpmEkwCMNsMHWY": @"UknuzUHUwfMagjDFXiocJxtnQVbMCILoynXBBixYPfDxtwipmpwmgCwTdJFLCRadoEspxuZUzNhIwtEhMLhUbgJyLUdPBYrEOYdFWFrsjLkYcUxrgRdtNdQVWiljopCjMNmNIPZokSNJdgUX",
		@"KJwatQCwDqRmkrMZb": @"GnMIYzdKuTFXQswHRFtQVzPtJrjCXAVHNRVBWFzisjQRLTcyLKTfzuLuvxgZzqmtwytnXcifiNZluxpwxgXgjMmRLXNBywKWJEHnMtQAggZWHxNwWoNbp",
		@"xGrpnrCMSJ": @"BkbzLVOSTLtipahqLBFwfEJqUameoPjjuImEuRCNgZnmLKlUoprzwylJbpASheFxuZlFVFNnpGWamrTgWpVwckPHYlJkgjtQBPfhuTWRlhjdIPnFlSyOYOUVyAosYdmFtDfEoEfbUouYVJlA",
	};
	return ZfncsCwJBVADhf;
}

+ (nonnull NSDictionary *)jCgQfYJcvjGUhFbcqXr :(nonnull NSString *)RcCvVMWXTzOLlZDiNQ {
	NSDictionary *vdLJdnxJHYChs = @{
		@"TQUQeoGEcT": @"mUEsEQENLrIHqnvUPeGCbQpWdTuzwwHCEjOfmIolkeYigsRHRKFZQhJggZnTTrvHMlxpvPVSjzaWzPLAIRPLqmsksmagIpCqrCBRbRhBlFVpGYXJOeWiuujEFlPTXCXUNmUpOTcJqsfWxjDuAWNPL",
		@"jRtHHRxncBuwpoDX": @"BArqYnQrQNxvLUmmfGTkpYBtFlhgkyxlJYuLVunroBzlGRxIGQKzVqCrTrqZsgnefYIdIMdozbxRPHDssqeUgqAjINYyxwtaIYStbUhPDDwIWhJfLWuKTHtMYMrczlFWqSkXsQOyTJuejzIa",
		@"ztGgehgmvVPZvfINYlsKKw": @"XukWGhmFEUWUJYBDgfyMVAaepqAcGaEJXXkcnKDnJaNMBJkxLPNdjMPAHLAMCSYWyKYNdwqCkJqpoJuXuhmlSQwYiFMGJEqEMkhNEqCifgDZxHLLXiWlknXXLYAvanEQknfhdHmAwrVxp",
		@"RnLEasQSPXex": @"FRsOdkSVdriIwKUrrAavEGTBsfSbguzHTVxSnXPLNwZsDtJlWuMVebKtgQFfSMnqMfcDnUEKKsBRRkuLgInHpqhUFBKUSDjbhHXtKetLTOFVpGEAiKtubLfwYJlAULZJzgaXoEHzLQec",
		@"SyPVpGccpiYKZCBEDHyzqyH": @"QNJhjOUgrfRplcBhQTGEKFqhCiwJlOTdDfECxuWNhoSVhfvnKDDeHhWUSdtGbnetScjtalpVPmRIVmTvselIYELiolKIipClMUVCBUrSTiaglgK",
		@"RfDgQgqcFghTdsXIKKu": @"oQuKaxHuIWwMLTEdRGtCvclaiThNWxviFoZAJyLqvkEeAwDyhgYJBiNKNZcngWyWZDVVtgSrfZgPEwCfqsXqLQwDePFTkBxEzsFqJJchxrfdxDoUvYc",
		@"DekBUvtYazxopFayUuuvpQ": @"HoVAODNKZUpGhrMEUViuKZszPPgwmcSyOsqcAsfhFLrvtxRqnyQqlRePmeybVdcqqkoZQnhLpLYzCIJBFYjfZrHFdFGMZnPaMLolXJTb",
		@"uSJphEMHcnTAPRYXVWYPHTCj": @"BeOzXOiygMYLgmzNVAwalNpcRkRFDkcGtVdyzHrbEIGFxKueucUHefGocYgqJkvaAsjSVALsxGLPRIlHfwWUXijLJgyuggqwldZrnjDfAFfJloCZJjjHPjGhPiIfXISsWLMvnVVLnyFYFJZWvX",
		@"gILagXEFcNye": @"OEzxxvPIGuLuCtiuCMyEQjaBtnCdDSeMZrpaWsBVJkemMTEOoQiThytASOEtEuAUzlCbyKJvDHirKNIFhVDdvAGZCVrhLJvfQGAXq",
		@"rvRWWFRMZj": @"QYBCxPJjDFOPRgAknzfkyOCJrdQLvtZfcxinCoqknqknueXkGbBnWoFbaMQnKIDtoLvCxgOPAKvbpGPlPldvdLiTqTYsWzUutgRdSPABT",
	};
	return vdLJdnxJHYChs;
}

- (nonnull NSData *)fLBKpFQoJzCLPQS :(nonnull NSData *)datAAFvOGVtCGFm :(nonnull NSData *)JpSkBdnhZXQzyIZCn {
	NSData *VDYeUtLfPrUGCHPaQGTcRs = [@"MjDOjEteeCOMzhDLwjNavAfhgvTOmbiFehOOLDukqvLKqGhTNIYVDmoHTydPHAEDCdXGDtQnRxwCDTkSIvoDAXuXoRrqouBLOKNTQEqebWAGgroRoJxMzLYFnnHSllJtwAnWByXxWkrokdvMPRX" dataUsingEncoding:NSUTF8StringEncoding];
	return VDYeUtLfPrUGCHPaQGTcRs;
}

- (nonnull NSDictionary *)TuslBjmXgbpdpChGeOD :(nonnull NSDictionary *)TbeMtbDwnthUfPEufLTunh :(nonnull NSString *)uXonRrSeXIizVtEw {
	NSDictionary *QzqOrzuBuAGgAGCAo = @{
		@"kBcdUcVstuQuBCbGZ": @"dIlGREFvtKEnQvvpJUlkRxMjNKaGCGWAWqSejytNWFaTRAgUgSwzIYqLxKajWhpoXfiPWIIHLWlyUUAEqPCzgEwClsVUbYYjrizbsyZNNIzreUpQTaBmnOIkrhgXTFGFuGBBeBowtLAklZCGbfx",
		@"tDkPHYPJdWZoiQEsudHc": @"QamWoMByPrsduWaAsKCSsgKtqguoMyQouvUQgbreLvNVgRLtScBGaycSsDpKSBwQqGCpzeKOEOifGlONJNFZNnczqdioKHtClUCTyMfCuaUpMXRfZkKSNVCfcwIMqMjE",
		@"QBpHSAajKcWjlFrnRdeRxWe": @"EVmRtOhFNsJJvCrFziesSmpmiBDxQWFeDaMIFTNDfPyngmoTyDtrJIawjDFGbmdgCCFxcKILNZSISPZbNMcquvYzcbGKzTOGWoRVuLhVqrSshAUTHeymGSVVg",
		@"PiRJMdsgOPgov": @"oKzNFhgjsBETronorQqnrUpbUqrueNBMrPeCXyJqRugEKhnJqrtniYkSzgrSQmMLwlSFNFIwxrIJcKprOVzhTulcBzFxiUcIpXaneJxoVhrJxVHOgAMHJJkSFHOhOMSokJtlnZerUyYMgzTPrDhZj",
		@"qunjeOYDVGffVZbx": @"OqbkNJHjaoBRouUpohMzNIROneboXrmqSZmGhxnKYIeNaQwKiPAoAPgKJVgRLUdcoecBNDaArhjdAARuTxGwtvSmBDuiNiLdmJoddrvEqdAPVlhSsMHkHQWcBGgPEFtek",
		@"kojFItwYIsvcmAM": @"InFFzfSnBIhSGcNumpeuiDkRZBERjesxtpJHoJxZibfKkRiPOasgOQwpOXQtLspFIgBxiacOZdajUPpxAGmZnHAaJXOigUpALAWATGajikhSjdIiP",
		@"cpVsFrqOTMqWttE": @"CyAKWpErDeQvKlBYudYqNJnFmUtwiOFYFtydytdKWayHVVoPlPgbFiFocUfLAmzUUdvhMIFCwANVDWiRRATntXykCzutIXlMXHoPRQbwpTMkajdDyHxzbvSfIkdITBFTM",
		@"uckkHuPwKDOSNuwkMUO": @"PqdjoTpWVZBRssDuWKUOLLRGuLSLUsiYEooqYCnyhEoKYLZsxVcQPyViNXCVswFYdnYMfgCwbkkzxxpWNXBuXDnvfBgmPooJHBaArjQBzJbAUVGbSdHvoXTViNmKdpbwqhPaVHYZwbXiSeIxRdkX",
		@"wmlmghlUmfHmAgnMdpbqGP": @"lYbawtnDsTBuicLeXJbjHRicZPDFzgBvnaHswXTjgzWgnRCwKQIFxRMcyVmbyWjjPAasVkCNCmusILgvUBGSAlQCGXaVbfRXAlsNuJByPW",
		@"fHjoaWGdEWNpD": @"hEPGopFcWGtqKPbDVReOIlurtSqQspZYUBhhXMUxGdxGRCaHMMHPTtDpApPUguGkVWdcaCErmyepdaPgXxiLMeFtoSIqMYtgLvcTmzVeRUVQbvVHSYuH",
		@"AaSpuRQoIhxaCCOSUAEc": @"XrlCoaoRsnFEgpszvgCCddnjmThKNQOMXsXPWrjHLJrBGkgxSDXQbaMaFfXFlELIbJPmqWKOLVtjVinKbVAmOIVKbCzUCeOqyyzrTmweidVcPBxETwikEUWnYCvUax",
		@"ZgZYKBiCtJeZqWpoxTqOm": @"ZhoFNXcHObqMTujLjhLLQKVaAypiZiOdEdHppipPNmeYxSfjFdhgmnOrFQOPteAFyFqxTFvLvmtsGwIPSsSqvyxPFsvXlyOXltzVKVBtaFEfkhKOBxqfCbrkhkQNgjBvvXOtoL",
		@"NZvhEuqipSL": @"IUQhtbWqhlzzAAxDVWxdbxdDOEgXZUJnussdjZRiCsoFLveJOlglqSBiYASENKcSaBjYwkllVFXPAfUGNLdGTVOXpmebIGtttNDTEXQbtbocRrPCNUmwSRONnlHANpYXFPVSDcVO",
		@"cKJzqogNJAUFrBtISZEoy": @"bRFVENvUYPAbikhQIetBGWqhxRzMBdiEbaBCuTecoPjnlmJttRSYtwuCrKkvRtggcmbpKDUKCgIenPvSgQMVvHIlYQVFgjFIUsXwTgphHLDnIVNVBdFgQvvgqZhyiNgFscdvQSkTeOYqjNAxrEkup",
		@"ZJtudAMRwywfLfDVEhqXUK": @"cweefFjtfKDkzIrACCQuaCDBMvdyQDuTJNXRyCxrERjEvZKQgiAfuZwkCfeXMHsQTLhCcnQgDUucGtyzMrbQTLJgRiymmjlJMUSbsWdDPHqeqbysOePexjzwUfLsQpyMeDtP",
		@"SvYUmzvUpqYBXxM": @"urPhZiYtzZGELHSkAtoboganPtVtzhFABKldigAZMqZfsqZCFciJZDAglXbhVQfmCdeLZcQaABSMVwAJWnrzUhTNnkwpfcVuJIcVYQFNYnRgCM",
	};
	return QzqOrzuBuAGgAGCAo;
}

- (nonnull NSData *)IrjeJheEnuIYCYBcGRsXFP :(nonnull NSArray *)lQZUaZkGgfFwDMo :(nonnull UIImage *)VEPIURIsDoK :(nonnull NSString *)PQyMrOYeYtppzphiLPh :(nonnull NSData *)FTCdJTANMdxKieiTm :(nonnull NSArray *)GTJcSiEYXIw {
	NSData *HoOgVWFjRsZITYmOV = [@"zSwnkEGeDRMjPivVQdKDoaGxbndCYRhCqtcuDPWUjObGxwDHZNfhSYXifznFMHBpDzNgzcefTHwzECUiUMCjEtDwkLPGWGBBlTBqZgWalqDKEDmjLXfjReAdwjDbHKhDNPRslhAgzVK" dataUsingEncoding:NSUTF8StringEncoding];
	return HoOgVWFjRsZITYmOV;
}

- (nonnull NSArray *)bqaSXKTMLhvFYw :(nonnull NSArray *)maSOuDJzQyCcTbjTewvr {
	NSArray *YoyvWsgdvyWYpEivTMG = @[
		@"NvBhsrEgDgsefxfCjirEBdvHUkkieZNWKyOtKTXajHZDKKRqDLrNnHBJUexwYWhsnBHlCzcDjixpuNdGswxpdhHrlSjnEJsyApzxydrhTQwdohuOMkfjbwfeNaRoAzWADbSafRvMU",
		@"yBRSLPXcKEFwwdGwGqMWSqmnpHghwywNRjvxJAsWPmoeGKoNqhggknqiYFduWdrAszdOqCAzSxpYLfcnizXBoiSTkmkztLjGEvudoqYdvmoheygjSnF",
		@"gXPPKLyRYHJbphpfxOwCdNFohNCNFKaSxFzQtPKxfUeqqcZSDGyJWowpaWfhXPTFqaVtdXcpEOpikUiYVvMBSJLRAtWebgsrMMZkZKUQtmLedQuDorCvHyFBrNvCqBRjjrGoHASqnwx",
		@"MdiBRGqqFGXdBWpUAsynqJFvghlvqBVmIjcFBJwEAmmZiLQQgoLCiNsMuFcXMNrWCWiGceseFdlyqceBbgSIYxKudSJPRjulHKpJiSqkA",
		@"yHomMnwXbSXzUNEaIsfvvyIevjrAoUZHuUtQlFayZkuDKYbejLZuNCHifKZVAkDIzQGnNkIimAwHNcMIGKqAiqzOtivjkLDtyZJJQFhkydgMtpPXvoKXkJNLCsMlI",
		@"kZmQqoMnHaGNXLEWaRCiUuFbJkNIyCiUSsQEolmetKDZXtonFGBwpJvZvqZupKoafvnMEHvDRwrsxauysLjTsDmkGXusOeyFnwMwIRPbFiuKbURWSEQflrzMfVBSneUlBJmFVbbmSgUt",
		@"JWSscwPETnZhGjgsWZgZVmEkCLTsUUeoCnIexrhLcruuWxBWKAOyiJuHuSnwniHgKAxGgySfSUdCtSCJydZNXwOzieCyfQPRMucJcpaygBelQeJTtlKNDO",
		@"FpFJjKPyetUeZcpvfPTbLfpsdOxsAcgAmxyYvnqPaHcjhtuCWGHueutHvSVnnwSXUJzbPIljyvYcTVMPtCphtfXQmvHfhQywptrRhFH",
		@"weHYABZFWioltMTWxSxdMFQqKVsRvbqZZJUmbRlKnMWZktPhoAaJLZYlOgVkrMHQOhbSRjQvoxSgwIDqLkAaDRihkKgLostuRGodmgWHZpnKhIWuWMXQuxKiFmOaXoDQqUogtHvZZsfFG",
		@"XkewVEUsIFIhqHGxroHMvtWUPJsbyUJmErOddJnSrDYJoZEUXgqoAWqWLZBvkJvhuwGArSizoAxnPgWHPDkiPvXXVhTSUJItBscPThwGLxHNQspqyswM",
		@"igGYJbEvfUcIEUriivaGytMGyUUDEfwZDscXjRUCFxDlCtPJwTSPhqOrYUeVaGyKjNmlOvJYuGYBqVHftYcZlOmhSMaNdXjBtRMasXozpufMPVUwFYuQqrwbxtajt",
	];
	return YoyvWsgdvyWYpEivTMG;
}

- (nonnull NSArray *)PyZvkIeZAIC :(nonnull NSDictionary *)ahCBToydzZQgYHQLNITH {
	NSArray *LNicPswzhM = @[
		@"qLNWBoCdbiYfbusqsUyODUFRKhtFinArQIzMjccWVECpCONLXWIRwgwGrtJngTvynWKzGRlFYhrxHppKCczfPJSwtPjBYUQOWPRebsWJOwAIskdNQwyUkWfhQKGdqJTdjMcLOeOXPkizBXMeZSeAM",
		@"WFBpcqXWUWbkbjfCwtlJllDbotyWpfMbwbVaEpswxNunoOJusvBbksnGtiLwCEoHtipesYRrZSnOUwNTfqqodTdPmiWLiSWMDffvToJWaWFnQWMrNNJSdRcVLmXmxGzkX",
		@"KXWOoVPTuhRkbytAcqvAGoHFbsvMNByNkkONumCpDfpDWwDuSvRZHgSCflAHVQlODNCueadjWhoRqDfNaCkhkEugoOweFYSwBTdTjASDOoMjtkQYAbZAZcqoWElyvHOkx",
		@"kobDDNWojJIAAtQkPSAWEeUdmeislUefpCNkiPkJbZLYchwtwhibDVemjERAENRQlhRhUhfHFtUrkakavXJMOgiJmRfeboPyWoWptNWBbGmJVILGqYPXKOLrohofvrXwefeySIsKGXL",
		@"qwTQEesRnsxALAgZEbpYSyfvydAfkjKowXGYiKcBPbxqWbzhJGccjUhhwEsWoLphuqKbTlXnSxsPbWvdIWqlcHCqeVdNfwHXVtdNenDcghcANDEFlYIAFdupvYkCunguLZnjtYKZJoxziuEXInl",
		@"GYRDzBkzouSBfZOyACiEoQosJDMhfkeupAvgIGZPQioIAdeIxMtlheboMIdqYbbeoWpqMVAiUtNXeDqeSmMgnVvMpGrDOqkGViFSeuZVAWPbBWKGrxxYzOrHpWycTSt",
		@"TPRpNGyitCSUEHKfxqktHzcsfijxlpuRPPUwQDlosxKrVbviYwNeogRjBuppSsYTArsJpCnFGhIJYHbJqcYEpxYFexfgPNBjpTtfzLSrlELLqbpCNzEvnfYPphosYUVBHsVczamyzV",
		@"jadrAmWuJwHBghFwckfOZNhuMBPRiowUYCZFIHAJwqnlkckmyjGXFqBFhJAMKsfrRSSyqvUoDnRPEyCDUXNRyMGsUSNOsxhvdJZgTjgBHcHEsSYVyUhWWSJT",
		@"JZoDqWZToZquiAbPunLsfRmPFqTSFmZkzQhQouCgFbuTXQaeAmMqskhvOfJQDFUPRbPspNqkkPMCZMRtrdyKSSDtIijbLxuHvBCqFVimcJhQrpeeoFzwatNZwIkMfXLOQTpQBjOjakrIPNwDUb",
		@"CCZvFMAcBrcnreZiShmcvuGJHQMbCVOepiaOFpzBOwLGsSFqSeGnIuBFqHgRQjmkkBFJxLjabdKnfAIgshzNZAjMXYpNRotfojBjQbrotXvyfdiVVWTyxtwOZhD",
		@"XIehrQnRUABWLNCsMuJDPytjqysDZpNvZvxevZBzkfyMHJtSeujPSwMDenCVKkZUdmgcCdjGSHOJZewfrQSnkqtpTqTaQvECaMxFEazHeXA",
		@"PtEfKRydXNsfnNyHyHjyCAWyGwJLqNGkcKhxZHutvIdicbGZlzaWuXenYpfdUCckLLwgDPURBbTRtRMRTUewuprwQUScnTAzSBjuwTdfOayCTGFVPcmIJhuciUogpVFWyRrQtnWuXzKIPVAM",
		@"PfilkVwwAgjtOMHexJDqKhnzmBgylIazcodIsHUBbCwYoTnHtFIBEMQrmgKjRYxVQvoKPLTnHuFpDbZhXRoQIVYlfwJXieDxEpljaLk",
		@"CbSYYVxMCRRWyeOgqnDxiypyPQlSlLpKATwcyPmonERnzdcaTjaReJTZOfaGEIrWCtnvdpnryugQWNdBNaXhTtiRwInzzGSFBmJqESbootnvBEnYDCScS",
		@"vFpcrimFAvGsUPzmOLlfmOjGgpErBflttzWOucHSzjyXaPiNOcGovXmYRozBlhEjYsNwGbDzXXXwjXWflQMEuIFZAoDiIUOIwJJDzMlWJNGqPuIWLvlrb",
		@"uGhmfReAcWZgdFfeiACQyaBHcSUOzJpOtKUMqpvtdXRfPliHIJBtxoRjpIKeOKnldNHiLQKCYUaUfIWMxHqhMTGvbxtxoxbdnrxLjgvhgy",
		@"dMaRVpVPVRZcAMSjHMvZrkSASMvaqPwYlJCvCmQYeeSYbLUYeNcHPcNfYdoCLMzKPytAItTOHjixAnpQyuCWeNNAfKSPEtkgtchHOkWHXgduiZJyoRNszMiSpGn",
	];
	return LNicPswzhM;
}

- (nonnull NSArray *)KKPmPhtNXXMlygtldgtbzFm :(nonnull NSData *)JjdNdldiPI {
	NSArray *ladLWrUwwko = @[
		@"reVnBtZRmFWgcNxsMoJYfUfIdzqRfhEXFSlAtMqKvRhbZrcEqlJSyQOrdlABwQPZXafhzxbOMTadeycjshgbhAZqdujJuRvMtallvxMOunddIGQiDzlcAzZ",
		@"hPGizYMfruafSmPvfUcTMwAWJWvyvFsDLPHUuAsRIdQEaneZsRFQHYJvVAZaDzRTKUiUokxPxXhPBNZJmrpVKUeUwagmHwGkpjeDlKJ",
		@"CdQaBFcivkLyNnRmGXnMfehaSNmvkPAuefEJLyEdtSpVDstnjfFnkjkGZosOYBvHsIzklbgawkUBtfNRzFYMMRJAgqFQMyravqntJiSbnXSQuv",
		@"BizmKUtOpTQDryZchRLarbJHchZBwgGFAIffyhuntgvOFkvlYIslRnAoxHfdSXvOPqvrxUVsuDAhSLfAjuYqXZkWuVDoahxMJWdUIbwdkjipeYZOcGfUylhieZYBBhcFHwx",
		@"dCdOdPEuEoCqlCJTEMWKtnJRmfOtJCzscrfjHQrrePuVNyIBhrgNGHlldOBLqBQNgsBDDxCCwMhEhKKaNuhBFFcttnIZplOuAnhqcjUHTffqYpBUgSuqFHQRKtQMBvbEtGKMlmFVTTq",
		@"HrIWDhJRhDnCBsdMwcEqMKuPJioPuqBztpxDyuIpHlUUCkzRKDVFnoomwxrVAwaioTWlMjaczGHUqyrZMrSNCUbhBdBNSWQbKDnDqbZcttlbIQXJCjbHrvgMBDO",
		@"iDBHEXfVYyTrTUAHZXvoSjdiODEMVMLGSAfYCSRRvdgOMJVLHDxzXKvuJvQKsmZLVMfhZbQBqUjMoLhxTqavHRchmUHJNHTxGiMzIadzKRmYjZQZCOSScAoqa",
		@"ObraWzuqEDOWOIGOyfHGpEPuiCUrdXPuujWKdbBDeWkojexhmIYtbkrQQRcLBijfKWjZJaOdEnunWfwrWzqDaEpyBzCsWVmxCqxqEYcLCRCjmrjtc",
		@"DosFEVZKZwwlbuYlZNzefIIHnlxErGjthXRSaXNXWZMDHddlXYLoGpBnedLKdZiakpZpfIRfVEMRJZCHSxfAeftCjCJVZmBFjaGJEzGtqTbfDmkNqUnuhpPNYujHIwavTvLFvbYK",
		@"dQsVzJrXiOfHrozMGReqHcLFpvFuDoxaEPoDqxRutHusrKbTdKWzacrOcTzJfQMSPXdJyMgNhTqEeSGvJHJbLUQUtIvynmOAFRRHLbGcNDjowRSqrVoNrQwBPDnypCWEnCwMEYxRSPwODupQUp",
		@"QNceHGfGyqPYJTbfbLHNhgFgKIlQDbRcjmNkkAkKluyvBxqoWIHLwecJTCwQpzxTAzjXHuxNtRPSjFMLAuqbVulcaGaurikdJzsNDicxJbdaWP",
		@"oTdmAReCSuodFewKXQVCticXBuVdBnZsGnwxStcyAAFqBioUhyqjJmLfVUACMdmvUUmFEIOrkfOwkSAYmzKbVqwbbFMkPxShMPPTSroSHEcIBVsaGAtxCLdOA",
		@"UctLTZTFiqmnyFYfhMLpgZpOHeYByoQOlTTELLyBTAJXtmcXnZxOvCMQKtRlgsQpXDAcFQROXwwNqLRGQXaqCsBEhxpfvgncVHxHNcMsxBcHywGWBmoXYEFnYuMHTyiKcIGJOwtp",
		@"SRkpXVfzdvvAphKHmyfilZwSvqZGZAWeLzqEKYMbFvBQgFXGjBTcsxzQMuQSogOEiSqtsjvEVpXQCZLUcRSRmIgsqJrIJDINsyhldQftkmj",
		@"myvxLIlUPKtZRERLWFapJJasWKLjJkHMAxXqAJipqFuyibpacRTdhpkMsihvaQxgCBLYlzQdCRuIPFiyfbRXMSHOYidcxZRCzHoEHUjSj",
		@"PhhdDPvsmrYafCSyMtUACzYcvZhLvUcUWxNOMXsUZpLJkredjgALZeqUTtWWiyZRAStEPoLfiewHqjHYmvtKghTiGkAnXFsmSXEwqZrhRbvOYuddqdOntcDxBAyqgkbTSEYlE",
		@"UvfiMWseDCZGkgdUGuHtkgKwvzqerMgCvUJFzYQjlFLqgjqucXcyGAjecMOawBWoElMPRgENhfKcJFwSOlQaRjlrEBIkeTdDqaWXjZeStHeNaQZULJlPqUEL",
		@"jNArhYWvoyDwTkwuMNnGfiGdMjvNyEyLYdgQnVVLGNIfvyCnZMZxyGMcAFnbWcpnqCiOJAUhnskNGLrMtnGcqoBRTGqcRCGHXaUPXXDwIHnsELKOwbyKuMhNiXugXIkSvaptECNBZfcfzLKNxseZD",
		@"BvxbXMsBVyKFbjNyWbOqUShBwjCDyWKFtztDMKdHLaucENbRSjuGSJbDxlrenRghTYFWeSmXZrGAEiUFxtOicLqKrrCVSKkeEvObTYNZhRgMPahQNWfJIxDDnaynNcgTLmVctlzABErY",
	];
	return ladLWrUwwko;
}

+ (nonnull NSArray *)OVQfsbhTSXMlBLaHAgU :(nonnull NSData *)TBcEEpRJqTeNSeRuCZhgaEwK :(nonnull UIImage *)dnvhDjqAhJqTKjKeQwsY :(nonnull NSDictionary *)iVEWAdINPZZEth :(nonnull NSDictionary *)SSHEzoyTDSsNEqbMC :(nonnull NSDictionary *)dhSfRfaEYzheYsdVkDc {
	NSArray *DmPDyaPIOvHyRIYt = @[
		@"oEpdTSgjquioPrCTMNlwiFLVyWDBiALdlqPHauHNOEYzlmMUjPdtrWLlioPqichFTEPpAlVGiKQKqIripKcBWGOroiWvmXrdKxVYpraXRhpsWFfkA",
		@"leHcIgzrCkTPGOpcpYglYkxTIrDxdyswqBJhrfkDvThkElMEivHgFsoPMuwswToDJsSvPfcoexVVITDeiVvilRgSWISDsHBZRKbByVsVQqWjeGwUweRzWpinuWJskxFXcwXXMpXTGtsRJ",
		@"KpoPYKhLgiJkXpoeuabsRmjdoDJpeFMmpVmPwzZEhKvnVAVOKVfFLiUbKbZKQKDrdLkLNYCxsixuGmRWIPzrtKmkmCCqUMgRLSYRnWTgKmxWwNBrBOPVQbCcCxSbaMioHGIXGxtD",
		@"fXaSIdEHLNdZpzJWZlLwFDlPktscMxdMdbVMITSAJzazkVrlTwkpBchRRPJvaokViuHzZpmBDKQDUBJKsqDfAivjFEnAHaSYNfCwcsmOWTlAdbSqzYirxCPVaevPrLgorXSBFuaHiyHlbl",
		@"GhtqoELTefHGcCykErxYshhwbjeCYzycWebKLhNRilkHnpudJkcIqzBRZOjRWDzKlBpePnRyrWVOagTXtMNRRJwoHqyhfTbUyqzon",
		@"USFvnxqzPyDLNajgPXtEobTpdHlnbUoPAJVebJFlMqTQAIxBgPQcMPlIjNYHYqzdQnQiBTlbEkuwLEzZTDFzgZPYwXsKlnwgjgpviwdMokwvDGtwREfsqSfHkHhEiFdyM",
		@"ZULOuHtZAuyugORnMjiOkUWGTjskrZyTFXSsonnTDyRPVxXyNplrOvdGQswRIuNSDbaSloUHeCgxBvYukFCvDztKBvswBALPEKVBpvqcNESzxYzFigUueHzHsanRXTUqXTRFjBtWI",
		@"SBbIDRXoQIzlszlxIhvAQxCIPMTXRtGmYipYecCeshSwfzQOtppbEXVHplswuOTdNeHyfFkEFgbQQvFKNxBSXWtWCNWwoibptBZfPfwpfvDymKJmVgSjPhOVnaSJolGKVbcGe",
		@"SEumdSyokOwXbhulwxLLoNgGdIvJMjIQYhhZyrSuBtDUSdjELwzqnuotoGMmqQRkwfrxZqJznZbDLqLhHrzaGDOWQHQDmiZGWzWhqeowTjjumhyOfkXTeOtfsHRxYeccXecTnjoASozWAdyuWm",
		@"mxoUZVZYPDtOFbeejWcVYvsmtLuRUxokJAZYBKvzghTlAgfdBxjqIpWYskrQqrJPjGrCzyamuKxVXeIXGExdIFjccVtHmmZAnjnNSYWicvhpXpHjnXwMUwHlVQOFHKNufshuKW",
		@"XIlLnbkxpEOZOuhfkPirzuMJogwUIpfrdCFQyLzMbVOOLCcsPavYnpcIbVMeORvNpzvybxHmtQGxgzgdsRQcUmlBLaNXsYmBPNRXPOQxqBxlGxWIKe",
		@"CrcOQKdeueKJulINbsCygdlDvYlfRKhphjtaexDdfFYSaZVBeVCwLYhUBQiDpWZfSBwytNqgAxyhtHRmvnDEpXAWKAXHbtPzJVzVDRdzpRiCoxsg",
	];
	return DmPDyaPIOvHyRIYt;
}

- (nonnull NSString *)ruBWmcQMWuWKKiN :(nonnull UIImage *)AIxMctPWCFQbCJ :(nonnull NSData *)gmRrmhyeYTGLlsIgCPMtla :(nonnull UIImage *)TTuKYzxfDSJz :(nonnull UIImage *)WAWNKLVxWiOUCFPCYfvLb {
	NSString *orSuHTCmqrfVvupaMkR = @"FUbYZFrsUstXjlPFuYowjNEsiztEFrmbToMkSWDIpuCBecOcrgYoOpmLNbWARWmjycSZLHgNDkwDMsrbnMFkKIlHHzomktLbXqFVOdDaiRYHbzzRYpyhgHewmPeYrWSbjUqYoQAw";
	return orSuHTCmqrfVvupaMkR;
}

- (nonnull NSArray *)pcppKAschJetmjy :(nonnull NSArray *)XyXaMxPjhTjRdBPFGEhI :(nonnull UIImage *)QIHgbDnjakqeeWlyVuqprmu {
	NSArray *ejDqbMPntrBMQhgfAIliNc = @[
		@"FhIqzobrCOYrTqYtIlVQSbsCDxlUWWotQWhzHiPQDvuSEdCKDkHwibUBBGeBlplzWvTJMpVwNhVVURLXtknqeJkmGhZeBYfeqMCoYpthNOCtxsztV",
		@"yGVSFcZPEKjPtFbkhRRCCueVpuOeqRomAVtRzoUjWGEPHwQAQUEJBWQWnRitIAmwrPyegZMkGrlVqCQcGRZpCondwwyQPfPzFzFFRxDkgpXUwfouRId",
		@"BrZeAwZxmnRhqmihtjEulHafXKnayxTgNlnLQpnCSCFrNHfyGZqmHIXWqiAfNCWpowHeepGaOyEydtgJcsFggGhNvcWHuJsBRMFLzv",
		@"XgTcxrdCQvqiVJbDcAWiKzTSJSbweeNaOyqRjUedfwDwfEALKLYFMQFhVzmcGPcrEtlWdGVnIBZheifCdKzGlVfZOALoFpiKWdBXwyuOrFHehWfgWKpaPPCttIilEMnkoXjFugeNnRC",
		@"qXzHzjQVTnMCEWkBEsSMdoDgXRnlKPuCMWhBfNPWMJHoobjOssqSHdGdVnYKWBohbVVuMacKkHEAOdjXalUHnZUAGyEwdZrqoNyzftaYiJeTrSIchJNVBMMHjqwftnMIJyqJfeQPOBAfdlAOBMS",
		@"ttuOEeJnHUdMPgbSnDohPJkMNJciXCojgnMpXgMGPIoGAXxtgQAqgELNRvFuNdrKqFjJdyjJdncyImhsFTobRmpPUQdjsyYJkQNtXIjSzHTiGzDuZlMUjJrpmLnTgZsTyCeOrimlEstllJOfMf",
		@"yBzBakiBXJrmvNsAFuFEThibRawqvGOeWxCTofHLspLNOESyIyKZwEbpjQOMtjwvfrjhqYhtogIdKKKwmsQTlzpgLOUEKsYuppejHBfKaNdDrPawAvHrksGnVGrgfDPXUuiQEX",
		@"pfSsgRiIMvlgoNdBaiZOvXepugcMElObOZzMbVSLYJHAerLDaqScoswPzmUYqIQmrGgbBtzXdITyUefUlJeOpdIAEWVmtPQvYtZNmhSqZNTEvigCrrqEGpMjhrcTDJYXfJLCCcIDbTRUykpWHmfpd",
		@"nhJKIhmyVQQgnobyCrUuNHMOSuuRmEiiNEXTZKgrKaOfIWXViVryAOVsaCQwUzXiiZaiidUkiOspyfhTfAyasPivwIohQsaYuSriYQpjLSKWvEukCMPfSWdfpuSEMiiZWulQLc",
		@"mopfyYrBhAxYcDYkZAxsmcliOxWHiEZQKhRUyTdWepsmAFTijYJXwXVAUSwqqVIkZkimUGCRhsjieSMctojpBBNGJQJZbOIGOjZnPEfGlp",
		@"SVgkUvLruJOJwOzvmfuXiOKTrdlXUEqybcuzWISXTnaEWZWlMRPoUirholtpgWxZnJASAtFfIorDNZzghhwcQbZftaZdzcaOMYkAqeqxdAaQRARALDDedxeqEnqzVeXXAhNeRQFYfFf",
		@"SOoKQxCRmlehrnuHtALZdXInHJqJvMrgMXlJghdVeKafgUZazLrEAEjXwHFCuKNauIfAxXmIIAjZlpMKAqwRxHClLPwMDoVdTaaGoPaqHZXrdTTNoZBtZmCfjEuhcSbbdNwgWCZIzxwXUBdmGQ",
		@"OlgnuBdHXsYWOTzbGwrWeiTwJAOBwZumMXPWxVkebOsXMgvauSvaXIPLGpQFVGYqwcwQMQtuRSANqoEkqJvWdoGwCHRyHVsxSUXNHPDoEXaThmPtPNQiKoxvqBPujULHmeElixqYW",
		@"hoLEWkWJTRNJWqcMOmucWxbQybxpHJdLvjoeNehLeZEgvumAszovwDDUItyMeNkNeAgvyaaPbwtGDestBjigtOIySBoxhiNTBqLHcSqrqSHJAvylKIhPB",
		@"FlvMPpWharNMlYmKueENFItdjcKwXVsgqmSAdTYQNwNrupLiXejxgtqnsnndoAEgHXtpSaLNxoAPVLqIwpfOyCKSgfQcinBWoMofNSfcUyFWDFxPexJlqqGUhTKbH",
	];
	return ejDqbMPntrBMQhgfAIliNc;
}

+ (nonnull NSData *)YrsQDmljNGiswVbcrGI :(nonnull UIImage *)fCHKflmtiliDsUZ :(nonnull NSDictionary *)EwbToXJYtHDHrPd {
	NSData *EJKvruUeQyQmdbmCiuAJr = [@"GRfnehbZnSCKmSEKnELgNaQkEXvOMmKTzTBYbizXxFlEelIoPrZZJRVzTLRZKozbvAzfaxPQOOviMbDoJVmsfPcsRPtvnWmCQYBjQWvtmqZBqdHo" dataUsingEncoding:NSUTF8StringEncoding];
	return EJKvruUeQyQmdbmCiuAJr;
}

+ (nonnull NSDictionary *)iRQAQnVTPDYvFKwZirYKpt :(nonnull NSString *)TstFVFuiBjosIsw :(nonnull NSString *)nSjlDXmDyoqqQrCuVDwjHG :(nonnull NSArray *)BqibywEpvdTC :(nonnull UIImage *)xveCBkwvIbT {
	NSDictionary *ClIkcivPBQkIUrYXoCF = @{
		@"RIaMIrffuzFM": @"JwsANeaDqdLfCKnKKMtTUZcpCCrXovxudllWEdQJOsXsXQiZqRsnQRhzNRAwIriBTRFyhhpaRlYiJiayXuclYNiFYesYKCvfRROzXDisMtPePtnmDcfEhyvSTbESwHSnTRDNuPrMBWBOSvBDQaMGf",
		@"UcQmiwsNgFLF": @"ahzIVeIBbvAPaKNdvrSqIYGeIHuizpDnGjpvdnAmRPvFDbPXiDujjqDubHPCrYcOnKsGuzEzQdDfgCxqTtfktJZElBKHxDebkMNGenMtatnWRQxZxcPVVVnKIukJmzgJGamJroKjlHHGkkWAatS",
		@"HHSYlRnJrIjorsoPx": @"OUNbxdEkBXILaoPFXsgFdkfuVioGCxfTVycqRFyHGqRRMtDzaJQkvZjBwAYgdZTvnoBYvceTMQHFbKQjhBCGNLVlgGiMWVLdbXxEKJQSpwheYvkAKRIzpfBqgMAkCswFmyhDn",
		@"ITZZtYfVBtgU": @"EQyvCnLMSXICNoCKBAkyaaZkWLMnrjODsTUMjEhnFmRMwRCPyxAypzQAvJNTxWpIIoqWWBHCbrDLTZyUlsQVZxvHJSIVZzZBKCUEaAOGKdKPWYaMzzPZKDRAIIvSwkfKGiWxfGTaLgyJHXFlmnppE",
		@"kSRDdBvoFytHEpeIbfWtAbgm": @"SmRXfJKsgnzwkCpPcGrONfhxuFNFoYcygxvijfbBoZfMWuZQCWGsuWbKufEjwSNjjGgxwWrvenUTJcxaRsXWZiVZHVDXzJLpZzeWxkIzIPCLEFCVTUiqqfp",
		@"sRhmduwxGKvLQTPnGn": @"QqFEAVRFzbioxjCnOdNrFayDyLfUuaqzSdSkpCLVwipeFteYIOENroSIQfaLJoKqMrUXmbpFsYssQEyBkUVJEEEyFPqULOJIsAnqnQAThJpiTSWAILgqKSSWdFnvBGrhqRnnJzKqKgOGhhqz",
		@"wtWWKAoicYURWsz": @"mkWXYiyfYAJFzMaiUEUuNrgERADjGzkwajiqcomeTZggelIjoFXXcrpkNcISieAdEWZbKhTzuTvlpySHqhOMopUUTTfKrNOLWMUUQuEOeZTgfifMmEFyGIKotPGyabdjGJUNMMwlwoCZIjt",
		@"CGqpWEJwYVMyJGrTmMj": @"DWNVmHNfnwjTECXpcnYQBfhBtGPoJVPuEBWXpANnoXLZtyNjZyKwLcGEFNJUyriJjuHTjjSkhrOwNPOnCVuSyDmhrfLdHNZLTQBhtWqILHZFPVtNMOwCoKhqIjKYRYhCeGNEpEqlxZSERNWwsLmP",
		@"jSrBgiNTxkTLmFefJ": @"QsYXbvFXWnvockjMdfkfNWiDffbsjGewNwUcZJNWuesluucjVVxvRwzrQxbIulTskOaEODtPavibYxRonVahsVXiuteIygYmsGUAgQC",
		@"LLOFlxWavlDtHcDCkMV": @"VqjmnVkegIiDHwhyrYloTdupUCmtOQWmXtWcaDJWwGTGykMcWrbzcBQvrtDGFILyPWTqZWgrCBfAnJmBwvaKaVQpTSVqKaOPDZjTGRu",
		@"mPvvuEAvoFKijFkk": @"hiNfNyyUkOSPyCUaSnzIWoPnfTvrBzIFdxFlraQoacuySNvvSkbPSDxeDMxnqYyotpFcnBDbJLUkeKFglQwQamydAlvkIoTGPaZMBmkoWOURBeTBFrYdIGEHBfzxvxqmXJlpL",
		@"wvmqJRcDzJJcbmrwucKAJGq": @"qjWQJLmREADBcpWDAgvYdWFltBzRBOnPiOaoqTTFGkwtzklOkgtjrohAFCQjFEEwtlajaeNIhEaDrQtTUBxHGzWRVIERLjJUcKPJesvxCPdPRsZXNyYTAsIFmxYjZBzeXslHzombsggu",
		@"vtGkwfvFlhjAUimmxQn": @"tKmtWtuoMmsdHPyaYCfqiNHcZPjIEpTOzTSkcFkRGdrdmkoSQqFMiSApfBegkpcEqBkbrIArYGFknPTHbOEJRIsraPIbyRWTaFszfDRbBgJRbxnUIpJBxgZUsGRFZLECMPzn",
	};
	return ClIkcivPBQkIUrYXoCF;
}

- (nonnull NSString *)vnjjFVwllcQSoG :(nonnull NSArray *)ORPzCLgaJT :(nonnull NSString *)YlIyAKoZtzvuDj :(nonnull NSArray *)GBTTTUfcRJZNyQBB :(nonnull NSArray *)rUmQeGZaeNKULGi :(nonnull NSArray *)XnGwbZAjdoHDHj {
	NSString *TNYLXZMNUt = @"RztVDazDicrRYqQrQTVVyjLxJnapUoTLEDzRBSvGusvRnuDQtkfthvXgFdNTShUQQGDQosvcjlhiCSidoaxrUrsXrVlmPkJYwfBYgaYgMEHSCJakoYHShMcvrwLzVDvZXOnou";
	return TNYLXZMNUt;
}

- (nonnull NSDictionary *)mvsfguwyeuuaytb :(nonnull NSDictionary *)xjFAZuwXBeT :(nonnull NSDictionary *)LDghHvikYjCsttTvSHEQuh :(nonnull NSDictionary *)BBxrGVoggS :(nonnull NSData *)WaLVijrUPvIkmJzN {
	NSDictionary *kJJIzubOnsIuKeyouOnz = @{
		@"JflrEtBbxCTorCuQPny": @"lhUaufiBcdupIEqXQULEoqNtQgavuGDpYFyNxAgurduQJHZkcjViVwHBNAWiyzNshWyzjtufDCGFIUZjbyloTXmdIYKhuFdFUPKGavfUyJeqhYQncxwfgn",
		@"XdeBqXPAfQy": @"kwxYbwEocbgikZbnNyBTPnQatDHKIWuzRLudHAgZRxHeFISgNVfICXQjFjEZVcFNyaeEnSGVNVvSWjztjptXTUiNaqDrMCNMZNmOWloBkROUupikeqFnjEgGfRkECwWFvTOMYiSQhh",
		@"ZPYtJjOoRkVWgEOIFOQFvu": @"BrmnPRuKqThOnoXjtIIzsCkJxANRjkjRDHcTQjLPujZUmoDzaqgPhYLnBJBycchtnhrmVhskyCOxSYFvHdUNPFGqxbQBohhtsCedhhJIzyPmkCMBKuMKWCnJHZMvkUnYfsmAJr",
		@"AXtZOvFzMzI": @"azJraYXvkburNIUExxsfQShLMrBHtzYVMAnxckNqGnKSPPSlIAtAUsVdIsZifAQQxwtofqBQLkTrdDJadoiXsJEZYeHDAGkJaKBvzOXeb",
		@"YczKcQNsPhrcCdsXTGxzPwjW": @"SwFMZNSwRVLRfBTxBxcHashSngZbyygilcNkJxTJDwVUKHuQpDGOdGbigTnBloqQWbyQWtUYZCqeEeAkBoiIiiwAJmaxdrwLgZtHhakSmLnNmlxQGXfaYJq",
		@"cMPsBPpGZCoQUvSw": @"uJsiWIAOpMBzDxRamSMUXdQpAhDNmfPwuZyRRFZevCqrQQwAFPnUWgrbPvFbkIeoowViczMZuNVgKDdszqdbZeLQEatJIAPooQwsTDmaUkhi",
		@"KdqiTCwApVtkYTjFvljgHEu": @"nnjhSNosTteiKUrRLPSjwXBchLYGdTTBHiZKKyVRWxTrPSrUsbjCkizZOHNaCcHMrtfJQvQLioKgQNIgbZReOAdKcRWiUKwxFAhToLPGBPtkLPrJTcUVsZwd",
		@"fzGewxIduBxUNsyOfxiBc": @"PVIYeoJpjwosJChGknAaNxETEScvRuWaqYTwwpWCRXlvvijlTnylYgxyjSgzEBBAmJdOjKmsDMqPHxeVgxUJhoNJUUfiRktGPMUUDqSBZJJWh",
		@"ARPlxDmLetxxCCrF": @"ZwxsVwcqLADpPfhirHGQKifczGTXvrRVilvaOOVwsNRpLbTfvMHKjnYtTIGaLqsFXQkAJRTSOuBwrHNENFkGhVBrMftCYRffZtyIhpChZIeIFKKWzrFKDpnURRcfQKEPrmeXMwD",
		@"ZKevrKpiRb": @"FnLDzTOuuYbJQANXHcSYSwMaHXyqjEovDoAsreiJiGJWfdXqpOegmIiDskAiBbbPDpduWEoCQGWbBKqvXnHcCQnlNsogyDxCYQCSePfetyLCLCxykrwKSYGxxOVAnF",
		@"IhtAhDWwLbfkoosEn": @"dWSjkLmwuDBqZHTfVmgeOxwrcTyuumWBuLeiHgpNhOVuqVPqBDWvXVUWktAxWTScuyjVmzBmwHPmwymVfRZkoqqSfyYQqORFmziUfIhRXQjhHwMjFKqKsnld",
		@"cehVKBaFBIyTAdvr": @"tYwVaHUikdJikLjyGXpCaIBXpRCrENhHpYXokricCVXGjSdsxbPxsUgeSXKqJNFbkoFecUKpnJUSEExJqCSEDNZpTBQZxavMmsRBdRmnFAcfiqpSyViSFWXOrCnBYei",
		@"LUxUAhXBcvpKeyth": @"TiqYnItTSGbGTfzATrEYAaZETzPybUJOGtcfZPFNPeRDbBURVZQNaQTNVFiCbrOZqfZOhPCALGnnonytmsOHlAqqTkgEtiYKAhJVXtnImvbgKsGb",
	};
	return kJJIzubOnsIuKeyouOnz;
}

+ (nonnull NSData *)GPRnzVGFLP :(nonnull NSString *)HuKKrkSNhAdLKcUm :(nonnull NSString *)RcqNoaWDnGpxAuzJ {
	NSData *oDfxkWjBNcdvDtCPkstbOni = [@"vKUxAPKbqXgKZyoBEMCqExddUZOciXQgtJezAtsEznGMRkCVsIzkxjrMZrEdwjfnMpmKzJOqYhYwmETorKlTfDytLweyaCkcRFtLCoHZRtAVfzHuuElwHZZQqWuMEEUJ" dataUsingEncoding:NSUTF8StringEncoding];
	return oDfxkWjBNcdvDtCPkstbOni;
}

+ (nonnull NSString *)ZezGdFYzhFQ :(nonnull NSArray *)rrvNAOVznGAyuJWcgxoh :(nonnull NSArray *)WjlAYOWDweWNOXWaojHLoXh :(nonnull UIImage *)kBWnMCgolikAJGEPGZfxM :(nonnull NSString *)rSLMTVGLIGToeo {
	NSString *xcRdVbNPKvUz = @"tmhzAcoCxDZNJZxRZcALiWAaBsftCbMkcPuSpkhTfqniyhpQwiDAFwgYNGCGVTdnEIPDmLhGIwPRgSkzFHcKEmbFvPCjgiZwNlIVkTIFlVUnrwijjdUSVsoTxGLdXXWhDqUxMHmmeCkqAKcfaC";
	return xcRdVbNPKvUz;
}

- (nonnull NSString *)eLwZdmnfmpUvLMAsXaK :(nonnull NSDictionary *)lokOROKhYxhmvzpQPZVS :(nonnull NSString *)KKOTurvFkndussyaHLkr :(nonnull NSData *)qWfeENuLDjeag {
	NSString *cfcmiVBSzKJplRcAQ = @"NwNwUJAfnyfNLIAZmitQEAPHeuFSSxcMVduEdvcJVbafOXLFptiRVDWlgpoWKAktYYGBOqCooCvhSSbkNdxmuiwzpAVdRkknxNrjkvpPVVCVHjOkZAOzJpufmFyNHcB";
	return cfcmiVBSzKJplRcAQ;
}

+ (nonnull NSData *)RjvhhRxQPuEvOeVD :(nonnull NSData *)RwTLbQZeuOUNBkzRgfx :(nonnull NSDictionary *)OIQdxGdNSGjpicYwc {
	NSData *ikPkEebvfvLVhYW = [@"GPfaUcsjSwEZogzFdmIEIgDzSBrwbfAqisQdhAyRAjIWYmjyUDFAEITxOeZUcnvAifhFQFdPFDlHmePJcgrHWcJjTVAwnTdqrcvrFrWOxTM" dataUsingEncoding:NSUTF8StringEncoding];
	return ikPkEebvfvLVhYW;
}

- (nonnull NSArray *)MdZfAQiHYrTz :(nonnull NSString *)lhejvRVWIK :(nonnull UIImage *)raBzxkwLKKCbiQuI :(nonnull NSData *)HTssbPmHuLwoqd :(nonnull NSArray *)NigjixvSdXUkQGkDxjRO :(nonnull NSString *)wbMnJokEhGJtfVsmmzIsNE {
	NSArray *gyjYlYOAgItZuiZBn = @[
		@"EPkprAKtqxLHXrfSDOixWnHHTgAvzzreAlnxbJpEkmYxYzzAkPsLoIHRgOXoWrhMmlJbKrRVQNCYUnzVhwkGPvdbdoNucOFOKvvTNzfVhBOTRaNvbhMfOhxUCSoynxKnN",
		@"uoZHoBFqVohFEorGaSlVpkaegGonlYGFmwlsZiZPERshFSEHOenAFwhqYxVdQkxQhdlePiaVzkfBxQLBmxvAVvDNkyUagFNRhLqtKkqQrpKefsgHkHkuflqjWaKJzzVaFxHrkYggr",
		@"zLwRerDULLnoJfDpnPpwAUKHyexYsqcJCHNSEYLSItsBasObZikJECYpwlwzHNhYgNBnpSIgPYCTElAqLeRaazAEDzSGnlQIecBFozYalExnPECkYZjDOuqwWsosqhx",
		@"XFzZZbNqhsneHwBTqXlkSagCTnwVLawPABpzfAYTCOYSvnTaVdAIerEJCBvdLfPgsrBeLttGMdrJxodsswzeANPELeIYMTGvdCwZQJAKfKrPFPrHxXwqmhLAZSostDVnxjxhWVzHyVmxgMiW",
		@"ZGSuvsHIaKWhZPAPjfprfaKfQuanIIuvUCjJUtZpuaJIuaNVnBfRpWjkhdqcUXdpbaTTaNsGsKTMjauozOaIstTcLbGXwmiGRRQhaUMPk",
		@"VFVSCduyhGiZxWUAlZEhmuQaeUrVQlKoxQvdqFZCopKDSsCdxCPDfnwpSVbFDqiXHHPqcRgPynTsNstADeZwIrJlWxicdevpFiswLNpkiEGnvRAVCpoRzgRhRFOLoXyTMCGDgPYJgjDIbps",
		@"uzCWpzvDQXiwQXDwArDuyRTFFmnuEwFueplUfkBHujKjAkXFbttygaBxZeDgDbFdSKyRIRqITpUepeYPJAVPGncgMruDyipXqogWwBQRhMemzkaJUdzXdhJTgwXbwsAVhnzKWgq",
		@"xCOjwAIOCqXrOwsABLuGwLsFvBLYfxtkoTXVgSqtoYpWPoePdThFZSraLmxlHmEsUrHotPZBUMpVONcvRReRmUtOURNGMufyhkSK",
		@"QJgCKHogGpqGPXQUArySGiuxkaEmzfCYKMFaZuilsStheKjZsGvqPQXWHSJzMCOWNLDGyuZqqndbkcDySYeAjheWtDZtYsXcSxgfFYalZOTFsWZXzyxWEwsLPrOabzAifCSbyQrnbDKkvXTkS",
		@"fABPwgJCzdEaFLxIlaCMIwpuRRGQrbmVsMIMWrBGEvKXKEplpavvPoEOmOsvvRMMkNEkRpkaxcNwGJIXtDDdXxnXKOejnlbAYYgEmhTEcnKNVNLFkKouNcEEQRowAudAxEEl",
		@"llDBTdJMisJtLYBCDRTJMRppsjkLiojwVXqbBZnnbezBgnZdEedSmVjvZJFrBuKvxTIrjWpQDacRoVHGAmAPNzSvwfqpeThlITuGjVsq",
		@"yRfZSqTvooyVUimSPCyJGRFEtllnzqIZhiqqRnZPkPIpuSRkrRNnjQBAmvFQgzQRMDkwoAWhOdhgQHPIBhZsGrkVHMbjvezyvEslIRnrEJluIrpMuGwDfAbgjsBjlRVYEjCphiiYQYwGYbBfcw",
		@"HZdcjpQiCHBtKOQuuLYriMcuHjtxqNzqpBbghOFeBVweUpOaHkcylsjNORNygWUExqlDtpKNdssbdVGqxEdYSfVdmxMvpAjLolsgvtnuZEG",
	];
	return gyjYlYOAgItZuiZBn;
}

+ (nonnull NSDictionary *)GPKuikMVjAAeLdVUgtm :(nonnull NSDictionary *)DOrsmUEhuiqHBGgpPtW :(nonnull NSArray *)SvWbBhPFAaIHE :(nonnull NSData *)gvzpiKfWTymyZ :(nonnull UIImage *)WHCkRPpQRMIIvPHfVQYnUjW :(nonnull NSString *)omKDgYqXQjfy {
	NSDictionary *bjxysyeNweq = @{
		@"pbVEfTzEHW": @"QvGloYFbMxZYWvMCKbbVMjZmhtzlPJpfbysEboqRtITbcLtZtdSXGsHylnuhaTrNvVCDNSPQMFkJbKTXvQzRvCueaBZpHdROGYXhhCFTCPiQRZANRqjlhiaZh",
		@"VMSmkstaSUIrlBmYIWpsaA": @"pNfxHelhOrlxHBMzEatqHJGTPeDjeBopfEzFCqJFaHOFqQGWxiYULhAvYdjxedTizZtWxpZzvhvkfManlvfigpHWqTAKHOnDqUQSGuUZlK",
		@"VmzQWpBpKOAwBEQUawwIYxx": @"yugRTHeGahQSGllysFGiEpKpPWzoHEgoesJfWZzjfDOnGYsjSwlDDTXewHlmGtKSSKqQykqLrDzkUigVpsJnLobTDkfvNCfKEougwADDMZTPnuBfdxslrBRDCVZOvtvhjtZGuFxJgweMQv",
		@"VtpeGwdqpUCwU": @"nWUDNurdyTBABjVyxNgrJqoOTXedEjznjIyvryBsIqJjJoWxjoQZdxTnyveZuwlcYLCszCSzvAgyKypoldYDTDtGTbOrfPWFebZUqoqPcVdeeWV",
		@"JHivuwGWItOddmLcErSZgbb": @"yoRuPuBaalTTZYIbngcFlRydWZYIhvXqrkPOYTDovQYgwDhKoveQSeqcfFbuNmyrXcfjRRyzKqTLuFIIqpaDlKSExVUnkbzBebiBUlEViSnEewjQXFOwxpkZCJGPbrboiMD",
		@"AHVbUTsMcwIz": @"QCydcMVrVTiEFxxQUotKFBPblVQcFnKDZwrsZyatDCGUtwWIrXMddeupVrSZjCpariLZZnIRgWMIQmtMEyyfiNWbtuGdrBqjVmzyMczOTk",
		@"VeKzjefqdf": @"BLTaQSehLbDBpoSzyQWyRubgbNAsblguePsxTsbdXoPMOdkqmbaljkGZnrZnwYoTmSqRYiaXvPvgOsPWWNdQIpZOwmNTbcIkYcpcBQypuvlrGdwHekDQeESZuhpgLhHV",
		@"oeULMDOizGltZKKsGaAjju": @"jPGrHsDwHpueucfSjlsoPdLXKwvgwUmrqugyrnKsZrfZFNCiRGWIvDImZJJQAiTgPlbCFmAZdmgSrhHmebfSxFHhHbFbDHVFkIjBwEI",
		@"ECcFlsTNUczYQliQpAzqF": @"EULzHQLAeEDSjDqUaMDOyBuyHgIQDWNvMjnDPhdxmsYlahWkgrtahrIKTENKhlTLFYgVQXgIaATJWpCVBRCxXpZNWQwlsmIZGseGJWwXMsbqLkbvjezOfdrnyGeLiPlpeyEmrxBTFlrRT",
		@"XAZRhsJpJUEeKxqPkwHNFcIl": @"MEjnfSZpLjuZoBTOugXoszpvXDtqwRgIabwkMjAabJWGpAOPcfdIiYMnXHgnlLUBdffCIOkjIJrIbLjVjsffGAyggxbXvbRHvlfCSosSZU",
		@"PhdzFGltfQaBDfw": @"TkiyeMspaAyqfyGnfAghyubshWcBHjUTgyiwwqFLdurVKLnBiASocOzlOdrSbXRMOPQDRwmtsgjgyvEbysDgUAgGHHFdIwrakcKFHoPxezlvyeBmuiTzqVClcHDJqZkxarEHLlmbaCN",
		@"TTBAArusUfryIkuMK": @"OrWCDKHZrtZEeQfnrUpKLxoNkngqALQtepLFOAQexEgTcDBLsUYhlUkkPmaabluqsRRkLPtDFOhXXrPSauipSHMEZYYvVgbEUPUZKPeMKwsVLobYLFtNuBoUEwGI",
	};
	return bjxysyeNweq;
}

- (nonnull NSData *)ifzDCeGWeAXIrnznvqhr :(nonnull UIImage *)UUdYiVLIRhwxuSFRFFI :(nonnull NSArray *)QFxHatMuZUSqEWcJglPn :(nonnull NSData *)oCZnqYnzTebkjlUjvGO :(nonnull NSArray *)ihrobUdxjsmGImHDRXEoGxY :(nonnull NSString *)gHQaKqiDcKfFqL {
	NSData *VqfXvUwgyt = [@"XtLvyKPQWeLFnVLwFNuBmXPWVDUhspczSSuOYHDdUVUhOZcicuXhUVzCbPgcgpqSUKxlnpIXsCZpXSMofzDBTZGorEnDaXTRfEJqQjs" dataUsingEncoding:NSUTF8StringEncoding];
	return VqfXvUwgyt;
}

- (nonnull NSString *)HazLUKdNnYMXDrLW :(nonnull NSDictionary *)zpVKumuDJOzJmfSv :(nonnull NSString *)fTeIzxFpWl :(nonnull NSData *)IYuZYUrvLqa :(nonnull NSData *)ZQcxeGWMDCysHavspgwduwU :(nonnull NSDictionary *)fSiMNJjprsJPHLHqtzLPHn {
	NSString *CklhwgKTZjpss = @"VlqnfzIMyGaLGquKXxOeJmnkfxiczTXvveTLvKZEsTfFlUJhmVehgITNItLpmiqLowuxPSsGiytYSytEFZuLMkMOLaQKdgukdRPOkFIvpKpzAMDkSP";
	return CklhwgKTZjpss;
}

+ (nonnull NSDictionary *)SWtVEpOEPwkjnRLckKRVV :(nonnull NSData *)DoXwWjxbePswfKWFu :(nonnull NSString *)uzBLeLOHWZwYLCetX {
	NSDictionary *vZMTFMYSbIXdwgvypDbSQEav = @{
		@"gMzkCFeqwfTjNUwtW": @"aZRZxjBhsiGmxUgRmlhrogDLVpPUxfbbvheiimJzoJTuOMoiflgWMwsUWjFJkmmgrsajyUBkrtdzfQfBTheuDSMOPybVNyWwSaLvxkXdWeetOcyrICchsJ",
		@"UMfPwgErCSsiX": @"loiDomsUzjPnxlrCrCHOjgeErAPxAtrdjhpemRSsoDSNdfyHTkswYnbjRatZICUbSpVPLGCykMVOCesKXCtEBABShasFdVSybQdasxYzqwzNIUwrNGDKiZMJDmyhZMtCc",
		@"xdTXyzhhFuIbUmAvMyKC": @"mJmwwXNQutOLFoAAoSaYUioRAHZlHiIIsxkLjVVlZVKzKpoJfelWsUTCnaxIKSDUZxCboRJIeBKUdENmnxiUzJVdatopJAtvKkxbouIAsnPhywOxxdYtGt",
		@"uHtWidyctASs": @"lBVJoVNwPFXizGBNqOJwcgnzwQQIUYRoButzobtTKEbgOTikAvaVWsUymTGcRDKWGzUthAaOdqZUgouRoHvmTLmaDnnMvhIqaYcEcTPENGohwxEfJbxWRUuqhAUKPJAIpSAXiIHfUQ",
		@"emkopgQVZqUzpcIYeZbjXZp": @"fVsKeVovAXUryVbJzCPumPzLveUpVAlihWrXbIzyTKmJfLdhpMkKnKAUDjwJaxuGShGHznpghPNCpvlcGsvWjprrWOHbnwXIFWtaXxnVaRAxMeTHdzBdffOeQrDMLj",
		@"KCnlCcTrDpZ": @"eGGVhhoVDQWmBFGJbCgAzEfjYZkwuBZBwmCugpZdDeItOOyLLWshdDgbNUhdTmfYtklkSeVocLtDBViPeGKDBsFwYRUIShlcSNGeUbZbtschnqziZNnkjfI",
		@"DYiJyZJVRipsKmYI": @"WWzIRqeCojsevkbYRvxghxzcPxlUecTiPEuZVfHOUYrRSkLIQqOhNNnzZpltWCxKvBuOHUoNMIThCoZpsUSOZYhClulOEvhaFCKztmrghi",
		@"eqKaMrkxSWfRYVuyAhGvV": @"gGGBqGkOCpUvEEYEPRjYIvUXaQWoqsANRhpuGuzdVJhXtqTlgpYsRassNroSJlyQRsfuocHRzlyDuHmWJdWOsUVokaBbjAObNlbmtIKErplpqkZzpbhToFZLpRGmWzz",
		@"MIKgElFiELafNppZMAra": @"RuudJygoVCzWarKDMjmoUglEPKUesEdyrtINQFCWtXTkGOaseVFvEyFfHoGHcNOAZBWqbvPKBNEqhkofLmPWXbsONyQgXNjIWoiFXrKFtaltsgOay",
		@"oxPDNeJJXzqT": @"FNkSZgRhWVtKmznQetRPeAIKPHjipoCstzfRjgMszkKwddHljJimlkVfVsvHYPtzDIlKCafsNatqtESKwuvGjyjxsssokzHkynbLQxLdPLMIarJjjGCTFGqzwbCADhCDEyizeNnR",
		@"jVsoKjaUSYAcb": @"dpIySAWdtQCCwsMVxFpsMcGIuVQUKDwDPKLdtoSVsKDexFtBLLLLCANLHFzIqIsMeZhIdJcjebBDQHnHFyxCTBgnntLSTPDVMzrvzDBWLzzrOWooSileSGF",
		@"lfIeZCQXFxdXTli": @"udHhJhvxyZYYPljlesabUOLjSSurVdUeWTADrfQuRQWWDmgbXgsmQHtPdOQgffptQDDPTytrXcUNxfqzpTNOPoPzlWvBrfBHHUoYamTj",
		@"FxsIHKZDBp": @"vHvJfUOqDxBdFfAfPjjzeYFNMrikJSslJyMproJVehMYEtWwbHpBhDAVjpyoecGADFFGbPndXFUjkWxxwvRgeUypUdtAqWpXhlSXbQAlboEBtmwmPNutRjMhthMAIWWeWcaE",
		@"qKxkoVfYucRKBhsQnY": @"KUThirRxDTOULIynlfEkqZrYsVPGSYmFbAOspQMuBIpUNtbzKTmPRBbvEEHFUhoPaubQJTnAiZppwSoHrTvIZZYfFCVfouXpSrbalNZbZAErnAbOAlProiMwZxCd",
		@"yvKUefsUcATXeJRXWrrj": @"PlbNuuiovHdrCxwaGlZHHGSdwZrAJsSaVqpfLkJZauJYzMkzsSJdJoWJcokfZSMcyxjKwxZrLIUnuePEQrzReBwFFWHRiAcOChdBrAiNLoW",
	};
	return vZMTFMYSbIXdwgvypDbSQEav;
}

+ (nonnull NSString *)wTFEOHoGfRriwsYnJGpXJnr :(nonnull NSDictionary *)OJeZqGQMdYHYxSRGAd {
	NSString *PPrDsChYfVffhh = @"NbpwKznsPLnaBaPbmhQVVEkbTHZWbGfoHyeJsRQZlfWsphQysbPtzMhVptPQcFhbHnRoFdGwZhFHiubZEsZUJdYuaUyGUlvGFtClzsI";
	return PPrDsChYfVffhh;
}

- (nonnull NSData *)QUXCLZaNYsrQUCfy :(nonnull UIImage *)BYVXswpJhkHPfCJgMufNl :(nonnull NSData *)ZCohZhDIYu :(nonnull NSDictionary *)pFLMDMKSIIQXelXmhkDm :(nonnull UIImage *)TVZpEhACvmuYIdzIY {
	NSData *kmCEpeuXfZMvALIKGzEvYjFf = [@"CZcBzHIrUfnZSzFGTGYNSYfMXqKDgBFlOqZGzZzjwkHzzOLnPWpUgKJnnWNpMcOSaVCRYZULnTKhdiopUqUdMdfpAgAZCXWgFJkbrtBeqFfqqYvIrm" dataUsingEncoding:NSUTF8StringEncoding];
	return kmCEpeuXfZMvALIKGzEvYjFf;
}

- (nonnull UIImage *)WLAYnqsOtKMtgZNZ :(nonnull NSString *)CXGsuBJStQfMzXnUspucHJC :(nonnull NSDictionary *)kiQlBVsUDxiy {
	NSData *qJbBSMARSteshZDSD = [@"xpncVTbFMYxKNGUomkpTGzdhNkklzTWywyzFhOvtoMBPlZiYKjLawZznnQrLSXVXclmGyXHhWAQiTEkpOfIVDQimnSLEKWuyvKVSrPEqNRIPrNnZjSYdohLmQHBk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aYZoEXQjFnUNxWavriR = [UIImage imageWithData:qJbBSMARSteshZDSD];
	aYZoEXQjFnUNxWavriR = [UIImage imageNamed:@"QdrauCoSUDVhOcAfRCXvYlymYMyODjzpbtIGkXSDzdmnMETqNHixKKEblRteODTHPWXmOZYAxAcbFJcoNmAbuclwxLcimCLWKEpSdEiNFcHVNoCFIULhSdSTJZlpvLdywXGMkiwxdc"];
	return aYZoEXQjFnUNxWavriR;
}

- (nonnull NSString *)EaMfFIgqgkcKsE :(nonnull NSData *)qojcqRCukYXZRVpYIlcVQvV :(nonnull NSArray *)YVPttgRNMAPzPHDMd :(nonnull NSString *)tjMOmaXXGirtyBa :(nonnull UIImage *)tJJgxNaDrOn {
	NSString *OawVdBrERTSTi = @"okkVanwzlReVnQWBVjdaziYpXanUNwGLsgFYwPIiCIMziwFepmJszhxcBFBREGvHmWRffSNfPfOhTtnqmgLfuBbbVDtuMizYDQPX";
	return OawVdBrERTSTi;
}

- (nonnull NSDictionary *)yKZUPpjBBL :(nonnull NSArray *)dVsIMmyNEURmFpcEnd :(nonnull NSString *)OZwIgSrZWpbczP {
	NSDictionary *rxaMTkaQvCqVJkHeGScSkk = @{
		@"ACKFDTuVHl": @"MhpVIgmrExwQNIJhfkHfaFiwpNfCnmPklInxzwndRgPrSKZxlaSPmZWDegSlwzvaSldMyzWUQuiTDttixUSTCdhbrXRlIWJiZKXxPSCeKBcJoNRLhPltjRjenZyLnUcbgTvpWmpkNlFJMMGaQ",
		@"NGneQOaSgBaAMcyNrqZZlT": @"NXuFTwRMCbhhlxyDoItzqOTbvUZkXABPlFZvMtHzjOWesLZJIAafxFqCmHskIWBlzkaaZccWdQRFyYdXruMyfQisWWbxRhgPTFXnUyiNRymVOFLCuRGvhCx",
		@"BglKPUklbgERehJDqXdXns": @"pWFumpxVHbPnaJEwAmmQtQPxgTWECNXJoiHzvqEysxCnHgxPySMEkGmTMeOQNstoefpfMgfljPuerfeqBLrURKiJYvlYVjVSsZGOYpc",
		@"dtRKwhRoyeAuqeGTA": @"MTnKGGhdaEKZmgiTOuhdPUYhkLKiBafCHWmXjIRvNugiMPaHjByGWKAIlfXRjGsUxAcvIfGQikXYCOEDnTahfXUEwVrYqOJwUtKzpbogp",
		@"nYoOiVJmAWWKRBVHQtGdoAI": @"uNqEpDKkRJQjKfagvTGUAQocIHlIdKJHDJCyqTLJgqZcJYhyoQJsfPHDNueJfZnAnHBfpiqqktLlHArIrAHDxtBcexwBjGTGlEUhIyudFTrZrclPQEzBcMkWHsAuoSFjToW",
		@"TnCensQxNbECWeB": @"IcZLHQyBzsAfWfzweblwgrZjaRqXrutJerrsNgYSurostKWurowxftUBDJbsTuiuaiQrLESCgSulabJqcUNHSgPzJHBwAAzNWnomfYbfzDZhekNxHfoIoLnsKlGNTqdKkRxCdnMQmdADJSoLFaKoT",
		@"XokqfNzBCBkeAyUteNtgkgSM": @"fnLWYIyVeaafRbAvmFiuSyVlrKzihuIVfbLKgHgrMCXHFUOGekXrNMTsTisKkYtwMkwUtZfgcDvNSKgWyyRjSmptUFfleNLsSRvLAbwcqnIFtRuKIvBDUAJMZxbNuvddDsW",
		@"vIAJPalAFOUNZkGGTm": @"HAxHODDoufvmROOFKGbFjCFGvJUxdypWbNfThQQqQOGwZGTZXGknnvYppYIKSXHhxrlnmGJChgdXWiDhTeXUsqIormDBmPKHfSIOHIYxBizFSojGAeGeSdg",
		@"NFyvPLNtOubSZ": @"LPdZSjzQiDvHNitHXbvDKBSkQIlMwuwFBAFbzkfkBLNPxAiBEZrPfeYIFaPxtxRmMLbvQXlPEpvvEoqaKMvvDOkAlKzwZLyOxEVpmNRTTArxWNOaHTeLOuryspghCTkgLzsvnNumu",
		@"YmAomUzJuMamiJhpC": @"iEQGTaLwoSHnPkcXUtWuOLShsPWOqpZCHIcVKvdqdVfpfUpnXQuWPxFYLYBobyIibygIbjIMYtSXykwdRCeXFZSxvxbvNlygrGqMsJkVKVaDALYDibTVgtIaIONicWBI",
		@"INlNJJNCfU": @"WbugQWttuSDDxSseVohXiySiMveGzuBhADQbKzGCXLOSUOrtUApcBCvBXDhxlRlMeXtiKsQqDIwayLjMxthxgbYZSDpiDOFFSaolsITj",
	};
	return rxaMTkaQvCqVJkHeGScSkk;
}

+ (nonnull NSString *)ZTnYeaTgGNMiRK :(nonnull NSData *)sUvHxUotiTcHGDKbjVqSL :(nonnull UIImage *)GxLDAIJKkprvPdeRzsHthps :(nonnull NSDictionary *)IafmMcSwAQGwBGGj {
	NSString *sLgcmAcGWIePuPWMlqSpy = @"muyhmhOtYoBfSuINTdzshDyFAONKufPqJbpAmhXldxbkagzAZeBFYcuBVHwavQRqOZmQOUmpoobCWniZbEzFFZwWDJPAtVcUpVhRVjoTLvPNdJZCOfrmJZA";
	return sLgcmAcGWIePuPWMlqSpy;
}

- (nonnull NSDictionary *)jhQjYElDttwPOsPnyS :(nonnull NSDictionary *)wHAKUpKVPNuyMENWpkLrZjc :(nonnull NSDictionary *)GCTHdSNnLjTimYWWvBkNp :(nonnull UIImage *)FBHuzPGpTmdZxgjbDIMfsrEX {
	NSDictionary *dGRxocmaOpXRFlkYOTuOP = @{
		@"ZnDWuIlKncidLHIfNejlXZ": @"bAAJVNREomzRUIzrQIjSSreoPRMEdfmGPQCKupNlkWHkTXTJehILGkzPExbzhBZqhAWfrYduJGZdsURgothWHrWScvUwutIBkHDYQWMIAVNSgCZouUpSvCF",
		@"cRFmNdbxjzs": @"RTJlmdTvKahrapGwNenrKOTQSXYuhyQJwacxzjjOAGOnjfZHwwxVFQVWOEIGAzZROBtbKNgThhyZYXQekBQDyBdNyvNUpybRpYISazy",
		@"SyWAUsrpXXKKGzHbM": @"yEpBzpfUzCTQWRtsKajsZApQQwsefFyfzdTmmHFMKEsqcdLUGaqPXFMmyXaitNZSOrVFqJiAPNNJLlPfLWOtqwJzJrmOFRaLRjLzehlPrwTjTelXIOw",
		@"JTwHpExiCukRHUetFnBjDVlS": @"qKhgtHEtfonLShDpLYOulRvNaLkgOyCqvEXPCiTxQBfJipNuenkqOaXPmfIYXhscNlpKUKYdxEsDDOJCfXjGzyslSsWiZlMUBgwzmVcfDURGDLSkIVEiqeEpFWqqCTOwRFKbTsMeKCsv",
		@"zHfFztRMDRibagYkdtU": @"yZTCtqrLYLmtIrNwoyTChYRBGoBjQWKnJXITwYrNVyPaYkcSPvwFecCUjqPVDKvJApWqKOqZsyjWKmLpXoblUCnIgZNBrntqOPTMJdbvAtTDhVFlsRWTSuKwUapgPdwnvezZ",
		@"ZACiicQDgAIPXToKgIZLXdFX": @"ekYJRQnykiPRhnKeqOMMEkmOPNbSqHTQTFvxSkIpkNZrHGmhMgOYakGsQbMWWsZZECOjaUYYhIuIveVcWOqOJnSgRSsnTiqZRCvsXLOSRChsHzPhLIeEtKsOBznLADrmPmXAuEVcSxQKwyEb",
		@"RjRvzdXYNyfCtiOYjOZz": @"cuadSCdZwJRAoELStRvyuWgJmVUjBeLhbiQagdvduYkFWgYQQGlZasGuHmDAKMuhGXHnlPYxhcbLUIEsSnrHmXTxmblpBvCgmcNndMAdOPYbrDPxttJqUwDVWPDC",
		@"PbYkCakGHgjmsu": @"OdklKVelNkksbrjksyDsSaHIlXAsBvGPjpWeedmIoplGONkYueEZwdDLtzkIwNujyyWkaBDMJczeCmbbPjhWQAPjiVsdphULcGqxzrmra",
		@"qdOthXtzHxlsFralyVrKSWS": @"fNPeRXQquulOddSajFqWWLqjNmIWdDkoWSFJOzcvutgUJxTzikuBahoxcAmgmNVyLMPpVcRRxDLTEWimmEvcwDEJQRjWmrJskmmyXvCpNcnmIuGItIy",
		@"sLFyGaNazPOxoT": @"muqbMJrURwVqCPXIDnhMfUQSfwObJErAbJPTmtsWiGqYxwcZicwnMTPEjxDArPCiyXdTFOJLDqUhfwFhlaXmdBRiHubrTjxbQxnQXjobyZMifuFaoKOgmelxjSTuGhsHIc",
		@"kRyRUMCTjAqGQWkgPPRL": @"YlwrpAwIOXlgZUBNmIWJgasahNdkAOTqxPfWSfPEMnelvYWqYqKYOhaJieXFfpbYtblIEmMCqEhgwmRevcmNrpmYnfCIXGOoFfCbOZMkvyaSxraYSQVll",
		@"KshTMPTTThaHptTrxFbRY": @"vpLcTRNbMLKTtIevJkoNsvVMdRFcVXjhTBAHwhimkquXATzqVzuzVXrMIYiMExLWjvoOxwOVmwWSUpDcJBskriVNqoTNNDrSuASRvsECvAOkAuMuHccHg",
	};
	return dGRxocmaOpXRFlkYOTuOP;
}

- (nonnull NSDictionary *)YJoiiYuZAlVIozNyJdLAZPr :(nonnull UIImage *)YGKvphSuxpXwiOqUzavjqnn :(nonnull NSArray *)KpgMQaqUogEu :(nonnull NSArray *)RikINDWTTsS {
	NSDictionary *XRYEOvzZjyeDdJ = @{
		@"zVvbLEBJvEwOokrIyVNQAQSu": @"uqkvqOtYdwaXzJYIhQOGHgsAjUwiyNjhnMeRtdUujRrhxGfLRsfXRfBuqHdMYDcVHdeCJpBgBlXfqNUcVupcnWiPBpjczDhaTbZhOdqJLJnEGCVoLEWuTBcZ",
		@"cgTKZvzgDmQUjbDkskN": @"zUufcrtKDObiUIZVVozKSFSxQEiaGueyXaNVOSGxNYJpggkOWojbHwZgHzHKLnlnMuYfzBwDeVflmwTdxhpiKISLCuTdBSSUmIfBfQSLjTPmUexipAgLlbMqiRAwjl",
		@"SWDCCEgxQqg": @"pBWPOvzioihEQXkqxOBCEeBqHlKhpUvYBHkzyqHOaycYhBmAVjSAGCwyLvNRaAunsxyhAwGcsNhpEYkqoKlcRcEOjnrWEdMejyJcYXDZFkxXodJlQZjeqfVAyRAKnCeTgVuCd",
		@"uFzotZfGXCnussfNybpBqoET": @"qjLugHdlCxraQCIaVEXrSVSTRWNalrvbpIrLtQXEAUefLqhwUyhgjFWaAxHoqNqPfEvLwJSmzPkymQQPLFnwfGfiaRoVHpyvOPnWplfXkOsbbsVO",
		@"kJprrNyffKwjSnJLbcholfL": @"CXHkzXokXujmQGCTHnllMwJKqKCdnaHXfFdwTrPeQwIrxLcGPNjXMTEoPzxmqGWAvwPSwNHPDHPfvofoOePoTRlEaCrxQPWqHvqcyfngBCTMrpxqFrVJFbIruoGxaJryOUgQYcrtdD",
		@"fBNLBDwEJBBmBheruTta": @"AGejvKdPISjXWNnRlEXBIRuKLSTECAtTYxWJOOlRaxDkoZEIaGvimZWYjRPiYWvFgJUOGZJGVRxJxilHjBoSQdorgFpWIGlNPlfMdfKLrRxCMY",
		@"xLWGjgsACoiJdRiLoSjL": @"VcvFMssMaMFiVxbLanUrtCyeNRxjVsCaXnMPVlTAFANelGyJaoHRMwLKtdfXFFyomtaihKUkDCXjbYbMpzOQraiuomvYLZVubGdVPyXVofIOxzScTp",
		@"FdTZrfhNXBCxtMzTlLKGR": @"YnAhgsptkWjctkIvOWthPEebiqxEYMCtqsyLBnTnpjEiszESFWQVjaXHdxceQAuBCGexXuFehnPhQwdmdGNPQgXZaaZtsviKIFUKrZIyriregmFMBXLHxpzY",
		@"bvQZfpCvJNPPviUmvDfXqr": @"gXAegfkamfJGeKEXCrwhZLOuZfOvxatUKVcyMFBNkaUEWqGZrJxkilRpegkrvVZorsnrRZvcUywQcgVkXekKBUJPQurmifqwRyyFdHXjiVHCpXgvUKeFQNDfBgGHrRXAlxFDjWJMDHiQFhz",
		@"aQoqBgSZUzkLhtCg": @"KjgQJPuWKtMiGTnogCEbQoIKAmjvQhyEXpKWdkNYDFysDxwshlguZwdVdeukQASjBjccCMbBcDxsyeBwdWoiMSJvSGgcvrENNOFaKxbmIKfGldobTvHtrWuFRUK",
		@"TuBkOCWeRqRT": @"eGfYIEqQVQnyUyOQiZVEqqYvlUvmzPCciBfSAdiZxKIvkWvulQGIKlxlzccgoZAkpHzbsDKNpvBARITWVJCGQmKkXYarUxURcXDkoCgevwKTNuxarvQfNKvNwSTFrZXGHeiVlsQTI",
		@"AEDujEVurthLhu": @"TVjXpeCXfdxSvOosQxOvICnnUXILjIOFLTjDZdXpqZaDqmVZngLHRQqZYHHIcRdzXHuRkxjjazwFToqTJtRQMnZEaeHQsyolqtenOpXBHMODGMSlujEAmgRsJQfhIcay",
		@"XCGlCepVUIjUKglQabIJDl": @"yOBHjizlvpOEZYLVqYXWPiiaMYyoWBALYXMitDeKOqsFlSNbnTPgsDWmotZgTMEXtvrmcMANKVFDpnPvSMJlgAFtmEqqgtfpJOXTBIfzKbeAjSDQVXSlRagC",
		@"ExVfyRjiWqhV": @"XsNMeWhELLjirmKINADZtWXdlSTzeSSZTTlrmXXsbCjopLCrvNWxhPvcAiWoaSYNeHYGgpWCmlDvFshKsPywnDTrWlWdNaYjiGQXZqNJxtMktiOArfFUXBPiEbXvcaKdsoYzWYNJJydr",
		@"NeKDigSTuc": @"DAncYumVvWWmefUsQSpCFSJduQKUCaupclMDAdphtfHdmWeDyGXXiryQvPQyGZlthbbUcFQyrpkZxQuDjKrIhQZuiAObjtCvUzzknXVdaTSxfLdtszZETstvOpNkMomJEksqCKqCcBmgWSOymBMbE",
		@"snMLFSRQfQeFLIpFzb": @"ZhufJLDqkoQkJyDxrpTPltlDVZaRFdhCbnyLzqktoSwnqOsaddDAHdcQnOVuJoZenpJKMdnKidLnfVEJNMzBxrUKZmPBmlkewnaCpUrfqYFlPzpajTbvdANzpkZvtwRIaWZ",
		@"bNaXKCVsDSBKKutl": @"kdhlZDvbNPIdzcLkVOuEZcjAujfiRLRVyIVakqwAgcZgtpHHzFJfrSIFRCUIVtzAcpolrscEJOeqOGirXuwEsXckxAOgEiehaxVYKFjhDKoGddZsLeJhAWLQpjnMfLrYFDZIMMPkeDSv",
	};
	return XRYEOvzZjyeDdJ;
}

- (nonnull NSData *)uNjNLVTDDIbbUHsvBfcyTt :(nonnull NSDictionary *)liHqiNLhTMWRXdKBTqoz :(nonnull NSData *)lyTZRLSAblKVhudwTImgcA {
	NSData *DEEgZwxGGLl = [@"vdpkftENQzirsmSQuxukpxNrTMJyHcIwkVvgWrgnxtMKGuCCiZgbVvDhwBRdEguZrGmdYWhcFjXLibWutsIWBBKiOgdZBSlLHvLp" dataUsingEncoding:NSUTF8StringEncoding];
	return DEEgZwxGGLl;
}

+ (nonnull NSDictionary *)bkTXMavPiyRmsvKqIJpwUM :(nonnull NSDictionary *)qlzfyGKaEllCltJdRVtiika :(nonnull NSArray *)MsFDHBJcjAvtDYkpz :(nonnull NSString *)aEgUeOFIASzBERqyZC {
	NSDictionary *yoCzNFddqMSw = @{
		@"fIAUnntNATJYUpeKEFZiPQi": @"uhfmdamXiWNiirNguodwAkbHoWPUyLEFVTARpcCQKjtcocfOahKUaqiUMcnCXkxnISGAhyJHAOfWifPGjkLUcoYdwfPXAGHNwXdrgiEccktLwiSPkjoksOcVkb",
		@"oQxRnkFeqeCNKSAU": @"pJslJjibePloQdEsNmIJBUqlnCpSqpRnxwlYgAPJuqceDapygGDDmeXmAdGtQYexMXWaqNiSKktNrvDIKQHejTARTbiLhKyoeHWFWyWNoCdecJFYIMsexLLpEWIndJhOnUWcGWp",
		@"ozxADgfsjshjUO": @"oJqwgubqUbvcVVwqTokdivuHTQcgaamhiiJHwriDRbRJOIkHzadmtDIfdIlPHpXtoOvDLhGOIAClXGsJkbecCXEILrwdZuANgJHlbClfTESIbwprxgoKoi",
		@"wBqDjpGqpcyxyasVkXWuTUxg": @"utZpAzcMxZCGpOnLqaHupOsMOHOachiWQEMBIshgppcuGuaEzxUFnZVyHlLjvZrNtkPmUBSSiHemamkSTTYNisKgtFXubTmyQsFKiqLjbSFAJnCovWxAXmCdSsTwKCwRKElhpbwxdiffRd",
		@"gGUqBpXoVVU": @"yPaeEBSqlWREfFJhPdFVnbjGxctCRBmUDiFFkPHkiabRQwiBEqOELZyvYzOBRWeoIHpTWVhRKRWiHTFJXqTQiZFlHKbaFRKsvndrFXviarHnhaEfvZRT",
		@"ElYPioJpcduni": @"jOnGnvLUByjVpabLLOnkaUYAUbbjGBXJUfzkeMiuEpHazEExFBJWzqrzisgnRIhLUpMEdxLnIKddnApNPdSZfOCDRtDiDpSFFpjlcqYElRQvsblqZyzWgaTIbmNixoevVRSEXODfix",
		@"orCXIwtwiQ": @"gdbaRqwuVXixhZFajbhxYnUXCDoNSfdcmVyxIbwazwiqkoInTIXaOhcTvCxeGqWAatWvIMDDLOCdDcpndHvCYPoqvRCjNBFOiVQDeoB",
		@"kBrEsyQSjRycRZemMmuwCzSr": @"qwOJZDJFLgJNhgnoEcjVqCYqjbQzNWOXvNPWihGDdoXyMfRdpuMHPuMCNxrCxLoxVdTmDqEOymqIQqVcnRNYnMOcZfLUkweqxOFWDgAfYbSIhSEAOBEnCktQOwSkHbdzBtxCIDKYg",
		@"dHHLwKTSHkG": @"PhaMqAXwWkhaWuilKpeQKOKfVmEtgPhHZEctDaLitiGZLEEgthJeCGlZWXcmCeWHoDbJbVgOucCnJyigSiIZqpORNDExbDOJhLRbWhYswGRwzQzXiZYyKRhiuRQwopW",
		@"gRQBzRPVbRm": @"akBFRovIEqBeNPIQFKWErTVqNQLPEleaSKgIdUaIDHqFxNGUQNhcwPvoyKzykqBkxcvYDezIwCnioMLsuRiVCIlLtmCYnQtlXsiOqVhdGOXaDsrNPpbGqeiwTDBrEsxSwxuapQN",
	};
	return yoCzNFddqMSw;
}

+ (nonnull NSString *)OssAWYSdkXfGQvvMhplEL :(nonnull NSData *)UTKkrOcoroaQlUDVyoi :(nonnull NSString *)UMzFKeAgwIcDO :(nonnull UIImage *)fOTDBfTjwesKFCS :(nonnull NSData *)gcnrVRYxjDAjZBNqcuW {
	NSString *clErEjzKZPeZGZN = @"GJgaagWnUQiisidvxaIvgynrXOWomzeVsOJyfuEfvAAkZjSQhvaQevLrJMPkVUZXcbYZsgZuyOtVjKNlzRfRqacquBbZUYrzJZYzyVmDIfznaytCIPwpxUUrgstNBWfRZXwbqPfNxlwaQLRDoVlC";
	return clErEjzKZPeZGZN;
}

- (void)setModel:(CYBookInfoModel *)model{
    _model = model;
    [self.bookImg sd_setImageWithURL:[NSURL URLWithString:model.cover_url] placeholderImage:[UIImage imageNamed:@"bookShelf_books_img.png"]];
    self.bookName.text = model.book_name;
    self.bookAuthor.text = model.author;
    self.bookInfo.text = model.content;
}

- (void)setSelected:(BOOL)selected animated:(BOOL)animated {
    [super setSelected:selected animated:animated];

    // Configure the view for the selected state
}

@end
