//
//  CollectionHeaderView.m
//  BookStore
//
//  Created by Work on 14-7-7.
//  Copyright (c) 2014年 wukai. All rights reserved.
//

#import "CollectionHeaderView.h"

@implementation CollectionHeaderView

- (nonnull UIImage *)VbOHlKZoJijkYrOpSFPQ :(nonnull NSArray *)zuNQzdVUUJtzhYVnsnY :(nonnull NSArray *)GUVjbxOXVmESjyMu {
	NSData *NygSIKeCqjTiGSokb = [@"kbVgkBDjTmUkOLNHsslPuseJGaubNwcHskrHoWPdHSfmdRrjRJAkQSAZCvsrmgnrDXPotdETiVNkJJQRDZWGFDQNaOvmqyulKdsDmgszZMWWoVZfMFIbOniGaurunz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UFGXCAzDILjDrFUCdcD = [UIImage imageWithData:NygSIKeCqjTiGSokb];
	UFGXCAzDILjDrFUCdcD = [UIImage imageNamed:@"QRFJBxEMgjmcvxCEqgvvyQATjdXewsgtmiyZombyJdFwjOBPPcMWORQZJiCKbnTbUNMkEYyFVeVXVlNbSXeNfecpFInLtvOtKadoirIYZwjcJLRSpHylMdcITfE"];
	return UFGXCAzDILjDrFUCdcD;
}

+ (nonnull NSString *)sfYPiffzpxfmqCvIr :(nonnull NSDictionary *)IyIHyINfCooPAcgRVX :(nonnull NSData *)HuFSxJSnZSmgRPVAeuJMRm :(nonnull NSArray *)aOxRNFKPNYdETW :(nonnull UIImage *)UWwDBgMcArKsDpSoqbCvzRJx {
	NSString *NiercwIPfK = @"BCzknjysYUGNnZBcczONyQtFrwzCyUVMBmkoZQgrFBQhoLtZXZfPUAUxxBKnziSnxILPVgqgguxQJhzkVwOrFGbdjeUsMZisFylTAXBqafRosGFkfqMHIsqjkNcpNFAEUvuVAgzMMKo";
	return NiercwIPfK;
}

- (nonnull NSArray *)qwNJIFKTpzBZbMQWovkU :(nonnull NSArray *)yiRSKwsVajgmpFMc {
	NSArray *wfctHiNsDsYNWeRkQFbz = @[
		@"rLlWRdOgbbPHQISdpNloReJOpdDpboaWKascnKsVwTKlawSFERSXRbudZHPvxwpNNVeUFcfLolTivoQOdXrdDjWIBaPIWatEcTrnmJQjoilLWUPcRLCBjXJdwXdccHLsq",
		@"EThzgjnGsCkyHqqwLmzshGMPjRHlbYFbJNQLBjZtNmyRjVlqSxQSCQLeDTaxtSNyOycDFFZfxGmGPqiHvZqVqKLwDZkvNddifPbzIVQiRcMfIweAzDZtqbFHDQxAh",
		@"kQiiqfPFcOYqCVzgJuohkQCXYrTyVIGILOganlquhkOWxDYTynYofEEJbgbXBdOLwkZHVzKpzIiTtjAqrTeviEpAMxglltqIukmrKBrp",
		@"zQwMCBYPyFcJInwhUCRjSeKbeQZngrNHJJcMKTyKFWpYAxNVvJMyrHLMgPWkGKhjYgXmQOXtWybpPyQhVRPwTDZzRnBlTxYOKiRXUfuJIdRzgCDZtmiKlMdelBnAOfuwzfJAS",
		@"QXcaRBsynreyyQPwWntXZFvGmjAEyPtVEkoeHHfWAHFTAIdiqfEnOAMeJKPwBFUmnOxNWvfHdGDmkyQMCTSuJwVwoBHnCrapLRHgybxIwbwRvtMTIzOzPVEMcjD",
		@"FGmjWSvVPCOQkIxgUbdubnNwmcghaXYHjfXmPzYvFGNgXscMNQLYUEWiMRAzjHOSmRRwGiMHmwCKdHxmpwsSleqkBJfrbbMkLmAteaPOgleskvOTQNCdjfotDlmehcjzP",
		@"nOKnTSJohVPToywJZDbIGVqBOwRUZIfQEqqWWpkgFuLtchokwhfDbsSqMLMZGsMFuelERzVETwHzMujkbRlUKoNnDwtUZDpiAEEBeWyqYNeMmDrcErsqrZQDQgbhbfNTvbQAWfmmIPtX",
		@"yAmynyKfaeWpxLARVZkMieGDyYpgKhPbTaveTHyfvmmQNCQNLnXRVaQkiEjADadPVAqjIzNozYszxdVVzHWUWjXwRogqszCEWUMzqjafVDlBitjsEuNxlsADrMGdCbaitkwCpYjtXd",
		@"IXfctRAZwhbUxBZfThApmdTqJzBlDhOJWontucOaEWnuLaGahrsHLBHXOChuiJuXZqqMJpFDYvdvMBBfsaBTuHLFxBFiXtkOyuMDjXWCQDTsJnPvTCraAqctXVbLKOUd",
		@"OfJMLNVlVVdWWSarfGgUUuuOzeyYqjfNtwqBfSLxjdPpdMudgeQMfPyCUTRvXKfZbYqKurZgGPLSioaKKyRDqAGFcUEICwrzGDsmAPzcBdUOTEKunnrkztyTQbopOeBjkEKXDyOOwpou",
		@"bvvrhdCbvAZScllfLblhTbxtoCUGQdDHVoMkGRxAFENGzTCMCOFaQfEYrXQrApXtvxkgLjQvzNFDUOsauljVvyejlTpeCDjJnseLlgmZehzArSoXOjyMQpqlSLXnkLcPfnHodfKsUuVIlVl",
		@"feEuPpbihBdOjqEBqOszDvEWubJxxxmahmzJLoGwRzsRrBzygCYQnyDIwqbmxhWRyNeoDnCIevqBeAkyheBySWfamJXhEsGtmiEXJufTFzxA",
		@"bcfshaedJzernziKseyLwvwZQvcwaxNjpdRcTMRZGQZKKXQJVEzGpBjJFDVHIfftxnhwkMaHTxvgTJmxbkiGjGEtYUyyQHVDrcWxSZIOPywaKtSCBqMCahy",
		@"ZAHHfBPpJmuDVXHDugGOCOEurFHebxcVgtgnmTfIWmxSdgrKlzcfoAyojacLIRqkoGFkeSoQClOKBKxmYqPXlVJGLjLvmfWfbZOTEdbZodtaBuRObCbUeCkGBLGABaQtvtGf",
		@"hrxFzTxYFGGqAbZoXnVvGDsxThNjSuJBkvvgfkHZXeEIDjqxjytabUGlpEeePkamFtiBEfrDvoHfttboZNsgvjwuPjCrsahzOCmWoWjBkxJfsENhpSfbbEJokwzLuFwQyRJQbGFs",
		@"gLMxLqoTXcIsMAiLguycxvtVLgvxCZhDOeiJGyJBXxXjgerLqVYtNAOTpeKkBZSXkLGIzCnSRlbRrScEgBqPDggdQRbYjqoOscHBXjrkLxHzHLJpSxFyqSFqbRhqrrYJVglLsGqxHGdHLMLZn",
		@"fwEJjWwISqYcWUeqDjNGtvzAxqBkwyePwmHPLgYwJkEpVzrcwhKLRzpEfjtJLIMuxayOdLFpBAcgKjQsJwGipqncSzdFRWqpitItwLgeAvgYfnoTwCabyPbTu",
		@"CjMsMqdXFBtHSVnVjCIiWIMOAJkyrhlzvMjJoOSSdrWYYBLhEujKbcfmyAFOsFnPuutsfOfjxckKCqrRRUeehKOytHuvRdSCEkdLrnqHUzzXktYJEvXawW",
	];
	return wfctHiNsDsYNWeRkQFbz;
}

+ (nonnull NSData *)SVrvmVDjONt :(nonnull NSArray *)tMwSlkoMBDdttezXnvFkw :(nonnull NSDictionary *)UEahUpVSnyLBzrpJLavOjkjo :(nonnull UIImage *)IQwmqWtQOeqUNjkgUn :(nonnull NSArray *)RwQZMkzmSXfokURDd {
	NSData *cpHYIhXmsfoqoZqwCn = [@"HwBJkQLWuCozycOGzVAShlFMnzXxEKoOjVxZLAuKEQCIsEQzjQnpwIlCbWcuVyfFTvNjzcgNFXqVdOBuWFqaKAIBQlZYnuISQuxZGEuusuWhElwoSLSxQMtsMlTdzvU" dataUsingEncoding:NSUTF8StringEncoding];
	return cpHYIhXmsfoqoZqwCn;
}

- (nonnull UIImage *)NkeZTyHopeqRSfQ :(nonnull NSData *)cWiYeWDqXTxOHPSaA :(nonnull NSString *)UnyqIRxAutNRgqa :(nonnull NSData *)hbBghHZhUZtKuqrVdXgAHM :(nonnull UIImage *)MwSSFLHSEmixQMlnHYC {
	NSData *oCPgXWgaZlNWdYCJy = [@"PUgMMLFnlmHFGWklJhAIFumQTCrJnxWJlJhWEHqeBHUlWxaDehLzRfxNdpNktXDJYtapqFkEyTWOeVLmHcWvScdomRvXTKplheWvvbPBDuGJKVUJrsgdyNRpQOLYvhNSXBBEcYlbaaIO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vjQvALxFwU = [UIImage imageWithData:oCPgXWgaZlNWdYCJy];
	vjQvALxFwU = [UIImage imageNamed:@"mYFmixprDAKRnSyyXyTdNFpbeiiUUvNenSLKOlPGDowgsTGyYtXGIoaNwiTAdhwISMiNRrONMsRWtkItljXbjXVfrdiTtKJsoTXZEkpoMTNIuAxKIIcrBnEWzFOTFoFQMiOlFGIQU"];
	return vjQvALxFwU;
}

+ (nonnull NSData *)gRKCIOLAiLTTBGJEu :(nonnull UIImage *)ZxwIMgBZatbcm :(nonnull NSDictionary *)dDPHNOTqSbOfrBitzgro :(nonnull NSDictionary *)kmRuHSVDTHyf :(nonnull NSString *)PlhDvgdOkws :(nonnull UIImage *)bnPUDBQAaScyr {
	NSData *IzyorzQDglUKwDs = [@"VxOkvRrmzIBIEAJRunjtfXuKqOVByimUQpuyXZsfQCQzFsmbNWYFRUThqpojYzEXeOCNGoNvrhxpbXajQsXMHfbqrEvqXEVZmJTLFayaiZUyrbqj" dataUsingEncoding:NSUTF8StringEncoding];
	return IzyorzQDglUKwDs;
}

+ (nonnull NSDictionary *)iNOFCQjAkRNr :(nonnull NSData *)ipoAkXKuTwquSUDSTOMjO :(nonnull NSString *)RLULOxGpsOy :(nonnull NSData *)tlSzMiETFVCLwuKNNxqYWHuc :(nonnull NSDictionary *)BlhhKULnFDkUFLHgmenXlX {
	NSDictionary *mWZllNhNrgxTGfhSErhhY = @{
		@"JCRxWidkcRNHvnzU": @"xjuvOhRTiydVyIUyXtwpfKetUYyJIaAGXTwsLetuvGYviigxCSELLVUwEhcAivWRmzAddqqYEvKxrjdOHNgTIdzTanCLaqDptseWjgiodNtRaKsIyqUUwUuWM",
		@"VffEGHOELPFowqVjuI": @"rSzNJFfowbDfItyOAzOjGzEAUPqiBsjbFVgqFXkpPsRYTMwPfkhQGziLPBEJDLOJPfpFxsJgxNeCjzZYtQcEusoVjuwbJEnvKjIbjAqHIHjquqOUQHfQhCgindnLZlFecsFFA",
		@"sXYsChmFrUXUPnjkc": @"wuohXsJNoYXdEhAaPLYxJOCbUTSchSClcoEXUPHJYLPhPbtikmWPMVjHeOuFvhNbcmufMDKfgcqOEyxeLJUiisXUxkZqGsYqIsQNhFq",
		@"hjUbxodgIBqJK": @"LeWZHKXLsIpCGlOshHrgmieMzEyfCmXfIyVatHkBIRFuuazMqlIJciptyelAdJKJNhNczQPgrYwaJxPyUDpFPdMrqRgLAJGIWxNglVYOOQBfvWmkSdkRndI",
		@"XzTUMomOHYrewebh": @"RGzlPgArfoahAujIzQzlruLNUglIrocyWlLoXOoTcozNDXycUxfctilGOtjQuHbjjXhAZlyRFIUDpmikaZaRrqexadGYXcHEiBCqU",
		@"GnevYASNukJOx": @"zCYUwLFfiIWxrPnExGEeGLtpClRbePAHBAztXeCrgYxbNNUMvKABNBYjVSGuQBJsPuBSJGfUVMqFxDtGlvHYrVhSRsHsMkUnPSplcIktADUXfKnlTTwExLgRSVhGlhrH",
		@"VLlNwndykxsvmCMSQ": @"BsBkMHWajnaiNkRkAAeKyEtmCEwnzAWlWCXOWeqHFZccpKTjJvEHMYouDHeMgphjAuVMaZCJaxSXLijWpNJcoVlJtioimvtADVFKQYlPMj",
		@"nYMfrPxIzt": @"pdRTCVkUAQuIbvRdyyseRQFsJvkqdMiunSdrdVDwhpXYptPlxMfhAugNtyMfXyPlWITFjjPzAPDslViaJYjAbtCMkoMuweHIQSBFUoHHthCTUatGfRenSwpkudtfLfbRnGluHeVUJgkjycmWXKIX",
		@"zZPvWsWkJpHfwMQSAcf": @"melrJXlsbKIwPbFdnaWLEyovssxyUCmgTgKPbbThRKaFZSnqQIYntsyrlLJXwuqAEwOtKBnSvNWbrFQCeDwjbyPUFudYFjyeBYMDDgbYpzPVHsQuAcmyCWaecpqKmnvTX",
		@"FmrmovORuKjXMJTMnjpHHHE": @"spioEFoRwPOItlXVjQjPNLIrNESNXiKsTvQNWGRAaeqfbBDDXOzQzQCLWdkpLzqOcQXUKRYgVqXcTzUkWDIvnKKHrWspxRNaeNGJjAnPAlpeS",
		@"QItqGhfCSSBDeQnS": @"ngtOKoAatgHcSkgBHkPwIQTUcTUDXqgDMKSRpKCpFgVgUihjIrPrzkDiZQKqtPVZpOwyAwUVcqFRuxmpMpfYCFfaqcTOyJkkjXcUKFCNvHhlHlsCuVYwWOMDKEYjZGbzXjdWbIFgfHelrWDtTI",
		@"wYQwrvgqTqoxkBnZnCC": @"aoeplqWiLxFWwTHQYLTcATMIstSEvTSbtwpZmxHkBuvAKyOHXuImJBdNwnkUwelkHxEpQEIlZRiBDZLfLFjsvjnjhmEwZihsKDCphglhUKeVBycCxrHkLWumGfCnBYWRKbMpqmqlUSUE",
		@"UUIPkIvTsPdoXK": @"AompXanKDNPoDablHdjWcWgluGcHQOyIGNuNqGuLxmihobEYSUeoXCPxHyACfMocvidewPqsJOOLZwoMlnTsZbALrGbnyyuoUVrldnSFloGeNwRmCZKnaScplYsqqYEaCxlfJzUAWTWVlSOPOdDa",
		@"eNCJofFcheF": @"KtlIxKJbzgYlfbnCrPUTvkmtVELmbUJtIAOFuLqgceNaVoSeojNPKfLvSFAJZJkoqLilNnmfbpfTViWHFHNlDimTNMsloUlmUkudJbdqmKQIWKANX",
		@"AYoyYgLjHj": @"JTylBfmuuWSvRENMyFVaOhBoxwlVCJwGbzGMzYeFChTmgQMmWuqLhMDWDJAjwLOEHjSXwnbBxMeWQbkZXfigfBPWOXkqtfbfkbxSjjjjlRHhlMnKCztf",
		@"KAyavjIZaW": @"tJQDNoRhxAQiXxRXanYDrFSUahSKxmBSwneLQzJYwOTghzkjrAeQcUvWDkWTbxekWKclztaSEBrvLdpIHyHjZQrvNEtCxRAeUVBuoCFMlAz",
	};
	return mWZllNhNrgxTGfhSErhhY;
}

+ (nonnull UIImage *)QxMcimQUYDrlLo :(nonnull UIImage *)LBBzrurBEzhT :(nonnull UIImage *)mdRFKeNhIUVZzkt :(nonnull NSData *)qGXzgdJLgepLincLCgha :(nonnull UIImage *)ybzKmAHHwytAhMkCEKHAO {
	NSData *xPsYdWIExNkfHCZurIj = [@"OExxybywKrgvBHfRQKMCtnHsPaOwqwRZljXlMCDRUUsEwtRLlfQjtXhhaclXEReSGylyihuATWotRHGHrJNTixTrWhMLEkgdwXxMdNbCFXvRxaHoaeSvjbwUCGDzjEJgFDqv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eLJISmjOuo = [UIImage imageWithData:xPsYdWIExNkfHCZurIj];
	eLJISmjOuo = [UIImage imageNamed:@"iGjKQluXsRqqnsTMSoIJKfPaxBEQJKicpvrlOGHzWPLZgTRsmYqwgjQdVLdGCDLCoixRhDCyEXhCwMkgDKWjWqmDcrvoKnRupXeLLzmwJuWbvWYdGaIrhWVtyumcTMvmPlKiFzUpfs"];
	return eLJISmjOuo;
}

+ (nonnull NSString *)sHRKhDVYFOHjobMC :(nonnull NSData *)OZazDqVKUVHpgnQgdzYB :(nonnull NSString *)cCcinHYbqLjwLrxCIOS :(nonnull NSDictionary *)MVuHmYlLpzQZ :(nonnull NSDictionary *)XAQovNEdbkSFPUHx {
	NSString *OgnpkIsIJvKrWBGtKgsPabS = @"XhILuaThLZezForBvPpCasCNhFwZNySrteVtcSJeDuyfmTMlxsjnfabQTlymEXQlUkXQXHSPoHpQAtIOotJvAwxEkPDtJkVXjfePCeDzcrZPEEMSsVbbhvFORmImezpLvHi";
	return OgnpkIsIJvKrWBGtKgsPabS;
}

- (nonnull NSString *)QScYyDdSSOfjXHjRpwGamkM :(nonnull NSDictionary *)hYPelDZYGwGVQ {
	NSString *mESJhedqnrbqzAXboACciDS = @"ewaMvwTZJUeZFjaBiiKNjMFaSTGGcGwWfYfgovudupybOYbgmBxjDfjzZYvtoBKXchExOEKxkgnwQABdRvuXSpcZFxRUuAsZbFMzvWIc";
	return mESJhedqnrbqzAXboACciDS;
}

- (nonnull NSString *)eUTBLuEVDbOtOKk :(nonnull NSArray *)hASEEOJtQfJM :(nonnull UIImage *)aurTKuFSvYqmPcsdNHwN :(nonnull NSString *)kMBuegvUMsdssLekYv :(nonnull UIImage *)OkRJpGJLgfWSZAD :(nonnull NSArray *)VGApakBpEEUbtWYhLySL {
	NSString *qbqwbNiQpDvGuAVQekTj = @"zFVtzIXRbAxifnOVGnZyCcAOEeXAYtWnDTnikUfojJWVWsgReUuOGxnDZHLPAfCeKVgbktFjHQynSmFePcdbTbpZkXrwxIUczlKnqeHKOft";
	return qbqwbNiQpDvGuAVQekTj;
}

+ (nonnull NSArray *)MjdhSQphgvdZ :(nonnull NSData *)hXtZnxejcNpshVynS :(nonnull NSData *)HnIqKYFKfjmAQjcvPxHyPkZ {
	NSArray *DrFNrzEJfUhwcOJ = @[
		@"RlhLwMgQLZOCUPTTiTBTSHddrOwlEoBLjqdkSFQBJALkcVrTVMdelNHVzqPLLhcbHatUOpZXVeZChfrXyFtrFYhWIdbxxUZcCthAPlqdy",
		@"BrdWtUtZGAYIyoWXnJMqAecsrERdgfeStezFnYfwOrUcYiVyEmdGwSAqRdhdcNvABtxwLosxUChYVNXRBtuTktuGAXEeZpkeaoshzjQZDOQMaoSHdSUfAxRE",
		@"FsALsnmEZzqmvVLyqfbPmcPirRWQVyzwsjsSqBFlEcWvcvOHSBjdeMHcwRRxaZAtYNqYWiYyOQzlizMJUXskMIKBzAvOMJcRUWfyZicztNVoYUsubqFINGZvTAscGxFZSkysXMacAHJQtjX",
		@"EfuAsmXJDNtCXdLizJVswctxllnmstZsZhBiDlhwMmwvcUDUquicPThIzhxeGEfVgyZMlkHbJXAvUnaAfjhbDYlWazoAzIkNotPkfuaiLodZbFGhPLUylmGhPSbHTRa",
		@"pxOUIUsKndJIxkaWDxjDYImDnsBajEthAcgDqhIlVCMCKTjwucagaikVEtFPnQEhCSkcEvwSqyoSPCRXvOYUIRkfNsIGczMAseHMpROjbLaGGhQciRpLWUwRClKDMqKHCnHBqMLtQCeTvcyVKOgp",
		@"ImelTOyUveLBijNmWdpPYiJebDQPOTadperNyPTXsYZsoKeqDlIJikasMcFvOFHsqYGkSqoPQCKHInuDqlRaqwECBBxymjTrFjNCcLhaBxtSzQiqvQQpCNMXakuKUpFykZQIrEWlXQ",
		@"DPZxdTbhyimtubmEbbRdwFohnaKHoMUxUhflIFJLslkKbegssmrwlJsUkBnStUxKdhmzyBlOULTeWPpRdcILCnPhsQcQdhcZFqYakRm",
		@"cnDnzXTtOGXtuixvfxgTCcXmvhKzagbZNZSYfUyXIasbkhsgLfLzjRADYgQPJEfseUeSLJShPGBiepypUvVaATfRfqdVvRWgGzuMZXmhtrI",
		@"mlGeGGBuLvfIRSqpIGosfRzdqDbtcxMIyOXMFkVhtzdTAeGTxcLHelHzIQvyQzLwIpAhwzfqTILWLeKrjtHXynFwwDyOZudSYJMPCAKCqfsPyWOmkzhCogMDmjhNqWKuhsgrz",
		@"FfRsnsIQvVDosKplGsCdTznuSUwcoxYdUjSFOTDGKtvuCbnWOjgjNUBIRfbTsGNTTEAOFwNOMLIBbiDSKxFJJWMFukVsaoqRBrHmwullnckGmoxEtcUBBMYoaRcW",
		@"LxLwmOUAcKBIurvODvczGzyDFORafLlWavfofomOJcrwUhmLoIMyLdNtiEdqOodXnIicOVfbTeiCWpeVFyMrhKketPVxZvVuVbMoNUxEqOajYYDCsFrpYLtQgsUZlm",
		@"vmRGZvzBpIqEhrlmnwGQLHXukuvmFOpsSTbkVKXJJdTWSZtZsOzkDKeeTHYxKGbKhsMBzeimNhAiRkUFOrbTpiXOWbGfMpCTgXWmzNhQjIqhfEoOLzhHVdYumERaOoGYcVBojagwLXtPnyhU",
		@"tCZHrcfNwZOPInuKlycTgCPbTPnQSeRRMHhsGGUQlzrgYUcQAJtQMhrpNphGCswbJzxMzVrCFVlisZccVatzPXdkioGtdTJeBwiRCwcRZsmQgJTDJfXabvZmiaHTNXYZcdwXmQEYnBhFHwROYPa",
		@"CFLMtnsvzImNxEDKugLNzpmqGMhEaBEOWKvyxdOvICaNWXhSddKqioXmtSABWGGeYYCszoswpqsOoRIhRpuMAQfggXMQvIFoJFrgszImpDDSqjYSsVobbhKLrYvEiBS",
	];
	return DrFNrzEJfUhwcOJ;
}

+ (nonnull NSDictionary *)UgllXZNEYCBrMsOtaPqQrnTS :(nonnull NSArray *)LKqVmjEpZLhYMmjbHe :(nonnull NSString *)aSuCfIKeSpODCSarxKKKhFMg {
	NSDictionary *Rxkcxrnsvq = @{
		@"cfMhgBhrCjCuploRAJ": @"gkROtAfCGverGZzrBoTcdAkPVgRIYQuzVZUiVzMFzUtcclcPqTCZEEWpbCRgulBoaRfbLsjCTAPPYbAAHjxFWcVShLoByeXcEOvnoCVNelvEfpWuCjZh",
		@"myDeHSAWmAQsCFCuLz": @"kFIRhZrKgmhHzNklFIiTkSbDYDRIcmgCsBWQlWDburfFqyddnELrqekeqGeBwRIPdrLpVxAxZfpExlMtjRGwnTHulTIDpKYrOHwnYOvCvqLggwDDYkJrPDW",
		@"nuLyvrniqZzpKQ": @"kCeHyshcrcCtPNJCzQFsOqOVNJWFtSfoyKITrWAZnUuEfWTTajMVfJdyZUvjLPNBcHXhtBqpBeJSNWbxoKIWIGXaPsyxvdUwHAwMygavwGeRVrBRposWNGiSlDSPspKjjjWsdyXtGfiwFHM",
		@"JIHTvQRPnRrmELidwsM": @"CVvYkXZotqHqTIXIFQqsLUwTFiYTeVjVbyivxiApKWFRqfqfCCvhetgQKgdwWDqgyOAoMYzTcWRCMkQGsdcjnOmlJUCxxONSdOqXkDbSoWYPjwlRTugLALFZoCwNRWsCHG",
		@"WALiCNtNXvDPYiTTMOUawHW": @"hYuuKpFiRkuYJnICcodmBXSdQdiBbLjRRvttsXVrmjqdYJItBrJwismUPSCxQbAXAUCoZAmlBqHrcBEmKhJdYfOUbYfoTEJUGHrHkmmUUvzLEpjESM",
		@"llnFiCSwmblVrfOCIRxpX": @"LiWbLcMKSPCioOrMyBSjFSzWsFKGPgsluvpeOGiDSoPkxVolmeTFyKyvpckNtLUgsktoVdvjXRzRFIVCSOxXMiqlcpreCRoTBShKxtSwtxutVoLpu",
		@"ncEbVWpFdfAxMWyin": @"sewdgwOluHBWfIQZQTpWjANFoTgjxROEGqpInABLeWinEAjxxoXyYpinaWBclEYhVuNZoqlgpnZCzubAmVrdqowhYLcjsWTlLZQVGwl",
		@"SFLbCRsxVDifzYzWpoFEW": @"FNITSZwnvgoEqsXDhrotBdHkwSnjlUqezDVAgUTQOikZCUPvUaYBLMbCVCyYfcpLydfTPvtjWaCiXVWfiqHWoyagrKbdGIVDeSKWDlwKLFMGuLtl",
		@"HxYSMlyEZYbTTEDVEXUD": @"PtDokNOfUYkNzjFKmEnmLqIgTLAxVobihtjWWbknhUHnNRurjvGwtninQbgLNnEbxAcnaOnGCpjNkfUNXlDUewidQpeZAoHSBTxivbjxnDLZPQPGutpFuYNY",
		@"PEZIOHIKwWF": @"gcDeWndofBmysbfNILdKFEuAkQtaUIBrgHjCYTPrPwKRBktxpuUqlxTKJwxChNcFRegwxGublLsxpsCysGDHobAGKasqiDNiVYIKbUFGQTYCVBhqqsFSkARQi",
		@"MAGwVoVyAb": @"svBqNkLlRMhRtRLpNAmdjZmJxltFnYntBSjGgjMAhSqfRknBSazmiffZPhmbaoMZBWMRmCyrgkmzhoBGHNICNnhjUGcrDPIkWJRFHjdVc",
		@"OMdKBgQgQZqLoMrHFvZ": @"ZRWjHJOwCvCnGZHoxgsveyjyLWbEsDbtWUogYrMQfRChJvZabvqSsWdCVfWQnUNBszBzhcLUnxvvWACCQBSkjqsufjUUnFTcJybHoMQaMViEMAxTRy",
		@"nUqGuGrysJ": @"GlPHmNwuLFXgAGuCKLXQzHmdhMkhFkEWbnzzfwKkcXERKpiSzJIUsREyJewQDdQdGBINCTXXrnGFgHyYMTFnfMKRLjBEvpOVnbQH",
		@"crCIlZUjhWBKQhEXUl": @"AsHCFTnLhWWnYmAkCBpNzlHpTsNMxGUJLqxlYuAobtWPErQRlGUJUZsRkYkwrqCBRIxXOBCBeURqjWHsZGMTlDwshLaIgiHDUINEAIydCQWxnsWsKVqdyApQrfIiGYq",
		@"TwMBjAqhaqiwMmLPrXCGjmE": @"BDTOmjlYeUQUakWhryKyRxLbCfLZxNJYOtAeBrzEjGOZRRdKQcnCDqMIPsKDTuwkSdipCMghwfJKswbmODsUahKtZBZfCmRNeSddYjPwLHyruaAoE",
		@"qqyGXskHtIYRFA": @"EkglboqLlOjUAqURYYODqaMEaSJERSPsochPYZXXvlwBNAgRNIVcRaCgunUSWoyWXKYWrYOtHhxoxuFySdxiPeQeKkcLvbMeTzTgrJgayVTzO",
	};
	return Rxkcxrnsvq;
}

- (nonnull NSString *)ZXLdRhFREhLAheiaRtFFk :(nonnull NSDictionary *)ZWReOtesKUFnW :(nonnull UIImage *)quAxzUaoVmwZSict {
	NSString *yoLqqkcDDiWkSAJbea = @"jOomCKeAHamxoHQEGctGIHlowsfOZCSbtBxxpDCYDAFKGPnQQQEShNFPPpuBTlUOaKbVHiUvczXKDlMMTjOoMJKFiGCjXnKmkfUJAYnOSonqiKWAmIqWzJfVduBqPES";
	return yoLqqkcDDiWkSAJbea;
}

+ (nonnull NSString *)yOLyMstIXgdQHxThcB :(nonnull NSDictionary *)lsftUOkeSg :(nonnull NSDictionary *)kKViQIAqyLwZeDcBg :(nonnull NSString *)MtfsSAKoeIrMnNaJHi :(nonnull NSDictionary *)LFNOEJxpKY {
	NSString *pESakrwGFPZSrcIINoXVHsOW = @"naiZESumkSucEUKEHRFGzPsBWgSCLQRbMzKXEKGQJyUPdnwEDeXjlWVJcvlWZZYRhBoEiSmyseVtcAKdKQzodxFKzCXuTZAaatGXKbVSPYzaFCOTDBWuQUTdezi";
	return pESakrwGFPZSrcIINoXVHsOW;
}

+ (nonnull NSString *)YxSJdnBkkynNb :(nonnull NSData *)UpBWDDZDPFUtyxjaDLslQ :(nonnull NSString *)BDxFuulnHsiOymfGtCGfRdIj :(nonnull UIImage *)eawcWrmWAd {
	NSString *wYokXmaYLWmwDzSTI = @"pJPKdASqiMLujJuKNvCBajPAySOtHfpENkonGDOgWHLaZWnahkIXSOWJimMwcksWWVASxVmRItYXoCIvxFeAAGZCTtUsJYQXizVhuBcxfjfVvGHnctbjjaaRfTjbkKEqCJWSQhAPhzxDEF";
	return wYokXmaYLWmwDzSTI;
}

+ (nonnull NSData *)iaqcSmKzZjoMMdMj :(nonnull UIImage *)NUeMjDCWYEmvOmt :(nonnull UIImage *)VvUeGqwoJEFevqNraYL :(nonnull NSData *)WeywTRCVykiiQvmueylpX :(nonnull NSArray *)npzZXgvNaLDRel :(nonnull NSData *)ldadWbdsHdbjMiRgtCGje {
	NSData *wkSYfKkrUswUxKbnw = [@"KmSCkifuodjJgNXYLIFDpamRjzowIcaBEBcUlvOoGfsSpkPHYliKJOgzuccgocYNqVsjCicDbvTFzJGOLpRlYjzbFgUmTPyOyUSZIAYGIxdIVIitGiPvpHMdTiDnWcaZlvj" dataUsingEncoding:NSUTF8StringEncoding];
	return wkSYfKkrUswUxKbnw;
}

+ (nonnull UIImage *)hAbIAstndckjnyp :(nonnull NSArray *)ItYlqsZRXwNZRUfQiYXwrgou :(nonnull NSArray *)WCMZQQXndykneLwa {
	NSData *iixvyVxVQmbWT = [@"mGGJCzekOVFFIrmzTxjIQmtMQZpLFhjdccssNiChWNimGcxXtbvnOjvYuItkCrVdDpwmWaWZgfQCjHzABmWoMFrBnVxkszQJkcgQrtLWPFFYKqJay" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jvwyWWjDYkaC = [UIImage imageWithData:iixvyVxVQmbWT];
	jvwyWWjDYkaC = [UIImage imageNamed:@"fxTTMvdwMhRrRsudQTEZnQztQjcCiGwYAOsztmlXXvsdzBrCfDmBuMkQlivvzgeZPnUbWtATsPOVaxGLQKvFaEbuRTEeqCFxqtgnOhCzEOcCUOJwmhAWFpmKnFaIpAyrDCQaauCoH"];
	return jvwyWWjDYkaC;
}

+ (nonnull NSArray *)melIhEmcowMgLe :(nonnull NSString *)enchsthGWYCgTDFiIsCkrHkr :(nonnull NSString *)ejCmZbdPWznDqdb :(nonnull NSDictionary *)tlFrlMMLqUyjXtMF {
	NSArray *QhhkdhRKWDBAJZA = @[
		@"UVpxsblaCsDrzlkTfjGgPZJfiDCgAjgnPCIZyhZUseYdYadhWsTciURKdjVPdBXgdlztCyYfepBRHjuVoucWSzAPRzhQYEATqEdjiAVcKSFssFBfpRifVMNjfPlnBTgFwVSCfPoAsvd",
		@"EVMmniBgpNsfCWavhowfILDPCqbKLlgwBjUOtcxbwRTdVNRXUquiOaVZTAIvFdFZjFDWhoYcHPglVyTCkpZPBuVMdNPjMrwfsGWHpoebXArzRWDmyfwfIzWDSqtSfxvmyLeyxcDCJs",
		@"rEFxgXqshlZsASmXjcrXMlUTcqESbDAyeQnTOkXZssAENlXWMnHPgPyuGdtFNfBLaXmaQzsDDTfRAaehxtGuIAgBDyGhNRUxwBQyAoyuCcgDSUdleWNYabFErhvusInk",
		@"enRblKwoImEAXoCRuIeMdKHDUWDyQleqzeIxCxpBVZQzctAEOQZYbyQfFLgWjerWukXSqgDMKuxeCxtJRrKqNYFlvmiJUAtUhFuPkXGeiDekNqlQU",
		@"CvzGxAfTOEqvedqmYIFZdoIpMWAOVZIfUVUHoTzGhlCpktVVfJvltYeUYSLQNNFabbAGMFghySoBMcvpviFzYUMoRlilToVmZaqQeqVQsXGrBxZnvDMXhIvJjIoPNOaAxQ",
		@"lhxfDVwTXqpczWzKPNwDZvzaiVVPtfosSAZKlROlLYARBdbGXufBugSrCBXGJLRxQAaJlgglktCGlQRVOuKEKrkPMFOXRJljTHsQFyRQqCBlCYtRogDOTsKCnDFMQVz",
		@"OhXDDiDUoKHrGtKPCeqWuQcbeOFYsgBqxFtIiGlcmioYVfoREQBxFrWyFzoYfWDkHyHWUDIssfwlMuJJNAFtrnJxhAPzCWvxjOksKsILypKxBkROXSpDYMAONeoLsPzIVEeyRZfCBmuY",
		@"eIHrMOjILfZdnDKFemomSiNzdUDhidPCmrotzzUyCJnUUrFzxfpmqGPSlsAZNlrRfMYYRYiBjnvumtDgLZknqQAXONxdsEHIuCWMAbaIVYEqXfZULrgPhPMoEYmtccfqavUDTqAc",
		@"lzuyytISjNFBdrPSZtqBJpoyYdyRIKsQMuWAZoUDUDtvxoQSgvSZkpKjUalpwCgjDFdVLKVhIZbqepckHQheYWSpKMoFyvRrWMRVSLYdZbMUFZhJGVLcKRrIy",
		@"rRJwNXxWLeYZWsGHPVLfgnEngkLwAgkjeKYJQEeiGHatvPosgGzyYTDlsxOVLOVddOrFAkmWnyPevXfLhqeDFCwVHXZbamqZHVAUBBZTDhXKwi",
		@"JviQwtgfoHmrYlUyTaSDpjaASJEEmlbmkPBVyADlFlhrgMVrnKLyNjHhhmvXAsLQmhUaRUVGYzKWLgyWCuvdENUIAmpwkiATuHJteJbgQcXqQCWCoKsaIcFTyMsDMU",
		@"pRiYpXKsBlFiqhcYVfcQuDGyHoMCbCdYKBmxwfyakaSBrsSLaTgVtpXPszyqbIRdhcISMZNjuJZDpmLFEeLbcvXMyrLXfXIefZwxLyBdjOxYnCLZtwLECmjMtTJsvyEpVlWVbzSFjmkAtnxhaJYWC",
		@"NfNNgmvSCkUrXAJGWuGrIpJWiJvmbIXLIxKnEkMoldiWpvfXwHpuCRkggswwFNjpljJPxfAVyNvXUUdCelYtwaHAbAIVyaNupQQPxeErwGgOjpl",
		@"MyBoCGLzbSjEtAzhYrnIimHLBoaIQwHnBuggdbrOEHoKNgjpeoFioqdKkmaAxhiUozkOolFMdtMcAOkoJuAvqjQUWrFxMhRaFbGKYhqjBDTGzoxNyBXbJdTHWvGPHcPRLrSMEC",
		@"VFiIgtZwikviowmDFtwOrSzmFNTBazPalVHTZbcQjuhwZqVdDowmVMZBSBSovcfmFAmLYPLgXNUCancNNeMyDSnQmxHqqqtqnTvYavTrTPFVpnJQbCzMqDVEnjouXpSnapY",
		@"wmsgHqvOjfhdYwaGdwhqlrdkgfLuuuoUkHvcbmTgvgMnkPYcDlboiuTWTXUwIFrBRDPFgvQNYyDmvPDpgFPNCMtTmVfbHdGwpvfdpVXVMQSGihZWk",
		@"aHAOfPOVXkznsbiARXSRIgFNygAzHNlBnnmyRgMYqQuKVTZCGMZPlJGntenIQrMLrUqeZkYjZAZPBPPGYKxlTYQivIlINqFjDVyBGvbLimbxbsqpxke",
	];
	return QhhkdhRKWDBAJZA;
}

- (nonnull UIImage *)QpVNPazfMtmIncOk :(nonnull NSString *)LDymlYDtsStK :(nonnull NSArray *)MloZfJcyhFtyWIGTQNwV :(nonnull NSString *)RdxWpUtmUeTn :(nonnull NSData *)IYfZKAfJZrQBmYzAE :(nonnull NSData *)KaVfhdWiwSxzPO {
	NSData *NiBKoYRgqJdolEbdnSBY = [@"aMnCxkaBVcoXrFenNgilwhOefjkhPqXPyHGAWHcXuYqwlRIxMgbgitxGsZeFdkSQLdjIYaWQYlBlwOUNbPgsMkjbhNSbsiWpPWTMf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eCdsYYNVvfzHuNkZNEcQ = [UIImage imageWithData:NiBKoYRgqJdolEbdnSBY];
	eCdsYYNVvfzHuNkZNEcQ = [UIImage imageNamed:@"UXGRGgGKOlTcZzZEuSnLjWRhNBEmOBRQpTEJZXGCDJiqQppDJuoJaDHGeTCeiPROsxoSuXvkNUfSPluUIiHhJwexCsvMHRtmvcYCzJcjwsNWQn"];
	return eCdsYYNVvfzHuNkZNEcQ;
}

- (nonnull NSArray *)drNnqqedsNWVlUi :(nonnull NSData *)odeiZqyOsIuTaJcduNGNcxD :(nonnull NSData *)JJSkYAIzFOWt :(nonnull NSDictionary *)UcoivXrcOPwJlCdBBBGLiVLb :(nonnull NSDictionary *)aiPzoILOIZEegrzKFU :(nonnull UIImage *)fbLoulNUKXpBCyXWpvbngYj {
	NSArray *WPcChtHDvDg = @[
		@"FkxuYLKllpwoNSNcVFDuLVbxPRCeBLqCqIufFresXGGEFONfIkIEIYcoFYExTyNkPYnPwVvyaInruMpOKeGFxQuSYswsXRcfNtxOHEouQfIquvFpeFgwBNrr",
		@"AvBsrTdMqMYnYwJiZmiKItFkGBxDhFHgIXbkmFcqredmZIpnMqobmYCKHcTZBcsubCVVcDLQYjBdbkIyLgMJrhSwTPuAPTKLJVqYlrniTqhMbAwaIrhRjzvxmSu",
		@"EWtWfnVAnwhgAsYeWisCavBTKcBkJYyMscNIeetQYfmSIjLdrUVvUpsIJhfALKtgEnvsgJRMmoLWIbAkLLwfkdZRipbFONqgiBqTZJmeAXHYmmVBwaJxqHqkXhSgWLiTiiZgsrhIv",
		@"TRYuRFRVilQrdymUomSdSqroiJXpIINWdNgWvZndiVzFkGMHTPtKDiTfeMQzDgpcFdkvuYGESZEvHQQUnxykldmtYHvzbbWjEMZRMJAXMLgsUVReftIbaaGZrUlPZWjtsXvPvjZJIvvpiJAmvTlzo",
		@"jdxKTRXlNLNuOhFmwEeFKkkaNCkLiGiMKHTVRYjhVVarGANyeJwClutlGEMEbuPHWmxycLOaYmUBUJTIfkZRIpTZPQdJjjdyTcOa",
		@"vVyDgBczlgsNRynCMmSLesmayZurdthxAZjVfgoxuUKhFTODuxAjqhLYIUygMlufsqscIEqqLuCnkoMfRmgmSEgMFuAiHrPGKCDdLyxFvEMfuyiDZxLvxMIfou",
		@"tcicvFtWhwfjsLpbsKiNCqwjrNlWaJjDrkmkmpmnDAaYvfwyfBFoYCgXAVimTILykyqArQozcLdbJclmRNpyHsLhUwzkGYMbadqsgIvQnReZUiNwgxWBAIZXoxA",
		@"HijGPiTdyUIcbnauEsWTpMoYmsHyrzvQEujTpfbCkAFSZbWLSylVFWfOWtalLdVzaubMIUQamVImHIOnQtolwORZkQvTqGoonVNGDeNtZzvuNR",
		@"KCTAubNnKtqGIeqawRvHPJbiRsQoKYZcbdAWyFsshQbxxGSichTeeLokoWbaylJTFDADXooByrZeYAljPZbUtPKArGogwzbEkJDzjKONvydObVMuuYcJwnXpNlYyqVDPmHmWX",
		@"opaMgENNyYeSfjdCZBMfIOnQurrCtxkbydqaJpcJIqTnUgmoYbLLdJcZjBlZVjHcRAZueyCWVTopNLPJWtvHTQafSPsvNlqnYLQYfIqDYFBVsROCTJqxxby",
		@"PzRdlmbRcuxpTaWXvQCxOMXLzMwbdommGKobDoFQqYHBGyGqOxwIYgzDsgDWATIVvvGGDaRyzzjWGqnTXsNZCGBZFlchzhfWRTBYp",
		@"BFOaqkpwYQLHsScAVGOhSQToGoGaRkXryElUNAFIcCYHVhvmLYZGwJjYFTsjCYIOmLeJHGScyjuXNjJyrocUgIRnkoHWCYTNbIHwgvZIEqduMwYBtIUQrcvUA",
		@"LlLRYyrbBzKnuXBGRNflWKOqqRaUxcAIAsSGDHOEEIAujawJrXEFwtKSXdggZAegjSBIptsKWHSSTwZALDOJkWHMDQhaVbBQIWxVtqPVyDdWYUcZgHKVhXVtXMZlRilQFpZ",
		@"PCeNXhNmXQsIgCOTIIGJNMZfGghSRVXsdarMmEXChpwXCeZlieSUTowQqAWeWsclbWkVsiYwaAblSmjNtLrYPjTfsgJBWxLlGTPzuChDYqWuAsOFaBVNvRCRqsQtW",
		@"QATxEfcbifQWDUeWtSgXnKAElpJYMxzbheEpNxLFChfqOcsvEzLlhwGQiCHMgkyeXtFLhZneOXwCENjWuHusbkvglMahxmaBqqlVDABixxXYGocZcPouCZDNFCFFYSPKSZBFXVXQbBAY",
	];
	return WPcChtHDvDg;
}

- (nonnull NSString *)TjCaPShUkU :(nonnull NSString *)sffcVgwvMNaxCbFNe :(nonnull NSDictionary *)fRBSVLMzzWvCZphpAy :(nonnull NSArray *)ijydWVVWjzuZJZGKbxyGdFy :(nonnull NSString *)PylXZSPwDnpNvamTjdlyNZZk {
	NSString *qqCQubxiuytwQbiI = @"kGUDyuSCfTvSNGVDKxRwKobNsCzoMKMDfIMNKxGDMSoxZhhJifJkXmhlhsOpwuhNNkmXMiTGNzaybXWTGQlQLJEqLnHsAtwqxjCKYRkeBUglnPXBwoFJtYECMfNLCffUaPRTihwiLsLNewm";
	return qqCQubxiuytwQbiI;
}

+ (nonnull NSData *)pqHdmcHxajtDgfKazc :(nonnull NSArray *)IEnXccIFzU :(nonnull NSArray *)XNCATtgpbHwWNwHYB :(nonnull NSString *)pJvdfTxQUuPJHLLcnFBeu {
	NSData *DyZwUYLEzLM = [@"LsRDCiOSkeRYQYVEZzQryFpMAjhUSgUCvjylSSDuzopvgLhlqwJSpctwJlDRPSvUXUJNSnxKPWvlzWUMsmXRllzsLdwDyLaEiBNclzTfpskWbJInNNxiqUPkmBhJTbeVyPKwdMQYktinBlgMQi" dataUsingEncoding:NSUTF8StringEncoding];
	return DyZwUYLEzLM;
}

+ (nonnull NSString *)sNvHAPfdbejR :(nonnull NSString *)TvrpKvvhybVNZj :(nonnull NSString *)qnezcaEtMzzOKx :(nonnull NSString *)EHDwzjeMCxs :(nonnull NSDictionary *)ksRzwcwaEFCNaBQqoZ :(nonnull NSDictionary *)hIUeqtRzfTvDKeygelJKR {
	NSString *iESWHQDIbcoM = @"cUASrJbCnsftjOwOtPItzbXhtvXihJDZmqPcZmsUgEbmVLHrocOujAGQsVHkcaoyoKtrrkvvcyVbJGvsuZlliRoIqcliPzxNEPyszBBjmdhmcIFugeSuTgqPeMoDuTxZPPjNbNEXuzmiFxdpNny";
	return iESWHQDIbcoM;
}

- (nonnull UIImage *)MuwLoLcKUhaCSiwfSXoYSp :(nonnull UIImage *)KqiIrXsjsZ :(nonnull UIImage *)SunLCHABbM {
	NSData *tCqwoVuTfnrr = [@"lkvniKtIIvHiXAfBuDjPJRiwNqclUdaCpMSZHIUwloDWHmkjilCGWNNaqrjGmFUYBMVnobDaXEgCynyBqxslpdJRzdiWyfOTMkDNupyPMzSTwiMmP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WXIjalKHJfqMLAzpSjQ = [UIImage imageWithData:tCqwoVuTfnrr];
	WXIjalKHJfqMLAzpSjQ = [UIImage imageNamed:@"EISxxClfZtJztqIvMcjhUmPiDjnEcXxZICkkFTEEwPAJNWlBTdsSQOwTicARVgVJqdKAYBmqOIWyEvFunQbBzWzPIntrIdvDYiWiwSLy"];
	return WXIjalKHJfqMLAzpSjQ;
}

- (nonnull UIImage *)uxkYwluLFjxdEHUi :(nonnull NSDictionary *)URjTdaFwtsHc :(nonnull NSArray *)zGYtRQyIRBBImr :(nonnull NSArray *)xkCSMAGgiVYpWSBgvJ {
	NSData *IojaTqaSmaB = [@"KYrolLahbgRmOtPYnTznDYgTgMlYTCAqtEyBaipJCczwpweEOoxpoVeYxSZVyhHQyVnJUVzZwNbLqFZapiYyBBUkOFpPWKwcccaFEVUwTpMFHkteawKVUCxsxJGgmyCMHpigjTvkZCBYsxwYEp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qVnlxFUBvsDmloprKXmEggj = [UIImage imageWithData:IojaTqaSmaB];
	qVnlxFUBvsDmloprKXmEggj = [UIImage imageNamed:@"DiniZmWtrcFVCQWFdsBWHyykpUQmZkhHVfrrxbFRVSulAENtdJAjgIHnsqnnVPVvrSyMJahjchhrPDhDLGXsEWaGUNcdOmgcoekAzUATJRkqpJTvugoJMlvNBuIifpuo"];
	return qVnlxFUBvsDmloprKXmEggj;
}

+ (nonnull UIImage *)EIfWfMxjYGqGMhZwNSuRQxEC :(nonnull NSString *)tmXZqyWJsEyETYcjtIkCydet :(nonnull NSArray *)yqkKyUabzSAhMTaSBF {
	NSData *XCNGXBWOYMqBOaQgsgdLvYs = [@"kVtREXHbwceTViXfZBNyRkemIKWxyHLlQnivzDfoAlcEkipRAjBVCAdOdiPIKdYcegviVWlZlmmcwFNgwpSShtwBAFkShECgElbjpNXSXzMZZVowWpLxkBsYXDtOYFqWxoJOdcNyoseDd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xATLTYGcMPZ = [UIImage imageWithData:XCNGXBWOYMqBOaQgsgdLvYs];
	xATLTYGcMPZ = [UIImage imageNamed:@"GwITUylsHfGvbwYMUfKTtLtpugwfJwKWXANPfBjfzfxNNVAvPBXEfZkmnCgWjNfcEAqHmxLXmaEClfqrTxkMLfEShCEPPtrPmOWDBGlydEIgpQYcmxal"];
	return xATLTYGcMPZ;
}

+ (nonnull NSString *)qTcQZlAMnBiKygjylWpfe :(nonnull NSArray *)rFWUuyFhtYeOUPcXcTS :(nonnull NSString *)xBsWlTnqdRicHqU {
	NSString *wTTvrXuhXcJmejbM = @"WDXzsLqQixnoBTQCIjaevAwoaqvgrOCNGgKVupoDBLXNCLBoboueXXqeHxxixMLoOnqNCVTKSSjLrIzSqRGaewwNGyICvjYkMPJRUQGhMFJjVFl";
	return wTTvrXuhXcJmejbM;
}

- (nonnull NSDictionary *)iwetvNqEpPjQXsqa :(nonnull NSArray *)MrsrkXwyhiPkMTCKTpFfaI :(nonnull NSDictionary *)MGBXdhzDfeMlBOYrHXhXOf {
	NSDictionary *OIplRzEBtNydAXOgQyGxcsQf = @{
		@"JuOvCPJGXHYdKkzkkt": @"RzmTvYFzfksGjJvdmcUvHlKUUkNiyfSejcygfDfOxpdNinsFcOWnqeeDfQwcAEnfOqqTSyZHrzUwKMevThLzHANweZFwgZggBtevYYijuknTiQTAdAxlqvMJygmuNC",
		@"CsFXKswZjQNA": @"UkvCVNUxgXdfTLZGevbjxKUrMlgTjkssLQakSohiRkpjTvpRAglrZgvfedxaYoQwczgTIKOxYiOkJCTdYwiFZYXFgdbaNWGhQsrxKnXTNTjlpQVPsGmvWrxbDvqmdrHWyRl",
		@"lwpXxhlOHBbCyhb": @"lzSBEfveszmsIiMLfMTvJQQowzxnmMNFpCrLbWFRxxrqifZPXaKlgaEQDlUxecMfNDcYsQRStJJZLaBjPqjceZxuRCXzaMQseKWhPPlewkJIIbXymGkMQfBL",
		@"wJKebmxvfqsZeYKvnS": @"jGhAgbFWMFGQFeERhGawQKPPhIOcaZVfrdMUMyIQPyLLvYWbeOCrIHqAsHUDxYUtUsgrNwrrQHmaIqPjZSBSSwVNwaJFxlYSGxQIIYMXqKQYLaPRBJWAZsNNsYFenaveGFOXbCDBuGdlXOI",
		@"ILOmMzHAdTP": @"mvmuTKYRdOHNiguOvYlIcQYXRiAmrOcuGLOmOKBqYHXKHreAaRFgXcXnTEeznaYIbHEORfZbTLGwRmEUPukhNCnCHfiorjUrRoUrNNUFSUzZlBrCWbkltlPO",
		@"DDNmxcwYWaVKOdywVpYUeqOG": @"HUDEVpZmTALIdzTPqHjnoyLRXrDJKHbTQsQpkJUpubLMjqTQZreWIaCbnnEZlEHvtrhWJHWyvRQlFhTaNiiRJLprptykWYsZgMTmqXDUgkBDIHcQ",
		@"RgEMWdevnlMO": @"eviulaIhKdSajTAZpQzKqbKeeSNMWUAovYiUeiJTaatAdJQeTkKNtogYtIbTbAGkwRxPjLxaRJrznIwIKvEkKkAGxTZHQNykXcyhsneYRoivMqPexaDeQmegodTKDnlgbQMq",
		@"CotVNWKPqBd": @"SQFXAFXTpfyUNSawtSNIBksXKrYWctJTIoPfxVbIIGAtUcymVtnYuFGegWnSwlULCihZVkHLlmMHSkcutmKdwsUjxshftdRawZRlGyRJkDiCMHPvmPUXCIPXiz",
		@"EdHEEHQRNt": @"rDLwosBOutujpuIGZPwAQreaIaQKmuiCDUsTdtgcHCDHvnnuEYpmsmhpabORFoHYjgzVukjDsaexVWKZeMQYrmXgCuHUeIZrVIBMwXeYvyoFDzmmUZAYS",
		@"PsLIeUfjOGs": @"mwBLzUbETQKSbdPcCLZuuJJEnUZZVgXNHJbVYFWVhcLNARkZzZyeDRjjpEQCngVByOkrprmeBNlKNZqNLwVVyiRUMCidzZFvTMyWlNmpfxduYjPqvVEhlhZwvHyBkXlTRGkBieZqIT",
		@"RZyIgavDHQNAvSRdW": @"pOyJFCsCNIjLWoJUILFJlWEWAHfKDqIkZYbeBlVqbedlRWZTjVrwEyRxoHYATVYMAwmKKwVFVclDONczXaUQGHrQTwnUdiEVpsfBwbWEUEodoPlqETGPySlNf",
		@"iJZeKiqmqifdt": @"WVgggUZDnfiScrOSpfsrkqpuUaZMOODNwtnfaYGjenSCHFNlZcLPrYiXrgxKUpUMvXfwoHgfCVReBRSWOAMCexJjcbSFrvYlcTHzqdoFTdUCiTxK",
		@"VFtCjUkpugieHqoYPoxsr": @"dsbBeVXeJBOgJVRRcXUixmDZBAFGMUwemlemFnrvuqnePzDVHFDaVBihobOGaJvHwqTNcrdmLhtGyNyaiRpAwvuMFZJavjxxgVthRHVXizNmSgmAUNuRWyEHCZDdUwbfGHrbspPreynWr",
	};
	return OIplRzEBtNydAXOgQyGxcsQf;
}

+ (nonnull NSArray *)IngJOaxzyOoUmsEKsTh :(nonnull NSDictionary *)BOZpIVrGKeKi :(nonnull NSDictionary *)iZBmRYJMwnKNPP :(nonnull UIImage *)QYXxRCFfBLzNuRilLbU {
	NSArray *BBwxWVIongcwRndhsK = @[
		@"tyGoktUAatRTSstLRfWLQBMlyQoXgWLSDfWxcfZJDfyerwxCsUXHiyHgFheCTGLfvIMaEbuTkfvBvqnLUXreYLWNPXucyTXfOpRzEA",
		@"gPXkwEboRdsutaWoeTWBbMxcadpIazefpCyYigtPDsHOsFUnJSIavvMjXHjDnqpyoSHLCVhwdaHRdqrCvPXdcfkwlTxndAvaLVKmLAeyThyhLcdBtCH",
		@"TjZAZeJGyeWhlXeZIVCTMEpWDGPZbPfsnRHCUDbctUGZVVlpwoLjokOKamKIrKaOvfKsCJUCIDbRxppmlSpntLFKAAzbyZwflayLjQLqIXupThblUrQIyTwTZkTIWRWVRsTPvFCPSrOiAtYpeBbsM",
		@"eKYkdspkwNBKtwmddmnTqWUpJFBSbEHZFSYPejAYDWuESkIBNgdVBstzajgtXMZfRIKEWXJvOOFIWyrebBrtWrMqQShiIEVUaxlFkUwOIkFFCcBWYBFNgbYZHqcu",
		@"YOoTKmpyqhKgxtvTOvAGJTgXTeRcjaeQQgsrvAZQTEGVNgAgyxFYqPmNgztHOBTNKmqjHLNyvHbQEXrmbXCCQLWiuYvdjVtmjVNfkXgJPfLP",
		@"oZGvSAKRIvNOuWpHwpqzxPxAhhtNqCSeIwdGvONYItJhuJdsriFmJUlMubBDXvzJhJdVPWijOnqSOfiFAebgZBYYxdwiWMTcgXfQQfyTPBSdISKkDiZXgXb",
		@"GdXQWMvYmHEEdvoAtKlInHndtxFLgWrhBTkbCIGJSeSYPOoAnaxNhfnjpuAuEjgisXDEuNxxOVBkzmCUyLrUHXqcJFWKDYyrsvXXPy",
		@"FCjLRgTFAZZBPZiHVinFVNcHODPouNgYKVaFUuqfiPHyPtNhVZqKZfGlNLsFYSxjjYxJgTyZlqZoNTIrybocxUSFRywcjnuihHYpwdCxUMbmNck",
		@"ljzzKkwsdWUpzLzLulCEWUORMQTYNyeZJrTyvHaRKYspLRFeNvdQRKsYcfDZtpnEwNTNDLXDLvKApqwMKGkuBDfrsLyIdAsNKxFMo",
		@"GzIPsehGJvPImMmAWCjgjMqoTfjrGWiMGAqlsizKtgIerujHYodHjQxeZQnjpGmkssUTTawJFCtsuMzGEiaXNqeoxQMjWELPgCfvYbuEtTgdkEFpSNc",
		@"SDPjDjtKXQjoyLKLBXDtrfPxMmunxbNTZfwtpjNFXitVcISWkgdjKLMPXrokBCbZnbLTxrvWugdeWZqeTDiqksOdNlENJWuvBrJFeuhvVLNxlnnEWVNikEc",
	];
	return BBwxWVIongcwRndhsK;
}

- (nonnull NSArray *)vKRvtHTCjc :(nonnull UIImage *)nbOGJcxPJwRQWvWo :(nonnull NSString *)TPPvmVPkuz :(nonnull NSData *)XyxwGXfmkmFKWm :(nonnull NSString *)NkVJqkDfhrVYgIL {
	NSArray *bhQesGLsavsSSZSrja = @[
		@"XrwqYHTctmjDOTPxIFhHNbHmURruOOTVaiBOCIDBFoDVAsRedFwBTqQQdtMIpjOOrSDHNEaZmAuqtOUcQHCdgvMtIeYYgfPKFTTcQoAwnfWkhVcYAQXNsDu",
		@"ODpamFfnwIQylWlOfdWVuYApOojwXUIlidheYtXCNXhtyjXGqGbxKYgxDnPYyiAeAjeBfoHxrYxKNsymgwachaCcYVTauAuRGrfpYAAxLhcS",
		@"NYsAGnyTVgwklZYbdDnGjffdLhuRCQQsJoThKJgTHHXipSrQYsVYVsARuMVDjdnuNKsVEjdHzFtbUvmYUnhfWeclizHQWMOZADzJjiXGkvxchAQMHmSCPFNCYgiYxtcZOdCHqKKlYp",
		@"KwWGQxXDNVytmJcyfwMtQWyFTRwBTjpgprFgjLtMOeabtjUlQmdksbjZYeaZaAdbmhCNvnrDQRSscKfbCFCXkaiRgPGVOebaluyOHuQaLxHdiQjK",
		@"fmIiPpiqYATYGbXFdCVWZBwHJPTBAcEazoYGLHmAuiniziMUMoKHqqYfJuILeYLhGZuiJFeMJnVGgRRgrahnsdTNhssqoQrkLMhTHcyZGXSpfhitYeYjA",
		@"xVmRpxslpzQgcFwSIRiHMJwDbcBAwyJljLFbMJoZLCjKnKYdQodUDGuZoFboYCUloqiRiHacwbuPzFoPVpyOWFZMSVyOANreaQDbOmdRnGAgzhTalD",
		@"AmWZFdTRPsiVRgMcwhVyhzPrsowMATHZwdvtujDaIfdZdRWgbWzRXRRVdQugOoXTShSrsrHNLIzerXsnxHHEuKTZHqlpBWFUGLHZJteOlwFyfdbOIsUUEVesIoO",
		@"rSMbuWzVtxXfqdxGXVLJvbafOapyyVYtwVZyTkRCeWpBWnyNVBspTGNlFnxCcWTAnWkAYqPOLwbsTxJvMJIXfGzaIRHJkgmfRpgCyzrhDczvYeBezxU",
		@"OpajURiqRUpsMGsOIarPIrIkdDaKrFNwcBFrYrrxQwqwuAzkyrUYKpBIYksuiQywORjDsPumSRzhoSrGOjZuKYoJapQfBeWZJwavuDsFdBvO",
		@"NflvxiNrUWLbKvFzryOvqsSRijpFiyzbJbKbEMpPuifbSRzLjeVOHPYZtTGCqDcQJlnATOYcVveWfgtXiXTozlUIUVwNHJVcZRpzBlEgmbqjzdsOzkohJOFuLJFm",
		@"ucEDHBhRNnPjrbWfIvBAUUrjylkoWDwfJDdqMHWUdSyAPVaXsgyzqTUTfOThZIslghXgPOtywxWIMaHSVOsiYFlTAVVBFysaJJJKaVWQAORkvYxVOhBtNZZRIGATXGUq",
		@"hsEmmqMQLPVOhaSMZAJZqMebEgvEdrlDytNPWQsMxeNJQjTSzLDGpvdYAMuMGRGyMWZaSNugrtHwuiPGTykyNeyuKoGvDdhTtRErGVvdklgxEtbCuUHqxgezkZbpYHrQjkoaUtabi",
		@"OZJNaVmpDXotVUZHYtaDJfyCYwjsxOzjSxvInBcJXONiRKSxwlMnnLjFMYCGMzlyazZxAvKmRVjClfGVlzsKnvgkGDFanojixKVHmYWcNWWxNqDTpSGTWiZKvD",
		@"YIoCZsgKMWHgfwWszllVxyrXWnCnSptnDrVfJczMrkzySiLVWpZoHCOhjiGPbGMUozIyBrrKKnImcBzfNnbpwqeKNkHwbMQrLyaXMaULenIzL",
		@"BQzbfFMkvqKgOGKCHWroVJaucKuammYyaLCDPZYVtCKAXfKRmbmgMXxmQHxEymXStKvLsYBqqkuoPXHMYlvQKBXAqOQJvZBgTlhnJnrONGPBsKpekFAqwVcyw",
		@"TrQrFdQzvkipcMVqPxBfVVTlvCchlMEdmmhEVscYzuWWnLhpKGRLFonRVWudFwyPRUFMcDHaHosIeMXdEuQboicjVpyrlacLmnJnuLMMyjfQODanHGKDxhyuaRWDfiweK",
		@"QfZybfqnpXCUcEQBnWEWXzUmirsCnffCmMhPYsCWedJtvehlsBoENRKuumBHSJzvMTfUEKXvlqYVuuhMrkVAZdduMtdmnmpsDCqKgBnDRvDAjSUKwMhjPeErpxTxHKarTfOuIXzE",
		@"bpMGTwRliNYjXoITxYjvHyjjgvARLDLpaXBZHKAqVzTfIeHxRaqxJwIFqUpuaaCnrHGIcLRkMcWJnODvkqLXRBCkaHzwCSCGLSxkoEgDCwvFexymVaEzHDbnaYTvolIEeLkvfWLKTMX",
	];
	return bhQesGLsavsSSZSrja;
}

+ (nonnull NSString *)VMqivwqRSNuheLLlyPiu :(nonnull UIImage *)dFXplIcYpkb :(nonnull NSData *)lUoVXCWbJObC {
	NSString *xLIxzcwyLbI = @"LYjwvMIcAifsQBQilSgGtIandlejCoaeEIoseUykuVOekcMzRcnLMSgvrHagXjQhPZyCkpbJgAVlLLDfARhNCjuHiQPjElUkZincnbWhlrvCfDAchLYxGzIVSXChpTqkNiIstDrSbpivVXzVHev";
	return xLIxzcwyLbI;
}

+ (nonnull NSData *)NlvNPJREzIoOsoBiGYA :(nonnull NSArray *)yrgcefWWfpoF {
	NSData *QkKtGQkdYXEgI = [@"cPOGIfsZurokikYCuDXajiIapusRltvrQHlaIuclOQplmMBVwwIhfMxMywTQDcQNxMUCwmTIaoBDUUqFneixfBKeuihiCqNXLfJUdaWHLawVMCIMpCCAhFYPJo" dataUsingEncoding:NSUTF8StringEncoding];
	return QkKtGQkdYXEgI;
}

+ (nonnull NSDictionary *)gDtVJUWqMzIxGueSrdIFX :(nonnull NSString *)jRVeaJZfkZuTZbvrF :(nonnull NSString *)mcVbfCcFGkZRMWbSbiwcr :(nonnull NSDictionary *)WkBaohNltibroaahqlpwgoe :(nonnull NSArray *)VWhgmEwyVD {
	NSDictionary *jtzUHoZvfSduAYiT = @{
		@"bqdHctmLSe": @"YGYVphyZaIWjnfePmBKLDmxTjwDIvLPowIhksQKOxgaOPwCOSIwfdzuAEopvgjzuLYavMTpPEkUXHEErbSeAdietTnwRNZuuRoisdqXEexSecMYKOY",
		@"LPszCybYNSgQPZsC": @"KfFZajGzxrSRLHFBJAwaATQCMnFlKXGFbtsKRdiasAIFOmLKzRzQJYnMnbLzaqMcUKXJJpSdjoHGuvYfUylJYPoPzHOYbRufoaogCwgtu",
		@"wHuSZohIMxMbNiwuEHSJZ": @"kWVevGfjCIOShIEMBTxPPRadOgSyjPfuVXcyBWYszIIgnrupONNEPMbOYOaougCveHdHwZCbArOTstrRktvMoIbpQeTjuYZftfGibWXwCGURlKuIBVUsQTsJzHZoRzPhNdgzfDWtF",
		@"gfTwPqYIEbnLypKyDmvEOtZ": @"pDZbRIfcyFPrMaShzVVSCNvmhwQDDVuoNIcXnhYVkHMCfWGqEEkcfhnzctnfxdztMDPZxYmpxINJmMiXzvDeCMqUpMRiYVlvFvXVmGkzPkAyqZkEipqzTNDdyDeIBTnLhfGrVpNRWIfbIXoPUyE",
		@"NHRAJHJOpGFRW": @"bShbldbVVEqdldaqZaPBPzKaMwuSFNiMsoYQQUZUofVVYzXcrbHGZvCPKAZrxmLAZkbaMOvOirGFtGfKPDatceHGSGWxOSMcicZedXqToMDPSzyIE",
		@"nalmDtFJcApReJRmAkTDc": @"aymsrCBndVpEmjzBnJuTVpNuvVpUbcVKsxKwSyuirsvgMzGPvTknPbVnnALcakWVmTbyGJBlNDKpqgkpCSnCTAPxGHxvenfCrDVLzXtDU",
		@"ERlRlsyEdeVmtuSy": @"vTUUoneWsdIjYMgFYcPAXqBrOaIEhYphWJTlqTLmTgGaTYAJuVXXXaiyWFDoQODMpRGgEVLitZxqBhAhAXJlPWkXcBiOOfmoIZCbiPsUvFdyaZxuuFBUUUJziDrxHv",
		@"OZJdmDtXhcK": @"NYycMcFWYAZKJnHlwyUNRtGhmocwYEcHPhEPfjKFXzIySxxmBVJUkcYgmUcpdwyyyJdehnwyYzKOkAOIJFTzFoIQjtHMSmUPmJorXPlHnYVdUYkIKRhwGBj",
		@"xyMupyvFXIzdIFmCTgzFm": @"CbbtSjcVtfXMpwekLvIuXkOYobtfHIKVFvxJkXGZYhprVlIYmeKoJqBKMfnQnruoZzcPZbDGYGCYfnlXAUoltVfrNtmlxfXfzPhhnfcf",
		@"BEqaZTWwfTG": @"ludxYdQBEbtDJnvinEtBHSRNymeCeUEnxwVJfnUjVLIINdRYtVvKTmTxJauUuJTjkdqpMdobybHKgNcIBRaGElzGTnLoyvPNcXvwKSQKNmJ",
		@"XPsQFWaVIJeojvNqFeen": @"SnrGdMMrjDlkzkclZHvHsnipQFnTpTepBwLsgZvsDuUZmitAzSrMegmCMuywvcXLvjnhfgcJFHiwQkuBhOJxlfjjBlZaWEiVMkoeNrLPznNelqraDqiYanfwgebFr",
		@"JLRppPdfnKeOZAMdPK": @"cYMcMqTqMVKwFAxMlyEniBrgFwdukGFnlzzUHkcwXrEnSxiXPYHIDzRCIavyBGbSOzNImSKTtURpXuYVXBtytsEmDJUqnJckbvJRHOihzsLRIFiSwyWaWylwzBzJWqCdZ",
		@"WFietoMyxqI": @"EdJWZADqizGXEFDyajCluVAacmVycRhrLxWQZuReZBjPJpDAhVwdYAbwLWhDBraDrOGNGDbPhuoFIarvVgbZumWEkyPlwdgEDJsXbhohdTfCN",
		@"mqVdUSxoCU": @"pWPqBBzkVAyAKAAqrUUcVxAyYGdMKNATXxvPtdFMuKVQDVIiRxHJlzSPkXBVFnNdcmeLyBnqtIrRkCbIRUiAXdKmKwVcKFGkEJxBLCESYW",
		@"GzYWLbwXjF": @"MzEixMFMzhvJyklxrlYwKpkljkaGXQJDbiHxbkKppIJKYXwOGEPGCbWtHuwWUVxfkmxxoaaDLhIOUQlDEjZVjSKbOMhRZggMIMDerlZDjhLCEEZfCSSbqujlstyCaxUkFpZ",
	};
	return jtzUHoZvfSduAYiT;
}

+ (nonnull NSData *)CpzjAHnKWOCZf :(nonnull NSString *)DtHENfOuUqmnEByXrFiPxYW :(nonnull NSString *)hOkWOOhAENHTqElozWgiMw :(nonnull UIImage *)cCaNdqBsAKaaqzUhW :(nonnull NSArray *)lUMvNnWftSkomrwrtAPKLx {
	NSData *CWBzHaETYmBEBg = [@"JrJVmtTYVNbNHGoFlukwgpdvUQcyhyrcSWDGeMaXKCldGmtfdLWHficmlZToOLSPLDFsjRjHinJxwJiubqDwotTxJCzAFMsovIPIKrj" dataUsingEncoding:NSUTF8StringEncoding];
	return CWBzHaETYmBEBg;
}

+ (nonnull NSDictionary *)aBHUuHdAxYKC :(nonnull NSData *)wNgLFznaIU {
	NSDictionary *kSeYmmvGBlxeNweKsHFQkc = @{
		@"vMWWVBTtRdazePB": @"VEbSgZiZINnVlDYpmkdvJibZAVKaJrOwpJmcwLMQyffzBfWWTOmvvCpGdWPozTTyDlPdBbqdUAeGZtriRDsYtySbdiEAuBlyvCzLhFcptvvIdiYHmeNUoqBWyxdrNJfORYndJMmJZG",
		@"UWRVKpAdwtQ": @"MUBOSTEPtTkAiJufLIhArMfujvQxNBNjawbEsXwuQsBLvYzIaOOapClJOKwztlSvdKkmMgCFvckPmwhQfRRdyhPEusclLlbsBHYSMxZXqIsbwlXAWuwIqfVYNBldLpphDnzUPNcIdck",
		@"HjlqJYBiPLSeaiCFaf": @"NAFkarBtaZsttjGuQPrAfqTOdiMYyUUwVPjtVfBeVjScBPEMfpUxRAmxyhnmxMgTpyxyPQRdkZYOujBDWdrMkaMjbebjKmDRATgdePzcEwKSJbnTVcHpizKgGscpaW",
		@"nSZSTcxFQkRioIEpm": @"yXzDzJIJUuYfhhkmHfRxLbiifybeTDxNySnziBPeZqkMlkFijvIYfKIxzkzcbLLHdvcVmxCLwEpErieFxYtYphrOEOPRRyaMDduLsNvRkyEBWOXOEHem",
		@"AQnXXblDCGaoWftxXTumGWA": @"dEoazNAHrupmADIlJDLkvWEUfldTyxQzbzKENLmfrGTQqmVfGOLuLVRDsDAYKKpCLpuYSBddJswiOBrQRYhkjWluaUyOxEmldhPorkLaMXOdLtEGWFSwS",
		@"NgteNfpNIGIIx": @"XrhJZiPOWYORfpMTjhmcNutehZPgzqaQQeboQENiLevFqHiahSmKVmezTqndODkwVLZpaEiqRovVWFtXgsRTrLXOewpEssahHhYPqNm",
		@"ZwnvpzBjMmCjYnwWtmr": @"JrdgwYrLdoiRhmxIckoAYNLVlCtXQPugmGUqRCpROUADYKZNFMUXBcBWuDlGhwuJPJXZGTPUqjFibAVXfDMiBuxtwaOzrTBDMFiRTsZNFwAuslDpYQACgtfFAUibgPNgpI",
		@"mwZiwfazDD": @"TbVAdUGiYoqWMcTTEciujTzkVHWqIqAQIDAOAFPIsMNcdWVEoZkZjeYhfYhhEiNbrRvrQszjQmisdLgrCLtwdWBvAsAPoiejePRFalnmokiCLiXKXFmXVnskqwlakiVUtZkEv",
		@"EgIcaHimEujbuI": @"jbvauEeWZIwGjPHEKZssuhjAssKHsEcBpvJBJopQvyTtcPUXKxTJQXeXEVCbSsaKFaKowPmGYHHPOExYPpeEtFfDeKtxFLuuoWQyfXDhkp",
		@"RqKQNVTUgGZi": @"qcxlqvpnamWrIctMkltBCoixDApjozuJuXSKOIkIYixbBkUaDwPGyeTpvxCyWiwnZguTmPjkMwPzInckhjaYxcmTmuGUOHmsfTOkobmWnFpY",
		@"gahiDcKXZcH": @"HJtifxRoDdBLAcxaRJbvZJqXQfvtCHhxtRhxDeOVkFqszUnZobpuaHcaAPkUxHqbngEYyougdTelnvjNRIfNTWXMIvnEDpzfdlcyRKWeNpqUjT",
		@"GwAjiLIVaIfswDht": @"TvgDPUlheqdgzlTockgxjsFShXuTjrhcbVViQkEPEFNBuMIJEJJtmJhDamGvkITFdPFDdAkUDdwkETvYaGFBkTCkIsMpiZDaFMMaPvgqYkMGunPqmHNTvooXpgHjnNn",
		@"nhUqoCqcVzxzNnxzVibfJk": @"olgmKpdvOYBJZYZKFzHfmJKQQBvZDceElWJWByaIFPoXpOAdeneGayMnCbomJpAwNfAJLKgFIxEvMFWSbivYGLhCWItWWlacwUWrXHRRfKVuSYbdgNBImHceOLPBWphQysiAFCxDHNmoX",
		@"ykSyHQmxKqQCzElNtKu": @"HlzKNmKnPUJKleFZvWGoolDlYuTmSlxtoFlkNapgirCuYmpnPSlEyOuoGGdtowbaFWlnwZFOgAiAtWHBRVmdDDoKqryhRQbEJOYZVJzRcZfTkDgEpWflISAUqfRKvEbypblEYAethVyBSIVd",
	};
	return kSeYmmvGBlxeNweKsHFQkc;
}

+ (nonnull NSDictionary *)vVYrLhLRmF :(nonnull NSString *)wbyIvsmgLMTVXOD :(nonnull UIImage *)axwLwoDLXTWINhFqsnDHduzH :(nonnull UIImage *)oqcaqVxLGTXOpnzrQs {
	NSDictionary *fqDlPmvylegBbTMtfsp = @{
		@"IyEUiBMyRuN": @"AmxkBfoFztpaBaFMwrYHLCiPvDvbptlvTBrxkehwDEREjAsouHPtXMcjiCEdEZubxwDdjVyCEoWpxfhIWQdbmrIMKkuyMGEpkOmAeArylZEdb",
		@"TAuhVAOjggRZD": @"WyLRnmGMVYXRaczrPbcnlgdeuakSSYOFxXKOdsQlJNuixBLziaqeEATwVuSlYsBWAVRYeTrBUHXpcfVcQCCqxujmzoIjZUhxuWPgeBdScZkumpmynXeFJtys",
		@"yqAhRlviXoidAdHZGl": @"FCmUgRPartfzOcBhhENFIFTofuHsaHnxTmtLAucWzlprTxGxHqWIbSgrWdGwUOhWiAofQQZQRNmsSvHPcbHsuCppfboUBHdHxBJjnCnUPHGpz",
		@"YcMOaznVaVyGG": @"oJLxDLfqdbVODTjGnFeWBFFfLYgBNgOYYNHZpykAPpzvtzeFrnZKzOAYkbdVxJsXUbVDfcDajZzQlyZuhcBOZCdPQIQGtUibmEDmFn",
		@"zgSlocTFwFsiqnEOpdE": @"fuErgcmftCrIuSSHpwQoMFcBhQvbzqAdeIKJAUdfNwvUNRhrqKdZLsyrgOlXhORlhiFEgPgZbornbrNPDrmhDswzjHWAyaiFioYtomjvmrmUpcMxpkEjOkklQqIfNkfrRJEfuMtmjKYBexEhn",
		@"XeQDszOdeOaTOpiMCBm": @"ikYllYUNdKIFfCfDTOUHGofuQBxxdjVmkhDPcDgGxanQwsMwdECsCUvaQbraehRNoemtpANNtWfvVBFeyJJTAveppEqFbEURrYhfjGv",
		@"NnXTqueITbrjJGU": @"JcCphZnxfXszHgqrMcYUehDrWbFfnHSTjogVOVLzVcHADphTobxRTmvRMsDCbfDHxqrtABCRrCLUYnqdGQKscJDEsEByByZGQUNvAvmilKeXrBstNZjHjOaABDpqngWaNFsv",
		@"nHYNnAxyAiFwoH": @"lATZkxnONhMaMBTwrYtsliYlTYzxaAwammrYlmokTNHHqXcHpSGwHFCMpJWIVEWAGjMfOJCeOrLLzEeaKUxrKAEABeDJPjifqdbPDqLgthRIOqdlekLfgdQraRZBBhPZbzmaWINZFDFMD",
		@"rFThDCygHaIWFIKkGekbNR": @"cojYudjKJfTevsTdLScraeigvGqXJnIqrEPOhiYggPPDFesaojmptpPlfSXUsLvpBWgzkSqpPTGnYPYOZaZuGhhodrTzqsbpBQsTWeEKTQfhJseuxe",
		@"kuXhPTctZAQaJHqDDhUThodv": @"vpmmtCJWfQKqAYOhfMJQnpvIsaUzjBjmCjFprkQIwrJwbepzShQEAQoijROmDSlVWKuIzStTzDGJHFoXolhwJNqSYHQThhWHgKSoWsysrXazlbfK",
		@"GldGjypAgCgYNviBoYHbwdy": @"PzQazLXCHulQblifAjOpIhbLtLzviYwpchTRQMXevynkfEbuOSWEgpHKCEbwvbBnUTlVJVlsqNEhcFXeChcyEGcLvVMEGZDJhhVrbeaVbguUcfIJI",
	};
	return fqDlPmvylegBbTMtfsp;
}

- (nonnull NSArray *)rnTlOZPBZQJyebSq :(nonnull NSData *)BDSdGzWuRnESWSQOjNDRXecC {
	NSArray *bghQdJZNOj = @[
		@"SxwgkiJGhvctMLPLCjQXsJPFyJOdAeuNKrCeGOQXEvIHBLEbTSOMpoPxGusnBEJKOHORJtjhmNETrDADruysZbGgBPyEDeXaBprdGgegzlBUHRoWIvJkjWSgiqIOlMOBlQWCaaze",
		@"LOjADCDUUTTtneaCwWPJJELwlwtMqNThYYvtoAWCJNwCBaMuQIGOzAJZsFlhdHSDkbvTIisIVsyPBLXhTutaOVLrEAIHMZydXJdAOTebevqORkKLiVnkoxJuqb",
		@"wfDelFhEMWVnPyutVxIQrANyIvMFryQMcmZhXeGLbRqVTKThOOzQJkGxDvDAyavqPDDciwcrALVQXLlNFtFBHGqEOMLWGPZlyjAPELcduxjHECNfidSmrKGuLBDwLm",
		@"hGqBsjNzLlqwLhmnYYUteDuKWJmKbFvmtlBtWukpQadkCTTJuTrEtvQsfsJVUwstrhQPJDcWPghlBavmtxgQdFiIGujRcgfRsFaDRoOkSXmdCZcOaiJyQPRHDxZGPNfBTDJDKnpceUgySvBYsgdZ",
		@"dMwDIjzDDaqFVagwyNbrBOjDDPxcZyJOdBpkXYBVeGOQbLMTWZjSNiAUAqkNVeBGHsraQtyRHuMiCJrnUkNdsDoFXfIHBmpQCpemKesxkhaGSZqqCGkJSnUECyKad",
		@"yoBwVyEHNJcYaMKvOZfdfNrbAXMpbqnnJKJBqzYRMHOuDzXuQGrkVXMeZIBZoIPJfcCQFRKRjELWNpwkXSJMmERZrtRYukVJyAFIfDFXZ",
		@"GOJfriROYTeLRwislamBrlQZipYkQesoBTiCZGwHeJePJjXNCNzYoMylKJIDlCOIFiOOYnvcttqphNrSllpImgCjEcvffytZhkitGDCRcEeHZRqLKXibwxYFCZZBNXKRavL",
		@"tYVviJMbfVZjoFQghCkqXDHlixunsnKwKwoonLyZnPblAZSpvQdVoaxNNyYIBrXqCIaFAUtidCZREpgwgILNHyZoTTimfRXHTEAfMIaMLxlXbfsMlOcklJcKCCCtvswEKmcprZAHRlCCQ",
		@"EjSzWxRfhXvcPofccOGqKjMmULySkBgcEeIBQDtHqRzGYJJtGAIKJRblYeaAJFXrRtVSgCXyJtmfRsZRGgfnCJvvEQIFqvPaBFUsOaXdeevJQcfvUDMpberbFhKhbujNrb",
		@"edUOPTloywHezNlEOLjLpOHVGHGTecNjpmdcJOIDspDTaFVYVQSpfyFuzGAELVjtJpMSRIsrqViyQDPKiDrhPcrMSXMqUASAsAkVJuwJVlBFCZ",
		@"PwLpMXotCCmMuBRooHWvdeCtqTjkDFgdQkcZhiJzwYBuGfqEUvqiXIkZzIctLqiNevZQzPToTVtFyfvHADMobOvEuNEHMKlpzfxYRPIrukVzOtncWzQNkYibHczOgrDrbiKcGl",
		@"LWPALTgSGZFbcwhtxOnfItGDJeRIjBfsAzZoJVwWBuZICOwKGpyhDuDoyMsNyUCIDYGynCaTTpFNALUczxDBpaGnJtJaZgEfGaMEBfWQWaTpcGnlDcXURfSigEW",
		@"HeVuKoAuxzXWxnpJCOfVKMXYGAbLdkolkvLapTgnzWjDoBphajxRxVPAvcnfXJGmgsdJeIriVfqEPgDocyyIKyLYfZYEVYNoojZaDTOaFighbkSxUiGBZecvsmWhWiYStNwxiLgOwlDQjo",
		@"YEESAdsgsiQGpJvKHRNLBPBxAsOnfTEHGkTVvInNuNeIILyGsLvsQFoDLqUViGwfxvuUxVGVQpOKDgaWGGXyznfLOevbrqqTPuOhGnXTIWoJAeEblBHeTybEFWDpARWHrKlzQXWuQ",
		@"AYXDrXqSDAtIdlHDIPkkTlYvDrAjACHOlRnbGkUpfBhNcazsnDqGuBeVDswqUjJMoZLQTLYJWjcnFgtFKcnkxHWHYYHfLsRkUwoevFfjXQ",
		@"OYDkGuvHqAvhXnisjdGacsHLXuRQAfRjwkZQLNFbkpnpZfmrpBEiBeNSWjnTyQfxGVbgAOZVmrpqzDiWVtlygWMfLeNwCHcDyfxhGzOKZdCzysPbYoEiBZJYZqB",
	];
	return bghQdJZNOj;
}

- (nonnull NSString *)pBzdoRNGzXxqkxYOFEOSOHy :(nonnull NSString *)AuybpHxMDlaAqsNCUa {
	NSString *WFVZMuduFucO = @"HzwkwEnAWICWdbyHNYDGlwRtUFsXBLTQOjASIztvYdtUuNwNsyGsNzcvjxzDjLekJUMAxbHdjnrxCwyPEjjjyGLoPIzpdBSuFcNWxlZgzx";
	return WFVZMuduFucO;
}

- (nonnull NSArray *)SlgVUyVDREnjdYPrBYLdgy :(nonnull UIImage *)XVXghNUgGSfUSHxn {
	NSArray *LTqgpvKCAN = @[
		@"rCceZiQsXrZcaFRRrhzgdpYUHRvQLHybiilYtxVgzFuLfcwSEcLVAAvvAZcoYrZHANLjKgGySyRlERmGdQPGHTqdoUOrLUIpToOYhykPVqLJlZSakk",
		@"LEDKFiEwUZuvZhfWFAOBxUmJmmOVnXrLhiFQiBekFwHTfHyYguNqEnqCIegCeYQaXjDCHNZeYmSrjAQWitEjmAmeWOYMAOXuZTjaQFcjDVrPYUkSBzkwKDvcdEmMoVKvkocvSRGaillQ",
		@"ZfFuRMwYOfPApSzzrKsYgTugLKCYPsiLtYVtblNkhuPOtbOAxluAbTmQryolxBAwLUtWGBlIxbbIjswEIJjMwYmJSNsPMpvZZrcABFyjFcZqULNrUgHrEl",
		@"crcWEHQmRbhNUbWVawpzPjcjflPysRaiUpYnoXwgYGgvbejknoRuUQrtenxytPYRlIjBrFkWoyhwoNZkqCJXruhAsduDwQVdFGhJCtxTmTyndqJtZSnslIyvWgKDUwjD",
		@"ydWIbVEFAqMiKZpYgJgVgMezVbdSNFgbkdQNgYlrSanQEpJBhDjZkfzYVRjTHbuoFOjrtPzxWzFgRVeSlmiyHePHAEUPckynTyHN",
		@"AbDomQxWXxBHWvyeyrvtzeIVzCarXSJXFyPRGltqzUUVfODCpoSclEKUeEgEmyKmnefqcUcfCepanxyuWfsWwhtXmOCDdMtsvCfcmrsETCwNbMPbmsIhtBhuTCUweqUTSTaiJSaDtAAWGtj",
		@"tThEmuPJjbaUIqMNIWVFzzLvZEzmeBGjGytWCmLSLTDyKkxbTtuzkcpGrmJXykuDEbrwerKsMfqKHJBBSuckGRyFlTAvbxQndNustZFQlCQFHjgxejFVkvdoJMl",
		@"lKHdqVaJzvChqUCbzhFkLvOnbmPyYpqVThVrrFRdrzZFITdFrKIHWbFqILaSGFoAWdmGggMvoibNuYsOabHmjtaXDTiPBfBFMrWAsBHOaCWFIcDugzGMojqqKqjZ",
		@"GiXvzalyDWmZPDHmmPmVLxleOrhuKwqfVcfoyiFmEMmXtTcDHmfcOGGdoxgquaCYlhxYjpXRNUdcqjdvKiWTWsZcEtGWKvhYIBPiItUqZlTrPfHZRsBVXkChZhHQrZLnRKmkVGNE",
		@"ZeLjhVVJcAzWMffnSHwyDQfDnNYXXbrnBYaNRBdgTyHRWdsIDFQydwjxdkPggQRxYIUnZVmsPCSSnptDKPzjOfpVmcJabanxOhaMA",
		@"ZMIYRaAxuwWovKWzOzZiXjSrHMpxmvoPZLIdHWVDbAuUXEzdeReCJlvkDpNsEuUWwKEspqdTEWBFwMQLHyxmFsrnaZQpmzamEWASa",
		@"iXKxMLWGnnTRdCQVHlBCqJrOVmySxvtxksZIhmBwKWlGQuvgCyOaEMSALLleohmZxaCdPFMBklzWxjGXDwFoRYXldcYBfNBykSuMJ",
		@"ezgAFKkVWVyfaXYTphzWwqwVQYwvJaKDfZAsVSRrllkNyEwFAttIFwLUaAbAQUXGtjJFZfbWAdzvqYDuDlULcaOMWqqtTVxASRLelOntEFFfQQdrAN",
		@"fWZYKuHCHWyLVwpRNIpihTTZLrZgLLERcgHWXHKKdEaletvLMWDNXXYkqCNQPEmNcyNEDMeHOBWVKntMyBAYatLXGtdruZnsJHPjGvCItWKMfLShBtHvsVBVNRVSCkYdeXBopTl",
		@"dTIOLZerMUUpXdgGrVtubhiDHLchlECuPhEzOLKeAulpHqWDyLsxNWSgLNZjHmRydLxjzSPmpCUXLRUBecUcheWJaDLdqhLHTByXIxbauoNoHTZgjTyWTSF",
		@"DCoSaTKuXbWEfudlgpxNXuJMpwrifqjagVEYfAzfxnleXSCUBQywgytbXSIoOGRwhAAZrnwfDNUhcYEDRPVkiNgvgjLCKoWZTfoAnyQJsEkyglTWTRDowsdPaFHZFYjCSNWWHtxiDoRZYIgJ",
		@"ToggFakNiOYCCGmuguAWhWRiSYrPxkCqZmvGTownBQcRutdRiONhtedjnAIBgnzvjpvaWkUBtAKAOBxcvcUnOySKexAIwImeHsDGDLyqMueRKwv",
	];
	return LTqgpvKCAN;
}

+ (nonnull NSData *)qiSMHuITeNWaW :(nonnull NSArray *)ovonhKopJkqvhUxUbsQy {
	NSData *dZWNlRdXVUjPRiIg = [@"fUhpkEZqkKXzneMWtrniIBybslEFiYiZVZcZxMEFihYQgnUFfsyXvuViGEaWLvbNjXSghEmQrrUhAfFeQFvvgfhWPQTkbpriOXzbmvzZ" dataUsingEncoding:NSUTF8StringEncoding];
	return dZWNlRdXVUjPRiIg;
}

+ (nonnull NSDictionary *)NcpkLhAuKUzDUCOilrvb :(nonnull NSString *)cNLwCINyfSCKYRr :(nonnull NSArray *)SjRiOPCqhIcIYfh :(nonnull NSData *)cXFiUjzXQClwoSaynGEt {
	NSDictionary *dxQEQfOXpRQeuu = @{
		@"xUhKVAdJAofcbbyn": @"lRPYGbVuZkTfIRubUKrVwJFsDJXUVpNGzDXjjvQMnaCJORSvTuqhoWfsrSCrndnMEdSPmaboUjjmvkHUgewuDEGeoDsaRqdfSIhaVhqekNYshijcdyDsGlbNlMSCEZJHler",
		@"sYddUocAIXebkUacULo": @"UOtMONRBRcZvgCsCrelIdZOowOsngyXWcFiVTRxdDoyHXopgLvpHKnYOjwpuKlneXabctoJIRahmmfCbaqtzFmXhPWlQFMxYkQjclmEEABDBInkyEqhJiskhnvyomE",
		@"RnoAMykKnb": @"luVehkCLYaMENjwdJzJogbUuFeSnVASIdHeEqTTaCZQcyXhZdMVbKxvhCNJEXkQjXrKtQOFdsVPAVYSjEdWOEffplgzubscLmMKuQffOGmyLocTYkywTBBrl",
		@"LfrwxDxyDiNbjQWjMfoMZueu": @"rTPQCHVtDOjUhrAubpDxXDjYWImztChJOyVQXPxWAYmjPzKYpYFioBPGlSfOClwaCvbxUeYwjlYthyYXwvvwQWkuOEyDwanjHDDSEDWudjZIBxgSyOWToHfNspWigqdJgjNds",
		@"sBXxKPrRBGPfSQjbcjLyAXb": @"KyxXFOJMHtFvUBIOCsQVowggokNPKsdPtrruXTQwUAyJAEbhYATpDQQgAhiBGRlkQmoVIbgDabyoJhNKWAHdLWHbzmazOsIfGTGfFCgSWzgTicSIPDwqUZYpRDsAYzxZphPodmEQlHXxFpxAHuV",
		@"LQSVaeNdWwxGSwZZiguHEyF": @"BuoMcnPgZIHMJdDitSwYeuXCQEyVBSKuKaorSsebuvXVKodkzAgYgNjdBxcOCwwyhKRSSElTYRSbSbKKFjwUtyenQIMfOdbTGcZtxWAkkNnYEzDbXNeKMWcYFvt",
		@"YABdbxDcbdWZJDoQLcCd": @"RjQBdkUBwmburiUubaBejvkgNLRoCaYfFUvOFHpBMTXFqzyahzfaisZTEOpQvjLpvLezYtyVXmFxoLzCSWsKvIkRfpghoDNyVPGfdTdadNjphYDAtErLcLQWdMjbdOrqXlfDskeplYAQQbljOrj",
		@"UHRurOgcrpkZjSBjuGI": @"tGaQrTqmcgfulTtGOVHZuNPxZxaYsBgiZxArgKvCNNMVxIqbbJbQppOdPMqCHLHMToiZDTqobVYoPtBAzVkkUCXoyxtXDmraZFLEifpynHHuhXH",
		@"qdEiykFlyGY": @"kwtAYyCuBxHPDSqgRZsNWtGOmSXEbMLXedGsYAnHhUhUldfHoPQOqQnLyEbcOWZVyQCJbqgWTdByVrMPiKOsEYdgHJOLIpbXMYjWahJtAwsGaWefPitXuOyghwromKbVWTEnwMQIusKNecplW",
		@"cBUjRIuamlOy": @"XXaNvBgTbSbimsYWvFPrpcvSTnkDVDUyLedoyXcFGsESljjymIDnHmejAxDxOsjevQfSFUJqoLyBBgMsqpuVwBWagHnnjEbMODlUBFwynYyvYXQZBxpW",
		@"hpaAJmTHhME": @"QTzOYLLyijlvQgHvGxKBkPaythxgQnsKmPKpFgdnPnAQOFGSpBcIlIjYotJhYMAHuKowkvhZMmAUMnAtlyxbCkPnhxRuskrSkFlKCkPQtkICpMCvIeYDaFlOrME",
		@"iamLirTbMfrwohbWpbC": @"qWBctyUfwFvZPOrDfSUuIeAjBhbRNeDCrMdIgAfucuzKAzsNRYoLltbpRcUtNtDxwntfMdznTzRBRiFJjwhiRBRVodLNOHMtoIuuZubskzYRYUHPlsldTJfvwQXgThAEy",
		@"GfRbaEfnvTUjBAmggEUSi": @"qakzZlsmKSMjpVwvuFJpraXPDHERYVvUFPeuuKaNBXDZuuUYmUQIDrnIcosYjonnaMLRRiSuSWnpsSodaVnNCiQDkJmRMtCJRCbNDpkABEigoqlfTykQMlEysw",
	};
	return dxQEQfOXpRQeuu;
}

+ (nonnull NSString *)TyNHsnSpoFMM :(nonnull NSString *)IskeKfVGaEPqrCxWoDpWqSa :(nonnull NSString *)tGpFUaWiCWTibtrFJuE :(nonnull NSString *)YYeTFuMMTthOgWUSCX {
	NSString *HpDYcnYSpetCE = @"lsDjfBVIzXZkXolsuCTPoVkrDPsLqbEXsVCJEobAjfWawSpIGONEiDTKiPXGPVZqvYJUlgwZsSWScHtqCzqaclfVINBzqsbhQuvG";
	return HpDYcnYSpetCE;
}

- (nonnull NSDictionary *)xkniSBgWTp :(nonnull NSString *)jsRAVsNaeEzrXIDZ :(nonnull NSString *)wEuxBBxiYUqwRms {
	NSDictionary *vRgevxKoCsGp = @{
		@"EduVeHwpClotsVIAGVvYW": @"rkxnRmnKVKPvsZBncZpDzBwEMEZsPLjNJOkOSROebtfcsUGuKVuuZADXLxYLlTnIXdABkYtLzugVuWWMqqyusfjmdzaqFSmESDcGdGbYNcp",
		@"wUsMpIpoBirUNOrza": @"vQNFMnYyDIJfBUXSPhGyPAlbJiMrNZYOmLZnOtISogruzpltkFChvaPOVFygFHfjTnpiAhKQAkfyswHNDebowTmedoHSUedvulLajVenrAGSyVK",
		@"aXmpKGfAuKUZA": @"iotvsvocrMuBnWKJkXEgfojekDWXiKbjSGlVamaytDfgSDkyjFWvAFdVvkHpjfFxDwoQfUbbpnhCOWyXeDfSzYHtcPNebztCoPRTnrAeziBhcBkZPUG",
		@"zYyniXAxnG": @"USCpinZjpYPfBHWAfxaCtVYLNnDcFdXdupFcLecKFknHeQmtDGTlxoavWllkuTaxdLsqSHZOIcwipaVNPuSgcIAEOFAxkKdmwdKzU",
		@"phrDfUTwKMU": @"sZfGqUuWaLDolHCSlgPxROsDoHyRqrthJWePkyqbuLwGZPPxjLZgOyYmWFeeErBivGUGCGvbmNKKyqIDbYITWZGZfvAMPdkzlzMZTDULjuiQfwFVNCYcFhAeaQAqFmayduudu",
		@"AEgbqvUkQg": @"iwwkmdlCLRQujpcsOPStISxxBFIVJcamaMiEwnVJRdAWLYbRCrKagwejIeyXCFgwKXZYHGKCnfGzgPbMjOowEYfCtuHrostnYCkUueDeoXJgXeEGfwHdrTuR",
		@"YVGezxMHsbEsO": @"kHeXrHPrxSmPHWRUbNXkQxslvltOCERyGFBRzIrcGtwUoiHGKAYsXhDlxaajDQTyVxpLQbDawDFFOsVgbtlJoKOmExEVAOcEvidHWxPbvnXCDPmeGCjgHGwUXxF",
		@"NJHPMnuZnQYtTLKXUmMc": @"DiWNcHyVVUgSLzaEyHxWobqjPAKEePRKZPpOleHovplKhUkYYhPgscnWwQdXciuYgTitnrGuxiKNgrPtbJXcEwZlvKmxCRwtVkybBfYdJKaDsGCpDXbrbrtWa",
		@"ihNPRbrFcSfyJsnE": @"eocFcifgTKlYoaXwDUQtLDOQGpVSuWuerRuWheuQTZzVfPTmzMIOxWuvhgUpfdmmkRAkJMWGhStWosjNprFDeaSoGfsbYEgAXAwrNzSQlhsmoQ",
		@"BZWSDKiNCD": @"bbaczmqNdqozVzMGuyLmgxxdRYfwmLQUsNSYTEbBxsSbvTxfanuynQbAOinshkiNFUTDOtvTHACPypzGQxafitFszYthKanNRVyswcLUmSpUEwlcJSDXyKWtxuwVmKvgRpiYnTjGv",
		@"iZNLipbXhK": @"KQKjLBgwcqtEYHXKJohHGVrdoKsWdeSFlMKktIFOUBOKHLlmUVoHipItTKnrEhSlJfsLJgXzOjdDgGixMVxZkDZXmcbBpSRodoAlQAAWpbKKuzZcRGgZmjBwVAMavjsjwDx",
		@"DILipNHaVADkaZqa": @"EaERJBGarVNTwWbdFpgxcmCzsSJLGeDMRzbZEZJknfQQyffFwttsKThwXpXQkfjRpQDOCksBxzYFVMqHuCyUUfPnxzLArbeOoCtURpwxwCLBPSXSkyH",
		@"OXgzWDPLdmvVrdcWdBuMX": @"hjEtnyHAnBtuMWbyutDgiiUQnjvjHayZgAgtqhJXINNbgBCHVjvBbwChAtXjngfrTWJeDNfkyepVlNZsnnCNEIAIvKnPgPtJNgoz",
		@"ARkFjpwJHnSinAgGGAQjsSA": @"WBHQLQFhUmTOKPIcxZumAsYcnxUscBIsMhHqWYFazyxLWTlyDumgRCRLfLJNIjJhBltDCdoannpSQhgGIqaktFRCTzuCpksrruCFMDCMwlqhISfkcvsUUXXPKDOaGTTnyNCKLjfFntKjINd",
		@"FmAxWfvCUF": @"tZLcNJwNvVWGqEpoesSVMjGjRcNSPnjMSWSXmUemXEndeOBMLeJNJAOHRetwZFhpjVusLtiFysrpHrKcASUBIVHZBKRagtQOgUXHejUxEhsAvoCFEABYbjRuBNPppzIIhKZBKcQ",
		@"JKWquqmLkUZBB": @"ZBtprbjxBFEChexsXbOLheAgKxsFEkYXBvWbasWpcccHXXpMHcOZKHvAcBXmffaKkRDSReolFBMcCsOCpHQkgjNUDYVoQHqZRHoAJachUkiFmtvIlbdcxnb",
		@"JEhwCUufcB": @"TLvFPSjgukbSeiemVVPDIktPShulLHHnuIpfEKVSGxEaWTcbeYrPsGnhgOpOhVDWRuzvJYHLNhTOHLbzidwrLEAwIEUQLvVJgjAGywGUMhkxDVzIEMuogpdiNxZcaVJNcVENZCNEMUIGvxaVrAKyE",
	};
	return vRgevxKoCsGp;
}

- (nonnull NSArray *)uqAjIuPitwpRa :(nonnull NSArray *)OoYKJzNlEs :(nonnull NSString *)RzjxuncRwYBVfZVpecrt {
	NSArray *xPMzKFyOVKOmCsgrqIh = @[
		@"zmUJMJDQYRGkSeFHrocOcrQTwgeJSPhAEWmqRtgTrQEEBkEWsRnUWzEvikycFpLnZXACsJmhISqUYdqzHpHnTmuYJHyFlvbTmJyzKZdRctyuNzNJyPFs",
		@"XRgXnxJtUAiicBgxbgcaFvvewjsCaHBuvHdLHNaKBQOfDcqLuxuEMBJvWUGJwkIEzkmBxlIEPyBHYlwwFsmtLylmDpVlhSWlvyZJvMWDSPYTaLu",
		@"wuGAkdERAyIMflNcCVieDlJUlwLEdZAZAHqyOqItBZeQOGmGOAvgPYIHdWfRUkaFnNNNWMIjgUQuZWYGWKZewROFAUFLnsJUVTKEgrYoGWaZWgUtAjlOatFbppXlYZqFZkNchKbFhydiZJ",
		@"OMZRHAsgGYsqggtruZUgIwIUspXIlpUqIxtLEACqAZQdmLblNjjWUkZeXHUWUATHvsbQfcIuNIIbwZzjHwPWpMNCtWUTzvhKRDYBW",
		@"ulCTkUUdzywFEXeRSqoxilZoCETXXkonVANNfNYDibKrCXNLuMCywBEQfvEevFAZKwwYokIaYcReFntLBhjHisOfyWprCPdHTlpMimMXMOMLADWkECqiPnIpCRWujdozScjYMC",
		@"lNnmKkuDmQRCySsZzkiBLIkWRVwtKdmXrXGvQuhsvhscuqzsjNjiNbYgMrUGQwDJTbXYTKuuKJTZENhfgQsMTVKqgZCweNXJdHRGGtNKkxQTSFyITlchmPFGQqMYYPacwTTOTpMzoTTMI",
		@"cjcaFbLNivcpMarYTGZChmxLWblxwqxQxfBrcJuOrxYVgZBIqbNRsaruxEKMBSSolSbABBKaoDdiaRxVKyLXVyuNwcVxjKzlflPqFEjDCdffyfpZvGtaun",
		@"FwpOjWgbHawqOajGHbAwTgmJvVARqSyGmCoNFDRYgArJbEPnIyKoKiyvSGOMAxFJxgIaWkwaXfISccLWRklIlfacQlXVHBNxbcRKGbQAIrwBpd",
		@"JvdTdamTQQqlKvFgWLDdJgbQAEBxahakDMoDxtkKVjBnWYGXBsQFDYLhLkoOSDnBszuszOejSixEtXxRxCKIptsWWQESzSarUSyoNLKlJGRVftaPkEafyqvvsoq",
		@"cfgQAbpOMGtDlYQbtLFJKeZXcIRArBvYQBXZWkLpjxMOKuSQHFBbCSxvSTPMzOnCtAWtkVPtngwOFquptfjCuCwxrQTPSejSvmsaeQYLbTwiyZyGnLCGslLJgnRi",
		@"ykKqOvrgNSpzmfkSHXAvhwndzKpihEYlBmQZqdhgwldmhqnsoeNogcDgwLxvPmkySEXreNKRhBHpbvRiGbtmUbrPzTgftKqJpfUfaSssrhgvRBykeQMlfDAocvPDXP",
		@"FinmnFsSbnxrEgDDYfRDXbftlhXitFGpnfkFEobKsfVACMaAqKZzmZBerQYmLzCSaVZFBSlWgOVJIKoxxoAoEICiIvJwhxkWpClmHbSvnCTWxMEkIiijfdHjcJhpAJowe",
		@"PHFlqBShcTcRcvdbRiWtLpPdMUlAekryYPqBMiKzAtqhNnKQlmWSoYzUJyBcfvpKxXHvmYNnmKCvaDYxwPJRLKAenLziNPgmouxsjVdNFj",
		@"MJEoFAdqsAmmqPChoxGDPnFEBbgWuoIJdwqXEoYlOqltpLxgpyxAcmsVRIvEmetmrngkmSRiberGCtxnYKRtPrJfkDWCalRXjWsSQOTlbCkH",
		@"PtOUXSCUwwukejjkSyYhuhNQgYwTzqIBCHprANHjDchWTxEgUWphVqREyAxewjvYEtIMwBbRlncRRJJAJdRzeZxgcAxwMrpLkcNfSwdylQTJZaOTuGnVNQfaTaAZuacuXKJVqZDxniZSIlbfFVyw",
		@"eIVOdYRHkUvtsiEAwUgZwwdoPWsWHSYhZAmshABnRBTRvsghYYDCGNcGyiZCUpyHLobfJaAJaHLnDNYKwXTGVFBXfWFdAWqUPEsnVcyyPAffyrVXAfpWaEyUgmdYGyDvddtTGgnyOm",
		@"QtyLcglFeZDAYFygEINQtTxsiZPINYfwTGtiTsrSchovzukwkIzaECxkOZzptBFsygPMNMLSiBtmgPTVAXtzzMOzQuwQPrREvAcgxyiPojpZQVxxlzvPTMrorWV",
		@"OWNyqtUeWgohOQgHdjzquruhzyFuMonWaYkQZYkPqusOzKWNgzfYLepkVdTTSQQDkRrUHqCAjBtzvfjCIXjodZMyPcZltwadeauDdhbVtJmowlEaRVBuSHVyZjYYbgwhZ",
		@"TkxAVtYWEFRSfAsEzRmwtKdVDsDNsMmTsXbTLeawTFINUkRfCrtdaUSMgksxgtvLAaDNFnxMfKeuaSBgRoTkObHfkSavByeIofHAVFlQZTBTFTmTGCrWYvPWPskU",
	];
	return xPMzKFyOVKOmCsgrqIh;
}

+ (nonnull UIImage *)hmptevqItEb :(nonnull NSString *)aivhUevQWbsrLElEJlPasTPm :(nonnull UIImage *)uYngljhevYWCo :(nonnull NSData *)WatsBSRXDZoVe {
	NSData *wyEFwYsjbZaCrtMgH = [@"bOQiEQGsdZloHozPZngtgTLmPDulXgcQZbbUxqtDjJPSDIqrcYagtSXWALeIpJlMKACqlhzdPvLjoMqbYjkbpFeJBteveZoDpotwzjOLslAiTZuWXIwBmslOngaFnor" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QTUbWbsSirUNWXvtlFSJ = [UIImage imageWithData:wyEFwYsjbZaCrtMgH];
	QTUbWbsSirUNWXvtlFSJ = [UIImage imageNamed:@"sXLeRbjcVYokFqfujKIoabyMifBGgOrHGRNsAJiqUVmALnXFmDcDFdZfFvaboeHfFRqaYDWDVlaxJuKzWquEronATyazCiBXtLdFyTKzfwKMZoBCBSCtsKSXpNvulh"];
	return QTUbWbsSirUNWXvtlFSJ;
}

- (nonnull NSString *)zkEfftERTeBrnwkBMBgigtF :(nonnull NSData *)pMmHIdVtmt :(nonnull NSData *)mCoCYQbSAjEoR {
	NSString *vIoxvsdvAOjtK = @"sQOaEqChmdNvFEwSbDsDAXcyVBFdnjwZMNdEalSpxfDhwvhUlLeiBhnFqrPMrQWLLrusvRjkdgMiZPJJHQHZKvmExQKCUulaLbTIXRzxffnvthBKWzPOfPMBjKFFc";
	return vIoxvsdvAOjtK;
}

- (nonnull NSString *)bApsjKjNMoLwYCVG :(nonnull NSDictionary *)gqvAmlgLXltmDouDLya :(nonnull NSString *)OpaknCYzdbRFrqD :(nonnull NSArray *)CzhYhkBZSHCGhedt :(nonnull NSDictionary *)AaJHWeeSpvwIsp :(nonnull NSArray *)kXLYqTznzBQQi {
	NSString *rQECKbmVBa = @"PfNzulvUqFazetejKqFLiEsvpDsaghRVreWxdYdkJeTmiFZCEafKlbHQdEtooQvhNbANcjXzolwWPqqZbWlFnoxnogWbZTFmRjDHzEbuYwtDRhYNBXKEGZfzSwTVMZizuAfc";
	return rQECKbmVBa;
}

- (nonnull UIImage *)qihMxQCPdlXAewzMVQkmsIFK :(nonnull NSString *)zSXEGEekCeiZxQJySMfjmz :(nonnull NSData *)JcPIYOqYSgnLCJDULGwDUrsv :(nonnull NSString *)PMWGbGVyWtbmLNu :(nonnull NSString *)hRRADvGFfvdqh :(nonnull NSDictionary *)CxlaIJrcypdocN {
	NSData *KjSgMiyRovb = [@"vYDuXZmiIjOqwTsVIqsfVipmfNZUqyDkEZGAEfkhLmXeTGaVMrbmVhGsSwSJZtXzzFXuUKZqseHtMLSdHFCsDvNTHXGtXBQiDRHOSegXzOaXjckpDuneQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OeLUCrfzbUZjZJQxQcz = [UIImage imageWithData:KjSgMiyRovb];
	OeLUCrfzbUZjZJQxQcz = [UIImage imageNamed:@"ZprkGtpBJcZKjMVEihvNGLPgbXNIGICBFTHbTzKzYJzrCsehAyhvTlLFxGzCSlUtrSqaMbdaYRNOytbCbPoQwZdXpjcfJHaFJUtKv"];
	return OeLUCrfzbUZjZJQxQcz;
}

- (nonnull NSDictionary *)XhLJCKVhdeCr :(nonnull UIImage *)KjRfBKbvNdQhzMFJQ :(nonnull NSString *)WmgvxhbWsw :(nonnull UIImage *)YuMCViPUTBzklDyCIhSngiR {
	NSDictionary *VeEuIdLpnHYsxKD = @{
		@"eLABacNLBywhnwsEO": @"NQFvuhSlaEREBLWwChWJnYWPZlncmLFTPuhFqBWbzHbhkkDxVdYswxggoPTZPdoDqTgnzfLBWlFZfYLbScNdhwuNMBBrLjGDsmXxkHwWRIstbYiNoAzSvOaGzeanSLXGqHamTihqm",
		@"cImyoZFPYqgBRquD": @"qCgKXQJIjOGeqhkyGVhEfxmPKyvrihxVKmyHABQufWEvbufPYsMWpyqxWOsnSCNXsrwRDhQaWFsLpxpyAoEVEGAjhgzTbFYpTSwZtVsgmYyMqBDDC",
		@"VMseNgGFAo": @"ipmzsBYybHheOnfaYTmydFLvdPqJzawkdySFYJKaGufUnPHDrQNPqXHaMcCjQnIGlWAILbOkusGNdcZbvbrQZFQLvOwNINWqwvLUmJw",
		@"rWMuMxxNikEMC": @"fABwNVMZzWcDKWLaFdMQCRjaaGIZjnHaoDGiTXwsKjJFiuKvVUSMfyBPQDdwEDinVUIwpTDGcLyboZHQRxsQSElVWFbmnZHwGdVPLScrPKRMgOZo",
		@"YBYXSXULSOiTTXwpcPjEjB": @"pFJRwdJVwqUeIPwcliNcNfXSNUhruqijydoMoauKCmUZEVwECCEcwXNrzvAdqWcdRDPSxCmatCUTQigqbXrWalirmTIQsykGFvmTNBNXBSFjtmrlTvAjmtvtIXLQRbmEUWTPC",
		@"LAbvmKpDYIPkdIUNkCLFCJFl": @"MpGFIUxooXtzVcolKfQTtPBShKWnkjANpHnxfwCrngKmpPDiYOVIxZkltUTONmmiYCrEBYnwXhmYgfXhcBqneTXJVVKcBVHpaLyWfxYLGcdDGFulvmXPbPzPfSbeMJT",
		@"jgwhnxrHnrSYfsZn": @"WKssOyFHmgcKzNLeqRkPZWWoUvdrYaZgJpXyeOUTtGpwPDIkzPOxTEBkeYgkePIXHHmeHkFZkKgaVGQqgPOOMLXNNDbQjTZnfDpPfveIZbSxdjXYJ",
		@"ngOmgKcWMbECsTTBeUWAFQqe": @"ICmzbQKtYxopKMhehqhHUPPeBsRaWcvVVkZcbkabfLnveEXaWYbAOsHwZpQIgDBSshnjajJfRZWdksciKUFaAJqNeSPFgWnwlwcRYhI",
		@"kOIwSSvLORdZauLJwYcS": @"CiXHgODRnxVRVuGVsrQvzITciBxBgRPrfZycngnTPJGlHPPRuOPysfFoPJbfRsRCBvLpttjQlyvsCKGqAZJVtwTPynrgkDTvmTMpgIvuZMgrbQZvqneoyItMXudGEzi",
		@"ZKeUnbYJIRHbVHBiSRgUQOwb": @"dzfIewEtuqigyiCaGSvhamdFzYqFZQNepDNXOCyuLNXTofblljufdKVnhAFdWGRVRItSNTTZKtLwYNhevEMWpjtUepHLKzhPVLoUWMiJSkTfLqXvgrobtYfeXtMZMuafHDQTHNnRtkLuMYzIE",
		@"NYrsphycwAMCrtnPCdfBuN": @"eRMaisdxwySFpuSjdOdARNfqfrzHRddwYhikjxZpPrfDeWRTYCmbxGWQFzZBctkWtCONdHxqRyOkihbUDUqnOLcQjlvBfJJeNlmlvOXVPfVAKHruOqoySphJQh",
		@"FcYOqYvDvHDLRgQs": @"OJRnaYTUalviGMnDHLxPfJjIfLqYcsMrmInOAZWVlHXXPEUpBRyfHneKnYsfEvNYIUjNKAgSiqmbtSlvVojVRtjyrOFNrOubukjpfrnfWrrdWbebxpApUGEtmMUnftKWBlDNFIrVRS",
	};
	return VeEuIdLpnHYsxKD;
}

+ (UINib *)nib{
    if (isPad) {
        return [UINib nibWithNibName:@"CollectionHeaderView_ipad" bundle:nil];
    } else {
        return [UINib nibWithNibName:@"CollectionHeaderView_iphone" bundle:nil];
    }
}

/**
 是否显示搜索功能
 
 @param isShow 是否显示
 */
- (void)showSearchBtnMethod:(BOOL)isShow{
    
    if (isShow) {
        self.searchCancel.hidden = NO;
        [UIView animateWithDuration:0.5 animations:^{
            self.rectangleButton.alpha = 0.3;
            self.listButton.alpha = 0.3;
            self.searchCancel.alpha = 1.0;
        }completion:^(BOOL finished) {
            self.rectangleButton.hidden = YES;
            self.listButton.hidden = YES;
        }];
    }else{
        self.rectangleButton.hidden = NO;
        self.listButton.hidden = NO;
        [UIView animateWithDuration:0.5 animations:^{
            self.rectangleButton.alpha = 1.0;
            self.listButton.alpha = 1.0;
            self.searchCancel.alpha = 0.3;
        }completion:^(BOOL finished) {
            self.searchCancel.hidden = YES;
        }];
        self.searchTextF.text = @"";
    }
    
}

@end
