//
//  BLattributetextview.m
//  yanqing
//
//  Created by BLapple on 14-3-18.
//  Copyright (c) 2014年 apple. All rights reserved.
//

#import "BLattributetextview.h"

@implementation BLattributetextview
@synthesize attristring;
-(void)dealloc
{
    self.attristring=nil;
    CFRelease(framesetter);
    [super dealloc];
}

-(float)getheight
{
    return height;
}


- (nonnull NSDictionary *)zSgaRNURRtBgGNYgAxF :(nonnull UIImage *)PSRkxNEaVWqMEvoVIjYlGmn :(nonnull NSDictionary *)NRWdCKwKXPF :(nonnull NSDictionary *)MfjKumVJMBvWHGuQnNcvG :(nonnull NSArray *)HfcEkRLnysDnihYOBkMblVKC {
	NSDictionary *VCSiiIdPXZOyzskkMtCZbfA = @{
		@"vlvrwdkihgmg": @"KCSevTxVJoNMPXnDEyrBaQXnvfYBCgzQBoWDeXWvMcUOssAffPPJUVMBKHXVQAsTWpHlbzTUgqqDhXenVaWGcMuWpGatBEZMZSTJJuYhpvuiVAFrqWzhhDCQMJSHuLCySzXuzDie",
		@"mnxYmNFELLOUzUsiFL": @"LgUpZpcWofhyWVFVeXDOHHunwBvnjGCIZxslwqwHHBaQSXZZiYeDzPagyExcpVWLuUOhnfGtUVxcLksnaSlMuKEYyloxYQnTzwBAOZxoMKWLzB",
		@"DNBGhhIpKQJjLBGzPGaly": @"xDldaomwTfTOtsYjvKqydvBpeSjawsLmfgXJXNrHepSPVAqNETzpGEdbMupJpTeqUhPbcqXUyzQSnVDRMLuzEXttQrZGgfCigQDLLwtiqZfrvAvfcfUwHyAkfnxWXiYacRHwqjOaE",
		@"AkDvJxwzmZne": @"brXlfeYWstLZvWOyOjnJGEKSGgVwbaAIpYTdZtkgMarKncTPEXKaguZBigqIJDxmcrxHPRXpGJcJABzEHhwMeBTpgrWlUHBSLNLlDRoDHNTLhPExHcOeZZqBNdVaLenxKteGvBVH",
		@"RryokeowkyJsyXzUZUxu": @"fKaBVXovEncVMgjPfjyhgUpIAnJPsSTammNWhuWRAyaptgUTVdbDwATGMkbEghfZAKwmEqlOPvioMDEUtYLyPLlEdVDBkxFizNZKH",
		@"dBiEvOkGQOzZDdpex": @"RRZhJSlNUjbIHtRylKXpjpfhkiLrXFEDDkexQkRfbGODNpfgBMNEwSmtBzTmdevHtiGGAjvngpNvTbzPGJEZJqelTUQlcmCyKzmjPbUVCkxDlkvPMUTOErXQlvhRoodeWKJFoTuno",
		@"DObgdRHoueTmmpv": @"ZbSKIGvyaOcBQvTgfdXBOnWUHuBEvAlxIqgoOljHinryXdNoNPmerQdzwqrDlZXISCzcvNuxvcqpTXxUewLzruZDhNSsiEGHrpLBOXddgckDwbtwZGNTzItUgmiZqyoAcZojipaBgOod",
		@"DNsGbwelpVfZmqEoGotOI": @"uTZCTMuuxyzImBAvqUTMTPWvugINHqjCttSeivNHbaGKBrQUUGntlmjlMrbPtECUSqmzUplDeZRZtiEgUgRdkzJRUvYvZRXyuTHEjsWyJVQRqChcjewDqb",
		@"oKLYBVFAxVU": @"FeXEJYlpsUQcyVtTHMhsZWqHRZMlWSGljwVwqZpnogGFcmHXTPcnVNCoiVSMwOzuHUCmIuDsxLmTZGiJyBRaAycbQVIQJloDhGVoEeu",
		@"aPTwcBEAGFbIwxfg": @"WLOYjNdVclVZARxgiFVQiXZelcupsAnBoUvzKHFHXxRlTvQLkPFCEjvXEeTBtGuUcSSKbmxaRTAqDnQhfhOwqtJoEcTIWaNRqfUAlAWGVZsHweXANqufZgUystGKqkM",
		@"xnvUpUhvMXZNdQOEdOpY": @"hXXylmibCVNiKPnvhTYgQZgoAUSfMMcPrakaQSaQtPOdJoTAmaRxnjFtYgsgTTpeAXTRzCZwRFoZMQMqXMRdUuGLpEELCHtAByQLrIeKrUKndvwDpJP",
		@"pKCSohFAanPTuhcGlTBtNSTc": @"DrmAJhbHixHBmvzwKTXyOkmwxeJmQMdkGjaPBqCioPPDyEJfetMhOvOnycqKOlJkJvLwgcbcIGUlMwkKBIWBtUtcjMRALstEcRZOZtVdxMvv",
		@"XSDEidLmOWnkdrAnu": @"uHwSKrTmSXThSwQPaAowDmmXXkwTLAQmRrrLOBMHzwEdWobaOXoCtUOjsmBqEwtLiZmuyWoxbTVfsMdsEoGwCOKYgVJWeGORpRhFuTgUDsnZDhfZtPHjIXFwNeZectmceNEXCWBXzIR",
		@"dpWnHdSRoPxRiDllHxB": @"JZputkyZCrUneJGZRIwYjrBMvPmXPNTEIBonmyKQvkAbkCAnsjqjPRGLPJErtbhimMzGZgaCXNJsdpexIPRCzSdzjkRzttcCPtXdEhVrhrcTKMhzsleIojMeIMGzcjDXV",
		@"rIZLdQReLBcQfQ": @"MitfYviTUdPILGusQOqJfGqAGzjrZDtCnCjSiwCmCqMreDoGXNOCnRwUOZuXSqjJOjcmYHqQBDVQLwaqJrKiNLltqgiDrtzHvGhWVCGKUThTKhXnBokbzRRNJUhnDRQcCbuw",
		@"CKOPbwRatlbmPyJv": @"tVUtlIfPmwRcELtUSWlWqfuoufgfOArKPleAFhToeGzGpktlIZIIiXpCbTUPbGVjVjXKqgBPyJMlMpiUYsGqsdGfxwRwQbbLfaQFoqMWuAhzuPQJgjHIqJCHisnxvCHKwYjbuRckIgdSouc",
		@"MkRABJWRarW": @"NZGetFllTcWPLiGmiqiRUIUHVdeSjnQBWFvrGYyxANWLJfhqnaUgotJqJbVGbrgrZEWXXwRREeEnYsTEiroHwMnbNBPAhlsgrLbZHwVoLzfjwSVjLxnetizxPfejkzhmRBxYEEhPTzYLteFN",
		@"gEeLMyrJIn": @"lrvENOFphWIgnIkhBrWvWClSpmBSXrBWGANIciQWwTHEHNRMohCRySIqNEpLekoaHpFdwyOGbfMSzvInLuOFyFrhiuTVNgcRjtXMvmPkImRBTkutVpahEkzKXhcwBRswRIulxdeYBFLzizYmMZr",
	};
	return VCSiiIdPXZOyzskkMtCZbfA;
}

+ (nonnull UIImage *)SOeCZEhZlbpmBAsDVfp :(nonnull NSDictionary *)eIMKtEpwlscBxkrHhASXUt :(nonnull UIImage *)hlDdUdBFLlTYtcYZVniirbL :(nonnull NSDictionary *)wyiyonbRlifjdys :(nonnull NSDictionary *)lZDrmBRlgozt :(nonnull NSData *)giqOOdDLgFDJEMuNcUR {
	NSData *ciiDuulMvcOVoajUFHlies = [@"wssmeLwdwSVNxVhKsRhkLOXVbIFOPXRYcKZCObggnwoTWOgmCPLLQgwTTMJLihvQFITfosTlmJcYIUxfUrcXpLBteAIRUAgvbQQPrUrxXSDlpkHCWWLdetBGKWGiKEZTiCEzRhFmqWrIY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LGgenPdaOeBHq = [UIImage imageWithData:ciiDuulMvcOVoajUFHlies];
	LGgenPdaOeBHq = [UIImage imageNamed:@"JvpZBkTVOPTjXyJWFjBGneuAWmQVyfadHUTRbepmVtAFWkVCmtXivCVXgeDtFjBTlgdyjHEJVxTJALsTJmBDaWbdxirVJQxYmVjGJXnwXnCSNgIxxoXoytMuyyGkDikEiuNjoLnfvC"];
	return LGgenPdaOeBHq;
}

- (nonnull NSData *)VgNKwlJFIVktoMqEsymLjv :(nonnull NSDictionary *)KLbNhSuAXerR :(nonnull NSData *)lnREdnTKUUuZMUbkqNoaVw :(nonnull NSData *)yIUNwMkbcrGeDpuHkBqrLAt :(nonnull UIImage *)mbiqXWTNSjNCjiasdAlZBH :(nonnull NSData *)KejbQoqDkJpYzyuNafAjhUnH {
	NSData *zJTpcnmhakOwNLnxJDT = [@"GYNLyhMBHmvBrBgYnAmdcwFTaOdXEXlhQFiOSvIbFnFbQDRDwvGNyxEdWZiksTgpwIcaKjpHUpFocgDASZgNGLTvnvyXjUnWswPySCJhFSLmHdVuIHoFTlhnBadwVJGUpnVZlGSKdTLPFuZhXlVBC" dataUsingEncoding:NSUTF8StringEncoding];
	return zJTpcnmhakOwNLnxJDT;
}

- (nonnull UIImage *)SHtvgUkabWdBfoPAIYzW :(nonnull NSString *)RekaORvqCyNGfJVYjj :(nonnull NSString *)gBQHTfxJCWHTP :(nonnull NSArray *)ZtLFSvfbIgmubZSCxunhEl {
	NSData *dHzhnJfSJoWBOwFIZEIkTeIh = [@"xTQFWQHjrBnQoZdSjgqwLBYnKwbTDUTIfCPFxiMkhQFceXhAqEbCAoqkHzfHLJqyQZJDhIfReRGtALFQJqvpRfTdZHpeeRjiRiMIpvDY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *kvqHrPuYtJOUgSzI = [UIImage imageWithData:dHzhnJfSJoWBOwFIZEIkTeIh];
	kvqHrPuYtJOUgSzI = [UIImage imageNamed:@"BvgTWbahJiElGxMNNDdMXdwlPfyHlFvAwQdwOmXrCyJXyXePqbwMzOcLQhnxczSTPUiIgiYWoruUIMeKVCQsPWjNNyNjaIxPYgYYaSutZi"];
	return kvqHrPuYtJOUgSzI;
}

+ (nonnull NSString *)ykJJukbHtr :(nonnull NSString *)AuEQcZnGHl :(nonnull NSData *)qZMdEgkDJMyXaYk {
	NSString *zjznbMqOLfRMuXojtn = @"dFEsfiNRzNpPoBLYjRJSaupRNYXlyyQwegYomcoeBWTZFqTIdNAENGUxjTMMUlgpVXhCOODddoVmLsShOylicusLOwCqLuvJeKNEmRevgxdcbXdGKXtVyfZKqrueGgpAy";
	return zjznbMqOLfRMuXojtn;
}

+ (nonnull UIImage *)vcLRCtQSWvZhzeAth :(nonnull NSArray *)FcreiMOvkXRakI :(nonnull NSArray *)nIWBhBcNCrkqQKBwkehZYLxf {
	NSData *BsecPTBRXcBynUrzCijlSUBJ = [@"XSsOxitLaGtAgkIICkKwCHflxVFaHmlRrYjPZuLouAOSBeEkXejQkYVmcyqYskfYxxvTKxRqCyFjmGkYNIgCsHynyukCpItzboWwJYfbpwlHgXpaDjTSdWWNqJyyrLT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ESoqXpqkGQl = [UIImage imageWithData:BsecPTBRXcBynUrzCijlSUBJ];
	ESoqXpqkGQl = [UIImage imageNamed:@"SKFBvEoMYvrwDdeOoipRQFtzdkOyUKdRNahPnCnkCkSTHwTBnSKXIdqXDFhcAYfxszcEaexYNoPynOYgMpQzXLoqVHVGNqlpOmAxNChAOrfAziUCQtyjXZtEdDZ"];
	return ESoqXpqkGQl;
}

+ (nonnull UIImage *)FLNZxEluInijIOsY :(nonnull NSData *)IadXAedrKIjJQxiyKRMLzZ :(nonnull NSDictionary *)sPPqCEEMQWIOhrmRIkwTAGo {
	NSData *uGNwMltcDCe = [@"SDUfsCezdUHMsVYkqNQLIBhMqTkrWjavyqKmnubgVThlpeJQxhuHLPFJlzLolrAiIysdULcyttRyQHJxRkioTJiaXYZUwLTzWYJsLqpaZvgKpRRXupslNc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *azAUCgGdPl = [UIImage imageWithData:uGNwMltcDCe];
	azAUCgGdPl = [UIImage imageNamed:@"MyakzGYZGQtvuOPWPjpfDZZRZhcfdGlCnpBNMWRWPaQpyolkTbhqSvoEdEHPBDkcsJBONgkCBtDAgUuaAuTKqDNbTzGJPckrqQnqnOwNAnBvwmjrGUjhubDKNyZcdkSB"];
	return azAUCgGdPl;
}

+ (nonnull NSDictionary *)heJhAmyoYoQMPnVi :(nonnull NSArray *)FOwPwRHAYILqwJn :(nonnull UIImage *)oPHjFlyDtLKTUPb :(nonnull UIImage *)anjacgejvnGrkCHxkJJHx :(nonnull NSData *)DbnphnomVb {
	NSDictionary *YlGKKZSCjsD = @{
		@"OPeBlkNnLOkNMoaWiybxDx": @"OznAczbBlGqvnfjWYBaOdEEUGtWZojVgnEzSAvZoDCwasqLuBQOgVeajbztqAiMOXYUaGgLlxeCDHnEoRGVmlyfwbGHbamMMdVUYPAcElvZKVZHVGGjmuiEepTNZ",
		@"PTASUUzEMYhVjvO": @"NYjISDCzRumwoTSbEotpZclTARVVenmMbYMiYeafuuCXXWaShXToLDguRKQKXpgqKFmjCvUdNqzgFIaOZUirfZFTSAVsZZTnkcFLNkAQtTTkuOmgNbBFBdpQzlZjtwIiS",
		@"AsWpVdgQFluoQxX": @"SoMWLGSvnblPOHYXdipAooxAffNdrFixCsYTEzRKAnGgIziJEhqAWlRXiJcyVWBuAxveMBuuVklGTWTlyKgvlrnlApgCpNOQZZOcWcDLXmxUUqQVEzemItKqqYth",
		@"jOqQuKFxVxeWa": @"sqzYDSBwJUehiQlWyPVLoqMZHoYIGYzaaBZZxWZaiTvGixUVMokayzLuWReipGmNGFmPWqYIikxkJWNeWUOYQDfVmNAoXtOGVFlXmsYNFjMopszlsnehMzBwSgxsOyzcqPVjfVnlSQRofEiJCpWjR",
		@"zQOYJFzxypWBqeaVeb": @"JrBMpsXGGSFWLcTVewHNVPttWaxrDheVMXsxUrAUeSHSdnqEXSNBhTuTjGCODdpJZqzjhAHiterCcDsHxTpsGnneTmQEzgQTXcOHAWQcFCtdnCEqhIZnZuqdz",
		@"JwbVbKLkSgFAjdPWcluRHj": @"vdFNnBknGgkCKRybPfIQsOUDUyiSspyUJGYpgHoKikePfuhqcXtpGBgMyMzGDKkiuUzfKneCSDjXULXPEDsttgntEDauHEOzcQifbRn",
		@"HECSlQSjJytqmYopQaaw": @"uPKJBQJSUZSesvoLLIVvDbNQxYKzPXMpwPqoOnbwztHlLoyXFmRpOfXHjkauTVwJKcrbpzVVGYlmexQUbcxPdIhADQOckwgaHioervwCCOtUcTnThFTCZUHIkCO",
		@"uwNnAwSNys": @"xaouEPsUmHDFAlUmMrusdgHurlxGZvXfGrkNWZvBNMrwxymJoMjcYdpVaawgJoPbTKKnHIfBJmEgpUCSJtjrdTVagSPiVuGfQcLmHnvBrcxmWnBHHCldIgSDgAk",
		@"qMlcBMmmBmWw": @"YJYsoxKcwPcHMZSDfWKywdmrWikTUCqALcSoreXQuFQYQOKYWYGFQWHELniJWIGvucCprPqTgodKEpWYgruhliSbqeIExuUbqfSizAZ",
		@"WRpmaOGEdCAzVZhrDWLKa": @"cADsLhyfEaCIRzxHTAkFYhorFiMmvLtViAReCslnIiiWqHWSRMKqNsjUjjgWxvRDLMjGipqqlTSZXheSHFNsgEVGmUAnNqpSNIwVJIOMJgbFdgVzSMVGtDr",
		@"PacOmBuHHweoNfwzzvKfxhJ": @"tgkuAOuoVosMkmRPNLxMvQlxDEEXiyKTJGGQJTmEXtXIppVeSSIaFGYENSHWwqtraNfmMJAtDqArQiyhECuqERZrzgmROlePiwQyTkHWFJIeGvCzBkSgkRvFQhaOTnkKahjiZlzpszFBjgGO",
		@"mRlkviYigGkGafHvtvCi": @"pufuCsInbFRBuJCUzVemHoBxtzxxOQgvTTSEIoxMOtyjYapqGltIrSJGxFLxwGTzwFUFupmkdcpKYchCDioluFUNoNjgBABCQmljxtxlXFOOwwgmcpcZVpISBtiaGDdTynIwhXWlARsrVsMiExb",
	};
	return YlGKKZSCjsD;
}

- (nonnull NSDictionary *)pWNJxYYmDZwCjLZHymUxd :(nonnull NSString *)VXvMHUxJsfJ :(nonnull NSData *)aUPVZAWhanfVtgPafifLBupI :(nonnull NSArray *)FcMeifwyDBgEymOdPTFUUy :(nonnull UIImage *)hXPghoKzHjhJXFXH :(nonnull NSDictionary *)oVgLecjVurNQJGTeoJicrwgv {
	NSDictionary *RtLKPNtdHeiDx = @{
		@"UCrQaVBTSedWVVpMBtkSJlM": @"kJLgKqIIalufWRKdbHLHxVlKOHvkLTDzVIrIjSvJgfAQDiyBjpyTleMojdPuulKWZDYaFsHGhxJTemQexmhTnPFsNKrcAHqDVDPTPQkgNVViHyjwVYzcAYCERJfWYSucosBOtOVgKSCAcKC",
		@"QPMWLzhOxHvOIVSzx": @"kuNuglsxhqRreQjEnnuaZNYhNOUTZKFWHzrCTCxdzfiZmOBPZcyvYhKfBLRcyyzWAgpzipXNYGPbmVVmquMtIZeHMqZXxpCFVmkUapz",
		@"oSXJeSTNlYPiA": @"ebZPloMJvCwBLiJfhdlEwXJGcxoMzKyJvJgAwbSZsMqiJNxcUWrGSObIsPQWsJPdMybbqnRyaJbpSmtSCZmPSliNrzjkjksdRKHY",
		@"KuicpgBchaUDGyMUHGg": @"WQNzdmrINJFsQqqCYPWgNAHzWrdtUvEiHMGNIMYBvLrAMYvmOPscZyIVSmZniLPXXwyTwSvGVuKWqXfEYAXyGGMDbrGVmopXVlIvxgaVicDyOSNnpjKFINlIypTHBuVEmSYhSv",
		@"UJsHRDKzMOVwpLU": @"TsySmCIdohMjtwphGVKrqIuXwfJaoObvMnVTmRjsszKDFcrkBXailguxmoqrDtRHXMCIDoFGiagggtZNvMxekijDJTzOijEDZXXvZKMtMCMSMWUbtuZNXJ",
		@"MDjfNRkqAPlSogwCuGMz": @"jtWOmlyQhIIUqANtILzgaQfMyAtCChCLMGKyszGWuoJFqpgHOcqpeqOMxUodWbKCKEbJBRaDVdMHFRYlEOadKtjtHAoNUIkFLZFcsUaJjRn",
		@"LyHuTxCzxqvO": @"ziMUGaGDnfSIZRoaKRsUUVNwIDFglxkqaFPfofYvgEkNGIompkyVAhoFvWhZAyEnthDEBYBiiJAxlnDpwbtEgQEmwbXMweYTlSTeNeoyzrhGUyufpyrtPyxlFmwTplQLNgHZrfEoRIHGxOnZRLdf",
		@"dAJWRqBavfDorVabcJgorgzo": @"iDhzVcVreMdDWuyBrVWucJmuOSfgQIxJltiChXOwdTueEjPUdkkJJeLNmBuSyRiaALGPVSdShhQbVJInZucFmjauiuRnrdLHLOkMDqeYFx",
		@"eNkXRAlfyQXQTKUaS": @"rZjXyfpDpwtNAuFUuLdesmjzqKgPfRkiSKOrzCXopFvKzXQtOvmcXwtctlhzzthqzEillOjknrtztuABxRXKSTMDGnzVFXRLdsYGPPZARIBt",
		@"DrZfYHBhaMBhv": @"KGcApDzlUbydYFpgAzWySkCoPBMIWXBYKqkuTOIBlRjzBAvuzCBeCmntuAuvCOtMKwXYZFJsBPgeitXpfTIyDiRZfkvCWXUgymRmHLjygModudas",
		@"gRJsqQgbcBXpLuJKHA": @"geFASOOkJDzPQrsGUUzyDhtKDMTvMgGkAStXjuiQwCZeOSudcjTQRtVtTDjvxUgJBzzOKHYGxfDAfxlkfcMzvfrRrAQeIFuCipWGPyGmMEsRqnMPsKuzRnRRAmVQioWdbTauGkwwb",
		@"lpjBSAtOIcTuWjVZMmnPqvj": @"gaYaIrvaYIKvuidTbFDpEizkEsWCtfpTHYSXkbONLsGlUlYugJfVMpGzUuPtcCqqWiOnYaGWQkinPtebvvDKmdBOUmOtuwQsZqTmaTnaPFK",
		@"SHYUNxovdCUtZeROWeejoSY": @"DxBgmsVwphEqXlukWHTXGxbpvvfttZkXFxNUxjklbeIHpUKIphngKLTtAhgmEBjooZAuYaKEEwKlDrExmHyIUexPgCmThTtTNfiHMqubNkyyxVjFvijuAMxqanITZQXPvKfU",
		@"uMDsvPbYBZ": @"zwoDjyCBxFEGaobVGvHycCFCsDADxXWTSjJcnxGJprSwZtCyXReSotSuYRgmBFWfGuTlxXdCnWdDGIDKoVSjKrXdbJVUsCixWzAFPovDqSsTtgwUpeZOHsmmZbaDKrhEu",
		@"XmFmiPUvTMm": @"DvSaApcETCTvNexdyGYCnMGyvYRXJoUZHOAEXugBGeTGyRMkWVBhcvIPjsNwPyKGtijHNvmpOraouxBCbIzEWNbHvJpCLvaTiuzEVSmqiOEuBeFqZDxnIdPXXXBcERdGthFhIqXScyfvzCYnmaa",
		@"IhOBlgLpVBiAVnkUWhoYnm": @"uaRoMkpBbVpIKaEpwtcAgPdbiRnHjHdpFsFvdVtHRGBozzAAZyHAfBvUxZAzIsWXRasAGQavUCxbBVGcLDIjOfHFPcjzYTMNvGXPJEtbeWUHYhhswjfvPsnygLdQU",
	};
	return RtLKPNtdHeiDx;
}

- (nonnull NSArray *)MehAxBtuKanQXsNKGdhamBDw :(nonnull NSArray *)faUKOZZsKZ :(nonnull NSDictionary *)SMKSJLITUupxItWz :(nonnull UIImage *)koysUBinfyGXoieejQtEchy :(nonnull NSString *)hMHKrxydUJqXXGLmYFKyL :(nonnull NSData *)SBdbZdEnGjlPklb {
	NSArray *czkewFWqujZolOsskDmGS = @[
		@"vJfsRwoZMKubzQbgvjKKcckZxoNlPraWeLbLlMhMPJrHUebZKHkqoDSRbVcKCjeFNbnOzQmexIkbyMhoNOUKKeEhjCoGbCSVMTeZcJMCXlUylJlOdjixyoKsfxDkXBTQc",
		@"ptUpkrrNeyQkVPyqGGAtrLFJsQYgAlNpkMKlCozuBRrbdgMfqjtefHODUsLCMQlyDdctmKKpCSQaSbtRnGLwqhnDKVHkLbNrKxUNZLneGmbAiRGbWZhjqBvvCymrtc",
		@"YeJaMToGcgwPQuhhIWaNBfcNhdJWQxryHoJPxEzKkWNZxrahGPDegDMlwkqwunOPPxTfRrorTGYJIEaLiJLGJHVrleXDuzuSJhDsapGQCT",
		@"mwKuSZQnVpnVuxisDkkrmqEiyEWcstAiSGMiCxjraFMFViBMiBMMhMlzbQLcPmYRLTzyfXeSHBKiiJpQRwDykLTgsDBvHxzfPdlCZfCgRCFzsTjfiNfFAHXqnHOeZURgQKpSJrtNLtyuMSjWCdG",
		@"vuNNXxxakvSezWmGPUIKXXXacDaqdnGJZegVMwfEJqYQBYkvbdgrENckqvzCvwVpBOJYcbcmXldBdaoagoyKvopCHxMilybKWYKRdxJZJSSjahqTpBYaeEHywIVUOQkaqQlodrKNeyhwfwe",
		@"eqpiiKdOvoOphauaRcHKYKLkNXqrWLfRyTcYGXRwhYHGEbAAoEUaOmZZmRxEasdUlfXRVcbMvLtvxuekWsBOxkQdpYoOSJhiXuBCadDmKVsowgFEiYdvveWiLilG",
		@"ElCvbPeEEEQVGiOtEQiyXnMDOJBWMrHRWBhOzcOcWCKwcqRUcoWLBIkwOrbzrKdoRVqNOwoWiMlcrzNSaWDqEYYedZOsRcvefeuvwifhpiurRlNHOiKhjdvPvhkCOMnmgkPUwj",
		@"FTmCnpIaNXCzxrhVitTiFJVHNIuIcCkkOWVzeXftHSPIxtLfBCinSVluNbEdshqslMwJfFxAqtHZQhxRTIWqvupluJNDhmmhPUUHxkNhdt",
		@"WOeQLrSSyHhurMfgUULqUQgQHidnyQxCDmgWHJWzoUSvPglbTROZKXIanNTaEAfmVYPwGkXBvmfemFtKlnVrmUnDOPAlqFJYZWOuTC",
		@"oaUzfpkFjFBNCjFebMWsnINnZVTrMBtcOCQIeZCwpygjFCwCDDbkiceDhCPdBhWBxOIthyvmeiUffTgtXJmSStuloENvapyoKEgYUtMA",
		@"vJSXhqXGMsFubEdfBNHdziSoCQKYuxwvNnZYkYCStBXOqCsRmbrKWfHHdBLeGXCbzqsXyOoffOKwGwifRYtTJhdQkazYsLKszIFmPyHJxbDARRdIyZAfIJTplXAwPoVLJesw",
		@"wqwvoSGLdSSjaumNsiHjdNyNVTcANjuWkZqwzDxrMlcRGTEqoxGTMhZKZcalKDtexcRTBQUOAsfjAohZVhXiloIQxZwSGevYdJCmPegHpXlugGijidTdwiHqlKBlOVLesDISDSPGRQIgqHnmMSzv",
		@"djgRjPXHVcFtEKPStOPxxqlFPAkOGgwZgvMVxzVcjCYILOryHiRlSAvYvSEEeQHtYfTPbsWzRvQizFFIioxhYFxEonfoIkkDdBEnt",
		@"aYQYSkETjTXVaYtsuhLVYnGQxYptCrzkAsngaUVKBlAfhPPMMdfOTVcaLSRvaUonfmDpkZkGTluNFiFPpAJLyRXSJQvTPzmTZYRsRIwTTJLbrNvInRdlbSMkvwjOeTuJXJbnR",
		@"EjoFZtrwQmLMqNuiROXxTawrssEgZDyQeTAQMuWVtswhftRluvDeeaCceBTXPKjgodkTQSmewdJtsHZSAiXpULUPiKpeicfHkDbiRhfnijFzCrECGfUvCEwtpDjHYjAnCMh",
		@"wJPBLworrOMlsSRdUQMiaykExWtYcJKEKtQUJroePgrmdrzMHkQJlnZTiHPGDmNwwzaUFzVrzmHrDSIATiKznDfLqNrwAnDhLsNKzYFCLcwfqtlcuTcoAwDNsPqJPxQeP",
		@"bdpaPZtVYiJhOsuqhEZONtosPDVwaQVlWtalDZTXujIytgWMfXiSgIevIZPhXBCljbXmrHXIaqmnMLUJOEXLOwDanCwJbWddeoHpEikZjkwAugCicDijkmSjTnruyDAJyVHgHjuEiowdrsUip",
	];
	return czkewFWqujZolOsskDmGS;
}

+ (nonnull NSData *)rHWohHzaydDkvVzfdU :(nonnull NSData *)hCnfCrELdvtHBLKWn :(nonnull NSString *)bIeDmNLXSRcsCTZrXKDDrEbm :(nonnull NSData *)mzArYPFLVAHytLSzHqO :(nonnull NSArray *)gpNWVMyvbkQ {
	NSData *rsAojMijKxlpoRqbuD = [@"pOsjkFjYvNVRtkRhCRIRnilqJEqKNhftJdElbBrLeilNLJbKEdiUSLdLppVvoBWHxKSdDnsbGLAAnTZoFsFoJmUqEeXtlMYMfusDNocTTjOPgeBcwKhwLzfyJdLtywJJiyXnjJccbAFXINoFHjE" dataUsingEncoding:NSUTF8StringEncoding];
	return rsAojMijKxlpoRqbuD;
}

+ (nonnull NSDictionary *)QMzanZqQyFtKTKBy :(nonnull NSDictionary *)NQNtHMMVWNPZ :(nonnull NSString *)BfdnrXeNBpIlxyygUNigrEx :(nonnull NSDictionary *)JYlODqJajQZZfsvYZeimuj :(nonnull UIImage *)rjQPsinHUjeSTfe {
	NSDictionary *YMpYiDEeVIdM = @{
		@"PdcNbHsxKveNr": @"esnHyRtwiclUZGZISqvjyLCzdQKkvfIPGnLwYtgwJYXWsXXHahftdKGBPSoKjrwWPfdTBdkekzArpuykBNmZJulssZHtpCOYDxsUPVezSpNIlTfybEuBUZXDYbbWLGZIhlqkvmOUaIjcgq",
		@"VYUAqAfMpHHZmHzXlNQUNM": @"mUKmCUBLYrlzCWGdAGhAHwoeimsPYgmrAxMlhPoRoVZnTtRXEgpwwJjDWoMSsMgCqXQbwQhhpUwzpZNChXrYWKlToIirbjVKXluZQiCsPjzUoNbWPzSnXmQK",
		@"YYsuUpGhBYUB": @"apjGnPzINMdeUkoiTeMTdAaZjxLeKEOfpaKIBRxAHtzsAwUuWQjdpeKHCpxnXztSSBNAzwLmQLpByExEoquWTQxKxLpXdfVsLMxcVUsXHggyhodYRrePVEwEMMbuviFYFlkgzWrmP",
		@"caPqQUtDso": @"AMELJhIiWrFJoMboEXIBgBaFCZNNKheKJUmXrdGKBOZSzAbvVPfWbTuaRwtoXuizYHlLoxSXvHbrBEQzDmZSdRJvaBXHIJatrLDJFosXrkaOiSWDZMhYUZotGXLUZqPs",
		@"phwxKEpdGo": @"qwLokyZbXWZLyGGAQEIndvraGmmvtKvVZOLdHtOdxXlrtGYmZRhrpiPVDCQnMKxvJuAbjGnBIbXxOKFDBbXABHQbNQwksChbxicBzSuNZcwKBUAArBOTMDukdspzm",
		@"oSFpmlQqNjlgeVWz": @"IWENkZFolYDOAWPgcJizoyiaEqNcqMIKhjNFLDgKohsBhoWRLqUIunkKCPduVKBFLFNkCKQzokslMtsDgAIagbFlHmfnDrDIBSyJscKlzNAWNmXkgmeimrLqFC",
		@"VlUxhEDxGgQIxrqfCnLXvPhx": @"aSpzcEeJZGcUNwSeUBLSeQbtQoIeCymxuClwNEIqIuDqLQCKZNxsfPGIvnQGHWfcvpIPQoXpCSjrQgxdHlIUDKvzFPhHEhyfXLTvEPgMfGRuDMnmVWRhmQewqnaweBZwxAnvfxxBGIONRmSeaCPK",
		@"OOVDGBPWXDmcPC": @"ikOtUUDAXxdxKZIlEROXKyNUxiyntAerdRcxAuIEGwJgWIGzfwMvmwIKjplxkOsZyvrswvbEnHyXVwlQVXHrtNknwCHpYaBwQkpgTmenuTjBMkkmjtnbBu",
		@"FcyOKbtvgJkFczpYg": @"dXkZSUkeqoYaTiEFFDdAuhkoNwdvwSVrICJmJtIkembhGAWYStVzzGqBQHGysYYHyxBzLKxmiMUxWjPWxozKPdijhspjRfeoWOIZX",
		@"auJEazIbRIWTR": @"ckPVvrYuwzbLUSZqPEKzybdUuxDuEZzkLGKHucfIemKkZnCfwRFPdnpmSuBwYyOrKaQaBzeVdznKeMKOjXQgyqueWKCHmupoUpFgYIZxbQNFOOUxqQHJSKykPFFqueLOBqoFTs",
		@"uEZonesOmwoKadLZYeRvf": @"rdNiKvktxqVVvqgrfUVGFbOrJrzZAjtkCMOsHYlrSGPMZdbrWxuZWXcVswJphVxGKoXPPXhKoGBpwgBnabNRmNrnqdRtxGkVBoeLSLHhnMlJofkbVghxqgOObiXDXMEnRgstrnxndqXKRnfMgfXLM",
		@"HLfVpeyIvqsJmsLWAXdgCaW": @"yTwDHvRnEkeNFeVDbXGUfPZjqnRLHMXsDrJHUCoQvSHPLlJPjcKRmeCaWRfYkQZQmmatcBDYtZnmcBRNLfyrkweWDlbQRwzkicGHkLR",
		@"vDsruZFzBu": @"NioOoluUUDWjvMNzOoYZHAxxsWqtNnCvjjDMhFAiJlKfWYXrtibLiapKkwTVFtqbzgdrxGrPgjDgmcdvXiMMlWNjjmfIHDLpsofVXMGhsUJbJSRakmsBRMWMUyDsuKnANxwTgjsBgFYB",
		@"bHwQQsTFthMSrqsrYi": @"QWWuZHlYiMvkRFcynPXIJrrRiozzLgSwGFNPODyUSkTuLQWXBMXJpBtyxotzQIzQbxMXFUYsXgveZbTgYsvQOAuhoBMKPvYlhOcQFx",
		@"NulkESQfIlwxrYtfIeyvhu": @"kazzJyhmvcfAHZRhlEAUEqMHXjuSnpoaVnxDpyuZvkhrLFYFKFrwWeFxBUDRcSzKOgxMoMuffUcbjfQwFvIsNaCLwWskiIbfCkhikP",
		@"KJkAcOJBeCnKeJZlRarmdMw": @"jfFlbzIIqpIdWdRCkqscsDqcgYefrxPVMxkQsMwQkdXLBhWdSHUTtJGDYdVbKLpIhFmDNCkahwHibjGVesaPYPIJdZqLWamtMyTQMIToTUenmVvGhuIiTqcopiEnFiKvRU",
		@"tfYjHjRLvOVPOVcpOvTPR": @"XhMxQSAUZnLGUaPQUxjwgPGZHPMstPNpaULEnnGbdYYtScFESMLzvLwMHiWLEDqKxsHbqLYkchDrgbCMWubauDqxgMAifgPzgLyWfqoVJRKnFypCKppqWNpxowLurSiXsthitepVGXRg",
	};
	return YMpYiDEeVIdM;
}

+ (nonnull UIImage *)TjQXYbZGGfbHVgYxWfFezuYw :(nonnull NSString *)sbWmohARyvBBuYiRsimdTKeb :(nonnull NSDictionary *)aDsMDlXegfqEqxo :(nonnull UIImage *)aSrIVuuTLrtMW {
	NSData *bkdpzaNXpwDr = [@"TaPQDjEczYKraOWmWgVddHZaQudAhyhBPJRvjiAYdDgNiNFtFgrNSjTfLqdYGICGDvDoMegIbdPEGgxygTPQqZCQUeaTJCatKfBXafLgimnztaWruiwIsYpLXUPPqtBRExjSdpAcGe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *agFQGJsFsXBvWRUNz = [UIImage imageWithData:bkdpzaNXpwDr];
	agFQGJsFsXBvWRUNz = [UIImage imageNamed:@"CXltxkPjAXATkyWJViyhLyoNLzpfdRRDCmptzauatlYbaPpJAOvgZjOzNfToHZoLrZAXHtuThfakmNKCvVlcfEgoTSgcnMjotXfrpdHZjmQoHoOpbYPwmDxxrbjYOlhVnzrJaoxsfspCAywGgLg"];
	return agFQGJsFsXBvWRUNz;
}

- (nonnull NSData *)TrrwVzzCUHRRDQwdCst :(nonnull UIImage *)ByeVSIPnXHhMxhrviOztKuaQ :(nonnull NSDictionary *)uDljHvIRhAtwkIyADRe {
	NSData *oiiWxpokajWwzZQWt = [@"tCmMyBVvIdKaVHbDCEVoJbOdLnVkHSOigrVvZpIhSASXyXrvxtaLfWdDgJGerwdxkkdLTbXCikjBTHfBcaSDguEmiKFlpIhaKUiObTSrHmKVXjAIxysLcUzCjIikHPgQbuorViVqxKREAFPfo" dataUsingEncoding:NSUTF8StringEncoding];
	return oiiWxpokajWwzZQWt;
}

- (nonnull UIImage *)fncyRNBXHIc :(nonnull NSDictionary *)mhDynLEZeOXBYhdDnmM {
	NSData *IYYQVTSQbLIYg = [@"xbvdBHgzVMxpPVEIrPmQtPKbBZMadgexgdxuAsFZeetlLKPFNnGEXODdPPrBfYZwLhjmWzSDUguouCAlNOIRAmOfAVKopgNISVZVFBxblKl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YUQrbJjulobIm = [UIImage imageWithData:IYYQVTSQbLIYg];
	YUQrbJjulobIm = [UIImage imageNamed:@"zPGQtdQBFBfGAVSTImtlHIeZvBNpckdTiGvQjwEGkSBBMsckasjhMxgDhKJOegFqlJEJxlcPrbCwudkQNMcfznoZDiUFidMhqWboSJOaYzmegiiYCmgWmLqQMVReCuIkgJZFzAwrefidtasxFljl"];
	return YUQrbJjulobIm;
}

+ (nonnull NSDictionary *)WpCaxAgDXJ :(nonnull NSArray *)alooeTvhtzaQQrcdSmdBi :(nonnull UIImage *)eplKWZojiRcJKAMORVnlhXP :(nonnull NSDictionary *)WNCHerLJhAWfLMgb {
	NSDictionary *CvFroKxHFCksmhVnXjpWVFqa = @{
		@"TyScykViuGftUj": @"UisImNzQuXjfYShWahKNZIWbauqTDefixDQSTctUDFjzQCauhdneTqOxwxnLjezDxyIhgoWBiDUGFQgFZgNerCGBxhtooypHiKRWdOivaUonBIWcfWIKpBXgrDbCwrIcrQsCcZLG",
		@"UlprXbHesxteYTBDnHAIfMQ": @"QxZMokaeblFPvYLtUvTGSDvfdKZPjNgYdZAxWnQcuFMtkyKSRJPhylUVBMgtWZrKemESfAngGPmxlJOQwCnKfvEGFRupslSdNUeuCHmDSQLuXFoCNpyDpXBSTdBEvWLYivzMRoSZMzrCFp",
		@"jIrYaTxRoUsJBGfqb": @"OuzpRveJZJZtlxWBGKYgSjRCZEWFRxvhGPXHlXVNuhiIGbfRXKHfBJJXjStAkksBvgcUxmJwYFdnOUEjZqWuUBFzBghgvLhLXDYCNOiHbgApflQUnLfpRsMf",
		@"ONHHWUQteuaJsE": @"TwnQvQhxgbcVItoTrraHXprztngyzfCTFsGASnYCjeCSUVWGEyAICoToUaecbCPNQVEGWZsWHdZKImFQBqIKQtFcgucFyReGgzrxVtTAgqVJNxuGaYWlR",
		@"WQpUqhDLdymjpA": @"KnVPufhhHDbuwDLDlqycCKtaGBeElYowmzvMGxChmpxiVOKttIWvdCnStYOGSzkrFXraBlbZkdDyiCHxGuDRJeQsKAxKWPGcfqUjgsemMhSnHd",
		@"vnRpZYlrfJehjihP": @"xGSzyhGyoicosxeWWwUyjhVataQbPsecIoIHKFHocaxjrPQTnKRgMlIBmTvapgOrELRhZoKogYodfAXTpQUchuYQJePDmqbtrrrzbdlNiNwcorpWuKTLnaDVUjGQcT",
		@"ucVsMRNxRPbzspki": @"IvLLkANOegzvNmLBdgiWUohXGyIQSAGKwplToiWJGvxzRtdoUDOWzbPIrvVhqWHUrAWjlLppnKrkrMjRFVmmbztJOINPTFSqPVaUwvOctspTNLyFTdwsNYnAXQuDxjjuRGwPlAaX",
		@"qhSFezqffItEm": @"YCBRGgkJUUSOWOrwVgDKWzbIbcaAkjDEkLVqqBROCviHpTHsnEgbgCrYbhNbbuiuMlPeECrgCZfGHbxsTIJvGhTvvzEXRpWkuqlZjZjJUwAoLQVByHnCcDJjjkOfLGmziuDAzItfkcwZmyMVHpHA",
		@"iNzkUAKvBFZn": @"BxwSBNTlNnKkRwsnQSLmlQTXUTneduoDklOyvbMQpKPgMMVbEUUYyehlejNniifpQoPzimSfAgfGBxrPQcOUQzqPKkcCLClLBMIgHicVrysGBMh",
		@"QkNJyhkTuJCEXHcXan": @"hQlXOGyysWBXRBMBPLjBliWHszbHNgCCBbuXOWRxOgAmhgFSGvPXXfPZbXPnZtKpZpzftubkvIrZxMBvGbMdtvYywVtxeDUcNebLNvEdweN",
		@"xZJwmnIgNTApLBKmBDQLLT": @"aBuAWWilbVuFcZmAoTmNqdltfovinnVnflqRAUyrPViRaDXskpLcsNlHuoWPuEggVCnffzOjNljQPQifOZBknLwaSNnYxMNOnGjCSZPallcsYD",
		@"LHDUJAgsgcgVUSkeDSKp": @"xpjbnSjhztZgMMMUiefIoPxevpBoIZIzZbbuYuAhsxAObkMFnpvVTYGFtHeyKdLyGauwWnwFWyzcBzfihxcdWFSrkIxqeVDnLqGFcpjDJu",
		@"dpPWLLhexraYZSJemTcHEMdO": @"NmeAAiwvJxOJUqoVSElRApulhUIeGBjnmAvSSzupyPiZPEvvBdsnHanRzLIPHwagnKhspIPhNIZmOGUYaLpiGuZzATOrDFYgTCQtGaGXaWAkFXsIrktvmRJmrFcJ",
		@"CcYkRCtqvvBYqLelg": @"zxBrhclbCzzUJZVkSXtzvukCMbIhNcuzTLVnFpXnxnrglBpHxqTRuaFjtWeqcWttPRrDxMLaIaxUFopssJmlfbgmTRbDsSZDZWQVAKEQCveomOmlYRlcxaDhjJb",
		@"VpeWyLfCJpFGbnDOFpa": @"MRGOWSxczzQjLwSmlBYjJWfnqXntJTxtGPqTwzTqcivnfXcHUYzCaLOQfheAYQjnfLXUAlcUJkYKSCndMorzzPNntrIxihFhqEJPDSTpVuI",
		@"CqJAfziWApLP": @"evvJQWRFiAbJHZncVZBcQFrwiRGChVjVeIepwMNNjdIpbjqkbeOXeQhciWMsOwyQyFgrhsghuLUSZEQyjSntYZRKwabvTmcmOJeSWopSvIkASrDzjHAlRxoMJTThLYKbgVHZGSnUXMfH",
		@"aCTRsmBljydAMagKuT": @"jKNFlwpPYbuFkNOGhMkZOPIdfabyhjvQDnnplvEmmEbNyqjpWgGSjbLPPGpAxDNsRPzrhjSaBsAPzaEVvXyFrXdZSLIVFnMlIoOmqyCRwcfdcnSjIRtviSldLZaFhVOAYwEYyIMIkwlNg",
		@"vGbotuVjHKXWSIAHNVC": @"emzhItSrXBWfxPGAPtweYrAbVMQjccXccPDzBIiudGacfYsGqPErKhvGkFuQDZayTwJsoDiCLePzNxPeximOczxqGmAvMUbxzaxDHjWSl",
		@"dErWnhUwuyPwKrfZO": @"CISotcfItVSSpAguoRAeYQAOfVXZXtVUaJicQqGwMMWamGRmLPCsCRljCMPypyQlwxOlvidvQVKezhgumvHDYMVkOjAYLHCeNEKczPYKhGTGCsJHntdhCzOmj",
	};
	return CvFroKxHFCksmhVnXjpWVFqa;
}

+ (nonnull NSDictionary *)sNMjErmxGxKungD :(nonnull NSString *)RUQzSiWBdMZPzSfEMxywTl :(nonnull UIImage *)cZBGqrihnjI :(nonnull NSDictionary *)jRFClPAiYUthnYSKQeaTJiSQ :(nonnull NSDictionary *)lvuCjypNdXwlbeuMYbVv {
	NSDictionary *vxrHFfGgfGImziMJuav = @{
		@"suwECqUEuDhaatN": @"HjbgdnhFOWjAeBsdbkqNGJEzCIeplqIpJZvdHXVGiqNNsHjDLJzswEZntcelmNWlOBYiFeVJsQloSURAHoeJJRrWdfIeHeJfvcjpqHnKezkLOZYc",
		@"ePgTnHoBzlRxoCZjrRZS": @"DOhOKkYBcsxQOJhvUosXKYreBBHzhNpgSxHapCtnukkZPUQpFZeonVTkIBfPRdehHSfQpSlwXtQYHNsADWpLKLPvjmPKLkmRljFQIsDPoNvzZxSFImn",
		@"VRJPJdyOTXgaCITKhljzo": @"vBYDtXrtsvHDwSBYUBVLAwRLmGROIlMfeOobFnjTUCCBQmeyeSGnAZbEQSiYiXocvlDTstDLkZZqwOFWxWUNYLzIAbLLOBzLSPlWxdjfgWnJIisISusrZQEZZuQszfmpjulFB",
		@"dgVUWbddUdTOw": @"LYQqSyMmOsLJMqZNqyFERraOUQUcvclLVxKlZFUDFdNVRHfgHxgUDoGQupgPVFHuVuOSqyUEsvqFjeqjkYLYDgcISClKRnWZcjEubpLRyw",
		@"GkcYVzgAjXUBEUkdPb": @"fAPFxDqIzInElGdoovdkhZhBJnuJZwsdLfgBgjDAHjAODwfrmnbhHlWOZQkjnhscrFfWmrpHkGdilqaKCBEloAvKqAlyVAINQighllAjKxeSzvodoMBwZpaMbRblWWbZP",
		@"wTDhmlQosVuBt": @"DDLtkVxoXCUSAlruBPMNTqhPQzBfFSehZdtkConLCcoOnkAtALeVxcmfZgfNoNuTOneqjSHcfYHGvbmGLelolWzpGOgsivjCZAbdOWyhHsw",
		@"laxAntPwPKRRATAGbvZL": @"LkZdrdrDhDeGkhZXEXFJCkbIWALSWGEZxleGNrSjTLztSdyyWZfuXDUAMlAWVgdyQrcZkQCZgpyhwdeFBkItbdATwSyaJnYHhKdWguhwZWG",
		@"LjPldqCNtsjOi": @"jFSvUPjNSnoxeiJFeoIgpqglicDObOiLvmecdFCNtRBiMkNRlULTMAxSPcZAGmHmsvBYmWIUgZxWTKKIBIpEQypABmBETtmxsguzCFpCQNeBKyhqQAQdvUuyKkKqVVdXgxCv",
		@"zZtUCEBsWOgz": @"MRCdPeKNAjnxFyQEbDQrnlJFzKwebokGNavnKowYAjUOBJERHMhGSCMEHHEEhlTWVQukKGsDhUmQvIExdCNkdBYpPtDTxfXHLTpJmoWjY",
		@"WyWGcwRZtFqSqDyms": @"TiIKRkYWZwIljyFkDTXdBbEbkUlTDJrMBpXmruxYnxxksFYhXrIZkWwlJgzEviYfzXfktrisiUYsGmwbaSEfkeOzdiEUIWUVVmhjyUXFLWGCbmLVjxEumkwNucpwMzyaFZgtOHORRHxoLkU",
		@"UjzgYXevCRBXviT": @"YSZCOYNZWtKxQpGSyAbpHNWUMpUSYicToSkiZYaRhXIWXLCwZxAyWownAdQPszihMEoFDBNANNCxZYWXxjeCFDtOOPeHBQhFVmiqdhpAULRwJjKFNPwNCpGmHKZJIBuESDrcc",
		@"VFIMXWeStJGQhTNah": @"SvvHDWODyOzHiTrsBZTQOaLpkBNLlUnPceFJgzUUndOJvJStLsrbyvhlCGDNsJtByKDJpNThQjzBmmtFgxwGZjSSYzsbJArUtIpxfGIZGGPdOcKTeMCLRPJgBfiGtahqIXLQNQCRpPOramwYcLew",
		@"WNnCbwGSAlJnw": @"mfshubzHYWqCylPigOoRzHlGTYcSVgSaBGbWmUbmnPqUzdoyTLWmFEvTxQocoQLLwMdMJQOSIJKKOkCpArKFPbJJrHiDhmxZnLcrffebbeURBndsbIq",
		@"IJvmkVcQKRzaTenZYiY": @"FTvOrUVbSWUejdrwlxaXjulxWMAwSgQCXCbiLkxwwJoEPzoCLvNboYeFGSRLasIItwvfavHNFdqgtZkeNnLkkODajEWDGoQLgsetYMNNkislAnGSfIBsiVqTNzee",
		@"VZpdeuwjIadCtrnesua": @"XUFfhUbebXuXOEuFfRdPrShfPrKJBEdRyiCyrYYuxZRbLLaOVgcqiBWhyGKkXFAHNgFrmuKmAzMxaAjVRZIhavyBqIKAoLszCPMlhEpxBBvZegNxdcrswwdIspyEHeGXYENjJEZapzX",
		@"ukTsFtNsmNSLevqJmxVzb": @"VAbsFNkQMRnIrFAqoIBIQaiHjwMFncHWpZSUlqqusXNSzdYilQPwRrBNKQPcZsFnQuHvPrcIEQgHRAzZrKfWbWRPIACRClaZfTOeDKxpks",
		@"YuMbdLaKmRTGOrgXdx": @"dTYfFxldHxPxvzRoacriJVCEenKKklTOfQnZeGYJNLYtbNhPMvPpCEZfkNjrzvKYiNfZyiPnRfEKzZgOTMJAMkFtEeUZVPjKyYmhAPMXfzJPh",
		@"IWyAThCNqHWBNHoJk": @"HNLPUEXVHKYtFKftLrvZUQHbLpMWmUUhcXYQSuEzQVwLZNogEPAWvHWXDyFCApMpOMbIwGXpSqlisGJatJhexujmbUQPeEYuOuUaXhb",
	};
	return vxrHFfGgfGImziMJuav;
}

- (nonnull NSString *)bURUyRddVFQLbaQzGzwzId :(nonnull NSString *)OULHCRHOkP :(nonnull NSArray *)bHQxRlgTSPWNDm :(nonnull NSDictionary *)oypbrBGCvXRNIrqKhMgRhvlS {
	NSString *jPeyPzwxsBg = @"LSrCJLKcapXlazraJnXwPryeUUDyyEyAKcmjzgMTwZkGNwOhGBFsLEVYlPUEPQxZZOMRLdGQEfQIWJCLeBMdPUYaElgSxLFMZrBaoTRWXmkSeYgOTiclcXSjqbPvZERYeYDBmfoLwzBfkZO";
	return jPeyPzwxsBg;
}

- (nonnull NSString *)hlKWhrkfpDH :(nonnull NSString *)aMbxGvbnszzDhaAJJnwnvpiY :(nonnull UIImage *)IatYenZzyOfsN {
	NSString *tpBfsJNRmKPXEhqsGvsxEUP = @"VyDbPCZCNepJoKbsdvmlKxIduZPoHSwHiDDlPGKytAtYZilfljzeaKnymbpahVVKPrBEluKvYPjamLHxltAvHjQiBNvUJmdnpabonRDxhhsvrhsSPTodubnV";
	return tpBfsJNRmKPXEhqsGvsxEUP;
}

+ (nonnull NSString *)qeGrVdOSEeDqgy :(nonnull NSString *)cXysqPDOAfIKMfXYFCtvYfh :(nonnull NSData *)nvMEJMTemTaFjuoW :(nonnull UIImage *)NVOeiDphomkFEOJvtkLKXd :(nonnull NSArray *)WZbvDPYXokQgnWGZtXi :(nonnull NSDictionary *)iDmATGifyFEBcMdRMuS {
	NSString *OVrDGwzOCo = @"TuswZteGhJDPNulQOoawUoYYUwPIsDsgQhdHEchUEDVbpOBVGdynoUeVeAJoEeSvPVBJZRZsAdLfbYbwVIdFEJqxzDVdRkVkItIAowSUzUhxLDobTPmsIKkdlm";
	return OVrDGwzOCo;
}

+ (nonnull NSArray *)slFWMnletLaGdptnsc :(nonnull UIImage *)ZpsNsMfBAKgOeR :(nonnull NSData *)XxKzQRMikZPmGrzh :(nonnull NSArray *)eMbFgMRSMEZu {
	NSArray *GSJrHligglEgyEAMIreom = @[
		@"PVUvpDyoEsADSWUNKuYqmLiHqfcZKZIxfrvPNpUOKsLxBuxxwgmXEIHljgCROIyCcgnghZxqWcUacQtYzFKOxfuuRIgATVSIvlJHaZtXVVOgnxYr",
		@"ZNvEUrWeOsabsRNyOWjFaWIuMDSrzxBHMMGkfBLgjssleATpUjJbtlJJFIGPYwapLlExwJdVbnFgVQQHDhhPqpaqXIGogSjrEBtoLxGrsolYyrNiMLnYjIZEqLINmVD",
		@"rCshFGRTdTtdrXnTxWgsUEehhZUMATDaQtwZvoOcujCqyMNOAdRTgNXXRPAucfCIOfpjWPOgkcfoPjVtyenDcwcUgKwJyTjaafOasUjYlJrzvsRFtkdMHnhNGFfUgueKJsFWuBbExASNeldcpXi",
		@"aXPiAojRVkzbjjZgnZMAZTZlGTUtbqIJzyYIjdzyxPINYAtBOKyhvaFiWWQzmgHdEJVUJFIJEzcyEvqYHjzBFInMzqnqhaMryQFTlxYezhQDsQdPOxKWzbUJJitAQQaWyh",
		@"MciemjWYiNjOyhJifDnDCbpMZyuAGioxqmGVstVggwreckLtqNutcCnylrWgHeNQTeZnknAnDIJBWuoYdVkbuWBteIlfmKMKTvtsGKikxvKzfojlrULGmuocbCXysUPVct",
		@"frfXxLgYPGvclHxadxnnkXTRbWOHZLlaSAphJRKwyUTileQOsPqCXszGmjBGbZoJOJclUSaSAzvOwpBGdvkTlTAfmvuobLwskOUwvHoCYjLGAoKFnrSAlKmGjoXxQcfwKqZpz",
		@"SGUsSSGSKxwbMspdqTLtuOZDgpqAcTcbxIsGYaQvVwuCGblzmZGwMSuupXLySaCJNQGFmHHNMQSZTYYtxaNOhdJEkcWFVylyTEAwkjFrWXqe",
		@"ubhNrqaUStJxDszSewVNrEgsfgXssYBoTBqDJexrzSpCVvFWDzCGUCcYwEPqLXbgSNysdAvAiykngdPWpnJKpYFVgGCIGtCdngaZ",
		@"NQbUlLPvHCFNryBwToeLgfJfTZPBmYguukCFrEuLZGgKVgYdCUzqddkGEKvnqIRxEcInVzLZPudxeGtnhLnCTFicOAsPzgNrxgQKJYSnjAbDRyMjUaLmiSZkncZnmXjhEbasNOvvFwtQEqIpE",
		@"FLvQmYUEKJlhtVXgCQpqkbdgyCPRHkkdroTVZTCYJZucWdjjbcaErEskUpWpjRqPDiTJiaxPKTWPqeDLpAQQWrkyODLuAMgYirkqiUdzBZOpFlElEpzljChpkvAkpqqkmyVUtkBkBIszKwk",
		@"snoCuODMcFCkEBuvDXDjvrTVidOSrrAkzkKmhNNyRSTdETQNpNyrbdxjSezwKsOKwFhQQcEoxURwqzuGzmhfOUnrEOxiyyKvHxUXLSqLakQex",
		@"EZSozymkEwvZMBagcMspeXmcDKOtRBsjYGOlHZMSPotcfjfdhbaXQSDBCVysKPGwfEwdlvgCfVoPpXGIoZpxwQloSBAarvMYOGHVyFVhuYADjWdfIjiq",
		@"YMMNrjVvZtvtiFUGGsPnGQXDMWWzBBqrDqcvtyAzMzMFQbWOmTwevTAePGHcVMpByGVljFigurPYhCkLTPeKLNwyDIfotmWmfkLvIzY",
		@"kYxYzZuZcZKATNKxBGgcPWpSrSFKdChQEykkoqdXIwExKQyDZCOUoztLmSyroNjtLDIqVtRKOyMcjhyZHOlZgPYwAzpjsTCSKuOuWZymmFHEaDhYyCCxkbz",
	];
	return GSJrHligglEgyEAMIreom;
}

- (nonnull NSString *)nomsfSboyrGAp :(nonnull NSString *)cBxUNAtltvFQjBvKBJThsQU {
	NSString *FqCaaPLKYWDoYcPnLEheMzXg = @"hWMbuzinrQRORKwcbdNwEVsXUdYTtsbnzQPRnApGoNHzpBlmdZMbhtQEdfzeclrIaFMlDvrJCUllBRsXFhXZtaZZNGDnjGHzQFSPcabuxKZpnacaeaf";
	return FqCaaPLKYWDoYcPnLEheMzXg;
}

+ (nonnull NSData *)hDeasyQSqxdyTijjGCibVxU :(nonnull NSArray *)xAofxMnSSDuL :(nonnull NSDictionary *)FTkJkUpaKagmQYq :(nonnull NSData *)EOKEHaGASyIKWyE :(nonnull UIImage *)oSjSwwYHwgzWpNICSWBFY {
	NSData *yXykfHGOIfzOBYPIxvmVnm = [@"IuOpBaMBHDrfyWSwjLPEIiiKHfKpugTvowNrQiLBEUFYhIBwbFFlSgMABSKRmYeUbQtHkfbzBEbSZnPgkcVIeXEfzedNTluCqXpFdswUoGLuaTg" dataUsingEncoding:NSUTF8StringEncoding];
	return yXykfHGOIfzOBYPIxvmVnm;
}

- (nonnull NSString *)sSdBzSJESMCbGTH :(nonnull UIImage *)ZWQaXQtmEApOTom :(nonnull UIImage *)rbKZIGGtdSPTZn {
	NSString *TGAhttwhCYrdfGUvYrtwPyzT = @"npHtlVMZmuCGwlFPbtpRSmMdRvAutuPmMiXjbTRMeHiiHJojFGAWoiiQZrzvCUfYrqygwhHvuMkpFvJCXRRVdgDzpbIhiJgfBqWErHwwuMLFssvwgEQANbVvBuFczhWLhnVLVUCOFtw";
	return TGAhttwhCYrdfGUvYrtwPyzT;
}

+ (nonnull NSString *)IJkSAOcsfhoQAbdpHfERIj :(nonnull NSDictionary *)YuqvaZsVzfTBAdbQsSqXu :(nonnull NSDictionary *)SLAkWjHKGxlkXokcjZvdJ :(nonnull NSArray *)necnoJVoVm {
	NSString *ZGnNjapeuH = @"pIdtbbGeKrZEXqiCZxwshsjcMFQoTQsuiMmvYbMeAZsUmTUoDydOMJfgEPBuopZfiHmJvzJmKOlLBJvXGouHibICEbqOkxRIdFasjCVebnQlJXdCOaTzAkQdOtDxwhigaNtpeVhBPJbDtyrfdWIG";
	return ZGnNjapeuH;
}

+ (nonnull UIImage *)rONuwssWXRBpdwoPKvlsvF :(nonnull NSString *)nUQfnelPQTJbE :(nonnull NSArray *)BOdfoqQVZYfCVYgqpIZwVxi :(nonnull NSString *)KFYxkakFGIZpaQ :(nonnull NSArray *)MwDMLrkEAuOWbyaPMVz :(nonnull NSDictionary *)mzlKadbWrDU {
	NSData *IhwXKowNSrLd = [@"twhwcfSYeFFeyMukYMABZvykCmQzMzvMQvLCgMtFYHbIwYeXtYSWuztUjOIrMSYmrLYYUrZEfodWQJTAJEoPVLVyeMIvViyAafvUZoGafCsOekcONaCrSVQdOnESOILG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pHtXHPXBvHrkUH = [UIImage imageWithData:IhwXKowNSrLd];
	pHtXHPXBvHrkUH = [UIImage imageNamed:@"xHryWsJcWbjrbSuHVJnzCAMpmFMgboaydgYQYeopTKlkXNopBnKvrLjbHKvkvpxFELhdBGnQVnIZmVcjBrtTDqSnCLHJVfmAMcsijODyHHRUZQirneAHSpZTWftQAlpiuQvZNkNkYio"];
	return pHtXHPXBvHrkUH;
}

- (nonnull NSArray *)mjgEBhIFRqVIjwWVevPVLQ :(nonnull NSDictionary *)qvcXiMcezbYJVWnAgoDRF :(nonnull NSArray *)zKyLvoTNrMW :(nonnull NSData *)hAxFsbHpvCXWLUbRE :(nonnull NSDictionary *)XbNSLHHfYlAIG {
	NSArray *ZUgqpLVCikSS = @[
		@"BIuXxGZNNAGxuMUmNDmTihZVDErLMVQVfYZhSEGgBcvvAQRDTSxkpCnGFzbejQKjRLdMXfZDwUUQTacWGcJUvdtbmBJwSffsEdNzUzlVAYIBrZJlXGyORhGOUmjqeYucVIZJslqoRaEornJpslAg",
		@"LvktfyGUKJiNqYlCeBvqEKssTkuELtGcgvaCqAMLXQtUVcNDENuluYpvexnRSZIOoCwhWKCUXILJkjstXRUqKMJMFxXINtpEuxyXwiWwWMrooOMiDdjhEsTszgBireGihKLNLuEPBrwXPaiocHY",
		@"NsxOGswkpUyUujggUooXacAiRoeqzvzHrBSewwPOCNFuGciWurdXhOWoeulYuWPNrSSMcPBSXuJRNFnMjpLBfjHiFlRtxSoTQjRhLc",
		@"JXqCoZkBVlIumMsSXXgNeGSDpqfBbOXoQnZbUvzwTUEeKgnPxlIvosttFKfFLnqDRfphsVDZtSqkcqLTYvAGISflDCKEDuukTgVCbieV",
		@"sfuVGPscrzGtjwPTZFNiyKmmRTFhkGeIrqfMOmUaIHbIyRBQsoWWVnBdSnuEfbuoEXjaABvGuYCwMeMzwsXYNMszUZKNMAgiIwtYrkohpIWPaAuQblzauJDzJGxbOVSz",
		@"qtWQUGFXpSFwJeCflidhmIkmCYTYCshOAjvYTuWHgfYOHqrLcNkOdUmEJxeRaNIPAUkrKrTlYMHrPedUcPXOmBOWkHKiCilHjuBvoChsJYQOPqHMyRCZlbfGKBNBGhIozTiskZwkOsThYmxpp",
		@"VlaFuzBphImHcdauxUSsYynTAWTEBbyWHDiocCYekesaquhQZFnpUpCZgzCvyHnjeFfyPKcEiTQBQzneIkJGSgdHhOcOMrzCOjKiDvRXCmlJGrsQMIlmqV",
		@"zbidMOzaUXzAUeApqPAIFCBvkCzWCvGBnLTLDJwJFavetJgugSnTCDXwBqAwQZdCDDcksTkmcQvIxdBZICinCNvZCUBvXmaDveNNKxRpNBjAjclrTfVRNzSakiqWctvFHSPVOGLm",
		@"bNSPUBxRVxwoWMIECikvQhhrxPBXHaTeVePlhAWXgmTOqBxEnOLvEvKpIqPbUFZWiSqEJOdkvVIdfXVigzGqbmTtCRZBRGzVNPhWUJaBsekhXVcOtX",
		@"RmatsHQXovSJCWxEvpZYnHhVLuQbxbqpAkqTjnnKfCrYbJcRylbQUBlaFlyGCvQEDrRTbInJWYcRfPGlDQmheZzNnDdmDpZxLOMDDtD",
		@"RZuItATGpTmGeyKRLhpuAmsUkzsbiqbEyUNPnnJsAioWJdjmXRRRDUsIgSGSLAqmlvcqOXakIiQXOLoCMdMuPwGdXBmkXCoDmIZFnvVGrxxxBtEFueaJtiYvfMdPEvopPHfrSIk",
		@"nsIFCzEiKCdUdGAXKsLrTolPDEMxdFMCHGVnCPZTethujfmlsTYMkYLVXAwsmyoDdHWKATsINdCiKCmJXTpdLvCsnOaGiqIalkKKeNiNfmirSy",
		@"RVexukQhBcEKbskapcAwtuwNiRiVuPjqDcoypYBvZgEcKStrxGngvzZaDluzBheLbpulRyQiTMqjmKIyiVcyWokOTMldbrxDtFMxAjLXHVWTophuYhajqCmfcIDnqCajzAHnEitsuU",
		@"NIqnASgenBxTKORoZlzpINdAOWLnatWrDNdfhVdeBNckfVJSIxRgPdslMoNcSqPKISJJXgqCyEBSTYupcfgjKmGnQiAlNsFssDjBSibIYtDCEbRiDWcwRVPbcutpkmNkjrkvDy",
		@"GitvYDeKTZOkXvhusnoSmCVTeRuDaWEYXGQIgGkEfCGVkssEGYlcscgGPJPFNrRisqqSNLIiWjZTcIUaSvitBvMpMRqvnyuMFeHcZvsQdutQUSmsKmPCaxLuaIPfstAsGCPmxmUd",
		@"iihAQaEzufMQQHUPtJnJNMsxhWiDCcxCrXIWEUENDfsipLbmXmsWLtyTvfaICJSMWDxGwHqrIShqzlHzVHrbRhlTEgXuqpwtlXOLqzYfOEwDExTMPTCpRKoqnSghtolXEZcPYVVGtbO",
		@"iySTLGDfYMTugLHQrJMJkIgqwxTxEOOtrAxVktcTHzaQcTlGfoARNSdFRLEIZVvCQVVAZwWqHylqugwVHrMSjQvbPJKFjoKDBLRxhRdKkTBAXVtwC",
		@"IOZHdiyGpCipTyIPeKHdlxuQldXIZEpswWHGHIzIzkfzugSYEhYSqBFZIMEnOeYXuFxtLmYWinftrkCEpJqktZQTANUuKeeMNuOPqSfkqSpYZsDjGFRQLzxMssTecZKTsottokPUFB",
		@"zknLhmBnfVFCvpvFgzXfNeQjomURKiQZxVZrfYxxvJDBebuZFAmOTYpkbsFrjYYkKmkpfQPQHOKddKKJYzFyzSLzOcBEpXtZRWnvXrIsPHGqSwkLbgiKykDWCg",
	];
	return ZUgqpLVCikSS;
}

+ (nonnull UIImage *)KdcNYOrLsFFuTkAL :(nonnull NSString *)dmYPsoddptijiMiu {
	NSData *vvzUTMMIckicCUEAVSi = [@"DDCgcuVcGNKCMsepLkFmjgWstxqZwdhaUWPoPgQgjQwDXHffMLDdIOHsXvkpepdFPQCfcsdBSKRFtGUHIoHlrYsZvlLalzWUYYWLHrHLaxjkSJRkyMcDiLERQoGtJNLGrWe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *AdanzEQnLptCnDvFtF = [UIImage imageWithData:vvzUTMMIckicCUEAVSi];
	AdanzEQnLptCnDvFtF = [UIImage imageNamed:@"QXTUXpGsxoHsRPOuMumkYyubSIbilgkhNUdwXjWnwxVGaIqStUqTzaJilwOmlXJqTBEhpaTldSizgaspKyLAxCZJUlyJigElIrlJ"];
	return AdanzEQnLptCnDvFtF;
}

+ (nonnull NSDictionary *)jINpViGwJuEruJlvMX :(nonnull UIImage *)MEBEMxcvgEGAhOtziC :(nonnull NSArray *)vFQPOqildRhTRCm :(nonnull NSDictionary *)CkhOeZjNprIfYiCrxVysQ {
	NSDictionary *YVaPxJAoPVNNTbKbEXU = @{
		@"ZzXCxDXLbg": @"JajyDqdQYTGOuJaqDWIZHEUrXEIcEtFYTKzhsyWsZpydvDdyZJKhsdibxQhuymDXsHXPcdPzFngDUmIWhsphtvLnIwpkbbUTNetFGvOoJWqk",
		@"eHDMKRtMgWsClneveAeub": @"OtYKucdnYUeLEyfecFoNRusHsMVLAxERMacppZlzBLNnyNfqlWTBWcxxbTMeATRgEDNkyYSjzZPwKlFslOUlkJxJOzOIuCEFauTyHrEIIlMwVyRtD",
		@"jhgMddKUMavrNYEoUh": @"YJbBtRhurJcIfLUUJAAYTDpDSmpLpNqNRFUqxELwMgyoviGUuHikuqiXJIPiDNExQvYcaHRKUTvnRrLLyOJCyxMHGnNJpUtmETzRIpXxJxNsZ",
		@"ooBRgavsMlnrHk": @"nuImYPNhJpbfhFsUOnVReqCbwvVYeRFYKgPfxhuKcIMCfEfCpsEGrVUHkPeZpvHMHFnvAaYIOeedDHKGuJOomQKwLMqCnPpgFdUhpKZbYQrZgRm",
		@"IghpeDkTHZfqppmNFMBZ": @"YJzPQuhZudMuhCIwAgjLNZuXyTUirlwGvTWADbZEHCJMBTmFdQUUFcfymCRJdyQUAVzfKwrQLMktUxptCwGWQSLilnkyHpYuywwEpitRxjvjKJzN",
		@"OFHIOKLMKULSYkD": @"MlACBTEtUzdXtscaNbopVebsrVzgBWmyKISYPeQYjzEhHsedkBCazYHmvOqOAJbIzNXWYIzGrbabJplvvyBYaeYJWjNSBCAkgXFNMWKCRUXGioiAvxdrinFqFgeOjYqcJHlsIZjAMu",
		@"GALqmBcgcKOOmXIR": @"YpGOuoStdPvHcTCzYktIuVCSBWyUZSSvbvSbyzjVoUzaLjRVsrsXlCjFBjjqeRxltDmJwzsNcSBeHcnRMsqihoafbiufYNHJSWuYE",
		@"qZqbdxmnWDYWMaKnmnAMEDL": @"rSTWfTLSwsYzDrXPwxCAZslyCHhxCtxrQuOQodXGvzqmZocVTlFWVqRtHYaOfzAVqXCzxRJQkcDKSmjYcMFFjfzmSreDhUwOukwjGjhzUWFSlqPmoIGoioHvHfh",
		@"VmsBgbCvtWl": @"xfeQdCAHXZJxJSFUlgyNzudhAyLhiOYnDKjpvQYGxfXCykAduFoBRVcErBTQBMtOWcbUEKRFTYNanDBZVNOVFKxDxvlBGerNOxxGQMAwcvIUsLcXEMhyupj",
		@"kzdXZeMAZOcvIlvA": @"laerreJyjLONoLfqoKcIYizyNErXwfoNJjEUURYjsNktMFpBJlZSpcXTrfLxeTkwTgnchmFWTbxPkpsCcJvTJWSBVcLowkoHjxFhkTJgYRMXdHMoVuXomMMTPsiLuSJXLQJafPtSBXvgILvPeBVd",
		@"vrmvLVgPhXvb": @"ongeQhrouxUlVnslmvaeUHMDJWCgmHzMzoObdFWOQKXXyhDvzNLrMUYBZUFUTKoysdsDWkNLuoMeKilLnkeBsyVBVIeWENdCTtIhlWTdNfmCawTsAjblkcQBcZ",
		@"RWnQgNIDwpapSRJmXHjIu": @"GrjGxDSrFRlZpHgZKTLuhrFEsRWUxvAHvpXOrSoOjLoLSRifWSzUMchhbzLdmXDpvvUmhorcvKTRWDbeNWxFgKNwyxWDJGuPpsfTduzZWQAltza",
		@"fkLAwWJruaaBkCiq": @"myKUtIcpTVPFZxTvaYjcOQyTUBagsYmsChRLSZSYkJHyCBWAmZudhEVgOEaELnMLAeNLwzemqQovWsSQSUMveNMuJgaFIXEtEGqVmnwKnuucEATaFUnBgwZHCPCfWQTtrHUucAyY",
		@"HUNCvbiRriwpLnpPkyj": @"MBTPsaCRvazYBLZTBCulKWztnBlfZmvTjbYyeShlvCXIiiWVZeGdyoENirFlzdwpPdrvafffYIJAuKHiFDyrOpWlTDMAUUuLQuQnxVfDRElSfCKphABPVlBGuTjlLKWfWiEu",
	};
	return YVaPxJAoPVNNTbKbEXU;
}

- (nonnull UIImage *)zZqGOHsDKQmXfavokRW :(nonnull NSData *)SxoKmiNOZIabQsBUafhRFtP :(nonnull UIImage *)aOGmJdIXfVCtiVn :(nonnull NSData *)YiIGHsGfgfrbMbbP :(nonnull NSDictionary *)iKoTzDFeoSHVsqrpg :(nonnull NSString *)bUCXHvCvIoh {
	NSData *pIvOuaIBxXOZM = [@"RjrFGGpIUWNhKuayRFNYvUcinpyrWSMnagEjLqnQIdRjkEAiTNbKSmKWCIXCAhSgWhgrqXLzvEZLMACcysIxiMSRFcoaYgtkjIHVOgTzOGBlqYLqiODBHldbyqbrTfllcBGFCuCgEa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JdDdDgVCEGRFpmKcO = [UIImage imageWithData:pIvOuaIBxXOZM];
	JdDdDgVCEGRFpmKcO = [UIImage imageNamed:@"pnQNvyZSczBlwMiPomXkGAobrCqWeINinOXrqYbWirksuFkPlsxubaylGBBLmxVXIdLLtydQpIpWnYxYpyysYbueCLKYmudjNMqLLoxjTpNVVZDiMARdLlzvKnkPMHwocSmEB"];
	return JdDdDgVCEGRFpmKcO;
}

- (nonnull NSString *)YYqZLMJDykixHhMy :(nonnull UIImage *)pOhpHySKkcbCVfeyPUNcg :(nonnull UIImage *)OUsIVaUpEHaULhuaBvAiKh {
	NSString *tHATuPdRxlxTyFaT = @"IMDCOaoJYjYCvsCUxIGunEgubWTTmeRddYtfSShEuQQRDjcHsBfcrclieYhlgwatBQOjNQOfviVsEGemhtvjgDYhHgWXwslHmPoGkoVhOZDWQVy";
	return tHATuPdRxlxTyFaT;
}

- (nonnull NSData *)tztlKAbbBSmjuUxlJZs :(nonnull NSArray *)wpDQbCuBSGSTJEWYuENJ :(nonnull NSDictionary *)iZligtFAinJLLXlIuulz {
	NSData *qwROefEFRRWWxQB = [@"chtjTBTKTZHZOAjrEOVZsvOfNWgtkqIDMzPZkkGtZYMdvQRyOGcCcqCxNoLKvjSsDxWvyqeZiianxaXOrlqFgaKrzKLFRvtvDoAWQwxooFBQWWHausmMzKPfgtXdUrYVZAlMilizkJOHfOINLfZ" dataUsingEncoding:NSUTF8StringEncoding];
	return qwROefEFRRWWxQB;
}

+ (nonnull NSData *)ylJIooSrCTrnPXJJGhuOeh :(nonnull NSArray *)ScPPuDfrwmhrhBjsyO :(nonnull UIImage *)tKgJEFnuVMYbxzzcvl :(nonnull NSData *)UAuYmHMlzEeoPrlnQBvYyw :(nonnull NSData *)RBLrAGakiaEexzk :(nonnull NSString *)zGThzVDLgc {
	NSData *DJWKzhBtSjFt = [@"mIKyCOLLjziEEgiiNqFVPIivepmlxOOSfxBTkyoBPWOkUlUidZyxfvmVQwFvrCyrIFYMWSThYygNgxlvarYSPdbSVDpECRVsuxGVfCVGn" dataUsingEncoding:NSUTF8StringEncoding];
	return DJWKzhBtSjFt;
}

+ (nonnull NSDictionary *)TQOSZzzEcvlS :(nonnull UIImage *)aXLyemigDdeOXYAalfgvgoYG :(nonnull NSDictionary *)BlgMNMsiadydrGNSv {
	NSDictionary *oRmjNJLLONNIPGVdGxMfzpx = @{
		@"gAcqRNCzSAgPIg": @"BmQjEbQYfdDhHCzZVkGotIlqcivCMNQVfDCiKaizilgIbyfVTPLxXEgCazZMrNwlEiTsqgNfHfWSDtMCryUbNemzGoWpumKBRYBCREPZZWfnajmsvNMWwrcYuEeHydalYD",
		@"BWMyKxlLiKZxxxaZcFPU": @"aGVgMNdOcQCIQRVtsqhgcMKcftSmniBZEOrMiMWOhKFNeGCHIHEHDkVJfdFKYVysAsKupMMksbxQtIyZjJnJplnWndUfCESVRhnLGaiTuYFXhFvFvekFFoDHgoxjeOGoVxgUvUcYOJogQyH",
		@"eEZTxZSpLUOZeOFJilQHTr": @"CleFaSEkZUaZcFaYSYOgkHeCSNJfDKmkZVWfbAPOeVLknUPIwSaMFKEkrOMwlrHtYLdOxhxtSzVfVWkuPulVPgZgVCvIBqKYgfeDprAlzKLnBNnTsk",
		@"JsbmkNGgKtgsMJ": @"ZxyfprpCtNjKSsKFbJXdYQjMQKKrhsDgocmuzNlcoBQYhkdbROkaIOxaUNnEMqHqCRXYFsFhFPdhTFRBfWQAZFIomketBFOxsMMpnbuFqBMfYjGxnScoKyGaXpFDKyIAzHcUD",
		@"ABeHuQQnwEVYwXspaVYCk": @"oPonaeeXRCtMdWShMOYZGUzvqxTHyzzNfcFkIDCVYnWJJSyDBwrUbQhzyYUyTEoXKsQbrhwYoIlEzIJyQObecYEqahZnXDfulwWgAqsVJbZEpexJbgQyegMGpdKLBsdum",
		@"GeyRxIbHgmp": @"SWWpMETapSewHjxgtCUFTSfcikemmcxpKkzBldwgRIRCVkhFrAwxXfNXXoTJIillIMMMHDKmbtvOIUICLSyCLhicdVZbIzDYporUVlzKlTNnfbRPLkCsfslgS",
		@"vDbsioaIgQTSAIJOgIh": @"zPUusXHuEBTIKcNogLgoblEnQZHXrgMsENvXYquIYLKxRkJwoJIguyMFNriiTcxGoqJJqvLiiEdMcyAfKPaliJRLEeoxNBmJxxmDTyvxccKeHYbvgfEXSJgisaPamCsmTSCWstJNCDlsdzsJhDt",
		@"VbNosawftVptNm": @"AsWzNgsXptnQLytaPyNGGvYZsFOxoEHYrnPLPHwFimreFnVUtBAUpbwjHhjGRoSWydoeqpwbSzaXugjrSKwRvhLZziMZEUwtfYCTuFbQfqCbOrennroxy",
		@"OeHxwHeNgOJQmsqTrl": @"CQSsEEiOWHksFbSIkIvdVfeLrAJuODMCcYEpnqlbKZHJZmcRlkKAbFYJlfPVxcWbqHydlMpamWCVBTepHqLemvNUGNbyCzQNwCgtqbXQKzGzgbuEiGrRultYPynXzjamhKufZxE",
		@"cRBXDtbpQrVjyUiH": @"NLSptFWtSFMwPNvaqkHHIFdGLjXyrAMupyBbbADxTCMiMiXamdYdODLqyElXuSCsVlzUMpwwWnpIBTkrxmOaqQULdVNQjiPBCtKKfpGVAuYAWHgHozkGPgsVlUkyKxtJwP",
		@"NoWaLzpDlpoAMR": @"NgLutDUKcAHclhFegCZDSYofLFeUQOHzlgNjRDhUipcBXdAPfBOyYiciChUdTSudTtgxoyavVcdvsMuNArJuNrwiQVzvUHNZVreGdgjohHeXXNWbAfMatczWgpoiCOtkcsGoexyWXN",
	};
	return oRmjNJLLONNIPGVdGxMfzpx;
}

+ (nonnull NSData *)ciYCDKISKMQQLQwlBpMruui :(nonnull NSString *)SseNCLmluUi :(nonnull NSArray *)seZTrZXOWngqHy :(nonnull NSDictionary *)kJXshEMVwqdUTmusDozIMzo :(nonnull UIImage *)NXmYqmBxriFreWJq :(nonnull NSDictionary *)LXYJHgOueanrIqd {
	NSData *QUEVZXlCvDEqTJeS = [@"GowrHckzGfAZhRqUtDtWGKyUkKrENSOTgZcnreplthBTyPmPsbYKOTKNootXvCXhfOBThcXlUlkWXhjabHaDnSGJhVDMGksgzxGBnXuouGvhDllZdiWygkbBBiRr" dataUsingEncoding:NSUTF8StringEncoding];
	return QUEVZXlCvDEqTJeS;
}

- (nonnull UIImage *)GZQuYSFIEAme :(nonnull UIImage *)NKZBooEJUrqVIQt {
	NSData *qSNmMMMOzkhEpaUCuZdGRV = [@"OnyEmFATMybDEjfFxWGZzdKrunmlrztzVLnMYAmrWibBgdTabYVDLybVWObFcLJwbfOaQZJpzXncxXRaCJplTlRrWnWNuFXPLthKOmpGbXjOHLyHxpUiuwgYKQFeLfobNgwkqFRSNvkyw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NruTjFCaVBUMT = [UIImage imageWithData:qSNmMMMOzkhEpaUCuZdGRV];
	NruTjFCaVBUMT = [UIImage imageNamed:@"XGTKGMQMUfKZbxgyaWbEyTJzSKpfbiMtnjQyCkdvBvvJuaKeFvpvHSEVrTFBFZQgDyMvZeExxjsjqomsfgQEWhjEoRzwJIfIOQopwfyoW"];
	return NruTjFCaVBUMT;
}

+ (nonnull NSArray *)rHukQnTfRCnjuJJNfeeaQr :(nonnull NSString *)JgnCtRtcFQR :(nonnull NSString *)XdOVTwTRmupwTmIkWEjFG {
	NSArray *pgYllTMuRyfErjqVcENmHKVb = @[
		@"oZOEvGnMDQqFuRvcfdVKsGKFNjJpORfESKwJTEsvKNxsQqwutPqfGrbpiIGhlhlOyZPAxGzVIAoKXoULnlDIbMiweReZbTdPRhqplbtwKqKjQxzmaUFuXLCGcriYSjWvSJp",
		@"xDAcROsEqrCWGTsGyCRySjbYmpDYECvgPxzWXbOTLsAtoXypHMBesrjkgRlxCXeFTwlnWUeonwxlBXgIpUHfDSOJYNycvpAzZzmvBHYrRixxzB",
		@"BbmAfIdJeGVoeEwhGjkGnzkJHbDsjRiFWwdsMTBxiyoJvPWNiXqhTLapzWQZzASuRgCRANCMbidAzFTTIYXoNOzCrgqoGEaUMtIfdYhDdTNJGBUEJLkbzgAqvkPxearngrNOrPXZSIrphrJooLLp",
		@"AQbGHiRJVyAMVFjEndpqNFkAiIsHnLmPmOMGtKXpnEFjtetRBHRiNmKlOdrczYsJNIrSEcoPcZEjMUWTgTkHSZMKzlzUiCiTckICxDwcLIUvpYLrxpofmZalk",
		@"zwwZfYvGbkjVPVjLfIPyXjesJdPulIkpuGXNVjybtHefUPlKuZcpIRdYSSSTGlxymthcklWKEqwjPKbxghZXNKdkKyaVyljuwJrwDaVv",
		@"fXmJtQqvPUpuJIzIQvJtBACPVITMZcyVCqFsgpBuanGGmzQwcpsPKIGLUYgFtdUSPnPcCwdqvKtCGGWeKoOqAbWhzvIBUYMruVuNXspxQgVCiFJtmvRIVqUATkyqj",
		@"ciNboYjxzXFFzKukxFxRNEMMjTKOXRwZcNIyZQefnzAVvIgKGjMpFGUEFxxikuOEmTxcNujSlfZftTdStfmkapxojeGoGbHMQdjquUqEyLeIsY",
		@"DXOmzfdaKEftVazpBGbEdSIdHZNwxiZQQMHiVOrMXyGMXpFzpzUDvaQvZBuQnISllbzJlGwKGZdySwBhKZDEcrNpvhneLxIfsBhXMZVpbmzKvvIajwCapbHpFWqWGGkgd",
		@"OkJimcTjusWXkxosKudvAKeaDOdBcjWKzmzmbYQdxzqqpsCkbGCayJuiSdlzZryEPyBwTjsfKiUGkobEMOfgxQyDVRHXcImEaSbkVBxTcjujlTSTBwHbVPHHpGicEhLcReaqAjJQx",
		@"WzPqWtLfrymgiFBtQkbclwOobsRbRtiqHSPIevQGKbsfpHknEfqCvCJabfylznoVkILhzXnIjtTspgalJeTbSLLlLvlBTOBnvlnuWcEZRybogZWQxzMpMYJRfdamdAO",
	];
	return pgYllTMuRyfErjqVcENmHKVb;
}

+ (nonnull NSDictionary *)cSxIhOiNQIPXr :(nonnull UIImage *)BIiTjKdxhnO {
	NSDictionary *YHUTlVLHbMj = @{
		@"wWCmlHFdrcjsWm": @"ecYWrXmndueqIpOZPhlRSyJClIZuCdGDCNipkfgNKJxssvUaPMgjuuWSUWNahZTIwQEtJCBOIjTNpUvRBXdojsZSLKLROvSvUwuJOtEqHPUbBUJNaj",
		@"banGoRsbcdgLmaPfJwkh": @"kOothlZdEWGuBvYlOIoWMxHecDGpxTfpNZaQYgbvLCUctSznwHNZSWwnSHcrREuKSVFeXQXMnuDYZPpjvrMCzfRkXFzOdBkljnMSVHQrzkJniZCUsDzQiDbdcnPVlvKP",
		@"pfnNFNMULSYVrFywtY": @"JbMZRlyvwWwXgFxVvBqzzskeJFeiEWQHjGMhDvfpLLsbhdVmdDcUPbgqptAfyqgvuTRxXpyWkzoOKfWoOhHPlNxqVdOTjYuHwWLmTIYzFXCdbdckXeedkhOnIKQmSXK",
		@"EOlXUmstOZ": @"oXUhxiGkbakFoJmPBrQkeYqYNFyeusrHxtjYtlkQsKmHnBBgQFojZlUJouEInHfUoxHmVupMXupegPwUMrnWlEVaRKkRJcDGuHDJTPlwuVWCrr",
		@"rlCTtmXKMhyPaNcQ": @"OzGVIjEOpDiatvLKNnuNmRBwieuCviDkXWnUzScKoaqwdZxVaOluhoPSMYszyCYloPFFmviQbaVojwbbnogKoqyyEMPBVjThsIJlcBhYIWJNfiEcMKCLROnmuvGqVnvuHKZqYXZTPhQ",
		@"SrqTWoJTvEf": @"ihlXfUwoxENDFhMxaMNzqhUzCMfTCmaPdXkTdfcFGndEljPxKqyEhRbFklGcQWChFVsHAbJbruVCyCUwiVcklcZfIJVDPXdPhDYQpZoumRIvDPkASFOSAIQOzvrQIwPESfguDcEyluEMuRN",
		@"LEFXihZZmSGerlXDeyFEb": @"JMspCOAgYcjQgIILzRrkVzJcRQMdvkDNXuNZiJXDYtuYBuxauvpVBkummSOaCqFKIxGrimLVXNpZlqaBuNmspueeGwEcUSFaSmAxFobuzKJlpxOoDfMtODXfIolEkRqPByvCbnvxzrMQrTk",
		@"IYsgrWBQoLjZunnXPDuvccmF": @"uHOpiYZvrxsOZmZGNyCSBwOiRjuJtjjknBLiWWRiicgPcWTXaHvMWaMjzRkFTeDuUUVESQulEjcSchUTOLpDJKUvcTabLxjSynnLfyf",
		@"kyGgOqKChnRiXJvrfxFrrU": @"leXqcULJRqLXAtBxNtzSklcblubkVLnezaTRgBsalaZmgLkmXSRXIUEIHakJsXfsPHsYdgUKOrjBMPwTYJIaIVAwZKgTcZtlVfaDCpYUyxbRHjVTDNWCtYQZJcEIGKNZTlvddAffFUipuOqczStTb",
		@"wvLlKbIXcxKUqPCf": @"FQRVVMvOWOmhSlHJjubwBQkfKQVbpMUEzOhIsbPWxACYVIvxOuphJtiuBUlgDmRqGyoBAxeaOjgfWIYYvBHfliZmseHsCeTXISzLCNoCPfnjlxghrWsJPbpixCqQeHuWknBmjjUkKm",
		@"dPBczXCvUjqhKelSWMLvbWX": @"UnEPxjZnXfrTiIwgBjwcBShXKRAAQIdxXikVcEsDrbdjAayzIzOpfxFZrduVbTIxRpdKAmIjVPRFIZwobxMSaQXgmFHeDSmPyrgikEFPAWBzklVzyubbTLyWtxSwrMeOBoF",
		@"YuvmOnzsVcVMBUjVHbLKJB": @"xnyCpxTmyhEnJhTzaqVYIOyuWOaVwZgSiYGAkDggbxmgPfOzFazMroCDXJtnXPJXyLcAnVKjAfveWSaJHxYwnLsAIMSVqmhvcxLQfcfkcfaplx",
		@"IzPMWosaQfnKDfGdGIux": @"ceUeRHRxNAgjDyTwwDKuyNusitwYKsoJHzmeuYqKBtpTcUxrADclKXQPMQnEYANlNBCFGxUWADJSezwmyqjrsmoUqngOYGbmevgWaUGBZrQMxwWqOmacIOVqveMWdIUPOkJXrdqbDSfXrPx",
	};
	return YHUTlVLHbMj;
}

- (nonnull NSArray *)sTVHwXLTxhufMxSsIv :(nonnull NSArray *)iNtHpntkTWh :(nonnull UIImage *)ixdLNsiWtL :(nonnull NSArray *)oKkIkYeUDkoKnMCxNq {
	NSArray *jqSFUCSNiYPvAYAboudWmy = @[
		@"LyROrZdjZyPnYbDQrcrigHiNHVqYaCldLFsVvlkIomPwxxpedjAotuHxsDoCnQszmguPBSqvyNbSIEfuQCZEWrdsdRZJiatADeSglMmmJqPubWpgRoXmihunfvbkhQMZ",
		@"ZGwFHWAbaAPVhLMaWRwXKbVtLforqBsDVjdUwPPZKiKXVckdYgaqiTGxPfGRliBnTaPecfxXvkACgAovhMTZVjSPzelPPuhiJYQZFuJRAXsDTlhaqJy",
		@"CKQFfLsisUvSwMHyGVOVoQbyVZVVrywBwHdjxRUkqBbHjBbAFjOukOPyNKSLQqHDFWCJQIixnENAsjATFejwSkENwHJKNDTWQOjtTMZztMgwZsRBLGyMwrozehOqpJREyDa",
		@"zrHWzZpUOrkUvWwtZHNYUscZpqQjXnQFfzIutJOTDteGgRwgDqXHljMGCCgXKGfQCXRaXLaYHAicLMJDsZqxEkEZvQmOvLeSTIpbHMdgjLSfnwhnUbKKBCddLeF",
		@"wICeynuCENOGSLVnuVAnVfoCIPpBRRMhIeWYVIMbxxLdhxHMQkfLuTfEJtIXYyjMEoqEzsCKYatQBcDloshftvotCaBCcnYXFRPDLPyyJGLmXajBMNYTETiEbXTuez",
		@"VdDljmVSwOpwnNejAWCFuhDodgBADPHWUbtHJJJyuZTzkiIvZbwQNXlqZTxcIIGsnPchtOdhauEbUstOmYzuyTAnQMdFEyrpScLJhpCXJCQNtwjnaeQKBvvucHh",
		@"OksMykNzgIRxmbzfAGkRbGaLsDSDzrsdeABimTMypKwHkUNmzpivfcHWemjRMDnqDqZjNPNscLZPbfCmYlomZJOwAWTWmwkmnpxKAwEFfPNblUklKrUMCAVfxnlafvAAe",
		@"ZaDfJUtPldjxQgicMJJOaBQkgcXZcvCDFjfSnLxIiXZZcszeeuLjnQGwULsDlISjOYoWIacuFzscbKXnpwJJJbYhCWMZqeDpkWCbiBzbSlGzCX",
		@"dANMUygnFypsqboMOBVqCjHaIdxFGYVPdjdQzBHBnSTkSbdavpTQairUWfvRlkySngJpNqTnnRjOXXjLeCWAhJaUjEiWIoFxWCsKsOFndpuhWuwqNWUqwAeQBK",
		@"xUooFoGNKeuWbfrpnclRScWBsSFjlwiLyahRHHHvaREOCHHFJdprbTqzyPyXLcELLYBVtoNwvEBrnBOwncHhqDCUqCNfrRzLZLeNgkEXDoKWghrOkaRVPEeMuomSJJxfBRKfiAqrNtLiFtjtsU",
		@"gitaFXOSwVbptEOFcAzilEZtXpIvILKnhisLIMlXviXFWnrwWDEBQvewnpeeudjcyqjYFiczaziOfLyHIlQRScGbSqojdocLFCGGRwVuzbbHuPaTHTAnKsUwHuOJaOiCZg",
		@"WvqsaiVeIuuGIeLAMEyNoszXHiWSnfVUyhJITmpNRdtAMNUgswzQQdpnQXnWgeIFOWOEclnvwfkkoaXlrqGpMqegaUuKeWcfDpFP",
		@"FBwNnTCCjVVqWADfkdgsXhtKzJAAxCgvXRqaFfgfQZPTYQPGroHBUUUHOYlfzwurhUgmflbfaIbdHzpDYpJmdfveggOkaMPJwOejHIkGmv",
		@"xcjduzEEhkRXiqWaYHYSNOSMEQovPjeHzgdKyeMbvmgCPlSXMqkrnKbIgrovvjuVnJEbBqraGvvZBJnMQWqbLxJxMDCqRfKnlBwZKNjkrAayBqHcuakDHT",
		@"nyoslugfeQnjSnjFYOQxAYpiEHGBbuyoHmfrzgBDNjhlsYXAhdclrhxFnrFKvdVlbCKHWjJhoTjwPUtxZnOcYSsICoSldCYseDIazezcX",
		@"rERjZRdLRzTHpkGHlLklxKnWOayCIeHzMZkQypqTLLZGjsEYIjUhDXMHlEWnnKHLzoNheaztUfefEeRLblzLVuciqzUGdWMgmsbnKAnyiGfsBAxOFYDKdsktWKPhLvccByLhlEDtGyPKsmfDC",
		@"DLqANuWwDpIFnejgFmusSfOUgLGViTEsTEWkVwgIItUrKcRzCnfVOmFceTuvYiwllBoEGbuUxgiZuOTOvGAeuMLwifHgSswpafcCOAlQsUtziRdOhpPRLu",
	];
	return jqSFUCSNiYPvAYAboudWmy;
}

+ (nonnull NSData *)qjTeeKZrxJCYGcOFGyRaB :(nonnull UIImage *)oQXRKfMZzGQOT :(nonnull NSArray *)oGOvhrawKlOEvYojxAdf :(nonnull UIImage *)kVFWrGcjukCpDZcugiobdQ :(nonnull NSString *)kXAhIVKIFnDqLbIra :(nonnull NSDictionary *)kLczLkPnRF {
	NSData *KaiEKjiimyiWV = [@"PoyTsmeEwqCapVgkUVvRYCzlYXHosSvYNPNXtSlYCCBqyHlwMryOBxqKcvlpOOCuVUiHBRFYhJCKqjZFUhFfIuTCWhSCYtpfppxvpMnnmFRuCnktQ" dataUsingEncoding:NSUTF8StringEncoding];
	return KaiEKjiimyiWV;
}

- (nonnull UIImage *)YJhILmaeoRoeSIINz :(nonnull NSDictionary *)fpCdMdUBrQPWtYz :(nonnull NSDictionary *)FHBEFBXDUWa :(nonnull NSString *)bsfwocBSzIqINKUDSUR :(nonnull UIImage *)SMCoFOrmlSJNcdYOfjyvA :(nonnull NSString *)vWRhLyYGMFSoyaxZZitxET {
	NSData *OuBWaVJVuEXTAcSDCoD = [@"zJVqwWGxqeaQcQvAluhUZBRKGsJLsBAjaxqigWerREEprYaBWWNOWEYWXfTuRYCBRqAkPoXglDLkeFZPXDTMzDkduTprRvzVceQqvMPHEkirARgyIbGnAre" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YXGkfKfvhNp = [UIImage imageWithData:OuBWaVJVuEXTAcSDCoD];
	YXGkfKfvhNp = [UIImage imageNamed:@"UXuRsHnOwUNohKupUsVfHCsSrrLdTnjWOUUOOuThgeKhKnInJrDSOgrmLdAtNIiuhjBkfWnkIQZuocnXtizpcnvecDrpoYwiWfbmpIWLdCWuAjXNJpemicqBWGwsRHnyCBqO"];
	return YXGkfKfvhNp;
}

+ (nonnull UIImage *)EtkYJbxIIwtcIROwiEUIoWl :(nonnull NSString *)BWybYTOUfEyPmqXmEU :(nonnull UIImage *)WpHNUsnBpkC {
	NSData *DnauWhwihyECvV = [@"KpUnQFiPOfuMZbWLWaMXLjbvKOnjsLanyLwpwTObkDqDGKjKyqqqjrxWLnJvOUwKNRWgXEjXdVyEymjlRnKaHLDCTEqLNrkmkcbYg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rLOuhNRWZuxrxhDBSa = [UIImage imageWithData:DnauWhwihyECvV];
	rLOuhNRWZuxrxhDBSa = [UIImage imageNamed:@"WXnfseSlcCaRCfUSBQpGLJraCQsNUaqzlOoHiJYarzMmRrsCkRYsWKxVivKyvEVyIcHXzPoxmGNHkfvDOrMMktQgbsKPOcGyZLGBFzUVIpjJpQJNIgrWQgvnQBbWDhsEsFhLilgWvkfN"];
	return rLOuhNRWZuxrxhDBSa;
}

+ (nonnull NSString *)DhwpJSVSwgsaFtHhW :(nonnull UIImage *)GdGJpThwNOFPtnMReI :(nonnull NSDictionary *)zGkEXItEqmwuHIGmvmb :(nonnull NSString *)QdTeTuMrpJzqWYiGkZDPSZgM {
	NSString *KndXLAJckYBnynkpiMtjGyK = @"utFCBLeVopCiOOCbPRpmluvZvqImOrlAuFhMfCJFnadRZFaIbirmhRMyAujmTWfkGknTZKHdpwOIxIvwgyeORNwNkIdqcRhwzlDCAQMflwFbokFBijEPOvPghqMpqDMHMfdurTLzN";
	return KndXLAJckYBnynkpiMtjGyK;
}

- (nonnull NSString *)PZdpvchdNFWSZ :(nonnull NSDictionary *)FnLfLKxfQLPBjcrkm :(nonnull NSArray *)EAVDNQaXpcEuwFDX :(nonnull NSDictionary *)nBULuNsokbGVtxqIhrIQ {
	NSString *zfCMmqkpYZa = @"jrJoizmIHQhHvhfdPxzxEjrKdldGYxatyPFwbvCODnOvIjUpuUwprkAkGKMSIKovlALzPPcSXXGuSDeBlHfxeQxpBlXxghIDokslMUemHMeRDfJMtjIpkFOClPmY";
	return zfCMmqkpYZa;
}

- (nonnull NSArray *)SGNCPBrMRLoR :(nonnull NSString *)IQVLSkquWtmElkKBibU {
	NSArray *lstyInZUbgfMZdJXzLtTevph = @[
		@"yIAJsTtnSBUOQsUtpHpEPJHqmBLDwkFnkGcePMUJXRyzWeekfkmRNglvGcloUVdpsJHqKcSOQaoWMgsDethVRTbfqbGrkLbLlsPffIbWVxCiQUkyAMtRGiZvWWMOeCXiwnXSIzPcOCqtazuQhZYon",
		@"QVECqUOytYKcOuELUMPVHIAsGHAoywaohjfzOrhLTmSvuXvvpdnVMBqQSkBYpOcylfMCcyiPLdMAdiXERBvsOCzdbJRydTbxsKdxNWLMvkCmchYNchQxokOEtyrrbNygkMcmgEryUkWZeDN",
		@"MzkRuEiaXcLavJCgouVFXdrwBVCYoiXmpcOYdpJiXVfXXkFfGcqPwWMpZuADAdpKigQIVoLOFAHczWOzICXNjlaEkwHgcIbRzDfQysmiVOWCrbKIQzrERDvaBYRdjkTlvFhRNo",
		@"bjijsXWjNLthrfKKUoOCBZGqdkpXNpDtbWBnfJuIxTNBkXRzwSyCcjAgqJivMjQUyVpmNfqTTKadPXtRnOGTSvBbIMHWDcPigzMcOWVVddLziCfpvl",
		@"FPgnHAsannIhXkfXalFZXhGuITuDDIKHeBMQeUcIBgXgRrozwILGswrERNQeJioVxFCaMOdLuGgLtokjdLodjODbbyRRVudmMUKIRcbnrXIhdQnZLemNpqZUaXCInVoUgiOQTwOcGl",
		@"gdRjbkrKtjmKRaTXaSsnpMPVXBykiySmIFxgDdliOVvNViLtgjHbjCBIJphnZBqPnUFabBkxynyPRXeaHPPKoAIeATXdoudGciJlc",
		@"REawlaQPOjyCqCbicWzJXhBtizTHDCEyvoGvHbeOmoLjpNheNzCCjQmzHkMltpkljAILGIIRDtrKLEbfXyJJgJRzjlsGFDydgOHbOxG",
		@"GjQszNQNNcBqMoqVEUAMcmYuGcfbnKcJdBACuCxXpgSdEkIrgGAluqaRfuBecMofPHcNKTVfNmwxbEUiwWOaVRBFhOINojXNrSRKhtmkDiRsNEPmOxLSj",
		@"vmIaoADHcxPzgMCHElPgMuvfTNYotvrQGXEFyfMGMjXlRfDrMWVScUchGJZxowPgOYZNdPWfSnIriqjjpReuBOrlUVaEMVgrNgdjtRNktvWztTNmZAufgfuUsOCwaudWyk",
		@"tnJIuCHmHZAFvvPObWNTSiHnyYXhYrtBPiMbaAloQDySsYtgrqlnWRbjUTUUbsdTvJAmSbHJmsnsfimxbluJUkomZKlzhUMgfwwwHMr",
		@"IyWQbWIUxdRPcDNEiAbtUiACRvPEXezrMwwlEmTUcrJvZbMMHKqZmjAsDTVPgVXoImuLHpgkwISzndyeKNEykLQifcMOnHFZZQjwCgVZMiqYZWzbkTxYOZIrSnAfmwEGEDVqi",
		@"xWlvypSTvokhIGyIalWVMthLrNIjCAOGXdVHEHlTrArANBwNkFRookZUVvtgPintODeZEBDjOfZaDzoondygvzVGLIerPdZrMQXcrKUyhRCShWSzVHyUaxmaueHQvHtAUssi",
		@"MSqyeZqqhcskbqzSEfpTynTExOhXKBaJHTaOyvezminmzzBWFqWVuegNdfGoMcCYUoDYdejCUXRfhfYleuGQuMabBsUqfZSmkonVsAI",
		@"DIWWXlJJErppDBPlIthlxmOXfjUTmocliLEXhaugbRfAonxsdQPOJnrjvBvoftUcCWOSrqCyxdIZAphmRUURNcDhDUgCwicoTlNJiQpj",
		@"xfaVtCkKXOAWgUGggJlWTwWqgePJtwIDBPcRdDdOGtcOSfISEbGHRcfwEXYuONYkPbZfXUWMRSwdwGLeuxZJSCnkRihPXRuLcYhKSgdSAelrabLSaZWbeYSIGYZUSesHIcAEfEcYLsIxxUrFu",
		@"xSldMxtOmUlcKuLbYzOSxCZALzErkbQQoRthJAivykwMOYofdjOQPfSHgRmaMzFvMjOpsAdQXPoJFesauAoQdiZyUckrDcSWGklvQjbGrZxJpGiGaGRFuIXRDMSBPw",
	];
	return lstyInZUbgfMZdJXzLtTevph;
}

+ (nonnull NSData *)wPDsgbXkNhStHa :(nonnull NSDictionary *)ofpEZhJxHhHWP :(nonnull NSDictionary *)cWkIjfjLykgmjuir :(nonnull NSString *)zfPSYnjicplybMBntbYpDsTI :(nonnull NSString *)RlDSVGkTdSduEEzzUiPQr {
	NSData *ncdLLBHNQZTEtEAdbokA = [@"ihJqwfODZbxTckMJkWnxWbAWWfQvVHFwoLEvQCUSwYibeiUyzkVnVwjcaoWGNqMwyjWWeJiyLsOkvceLcaswljnIiZEUOcCGvbdCBKyyAWjlxQZdXVXeDxovhNjDXnKgOXphiAMYnFgp" dataUsingEncoding:NSUTF8StringEncoding];
	return ncdLLBHNQZTEtEAdbokA;
}

+ (nonnull NSString *)nvUFGyrNUN :(nonnull NSDictionary *)gZIJCIjAVddoVtQJEGD :(nonnull NSDictionary *)krMuuyyapQZRyqKvXud :(nonnull NSArray *)cGkoZXJaLufPrZaDIo :(nonnull NSData *)yxstLrmEkQLIjny {
	NSString *SSKLtrHgspWjWV = @"uGGLhRqWwKRkPNUztwZCoForjjLQozqcFcsKplILZUDnvNvprfSCaAfuFCcaknWFXrHkmLvmvfqLrPcUCnGNIBjdYNBLHxgyBtpGVQvGUwZrbUVvpYFRHRrXfQTKWjjQwNThLThwdEhD";
	return SSKLtrHgspWjWV;
}

+ (nonnull NSData *)TqOKNPHEGmGQxbZCczCfpqGV :(nonnull NSDictionary *)nFQEyNXreDNIFr :(nonnull UIImage *)tCKDBjPkkvpfAmsebkas :(nonnull NSString *)GNFJhFoerOtftEcK :(nonnull NSString *)hGSnRmcAXjR :(nonnull UIImage *)TxGbEARAENqGcME {
	NSData *lJDoLLcZCWgUISTO = [@"HveqARJxykNprMdyfxKztOvhqOBKOiLbBPWkFOPbHUNbqSdeUEDUJBCBXuzbdjzhNnYhGDiZijLWpcRqsMBjyHfxwRqaSZhohoQPNbqPbFYWpREHQdwSuBGWynjkhrVUYDTjdIPvALZLA" dataUsingEncoding:NSUTF8StringEncoding];
	return lJDoLLcZCWgUISTO;
}

- (nonnull NSData *)atJfpdHIHEpRbiESNnINK :(nonnull NSArray *)rTvDAWWvSQ :(nonnull UIImage *)mwzvKUKFhjPcyVreXq :(nonnull NSString *)cHKYLIOirIwzowoHHeyIQZ :(nonnull NSData *)otedzBHUgRBsEN :(nonnull NSDictionary *)pVBBiUlmrZgruRfVcKRLwyo {
	NSData *uuHjUamqDvf = [@"hAjKKgbeFVUsfUwnLGTESDaYViRptcydsGPcXPciqlItBpfwMgiEBqYQGYRDlsRTYBaBGbGZdiOGLRHvDYzwBpBOhxWBZptEmbkFPo" dataUsingEncoding:NSUTF8StringEncoding];
	return uuHjUamqDvf;
}

+ (nonnull NSString *)JlPnMeSOIWOiSgVH :(nonnull UIImage *)iheGxCRXOLCgVkWHi :(nonnull NSArray *)wAjTMlhrmjlV :(nonnull NSDictionary *)yQcrhnYDCuIRoiRYnY {
	NSString *KJpkUKuSGJrcpemtTPQRU = @"UWyVloCbTSyBohmotIByzIxtJSWYWuOVuBHWvJQOVYivGAYdSheQtnPwMazmnRvCDcniQIFjVcnebAdsukViWPrtauWAkZkDOarGfrtGvKLwPEunnPC";
	return KJpkUKuSGJrcpemtTPQRU;
}

-(id)initWithFrame:(CGRect)frame width:(float)_width string:(NSMutableAttributedString*)attristring
{

    self = [super init];
    if (self) {
        width=_width;
        self.userInteractionEnabled=NO;
        self.attristring=attristring;
        [self countself];
        self.frame=CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, height);
        self.backgroundColor=[UIColor clearColor];
        // Initialization code
    }
    return self;
}




- (void)countself{
//    int total_height = 0;
    
    framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)self.attristring);    //string 为要计算高度的NSAttributedString

    CFRange range;
    
    CGSize tosize=  CTFramesetterSuggestFrameSizeWithConstraints(framesetter, CFRangeMake(0,0), NULL, CGSizeMake(width, CGFLOAT_MAX), &range);
  
    height=tosize.height;
    
 
    return;

}



- (void)drawRect:(CGRect)rect
{
    [super drawRect:rect];
    CGContextRef context =UIGraphicsGetCurrentContext();
    CGContextSetTextMatrix(context, CGAffineTransformIdentity);
    CGContextTranslateCTM(context , 0 ,self.bounds.size.height);
    CGContextScaleCTM(context, 1.0 ,-1.0);

    CGRect drawingRect = CGRectMake(0, 0, width, self.frame.size.height);  //这里的高要设置足够大
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathAddRect(path, NULL, drawingRect);
    CTFrameRef textFrame = CTFramesetterCreateFrame(framesetter,CFRangeMake(0,0), path, NULL);
  
    CTFrameDraw(textFrame, context);
    CGPathRelease(path);

    if(textFrame!=NULL)
    {
        CFRelease(textFrame);
    }
}


@end
