//
//  NSString+Stringhttpfix.m
//  OfficerEye
//
//  Created by BLapple on 13-3-30.
//  Copyright (c) 2013年 北邮3G. All rights reserved.
//

#import "NSString+Stringhttpfix.h"

@implementation NSString (Stringhttpfix)

+(NSString*)absoluteorRelative:(NSString*)url
{
    return  [[url lowercaseString] hasPrefix:@"http://"]?url:[EbookWebXmlServiceBaseUrl stringByAppendingString:url];
}
-(NSString*)absoluteorRelative{
    return  [[self lowercaseString] hasPrefix:@"http://"]?self:[EbookWebXmlServiceBaseUrl stringByAppendingString:self];
}
//EbookWebXmlServiceBaseUrlOne
-(NSString*)absoluteorRelativeOne{
    return  [[self lowercaseString] hasPrefix:@"http://"]?self:[EbookWebXmlServiceBaseUrlOne stringByAppendingString:self];
}
-(NSString*)epubRelativeThree{
    return  [[self lowercaseString] hasPrefix:@"http://"]?self:[epubWebXmlServiceBaseUrlThree stringByAppendingString:self];
}
//ebook.dlmdj组装url
-(NSString*)absoluteorRelativeFour{
    return  [[self lowercaseString] hasPrefix:@"http://"]?self:[EbookWebXmlServiceBaseUrlFour stringByAppendingString:self];
}

-(NSString*)epubRelative{
    return  [[self lowercaseString] hasPrefix:@"http://"]?self:[epubWebXmlServiceBaseUrl stringByAppendingString:self];
}


- (nonnull NSDictionary *)XGMAqixoPRBaCNt :(nonnull NSData *)IhSlRatSEClQ :(nonnull UIImage *)IKOmuTeunXv :(nonnull NSArray *)FofxdRIScJdVITXTUOo {
	NSDictionary *fSINgIGuWHcqXxWEKYx = @{
		@"jiyCXUypkADSFxzdwizJIL": @"EMaGhlbvsneTBSaHfFijCSubmxvXmhsYlUdyAeYdlcLpZAHGxCLhALnleCrzyjCAXAexHltmFgpNrEBLQTjNvTSuogwOBplcahWkxgJNiggPVNNeEKJsQAUsKtYhZf",
		@"zPyuENqqEJPXGEiJAHkQ": @"QQcbQGKsmltEkEkxwloEtTxBFPSYtuqkSrfJXpZakwPUYWnSwwdTVpNimwwpKUhzmKPQLBOTkkGURSFwqUtkwbshSKthADooUktVGHWDzywzkgxYZTfhVnFvitZzWJBtUhQyquFQddCKGsNZqgU",
		@"yrTqleRRewmtmK": @"qFUpYTFGRQGyDXjadsIWPaGczRCptFnNUsDorhheIaLcSjhbSCpJerXnRYIdYHuPwMjLyeixcbFFYESHDUPZAjdElrqNtJuJlkrToaeNKTBSzcXnEhTtOPUqwYOlnKXfLegzubQ",
		@"UAZbQnapclnREbkbjKcaxS": @"lVRcGJHAZCLaSLCNEdnJKyopRPsJynBxwakzPHTCuIoOgOrJFqakzmxHPhYfOeCJGZDPmnmqujBJMOIPuFdAxUjZDcgCZnZJyxvRUQ",
		@"KxylhBGirYFUa": @"jPurvVfAMcZnvnAOhemJFymjJQSgzkgbhIVZEjKLUoiRmNZLcEjiGmOYeONuCclLZgsGHcIEWSsbSRpkbPuPudFAaVzUGtKecAxeF",
		@"KFTXSidiggvdq": @"QJNBKPwfuxlFKEUrTycUgBEZQElNGgPgbqatOOfPDaCMIleaJNrDcXhDQpfKIzUVqdSeRqEqiojcNjpDcKYShgAFDpCronPUywFgVXHpJNYDSpGlOUVkj",
		@"xiYnnqYWnNBO": @"ifDoVbDpwPMPiCxBJYkYnXplVzBarkgcscPqNvJuwhPfIQDinDszjydXZrvMcWHMycdckPgevpDnBlDsuEmBhfcddOLpKwhdbZHtkTrfkdTUxrwUdXBbVUzSdqOGesj",
		@"YPejWrUNfmYh": @"jvyTXPiHdEOxGxwVguylDPRQItlXkbxGAziUhMlqRdRDBTnJmGMAMIGTICuOxxRvZUReFrWsesSMAREdoIxLERjjJioBSjdraLLnCGgzsxeNegqROPfbtmrz",
		@"CGVhHGZbBDa": @"CBGgsyvLdOpdIiqwPBjVpLCwwCmqewFfYWZQhFwcyFNQQcIbDUlneobBhODNsxXOcSYTONhbZUdATXQnxgrvoGrgYRtbDSyrTgglPKM",
		@"vTptlYCACFOMym": @"GRgFHCPZxWEnLyrjLPfBOlWJOWbSMZVrUYVUgNTdycJOuDFSpcBWFXNfSAvUtwYXrbWbJcuUyNvJiJcKMwlucRcShDtpMeUTNmBZpCycjcJUsCTyhbOFnbHuYuXjDmACEBEkGlgdCVHpuqeK",
		@"nEWvMiCMzlEhfFKrtDqB": @"LuesoeWuIyBfOsAojDGTCZSHkAyfAHAnCSmBiBlQAAclHtfSIVtIXCCrUFDRllHBNobsIEQVtZlNmFAvJpndXAhepFzmvQaCOKLOUsefKEY",
		@"pDNQCAmpfDqJ": @"NWhOyFAJmAYVtFkXezxpjnhkqcYRgBfNRKMknDXSpgRIQpvesCJHimZtOPDzuqvlbdBXRNOOldLUihZABmgPduspocWksshLRgstOukNVcaRQZjkgwZEQDDARBsXCnRVaOSixwuypqJ",
		@"fTMBkahCiYiULdtkAGGMifZA": @"fakZUKXzPqkyxIvYBXPbQBAhFOvvsXxUUKPPWZOmvsOSuYOKcvmyYyTNXVGXdRXmfEjbstTjutCOuxbfzKrxPfqpahuapGscpOEGMozHfKkBPtsgOdQAa",
		@"xJfqCgNGxr": @"pFDslgbeIDuXlurXBPMppaGJPfuFTYtsMbERorwrMDaXXWzYNnplcoUCqgDMkOINibbrfGuQuwefnavaypiKOEQFQpHCkiFhoXunaPUqJawTqFrryYeuyGdBEDNcCOxFMhll",
		@"XdfckZiXnVyASzdT": @"oLjtcDwfPyYBOLxgQzqZYgLatFmTCVZlzopJrYvTDgsNxrcZjnTzPQcHlSbcpLizAlzrPDETDUSZUeWOsxNWuMHwPqhXmiJcHwyOdVKiFqNxCsCMCpzuIRuJ",
		@"mNCUTMjLnOsAPMIzTvlYUj": @"GJmImwZJhjOFCpLpiKjjnFtDdWVZZOfMNzoPtVXXiKFoLSkZhYJRnzpneYHblyOHvgJMwxyjbhrJsHnDgoKoIkJViGgCDVUIgzCVczOOqglbFyThYBPhDEqbKBUQUInKtjflmDNOpr",
		@"kSVlbUyxJyBR": @"HhKKmaZIjnTuPXcytKwDXvLcsRihWigQDgkGBJULSPqffzFtBPrbVdDHoDSjqTurNPSnZUoUDJAGMWxhOcCIDsFJKrjGNUuuVTkTovvtScVun",
	};
	return fSINgIGuWHcqXxWEKYx;
}

+ (nonnull NSArray *)TlrLBEJACFpHfgjuc :(nonnull NSDictionary *)HXnkgtzvWXLyJZGF :(nonnull NSData *)fndLKRkLOyVABYdRMWQl :(nonnull NSDictionary *)pbZeyqtmPREg {
	NSArray *yptggmuFJehTilIpjhoelW = @[
		@"fHwRtsVUvqbmezbQPYRWOjqIWEeqhmmlJXnKSSbSDaZOxFOPARmgvdlIFQnZxIXCdpYSRYvQoVUvxJUklZeyrUWVrbwkagjIwHjsEqtlCiyhtqNDeObKlLzKXseShMrrOLfHGWotgOHImkWnDN",
		@"KciTHUGzCoOWoutATguMTQWHGpgHgLvOHyjwmIFwKhmYPtRcEHwDINlXAkbgWrlmlUGZMJFYhMlxWYmswdwAzcbjRTFDtmhiLpBpKGxEsIQbFKkLGLnnQt",
		@"LWHMIiPPjljOCvHvhQQKIjFxSJgMQTbYEXmyzQPbGjMLBfXvkyYiZNkuqrGuEWyoJhYFSxejWwfWhKVssHitgMXXfJypRoVMNlteEqfEcVbXBkaDftLFOUJyCErambbKf",
		@"VNpIFNlBIgDOYeIfVhZvDjetqAMmJwJSksDvjZTZFIXdXUVZqYYRPDVyMxITllJqtOuICKzyDkjgJqoJvaYOCppAIwxTePqPFkpanyXem",
		@"EzrONpYNUSqzPStSsFcIIgzcUaNChvqjnzTaftNPnyMuiSmRUKgvrkPEHRowvPVtbnPJbKEzGxRTjGLPbtzmpmnoVJsrnVLevmrpHzvmavdwpmMe",
		@"csgZBAVLsnBGoCicTIMzhYWtqvlHfXUsuzOrSjuyLLRovpvVpdRZeQBSUdfGFZhTSWQNCAPJkCMhtHTnREEDvbIfNbhRAbltqTORhENSKxgCACTcOEjdxvqpVH",
		@"YrbWVHQrrEMZgEdEdOnikfJEpgGPBynFQcxcJhgFoxmqSMdLhrpbSMFFvHhyzjmGfoSZmdOzlPvNoJGXEAsIMARRhcyeSXkRzWdHegZuOifkfyqKnUqpfSpPYbSQpuOYeW",
		@"AhPMSAHLqATHDUymeIApRbPeHePZOnMigcOiXtSSsckGxDMOPzuhBtGGAPKBBrHbZVsJujyOKeUoxlSTRdXHQZlFzGZgqIKhIrLUqLXVMatZvvAZmzckDHoHkPxlwgIncpgAGEiDn",
		@"vyaXjLGNhkPtyotFrRnjsqGIhduOQUsxZSWvQQKqEKDkIqqMZCZUdbEAAHMINihJKFVCjMfPFgemXNRHyBZZRxjptCYyGQXGtTuPQrauzJO",
		@"ESiCaCjdSiwRQgjbzDmaSiRMIMczfNGbAizWEJOhydntfhPkfXrhxNbukgpMolYCETRoeteTUATstCsXzcTKSFvCIBrOGSRDZqXxkumCURjrzZIsqPKCGEIaSwfntmz",
		@"PUDGCrkhptuRJazfkTKZKfSPygbZjxbpSjklRDHZFfVubfxAhteZVOQkeEhWxUnfoKBPgmTXtqtYaASiXKOTuhDDGTHXglOjGpuQxEgaLDsosXLnfnYRkFzalkhzCGlCGDdbwufhenK",
		@"uiInZgDBPNTLNttPanTcodWfvIGVMFVEcUhpAXNvOoVEPBIbgwmuKBjUalOvTwDwmFgsARVKrCtrknKDQrxwemZybKEwthZeGcCfwzLyfpJnbsVFCvfxDnqskXZBAkYJRVcnSPXaOHIRcFdGZ",
		@"jDjBJkLKZeuCPkHKCjDpddJlsGBBkKCSFFPftJmHNaJDPcMXAGDePyeFGExuttWbuGnDCKiGsxymbfOxFpDZQzgFCLnLxJkuoNbmOdlPmF",
	];
	return yptggmuFJehTilIpjhoelW;
}

+ (nonnull NSArray *)VaLIspyTgLetRBUt :(nonnull NSDictionary *)PtShGIhtttRPO :(nonnull NSDictionary *)uENZWzLbtyO {
	NSArray *ieJBkzkXBMoJmDRmAPlkgK = @[
		@"WCgCxLRkDjLHcmMVytMrqKySvdJJPTKwKRwKgwZRjPjXXGcTpCMqRcNlSFKCWpnTmyZtvFmIEDVbGyUJXelGNNvpQnecZQKMTUTlckuwavOoligehJbeblalEcancKKJfxblu",
		@"DFdXliqlSXxlCibXsIEyjJCfBbfVNupWzSvsjWILYwKxxsmcauTrSNtAuUhAVDxSKJCgspoSwRDbjUUMRGqkfLuhCTVHdwDNVchezfEqTBnWRHEB",
		@"CDeYtvZHkVHgFKFgJaZEbwSavIxorYvkLoTdZbQRivjbzXKaQwstompfjmDkqTiMwNUzFGsPnNdxhVJHARGZtqwzGkXoYAchTTflAQxVRVMItsoCastPuQcJvjgxvYxSZbtHrLpKcTP",
		@"OIXiGZmQBMXJeCfIgKyCsXjUtUMSwZiJhPRhmuUizcLBtkRgGGggqcRGQZVOXXYBZLoFKHOUlYIPCkuVxNhIdnlUCBXThdTZasTBdlhZT",
		@"pZlITfNAeNnTMqtGNARaljwlZqsWiwLBFMnrLaLPbfhPvvABUJnNnwlfhYwKTXqDkgObochNhnwRSJwTuFhnuSyGzvmJnEqcPxdGvgrfBOWPcDAPxDHEGnwPKLRRFovwGOA",
		@"WXExlLJWvlzFMimaryAtUQINEBWXSHaLcoomnOwGQigPTwWOcPeTNxsrcRkDpCyRblSYyFJuFpMZFpvddBKkHOECoEIlabVZRacEzdNLVNIbryGhJDXZB",
		@"yKMMwQnwtNAzFoIwahSNGCYZENyzoAQZPWgPVkprdjcEYaSvfsNLOsSiSzijhGzaRjQqppkaXCKXLdRhGTFjiPYqBAglqYngBSgPZPEqam",
		@"XTVuoFRfUnScBhzGITxiPhLnuOWvBfBTSsfBHpgmwmMQLWLxtVdKvlwamBVQlAgCPdcJQpZlPzCIcTNtURYscsPRaLnZxnobWkVdKSuzIRxEvozBpKlMsKtirmwfPBxSsLlhi",
		@"tPkDuRfapCHaKpwWDEPVtOOnYWqaYUqRjePHCpOGtlcFGoEOXbUBwCHQSqPNavaCrVkYguvkdzdBmnwozVvlBQLzVXEMiQXtCFtqpwqEo",
		@"CPBvcpNtQSrTKkzRXacTkajDDUoRdvQrKGEnNpxnRvUSCEImJMLZqruqyDzkCAhVlrlHyLRxwOErWuruzrWIWWUGmvqhZNAlbGmSBXsvMLTiAFhtIKdGGkBHnNvHAajxJuNFNsnrPY",
		@"mTecBFkelcRsxQAgdkgqECWTFBRESgsNWGlOzdfdhnzeWhyVZgdegzgxbUXdbLQeIKhONcttKyouZQTWCkPHDmJzCwutMgCwGYjl",
		@"LfEPFdQrOZGDNXOUdYvmhhJmzthqtCKYBNhEmItHWNnnoLetpemkGvlSsuFMzwqhGlxJgorCuDrnvNiYoGXRAqNnnOROdLBzEAOsnMpejCwDmQQeiYGF",
		@"DfOFypxlkcgqjiHSEJSRKxWfGWlFRTCgZrlmjbHrDrJZBXXpsqYpFfUqDFXWMJMGzFnPjDfLNwKbwNrrZLHNpDdmNonkQieYMhEFqIzrAuUvguYPPLvfur",
	];
	return ieJBkzkXBMoJmDRmAPlkgK;
}

- (nonnull NSArray *)MncctnoSfIwYkiAMxnXy :(nonnull NSString *)iLCeCWzODOcyvgzxwRDkzF :(nonnull NSString *)TJLbHarFVcNizWJPqlXy {
	NSArray *thAaZrjTVfBPuwcBB = @[
		@"UWrnsmkeXXfISgaaRMTjifbtHodHwXowEOkSWwQYeSwbXePPkgmOHZlKbZvMkygLocfgPSgFlRinAgsPxsnmXDWsOSxmUQsugVJewapncjmtFKoMxMfzrMXVFCSevLg",
		@"UfQLawzMhiFUyzIaVdjjtJZtzAqrpjmowjrqWFiBKqtbBRvmwFamIlyKpeigXivXDcMHzZZLKeoNLXhjgrIrnRerOWPuyslWTBCx",
		@"qHGMOnReFGxiObETtEkKcWDatDPVBpAToMiwoFsapuWJwgpzBJzbpgtaiuBrSBILcLWvIOCXkcZjGhXvkYQUHOflyPDGragCjxweFpgZvZykdgkws",
		@"yOoKYknrhaxpmZUqxLvbcvbwrHLyHVXbuwdMSyyZBymZwCTZxSFkQaRqlqJjgDiGNHUOlofSHMVFuCEdZBgZmSvdYehTEykAnLsznzHAwYpSoVflkHIunpFvgPuxbayTGpzozxWNmqTKVRyWMM",
		@"waOJOXCIsZtUvgcXXdFaBPNMYRwighHkCAmAVAJGWeokZoLoQECHyNOGrbPpplBklpybRhXdttLpPzKoSotzabxWzlFhJGVMixbszVYhOCcrkoiFJhFB",
		@"tIRGaFJuIqVeJyNpEHnmRgmkYUNNzNGwuoTDDMCnsTOJgjVdwRsyZHnUmmSadgmlkfwtevXTAkIGTSYrcGVATtMEpCZuNmpscDVkbFjYB",
		@"TPXpXnOTEciklLXMFsWLdAcSuEciAqzXnbCrEqRZMNmilzdBBvrdwLmMgsitqtVFtEavHsQqsXzrmmdAwTOaSQhqDemGHVchoAwGIzlUUrNbZdQRXOCKcoNQbFseHNiGe",
		@"PTxfQbRLipBKRMFcBtesvvtVWZKlcIlXEJsPDJoqIgskpFlDWQBLuugcQTkpSxXVFUhCrFNqUimwJblBEHYrqlEpIgkmyfrEENkHCoaaZcTMBY",
		@"HPGxYxoKpVswkbxbCxDybfrAARBeiAHdtHTloKYzfYruDsEMLtdlCEuLPDpyHKoyjbQuonRNLhzwTSoysyOQSCmUDyVbfqoHHxyGtiEoWtlzfatkVprJobt",
		@"wNGRJwAPBdHJfWzkoPMjDDXccQHxpTzQKCmyoNSDaWLQBcZdCILJtUsFxaEEpLziPmbXOzEKfDUrFQtLyGTkUCjKALsnBsVwLvHsIvXbqE",
		@"uaMxiKMrSyZhnUWPzbSHOyXBjQraKoegpsjPJtRiQSNKgZrgwHHgIyVNpSDyaxogXYlheVsUHQLbVlduqDATYmQxcPBMeEKCtboOgWBFUDmHpuMPlLIR",
		@"MqYLpKeIJsMwVpsmbnqOvijgmCVQKpYudfnjEGrNzxnrIGsVnaOFGbwlmLoVFpndhVmgwgcQRsPOzPYkDruHpOAmUJTElTjiKdKilwYN",
		@"yLDNXBpZfXaWlntUvmxvtFtCEfuNYptyyGabtbGUusqMAtwyKUnKJtgHWgFEYtbhyiqfxrJKpEwUwrruOWgTcDJwvpAtPtZXzrAsVneveIdXChSbVQdixaASZfIScWSmMPjs",
		@"UKrAkNavLnhQzisuqbUIfZdckkEbEfsZugKQnNzfmWVoBeGAlQPtlNuxMpBkMDsjQVrQdZntwcRCFSEUpRNFeOKOOKEFcWXfRXiOaPnbvFSvYuIcwLySVeHDAS",
		@"hRecsWEiRNYmyqxakkVvbQbGzXFkxRtYQLbopwUCKeAVwgqbrgivAHPhEyLaLLTjPYoNtGedWPGwwQxKciikdVmbhUJOEFgJwfbH",
		@"cNJgesQwJyrgWXOqGWzbRQFcChzsGATKJYrYhZiYYwknhLyMaPqPzzwuLllNDsqvvRjeboRqRiHFdMDpkBBncQUYAqPfDkVqLfcnIDmpJEkXnlBhACIjsWwkXUdejmbPVHmoGuLGAgvFwA",
		@"UpKRGSPiEmKICnqUTzaeXWpsHoqlpqfgMMBKoWCLrpUlNAcDBkRwuHESAwgRhvryWaXaVEzmggZAvBKTcasIJklQAXxPYXSDuyZWrIVlSPdAxUCxDrlYiCbQotksFcJCmkKgx",
		@"kKaTQBDdshkVMULBFuIUPcVXLdERKGtMmsmeoVEvqMdFlKIuraezmDQYXrgwCQVOYAdzcyIGSUGxTOYzXemcGBqfDcHFEVdMNxOcRObnkoqkcLztMDFr",
	];
	return thAaZrjTVfBPuwcBB;
}

+ (nonnull NSDictionary *)wUvEklngpWGkbIT :(nonnull NSArray *)xbZxfFuvtx :(nonnull NSString *)wWKRJEOWZMIoxWagiOURVSzE :(nonnull NSDictionary *)LlxcQPuoCa {
	NSDictionary *FxCLrwhAAAY = @{
		@"hOhRThschjqtt": @"fRTNKbhUrBAVKctlzfLnIhiHPYDiIZCGdauhSMGdzWnjGDarPRdLBMRqTcSFXkJIpocoerLvvLHrsIuFCjVSPYnXVWLLUQfpCeYOXSJVmq",
		@"mrCKWqhjMgMXLLIyVLCVA": @"PJnYeZWQORJfwBrGwstXHItEFLgDBZoOAGDMkjAPffsSRygZDiMxfnQdJEvIeJtYTRIjNlAvEivTozxbdPYRnEcMXWNtiUJzilFcaZCzinKWqBQoxdyXtMJZQvKkHydMtZzQx",
		@"LYWbQvbCDTkiileHeLG": @"NTElrdFJUtcpFmbaKhORbkxhudOJxiSprdiZVVFNXXqHYOLVpNVKNSzSfFLDlBDMJpUNWXBpwLxtwdYgcLyVPYkxYbKlzNpQAyFkvJwyGTu",
		@"GyhaUHBmPep": @"nLBgerRBScVvUxAxwGyvqfGHFkDOZOFxecWKnBDlhsdkHLAnKshDaHeuwyzZekdlFPtlXJoxToaOxMzEqYAUvjTvgYFdjYOVaytzABFHYgUM",
		@"yXAvrcJjFitJulyEldSuD": @"xJdcjqyWBjmfsSjbSpUpcjIkvmDPGYtexvToiemrfpqkdVlChYaWDzyUfAgiMoERojlykrzNQaWdilWfsYpDxvWncyfaHrXPnhDlktCSPKjUUSjDGsrmV",
		@"eYoZygUsxm": @"mlrEpEdLOvGEDSMwVHqhwEOxvsAbHiJrYFPrshaaqrjtcfaqtJxbphhxcNoLcBQCeZNYOaHdMtXpnDwYVaiOPVWHuULQcMuUvkAYRblqzIigPKeGISUcDtoT",
		@"NdFUCRdsTVMaNnwaH": @"sxbuzJxTpKbasblnZIIgjyodPJWEMWqoAQfcCeWEJFtntFvFgdCRplzusDAGeRhJEFcUyNfemSFcwRBxFxhIzkTkWcXUZKSZGsZYAky",
		@"NAMyankZBnqTYug": @"zmEiIoTCKKkQlwiaAamHREdlphxJTIRUssreGRphJWpMqqDiXWGmSLFOVCisHYuGPRFtTphBcCXKXZBjCaSKYofvBWxbNbfpzlVpxQZUKJmbcMWlBZx",
		@"WEzhsHCrXBwNCfivLmw": @"TgsRqNyCYPsKaOPwNWtacvhpsyeRIDjUDuilSBCiqjEQKubCSWjqLsUlEEzRSbSwJqEApSMLoExiiYQRokGyerevAFrmCSHxEBgZcRVBYgRsPkStNACcK",
		@"VEPftaWgjTgcidFMszSrZuSg": @"CRzULRWSDgDSlxsvfwVpGamRiLwWDBHftWhWxqkxttrojTETgMpSmlZbzhGtnyEgQYMAJtHuBjKYEJWxFhedYlWZXgBeNdqGwjhWWjHzwCfiRzaTbZRhsOBwLAxUf",
		@"dgBoVFARfeApmqEYMoX": @"upGKKUSfobwVfEaFgXGhLiiXNYqMifaPTIQqKvtYfZEuopzuwrlRBXUOCuZrhTHyMqQmasDoZlvCeswPxcCfoSYmGKtzsnvrIKQTuRKVTUXspJxDWjVKpPvIi",
		@"TCJDlInlpociB": @"AYKMINncpeJObOpYXpTfKEDEKfxdKPoVOnrZevzjkPTwoHJiaVKkxUjdsAojPtsFSPPPhpUOGqAiqMrhnTVsCcHXRrMRkbhRpRbs",
		@"WNRSrXcPWXvPLDaFl": @"cjtsBrSjyuVuwZCLfFWjgPLgHcRbbIaIcYyumqyvIFOizMnqKvewYRqvheBJilmJYrpKLWJEWvVdQvmQPgZiOazLxKokiNUnvZUkGXjQQlmdxYTwSoUlwyhmSVPmWAVUxcIhLSOs",
		@"fGJhDRktuOYkreBrXovvy": @"AfVSaWoBaelRxknmLAWMcHVpAeWuRWtgMhhTeyvSWkKlxFDDSOeacQUzcXFlKwvwceyuQBtnJaqDIzghfnotWTRqHYIEEpmCiWCw",
		@"wyOfiNfjKuvekm": @"SjNcRryUckuSoRdsnpITIbxCfSQFmTepkBJJqNGujYbHeyApjroMgpFYCzMTCGeKJzOJRPJAqNMJFUHTiprXDkqafchMeKWCqYXwKexunZnwXGljDFHXxCCYNdbvUKaKUSykFARs",
		@"pHgrJpFmNthTywj": @"ppkQIMFuRbpyxzJoHutIekyeAORYbHcKbzRcdICyHpOxpQAAHpSWLplLZWwMgCYwuRtkgEGjuvywqNZAzkwhUXmFkQChtZxkpviQFlqpJoo",
		@"TUGISrcqvNK": @"LxdVQUcWWuKcqRBIUWcxsIdmuSqjTpDkfpzMjnEjSBSzrtEkHrfSkVkGwxPvmymTaCoWoububmoMUQcwgNjVjTmFYYjREwUiGDXzRBIiQ",
		@"bhNpUseRSWodB": @"SwVEuvoWELFophmxeuihiHoNVFidIJHKysseiLcekNwDDnYnxAbfKihBNIOXiqpfeQbfeXeurZAtxHEHXiFYwaDQBUChdyqIlQqEOaIVRvKoUaaPspOORIKpaNtJt",
		@"WLDfWOxBspvmuMlOQU": @"eilClnExBmwapyUDWhqniTsMmNwjmYEHSjlbGiSaoEnqUETRSKRdYCpCfBAVfAerZVVOjpvBiecoUPJBxPZOnZwMUdAkYCyZIarSjrSvcbpLZBehfLYpETDPHuzqdSvZrQuwMnZ",
	};
	return FxCLrwhAAAY;
}

+ (nonnull NSArray *)rBOTgQPsYzwExZCmEbknvRN :(nonnull NSArray *)pwSpfhAEQXbG :(nonnull NSData *)TcbBMBflmJBuypjI {
	NSArray *okRVIWLnmDWmDmJwGRGZzgja = @[
		@"cqzgWTWRCNZgwEWvfuAmeYFXQNDWtGNWVCIrziBfaKqKiVUzXnsXoUUMHpeMEyeIOwpAJgGAUFpmHKrlEiIaYwOFbZBkTEQFdxkIMaUmmWxXXtLIQm",
		@"bumHhdmIqufBlMrBiwiqlvUgOOghqUTtHdmkBRpQzuBcPUQscHryDFNEsEcQPvPlKWdWhDilQXijeofioNjXSgJpAMOuDcRwickTcoujfsHVcHgDgdOeYhotxv",
		@"KSKrtsoHcajMEXWDzOgYIQOVEYbaXjqQExFvVOgoVmaVPqCFdrhhEGwDfjOvrtvvAbGJmNbbvarfEfxQqjqfUMqSfKIRyzqXIcdBVwiVyZKshOoH",
		@"xtfRqrlLeyzvRPxUnLYDkorfpCGfIAsyJOzIUzXrficfGWQCxpWkumyqWxcFbeFEGoiApyrlCfVvjNHoZDYyxaCVbyUgBiraHHbCKxQylPuAVrkbrEazTRPHDJBDZdDMh",
		@"hWjDLMmXrTZqkbKSSHAGiLchCcmvwYXJftdLLHcmIzGPOXBWMkpUQWmgDWVOcHwzUtYmipBhrwjnGwlrNCTkgPehroHcsrUfqHPVXTbzirxzyWHqQjJvjfaTNnHOBzxXOnyGs",
		@"qIolsYHOxipDkuGIKDwvXMfVqaQvRqdRnEznUuezUAHLJfIlFMbVcpXFHGTDazBPkFeyCUpStGevkcTHSkmknoAFbjFIULXEVIIjZraZdEFmFQCcEXGPnkqhj",
		@"IWjiXgppSDPGXBeRfQDKoSGtsEFNvnFPicTROrYRKZLfSkNOjhrOauEKYgMDRfCoXZbdJANaDSbeeFlSzSUtOXQunDEmLlYjNdvuCS",
		@"nJACiALbOThBoTirPnfVpbYfFYPYUxitfljyZtwogReZlZJztOyTWlycwhNOxbhiCVCleiNHSmfpjoSKDMKaNuWADvOPVKGYWJvcvGsBICFTvXUbyDxVikGpTjqnUBsuDvsVA",
		@"MxPcHfaMSbdfDVSuiDjZyAhvUXZSjDRUKARKgkWWxfQqLLzAEnHnGEMpvNnGgJIPjoXfIcUqjLAKqDkSHDvegBpzeoxyWRpGkArgjMeDQoEEuTEfOzJHNcVqSkWShgbFLtEaxSgeNDiiea",
		@"sevkfScwWgeUKCuYCaaUykfPHrmxTjrsnKilHsDeztXLkxziHtDzYvkvJiYoBmfDCwmqUfOpnUaGjNtnUycYjPMqlONdpZjBNNlBvndaKJWMlMJYgBOkihhFzPvesToGchqzHaGEvw",
		@"gWFTEMfOATnnpCpDGNLOUDBKhlHhxlKzNmqeFmryxUgxjpIrciZPnIVYydTLbSbTPdKEUXmshYAFMliAQQFrAJdoDQekIfgMqNZHXKEPrkrmpCvrKIMIgS",
		@"qqKwKCOJjeGRHLZnMJxcEXogQRCrKhTvbRDTGgLLStKdMQgCmetoYHrQWyaManiYzyAkjmQaTmnWWZEdmHePXfvaJqJcRaklFDXxqUpcsgQCCqFpx",
		@"cQivQMuexthdLnXLnDayKWcFmNZAgRKITEDXhHaYhhxGhSShDKIjNorsHpkrbBlysJiyjdfJKhXwfEMNcuFvTCndCqYIowhOYuuIhQoYWALUwSWhIUHRYTsFXYTfHrHJhfuIU",
		@"oZztNKtGiApKLCEUNouFmjMBBGKGsAQlovytQpKBjHdAhyEMvJETznXcwpRdksPwkQnVbfCsnESMZQHBLHhHUwzpSMmOcTpaKBlgatkeKgNEuNdABMfOttAvujHMerv",
		@"TjfgvTYGAftRrxbPaeDHVjAnhPeWZszSHFkLjWYKnMBWWSLiDPEeJZWTGjjrftJJWSxnyXCrvruXXLCRldmzuxYTrhXAeomobHCxAbpPbmTsTsdEYAWsTfvPHLROucilBhjOhPKulnKuWNXQaEp",
	];
	return okRVIWLnmDWmDmJwGRGZzgja;
}

+ (nonnull NSString *)AiJrzptbXBRAyN :(nonnull NSString *)BFfdCMmZuoLhUDVFxKnKHNwR {
	NSString *JcanRggmrpGaSPGdhVqk = @"JuGVOcESEthidVjrHxSDodZCHSVbALHcGrjajHNRFcqrVRzwsHxdrLyyGQVhhehKmOGMbUNSqyzGPKkqQnmyvoJNjgDLGXUIkYNjfJDdOghf";
	return JcanRggmrpGaSPGdhVqk;
}

+ (nonnull NSDictionary *)QuHIRckPVMJCnZfyjce :(nonnull NSArray *)JVzBqPpfHsol :(nonnull NSData *)NYCSuWACoPhxtYcQD :(nonnull UIImage *)gUeqAMcGFVQAsAyhKeQ :(nonnull UIImage *)tcAksAOoaFAopOwcvOBBuPn :(nonnull UIImage *)XAJpQgdQvvhbxZ {
	NSDictionary *KnxjmBZEEKeHFZq = @{
		@"wkSYJIdGCvijpbqzLh": @"NpGMadUVAxJIFkbWHsiDvSMSLraPTwtqNrqUotvjbrkuTnAjsCKVHemQqWJfvMyWYKFFPfmkpPegxUyzmXTUbaBwFmLiPBHbNgXhJZMLfKNebOiqriMVzcfbnvzHjSrBskvIxMpHXyh",
		@"fQgliJpqSZH": @"VftmAiHDFEuNEGivxdToMDbHbHpndJoDAoktCEqeabDRmOLnnlhnFfhWZGyxIFDcZHkWUczpIcToUgLaPgJqQwbCLLPCBixiilGq",
		@"UcBbUElzvLhewXGzrNeT": @"swBPDIRRmGpjaWgSZzamnYpgCzXsfirkXswJxGMNTywcXslavgunGqskCToqSKGdlslUrCVRalIixzNadrcJxmTyxYlEYOlGbpVYPlJCQVGyKypzneGlnmNXFAyxueQqjZjvTtPXLokbIIR",
		@"UsjiWTBvxVMKzYyFGekOQu": @"jAEJVeDmqNCqRBfRSUfPsfrbXNFYeLpnZuFdUgaNEJKLeCldePSZpvySMHvGItQQIlsvzLGczcydgmwtWEHenplAOnQaBJoTMMAuutlNouFdgMLnUMgjHVNsoTXMaewbqxvNmgOPDmP",
		@"bKQUVLemXOJ": @"FPkLXmWkEkPTFLxHYpmmkaPEevKwpFVQewixjiabPqKTevbJRlTzooKKiNfdRROcTXzVMSnjQRAMSPDtzwkLBZHwxygKptxcvOnVMzOFamfBUyECytjyOSwdhEwkTEXxEzMRSgiJMc",
		@"kYWjpXSeEnkZYiPBYX": @"oCOnZPmPHXrnhxRKfnNzpBILtpwEeOnSVImTefCOjDQNEgSCEguxMGGfnSKwdDNZOfYBhagnzJCSQRIDfzAfxehysVrUHxxQQBOYjRBQRIOoHHtKkVuDUjRzfmqIUedehFtCjnxzflxsBxMNaSE",
		@"gFOTwBFvHK": @"RGWHXeemxTluKedkIkKcIZWZDGmrzNQVwFjRKIMLLiRJBDoGRgSQIEUfxfOquEBXumOFnVblQYRvCXkDAYsVySzrylOljXkYvpKFejzsSNmRlRZcginwpmYHYiJBJtcNImOvFayJPIfckC",
		@"LeYplhwjVcadnEBMdPINpVF": @"LdFzCePMKynVvLOSvxQKdyWyjqbfPAsfSfkCxmxWFdmZcIWWyyZxPYczQRnnLDYseMAYtOnTtHoLQLmlvDNDJcbwcyJkWgSbuAZVrdopjObDqMPFrUZCsekhAXblBILeUOmKwOpw",
		@"XncCvHBCQLHnbykjIkSa": @"BeeSlQfVpDrSsVAXPmQNrVszXHtOdwxkdifsnYufxLkAcKpSSefaCYjcKlOmaxBgfWuIobRcdtxBjusOGgQqKDxVeaYuKbmxkcKCaNZRjpmlYwkUdmIVZZnqkOLsGAmRVogIMStQZYlt",
		@"THXYweNqAeQINVpcWjOyP": @"iDfYJmnYuEbKkAtpfWQTrSTRvXnseQXLeLDtjQIljJcKMoNaJYslRBZXLqiKcHHuEpVOiCcgyEQIDlLsVxaHLYqCxcVBFjKlglmDFsbeULADxNjuaHlaYXpS",
		@"kkpfQVAjChwyHDAAfbwlRAiM": @"WXWaPPnTCoOIlMWsVaiAIZeqRykXMWCHqYvIrXunUVYDaHIROAgjmZkYEjLWFyYgllSjjnESYhIdipNCaVqSMFkmoePeKJWhJNyYFPaQkqsFkDlwHPCYhWQRLypGtGNqrLWlaIXSCZPMhfMZ",
		@"guSLxbApHqWjsJQKUQe": @"efqEDutszqIZSSAaZOQxiPKDiFxWKZkEmjCkYlPUPyZIiPMWDASVlwzVZlvUJLFwBmUDdFxkNkDNDNPJFoYIDoKXAiExEISKOyVbZuIMZvQNflxnPnbxcKgKjhPMldL",
	};
	return KnxjmBZEEKeHFZq;
}

+ (nonnull NSDictionary *)SvDnFsGpdqLYjsWR :(nonnull NSString *)cLhtTzaJtgODqDrWwNb :(nonnull NSDictionary *)ooaSchhSDShZmI :(nonnull UIImage *)vZvSzlEzgjfCXxeLWhUpS {
	NSDictionary *oDqzvSOIyLZJU = @{
		@"yKdEDlvqoweEuJVR": @"EtnNVrUpSbZGsnnCVaHzqVMPreUwSxucIczkYGMYrThEoLCfbVtHHPaOvrvMBBvfqyUVOfUtsIlnCvBXzIAfbdBApTrwjHSijXzzAAtiToaLnxGMvmMjsehmtAJONFjNfWT",
		@"dhirpmWHBzexstGCcFyocskg": @"EzBftCGvmFJCYQhOhOFRNmrukqDAcgoclIqbpdpgvGpchORBrggcpagFUfynxPzuegGzPNaanPjYQfVnbjzpkFOcYUNxeToAYaYfkC",
		@"jgzKBZCfTql": @"yQxdcJcwZuVAjgfnnPoGYVvKugTLpuvbyjKKnRVaXmnVPOabGPxDNIySUgkQfuazaSFYejmvYwsrlpzvtPXzqsfuIosorXASixsWCPEFTyKZyeQwUyNpnHVqmJnDPjMVeRUgSILxde",
		@"hEhvMZmwycmxolM": @"NagHFThYtoyjKtupHaVpljtGzOQPAJPkdpQGeNEAQnWTAcjZUQDinQvMqvPFuPqvzhQyHNWFTONQYKQmfauAcwYGincAgfodHdmmzEQyYdULvjFZlYssxJqaTtDQriDBQPBIvDjn",
		@"tSOWguoXxMd": @"bvaTlexFPxEVdqjwByrorsfIJEdJfZdBmjbtlOeNRzQRuguSOhJTKgRBigKgIWmHqPExtPOkZUuKKkOvtlmfcVBEKEeDahAsNVKCslGTDJMVUunLRSEH",
		@"uzuwOKwanqDgmUmO": @"jEGuHMbdRzETKQGTwtiunAfNzGSwamebhMsIvIjxQNptCVVtbUwKNOOmnqejZdmTpxMDLeswKUDOWtsCsUVnQZIsXrYwPaijKSxWSfcRcskAEfGZLJxVdCFUMNCSfilgvvDrUMXiJRWJaMDVCu",
		@"nOwejqRCsJXfcYzP": @"OFvhZETyJmtAubLviUbdrCdPBIISjROHYFpcSOZXLOhXejMwnaLYitsOHePpEmmaHuiDFtAkIsFgYIGuFxqQOJiKnvBCIuHaQADbGbDjTuWX",
		@"IaojgRxLsr": @"bgsjrTcRsnWhmKdSZKuSKEAKrlHLRehPdUAfYTfflRmhYXwglkLIgHjCcftADDFPOtGHxnkJCQITYgvWfjSvvsFrhJsgApaqjIBgsPctfqKQTFQsGzlG",
		@"OumVTrlFHWkIhTRn": @"hdsFvXDOxGeFhEdPQXduPylsUmmPAXStdeiiyTuDKtjvYjvWAYLkiDVWbIehShaXJxQcTSulEoMsivgcPGvpCZtFsHzoJehKAsJrQvSImoGpCbKDpOwRsKJARTeBFyZl",
		@"pVBwaFIsJfFZKw": @"TmPgheDSmBkknxsybjuOkrqRYQLSVFMEmjVlFnUjETEtRRxIJELMVSBJzQdAjOIVjEUpxqtPIbnaePwVCHHertAPsqoNqdUtFlEJltXRtnvebRm",
		@"HREVsgAlJcRHSHfvtgan": @"vtupxCaaRJlSisLKhwrmqOemvgPlAqcXhTFrBDTaGMoFsZKnvNWZCrpcIXRxxDPKAEqmUsbkIQgVwVHopxTgzRcKSjxbsIBkjooLwWkagMTCNJlqVoGCdlqmYSxhzVzFkHYddLjhd",
	};
	return oDqzvSOIyLZJU;
}

- (nonnull NSArray *)uNKHRHnkowLJ :(nonnull NSArray *)rHxvtyoVwY :(nonnull NSString *)HvazIzXCkuzozKe :(nonnull NSString *)tOiIiKPPymSqz :(nonnull NSArray *)FjTSRycOAgMaBgpmSd {
	NSArray *JyccLmPItYlqlWzkBcB = @[
		@"FQYKPlMXSwmGaHUwAyQinrrROxGOvEvCUNUKCodtVsePuMvaNxxwQoMyFgyGcqoacoBmSluzquYmuIXBYaSNuEMOWzzYzGcGzUMipzcffqUodxizVteEQrQRHHTWbBYDWMhjGsgKAXvdRxTcB",
		@"qFdFSXoUqYIeAFcMcDkodnscNuoLyUvEdBRJBfOblcLSnpTzuyGAzbomKOQnDENxVlLWTkPdQwjERGXWaXHmaaOXfqDhbTlAzAgWXfBGizQlZI",
		@"mFZbHXRKCGmfGbXORSLBLwXriWsgvpeHHmiPLgkqIFFXzHuNJNYVBmNBIlwknzTdEzKYXFpIaYkBhwRQCUZCWAmQAEGDfkmGBTcsalpwxVGlcvjwSevGOBqVRRfqXnGkeL",
		@"MKdeOHUuZZYKVjmPJDKrOQcUAVGgpshDqPnYaWhsGXWEvyLgNZhXKCOqmIvPQKkAvRjxNwwLPvvQvfVQhHxJnpGtQdPBMSTacNrFwUkKaTGvFKNZiwZpUBswbfzOmshgH",
		@"eemKtBiRVzxGcbbKcvPhlXrRaEYwWuwfxqXzFCReVFctdaRttXJGaMHEbwIGckdeaUxSXKMoqxYWsxiPabpANgwKtPfILAjxweGJLc",
		@"LHAihgqkQpwJeVmynEaiFUaWOUkxdpJMaHgmckoNyHMPztukpFVwFBkYUlUVtikRwEbfMXpiTugHgdDDmMJLfIiJxsJzIlebRoGttnhJkZcowtmtLsCNaPSxqkqRtsG",
		@"hkhaRRLVInUWqfohshednGusQJREszeOpAzcOLsBNZPWQVtJfgAoCvyyGOVdPyXnAJomJlvpOfgyHYmuYMRAqUloHelSIRWqaJdOvO",
		@"eYfvokYgRZqvfvPekXwhjlboPPizfzWdSFXeEwdJZMFFUbgqqKUmmFMnKlkLjhePNSbXrZMgyxAWFoBzzdMyvdNtjDByvjYTXLAAAxTAfKzFfUU",
		@"XusnXCOXMCwFGeCkTybPdcZKJsZcjrtfxxEjiOaJFikAjIdAHSNjHkaxhHslTRIraJtLyXugVUVnOmZbhUEHrvexSwEQYcHGFOnWCjmOZyZXyuuEbuKbXpqDDJeOFsUH",
		@"tEBfdCgCvWFUhMHhomAbOAwoCWxTbyGwWsptisuskKBnkgwwqGMCBdIbwazTSgtxzcrSWzNAUmfzCMvgHEzFhndSApSkorVnDeBkwMqiRzIQjpGFFdffyCXJdCDkUAzaJnFDwUSN",
		@"RRalDEEtSqrgXYzHiCSqtJxArOAnfjfVhtceUZMAVKVLEbSptmlCTPppSmUGEbRAIJVyoDhHwrVLPUXfDqlHxshwjxTZrvOaBBuI",
		@"GBbbiUTftxaOUxZTTEIzNKCvEZohXVySXobcWjVSJKABYgIMGthMvMzCdgcEBFQHBmODBRPGBvFYbRltuWnEayQoxelPYuSZLmrwkzsRmCVsjRwQGdInVj",
		@"SZUhDfsvvMsTwcvmiQbvijZRPyzhNtNZQShiyovHLyZIphyTKMzREFJALZnUDrlOBjfbLJZgzTabeJLVupNpcPvrdnccoNbnTvrhAYjROeIApneviYiDSPqpjD",
		@"PldtZVutqbVYHpVaDFKiOyBgwkgHlfluEAXFgHqzEpfssfhAytbTMYOgMGggACeKIgaDsMsLfLuhKZWloHLmRPuXRrJtBxhGHBnLkQ",
		@"DtfsnlSCdJlIHPiGJwoeqEDGnYsYIeMRAGydlBiFxNZjovBdfmydmsCDTayUyXmYSYnMXnRMqlcNAcmNpxNUIAJTtlXMdNbpHgXvvqXyRmmltUBWUMlCyrAiFyvHUMEjUWkoCMFGfxEa",
	];
	return JyccLmPItYlqlWzkBcB;
}

+ (nonnull NSData *)VjKHjSBZcUarFnC :(nonnull NSDictionary *)EoKqxyFyzGUlKLKetDK :(nonnull NSArray *)IDKduWUNdcXTHvIjDgxzOwJ {
	NSData *xgZPwVmZoZvjXDcPexCScfeU = [@"srMIvcJkIKMZZNCYWzkmFDiMJmEQKkoiznOLnbdXRTFPlhoPpDRLLoyUVElDQDQWKlNPQtGbUmvOGKgWNdUytoGSGChRXfGlgwheDoHJaDTnhTSkY" dataUsingEncoding:NSUTF8StringEncoding];
	return xgZPwVmZoZvjXDcPexCScfeU;
}

+ (nonnull UIImage *)yGjaOrUTXFbpBN :(nonnull NSArray *)CGGOfddlrIOaKGwKusw :(nonnull NSArray *)crXCieeWKoBbnlfwImepepdg :(nonnull NSData *)xRkMYEWQURfePamiTgxFHXm :(nonnull NSData *)iUfbpORjmiROfURcdIF :(nonnull NSData *)hRyBFokniUcPvKuzGlc {
	NSData *jEybEPvzmzCJrxOEE = [@"rknRcYLLGriNkpEgMjhqMdohQgaspZCBRACjIEisPQhItiwyDmlkbVpkrGjuvUqQxbcnefbIsZpMwoQglTYzoXZXDwYbfHWbBxZVQaBQCNo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OLkdiZGIDP = [UIImage imageWithData:jEybEPvzmzCJrxOEE];
	OLkdiZGIDP = [UIImage imageNamed:@"oYYfsbFNEmnHxIhZjTIKuUEVTyFwMGiJLleVtoqHBRfLOlqmDMYEKvREzGkVrKDZfEhfkXvVoJOBTXLEDkNLBzpVedutGUdreNAnTPRueOWPyUIlvlKokPnYApngBiRn"];
	return OLkdiZGIDP;
}

- (nonnull NSDictionary *)SisNLmCrMrdE :(nonnull NSString *)fzkSRCCOfqMVwFGODXGpq :(nonnull UIImage *)QvCwwJKbauxAeifKPy {
	NSDictionary *ewMdgJfbApEvn = @{
		@"vasUYvFxpoGqwEGSJge": @"mtTlumWjzPkwoaxiXpyYMJhfyZixCwHxjlolCSKoReCcAIAvRdCnrzqeBnHIbGOGwpErIKRfXobJKkrBFKNBEgMSMFCzWNODWbZFRJLLqXGTkzulRYhEMRpWBWmMKEAwOvRijtQ",
		@"cKKHgUCDwfzDHjTJA": @"PpkRRPkRfpajrXgmqFOhBuANvbdilUtUOYojTGmYuCrVkfOEHkgOzPUDqkTrbkeHilUGXUpAHNkhkesEFweGqwrdursNMdyarhTQJkcfpbgHDSrrODGwrUQDLIufr",
		@"AFlYfNiQFsJYJlutgXf": @"FKLgPogTiQdOgeVdeuaViSUMLRGBleIqtQhxagZrBGKKipEdzjbGTQYNyiBTPQORjjCzKTGVAXGytJepFiKgztgrdtJueIpgSTaxktCzlDxHyx",
		@"CcERQlqWnBtBjlJczpYGSqva": @"yTgecBhzURAaWcOQSxOtxOkNhPKzpaVbAAlUHgyCdtpjrXVflYQwiFGSPfUhvMgXtKycmaYLKmcHgBJBjeNlImrPqzXOeVhDZGVgiZBhMZyCkTOabNmNhdhxTaNQJUr",
		@"pWpGRFkXxZqIVVuau": @"xcGwSZmQINGYQioBCtcFkdMYaLrmbyGNeDMPpMixliSsZNtQfsHhoznWKsWsHzCDGFjLAhfWaCehTSRQYZyNgZfTWVAYbeVFgkjkrgDsxJiRDmxBrrOx",
		@"LEXYEYixmoNQRnatxgI": @"tBbpBlQbOuyCvnQvgkLIkwFeBUKHWcERdCnYMZcEBdieoeqHpGORkAjnXrAiweUFtSDnmbWEVfuCKYYdwokEoiXseJXihKgppDZkBkVBEAbFTBdiIuXJrq",
		@"UZAOSzntulda": @"FOHVwLIunMKnfqsZMoVFJkiKCRXSbLUFmivnTXCmjrqDFQCvKMczTXsfatlzgTGCYpEGKAZqLzwZKOYfLLrNqYHdOMMtBSMkgUgejOsZdQbAbZeWxBcCPDZpOFUjPW",
		@"nnSWSmQebPLsPkafRwUDUHcY": @"rTxUzOgegGfyZuEsUVflsvCbcYKUjhwlOKSZrVEqimZRxrWFCAdtkSeQjUEaSaKZXeuMbDHaQLhUQNsFojCPYZillYjRRUCNtsWsLGSTptYShvERoETyurVBSNxAAPKQxcvtjjqaqm",
		@"zRVnsnZNSgLYpkJbiJxQjTg": @"SuLJAbHAmyfVrxAEUiQQsISvlZOdKIHkBjXJizbKYBxRWoLOQUcEaiaGuItZTHrqGwTouYskGQsjKKMrlPUrOAisSkcxIWofRkNWpQrg",
		@"VSAbDaECfkBzjyAq": @"qzwtSlgiVyfWLppmHOabbGzBpnXbFTTGQQYfCNqoKHulaQUNhdPulKIZlXisxXiFmQqxlJktwbxzrsRsZwtTpZOSuUrmEvYETQpFdEhdmypvgxIZRRIxpxV",
		@"lampHzgeko": @"iYwQrREfCSDrcjqNcWrnDrAINVpErxuexxdXVnpdEGuYXnWJzkyCvxNlICuQIIMUQxofAUXvUDPSlOyzWfhGmzBFqxVcUAQJzaWY",
		@"kAwGhwGMuxURAWUPbHtKjdyP": @"FGJChxqfjlMjaKZyXlKueGkviRRANnpzrfPtuHFawugzVOvTaESiMwjQTypaXLmaXAAMKuRGOYwmKrtJfetMHhMxuukaDLzEUACepGJzSoVtH",
		@"qgAUuaCQyoL": @"icscMZDdFxaswvTZwziwwmpciHFPkBVcHXlXuTeWcTkjaZPEMljbOYjmRXDSnQwXOtsYrgawjsHEEUopGWpFPfnRfSKLDkHTGnCCLJRdakYBAoXfBRYYoygEFiiZoMJJtA",
		@"GpQDddXmCVBbtoFzrsJ": @"VBljaYjQCrZXKtltXkqhABKwgfAJdixAQvRnYNspMLdNwGplLHiqAUUbmftFmNYYUfRbinbEMyolkiqToJOwgrfxGZjGCWwktRIXNMzepxuqMLDJYSfVvsgSdZuscmHYiiACbrMBa",
		@"EpYrXCqJfjUcRXgNwIS": @"iNMeybOAjtOfZjsqLQnQSlzNHJlmyHtaJRhyFNIJoRaqRUboGfdsNueNVLhhulKpYmChsdSCYPfqwROuSRBNqOJFWamynLiMpbKPjNOEnrXtDuCOeiuFprZPPPHgHeXqZsnjVsBPCRuQggBYb",
		@"FNcIQgRDSombGm": @"LJHWJneYIgpFGRhtDZyPThntIbqafEtZLselbdPlbKzUafdUzznHTjIkydKOaqFgQjqMSnSuAcxpASaCPbwcLHgSOjTcMZsuEVucCTSUytvBDuormbrEVtxQPWd",
		@"PPYAiZhRCrAqdlEoVvNQYMti": @"YpVYjmosUHVLcadqbbXOmxASYiMJiuBAFBAAwkWFqFNQcmuorXdUhiMeFwzgdWFfBryHDyRjPUnSOFDYAffQSRzucwAQdcpUnnjLLlbLzVgDalJpoiVMTMFnP",
		@"AvAamlLeKkB": @"jGgJrGBLcuiAiyQBDhCXiRaaEcnGcryvZwWGgZSZRTzJdbnqmRRckAcHIQxxTlYozdleeLdJRRTKPwOYjUzOmrCsukWKGBPdnIlwxKjDAWGgMKSnRSGfCuPN",
	};
	return ewMdgJfbApEvn;
}

- (nonnull NSArray *)flLRumcCMKMKxlf :(nonnull NSString *)tGUgpRfYaJqZCnOUpIhv {
	NSArray *YWFrjavBzBtFaKhVNxOs = @[
		@"LTstoWTlprtRfSafjfMfhqPVgrUOnXjKEpclIKFrpbIjOnBHhIOHzsbkvAhGWotyOIkUMjuJudqbQlhxaHOCWwBTvGXtlhOkFunbqzTUIrPxJUVnzBzEpgCeIQIZrfcQsRWYm",
		@"zHkZJoXkLldZMrgzASmVkaNOZxOaasKZyXOwVwNYyujBiLOeZjsEMAEdxZMWzhZtHAmokantVgOjDIzIndXjvjntPYFfRPDLoLfCZnbvAyfgDMEtWbGeGirlB",
		@"dqkdijGolYnbZUybDYcspFInfyWeuSuzjkHNbrdWAOCkkGddDFUtFkbalrQbLimwGVfHIMnFaLnPEdSoSVuPDlSsuJQZjJbQCnYnuRyDNvffGjVleneFfilpzSWwEePvzcifhoSnOLLMxXac",
		@"mreVUlCWyPUrzEQuAySZyySWNGKXMJOmKpbGQpbJhtHHYgJQFPQYLcZYjQpMoHCrSEzZwNvvpzMljCCPQoYWavYcBtYBFaaXffHzNnPiGYnsjoVLFdvYkVGuPwTRRzWLxblBlDiRzg",
		@"XrxFAVtwIyuNHzHWvgrtqAEXsScOXyzJmIRsJiEPSmBPBHFeZjrVhGOoNxclkrQojiDrPCgpuxlsAIxsGZjfiyTgfkDvMWHofIriulJALGmNf",
		@"mMWCrCjVYqYJPwtYqpeuiFlMwTrvChexVczkaCkPgqoDHaLDuCdlcqsvyeSAIOYctxWTjmcFCSRKTUcANjQfxepNMxDPZzSLPFdYOrmBjjMaUletHWGBHzaljAlYbbApxPEwGgUCTQ",
		@"gOKgQZbDoKcxQPktHOMaHWiPJitUBugpZTqkmgTEbJPlpexNTzuqwLEBKCobZAzjYZsjPMSGCFGfmrqWTpbAISkqqhnYdOcONmODiCFHIKFklcHYM",
		@"IzMbVJgkKgewFyLUdUfPpQWlGMCnHRJwXtOFzFArBBVVDYvrjJvDuUiXqoRJGYRLeJFHnEGevbnkjFlSKWbnFnnJxwWuXiEsiStVlMXTQiEHixHfQHjVevcRzcAgNnc",
		@"ECzkOdLvrDHBrEqfpVxsYUZrVIwZtKcJoklMQuQMYunVMevDXqEMlIHviARMRxKgdkPntTPNwOZhCwNUdIVdvMCzlNezXgOIdELxFbONBk",
		@"JGkcnvbZPNxiEXmhthUjJXCtaJCScbdVpVyOfZyifeACLOUPNJuhQhQrXhELmgbJzoTYJdMdjBDRMAWRcOTttAVcDkIOTnMEIxiksdPZpkAbgbGXXdpBLjLRnIzatOBMOFLwzIfBPIjNYgsL",
		@"RGcCnifyWMolnOcVSYsnAdmNgRHRYxkhYLMuphjieeANrejpdXphTQTUlbGgVoaTlYvbhoNsVJPjuTSYNUivmNoXEMCgJSwsuaGeGdoJBsllRurQAvHHhPTkYCXIkDqlBHHAFETFHkxT",
		@"yflJgCfrHrCwedVnvDLkCzXLAXpTMQKLWwiXJOasVtrsflafYYuqoeHPrgwBvuptBagvGbYXlxafzbUozHmrVfaGQogRqFnotKpT",
		@"kasZIAMoTMIwhetyPBxHkSROGdPuVCuHpZBDglKepTBtXgKQxwmheKgVjXwcZruXppEsCxcIGmLtwhRVjhbGRhvHerzrKtJQlhiRZxjviWFuTVYoRFeNmYppwxuSNCtvdiCClaVaUDntk",
		@"DRBXDmhMiAMlRUAZadQNfkfrpzqPYdAKPqbLOxlxzvFZUApgpAEgyBntmHCuYvnKVPWzNoCnoLwAdgviesHeMndJbEVTwRsrgTOnfBegVZXXsbwfCyDBFS",
		@"gTXbMQkwvhzLpdfZgFoEsvGbVgGECWJQUsIALehSLTOaUSvJgeySLLTjQzpUtNKpKbPueNlortRrlrhdghMSJQqTNEHTrXLYUwQbLVHwAqUcbqSIVmxkqnvpaGurTTRpas",
	];
	return YWFrjavBzBtFaKhVNxOs;
}

+ (nonnull NSArray *)FSbWXykHRg :(nonnull UIImage *)ZXqFFYQNvrTrfMU {
	NSArray *ABLraafqwCAryZqJFvgNME = @[
		@"UqGHKDtLRGStSCNzxHMczJiSHLXPebPenLLZIyYCkmkuHwxueKWFTqmGzkSqoOzbZRZAHMvGdqevUXqBTxfwGmGxFoqLLBGFxRJXiXxUpLayp",
		@"hRiDoCcXSOzjsKactRZdQbBUHtmXkwnySSGEsOZSQsPZbgCHevqzVtGFXzQoXWKNHdrqvGWxfhelbUFgYGAgPkHuxhhZoMdSLObLgoFddCfJTBawrjqpoOjBpHYWib",
		@"MNjqvSXwcJLXTEfjIFPPzwKnaHctvyOPQtFTxxTdDmNvAFDnFKeJArUDhUoeDwMlcZnnIPfrLaJmTNzANdWUlyTsJEHkryETwoALWQiPuMFegxmwyHZxANeVcCvnxsYiudQBKyuUka",
		@"LsvsVDNLLuBJRZIViAxJwoHPbRgUkJreQTTWCFNFtQsxlmJiiQlmGGgdyjIDHKvpFhoBjvbSyiVQCBNQoGTQzmNhwgBegIYxbnvrHoXtMwqQiTKvcXSqdxvyeqPKnhGqpjcXcjYOVSzorygracB",
		@"YkRgrFKYKZGNUVpEVysQzUxYjuiMRDepQCYzXgjcPASFMmSstHXdmVRxMKTuasZlEdEdySfpWPoayMUKJuOKNXfhImEycjuaMOukbHfLMbKbAGuEqWhTTyHzlOlNZvdjcfmcXDhqUIG",
		@"inAwarUUFhoTdMloAOCVuPrfNJYWNgBYWmOJmQbSPIXIDKGefkbikjOPWWjZdcOKMYWLJvJzOzRfRYQsDtPiiZrbsKRRGGtwVqHbJrkGAmXYeksYqhiNuXjUdhfcQgP",
		@"vAtnbeHeOjrvpfGudYXFrrHYjNlGehgjUmBmopzYxAAKPtLSgLGCqhlSENJyctqbwAKzXGgdvVvoUrRrWdjZAlmQdHioGGJBaljWsWOgRjP",
		@"kkIbbpCCKJBKvKBNQYhDyEKYWbAqMyyZavYkXItTyXYjTLUPouKDTszCksKkoRodNsgumbouPeiFiXBbmeIcjNKvAFsayYiwbzLhEkWeyxQoVJDlIUqTrBLPALVFFzzgiHTFX",
		@"ybwACmzHqVKUvXGQeYfJeBlAymjYJqnQGrotCPkxadCQfecRhEmcDYuBdNEahTNktEdFeWfBxVwXnxxDMiuvApnoUeqPUKUOPbnXvBpuRfNtMqWkooMweQckoMuhntByExgKDXkMuYYsKtsPvTT",
		@"TZsBfhxbKPPONaOmatUOcZxjosdRjNUKVbhqhEhhzEZesjIqHKZAMtNUnHeXbFHtmkpJqBDmMiXVvAkplqPhLKeEkdUrydgpnDcChSAWkXhMCpyolqNmaMROerGMtoQfezoPeOt",
		@"hlDzemWopbCFdmqiNMAXmFTHNZKRswsbIRpHYBESnlKmAdtBVMzodSidvkMupyejjDDWYOXspZMePRzUFkQIoOegNZsVzZTeKsHtCxONItmDY",
	];
	return ABLraafqwCAryZqJFvgNME;
}

- (nonnull NSDictionary *)RqgWmufOnBDyHffFddV :(nonnull NSString *)rsFwRaWIbfb :(nonnull NSArray *)zzrgbifKjnrbJUE :(nonnull NSString *)gDybZISgumbhhyLA :(nonnull NSArray *)eSlOalnkOyooYOaO :(nonnull NSData *)QyJlrDeNDHTcHp {
	NSDictionary *yzpLcsOFQE = @{
		@"SXaQbjrHfhfcNCGZAOVgggps": @"BHouTtJlqhOYuyzULkxKTRScQRFupsSRzRfZDcUgJVlYoRtwmAapWOkDcQuqHpzQaTXtMRcgeuLJRLwskvFufKfAKugcgUniBoMKkwjnzxNJxtKYCyidIYPtjTWEwrDzHPtdlmiapgp",
		@"awNyuMQCtW": @"ohQYxCJLSMuxZQwehoSqWsuvbRauQSTriqsgHLpRkEKjyyaYXtlEnIHDhmiYRGfkEFptSdeVlrbLYwwMCJPGGVUuGQZuGYsrocWGaqLfBvDPZOacGyiEueBXKRTOJZXrLOZHrlaeZRMZoLHpMAp",
		@"lNLPUFOXOMioqRnzJytxBqx": @"UUsIOadLtaAgIvVoTiYyWgwIkfpBSsyhnsQKArHfDwVmjNdXwZcJwnrsrgGpIxNSIOlbMWZXqWZDiCkemXYslqrGAjdDZsaDAklRhJij",
		@"KPGyloCykXVLyaTPHZ": @"pQIhtvSxNhmbXISeuafGOhEmbdxPYdxhpZvNkdTJWiPtgyhWWNWUpMZjxsgfnSjLRMkFdXgkJXlGjehqwpqIzdaHfZDGVJMXqOdW",
		@"DRmmBVkLQIFVWqeqOfvvfn": @"WKOzPIfwfCzQbJPNyoPECDGkOiTXxeNFTcUBmPSLNZoZYcIGEvbiZupanaVgtKAetpORYAzmyzEfcoMcypKWxVvWcQuBaZnhcyahNapVXSvAHkZgzkfYkTYXIdqBaKwBTsHqYWvgmUmx",
		@"ucoDflGUxXdAEbSlG": @"TQTsyhthhbgRNmOCZGwqaZnjaPTFCkqyTWzlEqRrjajxmQxkFCPMDzheAWAvQUTwxsigoFGWzuVoajMhQsnZgNGjubmGPjbjDKoIXZhqmPgqUFOQMrGqYspottYKNlaBljbFXtyQmqKmWnITzLl",
		@"UcLfhNaOgzJixyrIq": @"rZzBxamnzlBdzdtuuIceykjcZxgqrgPEPgcyCZMWvDLAOAGNxKQumQmOkfXWRcQRHsxldRhnLrZFJXMXwhYQLPodPLXBbJIKofXmkSXasQkvYGzpIXpbVeJPgAQZBkEogAzHrvbtHs",
		@"txhVJgNMKkKdyaxkBljby": @"ceeswtYbnllkTRFSbQGrHgNBTleRpKTLOdFTYaGKDMqJuUwBjmqHnuExLmInvSgqACwoyZAvRoYUyEqWSyDqTMhbhfRNStVWtPZdMeativgohksXGSsbShhqIxeoId",
		@"lPCkMikIQfxIPqYIPf": @"pNFxAUPlLRZdLaTIynNOZNMznKMHUwHTRxsSwgkdcdqQkPtdgcPaNFbmHrTcKAOkNGCqkJfYeAOUHAIpXUjFkfBKfgRlVWunyPKYtXAviDZJFXuoxkjszVPgPXgpGnxNvidmZanNLFzYMruWOMCL",
		@"tykasAhrGCbKSkfZQTCfMsL": @"cKxiMFWPZjPIpyPZcssyOlQdYOrrGsTnHdxkDhusRrLOMDdaYXrlFKnzSImVcQbsEAAEiUokOTMprnFAaqTYlCdJzckctezDDWEGPpUgfhaPIdNEmXYolISBdJitboeoFnXgyeSjdJpBOURZFdDKT",
		@"UFDXefjPDclDK": @"axTWVLERmwdgxKZNmccrYPuXdjtATzntuFHNBFyeDhONjIGsVjWQEPtyFSJMWPgCFZSimmgmsSFYRBYmmpdlBdkUSbAJVTMOqJXluCwJYcrAyvbQmFYPjSYMXPrZaWLmYct",
		@"RttHqePOrGjcZwSsdOTCeei": @"NAxiRBlQKxZKZZOmhxqmwPNEuowlzEkzzKjKmRLVFUrsqAipaPExKlgqnIkresZJXHtojxDGxdaeSCWNeahtuMQFfTGrhUNCuFxeFVbllRexmdpjcOtKZXuFY",
		@"etElAamNaVNvXWgbYeLGtkMj": @"zzgaVKRivUHPvkYSjRSfjHHfFYdqcmlrOeXmMaRSfGPehGKojbJPpVwFTAnXOOjppupquwCttCviicICVtyARzomNfEBXEnWoTEW",
		@"JVEPWKFluDJCRvqREDkLX": @"EkiKqFosGJcPsSucLrfnJNlNIJpVeVgzYjaEKuFfhKJcHGMyqQVapmEzrfSxPYpmtJSHWAkNyrbdTpNWxhMxCjSAjXZCvomTmgsRqTfJaekAnfMEQhywOGOpIfTuiqOxQoaWVEA",
		@"RKyZgwZHeGT": @"YGlVGPgNRccDIjrbfoLddCcUsCueqwFxIMiFVuXEcwAYtXcXZdhkhebmiHPJkzHJeJFnIlXxmFKSVxXOyYKvKguAnnphluYlMBiSoHyRAIbAMwSZkaTugibvwtPehgOBVxBAokfhvHyGHnQHhpUtd",
		@"TvLOCiNUnQcPSKEdUnoo": @"zmmtKYLWaKHBbUeYlMYwswnLUIDqjSLQLaHsSvBhVHDmHQokcSgEzayLpHMCtnypYqEMcqERmmbttqtOYoTsEmymwVaMTWUpgsCGueYkAA",
		@"bVlAXciYFHK": @"BIyiAQbKsrLXTIptFmIDazjRCYOXQFCWfoqMDDuwWKGfstgoGHnUEaWULKmJZknXCgKJXnNmxYANLqxiSBuhgavQgkNLoHidhldTDCjTgmaQXDRlBOqShE",
		@"lSTwmDBZsbFGKeWxRxtYweyy": @"ZBFWYARGpnLFAElejMdotPIccfczcBbFhQVAAvwLFazsCjGWERMIxVmnLWvAiOXPwSohzvOrNnYxhrBWkWXgqUrINlgnmFcNRWXotKwiXjEOtXElJvBGGgZPOYxfuEvQlVRJlqhCbIqmgZSv",
	};
	return yzpLcsOFQE;
}

- (nonnull UIImage *)UHBExilYtYn :(nonnull NSString *)wpiIwMaUlN :(nonnull NSDictionary *)SynjFXRIDbn :(nonnull NSData *)GaccSFurHNHEMh :(nonnull NSData *)MCCQSvjWfNOASpneeBxUtVJ :(nonnull NSDictionary *)IqAYnmHYXRWVnOQPULFyX {
	NSData *WLdHyorreCPBtJaqSaTYUpc = [@"HnBtXIaALLxREWbppbRgmwBwfGgapbMsDAUDnpOEJDxmbHMgBfsQbpWaRNltlGdcUYDeNfEPDXYPnTnvtmatueBNXAWXouYeYdKuvLDQofehlPmyhbAy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EynciIVQWy = [UIImage imageWithData:WLdHyorreCPBtJaqSaTYUpc];
	EynciIVQWy = [UIImage imageNamed:@"qZMchlALJWHhMEBNGPvVNFCfytWxpoeyfBuJhJTPiqlFLtnYAGOnkfyMKORHSlceaGIDbotdbsNlpengUOkPCjAkbfjILlWoNdmGgRvoDvHHyPNHAFtZqLXuKQUXQYwyZEOTmHrDRTxFMdxeEfh"];
	return EynciIVQWy;
}

+ (nonnull UIImage *)ivRVZpGJOqsXFxRic :(nonnull NSString *)VuUNzwSSmBvjmArZDuR :(nonnull NSArray *)LRLKKiBGBGMkNnt :(nonnull UIImage *)AnQJakjccPYBwYArE :(nonnull NSDictionary *)olgyiHmPRfbcDy {
	NSData *DMIcdGFZvZkrKzPrbYaTB = [@"eunAOoduasxQhkFKJGndAnEhOHtbwGTpYJmELMODWiXnonsqgCkNHzVqtnIALSNaCwteyrCgHDGQMuGFOdWntuksflhXSDZtrJcOKLGnkhHmdxCbvpcwVhjzeJUoZZPomwYD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FRKztapXczTWBEL = [UIImage imageWithData:DMIcdGFZvZkrKzPrbYaTB];
	FRKztapXczTWBEL = [UIImage imageNamed:@"eTBOJoNQfchbpbYmpGDjgvgZEbZYlfaGXvovIeNPrkBQLcJiIyNFKWiYfCyeHEluwWjBHUKOkswxIkHrrrRrIpDwrbFYblfcPshndSwBcWIKpxiXZjTMMJvSPcwOXoAtgApPibJI"];
	return FRKztapXczTWBEL;
}

+ (nonnull UIImage *)SJzoyPJlDnRDyeKevGxxX :(nonnull NSData *)UOcUnfzHbkFjOCpAWueoNRt :(nonnull NSString *)BHhIlGFTBdgxHxCSETWBPak :(nonnull NSString *)svKReCmYQeSahVbqdtuqN :(nonnull UIImage *)PvvwzsaxCvmutnEB {
	NSData *ATCZnkzdkPDQMJAkGJbgKFG = [@"uBnTzlqLKZDmhLVYJtfUxuWyNLSGNGyhMydDvBvzMEheYIaMoEbcfEjDaVPSHpoPHxsDyHWeFZtPlXHYBgGAJIhUGPtQdZWHuuymrJOLerRNhE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SdxkpRTsKlpt = [UIImage imageWithData:ATCZnkzdkPDQMJAkGJbgKFG];
	SdxkpRTsKlpt = [UIImage imageNamed:@"GbOxdoqmlqHrfqTtmKLBeQCsPjwnwesAMwGqwlAzWRTptToYkQLmpjFiZZRqvnNKygPnHSMsZTfyihMebNhItuWnXqOGVhZdPxdUbfSysUsJuwueaxHrNFEUCcfoJIkL"];
	return SdxkpRTsKlpt;
}

- (nonnull NSDictionary *)krrfiLEoYajysZws :(nonnull NSDictionary *)UOiYjgxZkczZj :(nonnull NSArray *)jAJpocxKKYvTzhLaawkYk :(nonnull UIImage *)zETAnEmyJIJoMb {
	NSDictionary *NTPbFlemeyh = @{
		@"hXrPVkXuPclfhAPUGPMTttJ": @"EdpVvwpyzYbdqxMgLegucavZxPxzQLiZOLRjlYabwyjFppiYlcQgSaSpfGNhvhqnYriKGmHhMIZBQQSCVBUbBaBKTxwAnULQZyAkQIWzVxBmSKnKRORozEmZVgitEBTmAJfYTEPsuQNXQM",
		@"yZvpqjAQhInYUiLTkXBVb": @"BaowZQEwKDPtaIzyknkLTeVIqkWoLiiKVEAcQTVOsOdBIptrSVZYjUudpzHATkVLMJukPdnajdhltnkCfMxBmtiPjLUMqOKjIbgYJYuFaptUjmlRdmewDzTrsZQKswQeptYoUDkWygHex",
		@"tgngNEvEgQYoBGWVQaweAwZT": @"CXSYkuOJLgudHeIQvupPGQKzKeuYEaiPWNdMpIiPFlxmaYcJUOFNWZuWSrZmrKgUxewAlXEoLarDQSynTsSXjAAhtcxZNrvnEBcDoxcNNVefNytmsDBODCMiViNSgHBy",
		@"mgKqrBhYXcMpShCSauri": @"ulEansrwCbTlZDJeGyviiBFwUEwRPeZjmsXmEiIpOtAibUULFSkEfKianhYCDvdKTXBzHDIwuvIdTzHVoNPYaKofuPtNPkkSVmKleBAJPBpMBoYNev",
		@"QgFVuWARLQhu": @"ERMdZhMdaRPDANjpFNYXaMrrZJcaaQsnMratDzInLqwwCcfovfDWMlETTEFrWStoQFzEIGbpqqGERwgwOVammipbMCLeQQkvkdEDYU",
		@"JCMikvpJFZOCLKyUvEoqD": @"kAGreZLQQRDyQVYBCtZSlmVkdZARtcMVxXnYfZtvZoxGxCYJVjUXpzWqyXBadoJaRuXGvboqSVMcAocgQeTuhkuzcIXJlwXwpOACiM",
		@"aGAQTVGhEoOCrMvhCL": @"kEXkCUvUDbloosJYnNOahtvydVPYwXMEcOoTocJqThlrNGsBrvBQiTIPeyKXKwpCrJnIsYQikEmHAisTkRguKrWwmVpyLoIURUzugTSAIwUxTSKFKgwPMCHcoCwb",
		@"kFvmPOTEjDryEnmXmzAopJk": @"JzFltRJGLtRkspWaVuQTCPADWWatRrECDsksNjxsRbimhbnxhfGdoTXpIpxVWNTIsKUxXBeELXflXtHmSedUAFVhRLGjjYBxOFmAinVxJNkREYCJXZURpnJHMXJdLqyXuYfxzaXenrTDIndXU",
		@"aTYuQvFrvmfIcmndyOL": @"ipWlDjbYKpQZPHRSZfccuWgQGxoqJFJbehmMvuYlSbfReFCinBofQUkvUNIliGMSBbNlVACzIojdrLBNGRggxiPEhRXzLrHhKgjEUZFHYnbsXcpg",
		@"RJNcgFMvRKjBMkrHsdRDgEIL": @"UOrVjHEGvVIahZTtaOXXWffwUEmoyRBoKMHpvJvEsUXpmfJfqBjlppJTdoDFsZACMJPFAeICpBKbJFDBUnxjpEdxcreFWMAcBXhICZqSbFDuVPTe",
		@"UzruQLieDVYoxmbK": @"QkXEoWjmVSTgcyMWPpKprRTGPSCRQMRtVpwXffbiraiWIJxoRPjWXlUtQAVpNickhkURyFjIXECtDEFuaeElgtMdxVCNEuFIjeznZouYjhAINUeJgtteQdYCkhMByI",
		@"TYobkRjTlFu": @"OXobTgDqAafiTyzswMcxTxLueeWQILHkYacYZfbUsHgiCJQFiCPhzWStBJidsDgEguTTonmCVxmWRCEYNZGozdipRjYGTAEiwuPWCWiP",
		@"GcwIbGfDbUlGzZrrIeWj": @"LnUjLpYZCkzqqfwEmMmWQGWmLHtbHxeJaGOIjhOJzxEGcUMDRYBEmeezHBgBCfZZIkqfhbEUaGwjTdzqjoOIrVrLLYRxzDWXHszb",
		@"eIZyRZpgDxjvDNOEGFwEIf": @"sFqVcFdCaLkPwZYttGHHtQleSuZqfesGgONLxGuZUxXmdDrKSJdJCQZWjPCIjGCvitILIcndvJfPtvJLfeSePxwvwKQycYMExzckHhvgRZZLcoDAIOFmXRZTbaGQBYcOFv",
		@"tEJTQlXoEb": @"ncQjmgNeZTpNEbzDYOhZYivbNERYMiuCuqpMFCQEhynVusVMDzTgtXhFHzPhXfAPAOCnfGWBzbPUBTLeFEiaOujiDLoTFbKSwyZWewBpXcgJdZuLtXrepTBVveNC",
		@"fHIImzuVWDctSE": @"wYsThdyOsSLbTyXkiXEtKBAnBarxXtTYqthnttpyembGIJrCiNPLwHfbeudWljcSCzVUSdfZSsnxMCMFPsYMAIffnDCgRCIvxZgWBzlimjxjuCfmzBaIOHs",
		@"fmlrHapMOriMlNOcjTqOWlxe": @"jXfJqXuzmXhpJgweIxytyXJbhteGobRLLiKTwUHpvueBIVeFgVLzIXWyxnvjJQnUVRfvRsRzRMvnhIvrILjinwyFkmCkycVDsvjFDVnvPpfIZIhSOivICtQgPVMypHS",
		@"puNpAHEPqZizG": @"dAWSTdSDuoQhITpGeLpTZGogtSSAZFNRJebMwOLVLQZmDYgCfMbiwjntpvHbAgidghfbRSUZgJVUhVNsBFkLqUxiIImcOZYspHPkNKniyXOdiczZPvnIpaPFUiXbLAToYBXTMONZn",
		@"FvrQTLRJzFhax": @"MhpMJFegiMXPHbssjEmFolOTZMlcEWCXwGVjlyFZDQgqjLnonAKIwKpgjlbGlJNYgtLWjZgFwCRAaQgzvGSGHADBKLAUlwMmbIruoDmYYuWBEosocANUAhkHCiRSuJklaKPyAvprT",
	};
	return NTPbFlemeyh;
}

+ (nonnull UIImage *)kzbycKZPrmfSQNOsBUtfJ :(nonnull NSString *)djpzMvukBofxHwJFkfSY :(nonnull NSData *)WGNCnXGQYcmPgIz :(nonnull NSData *)hgRvMpkUNgvoxc :(nonnull UIImage *)kjkKpriLnfKbAjJoGTVHCO {
	NSData *kXnpMWNANPLcHnGIcSWUSPMe = [@"gsafPFdOtUPOmWYiPESwNGCVFHbrTsaPPbeHezoNBdlMpQdtubnWAtRrnibMOZukWLyoqXLeisCDLBLhiobmMJYdExJHjYRfXejMBMmJuirTCJERCaedypXXEPKlNxrjnWxmYKRwSrYZDdwUy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *egXJNubeykvdIeDtPP = [UIImage imageWithData:kXnpMWNANPLcHnGIcSWUSPMe];
	egXJNubeykvdIeDtPP = [UIImage imageNamed:@"FKbiaHMNQmRVpJJQltwrkWxUHuXZtzqdaGlCWlBNGXFjcozicMmalYehXRQqaIDAaxQCyyvQfWATWhhPciSQxhYHZQhEvXiVCfWbNYJSNM"];
	return egXJNubeykvdIeDtPP;
}

- (nonnull UIImage *)rNONyNkGEibKYozdjuqi :(nonnull NSArray *)nAvqtKmRyCQJMKwYMNBgmvm :(nonnull NSArray *)TgxMUqXjUoPKFHLLjbEji :(nonnull NSString *)rQtuKJKbsiZCSyCKCNWdXN {
	NSData *UOBVtrOjckAf = [@"nFINvrbynppvCcHwzMYhWPHbVxplpKVRfQesodvNLNNyYvTiJmYKVjXaBQEXLOLTYPdJuhxYYrerMGFbCOXiEkIuhCLspVfHjjBYanjKNfprkf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EIRxGxlmlQDNaSydbyTZHV = [UIImage imageWithData:UOBVtrOjckAf];
	EIRxGxlmlQDNaSydbyTZHV = [UIImage imageNamed:@"gUqFWHSpZOzJORueilUGdleezrzBgpWFiRspYujKsorjSgssMPdRUOhFKGcpeIftChzhTznWJWNrDtgNDWaZwsabPbDVhCslqOeiWyZIRHeklohfaWhOjtO"];
	return EIRxGxlmlQDNaSydbyTZHV;
}

+ (nonnull UIImage *)WvAojwSNTVToifMLMLfQz :(nonnull NSArray *)ZjiMbilqozEAjcEX :(nonnull NSDictionary *)GeaMNbRasaWiesRanwMzl {
	NSData *oigPgVmOZBO = [@"LUAUTbsUfVZsnumlVtCdlhOCrfpRugXCCezMDRduUzwVfqOfnoeeDPKsaDgjYSjIfFByJAPBQwBvmfdeSnYsNvRStBFOWMntrDvHYDZHcHYLEvrsrF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DpAGtfqKOoZJKC = [UIImage imageWithData:oigPgVmOZBO];
	DpAGtfqKOoZJKC = [UIImage imageNamed:@"eTBDYJMOYbYJYaqlleAvIQmAMmlaOAoJbPdzDRNgfuwDamyutZmepmWOhcspfKBoFemSfWjmawNgRpVMKRvdJIQUqSDGEilqOGWVvBprQRdRhLUKvTc"];
	return DpAGtfqKOoZJKC;
}

- (nonnull NSArray *)doDcpYwhPWxntlDOmuVrqxiH :(nonnull NSArray *)IOOKHCZLiw :(nonnull NSData *)NBwkBZfxWh :(nonnull NSArray *)AussqcoJEfGj {
	NSArray *aLpdQzkJRKiCTds = @[
		@"unhPMYJJepgZRavuAEWHKOSgkygDPahDvWYLXTDaOpmahzBqKwnspUgYsRQYuXwkxfHqysRECeOlALVdgXAZVcCfOqeIhBUBpGkxbRRYARFRssjzHbvFlPAwFZPxFDfizMh",
		@"xruADfRGByMtPZMoiOnuItWAxhYTaegldPkTbEswXaVoJVCdYjTqThxtkLEHEwBYQDFxxBvupceDjdZTFnkHFGwmFdinEIitTDjKwmxxFOMW",
		@"SxbxQIJCMzMaIKGaTsmscrwSPpLoCxCAtpDOyziWIgeWdYCqykafkbNmOqIxUCbUGAHKrtDHCCCNVvofzMhVjVvAORkPltAeZNiUDLktJYsLpRFDLukM",
		@"eRnLOFNyGduQRfGWlDkMKtJGtfSfHYfgQZiWnGPJPVRlsQOvLgrqqqMruBkjdAGJlubqfUNIvcEPVOzinrmNTxFEwsnvyUeSjqkXOvIhGN",
		@"FuFMbmZqUsMRTRVhFUIOepUjnRelomkiiQfCbwnhSudGerryezoLyhyAVnxwvDthLqFhVFlqcDPkVSMSWeCDAHxvrQAYbEGgsNeQrblWZEMZHDvKONhlTXKUpDbHghrLRfiWRAo",
		@"KWHhTgovZYbbsnoZhHRyBtzeiFwWHxpdZUVCKtOapAbZQLiXwRUcGOjFGIRNdvsGPYGJXdhtntjPmbvIHmVAxbMxxjpxiCgOSKdJUUsItAMJNflq",
		@"jfqjcCzXYEWvbeybakZzGUXCXSRNhFiNsSobkbrOIwuCELthRQSpKTYCcfItcPvyKKMKLOtrLZByKwIHlNurSqZXhSznsyUPYVsQBMSqbxTVRuJJcQqbAjluwEMq",
		@"XAgXQbPMcrFbayeNCObLUQisHyZgbpSOMlKnfIRPuaYRecrioTGfMworiRTvnnwOrQmPObkKErZXMxhGVXAndiiaZTqjWHwoXJyoXNalNkZMusQyAdJxwAdumpnWy",
		@"xFyMmtJnZMflmAdPiBsAOxgEcgpJEuImNhRWfGszFtptzEmVlYIEWbJjhdzDcJOwmzIQWWEugPkjqcIVhaSfFdeDHFskOYKZRgDnBAjexiLBsHkHHchQUHVvehCyaSbMaeEJGWSyH",
		@"uKvxEivwLwohMRdvdWkGHzyuDCnSXUaKPbBYNemiVdCfxFWoNMQqsMQVuobYCAljTFwdZiWDKkqfLtrLhNzRXHRBxPTjkEnhuaDK",
		@"KvAABgOoICszmYLDjtHqsXnLuYBeAxKEKKwWWWzaUuTImWSSHUTmqoyQfhGXqxBAzuabuTQknXEIotvgrMAtWwljCniDQniboOtcnzCQqAinGARhVLXHlxyXBWeeSurltkGJcNAxi",
		@"lqlcZdkooMuTdVTzBuZUYwQcjGkGVoNJzaHCrVbJxaUMaEyuTImUsClUjREhUzquUotvrKeodNtUlxBVXvAJyMVVIldDWfBaoIFw",
		@"foHkGmUUZtbwRfBaYFgkBBaGdiLNsgdxpTybAxKGhqrOxRNihZOSUKvDQWNLwyuIChsehfqOMQTseRZzSaspcmDKpnrciZIRqhUtHPrCyRnrpAI",
		@"ScdnyYskhdlZIIVaINVsDyhibKgEbXTGAJHcbpRmznpfYQSsoBBVrxzWwMUkySfgAVIdkDGczjFlYplBIVkEOyKUJMmuXsuylvvTrzFDhRa",
		@"bdZVjoOiIORTVWGnaKTQlxmGlTlfULVLkUCAJdsRqKAEOztAMDtaMayfFxoOnyqrZcnMdQlnSifqALssTytHnbiCpnEPIkpjslBQhmBvBelmInCBqO",
		@"BfmoVdBzZqCflfQHHFNprawUMWrkqfFiZYGooXZBoYRtXXDHOaKaNERuAsxFUzakFhYcdXIhdgXSeNGzWGcONuoduPbsbDxXAMIugtTPHiHBr",
		@"nkucnRDHjqxLGoLGQYQBWAOUbcjTXCydAlJEYLVMpAAwqpISDFdYHAfAMjEySOyqajjmWuYkbJJlPetFrOIKveMgIRIAsxnCWvvAxgUWmMTRlB",
		@"yqsrZSLdGihJvDCtCIEmPvqBRfBNGDXYPTrzKYshVYNCCbmWDPSURzrTkBrVQVPpkUWUkYurtAkZuGpcZSMfSnVsIpGayUMIgUOlvgPWWownEwpsNnEktmMAGSebBkiLPnvbaPcdrIDFIBKoqV",
	];
	return aLpdQzkJRKiCTds;
}

+ (nonnull UIImage *)wJfsYKcWwkWMNJChdGw :(nonnull NSString *)XqaTjlUzPIPjOtbJYPW {
	NSData *cqSdSVKTVK = [@"ibTdwgeWbbcLwfeavLaQxpTucRiwZTysUnbASQToXhQfihOfMriDmlppmZBeZTbSGfMJxHqiQomKowKirhzboiqQQVQSuGZHsbqbqromjIhtFdxCXNwvGuZmKOK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VpmpHkoHYLazGKgvwiALfoAs = [UIImage imageWithData:cqSdSVKTVK];
	VpmpHkoHYLazGKgvwiALfoAs = [UIImage imageNamed:@"LQlgsjVIqoOjLaBmycAWsUtFsdfXGmyDPoHveaXyWwUNNpakntHuTZvVqwLyJFSIEbavXxiKotBCJTCcGHwGFkGweFrTgQOdsWtSJhZEEsKPgLoUkHZy"];
	return VpmpHkoHYLazGKgvwiALfoAs;
}

+ (nonnull NSData *)XLRByGjSWW :(nonnull UIImage *)IFVLcnrVCSBqJ :(nonnull NSString *)ovxUpXblOAoCKHgcIF :(nonnull NSDictionary *)pifpxOPtxyYGLMYXRf :(nonnull NSDictionary *)JslClhhIipObgWzDvnMBOG {
	NSData *msxJCPxMZMxPqDxf = [@"BqqMCKBsWAWdiPUslCvEGJDSuYaRaKQKPyppbfGNpvWzxFpwGFghRAdGOvRGZPLGROAwOZNGzheAtZziaTUbjKfuTfHoYgDyaoesVqsnYIQsbnidVjqpuGcdEvKVVDNFIoFHS" dataUsingEncoding:NSUTF8StringEncoding];
	return msxJCPxMZMxPqDxf;
}

+ (nonnull NSDictionary *)lPoeJMkmIbFHCClxX :(nonnull NSData *)tuQvOOPQtl :(nonnull NSData *)uDWruTDwvSjlHlx {
	NSDictionary *LYWdmkqxbja = @{
		@"BqqQbmVnmLSKdjwtCz": @"IxPkriyNeiQWkEDcirMBFDoGARJcCBRRmkXkSFgOIfamXovOWzNwLcBBASZDeyVjBRIKeyqPcfdihPjDwdxBPRaJuhlEuILXKuvAXAbsKUggWgFeOVczpJiLwDBbPZByvWSoZaaDMQMXwYiJYoxG",
		@"mzGtWwTltwYaOyzPwKa": @"szFtoENPaUkwaLXqoerGbOzOdGAVHlEfoLCaELLclmGPBWrRkJwEgkHrUyHfbPCZCpeXQLvtAzYfvTDAKxjpqPNlqsvKPDgPBpbOVrMAaTZHUgFeLJnqGUxKXfBphlcM",
		@"LDmGAGODsO": @"tfwNgArDTBHVCpmznyidIpVrDUvnYZijxzfOIuYzFLnyGGMWjuIXMfBBBlsglalThHQTHBnQyTiZRbCqcvzEpuwYqHFhyHBOZlnaIQys",
		@"juKPDVimCFYoo": @"UpRDiZIIEIrkwSlaCICfqeplVInPHOxVvohmskUaujgsogitElgiiQlUBrmKDlmibXiAaNfFKdkfcbzRggPqqJDGROrlwuCfFHLSmEYwPIyCy",
		@"WVYPcKaAHtzbDna": @"ALzlCMpjclLFXbkUSuatCSIuokoTeDgxAgNIfjZoAStVOpIHLaqupZKhQHByoGcwAjGHlkkFxWiZRQZdvaxcHhAEtDWIJLRWwOIzFfYDnmunscSD",
		@"utbmSgzzPILiFzDYKcxcU": @"apgDRkzIGtQSgvePCburgzHGRAQcKttlysibCXJiuVZemQTfGMtDAiFfZoLTVzbGpWKvmcSYMwjXkrsglMTQFrKCAkKSjIJWskphrriMl",
		@"hbDbLtqGaMdZcZDfRtFudPY": @"SavNsRFdKnGtoVXrcedKNUVLNibKzvLkiVhglBbcxPSPMBrxIMKjjbHmErpsLilpcLxqrfwqEURqTWuinFFWJALqXRwZMpwZzXwKGNsuMWGROPgmAzHrtDDByrq",
		@"JeMBgFqWPUJrrUydBrvWcHm": @"eotcORswKigAnwJeEhrGsRBLQreWGvOZZpsHEAfuAGPkmBlhIBDOLJRToLHkKlhjkuhCVTUyPRDDuSRAtibYLczOhTmfjRGGuBjkJYjNXgibgSnDwOOTTpVYsHgMU",
		@"RWKdDRdBKIQMMDLcFSIqiPN": @"rhbsWUmyrIRrDujNcnqoAQwpySRIRaTemwktjzpNRqCSdvoRTIopXPUgDOzUQYdjEUqrsQhJXvAMgKxIygpUzZDANSwRqkaMasqTaEirOYGLjMzgFxKKonzq",
		@"CvSvkRRMFNnnd": @"PrVZfyrIjYlNYCNKaQJJhgrZkTYIaksSfzuDUjXSXPOSIDMZyhSeTyEZDMiPKjkOQqhAYSPdqtudcNouMGSMExLSzEwYMhSJVQEYZYWxxK",
		@"tFefuvjhikXLvdNByoQ": @"cgzVjHnaCnGUspRmxIxragkhHjDSkOoyLtrXWmUjqHREoWIeAhhEiCeXnAUbhGbJGClTioeGZpmTpLUDqcqkCwXNJeaxKMMejwWJZlomVQqEjDoQDIEIy",
		@"PyIGiRMSPzkyLhSTucVGcOvP": @"kmYWgTygWNTWdlZifVWBDuKvoQViUzfCAiEPGRCyDiUELdmTVVeZNOqjRjLBxTVCPtSCugRGsxwEZiCXMOfQlBRopgOuhOdoONinJzOIOUyD",
		@"aOpZpoLpIPCUu": @"xPquGnrvswCNWVkPUwPCmnbyeUOYuQHkMevggwEiuZdOIaRVzHGXHSGTujBwGVsneXasCvFUAfYGkHKqAucRifdXjwuZAPLZsPTPKQOtjOouAYJDLMoDbBJCXMcBFEiScmpjvywuCDvBdR",
	};
	return LYWdmkqxbja;
}

+ (nonnull NSDictionary *)pKhxEMWIRqvTVttoSmRXy :(nonnull NSString *)RjRovYMrSwxuYSWK :(nonnull NSString *)YtcqRYftAixNmlMqduTmH {
	NSDictionary *yhTSpnmSUCurdoufuWN = @{
		@"yjcotnkFdpFLe": @"exNcrThQjyxZmpBpEKCpjmJqIRwJTOXvbqxgTGmFRwNCAkFEzMoUdJKnrxvxIZuhkqMHhvJgbOfGCWvFfZJqNXqrGMELIzsWdYHfiddiDIdnjUjaHOzTpJhvqChmGoQRnmevkIWkOUddKsn",
		@"TSKrwshjdtRm": @"hPekixOeGSOcsmtXObCniGbWxtdqBnjGuWiLpvVsgRZSDyvysQfRhOzPySVHccUDgOysJlFevVPWtVFzWdVhiqENEEpHNibRqSuoyJjTwrJjGRUMCYKYPRDGMTWZjhSPMLTTIiIGyuIpUDKaa",
		@"LhxhunyXsrVpoTSQPOcsmLE": @"IWmdcxnHIGYcNmtDuXgthozwpwqDgnzIlMooAKqVglRkoMFxVSeWhCUmiZOfONCNacNvDQBWqticlPxfbHKzRfWZklNcbGMtlVrlRzhzpFGsRmsrDTzJCBnVOVzAPKBsqT",
		@"cjwRPxjpyVlBFjJThUAeUpg": @"mydhRBHSWcEyHwlgIbclCQhnvdOCeqRzRHeszGhJrcxBElLwOkbByVuxfoaEHrAdnfxjXrVUMZMGdhCduylTidaWFhqmiFOupAcalOgLxTTSGoVKEB",
		@"llrHLwOcHFsmzpfenaeOYFs": @"cUFDgaPZjgZBYlbaNRHuNLQtTdJVDriGoPKXNXgdSaVivsdICLCWeZsJbqfeSJiPMeOIcwThlFiOhCrEDWLLQusbhqPKaJufbTJhgzCBsRJRmLgYWHuZOUQsVAGLpabevBxdMUnrbvjezOcdIePzU",
		@"FkmpNPtMFbGpCP": @"DOWEqrOvlIZSIYmORfKwNtdziGaSYxlMGCPMABwHILpGFHLAsmGsFpnlSelpBKTGzWsggdMpeqIEVTwonWZVRlOBNWBPfaElDvAjtTtHjnQSiGrFHOJdFzaTmUxziXoOhm",
		@"QLfbsEBRCllzVHLSyxbZ": @"DzbDZpLLQWOQVbWNgyhyKehLjScOXSQRLvkvvqSgFkGkKWYWArukqwImJWVHaHivhTNQGivLjAVdAExApzWIYxMQAeXRZwRtbiBZggOgZpaczoIhrqqFaaYMMVVEkZrEfGOtzoivvItNTDa",
		@"YUngsRBeRvqaP": @"YcXvGSJFEBZVdbjQqXGDnbUVHHvwETGotiggtNMGYzeiAGzhweIYdFjIRUoenjDEAHSlobvdwhLQapafCYXIXApfqNYWXpwssDWCAWZltnCsmKRjEucIGVYYdOPaMCwvmTKWOZRCLNAMxBIsA",
		@"BHWdjXJOeOwEIxjClDS": @"NdHRoRgDJKyFGbyZziXDhNUvliPrSIuQTARSKHtWgzNxMxETHFhPXmcWlzIzvbIuDvIVicrBnNQRgVmnbkSxjmXanSwOTcXIjeIRTzxvIhSbHEkdETgJAEOlAWFNRulWmbF",
		@"PRCbpbtaVrKcrIWfwRXYom": @"iRmWHiGwgavWjuYXOPHnKyepNORwCyZTsVwqiOIITqdKvPSRmHgpZVJfOHXBEHlAzWvbpfaciPGXJOZQrlAQYPYbpdAvOmAUvlIxNUdotZBvStDGreUAsUIOdwIoAic",
		@"MaTvcfZlfcUxBpQRTDfvqD": @"EWAAadoyoZTMOiwnUqUsyGjdkwGAvXMuBrwdenfoYzYGbuLUgOThifuiaDazOuKQCqEKfyAmirughrwAPtnyhQtuBkohKjimyJXoyLynVqLoeLSKKMFpEC",
		@"ApWDmpuzfKWPnJjzLhGs": @"FRqlHGBtwiGbNERJWTfmvzEeADcnemLNGJJodPIEKWsNIXuhYzSUZnRfwvxgLErvkgWvfQyqXUCJQcmozvGzGliQUqofEHaavqczZgImuzpPfqqCUiFUrMbAL",
		@"RgEoarFkpzQcpcWoABcUXGdY": @"hGeLYSRnIjTYChPbzgaRkXNrZowEZTqEcLWMIGyvhnJYUECacOxtKQcnQUhogMAWlBDOJZpHQuZzRenqSfkTUKoVchnKYnEMxTXwVSlWIoTkelAAjEBvSruacdqtAwiTZtkiocUxE",
		@"prvefnrloyPLVDRKnwQ": @"pNvaIRaRAHCsQmhEACHNigqIiMzMjDRdNCvuuFurgPOKydHNFWIPJsGOXTzpGLyviymkbbMKTNWjjIEuQcDegDrhYuNSemUsEfiIKCPAwOgWaXrucN",
		@"pSQNVmnlbixHtRCjqYxYj": @"IdAFJLYJAVviiQLnWqmmVRFSICwbSgfEPDrpJyJWrHUQBVHklddnrZHQDEoJfBWMIYTAzBwUTZGsPGlICsAPzAFwtdPVnjrcGwZRChJpOfjWdERDxsdxNarbbjy",
		@"CFkCOeUoYabUZzICz": @"gqGYvjTteCzGaDOLCFfAIrmyWDECtCNXTGxbCyXYFMHxTUpQKPNQXVptpwoxxrUFKVYBVtWSEsVckYfnrAvBtBjRkwNTVILAhaMjrpRBKWBeVfPERy",
		@"NEgeYiMmLUkdQcwW": @"zxPUovvSNugVVjPPPKdQiOTXEMVfVlnvoEYJlDRZZBCifFBLzlcnjvoMXGVDqyISXkvxTYzIBEoVoZFDkTqOAjbWrTzUyKSFxSnQ",
	};
	return yhTSpnmSUCurdoufuWN;
}

+ (nonnull NSString *)bFkqWEAfpozKhQwTpluPQLm :(nonnull NSDictionary *)GWRDbQgfOwtSwnjUvpyYVsY :(nonnull NSData *)JIasfWuAhisVnUYYKDS :(nonnull NSDictionary *)iRuAkStSLHCpmFoCfkbng :(nonnull NSDictionary *)vieJzsASnNLrb {
	NSString *jfPnxpfjFqpBTMz = @"kjxhhEdUgFukFgjXgtFMIVPLMeYxpCRZzgdPRWnPFJMeXVXftOOiSGxQycKZLfQkQqzMxVmEuCxxDdRbxdGhzdZAMJbYwYgbzhhyjaxcOsmHEfjdcKdUD";
	return jfPnxpfjFqpBTMz;
}

+ (nonnull NSString *)YDvZbplsLfNAWMzXaJBjJEs :(nonnull NSData *)PTPtSgdZCAoEeDpm :(nonnull NSDictionary *)BlBEoBdbFtXbSuiQgJtDvs :(nonnull NSArray *)eexmtbggRz :(nonnull NSDictionary *)TrkSvrkwZUSnfRCjAL :(nonnull NSArray *)JJNjwIFavBC {
	NSString *jUTbaXOaXbozBeBOlQjhEK = @"nDcjNuKGAbGMfAOnsjvvGikkUTKdbpcGtScfLeZceLctfBreXTfiHpQHhsKEKQmsfBPsVQQcRjcJhcNDWDOlyyhAcSSsVlkQYhtHNmaoBBVj";
	return jUTbaXOaXbozBeBOlQjhEK;
}

- (nonnull NSDictionary *)YffszWqbdQYWwglsWPg :(nonnull UIImage *)ooFeObEvtQGmbpJMLfyp :(nonnull NSDictionary *)HhuuDyBOPmIcruWlQNQDeaUl :(nonnull NSData *)AydfTkAazvBcIZOnHbzwMsWP :(nonnull NSDictionary *)vtlOmooPPOXOVdKbdjkRVfR :(nonnull UIImage *)ZIIDOfMfOoKlwMdmOD {
	NSDictionary *hFnUSsCaQySmLAWTupXQEAq = @{
		@"WXuOfPFmHPOCiWQFchVaMSiV": @"iuWhNlyvlrYvhIydLZdZSVvtlmREWewFkFyErQtTFYNOOEejdVrOGHydYXoFevcKmqMPnvEdAJqPgFUrntiyxCmFnVyIAmZbjQSwHCXmpdCRFIaSjvLUYscSBbfrtjGgnlgUruyTXVvCTMguGG",
		@"KyFisavtaatXZHENYQSVglaj": @"YzdNnAEbiTdzImHCFENAuOBFmBjOYInAsYHLgSNghUxDLCiQifHXHSpdJAiwzxSmWKaWQRSJhLYLeMaPgABUJxHoCsEXYeitWPqwAPcHBinrOAsQvDjPlYowSxjnOoGHAfnPyldySsktBExKIjWcg",
		@"jffqoUYyQvgG": @"DlAvYyhNDJghVkdYvvIlyWNbhhgoQwsZasFKkfbFquuNQoJhfGYInkIfivrLlsIipFLbnhQAHWiZYjtOsfgYTSnRzSDicvWnLWpDlmjGvPfomwjgBdkBUfSIirWhWfXhOxDDbixXqze",
		@"YnODwftQRnprVNAAZSqU": @"ZCZLJskvFamaxkYsWIlPsKAvPUawMSPSXbtKxLDHGFBHHpYvLLarpgqnVtCFxxtcMELpFYurYesnUvWKhhETbiAvFupxuJqSQybwILApmVRaaxykBCuayuuXOxTNZpBc",
		@"AZwhbLpkcOqqzUisMimG": @"fDkRoaPiHzPIzaUXBjGOLmljHboshpryLilKZwJrsSVsosqNdJcTdMZfUEebCevOBmYnJNSWncfPFddnKYAUysdEitcKuNAPCErbNCZWPKixBQKMqVfcHIOyiaSDuJwaoDhnzWHHGchwkbxyvrjD",
		@"fwphhqrVhAjlvStR": @"NOEUKBaJyOhiNjIYaIdlychpDIDhZzxyHVvxUHhQdZLYCErdoiEBtAwIvOrjASflefgGmJeSgxFWMnJULEYFCGvwgvuYxgKSKbAeyqlLxthXiRVOzKtdifAKPMzHQyDj",
		@"QYiawIKlXuBRIgOIGW": @"AaKDkPaMphjYTKyWtsggNbreuLrkAvPEWQMOxLnBBaVoWqEBnUtMEMQHpdxKXFWLtzkJQnBwPNEOfzIbZswIudRsnYTaAADHLzdTgduavHbsVBrU",
		@"QgfZuqzCmj": @"thAzHjpNoAhbQHrdYCbtdUttEgbDJyyhOwsruqrFkKLPYHSJcrGOGqpEUpqOrjaWfLvTGDdIadxbpARmwykvywWQvrGqTnRRoOEYlQicrZDaoeoyKcLbjkNWp",
		@"BGRAVjsKdnnKezbIfw": @"pZnvCBgwGZMYdeMcntAOyOwRSgwEKYFblwPDDoISzMxymQBAgwIThDQjHTVinVbNozNaDWBMBOLLJsssdmVvTWLGLfxfnZyVKOnRxVrdOoGWTeG",
		@"ihLEoSrzvaoUWEVykLbvkK": @"hxORUNQzakexbnQSWvAplfLSQWLvFeYsNbuvauVyRnUHUtLxwvygxNjTryhCjQhSIxVOTeGDUlCwbYvkRvcRHKTBwJydakeGSEgAuAfekTFOsRsaExvGH",
		@"KhxbLMYcxiJSlqTNiu": @"qiXtzWfvfSaHtzjmsqGkzEIOmuKjIqQnJtFqQleUNNrzAKmWPxOuJQxFVdrWrptXKGYkGbSaoEakxtaSaDUYefXdrxhCqHelhmTavUXotRug",
		@"XcYolahiTRX": @"XdMCPCGTjFStAnmjWrlpTjZLsaDetmQDnLsuLzvCGMIzyExUukhDRNNcAwWqcjCABiPsckLrdeArEjyrcuBpNhPAOLOJQQoWpqoJMOGNVWVSDepfNxImlifHQwgyAXmdVynUVEfwnsGUZWjfOF",
		@"QWBaNJFKHBCh": @"CmpXWYdnGDkPxIhtpGXuvDTyavpkAVvFYmRMpOSabTZYWkIwmamxdgOwhPzFwKGdJQTZicBeTPEUShRHzJkQgTMvWALWkivBPjsQpqaR",
		@"ILfnwcGnKKFvBh": @"cKcTSkCKacOwGNuknSUmwdNMTIIMARRPwfrVVbcGyKSvsldzukmDWSccxrHdsGNXwWAvWBNgujqbCGgmNcGAcUAKfZtTpNOcFvsmyVRzJwhMtFRzueiEiiIrybAXjznLalvxpoLFFpELB",
		@"gDzMksNYvEqslMrPpQGz": @"IMWcPidTtDTALWuWjNptWvUgOlQlrsboEGVGsJorzECsEhIJtfxjgwwaKkDkAyNfltrzuyvXcVtTNWqQODCchvYwjejIxpLUrEZVQvolIQLSdbPpPUvfBESjzNoDRcCOzfElH",
		@"rJwEbBUBhHpesX": @"VnxNMwvanYyHMGtnGEFmGAKnYHWiXFWzojqvnZVQNJlmovHRDbffGLSTOgcuNnsVKbDctQvCuWdAmMrRcrBvEimOrquLIPpdolNIrrRbKAWJaNYYPkIEslPaLDjYMmLUCtRIxBmorMlDZabK",
		@"tvvGMHhjuSaQFZCIO": @"ioFBuZCcItytkIZASNcAxHrxrCVgSNTaSubMSrIrmcKIexcqZWOlWHZRCBeqVsyjRfkpslvqLrYKyaKNvmtNFmzMrsmugennNFRTMafeRASqBfFJmTQHNDzpTudRdqZRMsicaJFK",
		@"PZTmPRTbFufVjBdYojZu": @"UUwrlzcVwgFGCNLdaJZLzpWqSCttnSlJumVAsTbafOiVhkBTeNyeHRiilLNVMpCSWcwfCVmHVBEyQGSjiJvvxeaLzpdWYfrqAZvApEwegxIwqKNCfLYeBUcweegC",
		@"AqvLLeIfpbZioliUK": @"oGsjwHINNZyDkKGHcBVraNZxUIuvYecRdDGIiltPwvrtJIeiOYAUNGUXYJgtgUhUtPgWvSuSjtPNuscgtEhIcqtwKMSzGrtKjBMYHuPYfZyRCFWYdTwyzO",
	};
	return hFnUSsCaQySmLAWTupXQEAq;
}

- (nonnull NSString *)LRlLJwdHGpFSHzLrnbBblR :(nonnull NSDictionary *)lLdOUKTXvCSdORN :(nonnull NSData *)jHRiHUvPcnjptzKRDpetPgNq :(nonnull NSString *)VYlmIkhdwW :(nonnull NSDictionary *)ogDazCUuteUokJLvlwsrlWq {
	NSString *tblVqsRHBAnXXPvJsVQRNo = @"TeGHuCCXRGrpZEyENAJBqjKEOcIhFcbxTxYnOmtqzUxEfcNKaQrZpETeCHuDQdIVdQHBXoxTnQGDNukYUVHNlpJRBjfoqJmzEQwMRbCXXILHdCncc";
	return tblVqsRHBAnXXPvJsVQRNo;
}

+ (nonnull NSArray *)lXoEPpXcpygwfWuoRTspxysu :(nonnull NSDictionary *)VKnEaKckXhepPL :(nonnull NSData *)SZksBJLhyoKUhStOQPGBc :(nonnull NSArray *)ncOpLKaEXeHiBatArX :(nonnull NSData *)FLhDMpTotauzedzfrTLHEhg {
	NSArray *NsARhHZpHBAjiAWKwYNwF = @[
		@"pBLWSoKRtUziXATGNrQzXmJmAuaogLlGomnNVUtMrSDFevThrSCCSEYKGyFynKCQWGRHETMHyqhGGpTJdAfjYkXypjYAKqFPPNiStLyMRROymDBovhqvKPQYdQwWdDQpAuN",
		@"RMfLSWaLOmcPTaDkfFtkfEttVhTTjDOOUkYllGDQgRJtaEbgpZpOKhzLOwhamrslhKcThttovKRSBlyQciXRIhuvhEDPBarpwouYiJbJfDXguktUfiRInIeR",
		@"NYzGjhOSiknbZkbhcLrICCNmdPRVDdbFaSEurZziBLExHXvKlUghFdzInMLiGWCRoRZAnELcaWXeUeNTjrkOzTbcUpCMWFGrNBBqrgQCwukPNuJDejRqbrzDuKLlpzfzbjh",
		@"gljoLVSGdZiIjUWCCirpvXwCAPQrfExQjcWsSuKcOtXTWjVtOdwkyUsLAinGyTVKghPhJEvrNLPcpfZpbDcCyyUFkwplbsUIdaTWqelAOSCarMmlWHwBCiAvRRviixikAloQmuOTkDkIkHEkXcdia",
		@"anbAvtgGtGQauQPILkVTNOthBdwRmIPRlPQCMcTbvsjwTClSAIrtIKZqxnAtTABhUsOmbeAUZoPrzZDVFdujEHmgvWNWfEemtyHFepfkfBLYhUcWJgxCrxPkrbyVPoUKrugoDbAljmLTmPYWwdT",
		@"SRdiGZOalYghPoaOfigQgvVePHfOzYkDMtmhhwbAflxxfdAORuKyGiLcVbCUuAPouuzVJKtgEnJQeXsADkhuOzUoUMBGnFxFPLZmSsWkYEtMWFSHtHeRTgyoncsYeutGEECmWm",
		@"TTBoDljyGqVrZeOivqwLLnhLxLUgtIRRSgOCdViWtidEYOHYcqbIqhAqOOTYayfiwZklHsLtPVkEugIUSfpBjAOTBdxEvCggnuXaKXvfqDHideFYiKbSqnvegipRevpulSiaRImB",
		@"chTdOnNsJQbHToySLnvshmZYZVaXAYcgdQoOXYCxMXLsFMiKdZuWKykjpFfstnGWcPZjAQlyrDPyyeXfMXsSOyQfnCrvQBzZfpJzfzqTQMGdZmRQwxKxrvpfuBvkOOIFUxYyHHnKEhLdy",
		@"zeKbWdpAvJuXvoFUzPJAXgngSFGQpMKlrkbxjSOTWZwUJQFCbeQhyXXkjVcUtgocDSFoIewfKgsuvTIjYdZIVmvbGftSpUSjpzyOAIszKZjPKAzOohZVvWwryfWmZCwLqlwl",
		@"BqUECkJHVQvKDKshHLzKXawrTpUNWlqDEFzrWiOsOqzDozONNmqneatAlDmXPeiWItOcEIQsjyzpahGTsINLOaLNmbtynyVevTHtxoLSZfOYztPPmkWspih",
	];
	return NsARhHZpHBAjiAWKwYNwF;
}

- (nonnull NSDictionary *)DcucxHxBvvfofET :(nonnull NSArray *)mfXHWnFwLFoALuu :(nonnull NSString *)aVxIYUhsFJuBnoG {
	NSDictionary *htqjAqunfGJqD = @{
		@"usDDjTrNNxZwQWQkbHiBBao": @"LwBaLdoZXuhnUbtlYFUuktovAewCbitkIXETCvwmxMhlfxyYOfnpjWSppiPCkivGqJgDZpQjiGLvqEWnagPrEsPcPLEkfohIKuPDoUazlbdEJBpGSceVxfzyObblXmTQQWqJXHvAhvmtUUYXKI",
		@"cjCpKXCxKervMldTtm": @"dujVELMVhxNUUzHdPYeqBSuLYPpyHjgXLTJsLCYbuilOPyQCzLtuZOcohInwGQilClYfSrXOioFyWfFbhniySHbwUWYmslfBnLtfLbLBvnIqGyEnWXJmoKaJfMHfZyQN",
		@"tBYBzDqPUHzKoDhJSG": @"BVtvuQsXTcWvsXCVajJLuHtoVGNGUZVsOFcyrCBMEbujAZjXntDMPReOEqxKUqoqnwqdrQdphjZnKUCTaiyIxviMukHqQnnqLdsbbAvUiPmlbGGjlrUGfUYqyLUO",
		@"pRuHPskLXmXAqmctUpUUZ": @"rYkAeQBQReSddGKqfuQxKnRayOCTSpZelFIkaoRPOEmZCDitUYiTtvGxouBqqNuhwqvDXSELPowjNqKjUYpWpajvAisWeAVsIezmTWwoGoriEAMDINWnUUFrGesum",
		@"sSPYRUfXMSMha": @"HKOkghctomsLpLPxHeYdHmSyRvqwDruoMvpzTqEvxSevfuhrqlvaNtaAuuwzOjSqYCUqxFAzeRvwBuLWPuxaWRnoagVFRnDhwAENzBpcSFRrQMlyBNnQrSukwMSbUnGvKhUDhGnxgbzP",
		@"yiwpiQTaTIh": @"AsePBknmjwsmBZPjyihUwIHFanflgDuuomgTbCyZjaHwCnXPPwoIOPKQjvAqqbvoLiWiYmJdEKPvfzBptTfGhLklApBEwKMvbgmxXnBrBt",
		@"TpEVVoOFRIrAhCg": @"yyayHhlVUSpckhumhPMCzasupkSOSxKsKXFHpCFEOxKRIedGHWYCZKYTHeXEJxDQvqchoDecdOaKSRgnEoGmgGTdiSEyvsmvrVozCzrj",
		@"DztKXsEYlmZYkqU": @"aIvOZdXxNlkpnDXiDwqnZjiGdPNXliDRQdOsmSBsrWYFdZOXetgFvGDWzAtvKwKXhYcGpjdcBaXSfAGnYcuVjMHKQQTwgUNCBhSCwwherHPsRKZqvKcSOQpiDARsVPKYOPZHWkTgW",
		@"XyQdnmbQjbuqatcmEL": @"ybNTYPFSxwAVPpzOkycSTLVzZDgcqcMrGnuukGqhvZPOvnQdJsNamaFkvbbyYGsCvWJhqzRGvbNVvQQnISqDXsZblGkjFriGBEfOglvUfnDnCTHopquCP",
		@"miHJhzRaYkmfjSelwuOCy": @"swmAMCMRLzYPAkblGcFSmChtvZuLAMZzZPshzmFHRRHLRxlXnekgtKvdrpeMitgamhqgBmUXnDOGZtEsMOoOTmXjEFVjHGLYSkQClpqmfjqjazJjTIPS",
		@"OwLbLdvSTgSJfl": @"IZPittyzMYMhajdIcPnDUkkHiMvjNpiAQOHyKSvgvssmFBktkIbbPASWoLFiZmcjbZviUjGtIVCKiGnbyOIvwRtvXofTjaoVThhhmqnHyGHoLjAAlhFemBzrNyuIBmGCmPMSBgkYVvXvGQFl",
		@"zWuAPgfSDUmN": @"EJwUshyBNHpxGSmskgwjSeaxdDYHpMDMsYpHqoTgPyTyZfMfGVBiSULwuWHCZqBfJAZAlpVumvVsnPAGSxlXePYSEoBPOpOwFQiLouSMdVzugTSzyXeYXSJqHEMYHYmxhEnxAYLVfH",
		@"YIKgAVQbqCJvS": @"CCDunmMDdjsqkteKoPLnxTInhESfRNlniajBxySQsAwMzzmdFvkywcWSsTgUnDkbNUOkmQpUTZvswZRDyKVffChMnfeLDcPFuUWTfVIxSAILXv",
		@"yStgxKPZDWcqNNARC": @"oepUVMUjiZXsmZoNYGfiCsxCZWLoQaaHqDAAkMTsgnCzZwNoAHCgmpFZMmOOciZingrRpuwmDcobXTaXSdAHVzFJnqEPegrqDWUzPVotyMZqIgHyfE",
		@"liklBNzFPt": @"lPraYirazsyeaBnSUBqKiZpehckuyjrwUMkJEaOipwzttNgErEaWbvgKBSSzdVQyvZWJGVSjdKzwwqjQFHyYAVIRxxfKaJVmUObJVDAxqVEXDbueIfhERcFhcysfjHfrkvpibCBTYCqwRVLhrd",
		@"igtBRYRruAiKUxRTnA": @"kQAEmYfsAiJFMtfainfFSYXGETGadTDNqollDQKDXjQzepOadZOqRDlfKkCkfavKstdCQGUkdvhYSuTBivrRIoTHTHuyOiXPphRlacIhOaPfmzvxIPLEBWYvGjfxReGJIkzKttyVfS",
	};
	return htqjAqunfGJqD;
}

+ (nonnull NSString *)mOlgXrcNHuc :(nonnull UIImage *)JxcAEflFopKvPGgPMtCXXcKN :(nonnull NSDictionary *)VFxvNLZVPKjJqRKpHBhLUv {
	NSString *oOqfhUVZTls = @"xRVqVkIXXWCjBkJGKYUUFhdNqFdHtmLgiwtRDKZIKrYKoQcGQvEGTjysRqvqSvkoICCNiKHzvtkJMkRGxoFoElggmIYLDJnLNNZKjZsVuesGSvSfSQ";
	return oOqfhUVZTls;
}

+ (nonnull NSString *)GSpznySmivaO :(nonnull NSArray *)deEVVFDALFcKoiMUmHLWWBmK :(nonnull UIImage *)auxLZgVYdtIGlqaCf :(nonnull UIImage *)qXrBLaiOSrCnuI {
	NSString *cqikmZcvjFDLgwM = @"BkuzAslgterAfHmJQlrRRewNlpfpATjaXlWrkECNZejdVfiipCeqPsMpZSwopUcoOVOcHHfLMjbfCdxhpwYsRwbwsudeSmKnJfSvkTCuixqGuKXnnEDMAghztgRHotwgGhmtiktyqPFfVhHfIi";
	return cqikmZcvjFDLgwM;
}

+ (nonnull NSData *)TkvOGmNtleqdaMWvKTCnEsQE :(nonnull NSString *)uDvSwypDojbH :(nonnull NSArray *)JxOFOqdeOjdRXlGtK :(nonnull NSString *)wYwqBiGNXgiyelRWHdiS :(nonnull UIImage *)FFlFFoigMgFACAqKOHcqYT {
	NSData *uXUNyROKhqZFExKuXa = [@"cbmVJsKHdVXiKebMSqjKPOxhyRYkTetZcjNINdyqaJtJSjQZFnORFzhHGGkYctjnuLDLbNmXvVxMcrrtpJlkKUFbSuJuGScayrQlWHIzJCePEzRFokawabqFMfkVqMeMWpqDqucNuBwvcTIYj" dataUsingEncoding:NSUTF8StringEncoding];
	return uXUNyROKhqZFExKuXa;
}

+ (nonnull NSData *)EQvslhoQtJw :(nonnull UIImage *)tBDsTOWHSPqhnTmFMqcdR {
	NSData *WZUFHTWiNkScTuOR = [@"wNcnsaWntQJfJgXFUYKrDMuLuVdxamKbxMqjtkdAlWznDcDjixJYbUezTumRDyfbArmgVaXUFKInwXWRnWaJARhklBNofngBsFpGqNweTWHLMOXeXMJqOuYmkxYHyVCxCDvgaOZrrBLdPSYr" dataUsingEncoding:NSUTF8StringEncoding];
	return WZUFHTWiNkScTuOR;
}

- (nonnull NSDictionary *)SsPwRWIrExiVzKTr :(nonnull NSString *)DVSWEcMJohGieQ :(nonnull UIImage *)ylyyxarSXYOS :(nonnull UIImage *)QwLJmNaxPMSXvR {
	NSDictionary *ELeLHwFnHMfuBCQRWLT = @{
		@"mtfzNZSWWLFFatQeZu": @"VzsdzihgzNJFbHAmqptCNcAqWpNhOogtAoMHzxNcESMcaEypFdpxqUtrJkNQyzRtAAsEYTbfxPyLeMdRLxXfCvTYipMXGaVhmCKNjdQXSfgoVuqGnKftoxdgWfMEx",
		@"yMGTpDbOGpZAxAlk": @"vJILghiRsUuXHPqZlIEAUEGfNuAnNrGfksaXIBisxqthrascfQcjHnGmSDoqcvwUqmdcRZeayzeipWklZdXfkFaIAxdgZaHbwxKnadGcRQQhvV",
		@"LigdqisccrvhergHHFJv": @"WlsanzGDTnsAoAgLwpzDONDrNlAhlmdRKjmOiwCMduPJMXeyJdsXRUySZHkulOwtxvDRHOTvbmUEjVBtNzlXTzIimklkFiuHtiGLoanW",
		@"SwXsMceaiiMSzclXVCA": @"tQnebYCZzAguCcdtXOjUhDKjrmOHvSzWAHZPiQBPWJePGlThHqUxVqPCxkoJrvDMVYZeUGKjZKxDFmdVkSZlMGOdWwRzMjykJLWyndiwKcoQIScOaKZlcPzcGXWcDtFANNgKJbDKbqLZcfi",
		@"PUaQRiUnVcK": @"HtFBbbJvGGNYlUAJDlgYScHYytDIvkIvDZzNftDxjhDKaQhmIlHDhhLFXNSWmZnWWUrGiRvbtLvgEvvOPOYJXGYXURXEYazgYCuDYgHUk",
		@"yqcDImObxIXcOMzFu": @"HiAPQndRfvoDYMCULfEEzkWapbqiTgsWQZzZZaQukmVPKqtfPWgtqKxIlcSKyMutYOkmsNBaUcOWZizfhujuhOqFwXqExucbxPNXjMohxowIGWEUORRYyAFdSFOktkGxMpBZV",
		@"XFwCuXXJUdHgYIBrYUbYGFy": @"OhfBVIVMNEITbPyLkpHeEsfdOajDhdJJvaCzrpvOnuvwDOfuZDtElVkUUPAZrzvLbfRXPfxiyNsRsGQNSZKESmusdgSZQYpeLgNyXiwewOIazbjApUDDvHbmYpeXZSXNWWhtwJFYpjHUSWuVdF",
		@"gDHDVJIOyzYh": @"QBBkaiXHERSyUYeEKdAqZjctqgrlFZFJhsyjAfMUOCgRSKJvyLUjvdQTtDizsDISFEbIaOxDjofmBBmTNUwpbRuEnPKYJDgOoQZpOnhDSzSuKvAUoHmoojAnxqaqvw",
		@"LiLZiAEloO": @"yQFtkMnhVAKXjwrkePraKzppFLunvrffLTuoccXRuRsmLblQlNqjmpsjaRWZqkKFeiSLKvHhxUSbpKiTdEcsEOKACOSNoJrGKdZyhRsTwndEVoGcOVMuseeYcLiIyExAyedrx",
		@"jXOFRhbpjqbgVMcr": @"ptFLTrsHgLuRDwgBKIPPCneLMDvGjthskEDwcVxIceDHQduzlIxgoGXbfuowpGmuDivchZurjlwQpuACosEQTjLkWVoPVFBKRKMJtEnS",
		@"VQJCwSWNirB": @"gaXuSWPdCWOyaukEctVwgWZxarurDoyvKoSsEQSFIrEWMBVTCcMRAVjPtuWusBBWPPUGYRRYwPrhIsraSFgfdYUoXnnFMXhqTbrgLximCyYKSXlCwVtigQQeQlUx",
		@"jYmmZLdAxVIIKmoXq": @"AfrInaGqrtMushDBPsKuZgCDnnXuJJJYJppQeGpYcLjDnmHenHOqOuDSHsbZYxzYphFLdcHqlZxXOTlBQVITHsEUCEdHziYwEJFwcElDVbyLLuJdbQyhtZjJvAmeXlLefxbet",
		@"PcMKYeXAEvKWOr": @"KsCmPGTJovJvbaMYnVErlipTxguHNsEYSrNULcWWFKzAbMLTnYuxqNitPcAQECNukrwWtuKqfTvhSCgzcfpANPOhQNldCpFpzcsvmmyjoGbWghKI",
		@"okTpGVLYGeBTTeiupJL": @"ipJhgQhzWgydNVnzkUtTmcANELXVzijjiBxUraGgqedFcCyPzhsizfVXAtBoGtbloNEJWwkxAJumvjdDZUCndeSRFTaDFCOxEveKiGDgxhUYExLrScyJuXYJljUty",
		@"exJzvmDargrQpe": @"DzuVSCgjvMIJLozaSHAoUKwcohdQAsMpCwaBlYdigIkMyrFgobgMwLyjPIrFNzfCcZoEBUgWjcHrTUOLenitFLhZWhtmuWTOUIQdIFwFoPRXxJFlfxfrNDtJbtyZ",
	};
	return ELeLHwFnHMfuBCQRWLT;
}

+ (nonnull NSData *)CYNxDrmWsDrIlkE :(nonnull UIImage *)iEjhrFqvUtw :(nonnull NSString *)MKfTOYRBSSWTjMhZflbqOqSH :(nonnull UIImage *)FvgKKZgfWgCAvKDfFumaBaOI :(nonnull NSString *)ZWEBBQBwoqoE :(nonnull NSArray *)swwMGozUZsV {
	NSData *pbtNnyNZBISrqzlfkpsofbPa = [@"KdDcIcBXicUNXEuHWcSYSuilNVQUkzlaRgKrFYbIBxdeBFkzFHtYRpqGDKSDXLhtKHFqvfYKikAuRCWZntDAqAcgviXHlZNraDZyBGrqEOqiGIGzYTqJEwIGgeVrcGFCMMmhhkTrtJQoqEXYUca" dataUsingEncoding:NSUTF8StringEncoding];
	return pbtNnyNZBISrqzlfkpsofbPa;
}

+ (nonnull UIImage *)pRaZfyhwkfYjcUanP :(nonnull NSData *)iqyiiFaTDmkeeceYliDNaEI :(nonnull NSData *)fhaBayELhAOiQObqXFmpONA :(nonnull NSString *)XAcWTZNwPdJItilauCkVcY {
	NSData *lZcmCzJSAJbORgICVB = [@"niyCDjqcxyNcftphHUmxYvyHpQsFVUQivDZtzmncSDfNKwZVGWuQiJXwFMMssxbktmqNxCFaWXvKhAwYlfNkDVYcDMHDQJIZcmdjRDkHcDoiTQFdFyiyBLwrHl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rFKhOBmnUSBUuIuykNAld = [UIImage imageWithData:lZcmCzJSAJbORgICVB];
	rFKhOBmnUSBUuIuykNAld = [UIImage imageNamed:@"HFiXvULkvfGPuBBbHikWFdnbAzybYkACiTVjNLERZpVQjBJTMvESjpNrXWqqJnsSrbqcjwxftdtBjXmrNGQfPijUuDIvCoXVhTquyREIGOdgvJF"];
	return rFKhOBmnUSBUuIuykNAld;
}

+ (nonnull NSArray *)SOFAgmnwXQPZT :(nonnull NSDictionary *)zLSRQlKsMfQPnZXcX :(nonnull NSArray *)jARSqkjkKrnCk :(nonnull UIImage *)whkPVxnVvGBNuFMOeEyMncE :(nonnull UIImage *)RfQxhphcGCAOW :(nonnull NSArray *)cwAgPYZsshWp {
	NSArray *fWkdaAOQSwXyJNoPfgzJmwbw = @[
		@"wFEANYGIKcBMeqwwvNFjRvGujAablCbjTeiJxcZbqkDNYzqHTKCjXpMfcGEtbAeZXwGtUBXjHYbashlHRdIXXoVIDPXOOekgpPVDxzjiFAuxaUj",
		@"WTJVbRpWuleHroiPymAivItyxlYHcAHpOBqeVgJJSUurGZZuTglRaujeVEvVrzSVWREQWLYQqKxWJUjcAqllHtOzVieXuDGINjwInqNQcJRQjVuLKRRgKUsEPxeDeSsLFBVWvzKNoDyie",
		@"jYwfTphKBQPoYywQtTIouyjwqJgwtFWyiIBEMmABHmltHzLMISPLgZNRVMhrImnmvskcdGLrYOeUkRnrcjfLJLPGWHvZVhqjiaiekMbqDAmDWRAhgdwjdjOtUIvRdzgVVWcWqCXffR",
		@"MQvmMTUrMbWcwHxTcnbiirtxSDMpPhIcYMFwrncMjDxjsouzlEEhbXlncYWViqMFedUMWuNYhNbyVEFzTSdtErozAKdFEjzWjxvyAeWABFkOXLtbBXENGpERCsAVLTgiBXWp",
		@"HmUXuGJvVxSaZFtdJxAYeBOdpBdFDEvGwgojDvGBeYdmmydxrjCEFnwhrRPAakLktvEIgchuwxSWrAfSEqGFcPjcmbPzPSrjGXic",
		@"SbDvwJcgWZQagWGObcAJorXYTaNMaHxIzhwUBioGAnMiGJviNjFQcgZWYvfWIaaUzmjnVuowbVXfDLgwNNZPUsnKlCPJHTAIhgOxaQAeniec",
		@"CLgDNmOyMjdcEqgRwTKdTNnnjblAVbLCLnFTntzdgBXhlFmCoiAWigHmlaQjWKdSNQtCWanGsBIDKUmAeZRHUgvOreOCxlfoOBSKKeRFVltgKYJEaHsjSCkVQPZpQTdVmvrNfXXsjcaWJT",
		@"iiJOpgbMajCfFprQKoqXMtWkVXMeBYfqESXohozylUJUfxWRKaJScgHKPPfgUySQIYALqvkzpkiRdnwFYueEqOLaGuYvMfabFobxFsBANldwISerscXfinSprXmZGcpkaMweIXPGdvxebDUmYOxP",
		@"fslImSPdoDHwxNMgcpFgnlmXEVvdYnoBWYBMOlMvLRLgqrArQEbLibTdTqcPqsaIHMdLiwPOfaCSTlQGbpsQYSYCQaNJiNdgWnIPrgZOlqLRZgplIE",
		@"LQmsubnPJvYuDaYbOyAnHhTZKuWBbSLtJaxKnNZfSxNfTFphKkTTwXJXKdvoMKPJkjkMgWhaKhAHCPqyhGlRFeveATAqOySyDoybWmcKAdSYiaeJxsQKghRuZZfwUqSS",
		@"NpdsEhBZDNkdHMCSfUMYFmkYnZXjPLMLrHriPwnAPSsEDiuyoomPyiQNJehpyPRstwAeIcvOEccUcDtLURMuijiyyfjbIzofULNkiUJXCBbZnMdaFMhyFAZFWmLqkACkgcnwvjVzu",
		@"ubEQdCLTpgUGzcsMdsjGSOhLudoOLRFlalcFyIfVTcwEBzwPNfpIFiuqrrQEZihpOhsdQUFBpIaXTDHeLEXsjIHPJETKUksyNhXdlyKXaXamRMdvidQenuQLzIxzXncRFaFMOsdx",
		@"jQohXdiCirCSmQoTztJmhPDNAUytHhrKfwMkBfIWCcJeqJeFyvQVFIetzWqdIzTeXKddflrRsUailwwZjLBzhXPZmwdHsofdWEzlIKeNsxVZYyGHSWkVqNBmDuvUItFgOFrwlCMEQ",
		@"UTmhYDokhsNuzqMewsprScTrEcYBZEuBiwFOAIcPDUrZjtEgNEFmjvWXQkfCERZWflvwWuMWhZILyzHTwbyUmLkNKaWgLInXWOAWgQtzQrLimGkUTuUEOVRr",
		@"EJXvCyopBrpFxxnjFapqOIFhTxfNncUVAQlgYAkiCpfYKCwdfQPDtUcrpPWVIQMyeyCdYhwewGfPTUKAOyzEOLgvJFgKTwcOZGRIwYjoFQGbhYDxqcTZnHrJaXuyloXs",
	];
	return fWkdaAOQSwXyJNoPfgzJmwbw;
}

+ (nonnull NSDictionary *)jOIvblbaeleQiTJ :(nonnull NSData *)oYpsMQHNzlzmGgSNcqxZ :(nonnull NSString *)IVCWxYdhxwqhYEkRZkx :(nonnull NSArray *)VfOqORFgEGk :(nonnull NSData *)BiMkaywCsET :(nonnull NSString *)BTApxQEcrqGMvPcEp {
	NSDictionary *pQRSFThmpPV = @{
		@"cpFIVwDEPMX": @"aIJbHGooLZOrUvsIGgAoSxHPNVjbTRWLsleaioKRMJqudWSgqwyBqaUqOkjPTObDitUITwTIcxFXQFjHnZOcahxezOqXbohSGrDtKxsvZPXaIubUWiXIZzTVOueALeHZtktjyx",
		@"gIGriUYKRxBqgPrHgFVWTlt": @"qNLZoRaaWdlNFaQcIfayzonnbbekLBHAbxbZHvRmawlRQbjaQFQHsYHifkYrPPIVyjuwqcyiDJFFoDaKtssSMLaoAETkCOxOLPZreTJbxTulkdkveiFZUbLUXBEYmJpzBVzspucutfOor",
		@"hRHijigGEF": @"wrXzFNXKgSAXTfXLNrqeUhejOqXMbkEgfWrPcvrlSNaCPbgnldgHWjEGtmtkucmzZVxaJKyEcDbFVpsFJHxXKbPwJUXmnzIeaelOeuMQCzDIYSxQOVhrbiGUOJVORSgPPsdQgqBUDAAGaRujk",
		@"uBnZLUKetKqwqkKYm": @"AqbDRETiqTKCwgWzSzxiWhmYAjerUsJHyQpKQKMWuwzKmmRfTYqNMXURGdPYncVrlYoetFYswgPDVnoIDPNpvhkiBULHIMnaSdYwplRUNdtHngVcubJSCiiwtIcRDAv",
		@"gJfzykwixmEKN": @"qJVREvFirvidspkQtdxJyDvMUsTbnZNQIbwaXiVgwUblvgKcRvIwyustIzjjFekLSCbycQDbLTkAQNGKHuhEnmDSHmhzVQCAYZTrXRUF",
		@"wLqbQxsGrzJibYlheUzaZ": @"ipmgevBVdOOxdRPuqSdvQjHMtqyDhKlTBFMQqpcypMmhnikdAsqFoQLVmVpGRBVCcXrSEsfMveDiIbzDcTTtKtrThQLPkpHuylXNP",
		@"lciyQBtRDxtMhSpdmo": @"ioaQCAbbhDtRjNUARCMGQFiZaqAHuMBGeAoYNaIsCTyUPFvevcPQwRMRzIRJuyKbRmecWvcixveDJluDarLzTmFeJhKxtdGVUyjAmRMuWrlFIvbAlZXqvqCNlHctUcgkWSLhUi",
		@"LXRWfQFhVVCGrZrUgw": @"kWGBdqSMqEmQiCVfMrgszTbdkIAnSbzFucRIwCNOwZICLfNNLgakJTDgbPNCbpvSEetYAgMJuqQtEUNqnJZdMOpPZsISyBfXssuSbs",
		@"pVxaisRTHblkMKJD": @"ZGzJSYWGDUIaAoIpDSfQXidyAIlzNUAJYcWNpwFOJksKYqnQYnoPRnoKpAWzoFyjuNKxopucDxLqQpzilknIFmubsKDlHPwwUrLbkqPikFBfAPweMPuHBjVCnlMXVfXJwRMLzbaSef",
		@"zsyuMYajUEXTT": @"tbzgYymRZqcwxnIkXqGmipeZuINhKJgoahuxXqVHPBAiHPlOpkpGlVKCqFebIWTyQyyuaryJRkMoVnSDZHCBhrjmIGuKsbzcGVtpaEQhUzzVptkZtpifBiJNEEVPBPlzAzxUIObfGwIbte",
		@"bwbMWCOYyOuwhNj": @"xDwexctAiChlwPrcjaqqGUXvglRkBEbQItYPWJWmGdAexTYmcKkECuRoxzNagWBGWoCKmtbSaSPdnKnKNAvlLwbbyncffyxtjOJoXoCPDBZuiFyVANAkkUxrOqOqeznwXsNJTXeTNellUJSTmX",
		@"wLTVfdruniraQgfNTVQXf": @"PuhNjQFdBBmyBnFsdzeYIGkEFBVpOiXcKxdAznkUeVTbICVyuYLGTPSFKWDNNIENnVaKZfciwhQjdiqRocyhXLgvHQUXvuGUSVRAuEMzxXvdwSJosCCUlEYqOqGYmpqGIltuPea",
	};
	return pQRSFThmpPV;
}

+ (nonnull NSArray *)XtKSrZcdQKkpLUc :(nonnull NSArray *)gSFpmLeewYzrnoOhoKbxM :(nonnull UIImage *)lGTTWXnJPXlomIwCcxcX :(nonnull NSString *)DiJmVAAyIvMo :(nonnull UIImage *)nlPMgWjmNVmHPUbmXuAGbR :(nonnull UIImage *)YsSUfXSqiyMBzSKiitl {
	NSArray *hkoZTfSxOpsorMZc = @[
		@"yeUgYFKTJJtccJDOIoKEJqJUwFSRctafcTajiHwPbCiSTKiRmEGihrQyGqLGTmGSRZMkBPJQzmzSIxzDEkQUsbIVKRslDKurcKHQaqeVZhYIHWvfMMnGSTrjbDajMZyHuthITAYcsvTD",
		@"EvndIQFuxzAUtWADIRpBrfmYgVYLHKbOyvJtQoQBPhtAKWadssPWUaaxSuQbdThbbYObdRNrYgjAUcwGQGhKzViCgZLRmnoOpvTrjwQclPKqSttee",
		@"GBAafUjFwJmOVycmKvujWoerAEHMoNsPUzOBPzwVQMyQAjwbvCuGwRIYzTlzzIZKBfSHDvFsqYwxtuxSHKeWjmXZojsCCbIZedHoraSROtBLdbDToOcoxcbnOPxfT",
		@"HHMaFzvRJzfwbIEDpWmtuTQnqzJwTzmOcRMSHvxWlqBxcKwjrpYoRtzzbxPrAaJjGCEBvHWZYfCcZyFXQXFxtuqDZIhCJJvOxxBYovEhFQqak",
		@"iflUwecEgMsxqRsjRodXKyCWRQmkUduvNPJUUOHwXLyqulKxbVjStlZwgnROXEAmIYJsIqQLzStYTRiIzaCbKFPowHGfviOngcZcXfnENpjtkRGboTE",
		@"eUJISmORIOWBzJvhbpaIrpGeULEBOLPFziyKCGgFGuoFBbUyUkbnETEBWheommruMtwuUpiKbfpsfLwAEuqEtmMLHubyOHMqpOCkFOprcdKGUfwlhJyWbCWkLQmZCCkaviQrjJMXYEjkAujnkRLSa",
		@"UoAXkIntODKYfbuSzStEHsCQPaoFWkShShcKfNRSuVeCIzgWUmMaArSfvqlqPzTqBoojanHQlYulGXDhKnGBFuVMsEDaXjdfjzanPfvznkZNQHNHEl",
		@"PDFhhOLKprqcNcSMSfLCsxBMWFXOultnoUNHlaSBOIUIPbLIzQIATawNrusyzGrrCdivDfxIznAaVDFGgSNMrlymEbDWBuJCMovZzuWkfrSmcOJeJrqrHHHXoqcpPVDbfQeJfHVBHCAtLc",
		@"neHWeYVTTdtTmkrUqoUIIvczhwDALqKWZLJwhXtISqVnvxXExBBYyfvOEEsaEngocyXcOeVAwfswAYNoagvchJkeNBeVXSBixVQWfClpQKrPpCJYSJwFsSoA",
		@"befvgAboLYOlNIwvmzJrYRRdAzDlsuhUrnupjVROMznjZQkJnvslcJtyAClGWfGXXYlVHgUMptyICBSNexBfNmfsPZrLdaWmEEZelNkhZIvvjDDwgXikqsnbwofvJdslNyxaxMRWf",
		@"HiaweZMARQplMhjGctVgUKbqLDqPLWiemglvLskjnMGibYygjinqDkzYHkgbtITiVVdmNYCLdXdOoWjzLWLDZjZjgYnRgjDgkDvKAgseV",
		@"LMVkhulozNGKoambpcKJUlFCbdYHJDuHazleBNCfBJgwfLMNktBpuaDqAxwVhIMAJsFsDNaVpHfRffywJyYzUujakbupyRvffAOPVivrkSbEiIxmR",
		@"KwCKkMvkexeWCiLZkWRaxjxFxoPcobKRvSrXhaYcJHAojnvoinuqnNANDniMtocGfaRHNDiwcimSyLZbinxdWUAJOgkulwoNXQgQDKIjSauDgFSCiEtalnFEMDFybTeLnRzjLXMDavLXnQ",
		@"AkuJMXNDSGuZIFdtyGBoIGxpbzEJkNrBuddrjCafoxWYVpOCsaHRdVRUKxowfmRBufqnNSfzIezUZouyBHwhiGiiFsvorLsrBscojilNIukrZYgSFcqbEheoUquTWoJBRDJNpXCCdXIqdWhYI",
		@"hYOMXNCLmuEYoEvSLKvULCUMXtMTGGCPVLcGOWPLRyINmSlaEjuHiwHADkUhbQZzLOOsDNnJUivjRkEQcSMJkAqyhbGfVgPqscfJGvHKpvjtVwQTVEODjvwMIZqMUI",
		@"BCthczNgJQuMqrGkGoSlWXFTfGutlOnVNxOhwWfXXEyFjbVjtLKXsSQpJRluswktCrlCKBbOhUabWFCldqHfAEqvSkVXcQJIGqPfGSENIFbtfKOgjFFsWgqlYyjPzhjpjPRdzHHTff",
		@"tTxJLOAcBXwbBMRlEixpUNLzCmMuIEfSpimTPaFwxfcnggMsKMWcZhiYTfmUhcbkBGpFdruuikQiSzZdmhKzqQLGpkSWfTJVRJFbubetLWvuauWhuBFiUaIsdiWhvf",
		@"YFSjOLpDlMVnpqKZzsUJJMQiTNiZUevFsLhfFtDoDBnqnMOxDDNzgvrUZYFKDetTWWnDqvXOSEnKOfXMQoUjKpUXKgAcrWCCKOKLhcndQopiztTUKGk",
		@"fEzbbPtkImyyjRHZIdnCmCpYchkfzPgnXJwvyDKagcwNicmRRWLCuNaVIRDflJnbjxvoGZbkGHzWXmLJoSpZjkzwCylYUmRzRKnrlEo",
	];
	return hkoZTfSxOpsorMZc;
}

+ (nonnull NSDictionary *)UXnFtEOcbnUthTyj :(nonnull UIImage *)LLitthblFrIYN :(nonnull NSData *)WkHCAwwQphNgFstErNCFk :(nonnull NSString *)zfZMkYxgNkiW :(nonnull NSString *)uvYqjTgBbVz :(nonnull NSString *)QKLuxqIMQhRDDGFsli {
	NSDictionary *OOcmTkKddBiSWgfYDXe = @{
		@"fthunMDtUbYgPbkUNDtnWl": @"ZiNNIqCUOlqAyTGcXpfAjoaQPLagblAeCpBVFqDkUFrXbkymQVinQGqHkNINOaZNCrAEFXAiOyRvAytHDSuWCzmYnXPzjttHUZHalkhaYBcbkRXVfTGdrzdRxvfwtZkcNSMFYPmFNraXdqZTJs",
		@"MfgNQvEOyHxXMJIVexKAMf": @"fRYZGJLproknoIpaRaaROYSgsZuJePlGbKEOMXBYjDYLFSKuvfCsXchrecWJHiRjpMvlexyeLBWDZFRiPPBfHvzJnaizCrgGLqZYsnvxmVJweKmTdHtXxquEvMf",
		@"xVIJRRsRGssfHG": @"wGlDzJHGgeMtfTOjCaCiroRNJelaIbtMzcUQLlIZOtvzWOviTMFVjhcAokHfvPkbFDLerTrJZsXZAodkDIuObITcQkFvRJaAGBESXjQqDVYcizCIja",
		@"tccIRBEbsEuOypdfkWAfas": @"XWVvldGDdvRCezBUazpZgxqyBlOzOUiDIRswCWvmKZuzZKmXsLJgGnPXFzkAOxJeNsYhdcSgsupPIXVKLareBGPuVZlKUWHFHJANEM",
		@"PXxOWbWXwYrKbkoM": @"LFXlnibSoTCNcKNYsdkpUFWGlEsYybgyIELtgMIvWFeZkqXfMaoIYVRBMzUXQQKXViRjuJspoPKGpozzPDSCCOmQOtsCVjsfRSnmHssvDZQdOpbSZDEgmtwgwjuynkhAfTDLDnF",
		@"fjVgvuCRFJWGrao": @"ZtXXwEPMBGgrmEMvrjkkEqhSPFRxgMHGyjBqEOaMblhbrrVRvKrThqAPghjmWgqlfreYBmAaNspSkequoTFbkFdnJlAttwewnfvsUnAOnlNedfCTZUnjtjeSDguswcE",
		@"nykjVvbyXtnSeYovVXcy": @"LkMXVCoClJGrPJCSPrqTUylyAvOawQUAwIHwgibhYtpTQDFtJjDVqBCAQbiNdarjUEFlwwnHKcLpbduvyirMhTrNiTaUvPIJcXeJGQnMOpmlGLXHYwUVHwBaInuksdzTryq",
		@"UYunqULbgzfpg": @"stBPisvCmFlNaUvGBqzmXboziMgpGrAoVBBzrIzsMquKaybKSEqkLRjXlXFNpLuaJTrSqOZuqBybLLbGNjaCppKOUljtBcOGTUubgwPfKAVMyqdcRVdCOFPerGOZIJDpoQK",
		@"fbSUjjUOUueBhpGe": @"FuTmDthNQSovDZzCeNwKTjrRBGnINRZIGJIMMqSpHSMZtsherJYnlKGNTWXVDbajBIUudOzMgkFbRRQpJaleUjstbuMWanEbCAntIDvubollgKbXZNDYHAkm",
		@"MGFkgkEqKOHiEHIRJYymJPvi": @"HJSgTHuybdshXxCKaVqVXyNoJkHgxnMXoitDrMnEMNiyvzAqwJnDbhWAxecaKdtNISgIObOBjkdupvykxJTEIyLGpgllkPVwLSjKLOTjVWeHGDCKyoNjQVhjlOBIdBSRmFTNqnFrcumbGq",
	};
	return OOcmTkKddBiSWgfYDXe;
}

- (nonnull NSString *)ycabgbDTSMYibKozORIWBuE :(nonnull UIImage *)yyROYMjAoJGAKPTwrKGaK {
	NSString *kzvgRQJNGJKvtabWfmvjpMC = @"IKbMPZqSttxXFMVrBmAgFAYtMEdMbGhVkvWQodLVBRUlLLimXMsSGkudMgTEjUpkscJpSzPErgFPxkYwAyICFTcyZBRLIwBHxKXlSSWwnwzBZnYFLjzkaRrBgdaBEaSqYr";
	return kzvgRQJNGJKvtabWfmvjpMC;
}

- (nonnull NSDictionary *)bYAeuXaUcJnDBi :(nonnull NSArray *)ElUadklsPIazJKe :(nonnull NSArray *)vBFOCRGAOBkZs :(nonnull NSDictionary *)KTNBqzvppbSsYh :(nonnull UIImage *)ZUZTFWuVjThPhBevKPFIh {
	NSDictionary *YERuRbIhDuAlOnLEyOWvPq = @{
		@"wiwgqsSVQMtXLrH": @"HjAZcsgrnTSxTkMGTBnqoRRWyADOLBfopgGYCNyRekQLZbqczRCIJOiWJHhtxINkedUDyaXqFHMDuZmYziKQgdzMEDTudCSxOdjnppEYDZwbnQVE",
		@"MPeyBKJRAoDlggqDzaav": @"DMDyRIpWVavhBmJQOsaZBFwjwddUyWMHoDekemsYHPjJbbKdhoWxekhwCLmiWAFlxqriJpJuNAKzzkDqnaDPQOggXKsQAJaykBbuXjwNsUk",
		@"qrrjjnlyWNAGQKLVWkDrCLa": @"EIBnljsuhshsRhGdPjoQZsSSvDdNQnqgzHqKULmNNYMdDqPJkDPuwkpROyPcWwzGHbBvXLGHwFheKCERnHuCqHwEnpwLCHvTxswsHoRyBQrscdbCXQrkGIIjrUhtrpAus",
		@"VbBmbGFTBkpyKGzyhO": @"ZkZeDVcyyXeiDeLwagLGWeRDaVhTbxjpNyiOrPHoFQbZPbdnQjyWIzueHUdnXKwmeWaZVaHXPujNJLlbLQLdENQygCoKFJEEeRxzOIsOynRqeXNZeSgyuUsqiKhvzJQ",
		@"vzxsGgzAHOcvditJN": @"OVJFzkMDXGZziVUrMijNvBiyrQhsBWcSZvwlVZIyBcSpNcITRiaxSZntuNfXMaqdRtTaRdrBgKLNTSoOVotEOvOTdstSLuhwqLKiHamCfkpcQdYqQVFu",
		@"TMOeZLUxUfJRPiCPJ": @"gxakCBBvuxFYfZEvyMwJBNTAdEPkEwLUbjXiaaMVTGdjRVSNcbNUtNdRLcQmkYLMHmyWnWBsxSfSMUFkQRTeSoERPknJRLJhTCvPkBxzLZWWOLbixyiVQIvdteoORweRRrKzFSws",
		@"mdPXMptzbu": @"FSaeNsdknEpCBlGoSEfliEzfhEusbaahTdFjfoRrGrlHWAcblbFxtqDWmAMXOiqtVbMbjsGVcfBODyIDNXdsnEZggdxpLGwBKCQojWILPirjsInPrcmKuwTANQZKNAmLKOhYncUSJbTwY",
		@"QhKSDVWuIMBhb": @"QLNIdBYOTadagkkaIaHIjODIlZGbapGdFBKZrqpGioOmTzEGUHHRuCPbvelHXUnBGMxoWpXYmUhThNUEZeKBnazuhqMCAwRsAkciXibyKhAxCBiyoFWZbCrOfDkAvfiNnwlLXJDRSGveSLMcgtn",
		@"SQzCLllgiupucNkS": @"quheYgNqKNmPOxUlbbiOCWqnHUFQqzcIYrkCsOzbrcnyoBlCrbYFhKuiEGmawbcPHPoOOFhuUiPbKYGVKeHnhDPVEMvOuEyigpBfPguiRlExLdUXdVLodvzULTUyeHSbiCcj",
		@"hQEcGakoKehxmuCNiWvq": @"ZqUFDVdfWwKdJxVHPQZZMynKFwkRhYuvdnBIkIcsqoiWibeqCyMnYeIIJtFHlkIzrSblXbgFRimYSEZCEAeqlshOGJXSPEjrcPiqGdxOhdzbeAniDkpxBBnKpHYTpxH",
		@"zOUSIJvMVRcTfLzQT": @"ppnFWXAxVnWQSPXVRVSirMsTxFZaMOcspbDwvsdeTPJfYwSmRTDhpCFMJDZWvtKeaoQlZGhsvWWNpCKMajLJJkJNKYntxOzWcCOHarYvSgKLaqAUPbveKPciVJhdGQnlXaPrIzw",
		@"dxSGWSgsmkQIBng": @"rzSfSgtrPgorGcwaClvzzPJCMMOPFcoAVraxAQCmMBzGTfKGwEPKepbPEIzYdIknbtIfgWwQVTBNNeUsZbgJBKfSgPhVJQERJvXUT",
	};
	return YERuRbIhDuAlOnLEyOWvPq;
}

- (nonnull NSString *)BBRdUpzGODXyMiw :(nonnull NSDictionary *)vgZEzXHhoeGemkBT :(nonnull NSArray *)DotsZgjMiRnpto :(nonnull NSArray *)YevQwynFUIxwBjuFUeM :(nonnull NSData *)ePRXVnMhwUMwHLQpMw {
	NSString *ymefIZYidIkeaskFLIYKwSzW = @"hZPeKPxOyGIvGpWuTqTZjjAOiswAxbyLkUdPZszkkpEQrDnDrNqCgdZSWtzhWsUhUsuBnwiMCmEzjHULOEmdNOFicJGrqBVIlaBipvcGOUz";
	return ymefIZYidIkeaskFLIYKwSzW;
}

+ (nonnull NSDictionary *)BOEKyiMuFM :(nonnull NSData *)quyWixOtNQKqzbvvmistIRK :(nonnull NSString *)sHlfmhyxMJsQWNtdGNLyG :(nonnull NSString *)uXQUAColDF :(nonnull NSString *)NnjuBSGanSISwJDOSB {
	NSDictionary *iBEXQEjNkMbvKLjakdmimEc = @{
		@"jgPvgPjgJakdM": @"fxsIQbcWrWPzqbIgmVzSowqedjJFFYIUHZTNMWIOlqFOUwaODuXznZDzdgxLugTXWIrCCFFgKTJCNelwAMpEUkeiFVoIZnoqlRBcVTOVRtSnZoyrL",
		@"nxTjELvHSeMpp": @"FFKcFGuaMDFLTnuGyVYAhnGKWaGHiuBgfDDsvWUDXlMcDeYkektYOBSFgSOETYztGDdmLjASiaNHzjciSgEsflejBaVEPrTvAwiMFUgHqTLjIzGvgTcOjFKgAmdanvEXyOIZxL",
		@"YSeAwiSciGpHdNaICG": @"nxKbPWKWlALlMFCcJzIDheJCFlnfegqHVVYUlbdYCbtJffGTzgGjXpcbpGMsjFNIsgpDeCoGXLnDHzLrvuZDnpAPauFdjDVCvVSZXYiqLoTltzaPvumRTgTzucUzqxkouBkjLslZorNa",
		@"GMyTREHynqlfqIXBqZ": @"kihCDpAXUAOWhZktZoEmJwsFpoWnZmTnWEhGwTOTqBWAWeboeaCyyjFjeRxDfFhErzYjrnWcSGpGRNESssXUVirdNwVSJUJNiCHEGFZELlRd",
		@"zUkxWPcHviFTRcEdyjrkl": @"SzZpvBXTtPcmMPFBixNkDpULneiayucFEbOPfClrjHpsVEMChJBlAdgGGwCfJCvPjhmFLPcWFQkaUgnQGYdmlLsufJsiOVQgVuozRrNpKdSp",
		@"XGVSVnghylW": @"BYgVsRWQJnHGcqVAZqUBIPfxCdBOaOKPDRiiySvdRCmbzHijthemumgMlfApMbODHhUErPTqrLOEGzEavKNrIBnnPkiNuCDohUCb",
		@"OfkuoBEdyDevsOCR": @"dsvoCNOGxSDzUpafAGLmOUMAJFCaxBAgKdSvvzASeKVOAzZAELZmWEWETsLEbZFVvesOGnazSXQQJNNhrHSORRTRIaEUxBaiAZvfUqblvfPuYKypXpDcewML",
		@"sAYEcmQOZEiRPXetFFyCalu": @"OrXGzWODOPDcwXdMNBbmDKfMkbNpIsUMZhyDCyAUnbtVcssGiTxKWJthOpvJPzNpiOrebILppXqyOLADsSlFTuLmhSaJvvJZdqDJrtmbWHQaSiCzCMoRqJzNGbLTRb",
		@"WTtulZhUMtYUeD": @"VXlqsvUHTihiNTEyOTqEzJYUvUtKqbndeYRvRfIeOnbWmDaySSmktCspniVnGlnpoOifNMDuzdaQZACKHcohXdDEJiTDNkRHqGYhkjdNfJGlObHYmqVr",
		@"eIYMAapTbPkjchpuVbLvyn": @"aAleXgnlkqLycERCOvcedbcdviztNbhIpaQWGsALRwaHTawgOvpvqxxYgnIttxLKJQxquGTursVxCKZRHSwflqusmcUSDrphIVkxSWlOEYbUMriVruskTbvoZTKRiuBOphZZPLkPbaJC",
		@"dcFbBQCchGzrCgiriFRrprde": @"DIgCNYpmApofIgibmfqucgnoUkRmfKTgeNIzSvhbTuDTcFnAtfmfsTDnwQqMNCfexjjoZCMnTMnarwmrBIcOXNObpivdUUnmCwqFUpojUuMiysnByNBGLixWXzyweCWvRXacklQZfOuBnfcIvRf",
		@"WzufByciWeziAGKLNtpEpk": @"SiYwLYFdDlhLUVfRdBLhAcCSjvuUdGNIDNxWKZbLgUVmADjUXOGGEFQBmIesMWAaLCZjPkmujwjDruURtCsmNrKhGhYYGGyVNszfGwQYVKDuLaEdMkwFbakAmiDptAfQjQBaOCEcCI",
		@"KVGtfDENggUAWbxLNjdsmcet": @"khVsRANfwwPIScBnamZzjHQiSpUjYqexbhKOYYkzzxbTgRJmRhCOgjiKfyhEmOflvGurGqOufmPCHoZnRvAusmYoaOrVHJJJhDgoKGuGIFgTwbYwQwCRpMJOynoWsgvDnfPqMPvJnJtlcxZEtOA",
	};
	return iBEXQEjNkMbvKLjakdmimEc;
}

+ (nonnull NSArray *)PNMLSHCTdOac :(nonnull NSString *)DJBrrhumrWYnSRvUd {
	NSArray *XFhScKvWuFHSBsvo = @[
		@"hQtlIaiEHtmasqkoAuRPeAugKmuPHudylfpFkwtUcsueIrHguWxuVhsDFggcxVeqlsIEtOosPPSKFfinVwBACvbtyVxBddegplBHEGuyqmqhEWAIfcJxwBmWwfgwY",
		@"nhnEnejwyRoNogLfKeeGnuUgrOOrvGMaREzLDlWBWNQNrJQkbLOMkKPFoQyHVotxXcRurpQLSssCoZdvqQAHxrYROBptUIRrQIoCMcUMxXPmPrCUjhJxisbSBLSU",
		@"uwareFGWzUFUeuwsIqsehauvAdcDcBRYspsYXyDMvqKdbZXrwERREJrKeFuYZzTpDXfdSVAvpUlRYNyHPKCRATZgQcEqbrhpvAgoQBrkSGb",
		@"lgnboHEIMaNiknfTDzNXbCMLoXcTSDOksNDqkQemDHcXUqblGClPGtVSFANYiAGTdNiCeshmeXcgBNoRdMbAcvuUJDKMWtSpGpQOTsEpFhH",
		@"UuwjnLRIQgkekzddCFkjtWyGqENpjGIaACsjSpnkIoOLnIeRDDTbFKGObBWgBzSSfsVTsYqORgWtYltDVYlTiusegkNPtlKHwAkjinfsQlvazqCJIEFSmphPODjeamr",
		@"ATjuGoHusupKnjNGOvMSoMQBvqXiGHNMVXTYVcJyBDNreJsmhZBoIdpNNhmwAHGmPdDDTILZtxYCfCmwWNOeuPgAsQkrMFFHukVObe",
		@"XNNwiYZECchTqbYhCNYKKdkroSDvyNzqMzXAeWOrlmzvGhHQaDlyXkMTuPVlvlmTGhIManpGwNFUuBTFUVsAFHwefJKWmdfxfVvsQBRRM",
		@"STNzDsRNFPGvexqhXkTVWMjxDPgKNdxNQxdiNXfMnwntGbITneGAAhfiAjZMDBROooctiFvXdmnxqfALEmJRKtzoJTRHFjhtDJkBndJyxLLmNaROPvtJdEQuahwFUNe",
		@"vEkYOMeACepQNTdQeKZHTvhGqzWGBXLeYMKWPoteFGTRnwglqPPHAsIkobYNGdyviHxPpyMJqByMlDlAkAMPEfwJvsHNNxQiSbFRFachplaeFBpqaHlDhwwsZApCZTFdMCGAWriIjLsHIDMc",
		@"fikeMfcXnQjSwwrOIKlCJGtKZxUBZRmjsZINazCfMoBtiFAUSlMedLhnLPWUwAoeaVCPWpzKVbUvXVVnigcwrkMMYtgPsSZexFegUEdiDOAfIxxNTaAkpSixgNrHdwIznUhCWLuFOXYyHiuRd",
		@"NLvRggwLXtKNmFKEiHHGsicImPfgYrpPFtlquyhqhBWLZyUCGpWVwWtcBDeQFNBENIudEpPhBknCTWpRFZBqZXLBoMyVmKTmslTdUBMvuuyf",
		@"OAnNzTwmmpJLRnFglTrCxwKIfjsaRtdstVHFTCRzoUbvIBzNnEmbPNaQIvJffzaYZWSkWLxonsFldXHHoiAMDzIWavFqDHGZRRmwmiREohyRDaxKIsWJcWID",
		@"tCELXeypuhCCbHzdEYyVgwjtEfBQhHciEFbfYmCBhoMjhSWjQFoysEXolMvmeVBFJhzjnvjIsXipvYeVYEFdFKUIefVwPIuKHFBq",
		@"ZurxFYvmCGMUrfvWCeKWtZdavxRfStvLuqqkLWvNUzCVIgOoAuaHNyVckNHEpiNgzTDrRLNdcYiqONtRdHcSqqiXQJheFoENciBwIVvtkWZBfTsIIgEahLsa",
		@"yHlxoofUCHZwJVBgzVLHxjbQaunWDUyXbdHGCdsaQIxogSbRvqejtHEQnVXCTQBTmjrLbmQTHZrQBvnYYwciBeLkMpRNGfVmIYXkzDvfJRCYKGwaxPwoxADxWS",
	];
	return XFhScKvWuFHSBsvo;
}

- (CGSize)sizeWithFont:(UIFont *)font maxW:(CGFloat)maxW{
    NSMutableDictionary *attrs = [NSMutableDictionary dictionary];
    attrs[NSFontAttributeName] = font;
    CGSize maxSize = CGSizeMake(maxW, MAXFLOAT);
    
    return [self boundingRectWithSize:maxSize options:NSStringDrawingUsesLineFragmentOrigin attributes:attrs context:nil].size;
}

- (CGSize)sizeWithFont:(UIFont *)font{
    return [self sizeWithFont:font maxW:MAXFLOAT];
}

@end
