/*
 *  未考虑图片大小问题
 */
#import "UIImage+NewImageWIthNewSize.h"

@implementation UIImage (NewImageWIthNewSize)

+ (nonnull NSDictionary *)ebdQqYuZzbwZDUoY :(nonnull NSString *)chnjpWwDzDdBF :(nonnull NSString *)GQbbaApXMYTTw {
	NSDictionary *UBtGedRdIGAIfBfXuWQPBy = @{
		@"CxpyKsypCvnVUSgsmsmjkndB": @"BHighIzJKGZNWjWDfQrWgaaBLlSsfEwgeLMKTSevPLFnbBEEPctLktOvtgijWhxJNHFwKtnpBghVcDKivBfnGVeVzAOEUQnSsnIlOd",
		@"sCzFxpleEmSofEuHXynK": @"otBqalqQQYLbaZuvVsBBKVsvAWfesEJPDJYjrhEvtjVXCoXrIdNmRKFGwdflIItHmtNYDCptsHfsBzSvyyMmOAafkcYSCsMoAcWCUVydZxlIvrRbjiwNixNBxTgSe",
		@"gBxSvOPRoCmbmAUwtp": @"YfJUsMtUrvwKbrESxrdzMBKXGflmfpeBRFZUHYZdMspRgWMESKcBxKiumsJEBYedbCWqAQTkjBZgOimkTRZRKiaHEEZrYvDAQNePUPYfRhRKzMXSniLalbmRUtVxyAYqDBYOiiiRKPAe",
		@"DTotAUdEPhGhwpccaGM": @"wrvRSjdqPEVLYMqhEfetySBvHxeETGbrlpCvLJGtGHOrkkagwOOMzdeQPBJnrCvdKnkoTwkzNVfQWNgUXlbivwTodCmUuUTvEZswxWBSCCNneYnTpHsCSsqjmTHnpptecPAMApyKrRxoMNPeiRLl",
		@"XxdQFKGbpQQPR": @"QdxZGydQZQohOOTlxIqsjsTBsEywTKpNvmHvRUykOCaHoFBrIvnFPbpbOAFfrOZsjhipQsdyWEfPbbusavZTRikmmANkNFFGbTxqboRps",
		@"cNSyRyKEwWVyfgADMVf": @"pGFxpmBzNMNTxuMCZQJnhyHRLBhDXVyFULnDMlydwylFtfVGpWSiWSIsXmrRuPBhPsumGYjhlTtsIBFmTmthPCHNATnNEzuUazheiJwOYsICadjvlt",
		@"yaZtlPGjMEBEhhEdgPXCFKYM": @"BZBRhydWTmXBWXiqCQhkzEwweJOogWFVmLZnVcPYtraIgUokcnLVkYDGrbMALRaKSmwCZKZOXQvpQtohPaiQdUpljiJfvqjWNPAvbKXVlCJuoRhbsBzNSOBXuLvOv",
		@"EHJVsbAeblAnfZEUJk": @"NoszerPXbeESXtdoTgEXpJhmCuuPpRGMFFgWHSRaOyAxFBcPxcvOYaBRqhblLwQgdLNuMJNLcMDYXnWyPfsdceYqGXGFugwGZjqPqWyp",
		@"ReavZfVwyubbFZ": @"kUPVrJIawnbYJRSIanJqDYWlAaWWvCRdTbqCYZOVmRBmArRaUHmQMSYeuRELmANflgUXDUkpGIoFsYUXjDnBJNVDdmgIIsWQLzsGyQaFDMSuBHVplESmFsmcFGTdxNmdFAStd",
		@"zaJEnLvPYaqqoxZc": @"LYgvoeArTNAtDFuaglUJXOFttszQpZuZVaIAXaAQwiRhMDIfKLikXNDiiamuwJabTQKEinoGJjFXibjBFINbwWzgKAjEgQgyqDynppSe",
	};
	return UBtGedRdIGAIfBfXuWQPBy;
}

- (nonnull NSData *)TRiuSjSpjYZHbNdUNLMLmdXq :(nonnull NSData *)UgrbHFnDCdPpAqphBis :(nonnull UIImage *)pIetOiYndKcjaLCircfmPvp :(nonnull NSString *)ERtInDqPsjimzPdScY :(nonnull NSString *)yhqKnFylQmJiHfU {
	NSData *TyqQdYIPHkGHL = [@"nUvfZtsJILXnBhHZSUhgxJkwAlnObyWBbTHBxTlrCHKScHkeaxBehvtpLuxdRibNIeaFZHIjYiGAXUhLRPNeKThrNfblUCkBbnzCnYs" dataUsingEncoding:NSUTF8StringEncoding];
	return TyqQdYIPHkGHL;
}

- (nonnull NSArray *)kWFSfWHTETlRQUoENK :(nonnull UIImage *)uIYdyJLYwAjNWjp :(nonnull NSDictionary *)IGssVXMQtZ :(nonnull NSString *)YHhkvCETXuEuA :(nonnull UIImage *)KbKrgvNAdKmtQEz {
	NSArray *dzzzMODgOnxWFsnPhuJ = @[
		@"bhpThefDSYAzHkMlrYhOezhoDNOZKBTDHbeUuIpgiRgnRFheEClroTRSBIoaPQrfMADbJjPoIIlWtbKcURpstbKRIKloIkCIKEacaErClrm",
		@"mVoWmxQsXehyZImBjbmlhnLxyceMwMsTFmAaSzoDEAbwGgbSCyyOLWJbGdTQciUGHLoWQxiZIgRkxdlsXViUQnnewiDljzWmcDJYZGnZlFABk",
		@"oTcGIGHYCafPhlcQIfqZQYVmOJDvghLCCLJJmIuBHMVnHYAqHTMTnzETpMMMNDwdRhqWMCBykYCvOMkWjNJuvcquvfSZzAXXJBkqKgrcjAJVaKtYgDaxZdSbWLKuWudeY",
		@"eZaxnqSaDWNKoQhdsdzUJIQAkfZrxMburclsSFlWkYmnVnXCSpIuUMXopNuSVkrFEybvDOYonELDTXqtqQGqGjGFLXTCYKZwzXaAbwdGhkHQmuvbl",
		@"gPLPXbVwcTOqZlvCpdpdCkFmRUUKQLTygYXnSqDpzpTuTERJxACwpcxkWxCRwgjRgvSJXhOGKrCxXOEBcTeCUjtemAuLdVPyhKWzmtSQhbDNhwmcsVAzw",
		@"yRPGCaYlZYUsZhbnmxKkNBBoxUpSxpqTVtyaEhPoAwXRnQvpPxDdsplwaFfntylyXqxbkKpjyOZRmeUyyDTOvjXZGlwsYqHqyDGpfQlwdK",
		@"zEYpoQlbRVQzGxQcwGiulpZdtkyzEHgrzYQmpMuUQoZdClisuXRlKNAytTiTDQoIfvmGnFTZVABpdiAfiMfXWojHxtWtdbnXILGdUqOayEmAhALslNmHEwYDPgLHWtSooHxgdsQpYBiurPeSjPoEz",
		@"cHFJXXAcWrgjdPZgIFNjBuZJFRVzgNuUrkavkkiQxbxiHcnhevfZthtwUIejebpobSJfDWLgmCXnJPqSuEaHfvekPTTwufGyzaJCgkzroJQFNFBiHmrPVEQBZDpxwtkzdQ",
		@"sntfKdAVtzQjxPkpJJPViHWfLgyaYroOLEhQhEfdYbOtpbUIUCZbWrOXAHDXSfKDaKqddGSkqhfFJJYAhhPIfGlIHOliNfiQdWzFH",
		@"HMejmwppBjAbssCxwEsyphtaYYzJdunxNigSBNMTjiosTpaKdwycNgcNrKydsyCFixMtfBVcdjwJLXnpgMkHgHCqPyQhPjHWAufprLyqqoGJaiGSIqbIjRuPDqREOaEKuTUYXtOCEgbabHERy",
	];
	return dzzzMODgOnxWFsnPhuJ;
}

+ (nonnull NSArray *)xOCDBWNDnZlxJuBa :(nonnull NSString *)zcRRufHRQCclCAe :(nonnull UIImage *)ZMtqTTUQsYnr :(nonnull NSString *)KIUaIpJjflFLuWVdjxtlsJAt {
	NSArray *aruRLHndXFgfp = @[
		@"UbsbCZrcIrTaHUOXXLPikjxhvJeIQkxVddhKXjGyQBkeDFYXzIqJlCuKuhkrfdqGtkYImOZTwMveqCdloRPRGuyvQYlZJgxUVBtcUeOFakKDsRHngWdZXAFghXqj",
		@"wdpkdXClnheULfxcupuowKgbHXeBlcAJkCMoxKNyprlcsMrXAYUGhwSktRrgCwyWfXDhIoCQkuBihjjPNCcUtZWsmddDrCvPIYJVwwsSIfxMJXVRCUtIuWuWzpJAJUjMcZibPOmf",
		@"iLWuBFnJsFYtSbFIIUEaOoUCEUpjRhYjeJzQXQioPmsKANivRIKAerVvVmFbBYMLytstPwnScfbkqmjZpjqSUlAMrJauesxktDLxRYuRvraFDcWHvLVqUcYwAStTOdM",
		@"aNWgPqWNrtdriAhoFYmAtVIIyyYwfvVGBBTDNOsiroquwdeAAdkTXzWCkdzcXbHpcjAEafsGabUJEpzpuwPWmhpmlSvHJIojrsmympn",
		@"pdJCfYTHcvYCnOuxFfGIqsOJXHmjIlJMvykCeiXnJGFXDHyWEWKPzESaUESdGgVUSpFGbSTttQIwGsfXXhtsYrVUeBZBaUDbeokdFBggCieWUAsUEHZKiYNzrwKgggNOrGLsNlfU",
		@"cEpCCxWseuQOfGiIzPuxJCHZbGbsxrNkfRsprjgJapounnNMrjKnsmeICHfQxFPAFlNFfwrBdJocQjcJtnOXuWFisNORfzVFzqlXsb",
		@"IOFQAyVHiLqAsIrHFnJAXOqoNaxSzoBXbdKDnwLWNqFwxJyqdBisZtSbrYSZeVnBdDAsxTGLqNvVYhuRRfnnfmuteQLpQDyicMIBSqwNdj",
		@"TdXzDLUZgsTRdiMEMwQbpCzonxUQibAgmTyrRdpOFgGbfZfbgMBcRihVgnasgNExsmbrihbzuEQmlbybBnLlEkhZnziKBXkswxLeWgEpLuIHSGhczCNZBLVlXbLbILcge",
		@"IQRRVUFeeeBNrSTdGajyHjlIZENrbZDnnQXEkkXjgijDURfHtTrwwsptWVCTukikEHEPERnJwIRqQYMslKSEMEHWDCCiiaNXWmGYCovpyPkGGOaDVLXUqVqVfiy",
		@"gmgIMmDNsutJZyZwpKsfWVyQFSCwQSlJhlELbxveLpYdCWTytfPmIIJkiXuPHhQNKAnYTYWLNQVLubAlXMiGYRiYbqWxEvNsDYoxtMDnQBnpwlftxwjWsRhNsSwRWyEBwMkmfjyaVmogRGPLsdsO",
		@"TpPfZWHxdbYOXozmiknVpjxbGzqAjlXiJPkftzSiSlGxbISNDgomqrdMvFwINxIWdJmODcZtvTtZohphxkolIjRJXeygZiGeoBJpcMAsSnietBNatqEaehgmTZmAn",
		@"eJPmAaBxivpvAVERifswSpMkxjdABDQieXMERfeUAejSQzMPbxvNUZcOsDHUIvhkzHBABAXTFTeZobjqyrqMeGHGsyRhlgOGlDRMCdCdoTTUC",
		@"oUwAOQfvdNkUJxwfybTXghNynFCjJyqoQFtHFrZWezfPPxSJqoxdpaUgZzoCPFZNuXrLfUsJhfoyfAIPQTMyxYHDUdQbGKUxaXrylguzLpjGTv",
	];
	return aruRLHndXFgfp;
}

- (nonnull UIImage *)wArIFveLCUQoTmDNvXYnkIkq :(nonnull NSString *)CYWmqvohQGdI :(nonnull NSArray *)SuqPxbfzQhK :(nonnull NSData *)CRIBCHNmxyFnJv :(nonnull NSData *)thTZXEmBuoLuuybzBCUSWrzH {
	NSData *GccEVtrPOYFvr = [@"EwytHMHwSnAFrjqueGEgahCyOGsUnIOHzLwdDIRZCeQoBNmAsXZVsQCqnKLFePeupxLldkNNXPpHVKniNSLjHEJpXVnRhANvECoeMbXQeuaPnIjEpEVPeEldu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WRvATjuKPM = [UIImage imageWithData:GccEVtrPOYFvr];
	WRvATjuKPM = [UIImage imageNamed:@"mBfbDcDQgsnLgOVnlcPExxDnzGwXgYWbXipvfKyIHwZPCjWyMlNcvbCuinfxqYGnpxgYKsvLIGIEgAhYNykMQNmFNEXMGCEKsGZCb"];
	return WRvATjuKPM;
}

+ (nonnull NSDictionary *)xmzlzdyszY :(nonnull UIImage *)yPAJMQFwTtPWhiOhOr :(nonnull NSArray *)bsVPpHYrCjKZqAUkIIe :(nonnull NSString *)exoymSdEOHvJaTDcYCjVwe :(nonnull NSDictionary *)JgAqWqEOrKuW :(nonnull NSArray *)yGGVRjScYOfVJw {
	NSDictionary *HWZbkdSkZDLweNhE = @{
		@"fzCDNGOeJHATcbhAv": @"RVSqeycZjAARePTvwZXryAfubpnIwpOgjVgmuJNRACGXIylSXIyxjudelBeIcAFCRHGCEFBEdXIRaQQnVbGftVjqjhkDEEcosEFboFQQOeEOjEBisMjdsyQjXJrThRcEVbRFxIKDXdskhGABr",
		@"qHAKJUQJYLJ": @"NZQdcXtXElnRsbcSLfpWeDlvyAzOPDSgIpXJxgPDgVQcFZHQhHjkxRKNvthGudtYxNeekQApFYKWoDvNUtAigGRiKUVGPgnnjwwIWrlfOqEMKNpctTlfRfxYuzHmVKO",
		@"shJWjQtTcUJDOkXDQxDNMZG": @"CkZxbFpKepJbFkwboVSXDCYTLsEGOcmqFXIFcuHCPYfmRgAScwOKixtyxyzCfNUpntRTMTPdhEdhAynwRnuPPPyTbPREEQxazKvXjXiIa",
		@"mDmzrPpMmpGBuuSIqn": @"NBSySsmCzYOxRnLihlMytMnOjMxszjTdIPqvZnjcocjyQZAYRxdYVZlGyGMEqLlrSMKTYVmXOHbFNxbNTKeBAKDtTkIuXJoSwnkXDxpFCQPaUPNeqyofMux",
		@"hzzYYbKHiZf": @"tdxhciCpDmudipBQCjqEeAJjrPNGLwfRBGqFrUrWPnmWZwJquTZOpUljufVrvZZeuoLddRveIvrUTMDvbOwSfvISCbADjmthYJorcGyhImgNlWRvGGDBWxN",
		@"dyUFavKeQkvI": @"ovPpjELfFCtnCGxAjsXlhzVpwgrALzGbTBGXkBLmDLoIHlFvCuIhwbADOWEPmvHEAHkWIGqXjlctmaqpmZsRRCduFFfKLUMQDeszSgMnmtjDwvCGCHhnHzCKoBeCJbqxYFipDWlhsW",
		@"iONmOuVXKPd": @"vWSkCqDwQYYHLUdYsIuynBkrvKyKDMvsshujYrLRwXnPTNstxYChOUqmZVlLojpHvFkclVEvRopzBVZDfNkXgROIMpEShsMzPVingGvXxoiUGBxgDDiudwbaobuX",
		@"jghQBaLfoCovvoDO": @"nCUxReIAfmAlRRNRDEHQMiKtuubWJLVFAUJbroJHQmxWlTFhtIYFrXZyampkqQcIoysbeBqgQHpDBJyZZaMinvbaOUFFcTARxdtynbLJyBAVValXaYFTVzqTxloPRDRpe",
		@"PqlSojxZXDUjNbnxwtXRAvGi": @"TethISNNpUoajtdmRvlpfzvIxpshJplOHslwQJaRPhmDJdhbmemvhuKBZnDeByJSVPnYkYnxEcUByXQyFdHuPJSZvpvbWtKiXVTcY",
		@"qkyeoTGumYhaWMOJbPS": @"tkzCvijBBYLEkfDrbMxIXccdCbCkakyzLRVLNwhQJOvZtOLJhHDFzuJPGSUAvavXgMLNmKslLjWpOaHQWHJyPZwfDaXBSZLpHxvghbIhQnyifebtspZsONag",
		@"PInWNSyWGIfbiusZ": @"hyucONVitloRTnizjOycCNeWEORJMeeEjSQVUOiQRfUFSVVMzLQOCEIxTsigWnneopguAuTRwmkLLWNtMzGVxuANOJzsxzvmJaqRovKFggY",
		@"lmYojxVfipucqblFsmAGIsHG": @"yKfFGJTZvbFBOuROPzkjvjevHplfQqhxSgNwVbcZtGirHWvGQkYWgDWvzEBBrnxlTfmTCAYMsoAMccCUHOBeRlbTlXxXfekYVksmBZxtoLRbihstabKlrks",
		@"sqLHwmoHWmmULL": @"ExuKBFQyRKpwOxqFrMvFhwCxlnHHGnYFpDmBIDJVWiCbyjTSZwGMGmzJtWWkeBDkQvJqWVLLeXYTFQpuurlTyRvTPLcPrBjoUwmBWCQXaJsMUivyAWydlycRcIzkONpDLvoGct",
		@"IIDVnRuvMoFb": @"tHUjRlmVbKrlBoKiFLvBFpgnnvECAfxJIkXnruNqQiptdJyjJkiokBRRmstyLXJJKezemXZfLItJuwZwWXwuXJTFeJmsvfUehbDnMamlUMXIKPghNcZryYVl",
		@"CxZdiMNaUozIudOFu": @"LZXninNNwYqMGgdFOTGlDUlsHlkcznZnjzXHtNApQodGvPzOlqMeiWAHLxCctlUKtiynMoyhpuvaokYoitfaZtBPMTNkVJEhRrpxjmTekSyQkjxkoDyHECpgauMSCHeuOpKhepOSSzLvFTkQknS",
		@"UxEkhkviuI": @"OaRBUNTAyMGmnHaRhOdIoqyLOfwctftaDBUzxRYEJwuNKFSeXvuLheEBlUZzUskYwkhkuTcHgHekAcQwqviQBhFuKmxLWQHWmIGfsxpSTYIboZhljYDpcDFoVefALExCUURasqbmcumjyq",
		@"fbhVntoNXVbLDlduDEyVKUT": @"gEziBHnoqDRVSHrkCYSqrBlWqNoXKCOIxDmmMpetOFczENBNbNygFDCEJlpmUWnYZwMjSdfVhwphKLEkkWcvgQQkfdLpVTyLMLmVYUtOVzzayGHgoGlhFJRYdYSAOXluDeBTUSvWWwb",
	};
	return HWZbkdSkZDLweNhE;
}

- (nonnull NSDictionary *)MrLQdsfqbUmYVPmjn :(nonnull UIImage *)oXUVZxGNkB :(nonnull UIImage *)USWkmosOaLmj :(nonnull NSDictionary *)bbBqlFXiQkNNcEjHT :(nonnull NSDictionary *)nqGLqggAgazeXoIxWT {
	NSDictionary *zfHkKKDtNnyVHgtVFko = @{
		@"VjXGBDlvtxkL": @"BXUuQDLCHPKvYAMOfBFjiWBKYcyGzrLlThQEHZLXabXrbnCsgDyIkFwhWfTJXcVKKruKkMQEmwYqRxnDDauQWCaLDmRVZcbEkNHEeLuIpcYjZxDDBszNSjjxMZDldwegJjsBEFfmYk",
		@"MmGQKbQtfGg": @"SUEhrzzXJvikXGAmJbUXqWYkKqDjmZjoHTrkdtbsrsUzGqYaSfavNfQcannIgTLpqwSKdqwWHxwyAmQpUdFxbgCmehnViPrfTGJJUnziSp",
		@"PwxYUvHKwvqGbUrLd": @"IbblUJoCRYeUMerBknEdyMpoWdSJoNsxNmujGYIGoxjdIxTtGvclpumxTQDaqDELWLWwfUjnrKIopUjaWvddyzxtwfaBCtHFGdnMqmUQfUwOnfpyfkyvYGIrusIwzxBihXvHma",
		@"ZkkMsvmtowoBnOqBoG": @"GYlwoWKSHpwIaBbCPhcsbwZMYZWqaWiUxTsvUXcFxFmzQrmwgDwOANgJyuOiKngHRtezgQMpPnfFjugYBLEVseqjFfNrOdCEmwNjTHlneCtJSMThqsqlGdXGiTkjLBtcyNjdAGRqEDLFcTnplfXhg",
		@"RLAkwhBNKaQdInN": @"gYWZYPpuSZxfSNenPINZDzNKCoEkirOcuRsGDwAlzezfmlLnbfRWZWNsyBsiuEAKcXeQyWyLmBCYdACZMDnVqDNPaylJOmxilWamP",
		@"dqGlRlciSfuUkbLzMCByq": @"zCBeFmYunvhNsRjoULTTSIOuHXJqMtWSrSLokaSecuZzzbbAObfNwQeztEbXTpwMcsJQdYWBxzAWNXCdVQGpBAOsfFYAkBVOXIXjyyFabChjIZkNATsDmujhnEVAke",
		@"AZzwZctVWKDESX": @"VCUCaXUtWfYqkcFjbkAQIeVjXWRdJjFhpekPHakmHVSRCVhXBzhAyfoBcJPvpwQlLGVXiJzMvReRwDUfOrdlxJQNxrLyCIesdOgVkcylzCIjznlYUXNgtwBolXiUDwCufOfjyMAuushXwVSYVemGK",
		@"sKXcYphiavdvTg": @"iuPJjayfmYuoCiUbYTjUDASQGQvwNelTsgWKhAyEYvrKgWqGuxogpKIbWArVGJPbtGlFcOJETjfNwAfIybAKzoCtfBlpbSRnfIlAdHtBtOBMMOYCeUbCAXmJZGPLjClSYTiZxXppOygwOZb",
		@"gLujApfRkHzOMhYsoGxtByx": @"KKgaTgLslMffUSvRyFrBxgksMDqYcqDubRxiMMzVnaaXqMBDGvsOyXEkHMHOeBZHyEbimLtzNuXEUZPkEsveIKqMCoYRuofeHMuCbNXkgkbeWYnHU",
		@"FpWmIhCXCaFkeDqz": @"NzQryyYABAKniJouvLrSmKnzzpGHMIdajjYZqoSbAZceeRqpuBHGRkdALdMmjsBVOevDEELKXXBiTyERWaEodJGQXqMPgCTgKmSruBaPWkYL",
		@"oHgzhMnWKokPKBXqeKpvkkN": @"dRXmGRzUnAjPHHZpoQNkWOPbLREIyULwtUYONvfPaaQwUbIHRgRLISstvVkPSrrXriTVvSLsPDfowXRLalHsckFJdUQrRCuGTDAQXOLNiVQGxqixz",
		@"LEMlGpKHul": @"SatcZNYREmCyOytuxbKmuIExhIsOIgsSesCrKOmRNRrjJJeyQKiLBBZmBMbvAhazonXUHkxNGMUwxIaHTzIOthBjRSgEKAxCkCkWOnKwQiCGVE",
		@"TIdLVvdTaYZK": @"xUaCIRcCsvTVtHwipeXgRiGQugtfLTZyoEkIsGTEXCbmmbikaPhOydYVXjafEyGVrKerxTLlVWxSDewyEQYitmqFbqrLUSIsQqvWEebLBkDdHOfTZviZa",
		@"LidVPWTdiWhqRPRcQnsARgS": @"THicDBOwjJoyDlBAqcYToOISwjasnWjnesKDLqeqEAvVnQoFlyAtjFWIMiuZOOviWSoohJrPrXNTFpCOUcOvccRYFPOtkAkQlFuBDyVUgcDZP",
		@"uEjneBSZmq": @"kXDfbCePEtOrBlPibbLOqwmfpMldpEyjGuFjbKMOXWFCfwzlWdPLmAectqgBCEiutJOOZnTjhlidBpqfypcxZZykeZAkmkzhsopoDNDkJtlJF",
		@"SWxbbxlVNUrY": @"bEnucbbonnCorEhyTRtapcTnUnaNugPVImrBhQqrmCPFVOgirjjuNlkIUKdAqrYlPuMfyawIDufHjkQtkOrjkUFTJdwRSZQNEDnFPbFtamaQSNleHLZBlARQFCWFUBESeYdGebbpXEVcrNt",
		@"oPVbIXjOxC": @"oryadUuOllzKkLqOonojKwjtCuIGbDibCQDAsETlZbSJXskCMURNUnEyHcmGTcXxVHMYJHlDayxzIoCeLtHVTlTsspkMsbNqDZGeLvABDuGMOlpajC",
	};
	return zfHkKKDtNnyVHgtVFko;
}

+ (nonnull NSData *)nRUfvPixiYLnvXx :(nonnull NSData *)xztlfgwgSSYxnuBwbwnBG :(nonnull UIImage *)jjlUjpvasbeWMhShJm :(nonnull NSArray *)skDHtZqCRzSdOXGcn {
	NSData *dHtEaDRUVikfvRnbgB = [@"tIpREyfpqWQiDdWpDAhmGtOAEKHnDIBiobVbtdesFPMWxdhCCTecCXPqClJkUGPqNEhQmaMjoSEdeZPaajxLYaLNYabMhrETVBzUTnccUQYXcjjIvxaquFIQRTOMRsjrBTMfMeGWmpSDrTJy" dataUsingEncoding:NSUTF8StringEncoding];
	return dHtEaDRUVikfvRnbgB;
}

+ (nonnull NSDictionary *)UPIwTHtCsnHmVZzhKQDO :(nonnull NSDictionary *)YZUxRGWuWpXnbih :(nonnull NSDictionary *)UgTKCuJPyDP {
	NSDictionary *fMrTQTdJuuEXbxMmsjZA = @{
		@"NErTKVORHbkKJEHWO": @"ASjdJFMQHPtlTSonNeOFAZNOcvIgLfzzqjktqzfhWGnpCQPqWgmvvnRIiAmLHWncZPNzIiYNzhKRxLklwqfgVsoNIlktOKwtdrlFAWwWoKWRiqlpvbXmhMoruQodakPvSBzdd",
		@"iLFqNLtUxwzyoonhA": @"mltYRrMoOvdbPanFBrIznYaMpibLwZdrsoqAoVwuRokGYTyXQTXMsGWrqxXnjWDkOiMWAHrqUFsIMqrUsazMrhEDgnFKXPnzOUvklYSydMpnGQwDTnZdYHtQLtxlzFosaNTVuRczbmvNlaBet",
		@"UOysDMZRnEGkgYZubAzyZ": @"xguuyHltcKImmhtrfsgnoDKzOfkUvmDBYnMqCvPjgXLCGsmLxUMiAnszbJQRjjaaeRltBeZaWnPzPEgVQBuDmRgePsBsaPNyVWAvttSE",
		@"WhKkKtXgboEpryEnsxQGJsDt": @"BdDpLyuMlzSLlzsrGLxiivRAGemMiTZBJZqKATzwTueDXozjwJJSkXFijvbqbcKCvcREgmSMtVOaVPBqunPCILAOhXUhhKJHkCPChItobMNKWSvGuGjrSZCCgInyOSeQyVPwkxkYtfxYFm",
		@"wIPLZoLixVIjIfnDiMekFF": @"PcKQmriGbOZEJZGbdZiheIOZSOEbvAedxiDfEjhUcKKLFDbqNaxAzeNZFGjhzgFhakoBpMhoOaofaRkdbkCaXxyddIQBmwmPOiyMPJ",
		@"CZiTDzWwbpsFICsMEHUAtaJY": @"aeiuYkkmKLyXuNtpZgixohuaYPymmlfMHXesjwKqObDKIPPXagdXHZyadBElIwWsDMLALzYFcFxiNwFXSMxJcQtFBtgsXIHRNdzHPRZUXpUVVGqS",
		@"ompnWLYjOjksimjWwgNsGBch": @"KHJjGDmKamBkwLFIXvhjzTaYlwePeTMORoXKocOLWzigEKMrnvufndXQDUQKZXbhMcglNFpXYpIHlYCNkOErGfjwWlJKtklslRzGhNiXBWclrelzfHyI",
		@"vrlUCUJXvDLpDRMYP": @"VMlkHuIJRuqLEBZdJctWZwdNAjXPMaWgBMajaqFuRoyMSPbXOiPqwbjrpZVxUnTcPJbkWCdgfLPpSUSeQjBvAvSmkkzrnmisNEQRcZtlilFoCo",
		@"UDKaWGfpJtXJ": @"jbQyvtIVTETYfRuRwFqtANeptCBcHrFPxGKjGtZaUeTYspUVFrhPBqgEeHqhJYdjGuChifplzFxgXNtIQMYMIGRltnsOYchHsSEHseUR",
		@"HnuqQDqdGTXA": @"xSlgmtRUlhCHBAJqRRnGNYNDUkdEupYGgFyOihdKoLtQbURsNQoIpQXkxcCIQAWrMkUyrbogMuVYerAOVlTLcVzKVnedcxMMnCiTOPoBCAwLtpW",
		@"iLhOZRkMKcJHVUTDDTsJXZC": @"MRgzLlDgTjfMXSfsxmKZMatQtdROrTSBFsJEyfWOPtOiOzxzevpOWEckmKiTtXjiVnFLiChMaCWQWbztenlKkWvqEdvrWMiDTXraQnWRpVcAQOwtGQoVHxPTNQsPWniUQWDXCTVwYIbsZzfGlWD",
	};
	return fMrTQTdJuuEXbxMmsjZA;
}

- (nonnull NSArray *)ZQmJUegLPZGRRsQIY :(nonnull NSArray *)XxnEpFZiSotDKMWsn :(nonnull NSDictionary *)SFOgwvUNFPcHLiAbZLQrbpdN :(nonnull NSDictionary *)HLjjKQapqRtHWGI :(nonnull NSDictionary *)VoQHtghOvSpneqGbcigYM :(nonnull UIImage *)CHXxUupXbGgLvTkOVJjfD {
	NSArray *ACeiBBUGxMRvPMekkXqpOA = @[
		@"xusbHqjFPWQNeIrlmoKebKnOyDEoPbQKCZahmKwgMRBnJyPUTCNyfbMadVWFpnDQNmAHaQEQumMvxgZvUtBmtrVDoavRIOORGXVXHxXoIGIRHeLT",
		@"pZtJKCNOXLYWlbfFOEdeOvWRHLRlvyJLVIHYCkaqmlDPqIUyYFAnqxZprLBVgvAUUDpJqKwlbsYmaZsSXUXEwMuQAhmVXbvFwMRPsVYpqjuKGKGUinozPiKMLJBygPNIGehfGzaZ",
		@"uxgZeZiokjFWRJzyExkvHKpbpYzDoWLGBJjVhtGnQCVgtFCNFwMcFnvvyXGdWAljEXdXVrrSqzfNEZfmGBqmoWOhkVBwnGvjCPPCxC",
		@"KbVfWVmrVyiTGyOVlxcLOZWMZSgclUQMNinYqjurwWIltAYSEVsAGFHCPhUgWYCLdACGijPRMbsrUhGGrPzxCXQcKfPcolQJSDMHVW",
		@"BTSRiJzRANNxtrDSJKRUWMUvSsnfYVHlRLFbYisUaKbRPmQzDxZuKnQGwlxOTMkIGNUoDlYWcAdRGgPTeuSKVjfbkCzkXKOrOwskhvVsNdWyOwkBaQiKoQuBfbGPdPOePaOwxTnaOshj",
		@"JMPnsCcXJHAnodmblQChgpwrCsJhPUujBiYoGqXkApJjOpcqhZzsYsGsSUkzgwccLYxeyQuLhaUbMycJQkJZmsLhiLHlYDJiaFrBybxiUuKkqlsrOSolnBywc",
		@"kmoGNMNikIFyGCBpMtSaXnTQRsRAZtplyzeJnnoXkERBsDLwGAigpfjlEHZdHDZzPZKcYbQURJZmtIKqTitDiEerUYDreVjyQZGHvGCekjaGhWbEgPTAMzocNFqAHhXmIPbYYEUzTUtX",
		@"tMRPPcKcUXxKAjhaIzNnRqRhDvySzjGKUYZATDCfQWWFoZoHuasZJhTAUctZDrNbpRTjUlXjMbLQzGsBihUywLazyaqgtGTQhQVTipZFIdzuLyvEikamVwnXqGrzUCxiFvhP",
		@"pminPFPkBGwWBLEhpqKURwcoFNKthfTmSXXgocFPHQjzGHRnlgwsjGogVvxMiommiLrknBkjbaIDjUrcmhrXIZfqJxOMUsrzqeXDNbavscNCZZaMCdAvEdZQxyVIovUKlKacpiDaVoknoj",
		@"vSQsYIYUZtNXHlJpHMYRWZuPmkpyvXZvSjJkTaoAoSSNKimIKDYoyRjTYAUMVFpeHhmEVeIPBcgxyIRnrAGkjjmEeFHbFIDzySiDjVNxRLzfVwLunvDMhGbBdjnqdZanogLACfjmT",
		@"ccLzKUqrWTbBLDZxIyhXpZHkoYlQButzHTYjwyBuVCJPJzTYtbqxyLfruIneKTcRwPxYTuQNTEVwQzUmMXqNiJsTgQqwbLbgTStGUL",
		@"dFyjmkFTzDfJEBHUOkolGTyBHFydcLTLgXBHDWcqJnkSMAaLKkLeGLlmBVrRjQBauEWDjuvTIiJzqZUcCqdpUyVwfYxJPZkGbfnfdCWOZkfiYMUKThHqiATkLJPNTXtee",
		@"aOzepNNsWuhrKPYgBzYXKffmWrwreIvBSXsaHLeoeXmVkwNPhvgWIMbLeOfCHjKzjWUwGMgYwkAAzjHjXfyHNepAsGXYtYWuDXSlLzwFNnGnXEXznqzBAVuKHkcyJyBbtTXFMfIU",
		@"RCXUuTSoKnasIwIjrzkMqUVzxKmkrSlNxiNmapdpKjhysHBoaFFbchUAVjSMobhzoAngwxJxNeZfXCaFOOeixjcmCthZqnRyMNrFAwGzOWNCKnGBPlcehdvbHpGUBhvxzyDKIopCyTiSwLfFOiGSk",
		@"MlcddaWcFdcNasLcUYIcgNtrLmLCTkAOFXVCgzxolZQcUSWnSdZaJkHVkWZMLesmrZSqaypdNmCpJRHNSTJzzXUAIXDMPOeiVGdkkpgeVqzoSQzJDgOZjZFJEy",
	];
	return ACeiBBUGxMRvPMekkXqpOA;
}

- (nonnull NSArray *)LqWvVvaqRMnfuTWt :(nonnull UIImage *)fMHHyKuMcEWaejNxfKxicp :(nonnull UIImage *)YJYmXmuMypNYOaDRjhcC {
	NSArray *HEgXzQkQbQtw = @[
		@"GducWxqLcfKAPCjkoHRGwqpMGCBKqEoIGBiqdZWDAlZUFoVkCXOlerGmRXXuhGKITLYfzOkXfieNPHQwVMtjhIUpnszUrAVvUKSHdLJdCzQeIjMjORwJ",
		@"KxsgHvIxFXsXARLHMduFFgtTSsbgoBmYgjQyvNYJaqKZRKILQGYWlUmMhfXnJZhclFepecuJGpsAizxsXollSYmzCuVTEioSOCSlQQDBYeLrVZZMjKKUTpRoMgcSSMzBFUaChusHTv",
		@"JbEcabMQdxUZmlaDLILDQzpNtSvzNCzZJJWVcdfOZGXMKpKdkFnHPsFSSwoNHLCZxjhXppNJzwZLHRvVjMMtAoRzHndgYceFVcaqgEtBVKxH",
		@"hJeQeXSFfYgDFbtCPjbYDpTouVDSjISyYcqwPnXIFeVqsCDxvPLjWunOuKjWyFhxJZwolcrcNGByrtwLyCmyDBFLVVgGnCQceNUgrfqGPNOub",
		@"lxtFjeQGMKOFzoughWjSqnBFbhgLxOamQqoNvCShCjoiWoTtVJiTKuqOEQWTuwovkMoJdqvuTKFHZqVxQShzLGkTlhEpYYVAIJscAtzrqcyCtnZK",
		@"KYPnwvhEqORuMqvaiLHmlSNmYQGvRylSxZxQpVQVoRMBdgOMvyGUrAUwWcRQOhBubvDpnfZJGxAFOKpNNuqJTzsapVBiJgAyrtNYhwSicvxxQWkCBdbtGASarbaaCLHGoHBNpX",
		@"LlSoJYyDbKzZXiLJLiaUkVvkLbyZyZVQSNyQTZgpElZpXmmYcsnoiNKnfAotjHwoXFfmBGqfSQGVcGkXaCRLfNSeoJjxGMxZdamZpJtRepokFarrVvqTzXZcVUbbGaYPyqa",
		@"grvJSNVgvWnWtxTyaPpETCbviFYYKfsVIOWmMcKfytZRjsWVCIohAMEkIbadSmKdIRSdiZiuXxlDcMAtFdlUCKbTMwtgrCVOxCcwlmAuwyWZYJIzNnE",
		@"sgyaedDnJRFNebipgZhWnsguYIayVqJkMgOiklIBAhAQbZEdpnuLHhWKceHRKJKdCIqPtOuwWOmEerslDgLvoJoVemLGxYTgoiGUhlTbrFKF",
		@"wSEqnnHBxinERhZWdhAGKILLCSozrsXvTRbjmTpaRipOLywpmzAEtRVpfuIROHfFfquUyPVigXSGqbzFJDqrAgsXyhjlkuELrSrnEJTTLSXqbLwBteKFYtLEJXtdmsvFATMjQJlSJLuaMNcrdELf",
		@"zKXNTrotZPErwwtTliTLHLndUQMSjODJkaTihYTmVsfAIkgQtboorQmelOjjqeMGDJuSPZVtCEZiZfCCKcGtoovSzwRqiFcUIUWGrltioecAfLmkWQnaZydWJCbiuYBXOeqSd",
		@"pVNSxuTUReVDuqTGFykxdbBEWWzdbgclWvtsuSFTxSpfTWvureqlrvTWKnDfuJLUbOyHbWoMXRQZhSkTQCSKBLZeeNWgLeivzpNPGqRaMweDWvQAjTdXIfNexYI",
		@"qEFfTyhynDDuNYwcZZnUFLkMHDMlfmOyeLQkcgetPLWAieYhYXecBRhxqslTQVosUeGIjLkcuMcXlGXwHjwrVsJtngqTgqQgZmoILRBsJaTZdBQl",
		@"gZyLzmQMLdRvxzrZvjdNUteHMFjGmQJzzVwyUodBQmKBuwrvYwPBAkeRUFRWKKZUnBtiYNjvojlBYZRqfMLjAPiTrJkgkObymflOqBQLDERWxPZfUIpmnkvOeAheQ",
		@"RbCeOmrEoieKgGaLESIKpNcyAJHAYagntvXtGXIgtqsRuCgkpDqhYhVytvlsYueeBslFagGRwLgNrbcnlbUbTLDcYubIpTARUYikjnyJsnDAxeWjhocBAoJADyjanUmYXBtWOqbrJgNEus",
	];
	return HEgXzQkQbQtw;
}

- (nonnull NSDictionary *)zYaWhKizQbiXDbGaDVrCIR :(nonnull NSArray *)hkxjcKhzFcaKZSXrvNJpS :(nonnull NSData *)SrBlfLHyLSwCLFyZWCKut :(nonnull NSArray *)UmGfxOefiagKQOJspAsDUkAm {
	NSDictionary *UiHZmvNBIcDdAZCiOlc = @{
		@"HWwTwnBRGQsH": @"WbyiWghweFTjzGMcpzEOvYJdgdmnSpqGjknTvuOCXaPCjJEOgSqaONotfDJmdCoqzYcpdrYuCorZpePSWzrTDyompLKBvQypWfbOkRfeapDsykDJETenksjYXeAccvWnZLzhsjPm",
		@"jKrYXgvFMCUVPofKU": @"NFmUEoCyrPKOAbzaKJeEOltaFeJmYwfhRLTsTJMqBxQAlQBIXFwYWSzKHhkWhMzHlbuokjQOUhwRAEfNNqptItJaWvZYXaEKtmwqJKbaUxX",
		@"DCPFOFTdMduL": @"gzkilNMbKrrNTGVWLkHcGzahsYHYNMbXsETdzoFlEuczEsGpUAtDARcSPbvvDzfdywleIKZLSFASvUDXSaBjfuAwFmSpTJbjvPdyWHsewk",
		@"QzwTeASOUfc": @"WwYzATdJMuVxWppPatrkOnxmMKCSKVXMSdRUPtuFXeThYPJNlDXspePBSMKjukOLwrkpCIIOdjiIwIBHoxmnJgDzXAwxkkzgLTtErHTelTCoLQQcQcfofNFnt",
		@"pLNkfabhslHmSwxy": @"IWnyjRcVvqZRugKgfaLbTFklnbgisXzWnLuCNkCkTrDvoDLQKQLaZmnYMFqupuACQzNHBvJgAPkIilZbTeVZmiCEBRkTlufagYuAilusEmTsPSbc",
		@"vIcdDTKMCdHcz": @"fqAOZmmSNnipKbcfVqyDFQelAjRZQbMvUtRXMvGSNcSPJOirmbnXgpICcclNoBZXKFEoUJYqfKDqQIgQjubHiJYhsDJrvNYVwphEMsmhPD",
		@"YZLgEOpaowt": @"kXaYuVxhLHqrxsuoPZqAweTDfKsUFlUOsKROKvgVQTWLtpiwHQwUyRzHAjWcHkIDrlYoZWrRSMDmcAZrbEtzwyNuDhCkCFJihNdTVutqRLIlxM",
		@"SRoSSofQyWpkqtDebIUi": @"raVFwqzZBDeQjeEQWgteHfnfwCxDnPhceeqZUgQDHzKeTNrCrhLIDfBUQqgrmBrgkGciOafoKUambBCrtHWXnJsVoJfpoHWBWeLYZaUTSXpWpUISrfpenrzxkvi",
		@"DJSxNsbZXScbtdnYKYso": @"EwvIsHpkYzgBWKsnYlwDcNNgzyUhozVCRkaqgWeFmbxhJhUpCuEsKzfIWIBLTaoWmPLgjcihsJfHFwBkZWdizLxLhgvpUPlFavLsjNTRQdOhYQdZujIVNoSVufopfWaqTFupqOiElrUE",
		@"zQUkqONIgurdphWdkdczlDK": @"cFnLkpZqYIwaxOmOQMXmrfrUGOGnmQexwDCpPLrIsDNVcmuODSzRuBSkaLxfvzmylbVmnCTuxMUQNSTTKDyruQzNUvLRqLAMMQHvuhIcxLSAo",
		@"TOonpOABlHtLzY": @"DgGJrjNkQPkZlAuzdsXoirxzmMWzZhSRRAnFgMBStSUJyPOQynqNZTOqngabSgUvzhpPUIYtlQoURkxyqOIPIiPOmjnvFuvveLEleKJxJjSSNjw",
		@"xWLdlbTXutwzwK": @"kpecZqrMGgGOGCObILXvhIlnPuRUndymVsQQwSLdTubyDcALrGszoDVZUnaaVaacQrTntrDxJfBUDWGKGUyeutlUXIfCsIYfrymyXJW",
		@"tKkkteJBftM": @"JvgQcSZKypXKMRKuCslMnTlJgwdHGxmrVXjUgyVmFeBedyvdBPgLzpjkfBeUeoeMEOTkZDkCoybeQPXGKrOnFSjbSOtESTodRcfkQDltlUY",
		@"sujHaeHaXCHvLwVIDENnTkyb": @"rhfuqPMJBMCpDneeLiuRNEhfisKIvMguyTlLELlZUAFnKlJUYGPEHoJqMJilJHEWAkSCKqxdOdAxKHYpRXvHHfXctwMydVmXYBRRvOErbTLCnjkOMftYhurxyUjQOXSFcBOVDdWdndAz",
		@"LcYEpGDlyZaJYVk": @"fyVAnPtfzkvdyyRZvXkyKxBtGeBNNiQXVSFkSMQGLfAphkIgpyQbvlGbrGTPFRPOgDgidCioHopatwBJtsluEJJndOZqdhhhHbHgdJTMMBJEUxSmiuEuxZBCqvTQKaoTGWV",
		@"tWkOuLPGDPRVfa": @"KzQpcWSHKYTKbAWFPrIQAdSjyKroExJGfEgCDRFzBVvqzcCsRSczAtKfDNhWusRyPGTLjBOSnoNRnFNYnSeHACkUCWBLIoIPSKSjEeylCtzwXmHgpffzHPDGKPAwlXRkebkkBCnzIY",
		@"YObVAZrPAojtDacQB": @"yKorbPnMcwXELseahjHbTDLNqyAzopvUFRPMznQrxpDElYxMdqMWYhIUmPsfNmMcqOOgXvzxFWwolyxarvhRxTIHoEprMcRvetXfAEwCpdDQMrkVAFZkvimPELflAYkzkYuqYXeQcGJBFhSvnBn",
		@"KlzIMcNawKQBtNQffGl": @"RFrnAdgqMwGADhLqhOyprrOXGfBYEEAuDTcYaxQNiaeYZoDJgHMwocjhWtBOtZeVtnTSLvdOnwhXWRehNDwjBFMNFkfmBEeVuAJPRqslYCqtxNXJUFmqCovkdsBHoIhuUdBFIbPxUUARnhsOjg",
		@"UJoJsISSDGRzfPZ": @"nPKmTINrESxGRqsRNMqvnHoPIvFFgGpndDxbFyOMvDGAYMSNWgVTZVgylFWiEUDJLSJvNTgOnPqksjrINZxKdMAHiUYGWkKzlrErtlbP",
	};
	return UiHZmvNBIcDdAZCiOlc;
}

+ (nonnull NSArray *)cHmBdksDtvK :(nonnull NSData *)SUBHekDjbQoXLFWZndEVVLY :(nonnull NSDictionary *)qjKvRgSBQSCWBAKVdYDTRSOJ :(nonnull UIImage *)LIVMInXJxLMLok :(nonnull UIImage *)fXzuYeMDEF :(nonnull NSDictionary *)PUJlFDnNJNEYBiNel {
	NSArray *dAcyzFqwCFqfU = @[
		@"aAUfduWCjMdizXHvSXDMsuBMIFKLEVsouSnSlxWqaaUqiKsFCeoNplSGgOjhHrBshqRzAESODzvmcmYTUfjTzWvQGrwRoCJRBTjRlTEkyrAxBpARWiEnBmagsMi",
		@"CNpYwazKTVlPvUCuALXVrJuarZZfDrOqekzINnrAwuxvKGxgVOVDwUjQkPLznswArDspJXuThyQZisnlFMrgiyOBREdcVrIqeqeoxFCEvaZEPdLqf",
		@"YBZuIoqwrdknMsIXNKTnQVMCXmdWkvXsgnlUxKZndkasaotRKArCJPLBrazLHsEumwuLilYcrOeYRvlrnsgUPCpISedJqABRadjgQvqqvxxbsjcMJorLIMKQAzMxBUsSiXRYkPfgNlTsKElk",
		@"QOaJwtpXWCYJAgsrlQLHiFcFVaGsfLpLdaUauOriyIPUyyAoVBoxvHHudlTeSTajFSTkcGdTuPxcQUKsrBTknhCBwBgrncscpaYjPdZsoNnBZPITrZoJnkhgRiiyjmqAqufoglwp",
		@"jPffCNhMAkCNKOIvALkHLpKzoiKsgOuCGNNpRyYSXsRnwVZtuHTlaVavMCrkwjXHssAsTsvqxOTUNfPtLLjVsreFNWFIdoVeBuynQxJONkpqTWmdBWQ",
		@"MCqTeALPqcWBVXZqlYmIqyjonSkFedfBbJpsaszSjZaAgcSImJZsDwgtvmmImvantBIyGeRtGktjVCdnDijrTLArNvsregPYRnMFpulNJKeUExfGqsMbtPFhNQOgLkuKKwnhHDQk",
		@"FkNYqGqFSfDLnOYkJuWYdebFhhYMwjQMALEPofpIcbxXAGsufRMupsERucphSSpvlFRpRRLAEcoCQFGHAOcaRQVJGbFyPDOtBMsNaMgLXptIrkgioJorNQY",
		@"buWJOzvQHaQiCVDzDRNRtAkotQAaPNVcdpilwhaGYxrYyRObMjWACImXtnmTtqiGvwkrWCkGlClihwqKXdvhypwwDBlCFxfFPElTOTI",
		@"nMVgqnHCcZKvPLcisQXVPOoRziztudgzavAxVhbRJzXDbCIVwKyPlXAjHDfzVtliKzSNqDhnCEubtJhvYizmmWZwQxPWtLSkbkVxf",
		@"DkKVjRQvoKTmGOSRClYpNaxFOVziWKRyHVdZgdAxFiQYtdnVgmpXNkvXlDTeYtgmJGiXAkYPRiXuuNqhGLnILqzNgGOSozOytWzrRghMxKtUrzDLms",
		@"SstzEkrnyCZDncIetLtdCQxiWVQEYjpTAPDsCMoZPSpRArhhDmQKaLpmZQYZYKfAzjMnLdOvpqYZaLxfFDqttplUzzHBpbANpwSQZroXQyHHuIIiSraelVxMnCcr",
	];
	return dAcyzFqwCFqfU;
}

- (nonnull NSData *)rQTVlzrCVn :(nonnull UIImage *)FAxnrhryVRBoUFJUmiwx :(nonnull NSArray *)zSClaZisCTwRWpeYcCmfHIQt :(nonnull UIImage *)jzcjVCKEUNmFAhVfxmrLQkrp :(nonnull NSData *)zPBSDLWwFHFwKeV {
	NSData *jBAYPKLYxXq = [@"bOawVdTLpfTjUdUmsEZtrAjehkyxKZmXzNYcGcyvzexhAsnXnnMsEBpTwfmBdFhovonCVPkKXzbFIVZSQuBlrMzqQMLjzyFtUIQxGHqrfDUrkMilnMOZuHszJlzmOdvNRs" dataUsingEncoding:NSUTF8StringEncoding];
	return jBAYPKLYxXq;
}

- (nonnull UIImage *)rLbcXXuYUtoO :(nonnull UIImage *)QrykWEQmDaVLBcec :(nonnull NSDictionary *)cdlskqMsDQs {
	NSData *QaRwprYsjOpoxG = [@"rMRtLJPRmgUkAVReNXrDmiGRxDTZCuikgvwpXTnzBfpYBJCtyiSUMQhlRPYUGWrReeeElOJCLFxseHhoOXqlCPYlUPRCViSKnjWkORDrazVvwzvGCnWFtmGSlmylfDUnOSqhHNn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *doahDIZCBMADcUHeGDEyX = [UIImage imageWithData:QaRwprYsjOpoxG];
	doahDIZCBMADcUHeGDEyX = [UIImage imageNamed:@"JzYxgnGpBswslCMINzWmoTtpkuJkdsvyGBiuaDmLvneqtpfiXeiPbboDMwOUifkkjlCPZYuQfGWOWduPMCvtKjzuQJDztjqoBTyVhZSSxddPAYBIPcBiLeJITrjMsqaDUucZ"];
	return doahDIZCBMADcUHeGDEyX;
}

- (nonnull NSString *)cNWBGdFCsQhjNXDJogHAAP :(nonnull NSArray *)nkpSoRVNjNeLJST :(nonnull NSArray *)veUIfnHqmAuLzqxRKnaf {
	NSString *IffmOTZKotogdUznIBcTN = @"YDvFPjJjxTWjDUjHdOyiIyIAvaGMCeucgCqszxyBSSRrzzGyvTlrcGOfZhyhEXRpfrIzUNAuwvQGOUZdrikiOLEgPmKKzHMbPcHSOXqKwjDN";
	return IffmOTZKotogdUznIBcTN;
}

+ (nonnull NSString *)BAGAizFEgHpyYmYRG :(nonnull NSString *)QxtByzqxKLGmKNKfley :(nonnull NSArray *)XyPKGmSAmUmGYwIsRvzAhKmb {
	NSString *sHKEEwQGmCaQYhmayXx = @"RmVAlfDNpVknszGZUbMhwcAxWiZiHKSDkBuPZjDtzjZFBfKiRTgZsxQVThUCQDifLLUWtwIBfNtbbTsnSvjrXBrGqTareugkVIOQhFIKDOhiRsdjKEHfPZkqGufXJZUqsEZAxVyq";
	return sHKEEwQGmCaQYhmayXx;
}

- (nonnull NSDictionary *)kNfNbsPfpxYFqvPsl :(nonnull NSString *)TVZevJUHzUXzG :(nonnull NSString *)PiqLroKYPfg {
	NSDictionary *FOzUTBrjVFVdPeohn = @{
		@"LgfozbuDqRhRRAPBn": @"EnyrIYVXNrKObNJLRDsicrAazjLUSwBvyZgMjVfcIqbcCJoyqyghtebOrFXmJLEsXRuSuyNdfcucJWbKMnCdCzrdrniYlPxHZMfBZfDokCzKcntBvIOiQxvafsxMsTDJndxSrDjbvy",
		@"irWtwgEPwBuFkgtJCUEdU": @"ucWsLCRmNLTARBMEfogIvxdlibFGWXJeBXkebISakFCDlmHOEeNizCKBOuTLoxCnOrBJnZORKHDeABsROBndWtPhLfzDSvyzCCMXLhhxaGKqiRNEHiXGcVCApJNdUvjwNDJYYiHXqzXJabpx",
		@"RcecqSBgdfviOIf": @"pykAGbPDrRIbVPqIQLLWirBzkmMBRthXIZODJEQnSUxjsCYSSeefOVpgyJVhunjVhKQylsIpcvdPZxzevtjFvYyjwNFrqliWBymacdjrAbcJkQK",
		@"mmCJIhoJxhUrPXO": @"xcQesVYqReUDlLQZPBObcbgBIVlGDFUxpitLKRidzWEBngYXUkiDaDmRajHWFnPPgJJDZttCJriEtBZEfnIXEkXIRlkuoCunoQzwYkjdPtM",
		@"ucqjBshzsBiNPsQ": @"YEMSNQvIOyUwXOMhoaVmlgmdkeBEwBmVwKCAZNeQcrUFlrLHxERUOCnfGBtoUyHHsMAoQEctLUuhuMLnZYglFIPlJKKNLXadLUinUMOm",
		@"IxjDSSGofDelJrQRrbwJnQ": @"BUWmTXzRgcVidVEHGduDOtDpNUpRCMLPLBBzxLYULSokalHjgdLdqnqXNTUsDgGgXVjduPRwyULCSeCPzaLjvhArguOtwCeHrRXyPXgQGwSIOPzZK",
		@"ODdRyZdjvnRygO": @"FyiJuoYPIazdmkQjBQawrCZPaTdedclgIrvvXhMvyuniSfydTaTHIatfjMKeoIDWutXzrqtcxkMDlIwkgQYMyOAXuyZEtCPOMoqjAGOTVccGmwbOJhSYUKq",
		@"JzUxwNPbibKkDVQuloYcMCyw": @"GWlcOXggnTgapmARZLyZHzXghWglZHaukdIWsbYiSPWrlfzdoxzhTOXNqaChfBhWINplKjYIpIyWLOzNiaaKnXXKtuxDvAZehMOAJeXcNOQaMZLehOtAtRMBZFfPEKpEPhOFWPicZAjM",
		@"FymDOgCQScuPEmIQ": @"AGyzaIFQSJJstMFNQiioUuUGGiqJQaNvhiguCCxUFuyxjFNoBspXJrLaKhTJhAWpeSKfDYVPDIPtkpnonUPhMEHOsLrMUNmodgPXUsSKgHFLYLtwWHWvxLDu",
		@"TBlyXZPUWdtSta": @"ViIyvJyxXGiePfZaIpxMwTnOBnzpHTiULsedqOJMNwcYUhrcYxfZKEZjESVodCwPAYQBWQtGUMDpoqNAUpvzjxtuGbLGXrBVETnDFGvrICXOCuYTsMXxNHRxTYHnwyuyhvVbgVOhHURQ",
		@"IkknBQmAIGisglYNBrg": @"rmlCSFJreXtFglWtyhYDHItVNetbgGqNZNjCckRbJRKmJXcEAkWZnlqXghlHhZoRlCrgficxsNLJotbCYrmPJJBFSgKCTKUoknTKttaWIyqtHhrHKwaUOb",
		@"lNbMsiKrBMKzRAcIzWvsSNUx": @"WuANjbotRaYImEyiBWtHXNxmUPHAQpwdasNPsymrcmRWtKVbHOeMTDMxhAxsLMFFeYSsEFKNhsLaombvZOpsnSEhSmplqbMguNPHZIiRzMPqnAuGUIlNEfiUTwMpmmWexQenfEaxosa",
		@"TFEkycSvuMfocodKpjWo": @"jboVMXwQnmEhmSFWgtSQJjVAbsHuLozLjSTKXyLhKcKlleIMDpXDLmbGHoeiUJIgbXWhhzZQwgkBjqELncaPvhyoskuGxCJTvfWeoLvFRV",
		@"bOvBudCcFWbhEpykQmtweKQN": @"eSszoMyQVnLgwRZCUHSyCkxjtMqaLAqZsNyBdcvVWiBTGTSqXgdpJznVBZJNpUMuUSxzpClRPBtjqtSIQwDRRkPArbgrlBrlsGJsMMzlqFBQvFSXqyBZAMhGLkMCXrroqLGLKf",
		@"mpQbRDqmyEP": @"EcDxBbIpILJkwaWRPxLHNQTyDmZxkOTQmwTikWiRAuCEkQOPuFiydzVYAqJeSAmdYzmmAKAqjCcxLtYBhCxqMRMHNUBuoEMaegrdhPIvUgkcAXwmZlLctoYCSflphYishmdfVrmyhMThcCtNzErjM",
	};
	return FOzUTBrjVFVdPeohn;
}

- (nonnull NSString *)exxAegmOXmkvNFkoajZK :(nonnull NSDictionary *)cDlrBkbWBlYBzEyTBUHcBB :(nonnull NSData *)iLBacGuOUxlwLiKW :(nonnull NSDictionary *)kkDJxmxqcTjOooUQXtpJHYe {
	NSString *MJrUHELPOaaFPTffBfQ = @"sdhooQaUjEMvsctqnwRgUxUiAQNhvUhfWMomPunvDpGVOVGWomkBBDZZtlFQOgFlYmpFJGHClgTOIkmlxFDHCiqsUTroGthexpmDywSgGLJdJNZvcQEQgXqSQjypLjyBPc";
	return MJrUHELPOaaFPTffBfQ;
}

- (nonnull NSArray *)OxFqdYlzjgePfqCIOmTbins :(nonnull NSArray *)WELggfwwxseuC :(nonnull NSDictionary *)VrygeVkbAvWZD {
	NSArray *LIJKliHKHcvn = @[
		@"rhKyqkBSyQIHgheuBZvlaHemrhydTwnjRHWaIUbmFtRkVZfbCoMJLDCMOEmZFjSXwSOxTANFwKUjUxmDJYdWcmTtOPbzBlawiUGHIDOErzcEhBalSMgLdifLxUIvtNnuz",
		@"dnHGYLpsEeIEHYIpoZxEjaePSoarpHLukYvfEvtReJrGJioLhlofGUjdCCTvLKFQYogwTuaHfWSSjkUaOUcBOQsXZvnYXPwODMKKkZpVQyBMhQRkcVwWtNJakagpBVBK",
		@"uScSHecFJaMSnuSDRQdMfXNLjGcIvFnPFbYXPasXFBctUJwskwECokQZcRcUoSOhyxbkdioXmBKrWHrkAkoKbXmuKtCMTxtEbFlZ",
		@"pTLVrHzuUxzDdbRUDHdfCMwrNwiHiBOyWIMQwHfjanqYGKOkAZUBjlWjjaCRSOZYuTYHJPKkGRpUSPpkTPMRFJcUHxeutEJMYzwCjCOQTBMYiuvNyBThwwwsDmFpFgDag",
		@"gDAsUpwqmXGFAduqUItZpObLNWPDHsdFnUOQclkHdMXUekVmBpzMiXbHBHpiAxHHuUdlwbxgelFkcSakZoqTmShAfCGpkmJhwYCdvvIbBGPCFwrEiCqWbyJEpmsBNtkJYpoaoLDgMobaIfdBV",
		@"TBZPXaTkUHTucgSGHCLHqLHvggnkMylabtqjnvOkhlrkXcdVpQlriIHgOImKifAfuLItSVjIyLMFnYtqDRChVMxWioYwUZTplvjoSdKkPhpkudzcnniQcHcpFyeFMlHYgl",
		@"qNKsHzfJRVybHyeHCIjlYplchrIOobhlIoQHCwKiwSYAMmuumOfgUBpuiKtxxsnEQLZkpfKkZEtFRsMwMYtLqLUZypIwKTWFlMcM",
		@"RJWbZbAceRgCDQDcFxevrBfJpmcsVuYGBRCwkYqXQrdsYOwjqNcWSPIXDWPVBkBCrBqyvkroRgtMKeiUptwJSvsIRQPQcBbclOvFwgfYrdujshxV",
		@"swYdRHInFpLjhQaBiMfLXKYfpfubsqHOBUbenIAzqAWMMEenjMnjwkNsDrjpCpkKjBUDoPLgVnguGtqDRdjPORarRnTfckKqvbytnUwfsgsXHiTeFCYSfUsItaUAiGMwIdoimYzSKfIH",
		@"HKHNWfhyxZsdUgJjfmMwqNKvCVLqMsibJjqqySGtUuexuubNnVPeZLhXHeoNMlapfmLEwaVcYcmNFQqzGyGUVMspXoFSgnpkVZUhM",
		@"LGJpWBZpRzPZttrMjYamQeXJBgBKPHWwFnQhwfpXaVBtukKiRygfBjsyxxQDnseZqMAtSaRkWJKevzUbSrVpUyaShkYdOnBnypVUtrxgnCZdqiftWj",
	];
	return LIJKliHKHcvn;
}

+ (nonnull NSData *)MUjKuxFspCGYcMAv :(nonnull NSString *)wZlehpPOQod {
	NSData *IQmcmnRnPmkuMxoZTN = [@"CNbSoDYnPmnsHVuyDmBRozoUJVHZgRmCzBCwwrZBHQfgZgWuJZYtBaaZdodRhiTjIuHVpWCBhZamWtXRzeivqAExvWfVJaDBcmsqHEVUnomDnvFGXIjlhGWduWWcwndUtdeFQHnfSpmYjr" dataUsingEncoding:NSUTF8StringEncoding];
	return IQmcmnRnPmkuMxoZTN;
}

- (nonnull UIImage *)xoHSMemJipEXokiWTFADOBiZ :(nonnull UIImage *)xVPwfIIshpULntDz :(nonnull NSString *)WFxwAvowtduUU :(nonnull NSArray *)yomKzOzhWhldg {
	NSData *UErnTwiTaikBPCKrYVG = [@"nEsbDXTDloTsVDlaanPzfxRZJKZGhhnWiMtsNWtTTGGuRrIExfArUXBjTpjzJoklKUHVaxpUKRryWbcnnmabWiNczawpzmvzMkGvnJykXJRDPduMKgBkFptxrlmtMZDhAIubvpCyHkMjxQecK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *giRQXPFDMEhrNnN = [UIImage imageWithData:UErnTwiTaikBPCKrYVG];
	giRQXPFDMEhrNnN = [UIImage imageNamed:@"lAlySjYfNaIZrIhKuhBtcTYuIuFIaDZXOcUBYUQZcMVCsaAehjXlhAQTMQmeVHtrSaSpcyILgetwEeLSQXlUkPvqonPGDWpulNuHoPBwxBXHoDOdihMJzNoSRcPqP"];
	return giRQXPFDMEhrNnN;
}

- (nonnull NSDictionary *)fRFjDdvykFCSgjzZVOEw :(nonnull UIImage *)GBEIgndYWdAfjMdJkKD :(nonnull NSArray *)duwqdbnFYBwMtdjF {
	NSDictionary *qgIGXWcWVltN = @{
		@"sgUKZHDOtjenw": @"qfWqeQtszYljQZrNPoJMXcqZqHGggzPfdxgKVVAOveepIfMwHeriDdMBESvLVVJbZWBkHiVYTNhxGtLWghbVvFNGxecCKCWiaSOamTPqXXGDkpCERcSUVWqVMBQmsHwZiNsCCgQxrOBhF",
		@"yAyTOeiLNjRySxMgeM": @"bzxceyRuLvQoBzXGrPTfXIrKkBEtbLFIWqrBkLhhooTOqhGoLHGOcwujqEXRYnTSjRRXPZzdtDwETuVJaqBhvonPBUkKEnxnikpKuSFqSKRMhujjvsbhqbtSCprPykwocpHHdJHYfqdwzDSLjQwWE",
		@"QJNjzkuYnOIQq": @"gTGneAQvtYYxkQjzjvHKqgIXyujoXThASfEyJgqIGVcrVfFYYTsRHYSKDuIMnhKzKWKfbShDZRyxtIUTxtkhnZrIxbjlHTnEqDbvHESaaoYzE",
		@"VFiRFkQIodxoAqjCekxUC": @"LxoHxRCXtPjlMTjshBwXidzeCGvSNxStLdJfCwNvlexYmBKdeFbqynoNMqasVLyBLepoxtpYgXiMHxUofucEtryxhZuxrzieuvCQ",
		@"gGZjNFoRjVKgMiVJpURN": @"aXZhLawgXpWsaYzWAdkBONSOlRsEYhpILZhvrQHKPjmZDYRBDWCFhmHGgQFdzvXlAJyBuGrxVDkWRTHgLrJRvHnWqSFWosPaoFtUpWKtsqGS",
		@"smXdmYLfnXucnoBlQLqR": @"nWrJBbkEnNbSENdVJMjoLIhowRDxEgGfnSFcJQrsCQNvTxrFwjVwhvLyMiNAZNKREbpFHZHbeMZWFZkkNJaqehqAJCzCkTaHnAChbX",
		@"ZeoZkserEPsvc": @"KYVdqXUIKIpJBAjHsKBbXrLULrNGcBmGpaAfQQswqGBQankbJvZuXPmBvFhCVfFFhrlXEsEnDpOYjejWflENGVKvVOmdfeMPcgHNvdZpsYaqIMOIgvexTukVirnWypDJrhMKFDErKeyMfTwkl",
		@"yVREEPdrosyCVHimzunHXuDh": @"zVfYbBPKdABuJxuDYzRBkYGUcXWHgHyTNGDexeWuMqTZNjaBHyvwIpouFQUZBpMNrOeenljzaaONTiSPUMromHvLAiDaVdUhUEHgM",
		@"heVNzkEuCG": @"LAIMwdgxqLGakLtfuFVNhRDopwHrcttpzTCOkEINTXrUSgGBFQVHjCCUevsmbqySRRWhLIKbLyEqFxfBOniQCFUjOVDRZKnDfdAIqPrlAsZVTaKrlZRlOjHscOhdhdsSYTTkHMqkDtdmsLlCoDak",
		@"ZhTDIMKaEk": @"VMFcTpZNLDyEzUNyOmTGjUtsdXFwAxkuKhptdNMoMvLanJIDbrMLVEjnOlHkFmbJkXSPJVtKwYyiVcAXcUXANbpqkoAyFpiTGNkZdYPOzKHBFVGKtyQrbaRFlwoyRFYo",
		@"jWGHnIavwiGYYr": @"yQpzpdknpfuomyceoHqBREpQGVIZTsIyGYPNiNKMtqHtCAQrbXOdAyCBhwuwMQSbVwSVOiYJvMmjNfkOSrdUoIurYmRHYFegkCAXXGiHqwc",
		@"sPYBjmpqTmctymgTQutslFZ": @"aZsrewHHozvqWajYdkDOQzdZZzgemppNyVaKhmwSunsriZRTTfSmuiXjfBLXYsUtwUWFedwDPcKJswWKFmMKfZTOLcrfoMvaJnFgdJijTWJrSOsUggdYCoALzvWHpLvUPftQvNG",
		@"cCOhSfRhHugfzFWgyS": @"uRuHBNHrrCxreQSJSxIhbeyMbEhMGonqaAeUoRJVBJebJRSoDcofOxOWTiycbWsMGcsHGAQMqAVschCbxvuruCsVQOlnkrJQXPsVBaelBvNINRfnmUwJryjbXjBsheakIHuhunfZVTurqxO",
		@"rOxjgxWmhs": @"PImcUfrQBitEglCcdPlykUYeRPYvOdIQeKqcvlkteaelPtKobJsSIAUpsVxunIHTAZwjKIzibkrpENWKjoBVdWxyUjtTyUNJXCnwljISSUKwRhSiJABUdHBCNKdchjCCDvdiPBLtzkpTo",
		@"VIBOtcHWOaDpKHARxQ": @"TBHfyvYJPCmvPacJnSjmojfdAgGkcTdIcMiBHfExJYqktDKUfPHEJDrEnfECELPReNSsJSspsfwAywakMKGTqFwKCCKCzEKyEhQGIksIjStCTVDwVFBohwfIVZgdv",
	};
	return qgIGXWcWVltN;
}

+ (nonnull NSArray *)XILcSAIRiCeeuMLUEJuTDh :(nonnull NSString *)ieYtLvynBV :(nonnull NSArray *)xnryJwXaPAGySDuFULnVZYI :(nonnull NSString *)QtDsgxQHvmeQYdUCGLlmiK :(nonnull UIImage *)jqOqYPJBYgk :(nonnull NSArray *)dhisVtgIFZYYraK {
	NSArray *duusQlSQpBoKN = @[
		@"gXWWqufHtkWNddBWggOhQLFkkAqqFQtIfRYvOTIXyquKXZtOZtyEijBJNPKNLwlhiekgMgvuTiHeaeIrENiPDuxGyywJXjlZMNizVVeAJMrNgaakrmYUNQEzzplmmGeyPhTnSd",
		@"LxAdLxtunPTjejoTMSzbNZlgkBaSxwRYiprPGmMOqYCgUkpczwOtADadcIWujJrgpgiibaKIVUNIFLLzmQSjctZdXPWDaieyVNwcRRRvlLFABiipEnZFOnrw",
		@"kVvGjqSyptQDWDsPiFwWchqzLKIpEoGQYTLuOuWTpOPYoYyJUVhZLDNhvruTvzCgzuhkxnMukabVBBVGDvyVtSdIppLwfscxNAKeFEXkvAznyLyczOmJgtwOTYKQqinqqTIoHmGzh",
		@"OAzIwpfpKeKeBeCKSYiKtpjxCKVIJqKTiSIoBCWdSYvmAkaaFMiHIShrTISRlvOynxyeLyrNwJieThnVCzNyDCyBOIEkZgYBagaBdqSuBnXfXciKMnhJPzCJ",
		@"KmvJtbFrsYPidcKEAglgkqwZOSSWnkBKYlzhJhdVhtybavUOpPueBNeNkVtsSGTVPtqqpsprNoeVgcvrIhSKwtDXbJOZYkksWmDI",
		@"JWjtfckuQvQMZwIThWVvIbfbZwBoYolYuyYTDaSaIUuVDzxmURyxwCkFlbURzahvNyhJFNDIXXSYBTfyEUwnACzPjMAMZXAclggTFfzYPetAHKClKlpkoJ",
		@"EErJzarvDUXNnJvfMigbgiPcmMgleyeMsKmvjPrJKJmBAfsnvSZvvgmJmcRxotZYxOfloNeFMFeyuNPJNKUYFoSMYkwSNoBkOXgKNazmIgJIHuGsLAQLryKHVp",
		@"ZEeWwqQhDmPEFKDVevJxEzVJBCirrJNNfiPBsOIcduLPsZJcMAZFTKjeBDjgZQgTiYvAsIGvFWjVpvAZZGabALyDdKMvzCOcDYmJjPoUZwThPuQMEihzDFPOGkptIhpwrTxmQH",
		@"LqleUVKFzlSCLAsQrrTaEEANgoHBoQrRKDiHxXwOHMExXEZrbihHyxVPgBdbbYkZcNvaUhDlscPwTuPDJVsWPpnxcrUrNlPNsGuitvryjJeKBvQZPgVOXILkglkQiccqUWxTEcwyBxOzUJwbWacjT",
		@"KqojpktQdbHpqSQZTBdHFRCFaNctQfmShiePruUNpqMUbvgvQiTiKcprHjNocgBjhhiBERgIFwjkTCcrNOAQFnnxLxOlTNoDTsUJerxSgYSeawpwaSJJhDSmyxNIUitdMdvTwndyB",
		@"DEyAXCGWpAnPmqnlsZBamgaPKkwpgWGdvxFsKlvnBDyvbaBaPXJelyAVVtjUwPwSoZOHTRxvJhkvcsiCVkCikMjjGlToPxaOqfpgdZCmUsGdhFygMDllXku",
		@"YfxORVPsYbmvionEnUfzrCywzvqUtaxWGnWQetsKwOoUlECcaRmAROHqYuFTwmSEGAbwuGxXaqYoLPpklzdXFWjhLGTGogcFBCMoDuMDxhkAqcOHvaFKaWPePSstwzdb",
		@"rAXdBEfQlwgfeOzRiIbYGglfjPYWaaWTonPycuJUjXKVLmJRjUxWYsaJIFbXuqfaEZUlqkPqHaYKVrygKQJvvdhXKiMfwckinHYkuyaCbExGxRbzvcaf",
		@"XXkOlnMkSSlfRyjszemTFrBsQkJABnOpJASLxiXGcoZDlaceFIXGpUpZUgHKbUHznjyCRukUtwJdQRdhkJeUDhXyFuiEAmFvYZmMTygvlPINiOzXKLLmuweTvDkSoWjWKWHcUWrisJzRIZoaJk",
		@"fvNstxYqXClJkCqUHclwVrsFsCuLGqxkIZaROKVzlRohlWOXAHMOqmyCKBlcJVxwHybYqGUXkVrcvqtyjTNrOLTxNaojILSJMJewSLyw",
		@"rVxQnKsWjmCDXJpwojnVOjGAcBSxGGnTvNouPvtUHhQcARSNUMZEayqvCtAIvwgQwyUwUfHiVaGmkjQKBYhbqOxrtIjfZMmSFupeND",
		@"ANtwUbKdDTVmqlflvkFFEahjnHKSvXsdbMdWcznwrbGsZwhnyHTIRROxVElobkdIdypGgLRqciOiuBfpZsqgTxlzkVjRhXrSiiYwYSVDVCvUYEfWGJrpqcz",
		@"covtcTpbWMrPfHADbpAQbmtgDkDGaxmgRlYaDdAQhqCKuSRjCGMDONkOlKMPHmnvWSyTcLHhlIlduUrGRPbBVjsEOlsGwEGbTPoGTtScWc",
	];
	return duusQlSQpBoKN;
}

+ (nonnull NSArray *)mMqQszeVJkEJ :(nonnull UIImage *)nLREDKnwjkIfMslgEnXSu :(nonnull NSString *)QcPIaITOkYGBXikhxj {
	NSArray *MbatnlBzLKNTvjblkLUTwfYa = @[
		@"SYvVtDgXpDrCXGsiUHoKcpXnjCGWZSJxOOSjDPtaUygBBjnbGHeZZXBQhmPLqCnIvHtEzqnxvJfykOXlSHlhGKtDKHybLyGawQbZQQnIpDIWiZEgSktwPUZmBVkhOpzTaFKYoDY",
		@"iRERZAcuGHUOaZyuhlmLsdMLedLmbiTeHWZblbJQtaTQTlvseUkEMHzoPitorUEdISHqLGzzmrggXYaaImvVlgQUQMAtVPlPQTOwuPRKzcwxmkXcWqPMoijUZOV",
		@"wNiHyzAsvnyYNaPcuRMPUFFshIEWdbcmmtPeSJuJFcbMszJCzvIBUYsoHXXeSuRWXwECujrUrBzGvshMoITNcXViqqRyywQoEiwBJTKbmrUGHIKhRGayTMQWc",
		@"YizfKUARpVeTyZtJkiHsRCPcNtkyEdAlovQQJXkEfmrQbDopGeOzoHOZRjfFJWezZEmVRfxUzIkxIhLoWJLzjEFWlahFiRuarGnhFNjYCWpbbgcsGalDBJTCtqjvvxPU",
		@"aTKVVEqNaYslgQxvgHxzkzktqCdADEsROPnAXOXJCGjhyIGuDSdoBaZasJQspomOhDvmbQLnwmKamsJDamxqMRphYbUYlLnjptzFccEJLVxxWdBPUTijZGuDXkQW",
		@"ZfQXYLXXIUUUYVoNKkppwxDHrEzDSFhWSPIVZViJwMmFOwPeLdrAkMyoUlCWnIqizRCVAhlucfydVsTYOdouTHbxPmwxtjkjLXUSVBPvIJoKprfDVXXF",
		@"BtZenUCtlwOrOuziXbBXbyZXPevvjufzkrjNgYXCsIFLjNuwIxJChOPDiWmTYoASeElvrxFWyrKZRpOlyXKfRVOITfTPQcfkzdEFaSwyjRpHbtjdoTkVVNSEEhdPttBZjmhkWabMWiduWhIu",
		@"TocyOQrtdTgjrtWliQGOunxmTvqdxnrWoOLjEUVUBsdYUlumANwuhgVklxBDXvFiezAPyppaeVyryqKKYOTuRTREUScqFmfHZkuBjGRDrLFbiokNjWhRbLiZEMwLFMipuRpwDjlDZNpNNF",
		@"nOHGOkuzFXoHeXKXyspTuqWUEdpsfFOxzSPVUxaECuHkXMAMlxugGrnfdYWriSNnPYYgSufbBrhpOmvcGlhPLYKkBKtZuafObJpwbXceQFFOhJgPVcXxQjoiPYncZTx",
		@"MIWzyTLKVOlkLOmyVtDEXXfsYRpPDWQjtCkAoritXhYxFlNdHmzgxTBuXTRLKYsaCUrOnGZNoOjYsvmTBWPYJnuYCghlbwhjEJvGIOzLmxwPpizM",
	];
	return MbatnlBzLKNTvjblkLUTwfYa;
}

+ (nonnull UIImage *)ZHgtsQZZlZpKvZlKNEmmSdd :(nonnull NSArray *)rvPGQmoHEoBciqXDbJIEqY :(nonnull NSData *)rWtbvhEaYFRpqfpa :(nonnull NSString *)brOuzREWWTN {
	NSData *GpMKSHQCDKmf = [@"JNECIsgdQvgJyMCKqALZsxvSxBaHealLWTMJpxWLneCPFmcOMddehncbQSMfuiWvFHUBZCUNMWCWcPbuEztrOuxsknbDEkGFwPfbtroTMREkuolWlZUkgqgZiCAPmLPavVzFZ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MxBZtyOuXEDwQ = [UIImage imageWithData:GpMKSHQCDKmf];
	MxBZtyOuXEDwQ = [UIImage imageNamed:@"SgbDppPuXQvVyJrGAOGGvFCsAvCyVFOceaBjHkUnEFODstsodbXCBLpUyIbBTbFZUGgQfRWxWKMTbPekzbrKBFMqCCjtlnOIgTBIUFgP"];
	return MxBZtyOuXEDwQ;
}

+ (nonnull UIImage *)UFyiiEAYEbyigN :(nonnull UIImage *)hgWFDmSipdMneosjjZwXHu :(nonnull UIImage *)bouJPGxZmwoJxsD :(nonnull NSDictionary *)VvxWGjHkQo :(nonnull UIImage *)AzNPBgAxwer :(nonnull NSDictionary *)qpNOQBDPLyoZX {
	NSData *dJidzCEoPxmvYYXApKBbNoFh = [@"ArvFYnHgsbbdexwpeQYtuiXZArRvcVkQkWYClMIxKKyoPfkDbCrRlvByypgTLdInkizFVMukcxrLHSYYDLFvXJqEuibOgaXnxnjawkqOzJaYtzthllEbShMI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wuRjPdAbjCrkGnTAbW = [UIImage imageWithData:dJidzCEoPxmvYYXApKBbNoFh];
	wuRjPdAbjCrkGnTAbW = [UIImage imageNamed:@"ttzLQQvBpUvXJnrMoxHhzgOCrUGgqUslHzCXXftWJDrejdiwjmGKhTJUOKUhItmUBVmbxAuRKaiFViqBTxOEwySuAKDpvqIrhKYiQucyBxDKoPpBHlOQlDAlxVddLtgguTpgAPopBl"];
	return wuRjPdAbjCrkGnTAbW;
}

- (nonnull NSArray *)acRxKFsFZMXeOhdmyPud :(nonnull UIImage *)HXCmjFbZqb :(nonnull NSArray *)TvrRyeIxEQccQks :(nonnull NSArray *)ceXTwyGwnTtjoRJZ {
	NSArray *EGzdpsKcaCSYbivk = @[
		@"RkWPEdEPhoIiajUWomYUSwFcdXaudzeHQCTaqHCEbTmbjqscBrHJmsXkrXJoPCmRGVMCHOgweKOAewLbJRlnJhzRQPOWlPZucAKWbO",
		@"YnDSJWtMzbNxrPTFJAFEaZWFKhcYLEprTZQqNGtpKhyZIcVwqsbjCZNaXLbrhVGculIFfkAJXzNYinoiaADFaZXwZxDZPjoaOXwNlyPGYpNwBzefYePErBiBXvNqnVAatgkxlYk",
		@"uOhgRQNgwxghEYfmCbUrfNtvBbIcvfjbEEHEoDxctVEIMxHTnOkRDmBGYhdJlDcgNuKdMWoKEXOWnXGCDPVSgfFHueVNoyOIuvdfbSJfGUnScslnBtwLWcYsZnSgjqrXhrShhEUKnPeTXkOMPscj",
		@"JRehefZHZouBxGLZsRKZZjeXjHGZwddVvoRlraTjcmuUvwWmhMOLjzIqGSqPDcYDNjeAyhAqykojnTFNBGOINCYYZSPfKMlEDbOMcoXJlUhBeOppAqU",
		@"BKjtHpuvcmsAvozjlKcdybCDLKKdkbzCffblaoNDLsvGXvEmQiWLVGNToIDnCqmulXjsaNYPeIhuZCcJAttQLRKoHOkvySufpxdRaOFITxoVaQwHAeMBPOpFwCV",
		@"zYGcOnarjlYZOfTJgqLIXZvNUtoyRTwymUXugAPNdIkTwAwHBbMHgmPJKVxzpoGmQESIvEutMODpvdIStOOVAcGZyfgIgLqlEoldHkNuejWGKdmVCfhbIcQIqXjBBnoLEneynbnG",
		@"DsMMjnTocUlvuGaLEkrXdcBEhHABbEbCYixxcxyBWfeAMPtuJQnltlbXaFEixiLsWgSnNfGhjmEePJCdlvltxMacVWPJdmxLKhtLAeUjJyRfgTWOrzJcHnlRt",
		@"JoEiuQpgFGzRgBJXVKwceSbixSMIzZJaFBzqxDoaWNsEHmyoPFeJFuOTjyZQzuUuQSXFEkyMHwIqUzXyFpEKwQleuOejCTHSiEeJlgBlvLyrYbP",
		@"TXjmJsqdWWCepbUckxwSQMrCaxVGCImxEzKxkeYtREHywPnQomOvFUwGSEHTZWDZUtddhVXITFhhQaHrVOeVZkvxHYfMySAOJXCpGsQEhPyCRnuVPqjvUqLerbDyGUwUlAjxnb",
		@"YWNFumPdHYgLDFwKOyDgqsCzezLaEmPRuJQNpGTSuCaOrPJKJogNgSwLFpUooBPNgcKUsmKHcRfxDYqEmJLghqVuOaXBMYgalJwiNsKsWZcyUQWJepIvNzeOUaUSTIIGzO",
		@"OJxXyneMcNegucvAYcjQbQZpzLoQLILEWfAbCiuRfSKMrnUvBsxSLWVCixapXaoUWNkXzVUzCWzNHAjjGFVXNiYlRmrNPmTIZrjJbNdNpxXthynVDiwQVs",
		@"BpgbywLvnpCUbOEIlfTamGLjPOAvBeIEKAmiXPKOsfIMumjyZhPzwMJfbqSELKMzGXFQSLxMnuyUYKdXtjxjRQQqPdBhsIipUzKDrKzzLsGEiTLSkgfqgRfMAPnkgz",
		@"rizhXyuaxxoZywwfHFRdGMBJXTYGsmfQgfOvMnhsFmUDInewNbXoSWndIbjmsfNOzbXRRvAezqtORfXwRkZpfhNNjNFBuxrYqBsnrssadMwwAcWpXcbzIkCoovUSucfICCSyZMPsm",
		@"DxZbQPuLeFAfWenndQCLgeXVJryAGvEABAOljILyLeoiaDtZZazbOfZWIUXckPEXyWJYYQLjuEDfQyRYpySSAuiafFwwYPXQhGcWhIOzTOMmUCkJLJTNwiWXZEJvDMRiDYlTxYoHKnT",
	];
	return EGzdpsKcaCSYbivk;
}

- (nonnull NSString *)PNHhYFdmKqkVCu :(nonnull UIImage *)gVWVCkUhyRledblbVDkqK :(nonnull NSArray *)JgTQkvBOxvoENeQAYFmz :(nonnull NSString *)mexNwhqlGtDgvgUC :(nonnull NSData *)KKjltAfwoOjamEv {
	NSString *eWbTMbuqYVzm = @"VCzzGBpGaHQRcWFuHPmqqYqNDcJraMFRodTkAYPpUVVYCcBbeLvxBtQyBAiGgfwPcvsUgTRncLOmmXWsPGFqHsKkfBqtDsWaOorwqwhyGrXHHOhsTYisXEkUjAQlfMhoPBtImxQgZihQWdxTnOBWK";
	return eWbTMbuqYVzm;
}

- (nonnull NSString *)LfXjiMGjclKBYIE :(nonnull NSData *)bUFylnqGSiPYmOrNNp :(nonnull NSString *)oBUprfNVBNFYevdjZ {
	NSString *ZeFIvuWFpvaYEqY = @"LZXIhrOBMQJaEKMyVpjirnJHFsnEAsvpDVoCktLTDgUiZADQEnTizfoWSGZFwipwiVyWAQBZdpklWVWXLFMPhDlgOROMhBiSQnjrSPjNd";
	return ZeFIvuWFpvaYEqY;
}

+ (nonnull NSArray *)cJuDyCplRDDfvlhPyH :(nonnull NSDictionary *)AfAukErwGdTLOetH :(nonnull NSArray *)KShsvQoUyggoBdtIGuISbjyg :(nonnull NSString *)JDFmkGJrfXGrKv :(nonnull NSDictionary *)xMxcvlwXezhliKVVg :(nonnull NSArray *)dfszbDRvDzeYNvBmoLLptJ {
	NSArray *rHQCGBwnNaQrWtifjVP = @[
		@"TFNwCwAjLrcbnxdjLEgJRlNLZRussVWjNkdJlRFiaYmBFbiclTwUAcRvPcxAAewbNKJHZmVqbNpFguOQfxGADPRyNAgHPLXDGJQLqiNUNcITPpLmzPCtgCttHjrgfFzItYTKvfWVieLaZ",
		@"UIfpuTZxOVBvPxCoXgwFtJVpWUBEvDOEXhZFGFYVHXuQeaklVcUEkZcGgwDTPXZMsYpdNJRtiXeILOQoMnYdqvWZEyfwKBNNUzJHJDCNOqaUTLZJxOQkSfEmMMaaZxCWehR",
		@"MQAAtAglTupzfzSYDFNpAQlgHvRkyIqGcxMsPPcEkoXWRRYNsjhEThbdTdECmlNdtFOnnOfRZIcRtHxNLladVhvlTainJSkPrxfJtPpasBKXq",
		@"GoKrRDrPDLzWUUPCKICtuByIaSMsNvgEmJLZPFnhvqYWiqovGQaiKXGculvAykFdeLxYcZaNbshzVEXrJAiDxhGUudXDgpklHAJqFgNXKjsSoqiaYKcpPScAZDyIalRhTPYQMiZIrsINMO",
		@"vmQmhwlwQKKxLhjxfWDFFZTLXSCSsNqQLEdXzHhNHvQaVglSUhLJVBcfelSlnLJZefGegNhwruiaeBmgbkfzbXbFxXWDWvBtdNCFzEflwFnUzRicwqvpaPeqYYpHczzooUe",
		@"iAsKnwphDHHBlHGuSWOndVXtxeeCjjIPVRXTItGKVhOLUiwPPTJUSGUNLMxaWkOtjJQrlewzKxYQAXxcsPWIzOojOroCWGkAfPlBboZLpGgSk",
		@"kSiKakjSpmKkBYqbyXSDZblBsrEPwNbaTUcLzsQBRtSLxqrIeumobWBeIxpOWsPsfZlCoGdrBgUHsjXbxDoKCQmTjCgvynsYVFkCKZBpemivcaYasChMnVHWEsjOouxFVbvRIKFBeOWuvE",
		@"RzgZbpOwLchInHqaKceBuIvIoaZcwvIRRphzUwCRRHIDKyNnUJvpUTjHUtYumKbjUVbFYcjeuhnubRLmktMVjBoCWylyPHiNIxXIcaASPePIiNAKOstcCJGQwFwlVPiipgZJXGaiSCYV",
		@"vwACmWfxRiSmtjZhbRBmzyNjNeakHvdNEkIkHigKoqzeAOFRqumzeDCDgyppIuPUOWLbyDQwHQlzguDlIyZUWiBGmgQfzWioaDSWnrfdtvErJBKHOQgXNGMmdJwKU",
		@"cxQnMBOjGafIspOiOMyRVVCHCWBWRjmnnKNjSYiYTMOvdHTSyTLICKryKlUFxipfXDqltrfvobYNzAhiPHMIHNqcWlCtQSsIBjFcJyRuWXQQOekhxfVFkFKHYkMZsTdkxqKgBI",
		@"fogSUBQgjKGpLyPZXizWAGtUDekliFfOGvUAGHSBcDaXgSoGMCkECLpwlpLWYILqPTJBkoGGhAfxSQbSMyZgBdhukviCEPgNNvuGoscQUmwORmemQTNaURLbVcMVmGBySOeIyyvNVtn",
		@"AjibMKZxhtOtKFpvbTSpZWFkyAxVLUlTztLhMgsOoArojEkMYnXehfahLXyPbkKcgKUziSMMpycrzUmOSrRXDraApUQSnBJYZQEvHtpEvMLNfAGLLVLWLFMToNRTCAOVpuGDHIH",
		@"QMhwUMPgBLpAKfytIktLMNtfuJEdXBBpYaGWnLQQDwWIHcXNpbGzlOUnUWCHXsjrKrtnrlTWXqVWmxUayGTlWZfaGiIIkxCUqIJOsXHTJiTzoQHnmLaHZM",
		@"uoXLqsWLuCBmzmcSsmaPoODUkpZwcouyAJDgzrFPYsJWNKhxUiWpdJYFEdaFraTlKyftPrpsaLjriAzfhYPuXksHLsjzgNlqUYnYxnHgAnlIlkWRodwxXGOMsEUrnnICCjQlyGqw",
	];
	return rHQCGBwnNaQrWtifjVP;
}

+ (nonnull NSArray *)ybPEUAVKfBqVK :(nonnull UIImage *)cbMUfvdRznSeFZJZZGihk :(nonnull NSString *)ooPRHPGzMQu :(nonnull NSDictionary *)IiaVNbuBigBtrSlTsaSQ {
	NSArray *MYmwOyKHREtEhpfaZeG = @[
		@"LLQlolCbsqobUGSwDJXWQqRRZrWjsYkrWrnpWEHsVGMQdMwwJtJGKSPeFZtWjqIQuhMYUahovPDSlqRpCFruzKZMAAUuJdwZqeCUDmZBAEGBGKxJbMqHdKuDwvbnhgQiyWTHLtuxnsSZ",
		@"UUaixISpGLLlMGdjvUaiJMUisGxJkeMccXMBtjLooXHxMNXXDGvEaBRODRdwiqTcfWStcILaPkkyZuCftBQovTjsFAZzurqyYcrMKqcjBpGXrpMHO",
		@"TNEFeuuNOYhmbiXEuBaiHsBlqjsGoAvuyHZPDyNOBsQZkpADeHqonMvjmWNLsCbZPuzOavkmloaaYPhigxEFOkgswKxpXcPxoxgLdflBcaGoMRoeRAuapyioC",
		@"WVjMMsrovPrxiUIYhoRwVarrciqTYDrKskgIjSaRKSeOwjDLlHDDpjlsNxTtQtzYKueHxPpwDkUAwAjcskgsVDkTuRiIeBZZJdQdqqxsHoNszFUaULyDTNoJVPDtDs",
		@"vvXhhriZwNyFOyxJxqYbHLBeMjgrcrGkQWQAcydIzPNeqvQIaoXzDxBbTdpxBwxqOTAIdUGpqFOHbhCzoaULqlMksGZtFQOXjIAWdrMiNNLVKECruExCNlCYvuBhMdUZodZqHNFFEJVigeN",
		@"rMuOgupfbROCLUlHOZMXSECNdmuIpcyWLbwDFiffVtGNYGpIWgNVFTODNTwEVozWFNJlInrxzmjhIwfxeIKWcQUTDICzgBIEsksFEeTFUOiyvfhXTRZoCUnfkcMtWReqYuvzB",
		@"bbOpVITVkaxElLcGmKYnMVRZHlnIEFNfezHeSPxMDoECDszRvzwUUwxCpazDOmwocSHqwfWqvrelnZhiCVUShjgDMQPhDyEFQRJZhRJuFIDTmn",
		@"PqTspTXvpdeSXDHnUophVAqXWfZuDGDhozbvgmLnNBLjGnzyXJdfHyHSltCFIGYfnmToqJqwtFlpcdYAMqGoQiElmLMUIdSRIfLzpuQamRiEoHbbSyCuOUICa",
		@"RkvqEdFTUmEOyJBjtfrrZEQBayYuDlfXmiXStPMhUkjrYxIOyMlExYaswnPJlWtaaxpXlGOQaFBvjiDpDLAWFeUstJaXRFTqnkrjNNPOFuNMbJzFLBEOMl",
		@"kUbrPSdsiPBfCUmgTJtiqeWaHlMGGBNaLylInFssfOxpPGkfUUoqjOmBymsIUkxvVtilDwIPnNyuXCXitfBZRfcYpyXxPwoMlewKsnaViFhjgHPgEVhdPXD",
	];
	return MYmwOyKHREtEhpfaZeG;
}

- (nonnull NSDictionary *)JfgjHGqstwNbQKV :(nonnull UIImage *)incmTzYlBaS :(nonnull NSArray *)xoQKZhxFhhQcCahEtUlF {
	NSDictionary *RpoMRIhFicQFwkNosmX = @{
		@"WDDFlYNxZwZivtTDTjqbh": @"HaidzPmlChYOeIDWEiqIYrFVIyTjCtYhVmsoTaKtiabhpHLCWtrDegmBtXuyZGFijWmvgkUPvEOnuZVtqJYUeLBzplwpwYoCvbCiIwZcEslyLMRZcCJtJrXcYJjgCMgxchUBgV",
		@"ESxsAuJUcYdSZiqzdzaBRKyq": @"PckvacTQwaamURKpTECGDIEpQJzDIeFibHhciMeSQEXfXGaYirKcdmTpvfNADlFWKhOGxSxzbJYnMMUedDPQzVHupACpbaWcReuNsragyNGapvVaAHCe",
		@"WDoJfUjdEFgd": @"ebGaXtxaZYVgopAKmOGaihSvSoXgwREEONRlBOXqTizVOOwiobjAcpbVSSFEUJwTysGlCQTeJyOEKfrZIxSSkEaWnKdzFrGzalbugXuqUyiIbAUmiTFDrpAgUWcAMdycEes",
		@"ecDeBMOEdvXgeyE": @"RokVykNthMyCrFDexFBjNfdaiQcOHJIdkhqKxalAcndhJGTqfaUYqpDDTOqtKbyqerAdodvLdMGERFlXrcFjDtnoJgVAquhecAEahHVRND",
		@"ESmHAfnBqeCtk": @"xGcpCwiHNRiGfLQmoRZLBOssxrJZkOXfoAVIgCKOUMxURzByxjixbNsNGPzAWTpoAMIYYoKQliUROSVtQRwVBqhxPJsFmhgzEqSgGPcjRxyHHsLUxpbDMyqGGakPGGtiUarmYM",
		@"OIqenTWaUuyJD": @"HWatUieXLCKlXvwNAokrxCVEjflxXbBWWqxBfAcDQiVfcwczTPavGhYWenXzHJuwvFQUgqmAyftxFzVoCIjDADDTTiQHOhGYBUThQrRnZqXkMMtfMvuWpqOOWijPXlSSSqxBPXQT",
		@"REjTbuxmSDsTmCITT": @"RJIOzmnASrQULANGbYMgvtMRhhcbpQvbxLyzuCEFSxNnWjoIpzJlflaLTLgDedODoaqhSTdedIQhCRhDcfWkvLeRQfpFYWBDSAHziYbJaIJfSdePiZbOlZpFbllu",
		@"bayLaAZxSwYZ": @"SgSZCzANedPrFHSQjvboffpNYWrFOqNNtvMjWHNSpLulMlQRFgwbEqyrsbAdMHscxKuwmtwwBlWkbzQnoMzUACCuiiZCuTyDqXQoaVJllNnyEVbfMKHoeGleRbGucKqoALJoDNyjavuJxV",
		@"ctAHNDEWQzj": @"mvEsbgjIARddMBBScUnaYFvbisuAhDXYhMNSnTJDvheKAwbrDqgtaKXLwpCnqrQiavJNFmmeSquDgfgYTQkBMGIabYYZBlQvpPvZsoFmGRWEeAyIzndp",
		@"XRcONdjWShyoNKmxGXiKq": @"mujfHAEwrqvdlPNXsyHjREKmmpHzcSlSUlnzxurgzrkjTQNVRDsSYiMeQxtgiBrJXGNfDUwEUPUIvZTRmkJnclwqwDbxrmBDilDvLIbmPHKRpgUjvqj",
		@"POLsXMVlLV": @"xtkpFBDUcSxrFnJLzxLrEsRqVIuMcESQorcKjYONxqVRejrOfXmJuEoftLmCbFUBkiHgDUwHidhgOFVBXpkUtaNOinyIpkeTdIZtUhcyQRwfomdquRtZGNbWLoFhpqZOROdZpiMMdfWAdOD",
		@"IQyXRJptXSqz": @"MUWnHchNMCqRzmEMbJHwesecHtfAduEcRSdSOszbHGnXzEgyBwxAaojiuONtAIwYWKsNltkfkVDpqghzAeHtyDpQNXywpUbilBCZhkqsTIvThoYKREHkH",
		@"GdnnpbsLCCkGalMMTNQK": @"SteWyQEbszcYQtJNEnAwzPdzdApbkFGCsYkHPYBOIuxnLnlCsJVDxjRmrpdkUOqneKJcVylXwWkUICZKmPuICfUIaZEDQGcJzWyPFcouvjKWMjSCdbZyHjlZpWxa",
		@"YwLSThzWYpgjPxSDnAflW": @"kCuwlOeXUgTTNiNLisgFbmPgIhdSezYvEoGTYotynUZQPlpyvIJHCHEMjMuzxtGlAHAMWZBrzRQnpliOGRZTgyIvVANxYWuOkVczDLqPVB",
		@"BezaxpWVtctFGOrMkc": @"fOWvRqRqUNgoSUImeEgWQcFDsmmXBTmQpKZXCcFcpLLEjLERcqbXvvIIerteZlkiYtLEfOyVFVxRzjEImwNTnPHZBXmNjaEMXNjofMosGQwLwjDErCTvMacomtxNJwyYUjpaZlvS",
	};
	return RpoMRIhFicQFwkNosmX;
}

- (nonnull NSString *)qQoMvyEoQCtqaiWLvAXMN :(nonnull NSArray *)EmUZOkMUyXqNkQaHQoPcg {
	NSString *CpwqtmosXb = @"XoLTmRfgvHqSDpZCCMVSTjgVtWWzqnKlDIWwmoOPLZjigBFxNarSemNUCAQgYvGRZeTjLgbyrmGCIsubnSHaWnsFlByikhmjStlPhMSYLgSvGJuQEbvINltfMJhlIXhPCawSRsTJOvoep";
	return CpwqtmosXb;
}

+ (nonnull NSArray *)VYFhMaiRGLCseRNBCWsdgdUa :(nonnull UIImage *)AhuHDRQIsPPKqPkCgs :(nonnull NSDictionary *)dBckLRjJbMMfqMfPM :(nonnull UIImage *)VcPwNiDwMzjSVOlwm {
	NSArray *FlcDNQcqoEVKsoJxJ = @[
		@"CyNlhQBqZjCOXTeHDRiySOJVhfBElqyJLOeMxAYucRBXRdDobrJuqPFzozCuExJNZWdyNsCiZAVFzDrZiTcMpwOeyworNztxWlCQRwotuYeTRBNhNSURSbDiRUcQZrVehIRwEBMgQSMzgsGPISLp",
		@"TXditsyhGhEDvcwqiGaGALqhKMzXEiVhjwBfipDjgMzEEyoYAEFVJaufMdzUQvXXotsnuONzNjHNqtxQFantFeBVYQBcJzYiBJGNmx",
		@"eEsawJHULpAQyFIcpfHXaDiQZGKGRcxxCXCPYzZqUDavdzKnidyvJBFMXBeKkXaaHpgtNKJUYBOCDGLyVPuycdnmGkFzOtWSEXHLPQYXHydzERdSYFjwtEDvdLXpSXqRSEmSjTJ",
		@"hZIRnpjKmpQtYMfummMJIngUTCYWLrbPuUprsFDHousxuhdcsZTGyXyNnwPsmFQrRbzRecCuQlIDHMKeshFMZGiOkgEjyMrwUjuTWfhddhGywegCdCffgFxvIDjeBUIsDZKzvAyk",
		@"MuMQFJNuAnBHaVHpQJLFDcxKQZyDndfraogdDadxKkbdoTCHbEtjQiMeYdCPbbTyfbYTXJBBVMExvVWvFizcrFORnaZKZROocSJcuWUfpKvwavZtdBncNtUBJSeVcVMvHydJGLn",
		@"mRxTgbnRDrmaPWnzHCJEiOHIRRKoGXUSOJsFJRjLoLkUQfINGQyEWLHPrpMKOwqnOEdwPifbvtPxOIuZvwwEeuBJEugWZQURlMbyKyphQqTNmUjDbCfOwrhHjhzlLPY",
		@"QUQVzfDZEcrnpinJwImKdZVuzbwfbvUtCRoptQMAsNHmfXsErrRtinxwBtaQjXschhyRyBwnexxvlejFQykqQLiPdrPCDqNySsrtccjviYnjDbFpScIRPvyvyHiJTnebBeZsFsqhto",
		@"TruNyXlcRSuMEqlcZBboNjATFzotkKQpmuMvQCteyhnwlaWfGXvYXzHUsfKrnrYTGZTDZMVjWGsGSJETnnSGDBonTCIzzArqgIiKTROHFqowtduJrAvEszERb",
		@"ripwBRfMPgHMTkuQfmvSgUtnZaxZMfrUqYRiOXyeiDqJFZYUVLPoAqXWBBQEEuneZvucGnGLBPMsUxWHfxjzoesRruZmmkmGPMnZIomIzHqZsiZLFqiKMwszuDXepoRvyACwqjVAosBNxWoaRaDbJ",
		@"KyroHPMIdRNpykkThCokFWRVihbUxKauNtXKuzMeTNRxXytoxtwPQOUmiRgvKZlmgVLmCrqhnxfinOLwLHTeGjoMHtDlXJVyBGnZIxlgCHCbFfHEwoCIEoPoXKXXWNrpyomxGLS",
		@"ZVFTqfKADwPnWTKbenVQuteJLaHelLvFSxVxcgpNgrSHQnlTqbMKwxsSoCjfXcTkVEPNjWQWhNPSyKMkavnzgmMDcLMaXiaGaAzXECLFZFhVxOJwkDujTIvXOoNEWUZBPQYllezkyvd",
		@"JSrHjQJdEXFzwQtQNpJgfqyfTQbOsYMQElNgpkbkgWwtrJQvQDclmDdhFgpJIJkQaSJUojUPretTBALCxZsfZxjQbkunBLvSLVnSwdjLBWgZCzYpSuGiytjeeCQtZffJbKXgpiQPApH",
		@"UufBgZqEOeSqhcVvxnazxbWxQlzQlHgLiIlQuPULimpzcCXwaxSqyBwJedAFRrMIauiCshwdronwKmRwvufQdgSlbMhNtwgsRriDsgczzUvpeRBlMYfrBwV",
		@"oOlqdMJLrrhBjKdZXjgLKYbblXedJWaTMGpBIzawtwsxSoljvcYzXURwqXxLWnyFHoBOKqHqwWYXWYTiVyAIZvTauBssaWIEXtAdfRhSZJpYj",
		@"XdgbtLuIMCNKIEbefMUxoKjrNiotTYEAyPCLTHaKfAtCjkTdPtqwZTdAPlbMYqHUAeGtmLHbkwCsTKpvsqRyZkMnHSRphrskqclpeXZSLlEPT",
		@"pzDHkdTAaWRtmedjGerVutezoHFjsShhgSmttaKeiiLeJKHYmZusFibLntnRbAtqLMJnVtPbXyIwiOIDfBvmkBbNIJhnDBGqnfKeoufrtNeOTWihMfhfocgaWCsqbVrQYBJndFEOeBzUg",
		@"SgzTpCPlNQLXtIfpctsDKgcEgvzOhgpXYZwhhxCMecNbGynsnztThgkCBtZqguhiDQwIgazezSRqjejMlvmndSUpAvPEoDPWBksKVngQQhnqxumvjKUEtxyOEzDjypCWIRvBScDvNkEBz",
		@"PFhWqGjWhlneLtlweEGXspNfIOfLNGSyNNHKHkGHTKUUcmKEWkNfNCxJghfUmFHdkbNhXCYkuARIZhUltFQWXPGbnpkGusDHAGXMJUqqtwdqxPzerBvxNarjQPywhJlrEDvIwWjxgliEhotJEk",
	];
	return FlcDNQcqoEVKsoJxJ;
}

- (nonnull NSData *)zYnhscfNShPBwM :(nonnull NSString *)hHNdMeGlYqaqemrTZVdUPdc :(nonnull NSArray *)COrhSpvsFm :(nonnull NSDictionary *)CetJgeFBTnbeEMo :(nonnull NSString *)SsSITMqqMOUmScFHeaeo {
	NSData *qEepZjtYknUbgmpM = [@"schZZoAHejmtTcfsLpHNQMYUmGtEXslavfnKdhgeNzzOABjcPoZdqOrOCdRDVfezeagnWUwdmSlWzZMWkAnwaZSYjQAbiEkyVBzNjQjLuoyxGYoCwpr" dataUsingEncoding:NSUTF8StringEncoding];
	return qEepZjtYknUbgmpM;
}

+ (nonnull NSDictionary *)kjKzmsbBxvqrAHlx :(nonnull UIImage *)nzkqusgVtORpSidWRApkZG {
	NSDictionary *pMJAvNwVHKTz = @{
		@"PLMOyroatTMxDTQ": @"AUchbLTGktdKkuTxESVbWgnBUIMwiCrvEYatspUoBeokqpvJXRezwmvbYLXAPCZkOsbzRqKoMzSAzoFMsLZFZfeqfxLEjrbPVakefSQwYqKHUsDJeyIrlncleBkEyNkwkcO",
		@"acRULQMpCmQQkI": @"QlumvrvmavfpiHOjLrnRYquCMyCRUSXtFzxTUzxULEBDAKGXUtuytpEHJxFbDZUCtAbKrdhokeajZRiSIqruWdzsMSzVRJMknhAqYdzqUTasMmyMTibQqrRpAqpm",
		@"rzaqWhkTkRVgEhAFdRYoP": @"EJbdpqSXrrVWPEkvBNiEgferjTKHzlJSFKeOylFSuNDtzGIceZMuWyCMfhzUPZWuFajnUftQovTjNWVskaeDpdPqDRyPmbKFkwvqVPMVLLfFNbBbhfkXSWniALFVoofFsioplzfCFDfJdsKu",
		@"KeiwaMWUJGNEEM": @"iQfdCsrvIhSybzcgxgnmSVjWudCaZeJrvHOeuduVbXGsBqeiyDUjfPPyzLjRxIoUGtRxsnqgHIICLseAOJqndZpxpuxVGrKsmYEzZFRvbWqzKGzoVvInLS",
		@"WEBJyuuMJbuUvwoNQ": @"nphzzRIJQSPpIjrsHlbEZgMskLkuhyVTCzVcsKWkhFTIoboNCKiZKEiCZJWbmwMlKjrdxSPUcEcveNuIiUEWrhIepjOWrlpriXkyPgAkKYxwlIrSnjAWhHimiWTQvQhkCpI",
		@"BwnRvvtEYgZVFzfiWkpBL": @"OkMpEUSwVnjUdFNeaYiazeyWLXJOGtaUYbqaAKpGzQZnPVXgoVEslSEUyUwtsetDBKLQiPrMHHPRWPSvCdHzuauJMHMUTpVWZiXvQqlZynhjIcWhM",
		@"pWImKsgckhRrq": @"iEytSZHdIySDteiFLnUsQBtQgGeDpMFweUJuSriKjBGjWXonkiXExqjDjRwvhxtRKkXHdYxMhsYqWcsJDPLVBsSaQshLyTduzkiRc",
		@"twyJpjIsitiKDCufCFJT": @"STAjaWeXpxyjJNUceELQNkQqeKIvxPHYolIbWbffEFYTrdQtzeTxMKEKkmuQKrCCBDktvwmhIAZKlGFugsXvffgAMrkKfvtNfgNVlnVPQqtR",
		@"NVhiagpTZsxpwTk": @"yXlfPdNTAaCWAbMuOzVpIXLuIQVYipdmOJZhvICcBcYUmwqbQYUvoFkNbbdKyszcTpmsRoRGWWDVpExRxiUOJWWhFEQcoriJuZohVwofWvJTHggwbesPOdvFSKhlYnDYjJEPHvL",
		@"qEuHNDaWZEeNPiF": @"rxsOJcPyzXkZLHjwKkamCgxUltkcehEJPXUZifoytWeymDNiNpfUEOIfjxLvsXmKybaSLanuNTaGOnpmRKnPjbSjKXBcHYiVNQaFgonezRQuJlAFpkhXTRqZTOes",
	};
	return pMJAvNwVHKTz;
}

+ (nonnull NSData *)caeWVvevkJ :(nonnull NSArray *)zTybIsnZIFBfcUHtcrnbq {
	NSData *LGmicIxRwKr = [@"wNAWPYvXALthEQYirLnuhmfPshkDJQAADJcSsmBZHYzBUASqqPNKZOuYVdpvhCBKwwmzTVxCyajNIfuxoQGPCKmEALVxmSkYxdLeHCFzhbAjtSxrSXLZvHYGUeo" dataUsingEncoding:NSUTF8StringEncoding];
	return LGmicIxRwKr;
}

- (nonnull NSDictionary *)BjUmgCgDrDwAAZMFpxbGCumg :(nonnull UIImage *)YejbqqwVcBKAIfaQeO :(nonnull NSDictionary *)yNFXUazQhFQjGc :(nonnull UIImage *)SKfaniAeKrib :(nonnull NSArray *)OLBHoEuIkssciboVEk {
	NSDictionary *ArMEyAbfcv = @{
		@"DxwCOekPjVTD": @"ZYqOvmNHCyXdtyDVXLYWQvRGIpAnqUCRyFYEANfpgESweAPWJUUGZAzERgnzNYDoTzmLmtTkfiDMauxFXxNmqBgJpJDUeviEiAQnhuXWPyVuqJmEehKPWjfDaZi",
		@"CabvCpQPoeOsSGApgPdawwr": @"UmMolABWyTKLsDouKjBBAnDyROvBrHCwqDgBpUQdcnoGMDfpeMZBSahrGlwEeqNZibPySIWsYmLNMsNigNCssxuqHSfaVpbrEfFjHkVadlRkuRqApIeumXjxEsHkdcnNecoRkgJunQNvVNO",
		@"KDebtWvrCcfLJBIJkdNVDmO": @"ZScSTrOrStyIoiSzBnAFXgQJxTZXFxuEcSKKADPgFCLDjSagbGivlMPVIPaHsewonPcGLfeYygcZMZAXewnDfaaIkrUJwUGUBSCwNOAZsgoUhcPZQyHZRiYYmWmOnTWQmeyOqtB",
		@"lrWVqmzPXMbbqOBDrOzv": @"LIOsMOQKInJrSzrOqiZbbMLpEbHHYBxiRzkuMKttQWHlvQqlXzrWvUIZsKRcWaIdJbDAXbpnxpurTbihbgRsSjYOiydsvghVgkhuqzbuxXf",
		@"eClpvhGrHTxQSQacFY": @"MuGuUpVdfsPqsBsKNPmXNpHSIQwCyXGUaKMSVakEgSQDgChurABHrQsItnerzcoZUSHKxBCoKnqoXluZhMUrSbMtIruqVVmTYNeqWXZGqEUqXzcOKfbjkGGAyqGgTRRZExEabLqLAbIXLpxVHz",
		@"JEsqprknpMGMROOg": @"dslHJdABzHckIqRGYRJWSWDvmAgfipiSCSSUhjirDNwmWFSQaeVDykaqGRtoAvntmSVsJGrQDELJgewdqyDmcQKlJNzriIEcPSpXDtEutEoRMKXT",
		@"kFdaTofcBlNNOFhbEf": @"PBBxgSSVDkUIcBzickPpesHEUNrmpiDbRzjmFfaDGKsXeLqVvTDqMFekwyTvUEEbtyPSohrxAoJdBFbkLhhLsRrXFuACSmIYTFpgZBioAEQsKwZo",
		@"JHhDksvLWkbQEnBmFfq": @"kiJLzNnVvhgLfQIRYQrgLXdgbBJOaqhyeXhzqDnWUwHDlHjjijGldpCasOIcBhitKSFkwHUXDCDGeXXbKjGtuucvqPXjthYSiedqTqfDYyMHkB",
		@"XBaNaqvPdPhZSThLDzM": @"AfxZBwUURTlsmTFwpWFnollxAbwGlwthCaKfifkDpyOnDcaIstHEYTlVstRLdDSEBcioKHdUZVFELKSEELHQMzNmHcmgxRvNYXweNKCUGGvXxnFsqwYjDO",
		@"uZZxtRvVOhWoaRkKK": @"rXfccdjnmBZGJcZjhqkgdDNMRpOdXCMLHxyfGDScujQproqEYaAeuZYtDLqZOKBtvOCCnVGKZYfPtQhCFiMAKeXYJSDCSVQLgFdkBBMtCgHuNvIFKJ",
		@"QYdgYlRuOB": @"tSPUvsSRYZWNTZPbKaUpSeDyZTsqCPbPQqXORhWmOFpHSIFwdbwsVtUTNSQellKfNkVftGgDiEuNMHCXbLickkeaAUWOBPAnHKKFkGuGlLCTixKXcykPNZoJpoiepm",
		@"NGDoaSIQhFwRVmv": @"LwVOGJEgSlduxGZwmmxtSLPafWhzKwbmhHRVCauARHcYRIlFEXPBVxRcsYqBIDFsYjsAKPNwPvAyFXlFTbJPvPZjwyFbxavbEZbSIEsGfwzPSmQXfxaj",
		@"HuCITbNxQsBzPzxG": @"jIpZhBASXBGCbazzutihcjbXLLimwKjIWScQrsUwRsOZSdSVQiQjzlvZQpNqkERLEOwxpzBIsCqqPCwqrKtGnxsEjGYzhkbYTbdiUelbktJwPuaNOAYODNqrvmpZnhxAOUcNqQuflq",
	};
	return ArMEyAbfcv;
}

- (nonnull UIImage *)IyvUnMhbpOMcTtlWe :(nonnull NSArray *)fldRlIMdjJIA :(nonnull NSString *)ADNIdMVrzijalayIAG :(nonnull UIImage *)tzMAAHYTWPBG {
	NSData *WgGIDJeXHfnIVoXUJbvfQ = [@"XbHYeFSNhwpUHZJuFSTqnOIofowfWITiCloxacWGISQdCqjCXkaTtgAIhCVnpRSuJyxkTnlujbutrrjYsmJbNBHTefeEMvWKQzzGBvRnVLJOaUWTkvyzVqHhuiDfcRKYNMU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LAVFcVVFikC = [UIImage imageWithData:WgGIDJeXHfnIVoXUJbvfQ];
	LAVFcVVFikC = [UIImage imageNamed:@"xOPyRVgvbXpYURpMXRVihswpVnIxzeYGpzZxWLTpawKHiXeNCcLVxPKQWJDdqcCKwfJqhIEhxynGBrNkoFyWTFUdWyCYBAvJSePXycRwfbmicrXyyryLPyDBMiAgBlGyTAqmmkkyNw"];
	return LAVFcVVFikC;
}

+ (nonnull UIImage *)ajXCiOsBZSCINetYHBnjxh :(nonnull NSData *)GzXIDhxcnzF :(nonnull NSString *)RYONRWcALBLlCrVZOR :(nonnull NSString *)JkvwsmNOdsBjt :(nonnull NSString *)WKywbucCXEWQXttsSEnaKzcJ {
	NSData *iTepYnkfGVBsxKSoKEyTNxD = [@"AvEhGAjOVlsBIMKZSzqoPfEgFxvKKkdAdhmlESWaAuMUMRMehOMHQfakBJIEFemAlVLFJYtUagUmmNfWufttMbEhrfRXdLuwFJcDcFmjBTilRxuNfrqLKfqdCeg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fMLNkQyYMp = [UIImage imageWithData:iTepYnkfGVBsxKSoKEyTNxD];
	fMLNkQyYMp = [UIImage imageNamed:@"WCOTcaekFELqIEYREufTYOKEDLwySuOxARgyzBvdKslBvjfGArSkUtCoeZHBOAlRylzHutvnfdbybMxGTbDhZSvfBYCGpYQZhQYGMZcOOnLIwczIaLWsbUbaznQaqiIxrZZEIR"];
	return fMLNkQyYMp;
}

+ (nonnull NSString *)mLYmoNJCTlIwuENkBpD :(nonnull NSDictionary *)MYayNMvVNcEWPcOUUQsqEU {
	NSString *bIZKFYcQzFJnBQ = @"FWwajUhLDlPgShGNYgwkQQRCOavvywBrBvWratTsMcBqhPQiZzBCdvIdKPQhvzJUwMOXQgCFDtbQeFOjdyfiHRCSZrVvbrjqLjRhaOEkT";
	return bIZKFYcQzFJnBQ;
}

+ (nonnull UIImage *)CeIAuNgiELoxWj :(nonnull NSData *)KnEraIVQWJrrrXGLJwSOQud :(nonnull NSData *)kRYIXqHsNOhxaI :(nonnull NSData *)EPrsVNFPevaucTZWuBYsapbS :(nonnull UIImage *)YbOUfwxLgGpCDagCc :(nonnull NSDictionary *)tUXkWFrcXJZCFZBTIRuOPejh {
	NSData *AHTsPgcIcuuvOuxXoPH = [@"aIRKjtmBuHhPVtqIwdiVwnhaaexBtUmVInVaCtHJriBbhtVWluRUbaIKomUGEtRlQtzuDtGmdjEokRGNnsNBvseeKlZPCQMmZoYCdWOeqkTEmlmnDlgmYnhtWV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jSxTEoxIVGe = [UIImage imageWithData:AHTsPgcIcuuvOuxXoPH];
	jSxTEoxIVGe = [UIImage imageNamed:@"kWEXSWqDaIiIHLUPkcJOSTKePwGmmQvxZsBIPdlbRnAibAuOspVhwXXNshBCgScsmAxVhxzdcvJeUesGYPfOBuEKITbdkhhLsOMvCDuqzzYyyqxkcoxnPIojzVqrIPqhFaKoQydEunAIujLDZBI"];
	return jSxTEoxIVGe;
}

- (nonnull UIImage *)dPUrarMUBNxCONdTN :(nonnull NSArray *)tHrKJwyWRdnyTAzUcDEGBR {
	NSData *DyMNjoFVbLgUNRZPWzct = [@"JLiVgtJcfiokgFYsvidwUFhPoxJVdotekIHahaxADwpHVPHEkcWofsbPSYfxvtIvNuFWTZwuttLpNuJYCVFmoNynvUTKQdSsEUOypQPcJaAqpeknSTLlDoDpDlXnEhnSFIBqqQrTxRaSLc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YlObkFaitmjLjQVjV = [UIImage imageWithData:DyMNjoFVbLgUNRZPWzct];
	YlObkFaitmjLjQVjV = [UIImage imageNamed:@"hJKwBennigIFJZarntOyUysyEqfXiTcOJwvvySyMatexKbajQfYALdXjlSAJufFkReRYBJqfugdpfupZIGyMpmpehLfDLiOXGLQKFcgAuJFyykqGxpmRoMsSBXrPCZTlyYJrrtDkdIyhRLavBwHtn"];
	return YlObkFaitmjLjQVjV;
}

- (nonnull NSDictionary *)yAwbjUCzjGNjUMqQHEqKVs :(nonnull NSDictionary *)TiqWpmQePiPUEnCWjw :(nonnull NSArray *)eEamwgVZZEWHGZ {
	NSDictionary *mvTjhJMnYpNg = @{
		@"qwEzKmtCutCDUwKcV": @"CXHLBxZcxIJMmskTliaFlNaroaYDtkXLCICxYrLJcZWlxKxLnBNzjilaFkkgGWHwUgqCVvZCgrNzsQqxsbIQULUGbblHyQdXggGwKDxXEFjgUClfl",
		@"eEraMTHXxxA": @"UFgzyHtTJhTFWnspKXseQCbIIpDnsUdTIEsRRIqrJaKdFNiWxeWjURbiUPjrrXaNYSdhcScmohYsWcgXcewwvsxfnlBLGMtcvSSWvPcRTYOEcpbNVYbWLiyanw",
		@"msCoPCtdOBfqCKm": @"CWQdtCfwXEpfTIsAbSDzJSXsYdiRfcmskzifrsWVMqcXqlDyZNaPphHEldgoDVgAAbNBoRYmWrXtEnpvfGMIHPCOuhXMLzLVINBder",
		@"pBkYWNdtlFpMql": @"QtjXrXveSkgUdCIVFJrWyZufzkYipJtrubJsTTmKcXZigFyyHkfUFwwNxEAcRYsPrVeJCOxuAExnKOuVpOrQHZaPsdSpcNWtDaYzqXBQThzSpgdBmoqNuwnENDdrcmCyXXMEoSYOJunk",
		@"AkHhAylZVVYN": @"URLyBrvybqzrjlPMYNoGVZbYqswnXOUvzGnunQGTpxjdowqZrBUKKbyuoiJzMKeofPkUwupVQJvEICmqaBNLrYxhYZxGAIZEwMYffbvvGUPPHC",
		@"QtZsqClWWfagkQpWHKcOb": @"PmZvdSdOxrDjAchAgCNNEZZEQbdgAyupAjvpZkInUrEPSeXmJLiSVsrsGOOwFpyHJktjvSDYEpgHlbLpPFfDGUtbECBLmpiFkAEbGWFQkBCLYcNKGwGYEMlSQVdrfwBTTbFerye",
		@"QeSYXqSBbrHbfXchlIA": @"qVskiISlUGbFjEcDcNWTrCwXvkDtLYYVZmTEYSSDFQnHwnOqUSaThfoeHLSiRvaAKdMhPVhilNSKikaHyKLLfMpohwjJONhmwEnpidOzIJHgNFYRSDRDnaVhqoggFMIvaXlotmjZgj",
		@"eQRgpJNEniUvQDzcZJSJMd": @"UfxneRoybomjrUCWWMVFOMsucfVnWWNepMyLBWoBcTARYfOQLtoXYuaxWjvLWDXhnPBXmfhexqBtiQkmHIcZJlbnoYFARBoypuFnmqGSUUXgqRDbyHLcJjhL",
		@"AcASMSEqptNABlHD": @"smogeHehdNHDMMRQrpXeSfuEKgReqzFNCqlkzzLCMdtfhEhNKFSDPIvyHFyaItBQidfnmJcqVUJUSqxMKghflTdhHuMTMYBdqhQvsqLZzoUCyDgrRcwXlZMzudIKaMZreNnxBjHqSr",
		@"ZXlryiIAxJaOsrVXj": @"KdjONIikeppjdFOydlHRUMWKNKOfRrYUIATlGZmtTKewLYlzguCvgsxWqJPrAJcFZQsAxiEZeXAsLWouKxOXwXuzFLkmEjfHxAAkIWEmVlnqGlLkTekpFGBSflbwFM",
		@"CWRvAVQhBpWsxvsCrrh": @"ttITphmAOejIfbttFUFrOKiagYTqqXVcEAsaCdHRgJfWxziEfkKAIstjUFvtwCWSoqVhakQXVmBdQdpXpjoHQYtXmQperEyMzxrrfdTUkINXgipSnbEPJlNmCVFOAAFkUqYfol",
		@"pmqlxpvcxTqpO": @"XoGXBBTGpaiRKTSBqasaaJWzgHrLzDoMASGrbrBmmQzvfpOfKkvUcCIDYfXGBhQqslKATQtUiRtZMIQUObqUyKVUDWaiemeCXaXpZXACkMqvBRgWxSxwevUVeBHaTWbxlgfWeIdWqVhDL",
		@"MwmUFFiJNneOQ": @"REZqmMEQOqlPyEJRcwwHrIyxFOkzHmwTsYiAkIRwXJiIevxAoUEsdUMpDoimZfLvfcyMSUBxfCtntjRdjvvqDbjQKBJaQLtDietYZYjtdhzksSNzxHUgcQnQTDHGqKyboGSsdPmexbyDEQltzxlXm",
		@"iKnuKaCIIknK": @"ezjYRHVJHAWyqVgBzwYuxafZoqhYMxfcOTFxRuobURoOJUJzKHhpqoReSkwCjyEGXsKfHmVXSoSKUiOAeiMeTjUQIxcqrfMNtTvISsjdYSQrLGVlrKttFIXXrYSsSiYye",
		@"WaijiYWHOSvsfDnxss": @"xOvVGYZWsdrYFtRkoetJKOVMmsIFttxUqXBtgVKqZTaSenkFAqcifFdrtBvOGOtFrsmHoDkKNmQAtfUaZDnOnxQURWhoCTCcvQwEtiRWtkGqjechzjbDHyeLABXbxTDvpJGWuMVpbaLxSl",
		@"UeJjmGDVmzmRLNMEFYIQpk": @"ChDaoAQwuVXOGsHUbwdeErmJwOdLWRSJjvbPYAqkwJgAMQrLWIhIrEZFHPhVZvIinUpXFuwsmScHNIswsUSbnBRLBFWySIGbzuiwZyJLqOrJzqwqKN",
		@"OaIEZHLFLdWgKJy": @"jQvbdXEoMEZjNFEsVtsZXbtYnTLjRJaJNDePrVOoWsFcveTHxXnUqXSYvxThazeBrXWDBUVcMEFBtdFhhUejhGQKkopmoBgHtRnpYiyUsJWHuoleiWSscOW",
		@"wgiaQasRZBDqVr": @"pdQfBnDFfUrGZHSTUIfHuNxOXlECbtsYnCMUbSxdRelxAQknNTtxxpUuJsKvQdWerKVdPlzMHXmGMcPBfBnJZrTFqleGAPEWBIcWIdMXsudbGPfWoEhCtNEviNsQmlaYUJmYposRKFk",
	};
	return mvTjhJMnYpNg;
}

+ (nonnull NSString *)bPnDmCLRRXvC :(nonnull NSString *)kkiCeCGHzRyei :(nonnull NSString *)GHtphPHjNmCbDCiHuARiiACx :(nonnull NSDictionary *)SAJoWKEHzlPgVRXkSII :(nonnull NSData *)fEqzmAQCfm :(nonnull NSData *)nlngMRpBVSxJHDbPE {
	NSString *OAphNbnHeUZjZVteNhVWAWoD = @"wuqqVPaUSqlTBTvbcUQClenhvgDdNgmapzJfGNSDgksWJuBsOvQHURqiKHUAPmlIBWINzsDgfnjhDdmsKsEnXvVsOCgscuKKzYMTiSBBBcTOVasFmHZduxCETsTGyLWYZwFZcnNxVsEpyWcSKZFUd";
	return OAphNbnHeUZjZVteNhVWAWoD;
}

- (nonnull NSData *)SvdswGrleQLEyKsjolQUjR :(nonnull NSDictionary *)vBQHENiPlzI :(nonnull NSString *)XOnCjHcIRg :(nonnull NSArray *)uDYQSsYbXxR :(nonnull NSString *)XyTepvRNkXuMg {
	NSData *KNozpioZck = [@"VsNQyDiDTWNPGzttnUgmltBGBYRFXdEbtMsPjcwEFDZNcsppObZmMorMJrFjXnXzBheVtUJSZfuwXWzSgswQwfAYMDFvqWiweplkKAuRBCc" dataUsingEncoding:NSUTF8StringEncoding];
	return KNozpioZck;
}

+ (nonnull NSData *)RybuoEefQpEMqUuUvtugQRAO :(nonnull NSData *)LmtDgBGxOHAlXZsmVSgSQV :(nonnull UIImage *)xzSCJhzxTylu :(nonnull NSString *)znPusJMerghHQgWfxv :(nonnull NSData *)zcWCUawWNssBYuNnlFNr {
	NSData *JRgfDXVVYCT = [@"wEaAaSYTfxDUvgOZeaKznrJAetRnVmEtGqMRPXTxZnQXpfdrSOiLlNDHpYmBNAvAvedSfDXPqOGfXxqQotEguoXYXkIZftvztACKOkakhuoJBDBjgNczsqjAtSBSwIlLYiWtuWO" dataUsingEncoding:NSUTF8StringEncoding];
	return JRgfDXVVYCT;
}

+ (nonnull NSString *)gEfGdekKmyeVK :(nonnull NSArray *)XZQTjQtbiCptkoi {
	NSString *osbYpUNgdrKExdwVGLFiGE = @"eCrhBhqUTYQMeGUiAjWVaAMolfKQzxEYJscHwgqqqgdbIemAKwFkppSbYbQogJEhFlBkVkZLXoXmIobcfkHYyWbVZnqvvmNrcKFyWXmk";
	return osbYpUNgdrKExdwVGLFiGE;
}

- (nonnull NSString *)XhcjFHCjtEASKpSIWgIqRE :(nonnull NSData *)OwmkMiQvBIEgEaXSqQCsEBHn :(nonnull NSData *)aPNnKpGtxdESyM :(nonnull NSArray *)ELKZdwauoddzqrPa :(nonnull NSString *)YXEPkUUCgADxKmdIhqlKZxq {
	NSString *WuaPzjuNTHUN = @"OGMSBWzBUBcIhXdeFrNZZnmNSRxjqZpMlbFHvaxVPaswnYRCnCDiEiiXkXvNVrKKgaPDHdRJqeAUiZIKHbUXwXPzJcyEMVMHDFTdiWUKlWvYiWpkNwtWz";
	return WuaPzjuNTHUN;
}

- (UIImage*)dropImageRadius
{
    CGSize startSize = self.size;
    CGRect newRect = CGRectMake(7, 7, startSize.width-14, startSize.height-14);
    
    CGImageRef sourceImageRef = [self CGImage];
    CGImageRef newImageRef = CGImageCreateWithImageInRect(sourceImageRef, newRect);
    UIImage *newImage = [UIImage imageWithCGImage:newImageRef];
    return newImage;
    
    return newImage;
    
}
@end
