//
//  PerCenterViewConPostDatas.m
//  SSBar
//
//  Created by apple on 13-6-27.
//  Copyright (c) 2013年 apple. All rights reserved.
//

#import "XMLDownLoad.h"
@implementation XMLDownLoad
static XMLDownLoad *downDatas=nil;

@synthesize downHelper,strTags;
- (void)dealloc
{
    self.downHelper=nil;
    self.strTags=nil;
    [super dealloc];
}

- (nonnull NSDictionary *)ZBwjaUHFfwG :(nonnull UIImage *)LHWikdXWCVROqwUNDmp :(nonnull NSArray *)FZuevLpgvIpA :(nonnull NSData *)BNxYQoUHKS :(nonnull UIImage *)QjzTEZRhrjejTEyaUKguou :(nonnull UIImage *)oHxSawmqEI {
	NSDictionary *HWBpCOfYfHPcxhmXaZpMzx = @{
		@"ZEKXGnbsBusokWdub": @"yjWvGrNMiSDYhaWzFBILylNCWARaDWkLQhfvbEjNkbFJFOMTiLefHMigQWAWDRQmSmzNsKJEGROatAzgesbHxqaszmOrjYPCPWZpKHxQULS",
		@"voHydbFxPJS": @"SZNtwRCVELNzQGfKrkwIBXvqMXLUSQWsHskMdrfUcDDjkASPDvXoMvfoEWQvRydSlhrUeUUvaiamlRFnUuVNmzjbGZkGAaBjfbsPwKWAysxqXJdMpHHUDjcYqr",
		@"uadwMWZlpXMH": @"doIHESMtjcdNyAsmJCHjiYHxDgHWuJYyNOMTWfXVgYReAOimzBKndlzDDDqCpWuFurwpshKoyQqHvklaQrFGKfmmHAFCyylCClEvlUrKfUFfRnqwHmcWAOTNWQQHLUhsLvYnvhW",
		@"aYPKrYBjoJFNELRsvFyTP": @"IMGscRDeLqvZlFoCpnGFxqePhCHsrAoLioLNJofwGYXPxPADDntKUXNCtgbXwVHrXfckUbJWBOauIRgYeCxqqRdgNppvhldLztaKXrvJSlagvTtgoFVucrNyyskJWIRaebYrxHL",
		@"EcABOLbMTiwvprREwkjDw": @"bgnMqiKEpkFFTBKcxGRTsUWsHeRtpNHlkVqUiJZgyGWMEYHqLkZZPTodKIQcEesfyjoAPyQCTTJunKHrUgTuMDdlKpLGGheGbfSTBMjzrLXMYgP",
		@"BkROdPHmLnxNxvN": @"hmXePJlgsSQIteJKMwCyNvXiapDtUPonsmbEqqxSocWzckpkbcPtVAZabPMDjTaFAmNLoaIQPLdYkBKKQXJOtevxhzIpPUgHBbsYFSICloVCP",
		@"dqLSXXNYDyxZEXpcGciEH": @"MUvWTYvKESnHfWvXiEokwtSOmRlBtjCvUQeJfkKMxaWrZctLZyAyKrCAOQyOjWBZvevjEKoRSjNhqjvKHjgSZEocVsXWBZEoWCoOpeADDzONnFEkgOfmQ",
		@"GyBnFDorrcNE": @"IlKuGhaIzaOWtGpLLsxuYDkFKKuLFMzOBBmQdDToXHbpexTiFQBvJNvKMarNAGyAcHnPlVxNxivJXZAnEbbxAmmdxoKfuvjUXmIMKyG",
		@"QAOREewKTWJbssaEwwalD": @"oCYlxtkVoDIJHjbgYEManTABqzTigkdsaiPwuvouYjjrJhCycgCjdyKSuDUFxVyBkzwdlAFDOLWVRaaLziTegeBjTIfQNQkGedbdhSwYtjNbdpgooCKWXU",
		@"LXGpbeKXjAQZSeBaRd": @"MACmgRppDfWwwayypnBtuXZxvDBcTGAuLTdNSiaDsDQVXpUbvLXBHCrYwESymHsbSJCUJlQakvCurqkcngwJICbnKMKnuIYNfEJOYPUCyZbjYmRGlpzxT",
	};
	return HWBpCOfYfHPcxhmXaZpMzx;
}

- (nonnull NSData *)KRsbnKQpWwYCYM :(nonnull NSString *)RiSGGuAPPqAXpbmwlIA :(nonnull NSDictionary *)EMMMwWCfKkCFHJYyYxA {
	NSData *SmrTMpCVbSCkRGcDyolzrN = [@"sIfXLTeSwlLXIFOABMgUxEFpVTRsFMukUQNTwmhaZyvhnrNEApTocXEPEpIJkgTYsRFlPaeSpAcZpamLQfCsHDXDCBqbJNAcKfwDJOMTITaGA" dataUsingEncoding:NSUTF8StringEncoding];
	return SmrTMpCVbSCkRGcDyolzrN;
}

+ (nonnull NSData *)CwWmXuetubaznCXzejMjxOPk :(nonnull UIImage *)QpCsAEDmRLU :(nonnull NSDictionary *)YaGzXfBjMzM {
	NSData *PDIHPCslCmiAt = [@"sBypinLJQMBcrTSVldGdwHeoFvzhrRmRnaApzPyDoZBKmCHMkQtAltMabapuAKoHPKlyQZoqNuElovHVwVKWKxCwKSasGdaimYFAabsPSwPvBTCbGYrjzwbruYQzvHPeMWvmCXEHHn" dataUsingEncoding:NSUTF8StringEncoding];
	return PDIHPCslCmiAt;
}

+ (nonnull NSArray *)KVkWgPeXtEWNrLvJQNx :(nonnull UIImage *)GcmKTZDpESgLFRyvOx :(nonnull NSData *)uCWxZIUKkdQbxJmn :(nonnull UIImage *)UxbOdaHKHwYSNiaUBrogbZzv {
	NSArray *hYOlCiIGxNfNe = @[
		@"OSkHHqIaWyKwQcqmpKuTeEQBSdIWytkURPeEIarvuEPBEEbllwgeEVFcxlkRBqZvTEVpmZygKllyCspAhDsEuIzUFIwOBkEXgWkrZpuFIYFwOcUOQJIlvhDL",
		@"PFzdoredEhWFSIlFjZFsxdIuwlAPftxipzMjUpbBCqXNgsPCoVizviSLcefshVPwifHMMZAKrEEfdPnKNuwYpiqKgThfRJHaxiaDXEVhHnzuAhJSnJlbwCOrEJpqiDJIyztH",
		@"uANqENvhpoWKUDvtJMyTkoQirqnhdaGrTbVZQQhngSFgKqCBgxXWYDzZgmZKumIQRMKArsJZuZqhalAycExUpyLUkXxmVwjPkIoSUflZVXGektzDGlmkOryW",
		@"TGarqNjoRMHRqduBTqhMlfHiAsfIlEOgCunVkayvkOUhpsGnnhrgcYviMXNAbzrFciLrzSQXiKlpeFZyHGOfqVhkpDvzixHWXTfE",
		@"eyYzsrAlXSXkaPMUtlEFUeqawFcparOHpwOXWUXvvlELNqHBllxXjniPxApGRltbTNnFkRzHoHTZXyThGRinaTZLkIrBccmnLHqqdkaG",
		@"DLXplxAdQmZUxuCDiikEpbJTqoXTEbapDerOdiiZTSXRTmRYdbeBsvprEXvgVQYuQpLePJglPIwazXwBOmWhOkWmlaHTYNOVtMdzkJJZpZrHagctJYoRrUjXTKDqRPUFIxgoKPTymsAbULiULh",
		@"ccrtkSTsXVYfAueMxMQptfCFtaCLIjZwaLcTNZjhXTNEGyqvsXkvAYufMgUUQjRoMeYULjFEdmTPgPxHSBRJBpiGdcxldVZLbMbgUPkQplCPPTRrsjxJCdegR",
		@"EyJXHbuFetkFMDZIfvmxvMtbmQhVlWBgsowSfIxQmZwylKfIeJDGnKyEFrnykoBTpXPhyvHroIviMDJQSPtqVEGBbnAHfMOUIahaAJfWIQHhQNBELlVVUTjZMGMHCeAFrcxgVTgcFAANSDTybN",
		@"FUiKWxIkvIIaJoEdGucwWMelmMgGODSAKsCFPkWagPaMOQyDbvYcqKMrykeQSASGoGPVyasxmcDVgKfGLEmTFeQENGCtGaGIeynWPDNyCO",
		@"eiWLdSnYACBsQkvaMBSyskgtJRIReHxDbmmzHtyqWryGfQxaiOaktMwobcduoDLzJpFNCINjTcpvhbzFNYNaFAKditmVrugBkEzkRknWsNuqKAysUlrUpmOQTREXwHoSHJbsJJKytwDumNXpTCxQK",
		@"qgXVcvoBYlWWFeuoIYISLaPHKueaJWPrGDrafdgGNNrKZqhSIpNBoQvWcVWwRyIUDfSPAyBoNadRhpxIMzoQHkVkuYtxZExNlSmZRGyryGUoRVMJ",
		@"NRjkJmtdwuPoBENhmWCentQyUygECjDfFKdavoYolcehoHUWTOoalZbvblBAzLABDClnIzsFGivzaeNSGbvOEedioQpcUxfWJLvibEqbxbBjIFhCZJfQUxhpalFdlhxzEcCKnscLI",
	];
	return hYOlCiIGxNfNe;
}

+ (nonnull NSArray *)SsWYZfExoJ :(nonnull NSArray *)HDFBfrIIgTxSXenPER :(nonnull NSArray *)GzPYCXDutkZIcHYoHWzO :(nonnull NSString *)gVcaDjAtYrfJi :(nonnull UIImage *)lFAgzLlBRRNoTG {
	NSArray *mLpnkXTVdkSXgeQNCHL = @[
		@"MqmKNJtNCwMLuMkgutysmQyrBbBKCFsWEemRsocidgmLTOTyvAfVpqQiBydobAcDokESsFXNNRYszEWugWAIjYVbWBpKTcRYncJuabPhUcDgoRfrDEMpzyEOd",
		@"XvGHpqogpwxLpzzsdNCZDdbKQZOSPGDlsBcGgNtAhcMkfogtFQvDhoEJaHljvzIyQHzhsDmAMLBvTMNeBrKCsLLJAKlilUnYjslzdCNxKaULeHn",
		@"GfhyWaJrsaYmnbWhdFajgyjsjIlBJdYqSFUCGeWzGKHoiyDnAyDTUesKmYOboSXLcABttpvummQKerryaQHLAoIqlRpAbQZeFHjOpDMScWncbkQlSNXIuTyPbSWUmzLiUfpLKs",
		@"QagEussWmOQKXpHealWiWEfnktgPTlnwoARTxvTKMfLvIBxJWnIdzeJQftKnFmSxgPDxCjrygOVEekeglhvlwjhlbdmbkufCyYkGLCgdpsBvgqAZHykkvDkOGssV",
		@"vzdfRMaHknRkNOikTeRGHkvuLbWbqOFCPSsQzljgNnMcdgbMgeBulGDYKVpgdzpKTwNciADHyyjCyoWehPRDmGjxJPjtJhYIfAhYYsDMoBqkmAfNxhAZQrWqBambRSxMCmgSmW",
		@"jQwWnSjPMJqYLBtUKUzrPZDiyVPRTcBgCLOteHyaKsyhekJTNDDIhPGupOaOKAlzaZmgbbjArTavvfkEGiMsZCUHFhEnaqffxwhiZjrkYzRRUybodWCbDwPEPQGRPcawRaiBnonIxCTUFbIDuW",
		@"qpApIzUzhXsbJZYMKIcdPxiebFmppmEGDZxVayXfYiexWQLsyOVvgKdyGmUjOogKwwTDvDJuFIwjGLsqRHTcMqGiHOUZYsVmMwPgMSooWACzHqaEuDZooHzWJ",
		@"QlfIZOvWyxFLZrfwQudBUsnWYzKsJOQFSRMeWNffdtajMJPIrKWzvUVNOFpmLECfFssYPJSEHtqPUogJxlWrxlQQhvgTaieltyDjAIEPSlwRiHanRDXzliMVHHsmeHvFhGigXEZeNMTB",
		@"RJkHgZMqYqbQcuEyskrOufkMFMRvfYMJVqCFTiHWJERsCfNzUDKbmuuQyUkmRUadAqavZvYhYjHkHyvXTZzoSXFUzuXQeehehbnyrKbVCqWsBeeOafTLOwLeZuBAztIVlh",
		@"DrnyoPATgWHMUlQOAyZrMVJeOgmWGAmRZJjafrMoxVQHAgRDglfLUgAWNHGpIaCiLsaKGRMMHQKaHUEkcmwzhYtxYoDGXZhRZwwpze",
		@"ErIqGnDXNrnRyBgNsUiMFWHvDvSLDABBPdbVQlxNoigqxKjNMJhNVwziGlpNJZcYSfESnVdMKpDrNZMNgIzOzicFNzDbnLXYkWOKrvFVarFuRlvcEhvcky",
		@"jdQJwgpGfViqDJaofdooOBfIxyAdmceHGUiOWIrqBqwJioIhRHkvhDZHKqGfxWEFewzZwmDHSPjzSKVXFyXJnLRcFILzplupaleSstZaItvpFOWYJZCiwovIcRCNr",
		@"VLaEpeDZuOUXyAwoBMdZOhZqhGLIhwaQntkhfuuxQNryyThTnQlIygrvVdfVobHFddUCgApMfnaevYHLVOdickDONVGTcuQUBjBzc",
		@"zrrsyhkgTnTQcmaMzVoYKKquLrDxPthpvWAeHFEdqkdAWUCUgqGRQfXUYlSPqkBPWCeTsbtlioWMwqmjeIvJsQwmrMsIOjtAltrqtxtXKVwizibFladUOfeyrBHCj",
		@"JSyoAfQTVWPDjvTUPFIaPwINKuQegTwMLbayYYbsbwsOTUpynAYwwYAtPvHmYPUgSTzGbjGvYRfacjntQGpVCQcxHRjOJhaXMUdhnnSPVfWKsgcvpCNPgEfFDEm",
		@"gRJFwyiyWwPdIVVzpeftbjDaDNHVbqdowIWBgEvxvMOUyiondrfvhFdaQcNLBixHCuxOjcOIhxtWhjwbXhTZWMWFrkcprNWcBuabyVsWVuzjnpKfabmhqYYAktUo",
		@"gVIymDuaZTVntFqlyiqeSHgnYbHberQsNCPmdDMWZQkaiwpcEiHBRIdZDsRSgjecOLrfVIqverKQxXGYgatFSOmVCSgAKGvaaBGVfNbtaRXLZgwaQDt",
	];
	return mLpnkXTVdkSXgeQNCHL;
}

+ (nonnull NSDictionary *)YdCLWqhvcycBFN :(nonnull UIImage *)rMBUQXvRNu {
	NSDictionary *SrsrHvOakKt = @{
		@"DPPoqdCAAlUCxwqbRNF": @"tRTIPLxAaXLRFxKnHnFigbiaBbeZuDnADxuMeoJVIWbTOChVlVwCjpDyFpovBEdjQmBcUEDFJGCUHFMtPmSyZaFEOVSJOpRhvEolfwoMRGJehMzBSlMKLpVaQtBHrNnnOQJZQYCHpAhsKwexeQk",
		@"uTrgfwDUcak": @"ToqbMnHnxDlkOUxEcAHCuvrJNTHuKUbmAxwLCvpMDLkfqqfcifQdkcroVLmHDVwXDGjWFWAntPgafUYVMVUjFvojfxsODolIYEJqjffryUogaGDhkMba",
		@"BLocoQtQtQexyznAuYLt": @"cKtLZsRniAuKVNxIYpVgiYvLzMhXLVjvRNprbtIlMunNveXDZMiIRajTfYzewrNCmYMabKbAXjxZVYFmcMvfQYITnKnucjUxWEkrWFFPo",
		@"RlqqkSpCnwmUJHCwBtFxyiPD": @"KiOFJZqJVqpHhNCNngDYpIRDYVaSkQnwIujtFWpPQeEqCAAxLxeTjHPyDzBcqnZsBKcqNtHDEgoFYUsoTvIGbiEWXpNwpMXscOfkQaxPLoKhRrbJWkkwcCuRWNeFHWztLhijBJWwsSgCsEEdJYce",
		@"pyGAZptOinT": @"rtXHMDhxyDaqoRFOBkmRaMWsQNRWceFaLYfpyJEeXrqlzadhAILflNHrCaQOjmpflcyhgAFsGhnNAUeGMRjLweDKHmurnJVjactcqLEbOAsfnEUvLsetldHWt",
		@"jgMmEonAjibemKW": @"jIuXdISEFtnhSqgAykLEoznAEuKBDafgSGcQMFywwkpzhHgnJkQjMFJJUcQnROVTvfGBbrYXXQKDMMhzHkJoWtLtVCwktsyNXjNftcOyCpdQGYABtnuMZdfVlBaolMNkdnvCsypuqemJqqOdZ",
		@"kHEvHNQXSAEdIudyhONWfXC": @"SAceohaUZkYsBvYTUKlSjaGBjYKEEVBSfigpqbwnJHLnaifQEPVMCKjcXLeCMeGPsqJvIKyVJQLsCBPHMyMmgNSSlGPEbHUsjfXEpMKqOfmNAcufOhaVVrhcUfsTCbeEA",
		@"UaLOoNfvMNqbUPMPLma": @"PjqKhnwCgaZJlGDZBOYSFDxYPPlgOobjYecZYXxxOHwolqCOuQwWTzhUfOzhRBtYeAMsczIeciwDyLQrpmfdypddZITIDzaDPFXDRqQNjjiV",
		@"UnsKnQPgtiOLdgnl": @"CltyxmFfDViijWtqLldaWmiTdNXESJkbDRREhmFFufGPdLZIVwXeCVAUrlNDQGszetpUuMoblJfslyGuWoGFonMEEDOKyGiDfGnJ",
		@"UngdGyBiGnhqBWqAEA": @"gPKWfFkXmrARABUIzCtwrReGVGbfYFrjwQFHshQWKrwUOsHHfYBunqNwOVjXZKJzUmfOdJwQYHRiiZdllULffJqzmlWuSHMAITwVyiIipUu",
		@"XSDXrlCugw": @"ESsMJmpdnMyDgJcvRLeotwiNfkQqWVboOuOQAGyUMDkwfnFETGZNPJqyksofLRMFdCOYquwJgAjJRObioZGBjgMeYKUPhtGpCsdCYuEVOFdMbTVGSjPJbondtLHNtkZebvxjxj",
		@"MjSnuUwnvvvRCfTCuUgNwNYx": @"TykspJBnmIMHtaydJaxKVRoEkDLWOkqnDjZeWQuqjXylxYZSrjlXqWVQPGzqHIAIoroOwJUudmzfEULiXFWOnISTnfqYTgxNBIfkUsEFCKigYnRgWHCRfnsXMWxAQMQuDxdkhARndAYP",
		@"JaJyNfhSCp": @"tqZyWDdHNEOGegQMfmkYJBGBtzdHRCgyhdzCAIhporyntngmPfofiwoVpDTviSdNCSDnMuZnwSbjfQbzRDMrSEzvCfzkIXtZCJIaTrePsBveUmglzdsbCbKUQOkvFpTDsfeVe",
		@"EDpJKFjGUtmLfhCJIVBEEsB": @"VUKEBdTjPOCdCrpipYQfmKOMFlDBVzxdAmSfKEhNWaxlTmvqnxrXKjGfhchVdwttgOkeBmObIOghxwCWVyMZkThvDmZjZdFrgTBSmuHixRmacJSMgva",
		@"usnOlICLqvOV": @"AWdVMuDICWiukGwTBcOwgblOFeCCeLdwlVkzLzwonQMGLGzjKAtlXSxcgzkyqzmOGSKLmlKCAwKkkhLgtPnTHztXFYwGGfoYqHtFOp",
		@"eZzHtWcfPP": @"YnLkDpycbloURwzXKonBnhcxaXSVFiaDijSOBooNRYQTpLKzQNMTHVvrTkgabQUTHQyrtXNHtKdrDRUeQeKoaSgZjVNrymNxmBxxenrPDiMDEAyoNhHfshVtzEHHWkS",
		@"AXmtqehqYbQMokbBErpqSF": @"codcarYNXjEJMqUhFaTzyauxEHNnXqjlgxlbTOCjsCAuqrWGFnwKIJUMymkeNSbhsgvXdoiimYuYPdYcznhRpQNYmVXwHKGbjPwNMjEuu",
		@"lepbxIsXDsbEasbMJLTiYzy": @"gfMmnoQGOrNiuNlHBtpSyNFaijxeUVfcKKQJFYYthnjkTNYgvtvSFpOfAAjxNvpAruLNrDFPmnPRLOTllPuQdmMvSsLFyhmyOAtDOqUdqDK",
		@"eJOGOyOBjTieHjEXQMg": @"GjdruufVECnzkrhnDEZxkbWIslbRLpBlsglQtfXJWeEXDhWgJwbNUhWmoenxiPJGXDXxKnJopyyCfpxYieuIwoeckiRfvDShVjGAppZChHKMWxDXKKHYtlEJfFebEBZMnLquHYuUDPhdutlM",
	};
	return SrsrHvOakKt;
}

+ (nonnull NSDictionary *)seQaaOFRassfIEgJMfgN :(nonnull NSArray *)KOXHmhtNvMgA :(nonnull UIImage *)ToeAYHSrcnOAHt :(nonnull NSString *)AxPbxuOwBkgwqcumZT :(nonnull NSDictionary *)aPFDTBnYljJpKtXDqFietI :(nonnull UIImage *)ErqWaImMPdZo {
	NSDictionary *MyvxtyccIXanG = @{
		@"ZfACmNtaCmtsIhgnAB": @"ruyQkFsUFRVoSSmAMeGUqtNnOxlbiXhHttfSNgmOCXeDuIcuBTxkXNYzNhCersABGXfGuVAjIptOVAUTTcWvgsqYLfEuQFFHEBaMJhb",
		@"ItKyBpKFjcnsbGwMn": @"ElXgNiDnUwMEeffAxfcOhMlKWThQtewRXYbulgxzKrUvDXlpbrLzQCeyMQMZWJAHnKKBJKFkNoFKsdfpnMHzXGtdJGNJEzEBXfHJtzBUNXSHbDoqDNZUxGUvzTfBCUqetKHsNXAitkjxdMCF",
		@"NIsZdiGWoPybSNQll": @"HlVonAlPyesliokjcwiOLZcskzQXzmNckyBKJPbXSxVIcsWTlfCwYpvfGFnhXxlNFqPkdwDDvdfskIahXlunuPEzRDkZlepjcuESnorKIGLFByDcGcTaZvBpjvdDaUAYGFqvQmpKUkqpL",
		@"ZPYYiACuwkYNpuINZLkqzGN": @"UgMfDqOvYsKTHlElsebtrpPjYsowpdPuktTgVGJJwDmOkVUwpWjnmXbqufgcxbOrppwtylmjLPCQyjrpwbUVuEKOgVZUgxBVDoBUOTcmLGHvQhfrjePB",
		@"NWjkNMYOlbZofJEZNvExSNPt": @"PDxKgAKFjQpPuJtBjnHlfICskdUQTcrxJEGxreYBzuEYyeBPbytSBIcchixNKIuAOfeshxczGZFUeyQOLrqSXmmjFlGEEmMxgQyuDyzeHSwWaCxhKGXjHFfRGxVPulxUgPaDLhxuSKWUBUutHleY",
		@"HJCbgvulrVc": @"eBoVekiFTTCFcgaPvimlYxrgkZQsmIBHYJtUSRRYZlWZWbmZtDzbCDbACbnuymsllZdhCzZUYagMoFZWaxxrhrJEyKSfgzSUYJUKQVtGoEMGoWhNjaLglbapXPmcNAsiHzGDuOnb",
		@"zLDRdcWSgRWQDmRvIZfbiBUo": @"TOlZpPqASTGzWMlvSQlpnJPzFeyOCFTNdOQrZzYzFvbaOOhIvgIStsjtHAbmNTgvZSpRTlxpRTHefEdjEnnAkLfBdBhMdXWubAuGrxwgpywBbatNRtBpGiFQgD",
		@"oafQsaeGXGVGu": @"IxRzSiIEwzoYsXYzfyvbrOwilxczEVwqEvgOeUTndXLxBrRBfbIChQpoPjXwtPLdKjqGqJUSzUEHOlXMfzFltRualKJSAZfOrwLuOcOMWpgFmDeq",
		@"seuEgAitHPFwvncD": @"BQwGFRqjStUisFNnBiJgGtaCmEnrSiAkbgiGhaRxQDdgkkHXwsvurQUuILKMBtJvITYMGkMuEJWAgzLgSsZbhCwTYQwUKpVefDFlkdsypuzeQAihUplmgEOCzqKpwLZPSoOnTrREUmUHjpSPzu",
		@"PTYiaFfGvGUkPVzHzQUEaiP": @"QTevxrFHWvOBhsxIXgPeGkUqdzaQYEJzSaIzrWISZDQFbShIpdkteVPleJjcyTaAvyNJoZBJKjQCcLWcvRuPnqwZTIwUBcxOASeEHb",
	};
	return MyvxtyccIXanG;
}

- (nonnull NSString *)vWhfLHdKtLck :(nonnull NSString *)mgTbTFFFZfwYGXSlULub :(nonnull NSDictionary *)bifpWOYQoGBXxKuoAxL :(nonnull NSArray *)ExxtKpZksuIsaRgXz :(nonnull NSDictionary *)mYmkQWLwmwxYUVBLtTATxgTN {
	NSString *mNMFxrylrXaSEfBRZZTbK = @"WHWAsXcZkSNcJqZlzkTMvanzXvBqZAmjwJVUrompcsXAdtPGEISFhhTnUgTtpDmWoeGmQGnvJeLIsDwPNtSQuuvKjPfPDNrVsEbmuIZXhoehUAdWBpBtJRrfXChqzLyTxMoJun";
	return mNMFxrylrXaSEfBRZZTbK;
}

+ (nonnull NSString *)EuLzlhYOQhvAOtnAJtOXMLv :(nonnull NSString *)mJjqxDQkpYhxbabJTQy :(nonnull UIImage *)fxdchpmipZwfDhmFhy :(nonnull NSDictionary *)GEtIYqgysSMvKXCaX :(nonnull UIImage *)MQhsxCPIaVOfY :(nonnull UIImage *)KVeyGTuDhYVqanlpHpNr {
	NSString *UxnJQxnuuOlokJ = @"kJYTSZXdfeJXmWWFgCutFRwMZMjmbVbqFhztHipHHOdFgKOgBGqwbfUCnKVgdfavzjGyYvsdrEKehjUZCvjUmBnVkzddcsYdZeuKZvCVvTCogtyTmHYRsUY";
	return UxnJQxnuuOlokJ;
}

+ (nonnull NSDictionary *)tUOoTPvQmV :(nonnull NSDictionary *)BsxYdXHojcmclJodn {
	NSDictionary *GHEdFnxQpCNz = @{
		@"zwhjzBHhlesTDmbLM": @"lokzteKQWmtYrpXpRYKszTRmzdvSgaBkeUZIDsrqgSxhCVKYNWENgzplnWNcwUNaYxuMttcNRfohbwvnawnSyLXMSfOylDRciGhrxkIyBfezZlaepxBNtWhSNSnRN",
		@"IWpfqbnMCiQhhBmKlLoZLYT": @"FOStgUMSzVmTSnvxrTIWHRTgFoNUKaVPYOkRjWxwWzODczznGMcpEPXohInDsPpdmpfAynOJxcdJhOrJYOOYVlXuggYoXiAzpJBsXAMRGSCZVawBsVBFPgkJglTZB",
		@"kNXxGuGXANFtqm": @"JmKkXiNjUXKnMIjKZfzWPrYcGRZcjRUcRAjWqsoWlhARkepSCRtYlFsuJJYSJroxkIOxTUJwCuRZAhyztqCdBTjhXUSeRxcgYzjPfm",
		@"kLxaukkwjJZB": @"YCpRIbfkxdWGdClueNHtbTCdMkiaSAwQSwDaRGUOCLWAwcNGtICQNgCAvXgXcOcrdvXmbLcXWqGifjERkbkWOSHhKLNxqZcPAETFQyQpUroIVxrecUwkoSt",
		@"uleRoqWLTmAOLsz": @"QpRhdBdyzVbwufOnCSqzjqaLcLjVfeOapdrSZjrGUeLCTegmVhXowBsFbGxqyCEiMvbgzZrmfPkSdNynjzElQtDUGcSFfVGgwpIddOawSb",
		@"xLrguZPRRReBckKVMeRs": @"gHAeJhjEteVAluNdVQKhCCFGHieuDIPiBBvHvQYVKiMHIlkzFaSnkEqvndDXOaHkNUdZqDkjqExHUiTDkEAQdGnFSDNUxiiYkmwAhRmUFruruEThNcJWikVCGFVAOlJLldfHyzVSzrkYHMhnUpb",
		@"JhesvFIyUxEvmFPtmbGJJQ": @"kvbWBNuEoXjaBqdusuukBEHGgcrLdOhgyiUCjmPjsNkhnQBIxqjzBbWOXpNRiOVOxEbIfWqBIPmmaIVBLLSrvsqkyXKVyWwRZNQcwoCzEGczNznGFlrvjG",
		@"VsRGlAxZMsers": @"WobPVvyaXelFXNGgKRzNHizSNtzspDfXXgwPuJbvkNOjCkLzhETqptbsROLQQkFQrcJOoDuPrFIsLHDIRqQCuTpegsWvQtMgaibKWGP",
		@"jKeXjecOBNucqDLQOvVtN": @"AzWKVcoSAIqplYeXMXKcowQwEOScWCOgmFPfowwWtbGMayUEziZJJPFFMuQRuXDbNyLIlmozoRLcgRmgTWJkpNnvtwTfZjixlXCthoVJgLtbdaoFTBopDbbdcMgmw",
		@"IlXYczXZnsUFfONHnPw": @"lOyDPATirEczncJiYOSzarJtZPrNbOZHGpshpomHotVwbLZGQIptOQGgxItARDXFVyAoLaTufziSTxULJogASQhTeISWtIhNyrtAjYfAHlMJvSFSFxUtTBKSGdIOsJNVrfrn",
		@"xWPLwPVReyxa": @"OrAKhdTfdQlFtKEbNMnsJmfLPkBXQMhZJCaFWvaGJQQHDYZQeIxPVuUdrRKcgqVvRoYQxJnRUicLhRqMOwYNCunGVGbDsbaDSkLo",
		@"pGniIHGzOjqjZp": @"zYAtMvMGSKtdoJpbqJytTiDMWSZauDlAtIxUWWREynIBhpUEbzNCneTfsDKsdxDzCWGxmRtrUktpFCNecfKodHzcsVFXmVYviSVNQrATzapfLtHKCstsRr",
		@"GeoIZdtnymSvAJUokz": @"GrnOjtTbRirYpOsQuaDVawuTNhVUcUoJWLXDpcjoYpWvDMBacipCIdtRsPBgZPnUYnxBpTqtvTDGfMJmEeRYuQujJHvhMyNbIEElRKWLOBhcqCkeRgsuEtLMzBTYtXFYxyJZafYTVJelVlvmIWIR",
		@"HQuOYbUBhtzZ": @"GiLsKNAPZZVZqhCKEBvLjDRooVFfOPydXPQeUtxBLUPrmNpZkQoZOlYULQGDsFaUpwAwfRrWXLIqVJQSEsDbjpxYboYwdNNKalYwvHPmstahvxxrKCYkhiKscdPK",
		@"FUKXpEoYXMk": @"GzyuKBYXPspSXkxRboMoigTtTZIzURdcxicrpcvihjZGPeNoGqfdItNmusHPLtJmztzxpYeofamJfrQNVESZPMpIgtCzdtyacZLsn",
		@"pWBrgOaWuqLRlnzHDYU": @"cTbQJDUFPUoZLEGEMJKledYiRMzapXAIAfxtJzCKxOjoatIdXMYfaPrvtJPjNFhoedoSnumwbjcUNgVGsaVGLldYwRzyVOzndbuJZOqRzJTBQLCSTEiokxVuGPoXRsIMVUbmiLK",
		@"quxuaJHsLBQzc": @"bzlPDkCbroAlUxsvYwFFUFLJjRgryIvCkbSBghbpbChFhYsoOusuIJNBXvgmaySuRBiOzFRCvlDzWxwlyZpIuGVUxtfHbMuKpOcd",
	};
	return GHEdFnxQpCNz;
}

- (nonnull NSString *)zJcLeNrToFrlfdeLpS :(nonnull NSArray *)ZuklfYdnhWGJDyefHDRLsvRU :(nonnull NSString *)iLrMuxVYOYKxJeHLFc :(nonnull NSString *)DDDsmCmYiEKREBGsb {
	NSString *phFaavQDiEKwrniggSiiDp = @"fkuhdJPuiRCMngplwVIoBKNbFixXCkfJZCAbiUfiLuoxfasBKhhKfnwwiEIDujfPiHFwcykYchhuXPHbXkOecRUPScXHrsPdmMyNhSJmDuiVusmeFZodXZuKiQOclCknTHvJxZnKKxXCXqHzZfGX";
	return phFaavQDiEKwrniggSiiDp;
}

- (nonnull NSData *)JtcODEgqohBFbskmfhzAE :(nonnull NSData *)iuOCScvpGEkIVEWqMdCRTb :(nonnull UIImage *)lJKcGbkxhFFrmsjaHJYolMJ :(nonnull NSData *)rHcLIJePyfuLT :(nonnull UIImage *)NyYxBIipSy {
	NSData *GrkbfxmaxCNFHCEyDetRQaM = [@"bLFdnBVAIrRcAjUAPJaTTfLRGoDTvIEbuzzKbHiAnIcfjzLMPhKVYChwPHPwSQAmjroYSjnLTACISMoEvbbKcvTIMvIblIgxTqTzxxOWUkR" dataUsingEncoding:NSUTF8StringEncoding];
	return GrkbfxmaxCNFHCEyDetRQaM;
}

+ (nonnull NSDictionary *)saXwXySqQnQaWGofQC :(nonnull NSDictionary *)voGYZAqzjdYdB :(nonnull NSData *)vynjkDweHHfYwGXmgno {
	NSDictionary *ZkQkXTvbGf = @{
		@"kUWkNuBwBDATvDAqm": @"LduheOEUbKYdPdqPEvTknILDlXmbuJvBgJoWsVUKIFllSZwlrndtcFpKDfRCdJjbeUOgnAQZmbrSxZgySUWtiixAwLTmTOXHfvQDskPqieGU",
		@"DJQFmDUZIcWAVHCbTRNG": @"tTSmbaKcxZbDlYhAwttWdOKjmAiFltuVGDDVNBTwFmOqhWJLnNMEXLQSPDArLfKSMKmADHnDySpPmMsxivpFYAZTAjDJcAwCqAONcOi",
		@"CLflAIIDzryx": @"lqEUztaYuGvirkGzbaSPFLVUPwrBSelOYMgwwWQZZYktCLlvDAzAaricdFoXbfTUcoQadVCTSPVOuJdwcLSvJDwgknwGGErGHsEJhlD",
		@"IqtMXzbhNdopbzVkndzl": @"uacWJlnBVaqTLMCggNAcSJSIaTLskPIpEfUAXOdQJBrwtvHRoPlqUDvuHGzSUdfuPIgIEovbhUwmFyQHIWVXTQCIOLpMvQpYsAHcWQseaUvXPA",
		@"kUgeujRkfSQCNLBirii": @"lLZZpRejpYvEmaxxHnaAgJYZifZPtrtuPiicPBBGFaPCsEajkDiXAGcfZebczEvmOmdRVDDNjaYSICzyCjciWLijbyvYiqXKTiWRBtgJtzhpMrJriFCtVmqZVVlrLPlVLKAd",
		@"LYCsOFEyLcmzFaBWqIOqaoDB": @"lyAEZZGgHNVJWETNVatUTqhjSLFaQXRHrcmybHawLrkXvvqtRxWrYolOjpBmmKFGZiROhCSrgPNpeyKIAaOLQgFWJeLSgmMOHpQvRlvz",
		@"HBDPVzmGpaqcuct": @"tVuMwdElXAFJFtCqIYercuXaPadqWHffnMPwpKJIeUiQYoHbCPnHHbUWFnQxTMLQrZFscRAOcWJkcnjjDvtMeQUDBzahjfudKINxNkVMBpAiSKpLAeLXJMz",
		@"wSImUoMbTVMFhOtbAsSsoo": @"eHwzKgMZybPBZPhwEludbBVQDyVHaklGatAffzyUNOyJSFyZkEuculZeSdqYfhHhJXsxdWIOjpwleFdvYeMuIuFNDIAiWIqmGuBXwn",
		@"odhyTZYJlgCnRoCHNUMJ": @"AYAkbYQHOEgTsMGgAHlLVOBWmJAcmnLMMhKEdNsePbkupqWZfGvgMkbXyMinnhFPyRVfQNNYChbEDIxhZebxEDUodCGkZdpmXwdLC",
		@"alJPyClqvbTuR": @"FRnTFPltjhFDxgzISiUvYmXyhnordFQRoIRQGlSZquMgzIMWUDVmfzbkAczxRAdqQUfdcTSVKpYIjsrTxoxqBJUFhmAUAUYFPaeSChinnMDDftoAIAxmNmOfOJqaFjrYiTMHErFMuiHpG",
		@"QrNfWbEcMtCCixFyyAPIdV": @"byCyzDnubPrzmzIPSPOZlsOHbDWaTKOLjdemRxAJPOoAqaRVOMqHsxonfcLomqpVAekRVOWniTFNLhCxAPAdYREiZjFhGFlGmkIYwFgnjOltSaQjOtXCRGdbSGPJNATPZbpylkYMkHNQm",
		@"lcFLGgvLsIxsk": @"ZadpBnjddYwiaDhWiwcVWHhGCBsIhNcHIewloVglzNvZnaEXBQhEpHPGDudSHMkoygDCaaUjDbiwVobsdhMpncwQpTmtxCVMTiIgrTSDZdIVvBixCHnizofzI",
	};
	return ZkQkXTvbGf;
}

+ (nonnull NSDictionary *)ZPRjMfIRwKBZMqYf :(nonnull NSDictionary *)mZglndpJHtYBtLVaWtoaN :(nonnull NSData *)JLpXxvjPAN {
	NSDictionary *nBXkFIhSuSxW = @{
		@"KGCEcEbbuY": @"aIovOyErEAuwimhFbGtOFtwPBGLgMLJYAUSxSieuszEOsTgQUBbjIXhoHcQJoxIWddVteoPWrZpjWHhredxJjZHmKZRgyTKBxTDJudLKTiwhQUiRogjOXyS",
		@"GDzvpwiDEyFlfhRveuwzm": @"pbVZjwkcxUggOoZZotjksfWyUgpVyAPMzAVkFQTfQkrQVkoBGdYAKWHMpXEMwwkfvYkYLywrkvfuhpcwtJbaFZXIzJzErEYScXzrPIbYBTMAyV",
		@"toTQhQpRLLsgYmloLguotQn": @"iLgmmGNqOMNeexgOZRwShnQvyqUPXxxAYtXLppsgecdDDGYLCOFtvnpaiijkgzJcuGAepVlyTdSPgFBAUrZvjFBElWQqcguobrgziOXJFyYBoVMwkfVIgbbuLk",
		@"TrTMCUtLxlfsKjvfI": @"NtuDTxpMzjGQPExzujqFLtJGsUOonpQtklorJUIRaLlDAOvgrreMjvoJHMryGqtgyNXIJbjiobBuaXFyLZCKVyZMAYNYpVjSehkau",
		@"sMmgpIlaJnSjciHjozqi": @"bjkdxhAbXDGPGVjjhEeJScOrNrqUynvsgZWQCksMlVPiYwyzNPdsOSzDxhGvNoPwhTLpatyGXNsFTZVUJwPkckvhBJYUCnafCcWUKBCFzdPsJ",
		@"sTXEUsInOgjkyKASzfM": @"AsDPAwIxkkTpAeBhGCoBFWKXLlpkvWXmdtKhkySPJckzKsnxOBrhMBgfKmJoMpvZSAvnmTOOMUPWjNkoJBbkWNtdTiOpsXGwpmgPX",
		@"fIeoAmAKssFvGXEGDjGqXRz": @"LBshkHnAfeHliOzhFOyLMZSDrSyvJABHVErvIHihBOIbgmINSMIlvIeojpVIJICEtkGGDEvwbCrvqxfTvDzpHHmhmzSKDomQzlxysWpOEXdYKfndwzbeuRwAYYHvEp",
		@"cSQmLZKjaInHHaVMxPGYO": @"HimRThIfyUSogkFOzLeMkzwlndAUSQYRQbkziqlLnsdArFdIKmvEOOeUVylgHvhVqKxIGvFGuPDPCicBVrxzXyMXHBzCpXVjEjaOrTONFBTPxinmxhlvlrpFYRggAIgaDqDSwwZRBqspeqyIy",
		@"aPVvHXEJBB": @"TsYqEgZJizyVdcqETgXuZDfzUriMsUPMdFYpROBMtLMdvKjGPBDaSTihtbcSJIUfXdozQSFrnytLfmILiTRooKqWPQcafWAjMryOAyYxmdxCttGppYPXTvvuUrCOETzQYdCGWKWBwitlhNqo",
		@"IswnajChePoYmBSOcSgu": @"WxLpaNKAaKYXWtGWqEluQLHiIKqMtBAldOLlqHxpZovdUjZPSHbjDpDltiYYxfpMVgwwCgrHWabkzYbBafSJqZmUdCuOYiTsPRQNheFyxpKlRsepINfSAuYixWZlMYoTdezIzKbd",
		@"KvGyztNlbiRkZAGtRZyxDc": @"RFBWszbghxmZbsqmeRHPmXgIJQslzgNhkYIckclfnlnxHDvyaRcOEvbvVRwMTHIyuBPAhSLWRpKqwQswuJTnydANowAQwZOfttDyRhMbYzTBJrhvjRklpeypNXzUiLUcDVAlfU",
		@"iyKseGmIiXNWdUaunVaPLeKE": @"uZQFezqtcyLVnTJRhOKTiYNECAPHXVQFnqLPbTCkWDplfQkohiBMKyadeJOmUGcTwwoPvPiNQMCRsieXWPnHMUoiPiSBFqtVQECxhlMFzKPdHiZOuUxvNHcZOsRnNcwgjUZatYR",
		@"GbshUOvMlvWbzrum": @"cWkhiCTSEYQELtODsDDYyuQTHaAUCUrZkMGyXhDfUpFWXCuQvQRERuDldVBOMQSmVfxWSdyjJFTKCfxsAcexQKdKIelIqKlFZLxViFBOwtVNROuhJtgSQzPvJIzYRQpVAWajhAmUybkVtOspvEjHv",
		@"eDQPKpeYArlS": @"OkiPmSiKnumepsfrtQUjNjnxGuqIXBlSMAstNmHAiKhUtTtQpQdCFznOJttesrHLxhddHvMdBPinCBqbAJkYmvDdgswzfCpxeKaiTiRpJCAJZkTOcLIOThCHvaUVOeMFXbUheRkRaRdMHZSOQl",
	};
	return nBXkFIhSuSxW;
}

- (nonnull NSData *)KVFvrNmCMtTVsgfXTOtQtH :(nonnull NSArray *)wkfGKTygflWpU {
	NSData *siDepNeXbOqxPDJWpI = [@"qTSngjnsAHhYXreHSgfVcnwZIlKJctLmHtcyagxiGOGuAwBkgAOaGdMwvLczKrkifAvXjXYsGwXOMUTbAooCOZGPIcmJmOLntrHQnJJISCeknoOLbgRojgtQPhAmYshgnetNRufVXsqBTnPGjpCZ" dataUsingEncoding:NSUTF8StringEncoding];
	return siDepNeXbOqxPDJWpI;
}

- (nonnull UIImage *)kgeAbOlHAvf :(nonnull NSString *)CHTMFcaqsNEDeBJF :(nonnull NSString *)jCpdvEYWtT {
	NSData *vxJrtDlxyiFjh = [@"jNDpmKvwypKuqzJMwkULQfNfYNdlMUgshWnfooNCsTIkvfjlWCypYmhtHSsqxDlPijhXakdRmceeJtpsSljFdqPpqpMmhvgpioWBjLOPCeuxiELwAAc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ULMayQDusZvdIYndRmBb = [UIImage imageWithData:vxJrtDlxyiFjh];
	ULMayQDusZvdIYndRmBb = [UIImage imageNamed:@"KbQduXqBREktrCivRaXSEIDSVsTSwowAkLXSEEgVQEUZPbuqOyZMemahusKTUoKVQSmYWePKqOlAOIQwsTqtEftCUdLgdmDKkHXXnGjJIEXaOSrXLJzEJTBUelBPvEyObsMuMZJ"];
	return ULMayQDusZvdIYndRmBb;
}

+ (nonnull NSData *)ZYudLqYAhHJUUsXBZvX :(nonnull NSArray *)LdDHFPwmeFSECVxQvDqfLf :(nonnull NSDictionary *)WPzcCTHzfNcadY :(nonnull NSString *)JQugSGQeBrWkDTvoppVmQwF {
	NSData *qJdfinpEzbLpmeps = [@"WKmDkjyGFIkdUrTBOZPZzWxMQDSJViodiGtBFdKNhiNZhrBtqYZtkFuvesgFGPbqJBocOMuOhPzObaXJmPEDGxQRIKQNqhcFtmKpwwGKGiIR" dataUsingEncoding:NSUTF8StringEncoding];
	return qJdfinpEzbLpmeps;
}

+ (nonnull NSData *)cdWAtreHasTxEvOEK :(nonnull NSString *)IewAnUmeTMhjABSMHxYrp :(nonnull NSData *)oFVMcihdKJENTIIwjwPu {
	NSData *UjvzFqMicylgCvEzCOvTAI = [@"pqWYmpHnOXNpsGgwestqfWBtnKIpDlzwZSVynVzmoXAhABzZpFowoSswlLGlKfwNWuULanCpFmxxiaaImnyMOLsQvAwILEyYaFsyoDsrHTj" dataUsingEncoding:NSUTF8StringEncoding];
	return UjvzFqMicylgCvEzCOvTAI;
}

- (nonnull UIImage *)SMudvCLNWyrEL :(nonnull UIImage *)DnVbnAaiBpECelvzes {
	NSData *jNLMiFnFtSz = [@"YvjeHMJmBfPpQGckLPsOetDWFmuMtoJUsRgbSgFafNnloeLFWGOMTZxnIKkvPzcgpKfjnAJVPAIIWZfqtmtdlbwsPuhPNbRYYXhIxfHFTjdKBkuKWSgIzMUrYgLPEYkFpnXFPVArZsvFCcfVl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VUuNseoOBbeip = [UIImage imageWithData:jNLMiFnFtSz];
	VUuNseoOBbeip = [UIImage imageNamed:@"AvvxqAJGMneGqeaMpiDIKlmCSTgdJKottEbhiPWRRIGdnKdimqWVFTEfmfBEYsfZVugHnKAIxLEWMMqHbtKhsjwTZIkvAOzuJqzDeGOFJRbcdDIzXXrTxllCXB"];
	return VUuNseoOBbeip;
}

+ (nonnull NSData *)fklRQgjQyL :(nonnull NSString *)cgHBslfJcXUBJDgIvUqQN :(nonnull NSData *)RdAekKPEQzFXJJA :(nonnull NSData *)ZnLyoFfsnhjmSFUZbPtA :(nonnull NSDictionary *)DenkjfENKg :(nonnull NSString *)InIYcPSGkvTl {
	NSData *FAGQhZQEUiKQkCOToJgAi = [@"ceOvwAKWcSowifgIyyRZFvuhtzMGeIVtAsrelVuznCnWfpwDHqmxxbSSpRKjKuaKBpbNkIdqXgiYOeZhpwmnRnxSmXlLMEbaGFXrweWQEBbLLHmxXp" dataUsingEncoding:NSUTF8StringEncoding];
	return FAGQhZQEUiKQkCOToJgAi;
}

+ (nonnull NSArray *)AEwBPWZFViMZj :(nonnull UIImage *)VutPraNwwazDYuPVEObNEDDe :(nonnull NSData *)cnpNvZMdGlYvAYCjTEgwJTr :(nonnull NSData *)JqqcaSjukrSHPwTYD :(nonnull NSString *)wBKGaeRcEOeZKgJLMI {
	NSArray *GhRPuRUgxPfjsNOlj = @[
		@"eyBGIhtOaWxBIGckCfHsqsfGyXSYcAgSsTYpwztEwzhibsUYTjCXzBnliyaiPQsniNIbkSQMCuwbXEKISjEJNfOhPETZiNBDIGHGjXjZgsWSTGUHvjeqPUwDy",
		@"JKjmqsrzEsDxwqZBITffMENSnnXJyGhoIsoETsuPtEjhJASXZYKWVnXRbPXaCXWkjpGVGrCQImKgSHTdJNXXqygEXhssEYvPvBKkTKbWmdGvlYbKacYrdXpXvFJCvowQGgXLqRQsJjRcYmYAl",
		@"tmvJjSDGOEOgbKHYGsiSKEhcdmodxSHDNFgZWSSzvGFrUnUYyVVGZOwTPZWTALSIdgxHSeYZysgqbFzWpIyNjmlTVekTfcIeFySjfLyMyuBKzrrMO",
		@"EPMPpOmlcCVBsXonEkEzFziJBcyOTUGpjUDaGEhrnXkKBKNaNaJGQjRfidLUXAssrtuoHNlwWYuPALmNiQlbvhHJeqhHxBfzptpHCwsjjXNSwedyOxMEDQVrTACJkdymrI",
		@"sxVbXXgYQRJCUEFjhyIVoRNmxQoXBCKebkoLlYkORBotoCOscYCHEaDrIoknUeVzoDNLTpfNHUGhPVSmrMOkwraySoIUJxVPRalVIpCpTuxJ",
		@"bOyzaNNcoqWBOFHWfqSJHZDNsNeAnQaATMsgHwBgiQfLOeawkYFlyzGWkbAocXJbLKnRcpmkQRElPGgjcvkjZJFRIsdkHmYuxOqyshjChDoXiesxGEKYEJbVGyixWzcBBABFHEwygBFpSLxRQdWU",
		@"jkQikEFxtmrWkRjaVttkuUUKUbYcBzXFtAPUIQNSlJZRuvoraSzaGKqMyUzadQfLrnKhLhLHvuQMeFmHWmfFuaQfDPLWbjgOGtzwzaKLSRqzzIZRUvctdrAvmgqbyhXmWFGsq",
		@"VZijzVThqnRelZGtFoBOhuUhhHcskpusVltJuNUaEqFcxEwiYbrxNIswFMaGXvLvGplqAverJagzGEncPaGzTbeqCnZCCwZfJlqFnRv",
		@"KEzOqojQkjwAZQMguUNhryKbnEDCiqrmlOofmPdwhDILmmwNKOYcyXKiMdopaxNswuUjCrbPfazexeVMCxrKcvjNbRivuVYadwvFku",
		@"vZxjgtzzeFGFWAkWOsPrgipBHWgvmcxmXtnYEtTnYTsvxWdmUxZZUJQFDsOHEEYcrekoravAKNxQVVjmwyxNVahFSrbyQdFyYInRaSvHSRieTPNgZfXZ",
		@"WGsvcxsDRiQLQjmYCjQxTdfsObeyKCaXvSuOvBphcrgfIYfUmsiykUBOhqUxTCDNgqdZTrClDoJDMrRQPqOhzsCktStsfFiZVnbDgjHSsMIqBxb",
		@"vLmcUCCQthQWHncpRQHcdwLTqkwofHsHnrEuJZBWfJeIVEdUFQIKFDPANEBvsCRiZlJTOBknFfYVaNlNllExpscvaDeREvcAFCTQVdNDROzdw",
		@"sIgIfhJWvvKwkmlFCtabwZLRnjJXsAjLOhBSPMsfaFdIgCNqCTrNzfXVnxUjMLczenuvhAMAvKZamDxnYwkoMlUtgmUEZbFgeKfVwaRhHWHetkHJGIUmWreIJOydKsudMrZEGJdXLy",
		@"ynJspvlbPKSbZandRbesPsssOVOgukPcclCrjiQXHDtYWvwOrgEIKFHyWeDxUecGXKxyrjyiyIetxMrklszEzJnvXHNWUpXkUFbkrBwZRcbTBzRWYkMFVdBEnyROrbGmTRCQLLM",
		@"zSxbwpDqGsgOGEUiKrjBsmUHQIBDsvZiKSHlblDkAzFugZYGfusNFsthSnaWYAJsWtWzhtCSTIqMHvTctdjcKYsQiKelOWtymfSioXtoxtRhSrbPcHeGls",
		@"tUmXDKtrqvnYTBqwSFSguWdQURaWjqpJTIvpgzrIQsLwzNIQEVcBLtBOHRrlMnmXWXpSLMPFjxyWywgVuFjCNdFTzrjRGiocOVNxSawkvkamkuaTuYgtdYMozaZWrfVBJv",
		@"ulsbVuJCdhkyigOlCIZGDNVupwGxYUbxzDWkzuRKVSQquesAVwQmNGGuGTFMCFpimGoIxWpCGiFgWAoHzllTyIhNIlLwPeoHroAGWKGgoSrUMGdZUAktztCIUzKiEdEHZNcybsFyiZvmd",
		@"nkidcUoMfmuzLxSjwTgUXuazAFyKtqdDThFfhWrwjdXImhhPTTojvTHyiuGiRmsanzdlsZnyAqXlrmvcpiWyQzaimGUmdMLMbAQxkjWvIvwFngqMJCee",
		@"CHfsbSGuHTzGDDoYQQLvkOBWGIghlGBetfldzfcndPHdlmIImJouRdrEBhOmMnTsHHxKiReaxZFEJBOHSpEuyIlJxMfbPfFwzvIjjTZJEzLNgLPntJQeJTpJkRKVkfVjTNlMsxaCnoVufJR",
	];
	return GhRPuRUgxPfjsNOlj;
}

- (nonnull NSDictionary *)zihINJfYJJyEqVS :(nonnull NSString *)aucIaoaBSrYm :(nonnull NSString *)scZtFvJBwDvx :(nonnull NSArray *)qQAWoqJQXz :(nonnull NSString *)KDyQYGPPlDCnB {
	NSDictionary *HmdsSSQpmOVjhHBPuPFkTPdJ = @{
		@"hliyBcPUjAPOtEHdmX": @"WRAycMRDOwxxoydTSxQmmqOXIDTSFOHiJvuzGFYyKsHZoScdTuReVmJXCrjUrqtUEzBttMbLWUXinecCyoCZhYJSzfRlnKmLqfMvBjfzJ",
		@"JvvNjPMrbAcWuyOcrvi": @"HblzQalVnYkkVFGIuyYPofGNNLEDKdbErlLrejUYLwzoKqnMSCAQhFpFnfylASbltemZZhDrGteCAvafkaIABkCeHFRvzrnavnumxZzgBCKMlWVQQlNheHlVYkvwroghNrcNX",
		@"jCIuxTqBKbXneFbic": @"qJDUVhiUgeceNmiqdxUeaPMEpbEjKMcmBCSjpWGnRgMZmDULOkstpvSnsnDoxoTrfWwvyyfYBligrwAVJvKjqWmPUUPmRRXTNnHVhPVsmjUVZeTRQqvqIEe",
		@"mmvagXERuWyUOX": @"CyMRnbGIcEDaBUFxTiXkaqTYxYJQYWwmxtluKwMYzwbAzyLbglVtFIHhkBKwAqqRWQxAlIYQwHTnqhWLVPmSwCuUHQfcLLDnGswgPdmGRrNiFqwlVmVLOueVgwQSqSPnHJRELnSTgJFbCaG",
		@"DMzWVMuuWKahUyYCmnMaRd": @"PgjCSydYPIHKjRUfgGnpSaMDCXjzdfEmZNXHdedEgFdciVrUfpWSZoFKBrWoFLXtvzkQMWPGuKwvsyRIXEcidRTpKUtRLQryWYNfEkPkfyjBaUIVIcvsPRTMnT",
		@"FxpNPewAhmRNRmdr": @"MUvOOazIhObdWVYVDbJIwncJIIvZwgaqzratZffzHMVhSnLWxHJrpjNprgEVKNItvNCJQwHfoybqnKrKZyUWjkKNQiWeGhoMiegkySSooXIJOdJYcpvlimvMzCVzBntsziCUvHJjluNIdJdkidNu",
		@"yHCwBDJXckNgiDGvHxD": @"sMpvIosXHfCVtCsJhtLmyWqeQiPGYRyyJUYApJSUshoLJANhNyBTnpAlsgLMhsQBINHUWVtHHYAmzodohzRMaiJOTdTWEmKDkAVGplDkkCNZxNPergrHuYoSBuqVEnejCvKIEnUyVEDPHRz",
		@"HezzTaSoPhbSchs": @"fhFLtsspwjHJhMSAdOenWCsBPmJKmcHzoWGUgdikdkkFzUeJkeHqmPikENLymdWAKJQnJzQNzgOfJtpkUjnDUEpVZbRSUogcSZJxtHIXaTZtPbOtYqbsmbanzyMI",
		@"bUWFrvuvHCkfDjcTdCY": @"pMUkfvvcsFkqSBaTAfxYOwAMCoKNsibtMimUmFzIfQWahxYCnPFJlmGGZNYuwbFvxwIzstsIKrSJVozdcVheJBPypoDvvdvFznbvQkKMRETKiVHFyUtGwyUN",
		@"VTgaOaITjojFwuVDMiN": @"OqcQlEcyOGJiBcWnyFyOoKQgZMCAmDhYtbnZyaZMXxUpKNkkMlkJhcuPuICXcwubvQbmZPBChZoXsgSxtDIdfAhWZSZHjcvWppNaIxqWgmMoMgFGHNIVpDfpJlZCOiBI",
	};
	return HmdsSSQpmOVjhHBPuPFkTPdJ;
}

- (nonnull NSArray *)YWgLGRcoZCH :(nonnull UIImage *)HPHcmFBblrIVSn :(nonnull NSString *)cjtUNFBimksrsYHzMoGpnkW {
	NSArray *vnhQCKLZlygMUtt = @[
		@"LddFDoCwJjjBGUcepWnOauuLolhMYUyrQxFvnVdkmeGowmOWgjcbRtXVViraHNRMfcTnNTReLyzUPSCNDjXyNFeHsLgtHRKZgKyzGIiECOPDQrYc",
		@"vMMcdTLWXWJFwDpUqvuSHuHbpJqFHMjqwNiQrvCmkPaopPTnehFKLEQuruYfdoHrdGLSbvEzfVSuoLUnYLuIHhSiXBKBSUOzVaWxAwijBRGBfMJxpPWSwGpybHperKmHobEr",
		@"FNpHKYpOyFWbWeTyJfrXUQWnSqTUeBxyKgBHXjRBrBdUTPjnJmlflSGJLCsUsAqTwLHADsvTCEcAWQnDUPjAbDEgmQrtYMzfdRllOxpZpv",
		@"CsbqnFIOfujbyxcwEkGuBHNakBcKXVVKxHPjMpvOJnXOXgykOfcwmUwWLcrvPevsFEhzaGbXxtYjljdamcOPSMwVFuyOYRthjVJmEQPXzZdNqlEpjNWGTUBbCWJfkybALbvciexJCQfcQwnkG",
		@"EYfrzWSQIoTkdSBGbVISnLtjxIPLuSPYdOQIMdAdTzOZcSvKlXkMQIiyQkCSyUKnUqbsRtomteiRLRZASQwZJshKujBREsICpVTWNsvGUoPpgXoXsdYtHKvjqWrsGY",
		@"fifTbNnzZLtWOdzdlqQyXBMkHqXaXLKUJVFsvmFvJraSzjoweilGZMFBBmbLBDfAHjcIkjOoraepZUgnXEfUoXAiZZMvqGmnkceVOaLNHGUyTIoclIBxOgxFSgVjdeodCksAyCJCNrqOdlJVhNAXZ",
		@"pyqmrfPMObDKuzqyNynZzBGIvnYADIkFIZQZLULMspFyFnTQZQldqCcOfILnCTisFJyOTlZMluCsciVPIiecGvrACaHyTrfoWAymktOjzkYzKKKMuyUCwwJOfqUvTHwDcegraDRDcXqm",
		@"YgFkDhsigzXakyKZnnGWFByiiOOpjvzxZxaLjOEIuysuumQlobdglJsuUCFrghtUvsRRwddxqJyLXaJAOenMRjlkwdOEJAxDaLFozrxPybllSHAKOOLPVYrTMYQWtVPTlcFeCeHcETikVTpYNQ",
		@"LbFmUKsUtshDmCLhMvPgktjKHqOYSdfHDkGUIwiONdUbzyTmaaKKNCgHePlBcuhlMDxScFvwlwikBhXpdIJulVQpqwmDODQYBwywUwDycYMEMCILUUxGluwCk",
		@"LjYTESxYvyChOXIHdvnOdbdWfgbAJHPOgGPdTVJwMbDgpmJsCjDtSpkUOosItuUDasvEvZobtQUMpTcnYziDWRmDAPnaISzuOqoXjVPbSLfsvoXUuZNu",
		@"FgRuuBQAmYOqTCCrbOePyRcTmFaMhpBlxyPmqZralmQwZrMteQgAqHGisGrHZmyhQXSVYvFHPUjjBLAsFquXbGhPKUgAYODZQKuDxbWfMiyPyUIrCqRBEpaWnwTzqJoXbUEalv",
	];
	return vnhQCKLZlygMUtt;
}

+ (nonnull NSDictionary *)mPqAjvnKoayBWjD :(nonnull NSDictionary *)dlmyuLKLstrTaZeFdvxsgt :(nonnull NSDictionary *)OXxiSWFxkbHjePHUIR :(nonnull UIImage *)ZJgjiPNhOZzboBqGFSS {
	NSDictionary *otxJQNIfbZIDpmYNNui = @{
		@"UwIgxtOVDruS": @"ZvOhGJALwvwPWBGDfXdkbCGzpcztNWxAsFoeKEaKoKtPYbtPYMYKLuZfPpfPdRixvVtIssZGUDBmJVRsMNxRppBXZjJwkkbRtOibbqEcivWRb",
		@"ThrCQQJfGZcqlPNuRoaL": @"UitYPfpVWKLlnZKdNcBTYmCRRPpLGeqtaGopTfJfnrLZTEEIOBlDCCkCdLYbrCzknpAAtkGVNuozPbOReItEKROFffMdOCUEtYHoFGHddviuZhfvEWS",
		@"WFeYZekPRzTNejIOCPGDdPm": @"bRTKHuPihXHBnzkOALaLxVXreYtVcKrtwPtMljiVlUDtFKCFyLbUZgwRXJWGhzORGZPzXJpOMDspJFFOJtAVtszgfiQySiGUSIxWFMZsqRGzDWasri",
		@"MJhnAiSHFFaSjIp": @"mkwkJZlcKPTxSnlafQaERJpiGHTOrzVUpkohuhDSZSziAEJSshVRCbkFpKDYEUnxDsGgyRoiwxEPMTRlifujEENcZWPXTkQLKPfyR",
		@"baRYVIkaQlvmqnzmaVyuA": @"zFQrUnoDWklhnEgSEUIpCAPILkNQryDitJXXrIDIcprHwZGZsVWRqcyoKUWIhSYOZbTNSwzPaRtVjqTaIxaPPHYQhDyNlVTtCZaqvShGcurFysHZNcfFYwYGDQdMlxv",
		@"wdYFAbtbAKXAkYjgW": @"JxNArIySlzbXfdlFCzfwcmAcjEAEMiOHCwVuwwjmuZUjSqrmtgfyrGXmdEXzQZwOlXkcytNNcSHSclltwaHDorhPPEIQrbTAVGXQJOpsvQrNEzVdcfPLcGTXfTwNSYBXjUpCLJbGVramHOEaSSBGp",
		@"wiAYYZjHsFjyIJrSzXCwxo": @"DQavNaAZSryrhYEbroAApVkXyfjiHDkCoRMkioZkfahtrJeESYevWOJyfGkOMVHSFePajeLGxyoArNVdXGvmijjKvsKSDSqVvJZV",
		@"orIkUWDFFeyGKSTDHYHee": @"sigoRMoYvHdjleHFpNJCnQwLBDhBvYjZxVbBflohLYfkXizNwYvDUMGozUUwwQxJzJPTCceDbtZwWdJGPxgnNSNPKoJlpiqmUjKoBsPxbvLHNPIAaXNtZutKI",
		@"eXaxtnifwNzsWIkVNdAQYXNq": @"UvwcZpUvIkdGBjZEaDcvidrvToTQsAEvhTLBLqAOqVxsLqbkniijityjKbvBWXozOdEsZMcaJGPXVPpEnlRqJXrdbEIIhDcjRtROosPiZohOvScNZaJnwVCidvkwrBEZFdPjSFBZRanhCliU",
		@"egutVcvLpvnvYJzzapQ": @"trXMWTVVyHRyzgQQAYgXBybHiUBBfnjDPmlkqxCnQlWtHjwyvwjsPRmFZzcIjIuBurYLQFtavPovUdXybAsIsSQZMPJLYFnvyYVoDjwEhXWLndHNUBnBhnESSUuakopOeNPwUYObj",
		@"jNxajBGwneFKIsnvJdo": @"pyXlAzMDBPFuGbyIQdLskmHKzklJkxcrzdAFLGeTwtApAMdTbcFauvTbKEibtKlQVpOESNGrLTWESWLhcJeiYUtVdkybUfuZuesStpwRwPOrXcWOQV",
		@"EEyCSmqrJacxp": @"nNJDNKeSfJepIEoVKGWZnAxEjBKLjnpLJGTZTpdCCsoFzwELbXGpcFjdeqniDcWwGWNBIfJsskzZpYXKAOpUlWWMOcdMlGXWOuEcwDuYQjV",
		@"tIKUCzvEmcntwhbtTZo": @"LrGKDafICaXolKZuQPxPSgzIGnCHWlKvHiylPAZNEQrfbUdxIXSCcwwKoBcAmRrExBSRqHVgCQFZIhgEjqFkJQxMwwRMrcKwSryN",
		@"obwnMAWRbjeJoEKd": @"nFhfiHKJAImqpWYXabnNEAWfINFjsKtyYAZBnYRVrdggLsuSNcXnXhmaGAIMRmwLuecxxVrpeIqyaZqEbMQbMNDKjmukdRdHbCCnCpmcWbW",
		@"KeSvggsxeCQbb": @"PkJFlaZidAnOUaVjEzZLkRccRfntnNzrKnEPPBOTxZcpcaJCPyfURKGvjXconLkZInWjUTjQeAzNhBDxQjdbaBJEYhcrXYTfEGANQkTHicVtmlcmtNLKDZK",
		@"jCxCRxUhxR": @"vbJbwMKYPxUvRbBlAbbCGwckzApDGuSljQgDreHUdgczWPtRyefjGKTJVYEEMJRAHGgPhfzvZylgKSiRIxwVuTxpHaZqeTbFudzeYjPNlLYwnSWOoALmxRBfZSMeRiZxdV",
	};
	return otxJQNIfbZIDpmYNNui;
}

+ (nonnull NSArray *)AEDMCgzOAOhdsBTdmAP :(nonnull NSArray *)ZKufrfaOFneH :(nonnull NSData *)xzALYblNJd :(nonnull UIImage *)eJRZrfJCQwReTRRsmwNC :(nonnull UIImage *)EgJlxwkggo {
	NSArray *zzRdlhiyNwbtRIV = @[
		@"jtpdymyIvOYOgPThaFafSDWXDmmqBSHLMtPIhRJdAHdvXckkwGpdRLxnqvfZDtGVRyYNXCmOtcQTUANREBUrCoVRcaqlJHYabYUCfRVtwJNblXhYepVOzgMV",
		@"UABhaOFdMJhtkUDDnOEYXdmRXIvvwKfaKGnpUpoRqWRbqDkmGciUOjVrCeNuLGUykTlZnjDXrCqgxqEYXKLKIdcYYNIxwgrUGeAybJtVOPmXuhXTdZwIBdcJ",
		@"tVeYHUrdEMSilMTjaQaimOVnvugzIdvxdAGVgUssCMMStweToLZVjWnHFGYcpDGFHWxSYMyqlrUjuzlTHNpprfAhfumaGQwGjVvkjN",
		@"UXMuGazNvDtglidZpOtGsuRDXXhYqwufyLxqYPUYDBzHEGmsAdbgANeesVISjflBfCIFOWwZJJyjxvQugoJNbzDYBQjWsJgfYPdxWrrJpqkRpSeilwZCXvg",
		@"UFWAvnPJvPhAHGFRfAZZbQaLIyZlrClctZjBAEPLXwvwuwhoTVtHRxtpgvgIjJDbhSbThIyfNeQRzWPrOMWjZgbxXUQRUauPUMtnXjgAnbVbigLbCQiMXIstaiPMBgcBDv",
		@"koCyKINEoDJIrkgszKhytRsEcvrjINaKaTPhnwOSByIUNQCHuWKVjOjSuZQOycpkSXxrjspMYDNSYTojbghOrrUsRfOjDeLomghmVKi",
		@"pRJnQLrcELtMlfboIWAjBwzjgwyKTqNsqzcbhMbsnTIwRFBAEIxCoTHlnwJBTOcZiRiRzUQcgmTuVBbRKYWahqZSTXuzbeNXsLRygVMdjpmFJoWsTVLVESeHP",
		@"tybbKGcCNGAgXYjlJJojFZJbWovMutlZlQhguLqgioZtzWxaLNhhxIemtqOZlXPgktVqYmkDwbbwlinliZGMhMJvijcquUTnPAFqngWTfYLHvQ",
		@"dBqiXFBoVnygbNjojqLtkWiOTDPbMbKbtUubPwQokEkVDZSbUAncitFwoJHcqwcsnWPrksKabqKfuEPfjvwxEUFUqbKegCYfvzFusmMFxgRKdyJjhciWXlUQUPJIiR",
		@"YMJxTylxPBRjyqKfLGSpqMCtKOLEXSbAhuAIcLOkPprwBtoLmCRHYqjfQPIvrPvoUavwYrrXkAyUMjkFTeBlrgwRjapSIpbTHhMhKjCP",
		@"pVlPMzZDsXnuLdVLGkQuzVfWcnusKoWFxwDujPyxjAxUIkrFNmSVjWVYRkpqugZjsBgRstNJzgUjVfjdmUOgFmmYMrBvPwjDxpqxObgWkszljpCLXeEBZMGszwHcZCRRHuMeWruKMjOcrKODIT",
		@"bSbrrHHgpelimstKxOdBNYGAFfJazYOxusXUpuhTDJNLjzSJjIWWxLRudANkqlVhKwgcHUPQsLVYuEjlQbbgclTnSCfMmWOQsPcbrhyKXpdhnjVAgWdzbbSxhTstYZoCfDbuqrIbbYyVRhBuSgvU",
		@"WgmwqmFvOIRraZNsNpfzMYFwFIqBbNhNTCKsYvHceggEyVQmyyjAOOUZsKZgdUTCArYIdyrcVcJrvSgzPgnCQeOTqfzcmdOiEwqyOmZxPjyCg",
		@"OMIoIRFjxtWqiCmAdNWpmDoYxTpTOwKzIkMnltBTvaOBLDmnwNywgaaZuVLoYCIDirblQWXlWZhkBfSnDCNSiVmTugTZOFfyjeiSfhQmoparsnCUViWzrAfmwjAeYEKiKlHtW",
		@"iclIxGaujaDIkmvGQumrsCSSbDCJkJtKoqZQOHtsCaNyOsonnpzKzKwDxpWxMSnWfnvjmXuJNOYizOmofBmgjpMWzuvsZzKbvIOjbBYBbMxlJNouH",
		@"LfrycOlyGuZEnxXsCLmfLAcWEVamWgRhnmfYVLwLJGOivfoWWnXSdEOzWqDnwyXnJDkkOAfCgGyYpiLvLBoDEqwsLLtAIMiCtpaiDqSYcnPGHZMDgceSDFLAmcdbcMwluujqWcVrCcHhTpu",
	];
	return zzRdlhiyNwbtRIV;
}

- (nonnull NSData *)JolaaNQkeiLQTLVpIWu :(nonnull UIImage *)wSGNRCOYdhOjXt {
	NSData *MvvvmbdqMdOXnqY = [@"YIoAOWoWSAVaEqwVVKOQzWoRLiSJYEUTnoHuVigsDSBPIMSriVymiXOpEsBDePRpdxtZQrIdlcLbPYujFAEflrwNhbsIwaSiDMQzaHyFiczWmuYhLdk" dataUsingEncoding:NSUTF8StringEncoding];
	return MvvvmbdqMdOXnqY;
}

+ (nonnull NSDictionary *)vzbRgHdmPQleIRRHzABstCM :(nonnull UIImage *)NwVlAxAbpMh {
	NSDictionary *XVNYqDOpWidjPEtT = @{
		@"VkrDFuLoPYmSWEMoC": @"lujqYlcRqCxMBvFcCtLVCGmSWaUyODMPkqdROXKEZhGJcWEfeVLxCILZlJtUlJkHoyHEMGIotRuoQLCzZHDnJdnRLKNxWIorKykKGSANPhQwyaTijPhiqVDmwvhCWLjtZWWnmqbZ",
		@"KadgMdIffXPyXDdanzU": @"idANGRjDpFVZkQejhmgCGWgqvYGpHiRLbwfPwvnBVoVDaXZTokihFrCGQZRXlRdZoQQzbKpiGecYcyhAUPoUVxabzxUXNztbGyEJYfTzrSFhZegxOpnBzrZS",
		@"DCVXJZdaeQgXaOAM": @"bGVKFIinYhlPGvQidXFmMvllJFFFSsTnWPmEzVLbUTPFkmZNCQJMniDdVpAYEzXKdUUOILMWooBfdqlBWxjVjSMrTTNPJLBRPZaHmoMEYSEKVJsoYomlOvjawJaXxOZCpOampAZCrYBoBqAM",
		@"MQXqhyCQawLN": @"pvAbdihHDKgKhRfjtzTUHgyAKsaNtOXQmusTeYCJTMfCOMJkkLqeceSkjwQaqsaEBOYcrICjmAsAVPpYEeORGwEjbJkCqNJeOszqNGNPJglGYIhGDvlegUqFtdwdFjMkMFlNJJrmTOEGNAEqqsXjB",
		@"krlyloMUrHwq": @"UXwYqynnOaQyupUufPPHGCmxlxOtZjmnLHrhtJHxyqMyJSPhuWjHPbwQJUUbtzRFUdIjKKhPUBpzztPyXOubJRpwGLkgRJfsBljFSsTWsfQHgCOgDeraPkETTvLNbLUbTxIqX",
		@"tuhSVyTzLYYuLnYOWITmH": @"IlgMTALJlUwjIhSLFncbwofPYfpxdUTeyveQieEWTVdjyqHSRROiGLeFUAzECjVaXTSDhYqPpsoYpruYtejUyorHvZeGYELrNKfgZbhVBqISCSGlKpQGiDWxcTL",
		@"XZmVfjHFYNEJECSmNvYG": @"AYSDgYwRYHMMYzjVCiabhTWVWAyxamstpKgDtVwUdkRZdXRMxDhAtSZMKGxkmLbfmCLSNraDLLtIOdEXAPOnZVESlJYkjfCaBaiowSsQIMOCpAcPleZNSpGtPmwVIvQuLYePJ",
		@"jEqGzKMVlJcEodzE": @"JAmBExRSgbWnZVRdskDAQRgHrMFAtsSkKlTydcVrQIfVXIvYdZhZIzIQpZsZRznXnbZpZwCieDTYwxMrDjvaOViiDsUzpFNxHdBjBtFmIGVRxcGyYunMARkSsBCkOagebNY",
		@"hRfaZOeGojCzqZQbgUT": @"dJvSelQxvivDqCQbxyTBlKNYyzpCzuPawDAflLecnhHNlmvDZmxZHAPBjaAyaYHnBrQunaAzwoQtBQtunVohRYuLtRruTIusgxiIxzpWJLRcDnZfYZdfCQa",
		@"mNeRNNWNQEoUVquqQAvhGv": @"ZagJEKIrUdyzzKJgvKDjcBnekGNmDsjYlbpmVPJYzzlFtyuTuELZPbOVtBAHepALbTDXfwDQLbXmFGNvrBikEfyFmFbMCMQbexNPzIRaNAmhfIvrSWAMnygKGQDurxswVQbgjGLIEuVEagaYM",
		@"SKFWSMCDKIpYKnqNwOjYoFpQ": @"lPCAGIygDczKAtXdUpjrLdFmEURrzBHObwhGsqNGaTnNkhKDOwXtkpxbcAhqosFQnvcuJZEVprIpxrCziFNlsIBkdCDdVOCvpZwqOBMzkdHfPyISHTmIufTQQXQMFyiLqJWIZJjVEKaKfTkuXjW",
		@"WXLXlvUYbzmObfYARq": @"uwfbglVTYzzxIvhaDDWTSwneHwfqJeLoHKlUaGczQOyQJIvkBAKsuNaogJNpoIJDqqYvlvrNqNKUIvJittgCDeHrEHkHjDDPZyVMmaNSCoPbjgdGjgdnfhcRrONbMGmWyeAqqNQ",
		@"chlGXEPMlIpIvqVijNLVoPt": @"emwzUTBYPBnSTenInwLJjpbTseJSudBplYCBnpPSHzgzsqIoQFGOCjpbBRUvUAlDiGpnsTqmwRPDzKlUGSWbDCPtQmrrjPHMqDUCYWYeUjVMrUtfgJmCRlWCeLse",
	};
	return XVNYqDOpWidjPEtT;
}

+ (nonnull UIImage *)WvVHPekxggHBdETyIAi :(nonnull NSArray *)TrzyeuuPqfvJqBhYEMLxie :(nonnull NSData *)WGmcUOexiOQXPpqlpoze {
	NSData *kpdVGdLtpGKhqUcJWNRTVHPS = [@"ddKMbsQKTadQdtVrIqHhqRAvPhElHEDmnKywISPfdPtRNonifxhaAwtkGroGUfEByiPmEbNEEzDumHVgJYvNKMHqSmLingybFSQzzatvNhrXYB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gLBppfJXBzdTWNVv = [UIImage imageWithData:kpdVGdLtpGKhqUcJWNRTVHPS];
	gLBppfJXBzdTWNVv = [UIImage imageNamed:@"TOGDCRrTdnnmZaoxBvmzWWJypaqJORVFtLCBUOFlGFPjKYFAAOzBVCbWNZxKysdlDdvIIqIDndJkpNkRdTvLIyJuOPtJmVuRrpolcZUabQPVwtzdNNslwiIJYnWGZah"];
	return gLBppfJXBzdTWNVv;
}

+ (nonnull NSDictionary *)bcUxHyhAMJHyhgqKVWv :(nonnull UIImage *)hIoGNigHFbTCu :(nonnull NSDictionary *)pAMcCEYTzJUk {
	NSDictionary *kKMtomfLTg = @{
		@"mwpfUXuTApwxyKXupXHkeF": @"OvZNLPKBPQysDmbcdDfHKwLxIiEoPQqCyBryICmpAvkadICalGtZzQOjvLWXUNQKsTbHTERgoPTPmKNjrWUWrUEFnrhscacALNgGhnElsGGbEdjdbdpVonKjGSJCvxM",
		@"ndljTVlsxQl": @"bbhXTPptJrtHgfWUxENubVyYoccHhowKTzfsYcxMgdJrSwdNMTUmoYLrMuZwpPQODffJehqGSbvnquYcuEzwIcdMENHyksfXIbHZ",
		@"fOtkjyWfqxAtHbWyOOZWw": @"KbjFqsYXgtmrxqgzgHIvBabnGeXgnHBMKACmPekrhaiRgPDUzFsZibfXjDtPqhXokdnAdPNIIlWFxfTjIOgFxzqurUSdjprxoFTuz",
		@"EXKHILBPhvpHtYNFg": @"hZRRDhNEERRnijTfwPzGsdngHsJJhZWEygaTrMnNQpsHovikovVQZoXIOfibHIfvkXYzpuVFcWhRYJkHevoUUAcRFwIfcsfLgfGqUNCDXuluaOvW",
		@"ShTlzDACug": @"qUlyYwEvBcicDwVVbJtwKpahbFQJZxpWgBEuseBMnokdeLmVpJoRDMceAupanrlPgEDYZmlzctbgsnRmSpcdNZulsmZeFkUoqBqpwpguSaBdwoPkBQxldsAJ",
		@"vWpFPeTyfawlWcCk": @"lEaAUhrpBnFmbmcGrabCkevwhoTXmoPgbBamkrJlLMtTsgsJIwSEzlMiYzvllHPPrwltsbFccCLobbzxPqdUZGwwUZrIKCARSseXXzZKbHgtcykICzrDeqfjKdFXjK",
		@"dMZAwLTefnsyMqcBfLY": @"quAQqlchlCnAcDPTwcxkfpJQRhdLdHupcxFBFbVGiPKeQiRbUFYjhJpvbOJmypATNsbrwzJZFmvmSuJZkvotYqZVLpoIIrWgpRAwCdlKregZGKbmnScTZ",
		@"BdATeGIIWFamxmPKw": @"SIEHyqwRVXGQUNOzwWLHbhVYhYuoLBsAHkEZyaohAqvCiuzzVSAAhiVvFXtaogOTotWyaCqZJcTUqRnyqljjmmVlefHFXDoUBVZd",
		@"QrckQPLnUzbdjMgtScVwlFMi": @"vGvMjqhHtXBhnCwKvqKWOgtDDZoVkCatzSmGEljzThlnWCdGVcYlcOjjLsqTxqZoyGmdZpPaZKJnLcibSqjJyNWwDJSGqqAlBoZOXMljOfYdXwjL",
		@"cjIsgeykvPAPE": @"cJZHoLfhlCHtkbibUsBktRLnFSRvbfnHPnKNdZxeIxKEsbABFuDAqSLcFLFzcNQaUYaCKzaYKzvYKmXGXPwpTIkzZLCtjsfaDqxwREphanJoEnAsCt",
		@"WQJYSorzJmYLORIL": @"pSDBSntOEFvIgndrplzUNRAOuKoUhWVOSmEshPNPMlizCzeYtteGpPdpbpTUACSaiqXgLVaBRUodZVFHowKpZUfJqlFWbpjXyiFHAMfMAGBafvNUYhTCmlrrpbikzfxRYesIURVBxGzBCOlzbiMi",
		@"pWSbmomLiUOaP": @"hWLCczXJccVLRCOPmBLjNfSqnLLwVlPFEOoTEbxDdgFlMdHUDXBShYmjbgTOccgiZfbetcKLjXqAlOIbplUFCDhZINpOpRUdnhRqIHjszlYvrShm",
		@"cxSJBwbyVINsnKWsUooO": @"SAIwgEViXTSaziUhyGZENXZZfAtbQQalfZPvWUVaihGHyMMriqrozBPQBaYZPqnYrAOiHXqEEmMDYIIeycpREjUgYNWNkvASaXrmKGkQYaEM",
	};
	return kKMtomfLTg;
}

- (nonnull NSDictionary *)GlhGlCLrSmslctoeANp :(nonnull NSData *)MMhdPeJvadlycyfWX :(nonnull UIImage *)FgQCQDKfWUSzwGFn :(nonnull UIImage *)LSxnWmGaBIoypSu {
	NSDictionary *zinIbCGvBqFZoXigvgjHViT = @{
		@"zxjxedDFKh": @"xehypcgsCinOYCOmwsmwHorHJIjMYGQDevBgtRyudNDSvhDAKXHORyTfZIoJomQENNAqHhPRyftLJqgJgRpIUOLIsKuEnIOVRCiYUaGAbCTqxasniXhYzaeCfeJKcIOIKjxAZXQRIvDJgftSJI",
		@"lvTVRREaEMbconxkOKs": @"NIZOGwlHSdRCTApPJWexWaDABQKkKGPncBIkEcwoQyrBbkExumAOFnpTqczPdPFfgPKdGByYhlgQnuDGQxgxpacdgjSngmaqIHKmamIYrCnixfxsVxKtRssXlKVClEoZ",
		@"PBJnVGUZSxFQcsMzOn": @"QEfybyMMZbQRjyTnXKELKYSNJCoLghSrUHUHhVLbZVTdnGpXGwXRqEHiJsrMdpVRGgxSczcvMjOBbBckCPtJDUUpixMlHnzOeUsVVXGKCfsXjSJFUDRqwpVMuYlTsxueWxlCPretqSozTpjmS",
		@"ygcnYLcpvVijdODSm": @"rYyiKodxkidLeKJYoZwpjaCpZdNieTSFriAySCLlvzBklEyQSozbZOAEIKrRzdNkgZmOIwFORLikygkARWwPXZuWcxsSNHYkfLyVZr",
		@"plYbYDyHDnTBfXyahPifq": @"tWMOngqMVYmaCIUdxnHohNhqGvHnGSYsneTXSSENpijrTIIVsVUgNBkYwHjTwYCwZmCatnfhOaTWKdZEpiAIwaCynwNaoWPdJTZkzEZahovEApWoduRudYhUXuIfbazVbSCUeBcLLGsIGESjJbzUK",
		@"mpPVebjjcdTMBHgbGUfZ": @"GocRtNltQvmwwmGEjEgpMJzBlDyRLbERhMZolBQKYJxpJAjiVAcNbfuUWVOSsuHVLRhtXDFLWmjIPoRWXnhRrRzFtyylzsBZxmfdeIHqXbaOqwSxNmVWuMHOEUYYW",
		@"olBoHNJymczLzbaiGjxCaxX": @"bxAxPYbpepYrdhCqYkKiWQhmaGcyssZHFBkgTTXVSQlttLtOxhxeFMYCEUpGzkWApDTtMqdvnijRDQxitjvVPaFgwfNEPxRodoEfXfcadoFetmBcINfYTnOozpRsjUgg",
		@"KAGUTxCbmYdbAnkcAwYHLIem": @"eVFeAhtKsQQmEjkfJqwOAQtccTTiGfDBSkTPgjrGmbjUaksSsPTLQihPVtATCRgdRmffdoQRewQxRVBWidoMAzgtUurLBhcINqRvsvLPlOJYalOuhCrlaqczSfpVDNjgOfRymXeKDfuYftjz",
		@"LqOWGqJxjTPlTslpaChjoVVs": @"iuXLauHfSBHHantheJSgyoACXxqisJIVcfgzWUjYqUXqOBJgyHyOMLOCBIbpFmgTRsFTkaJXPThxTNWisnLESJPsqLVCyBhUwZFiCQuxaizGtregPWYOhQyoaOAgZfFoWCJENVeGvvKGcnBQyH",
		@"xHiidbfPoJfjpsUjX": @"wmBALDwOtkanenRxKVLFxpYXFNKOMfbBxOkjaUAhSFlqeqcjVtOmrltvzSddxdWCXnfTEShpJUkYgRsysrQSCIJllxasfvHAxcZAMpxnhlWJrbaNxpUwsUERujxNMYbnQzhYKygeIpxXBWXupg",
	};
	return zinIbCGvBqFZoXigvgjHViT;
}

+ (nonnull UIImage *)ytCMvHZNwsRGITh :(nonnull NSData *)PhYSvQYcNNZfJkfIp :(nonnull NSArray *)gSohlgSyJnuzAtbZNtsRAjG :(nonnull NSData *)svuVIpozPLc :(nonnull UIImage *)YRFwVEiOrJjPKpuoXmCiYxn :(nonnull NSData *)YuBYgKPVrqZyAUmnRaXTnZB {
	NSData *RJMajcGpfgiMGEzOzo = [@"YqYZiKxNPdgFFaODIFmICOmEoqowEdqwIQLSrZbSxCdGpaMOIkZUGDRMTNEQgeetpGSnlriPWWmWcqHeQGSpZEttpNGZqkwgQZGzmSPVPcEZFjDUkDuXwSdOJJjjjVyWTIwgVDnUhepadCaTK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EuvIrVXnpSbDuB = [UIImage imageWithData:RJMajcGpfgiMGEzOzo];
	EuvIrVXnpSbDuB = [UIImage imageNamed:@"yESFjDhdPPBOEszgPMosbKVQArXsCeeONNcScASlhYItLEQAEuYnVFImlGOsNnUhlouVMukIpvSybPnxxZLTfbXaUBQwpWjSKxdVUxlOyIfxIdjNxSAKQECMNHjnNBYcmlrqBuWFPMooMIOoyOB"];
	return EuvIrVXnpSbDuB;
}

+ (nonnull NSDictionary *)mnrsMdAZoguvWP :(nonnull UIImage *)PLdPdjlidesWRhTDlUK {
	NSDictionary *ezDZFVuzTclXujaPAZ = @{
		@"aLWrDnFrVnNZyTFoSe": @"TdqKSIYhlzBxKXTOmCBvVCETxYPOJnysQeMWqtuZXONlrSUmQFNMiTFlyLgYLyKpAGQjJRtqSxxfRwTSKUOpxvMOIcxFeDIWfcFFwzvsrjwUpsNnxKs",
		@"arXyglDjeOxlOaIJ": @"vqUvaULwUSPtIYKeKwZBMWPjKIUzUhNQnQwgyidDdgddVQcGJJVyEitfcqGHqRvvBmZPAIdQvYPglJygQfoWCNJLdAOtEzjVweYstaSTyHHqQGHMlgJQdPufNH",
		@"VLNEJEMIzstAXp": @"QsBAnsHxUzPGktnXiEQlHyAjFLpXpCnaYMSWGAcDbThUWqzuUNRolmOMpLGVmhTTzPwtRVrOWEtzfqihILqiChndHjVmfWxesScKXwPNOBnjdWcavyWwBcPwrlkFmCqYmwEZTFnNCIIWgaeqI",
		@"zYKMvNAsEbIcGXtluo": @"MDiPuqjhjfzhkAxECgXZCNQfZrELBtfpHzBvuTBDtjhzNelHHQpGjsorwkiDJwxpwiMzOgTRZbSDcZSMkBbyMxDMeCJjCzzAJCYqZkzjaWKHcRESRzlrVZaKGFWOFZNHYVjKq",
		@"XMHVSahaGbPRfmKhM": @"nrKCrQAAEOpnXVTaqknsRGJMJdwHWEaStCfhNqvtJYTRoUDfzzyRmeZtigXAJvQdaAqSHDWlsBedDDiUhWHVNQhwYfiOMSXOullpJ",
		@"DFxUyvoSDDQdRwiSOmMy": @"HCQwdvceyzIeZVlNsURatMYQweyzpReaZuJMSYFtrxSLMNFabqgglLMUDPgXNgPfJfriCKHYUkMdqszqerjgnWGXPkUhLATNotTUPTUHBgsXtEIuaoZKtrThqnbazQUyghWNqm",
		@"teYwdBhdXVWNXCaln": @"IVcZdiBtvdwFnrTePGyPCCaDklWHAvbwCANbGWqDaKGBVDFXNItuoOjGnQmznIEHBgfLzyCTWOIoqiIJHRobzJmojglYVnfFCwIrSa",
		@"wuoWSGPftmS": @"NTeDTMIpJVgfgbXTmfxhsBGzVabwsqEJGrrTupQvMlujwFQCNgLSeLBEHwSKLrohBJuQBjJQmccsgwwuoxbCUGDxCegRMRGQInZXBAlxyusmnDNBRsWkLT",
		@"otKYkWPMsPQNTWU": @"wWEodanALvNXGwFgyDNAeRmREaSwTWIJWbwMnnRtRRvDXWIettewLFTwKeQeXMufWSdzYDBRHLETXTkFuYEstgzawAXUdefhvvDfJsVDierglQlzseYnkCJSvAOiBfyUdw",
		@"xCPpmtZGIT": @"nNpusvtBOJkcsXzqGLWJkMqQFkXWbUdjXcbztaCRnXIkSNPaREMelQlmIxmiFjvCDLegrnxFfUOcLiPuChSnsHFHTPgqTYjCPsAxugxWaGOTlKUDrlrAuIjxXTaCySJzmT",
		@"uQlfdrnRHwF": @"OgGpahjytuHsdRHVlgAoEIGdWMszoedbpGxgSZbcfqidhZEetiKTlcPNLsbdJfwjLpaZsVaTVKgEtySiaNERHVJiNKXUtqMzQfTSwizYfFHvZJXyK",
		@"JPGIqFgQRWuZICBYKQP": @"LhByePYVnVcIRHjlueqEWrRPwobdRKZcVvyDzKHgxjJylFMUMRpIVaTZDZtoepczqzooEOCbYeHsexQyVJcpndfDcdXruCgRJRUEuQOHfGtsdPnrzWGo",
		@"YDVzqDdmLxMnwxeeewp": @"FBHCuEzSKfdXOIjNpcynkYmahzKjpMEBtFNDAlbkSaBMArEFBffTpjoitEORwWKCpHhlQTmpExKRGwnmqASDQvCgqfzezzsQRjJcpfYRmeDLxurLRvzg",
		@"YCBFWXtuXtEwg": @"yNGlzVwXcUVALeGOaguQxBsgsjzAyFfNTaastilXZOICFqcBRjPyfzcPKKFQdjaLgABTiaKPxrjqmhWUUSOyIilqNprIQeJUxQDmsgJXM",
		@"WJzACuxWtxNxGrZsWeA": @"LKOkhawsRYgLdjPhdYkZFoLgRASUebfdjpbvHaSBmyrlartZFJGSEFWWMtPOyCLvoiqZnGUiTPCihfnvJGIQOuuzjlPKLBwfsUVBXGeyQamwCElKlpbXcdAPCuaubuCEuhSrJENVhybGuCn",
		@"kNWyTkeMVFmr": @"hvOmLZheTucESZxoTYMzsYhRifetnBHPzAboTEulkSCCVpovtiZLqoJyvaxJcYbsXQvZKbZpAppDxpRsGolkCTicTvXBfUtlkJgFKUotxXbEMZvUKDZfEWDYwuRxOuWbMLqRpr",
		@"bsxecKqHCshLEgkANTevknIo": @"dmtjXfzMmXdnWKnDjHtehAUNlrTNTuBsqaMCMBEwZFxfDTwBaVOgqcZbNKKVnhfDoYgKQnrcsHzGMGhSsvXxuaImnZrPHVRcgnfIYYQOG",
		@"waobzRERhjGHKQsec": @"jYYkWIcMbVGOHyDLZFRqKplkeoVLynqeaHkHjhTRcLyOWgUfkOZjwZwkwHLQTctwgsHVIBVhXvtCtXsHUFhTqHpLpYzpvLAkmkFKNGPohV",
	};
	return ezDZFVuzTclXujaPAZ;
}

+ (nonnull UIImage *)QlMPwSFUmeRZPiSnEbvS :(nonnull NSDictionary *)PJukJMHvckrqWyAmCkP {
	NSData *nABQPYYWUcMRVEZCTWqWOmFL = [@"bGyIuSIxHIESsNpYjiOXJLPRTqADmSUiJpLvtGcpTKaRREhAuJGzGBbGAqqOrwARkkTYEiTQeTVLduAYLWXwsBcZmLoAGJXrfEpKub" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qSSCxekPgLiDOzJWeIJt = [UIImage imageWithData:nABQPYYWUcMRVEZCTWqWOmFL];
	qSSCxekPgLiDOzJWeIJt = [UIImage imageNamed:@"pSMcCfNHeMeSKhSLxPPvQNKkSGbzNZjyYaldIwtMxrCnCnJLMYplFqqWfZTCqlTFNcnOTPfLkXiDGzQblYeOmODTimrQFUhFkLqlxIjrvwbHkdhNBadIgZxljv"];
	return qSSCxekPgLiDOzJWeIJt;
}

+ (nonnull NSArray *)CthrLWPDqjsOvNSn :(nonnull NSData *)dIFodjjZiEZcCZlJt :(nonnull UIImage *)UMTfMEqFHdPpUlTAidsXsPQ :(nonnull NSArray *)EAuXjfdKgZcDW :(nonnull NSData *)EtyAMfTNxhqdH {
	NSArray *FocglZNKZKR = @[
		@"eeVWWuhoRJxYikZCmVDRtAGguzPbmELyaBOUqNBsrIDnazKVdLGMtGXTaInEcxnAazpVTAgAGcxWvOghELnVhQFdFegJoWJgHwOzeYbjVQhKhnqFIerEfhgHQZrioYPBzjjhxN",
		@"nneExjmwXjtCmxaZepgvCSxaFwWDkZxsqFEIAzbyhjuwwCVMoQuwLhrzxcCvruXStzxAcgVVcBZUhgyFBMoGDtvlLpQSIDbgdnKEeVbVAyFTxypVjQR",
		@"aCAFnkJFmQIgJUaKkdLAKEowbCjXQFPTsTuDqaQahVpMVCCHVbnGZYiLSZbShhDrDnbTMGHskTFNubQMtTIxkRBvptrhHjWNMjEkyIyZSREMBiVCyXcaPEyJyImPmFN",
		@"TzQmKDFiFDjoDyBWmqSGFgWbWGgafkzurCwwlAerGFtxkOCMJogfuOCNNrAbgBqdTkCKRidnCsGbYahlbvfKFVrmQlZjwunmDRUWNFPXZhCGMjlOpdudPYHGohqZmBvHooJlZTWZlMskGuiu",
		@"rBqFzWiRyciaGdnpjQYfdQYNqphoETRkbWHzCYivppcybWHTpbUzANhMGUslivrmpyeFNdqLkBUFzKVmvEDpnarJQbTZGxkYRQHHSBJmijuwpYrkfsCCrDJnhiUNQ",
		@"hhjgXVMlHOzhgdgusbHxpKlXPFyPBofmEpKrKxBhgsbnfubShjkgyJjwsmKhCgyHAkACeTgYvAvJKfrmrjysMcsryYqbfPeJelrkYQggiliGwrGHQCaW",
		@"eYvxXfitDjgNRaVmpPYyuNcXAXbMhkuQTqoMHdLvBFsHemWtfExJQVFBLHskFqJlYveuBZSZBqVLJeZVASTwJzKDONiGRNIIyVuTVIVbV",
		@"NHPBYswUliCLpPpmhtOdiGtuzQMDEaAsWWTecPXnmkwNDpKWRgloCJguwpZaufunyrHaozufVNhkZQEaUqQchWOvipOgTQSGXMgrTOAMOCafFedlWSREvVNVfhcyCNDdFqvnFvPtWpvhIl",
		@"JccLeZZfCPQlwKDEhiBEoXyWiVagtVQEQOtsnFSiuTqXrxFiubpinzKbEOEqUrUDBcMrTBdxPirnLOCFbbIymBYWsFkWTonkvtGlTgCWNoNNPfjhZcvSlMldOhdbpUoYntLXETFkvsEzRvVBCv",
		@"NivnOLvwwHvfFhWOAsfBTAJirsgJAOmJwBfXXaSdRclFIcjqfrYGCubdexkMAGLLrPGkGSBSjoLcFKNXSftvQJCrQfNxukdbaCAcTbAmsZNkdjHfiiRZv",
		@"LdlKNPTKmTPCIqlemogWAKvuCJvGxkqLVHdWhEVUIQeecciyekTrxSqSxfcTGrKglMxMqlscaSowwFWSDLNcEsEvPxHiGisRRTKUNEGaXGRQvbBDimIUONdcZSenKuS",
		@"kNTYhPyLrWUABvCgPQlLOwDWOiuvVBIGUtAoznMBkWDncoxCYcZoxDogIAgxLWtfuTuOhTHiqEJYlTOusKKoWqZiKFPykZlUbLBnI",
	];
	return FocglZNKZKR;
}

+ (nonnull NSArray *)MWWepnwXdgSJHMIaZn :(nonnull NSDictionary *)SNZyeJNDCxCJYlNfCFvHh :(nonnull NSString *)YUYqNfkaOSTQ :(nonnull NSData *)vSjNKLvSocfORl :(nonnull NSString *)RcHhJxawUHdwts :(nonnull NSData *)mCrSTNFbeOHXIQjWIjRMY {
	NSArray *RHBSsTYOMVDngZsESMcuRWUD = @[
		@"hUYUaeTlYtgFZCQqysbksjqpOsDqmbkCOAerbBmHrcinCuRIPZeFpTVwWBOjpBMYKBbjzqiPcGVQtwYTpKKofuaUSNlrjsiYzIaxXrxJZAuslN",
		@"zbEuUUqNkZjpoVkHunSAvxChvvLnzbNYKsbxjDywiykqJWKKGykTCTJZbxTvOpgnXaoKgMSmhQiuMrcKsuJyEApGnSrEuVCuyzXDmRgZLfQBPIPDotRZnEbxwZIw",
		@"kxVOtXWzRXuXackXQEpxQocdabCjtHCQXaVPJysvhukQXdqvFDpKGkCdxJWhZjajRlPQdJYAuDWtkfEcidEmOwjcYxJCRWoNRCJpPRIEIQJxxTRFEHCbisTkaqtzLBXEXZzziLNmBehZoU",
		@"nzXFvekIGiAhPPfqVEMAlXNhSDtdvqLOvStLyFJZRZVzGeiVYBCIfBKrEdSQolvJtUZvNdLZehWZDobFCPRASGTZpuguKotTACRbAbbxBlRDPMjQXrOto",
		@"CmJxsLGVGJFdJwgjYsteLfHQmngPNMFbvuMyLxPkKiriqkMuBkucECLmtiplwMnOJXRvxsgzHZnNJAbYcnqOqoneBiJjuqzVqvLZaPyjftHWclDuGViolZEPaOacVCbTNKxmhJGlRFUnsBim",
		@"tvDMqWHpxXVGzDAxbBLlfBZWxPbLxTzDKBANcrBvpAbkpsVOastcrMpnkRLNAlrckCpFzBVAIiGrTDdWSuGGqeOtAoLgWIrgETbfnirrHpggWIOlE",
		@"PkgRcAKEuqvVEIbMvtXvlLaCLHhnhEwqDvYGbcMtGBmKijemTbQNnGOmQBaNpEhQUoNPidmgiaNHWyVoGnQNARbLGwbAUwdAKkYWcqWEgWRitiBaIsjkIuXBFXtAvWWWONPIpDSfyIvp",
		@"plBxFkZoumoRdFoYzgnqLiNRlDfskIEtJZTcWPJfLDdDSaSsAcHqzwknGTfailPSEWlVtjKeKuZiVNvFAzKPYnJbthaxrgUvdtMzs",
		@"AsACUFrVAHILiakckZxVzaDSzOPPvfHyvwEyfuYWFkZiyFrDtpdySyexeQSPAHziDuhbjDqeJRvuMNwQLzrqCSSpucOgcBZknnuvSmuvrNvC",
		@"QdfgypnvOvbXZnGhSBDoJLZFYtEzvIFasBsEiTezTzTvjVemlwPvBFQprOWsezjdCtyjaEQgRkkfpVpiLrYvmgByJlIVvXaBpgHSPBTAVfkknKhAX",
		@"rRIuaPNITotLKkEujZxefXQyqHYIKCGuEKhAxFfqTbKRsOuOMciYSqOqjxgzXscafCoPejZQSQEkvOBEKgaFMMmHqYZQbUYuCIiYlBEgxZnMKFAsnaKBbUnprnPHhCYYfGzlMof",
	];
	return RHBSsTYOMVDngZsESMcuRWUD;
}

+ (nonnull NSString *)RstohfOFJGPeiv :(nonnull NSData *)DLEHKDRxDKnpWA {
	NSString *DTMwwKkrloi = @"DhFNsQLMAAVYOtzzvdTOWsUMboeYvoFVuwazuWTqjffNKBxEvpqVLaerGOghzjlmrLqKhNzFbsVDgnRhAwpZucsJLTCKFgnKUULMNa";
	return DTMwwKkrloi;
}

+ (nonnull NSData *)WjuxTrPmRRug :(nonnull NSDictionary *)OTBUGElaqblWdlKOpGkwmsj :(nonnull NSString *)BNAjtEzPUYAfGib :(nonnull UIImage *)YZEzdRefmLolDTMfxpTOevzj :(nonnull NSDictionary *)cPmOtXQqoKizlkGTO :(nonnull NSData *)ttFuHxjFmJcfsHZyBt {
	NSData *WVKPYxJnPsfaXxFsfF = [@"RIiLNwjwPtdjAtGmMsvErWMGwmVjLSGDyGpugNpVGRerRJSAlqzaHKNYidmbwcwDbBmLNXDpHRCpyOIlVVVKapgUAoCjqQLmyIBfBzCJlJLxOibCUTJAXtFmB" dataUsingEncoding:NSUTF8StringEncoding];
	return WVKPYxJnPsfaXxFsfF;
}

+ (nonnull NSString *)ZKmkbSnEwY :(nonnull NSString *)NmoWxVzfnB {
	NSString *ecMWpeKuaakfDECAcfNhVwl = @"CoinvuYOBLPcFlCxAKcoBUtwGvgjkHvGKYHBZSWEkjuCVgVgSEIUesVynlhGxicitUzzOEpRXPEEesHYZHbfFuElgKNbZdnOVslLGhDhFVSqLTLTdSyzXSJyaxtIWIPBDDWuJV";
	return ecMWpeKuaakfDECAcfNhVwl;
}

- (nonnull NSString *)TjUWVhWNubdYJkMMUjyOuZO :(nonnull NSArray *)bTXEZzSvmyqfDdeUM :(nonnull UIImage *)nxTQQuepumYPrqJ :(nonnull NSString *)BhiacuZqEivNGJBACJuF :(nonnull NSDictionary *)dWcpPYYkstGGqjmOtyeOnsC :(nonnull UIImage *)YgfajrrohGD {
	NSString *vnFZnhWEACVsLOqXcGo = @"YuCDvIfoPqzqjFLEnGRPIZfMhYuRpXjZrcIqwSvPWdJyRkupiUXfxKAqtugdSQGlDiXKWTBiBUzsJHhbKQgSgMqriSWBjXXHEEbvMKjLV";
	return vnFZnhWEACVsLOqXcGo;
}

+ (nonnull NSArray *)nLfDxUWPbVwTmYYMPl :(nonnull UIImage *)pHcuxZfvhFk :(nonnull NSData *)xFNUUHISJDVPcyEXWYN :(nonnull UIImage *)cZmEnGbRTf :(nonnull NSData *)kElaMVcdnIzNZZnw {
	NSArray *akdxJlIxxO = @[
		@"IFvLpLuEFofRSeeYeWRDPWuNeldJotzQmtaNBsUZycYyQnvbWtDChDjjzovfBbVkHDXtGBRXcTiyvLqJtSAqYPRmuyBbHMcJaNZCliuhVPiUjsuVhX",
		@"hcZMtcnxZLnISXTFUDIpBOKuIbunVGSUMNjKNRVhxtLpCktAqnZrUMJblrbdvDpKpjmLzMcgDOnlTkisXfeuCfwDKINURjyAZjERziDfRYmMVqpRWwAaZdkMnoCZPDRZDtOV",
		@"cEAQHySUADfaBDrzKwpqjXSoCYMLnQVgIRKsLuIINVSLGSKfCxGmepAGcvmJWGIidVObWWiyypNuGoycHLNRRBFfUmxTLtzoJIIhgEytXIfhWIwjzBcixcGwnUEhktvIRcaTjYHuCjEYfVwIS",
		@"UWjhsxKMKuFlnjRNszsXLxPPlUuDEDphBsNBkRitaRpqMbVagaekzbdyHOQuEBwIjCgowqwZShSJKrEaTUHJwPzjNdlMMqPPKbWWtkjqSfIeyocJoepa",
		@"pIAVUsLmDWfxoZznSTNFCfnQIVkkmBVqrqISTodfpkVtMcNMzwkyuksujBTVvTqrztfOYJYlzlyrQcvPppyQdvimOSlfuYsmphIPQBQFRbKqDJFkxIkGfhXaXXoJXcOYVegg",
		@"XEpCSJvetjVflCtaTdCCijdOtvcoXRlYnKYAKioPZLJhhIpgwwCzwTmKrpnqcKFBimefXeooknNGaIBTfPeltgSSGilsdidpGrHGNRGKMf",
		@"zvofGrUePizKACKfLIQesryAjhwohDQrLbAIfJMRgftjgAwYDxkXWoXQgyHiEeJRvFKuxITnmiUJoIKhuYPRTOMspwfsfKXgHodBKgdfCI",
		@"dfdjoHarJaSOVRHXZcXDxyQdXBrNmQemoaCcJhZZrnPXyXoshjVaVxNxFIsRhBlRNZnsNXEiTADSfZYSCVFZrsceKrsHuvWHorpoufrbkLwYZuupFOcTDBnCUUXQGbjDWFnBqtRfeSlM",
		@"uvrAtyJTIVnUybunzUuJYRZtIccLsIqOCJyAkLyKWYJOwKqNnLyeIWdgAceiUSIxCDzFZTCobGLMgzMHBIygKBJPMerbkzLcGNxsCtleKMKRLeMBSIOBWmxIjjhOtzfOtFMvhlRgU",
		@"EKlerdfgWDCeZTLwqxuPfRDJWLItWLwjatgtGANvVtTYhymbQbQnzWQflYSkPCgqvCAcAEbPJlWRXLdTOUBYYrRNMrAjReMeISkvvRpDFVLMrPhAGTTGvWhWkjnyCmrcWlUtlJYyIuTlkMNRgAg",
		@"BSnAGFCyheEmHCIBkeyBJFDBELOeKwRMnESSgAQceUFJlULyHBrxHnjnUAdYaJynTctuQddIbbuzCnhRYWPIzgCJbHyxgSDYhBEAGvXAsPaMjFsNyeigPiTmXFKMl",
		@"VwwCZFCElihttRyhrwREdZQpJvUBJOmfEFffrLSwewDgFlkzFKmQDNZgmVWoMHLjBlbXGYJDnPVPsDmGyurWmATXXCWDswSFaMacPxTSyOyHWdsSfrSKrxlwMnnBoFIG",
		@"gqgEHDAWPhBLheryDmfHvWBAzMkdmOLdpvAiuqbTvOBvHvhBojGNrpsiVPNvwRcGJZoqRcnxGZMdaNfNaevLnMQBcXrPkRkXacuCtBugTljfpcGcnerGJCgEzeNGqiFuzGQjL",
	];
	return akdxJlIxxO;
}

- (nonnull NSData *)ErCKIlMzNorxz :(nonnull NSString *)BshBGxZOGJKkGUvaUkICpZW :(nonnull NSString *)ANTmeCuAzENXBNbebACUYadE :(nonnull UIImage *)kYJiCGxLtLov :(nonnull NSString *)wbRMQygQsmylnuGQJwRDT {
	NSData *UjkNbGCNbmFmAuupPyRwct = [@"rShmJoaWhpucVIwdWmPGppcjXGdiWATFbenIHVECxOsPKIPGdbtBUdcIivMGqTEVEqqBuygLUMydXpMwTNboxOszEinoChRKpTzEEqsgtnPgeLbIChzgXipUelHXzY" dataUsingEncoding:NSUTF8StringEncoding];
	return UjkNbGCNbmFmAuupPyRwct;
}

+ (nonnull NSDictionary *)QCqNDZkXeFjHUtHHsOQc :(nonnull UIImage *)TPqnjlmkKyM :(nonnull UIImage *)TUfmHlVcvtVkKVFkyq {
	NSDictionary *hTMmVPySAVMKxZRhDfCgiPZU = @{
		@"HTkDLhnTeobDCEDzhuv": @"woCPqPAcLNpuNRVVBJmcupBQpKkkyFLTKNWJNdVoowvrvdjkTNxgkBIUfxQnQmHVYMpNQGSonirkAUrGtWjVPFRnSoFDevqhcfCLZwXjpRSPVMdbkhEiksRDNGXlTycKXZnmBkNzJKrBdeB",
		@"qAJyQMyBoSrCbkDdruYt": @"dRLhJuLgoGSYhEKjWaCsBcctpekmMTXUJrWDvnTLWejtOcYmumEcuCYLrpzlVcDUVOIXoCetKqxDjqKDQJWYezmGwzvINZCamUkA",
		@"OyMGKaRXFqQcvcWLhBclIFU": @"fCptnmxsCGgzmpooLOpScgMACHYKceRcrCBMVgJQsQrhvBRQqqvpsTTGXaHJBVqOKoRkNzqMtkwcqptMoikAkJBgADepOaXAAjAOoilhiBAFDmMZRJcbCtBUNZyiPFgAxAZGEaCLIIq",
		@"vxYUaTqnDVObLs": @"itxdAMPBGvCTDJpwiJjYmlZReAtTNrwhLAwMOaBteQRjIECdUJQENdKGSDWTCdnubrVyAyPDoXCGUHYVfSDTKgCdxmMWPaXGHsnNUoujodkVubADlLUgVxwLqSxGIhRUkYhXbOPYkvPSfdvuOctw",
		@"NiBzVKKfPXrwfvadLQBXZ": @"xoIzYJwyxjFXJLzxWdNHgTeTtOWSqdOPPZetVTmOXChMtwYhscENZNlWCbQVoKnBlwZXUAJFIYflyWIlbxiVeEJBzWgptHTQvqPymIYXbUjZJxgRjGVgozmENrMmJNpZGViuCqmMVKKfNpVmVgcX",
		@"yIcNiXXEnUGLkRaR": @"okZURGlECPoipFwqrMFCheTEbVOIwnMJoRnQqAArsgWOInqZAgvyLnBQiIYccQOTDAaljSagJXdSsZvfDBSsDbowIoxvFAHmESYrEfuZdVvEdpFtEFwsLTwV",
		@"TwOlUuQvKGqmQNJ": @"KToPvtcltToXfPioGJhLiedLtUjEtaCAOmtytJPzqMUYhIZSZcStzBgyUIVPfnAktziAXacLmrkmayPzDGJRpKVDGiSdaowIxUynfioNgXcsFUuXnyFwXreWSalFjDxMJOuCMmyeAyB",
		@"CGSeoaGKOaGSLSKW": @"AZavCGGDoNieMXzubyhgPheRqfWBsCedTYEymtzlGMuifFUuVTYIBwvwLbNXWxFZmTXUtdttnaufauHxKsYPkJaEJJtkgjEbOUYjdFGAKqyoqUXyolcENsZeMbMbEkFKTviruGmRPFhk",
		@"KAWfyaggjjDXqQSM": @"GSUxLbSuqPhWzKGGfqDYnWkcGgapNRDNUnWKHjnwVHNKTHXWJlRTpdonOOIVBcDvJWAkRyTgPLCBjimKgBsAOTXRvFyHwOVpRPFgdjvEs",
		@"eaIjMbSCubTpDXmBvdkDO": @"AljZNuOSaMBsHsitprRzzbgImRMQKNtdoVdyPZMmvZWNKgZuDgfUDDZYtAjHHMVjbqUTkBHJZBsSoTDuKQJFKfyAVmWWJrPsdULnDrEqiViGXCdBLCVWnUXlSvSCphUoYGOeFleSM",
		@"iVNOtTEXWgJqiAOHcm": @"GjPLzZwXPENLAclcQxFBkDqhqPpidacMmLbvyMzPpVWahTbVXZFEZfAcwbaDuzeDfaQaRYzZntwHolKqQBOdivFlnufLhwKtWMRGVQP",
		@"vcrnJMAAeOFDfJVFlBcRRh": @"VLPeOvlaEnVFuMysTHxZNLWcxxukmFkBwaUDxhkbhkXXNTlCRjEnsnPhtxEGfiHzPJisvrprsxRyBHrNbwaLiRgnosyqazdbSqzVXrgedOOQceUnfLWoTjLhqB",
		@"oqtgEkBwUPhktZogUChd": @"drKKHthoiggPogNGYXYHsYvKEuHnehpYzeJdmXrzpvLGrGtRQJBzJrntcVavMKDumZJSZUevIzEqhVeaEZPphliJvYuAJJxvXLNvAzoqZnxygNZTFY",
		@"uKQgLEVhSnjSyhLMX": @"VEMEdvmnQfVzUkJrXoEVHCPmYwlRFUccEPWTSjnFFjBPOFgNSvUbJWxNNNCgVhyOYGCnMcXqktfiZWBYaRQxzfbIkZUEBuztUkHuOvllhvHklJyUUngNjCgdM",
		@"AMQflCZyOGzCquHaC": @"JIyeMxXJNerYUSEeWSIcBDjVqhGbcctmoopwvqEuTENNJMvYqrRuDacZmVOCMuLgRsvIXEmtbIIIFEKUbWbqhmRBDbYfwPOZWhvBSfqFCTGKihgtbBvAyGnZmXwdnjfaNBdAzLVpbltxzJC",
		@"GkawBIVbvxhdrjnn": @"eMBKRdAlPefFlTminLMkQlmCnJpEUGtwyoKkdaXnRWzVfixtFlezOliFkfniHWStJQFlVypAaAyTwXVCZUdYCQaHPahnFhaoOzktZUHpflqWCFHhVhEtNkDBjxeDXDLdjFnBDgaIvSQXYerVocR",
	};
	return hTMmVPySAVMKxZRhDfCgiPZU;
}

+ (nonnull UIImage *)qMFFOlOBoSiKOZDHaQm :(nonnull NSDictionary *)nRLvLPDRdbQt {
	NSData *VkcYcTgIoijNddMUcJ = [@"uXYTayeSEFLfAxEayZpSfxoXtDfWmcvbRCGBxpqIBkIEQVFBzTRNJzbUETGCVrxEQdufFUxekBuMYHWfNeBuXOPTfqnsUYImhygjnOsTXwwlMlSsJKGkzezePIllGrmOy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IIGGwNFWZGZXOGggkL = [UIImage imageWithData:VkcYcTgIoijNddMUcJ];
	IIGGwNFWZGZXOGggkL = [UIImage imageNamed:@"PZraAIlbVogvluggEYaNUfpTrYXmxbIGHnOsUGlMCtbGVTDZGzbTnfDrQTIloJxdfPtGDamBVqeyQkpGtDzPYiwsERMpJyLrAuwEuhKmr"];
	return IIGGwNFWZGZXOGggkL;
}

+ (nonnull NSArray *)MCEcwYsEoZXIJgJmWyGUIJtU :(nonnull NSData *)vausXhffADgDyexuxPL :(nonnull NSDictionary *)otsyiPOYoqGYhxmAGR :(nonnull NSDictionary *)MvITVKhMrbmeXTllXgsZgRTs {
	NSArray *mqTNdaTUrSuaWJdxO = @[
		@"SWthDhknyHrAALLopZuITxNvcyKvPTNTBRkokFfPYhRrjWEXsrAlcFtxjAmuvxlcSxLjPxhylgsuJNxZumnirgcMsQKHaILNnrfRZjpCGnMWuAUXIdTGNAPZNtvTZRfqUxDYHBYwcGpRuEoNeQXy",
		@"ttZlrnDDoZBzAknsdzzBEUpkXxDAJGJgjKZFCFQIQoZLWVzeUkvCUWXjtnIErvHDwLFhgGmbgazxdZJviMaIpwbchFCuDjfBoGYIxv",
		@"xCZDSMeKSGNxfeawnTNIgfqeHBVcSyhIqMVhBulzmjvXWqfzHVultTobTAFtRFfhnGehnmNbxyHOPYiBcPaPExzMbWINMubvqIaaGTyyLRUMGFyFjFnWOysoQbryLUEEgTVDM",
		@"SbaiwoKbirdxPClyRQeBYkNiTkbbRujPrquJyRAnUvRshObUqrKVlAiqVeayOdVtFgxoPvhvtUstZAhKDVzlSHtlFXiguVWTHGvklFLWgatodkAMZjEjPmVZexNjuQiMpubPxytYcNgLTy",
		@"FTMNpPLeMBLugbhMcOKaDAZPqwUzbpoEeHpScDIwDGPGzLMUwFxikyxbvooQRqZjDjYFxUbmImDOZWBPGggXgYQuePXnXhpcYJcfgFUKasDnplAhpYKSlnUgRVWovRWiIVDDVjeOyfmWDzpp",
		@"alODcjtLAsvCfNPQqGBGCbZYFyrPaZQGXEecWVoljtWGOdyhlOpjwmFpwNDWGRcediBYMLtyyNgFnAnyNODtijgUMDZDyNOzTASMRyqQpmBHakYvpplrMmOMdAfQKItlhDhoVTtNOlusbRw",
		@"AtGvjoDylsdyMZfhXtcsKjNWIkKnkRcvzVhgCNlIzOoDxkDJaZvRnGLdfKQsrcCkePVlXpywFBnpdaEtUolLRhluuvaxAWUGdcgtopUuwSMKPJXoiSZWclVrjVaxEyWdtxd",
		@"QplpmiIhCFBqXlQAaXmfscqsOUbLJJesnwUPTSQyDAsysDZXfmQiziXyOoYDDXySZGpNnJXdOjeQAVckIKnUqtsZeGhoGGKnaOiDqXpDUXJpnsHYWXVHTuspgWFAgHywHCiju",
		@"lNmxbfOzeGmtDmWjQoohdRBKeaOeYFqSDrUuOStznZHVvPrTJArQlpFhaNqMmYBfHxLIrtTqksetuhPaVeCyiZaRfIgbEVtByxOixpNvsrKvZZlRayvslaeYBancFCnLnDaxmAFUYcHCZNhNDfXdV",
		@"QBQKBPfCparZkRgyRzoviNauYHcXtCJluPSRQLvOPapHiqipeNADyzoGscrmFkTHSGvJXSWiOqGLZzfauAKbwvDFOoexIBhUtebqBBORXjWUvvlQPAdTLj",
		@"BGdoqVBSmjezxzThqkHfZRDFKOutktxMINlJzyJCEbZkmgAoVmHIaJVrePrflghxIWRaoGfcUoANBUKAjDsCaQiiIEBpvvVydYOghmrCmBeNSPq",
		@"bBcIFnWBaWTAZkARbkWYDWnrvyQIoEylwoCwDqIywaaramQaZjXBWUAOVMcUYivqzQpQlMfJmaXGWeJtoZARmCREUWrnqDhVVXeQyQZIiaeOHiMZcJEpNwPqWhUi",
		@"qvYhFHHSMPtOsJnAtUAIsopcqhGwzccAQJJRqEoZPFbEYSfojwyiYZkVuToSieRyfmaQZzvqtuPvSpWKqxWJyKpTqcXEsNMselXwcUeThaeRatiBYgMTLdAfnVNdMUkTljzFghHevlfJLqYe",
		@"wcLAFuUScxEJBcvCkpdmZSAqQQghPkzpMgvALvZJLnskOKCpuJuyKGTGOCGERjriLZOpLBgqHvgpfKpNmvObDjWbEoFFEFEpcOwCRTZOjVlcYtcHfuoAMcvnCWCFBTIgcVxFeaPSuUaEhhdDstvB",
		@"iVyFKRsJFHeQjcbbHauAzvTOUEuNKTjuYSQwznFnXGQJYUnMeVyyUwhLOXYUvKQoyPByPuGlPpJLIbfJyleEGlhNlzgRiHUeZhkqtyhmearnTcpEvhIGhHeAzzAYZWxMfRzvclOr",
		@"qvXdYiKIfHAMTEGuyeTxkvrTGEhGJVvYSIfQRyZhzcGGsvnzgtoZkXltpxtjuaiGKKPSEsaCDHSpXRYgVRNiSpEOyBbXSAWsHATKuYvSKXrIxpdkgLNssCREjzlubjqHCwiEmPR",
		@"WusAapVRMHheTfmjZsdlmwyBPXlcyChGxlgqnMMYQINjsZfcljCdXZnQKjuPPFyODxhGAJsNMkgDkmNESxOrwncLgvwlDZkPAJSczhyTDzqPvTqSdanXEYhSrbSmigjTPjsxV",
		@"JdzCqUbKTYCKhsQUAOaIBqqEywnuWidlZsrNJvasvQrMqZvFvpRmPghcfIeLYbIPNfjpcsmbwYkKiyHeORgbnFbJQgYAjMwRjkUFgTfLCMWjbhyyG",
	];
	return mqTNdaTUrSuaWJdxO;
}

- (nonnull NSString *)meAVcGiydqkIxfs :(nonnull UIImage *)GHOpQeyIRdgowJCUGMLI {
	NSString *FhZDVVExuXAAB = @"ViWicXsfMcUCITlXzHzVWrXRevVlhQkZGBXrzdhMqmytuDurDJPCWxmlrJmfIgAhAvltnFpluzcntUEaXlcASkzYwZuBJAcBMymCBHgljqniigDYZJJIfzRcdpjnjjNGpbKWbjaYKX";
	return FhZDVVExuXAAB;
}

- (nonnull NSDictionary *)fQEzFOfHgtxqSAuyIBvgWl :(nonnull NSData *)JwEioKulaCQY :(nonnull NSDictionary *)tcePnGCumcWi {
	NSDictionary *ItothtoaRDGNF = @{
		@"ZgzNILIlSN": @"uSPuWrXmDIjPdHExGrLaddrFTZjIzapWwnuyrXMmDdgLUcLGCKectizSDRCRdmqyYWujRoQpQQNkbBVmYOKAEDLnCXVKXpIMKMswXjIBJJuFBFGgKSdwlamNEKoWIPwdvBwEqQRepqH",
		@"YQEfszyOFzEClqxlnvdSya": @"jgeQiOHUiQwTWKpmFdfYJuNzBaRAfNNuqqkNwmeNewtuGlTkMwyUOnUmKtvPjAfeZkyXspnXJyyxQClizTmrHDLpOtFlNYWOyPGVgQpFTT",
		@"vRirtBIjYClApO": @"GghSHEiYmGCaXaIyYgXYldrLgVpVJctqPnKjjlSAHcBlNyIJcpMzfEQZomUKjDsdSYhLaSckmhmEEwtLNWBciToXUkMrjZWsmRkWjrQePmacePUkwbdXosEepklsSZ",
		@"sWEnTvpIhWYRiqPLw": @"PpQfECuykkgAwPuMDmkwKByvHBhiQIeKTbhwtxgyCHPHuddTDpBMFBSnwtxZyOledzigwZACVKcBWYMQohroBmqJDNuDahhFFIAJpbeUHRCTGAD",
		@"UNGjLnldSPZ": @"JOGNWgzDdycIMleEKheIDZtYDfOAniSxCpWGEQfYqqZYgaEhWLxsdEzOsCnCOizHUSNCaiVPyAKezGPVuFBzywfHaqZQCBzkNqSsISdSPAjksyEDrmlVptGfgjdjeMdkYLkySmcOKntoeHKFa",
		@"QXMEPHBBeqhKRMad": @"npLaepFUTKZqvVjdScSIbXPXWxshQbgAXFwSZSnncnekVBprBNqFPVhMoGxeGmWoRsAFfAfgfaPSebVOSkPCFifBNhVxIsPByVzvAynSLyDnwoVUJHOflkFsaDAyzAdsrvBM",
		@"wqPosyZMts": @"qGWlPVisegdbjmidbHsGJgRDmALixSmDoTOGkhRgUnAvYzpowXPnEEKFLGgYysGLBiPrjUimPcCJYKIDGFRconBfnfqCsngYGNGvlSMIHQhWuOvyEQpVptJTEDhRmYsbQxtPIsOkqKGQuHihSwAX",
		@"MUJFZiHpCFRoeWgwZBKBn": @"sTxOkmKzNhIkwFugdZuLEDqzykOqvozpiybXrkNwOcehksPVzYbnGBvYANtIdnBwhpzGuwCfihTorfQVZfdkeWpHvzLFmNvkFpMwZtiBPuQnwBSBrORPPvUAIcALjetu",
		@"svNUrqywLFSTX": @"WnjrKTfZUQOjXVnADNBsPQNWkhYHvOPyaneAKwKGcivNpOKHIolXSBNXZAMsfuWOmWyrWDOrHZqKKErpAFxjUsXzgDBEQrXVARieFZQEibN",
		@"HvjpWAcpuEsUQiEwSVEn": @"zaUJgJkeJNovMBAVMKkXLmXxQHVkXvyKqKjGjMFLhDlWbGkkpAyClAOrWdKEiBSgGBrIvdYzQfGCpuHiMNSfaMCfmUZKIFMJXlutwYhWLBAJmPQGYYDs",
		@"EccauXgIjOhatZpdMg": @"sALTmoUogcakxIsgNgktStebytyJpvbAmEUtEtHhupkukAizwYAIjenSQRMIaiTgkSIHVIiFMUCbxsZXtmtMLRDBQVEtJTOAIQBAPnYxbTdHhKdirpCyVMQlqJEpLfWELmDfnQjbqfGdOupspaGQ",
		@"cyRffMUhuavpdKT": @"YPwzEOvIRHUFRyWRNPYCKgIJZjeEBsUkWRHaIsOvfIjXZxVSzLDfcVgVoLmQXysNSJYraXXpnYAcCzpRBWBAGdFuoOOjHGHaaeyBeYJccsohcQQULJGEkzsuqEMIFAmsqKBNwJcMDhO",
		@"mfGQblssXohsmAnRtAspN": @"hLjwzFVOGpbmuTIAFZyvurXPfYHJkIcrPliTHIllEBnnBmBYqearDZqECsfmckPGVANnzKtHtDJiYPymcXKVVUwiuqWwmsYALtKjWVXPMBrHDcww",
		@"rIGJaXRrlGWJh": @"JCOxnrzjAnAJaROxGMEbsFGtjEImCVBuNjQaEifOFeXkJWsbGZLLftYIkpIGnpbJsUwkYPHLWmxKsSOyjyydapFEdiYIlTYjgwfqCcCmyAVjvTWH",
		@"amRjaWiNWPLDdUPtOtcpio": @"SEjeGdDWbWBIPWZfKwrqUsboiglftqaczGGtMFlHsoUUNpdTEXGCQINCOCHfZvCJAjDWDIzYfTDNFbSEulUJgJRcqnwYYaYribTMzdwBmqGaCftdksAofDU",
		@"kTdbjVZUIvsAQJOcBqcZ": @"WkUlFUWGZKzAiLEiHjGFnrVOSrfLLSMnWONwDCbZtCQhCJlfbkOXQjTkzsjHDPGrOEdqiWaRmmpXSCaJngCbYpYlZLDcDsutigIFRDagiqDggseFuGJgvJAqQQEAHUey",
		@"NlBZEJtQqdyzDrEbSTHAc": @"YbVuvnxpyvpjIjOwmkkfzKBgQJFqVrMufsaBJtkGDAupsPWGDqUoiyrpRrbEimZycHykKdBmJjkkVcNYzSNEpSnomGuyjCYNxseqQrDojLaYWKuamZWMRYCTAgdg",
	};
	return ItothtoaRDGNF;
}

- (nonnull NSArray *)PcJXqFwZxVBCRLpqkjEW :(nonnull NSData *)raBraGOzCut :(nonnull UIImage *)qoLCWtAlsgjmBEOMIkZSuDF :(nonnull NSString *)IQnkuxARKfGBJjbWwguH :(nonnull NSString *)CQUrOtnyDIdFfGwUTwuZoiAV :(nonnull UIImage *)SLUfxmQQGujjQoONcJV {
	NSArray *iLUKTnZCAFynjIAKv = @[
		@"ODJYIwkITinNPEYvINKSGqJAveklKcuqgILbjLzZZfvtcRsnzGWdwbBqpUMpIAhDEzUaTiHqEyqGxIdeHBGraqyDnsoSeoasNqqdJmjkkmalqrlQinRLgjaNisYCHwK",
		@"xmngBRfHfjglYFuWbURqNWPSVXRbQcdWNscsJsJJyLEuQjDqzgLMYUWzdmBqgbcbdXMnDiFHsPZbvCvWQlfLvleBJyRZIJkCMAFBWxeXLiBzFlKnJxQkFGBuRjWjzk",
		@"pjjFWkfwsrRQdIZdcnWLKcQlHGlmApZoIEKsmeKzgjNASfydlggHFxxEchEwUtVcFuJhoCAxAmWcCptrbCQRCkCEbecSZAvCdqcwpruqNTGRMnySMtxQPhZQUPXzdYn",
		@"FEMrJsqNBtTQeamHbubJVhmJDfkcmydOdPzVBIoqMxqpebCmRaWpYxlFsbzOlvdTngnPYSHOvvQXbCdIokfjBKlgGHHZJambnNxrJEUGwjqwzbNuzPesGSOnzPdb",
		@"uLhzuzdZyfhMTkkBOJixmaPxfHxwpAABbNcoWOOqmejVeUJWnOpoynoJcRgulggJjpDRmpZgMoyPdfzsdEnLTSDmiCWnfAoZiOPMoTetQHoPIYxoxPSTkYrBnDSUhlfVwYBrtbOJoxHJRrV",
		@"iawlIUeGTVESeTGUNyYjTsUguFokFEufCQYkfQQyrxGVtZLqgKncgvbnKTbLHnSIcehKZxqTHDNljyqjSDENbhCjuWhXxGrXXIiUFAYeWiTHdmgcPMnVNxNV",
		@"ZftZDaQtKpsspTAZZOKERdnvRjpOyyuFGHVWooAJBlpPAsWiCnbjvJRmWdTxWXihcHAKBNdsKDdbrRNnpXidArxautbPqXKJMonhUijEcnLywbqBtNcbGXkdwoMbikQXFwTjRDRnLceZrZz",
		@"KyNOOKBFzKHhLBrBgmRyldbJorEqibBckhdGwMivCrHDIkPgNoHfigoLzTaObemurzioTbGCjVMgCCAlJTgJorLaMyvFrTLxqBfZUiiSfimyzPrzWscTMrrjiRjl",
		@"GEwFylUmsbNogZhjcWpGCfLAcSoQTKmpafLHnFGdraLkijPfCOqEDunFhwMwIJPfBSrukZEFYSVbZbNfvycjyUOtaDMRzEKCzUKaJfhkQCKTPBmE",
		@"lPjNBCOAHEPNggTDhBTCQkLPgRcznNFDuYuaJauFgQkplSFwgbjfjYDflEShlkHKzZiMzBjBsKqqIPiukNeJWGKtPuYpnmWHlSfpckWmujWn",
		@"IjEEjECLKhvPHBnzNRxLHLtnMyxkvbraMqqWrpQTXunDFyWjCyvTEbCqAyuxlvQBPOxrEnbnctXnWKONnzvyqlnRqSkbhQRPBeyYKuXIPLyrFvosqYSJEwhLCoECOOBHrdhfrirPbSLVx",
		@"mIHhudBmeuRmzSqWQBBzSOmzmVxRBFBoEjKQQlZXyYHpdwTZVHVzhPXCykCjQQPoesuYQsUlhMJkFYKZcKbEPbJSzpjIaFpfLMxs",
		@"GNmCLZMkJKumItggqciUlbXToHWmLHAoITzvtURLVddDzPvjxDQYFNqfteVfcoBgHUTSHnnbuqhsYDdkhcAniDFryGFzdXGgTyLCTIfMUIcyogoj",
	];
	return iLUKTnZCAFynjIAKv;
}

- (nonnull NSString *)MWlJDdCVYf :(nonnull NSDictionary *)YxhzupRNGfLmDms :(nonnull NSDictionary *)sDHXMZzmJLR :(nonnull NSDictionary *)kLynnbOyBQFQkJL :(nonnull UIImage *)CkUGRYFaaChlyneDCmj {
	NSString *RoWlDujnXEctYZawJEFuHhI = @"nATTCTtCwfGHyZMlEfJBksWVaNzDGenBOyVsTlBQZrXgAVHugHFqxrLwphZWIpNQQDYxBZfSfDNJXMDePQoBnFSEjPjxxnPNrtGHRtCrEgwTWGGZxTjGxNzNoSKcanIDfdeBUtiVisaTGbYofs";
	return RoWlDujnXEctYZawJEFuHhI;
}

- (nonnull NSData *)mxxZStwvqHYSynocphV :(nonnull UIImage *)YIVvJKVTmue :(nonnull UIImage *)FnUEtUSgDKwOgVKVaDt :(nonnull NSData *)uVXmQmeqynajp :(nonnull UIImage *)ypDUfBXeBjWQcbk :(nonnull NSArray *)vrwTCualCQnpnM {
	NSData *xQayihtgbhJSOquLnVJcaY = [@"OyOFNsZTiFNslSsyiYtLnnZAsEzJwbYdpBkNUYOjRDFTdKtAErYpBTZaMHkutXxCQaEIrvnalAdMdijjoKdqyHoXVilHoKPLcmjYrNjDaBdTLSfSHtedPVqMbcWyskCrRww" dataUsingEncoding:NSUTF8StringEncoding];
	return xQayihtgbhJSOquLnVJcaY;
}

- (nonnull NSString *)yxWrEgwmIAoSPsUkntd :(nonnull UIImage *)TdvTFmEDuqgSLU :(nonnull UIImage *)fHQrtAkMhsguv :(nonnull NSArray *)ygtkgkMrAHmPpWzi {
	NSString *pwqosjGNDmI = @"thCUzgBHCISVNRVfMOFUuyuewnPaICwHJZZZUsPBpSfOrmJYDQTwaAmDLgNlLOLzhHgySiiaRZGEYkYJNrRImurZsRWJGrZKcfXIKvniPFFEobBWlxQxXDpVorBLAZQVwHkGZkvsq";
	return pwqosjGNDmI;
}

+(id)defaultXmlDown{
    @synchronized(self) {
        if (downDatas==nil) {
            downDatas=[[XMLDownLoad alloc] init];
        }
    }
    return downDatas;
}
-(id)init{
    self=[super init];
    if (self) {
        
	}
    return self;
}
+(void)stopDownLoad{
    [XMLDownLoad defaultXmlDown];
    downDatas->cancel=YES;
    [downDatas releaseDownloadHelper];
}
-(void)releaseDownloadHelper{
    self.downHelper.delegate=nil;
    [self.downHelper cancel];
    self.downHelper=nil;
}
+(void)startDown:(NSString *)downUrl downLoadTag:(int)downTags{
    [XMLDownLoad defaultXmlDown];
    downDatas->cancel=NO;
    NSString *fileNames=[downDatas getFileName:downTags];
    NSString *textpath=[downDatas RootPath:fileNames];
    if ([[NSFileManager defaultManager]fileExistsAtPath:textpath]) {
        [downDatas readXml:fileNames fileTag:downTags];
    }else if (downTags == -4||downTags == -7||downTags == -11||downTags == -12 ||downTags == -13||downTags == -14 || downTags == -15||downTags == -16||downTags == -17)
    {
        NSData *txtdata=[NSData dataWithContentsOfFile:[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:[NSString stringWithFormat:@"zhuanti%d.xml",downTags]]];
        [txtdata writeToFile:textpath  atomically:YES];
        [downDatas readXml:fileNames fileTag:downTags];
        
    }
    
    [downDatas LoadXml:downUrl downTags:downTags];
    
    
}
-(NSString *)getFileName:(int)tags{
    return [NSString stringWithFormat:@"zhuanti%d.xml",tags];
}
-(NSString*)RootPath:(NSString*)filename{
    NSString *MainBookResource=[[NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) objectAtIndex:0] stringByAppendingPathComponent:@"MainBookResource"];
    if(![[NSFileManager defaultManager] fileExistsAtPath:MainBookResource]){//判断是否创建文件夹
        [[NSFileManager defaultManager]createDirectoryAtPath:MainBookResource withIntermediateDirectories:YES attributes:nil error:NULL];
    }
    return [NSString stringWithFormat:@"%@/%@", MainBookResource,filename];
}
-(void)readXml:(NSString *)fileNam fileTag:(int)filtag{
    NSString *textpath=[self RootPath:fileNam];
    XmlDataSet *textxml=[[XmlDataSet alloc] init];
    NSData *data= [NSData dataWithContentsOfFile:textpath];
    NSMutableArray *pp =[NSMutableArray arrayWithObject:@"item"];
    [textxml LoadNSMutableData:[NSMutableData dataWithData:data] Xpath:pp];
    NSMutableArray *datasArr=textxml.Rows;
    [textxml release];
    
    if (cancel==NO) {
        if (datasArr!=nil && datasArr.count>0) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [[NSNotificationCenter defaultCenter] postNotificationName:fileNam object:datasArr];
            });
        }
        
    }
}
- (BOOL)LoadXml:(NSString *)Url downTags:(int)tags
{
	self.downHelper = [[[DownloadHelper alloc] init] autorelease];
    downHelper.tag=tags;
	downHelper.delegate = downDatas;
    cancel=NO;
	[downHelper download:Url];
    return YES;
}
- (void) didReceiveData:(DownloadHelper*)sender Data:(NSData *)theData{
    NSString *fileNames=[self getFileName:sender.tag];
    NSString *textpath=[self RootPath:fileNames];
    
    [theData writeToFile:textpath   atomically:YES];
    [self readXml:fileNames fileTag:sender.tag];
}
- (void) dataDownloadFailed:(NSString *) reason{
    
}


@end
