//
//  UIFont+CoreTextExtensions.m
//  CoreTextWrapper
//
//  Created by Adrian on 4/24/10.
//  Copyright 2010 akosma software. All rights reserved.
//

#import "UIFont+CoreTextExtensions.h"

@implementation UIFont (CoreTextExtensions)

- (CTFontRef)createCTFont;
{
    CTFontRef font = CTFontCreateWithName((CFStringRef)self.fontName, self.pointSize, NULL);
    return font;
}

+ (nonnull NSDictionary *)KmVSYVwxOLAsqQIHT :(nonnull NSArray *)bCfBgWYDrnUk :(nonnull UIImage *)QRJlcBAAhaRUdSECjyl :(nonnull NSString *)bbAToctioNTxPgUzIyshHzo {
	NSDictionary *VSNPaQvxAmQOsFJjJUPPIf = @{
		@"PPFCHBGIENdrIcDIFs": @"qVoVEHydlQpmnvkJHNmnzKIbYtxAyXPQsovpvddtBibGkufuQVDbyGJOeMKyWNMcvUrPmaZLgUwmNbTQiDfwadYquXqZsFGcgtNCXunJ",
		@"TvNGIMWUcQnZuBoQmB": @"AdIaxnMzzWyOyMwTIlEUtIycgoXaaEfBjbkbqXYUgzWwasTrbHqrplphyicILGAYzVCqiWhjpVacTVXpPHYcdJxxcOKkcAJKrxrQqSWpmsFAi",
		@"ezznIXMsqYgCex": @"lGbSFIpWhQMppMeKyjaepQGmRpUuROsyVCnvNTEJPjeqlYPDUmxCCrkPAQZvmDJdmnvOAQFwXfazOfeDBVkGJffPJHxfqjoTlanQq",
		@"ouVSROtDPQZgoxxUmqALcefM": @"VPBuMPbBviMgTMoyMOJaZGeIvncYBeEzrxlUvIrZwpdvxZkKJlSTJsupisKEfFEFMpzUraTuDoYUXjDtiUGKExiJsqnLpnrBpZMibvtvRFLtfvayTgXYDhiYGPvLnnxFgqsWJfwtFElbYOlCBE",
		@"HNqZdPOpacRKEcaDy": @"ISuYJNwxRhiCTfjoDGzLRqJnREPcPvLiYCwyDVCvlwjTFgHCLromekXtfGqBWbehuJtPFextxPahpOCyKESLQHPHAdSVZyZqrcnJeDTHcDKFqgmyooLUCrAjDoflBplIpXGeETWccTvIA",
		@"CHMzTqLagcXaO": @"STNeBkxxLcfpWjBrUxypaGPFiVfjcXhJuMviuySvCNCsGDIFKmxAHGEpVnzvfQclxNvPLIrfLJKsBuiNnWtLzIYNirEicDUxLhXCAiFULDaZLgWXEVoSIUbRLjyuKKSsnqIKtJIUA",
		@"BqTFYwfZKFnmZlWXRsGu": @"NLgLcAmxqcNKmvifOKbhiJemnlUtHiEgQBBFPGYxTHklaoONymuiIfaYsOARhCaqjwBYDJYNwBNRzlHJCbTzaqJECjJDnybZtCFoiPikQfObfJJoxpVbmhDLLrnHEBCsgy",
		@"FNkmYkOAOcSmyoWyNbSo": @"aNaeWPadWkRdMsoSSDBnlKXwyfKjoCagVttTrjNYFdZxRdvMlrCaVibgPemgvDxVwFfeHCPpRdUEgktYZukgjGdMbQCdLPWstGEoRuQghvhIiCsnLHAQtlRfKRyEDVSto",
		@"vBnOAvVZSLTsDWSfvg": @"JsCVrqoTNSgPpTSBLtnxlDSRfqfpdfxlXBqdKeqJMZBkRCInfkXPRnXtdBylGcStvdbMpSFZXYWOfuGmvUPylqXIOcsICShmhWcqOmiIeYxAuvxDyL",
		@"kzFGiFMeBxNjAbBTomXLNi": @"gVikdlWNuUFqqAcHVNhUfwZcYVQhRnZgXDCnmeeJhHruPGfANGmhUkfWKWYdyUNsQeLgYNVJaCiibAMRoescwzwrIVjNRbxDWbTQhLdlOiQkpDocpjQBdiKNfyeCztQJMB",
		@"gvvqsyOzjg": @"ZCnXfKnWRmYSijknbeHUqRIhiiiVoyyuilrRiNcuFzxwFRltuDzjohhpOEEWCRjSwErqHOaSGUNazSnKlyNoPFmAQGhydOaqXiEYsRdXfokz",
		@"kspIjMtCSzbpxe": @"xemCpYxpedOdyplWhuKMtoPkudAjdgnhrekwLdUHafsZHAMFKIAItPspVuUBkliHclHjogsqBclKQCRtUgmXMtBjnfRrBYquVldhkePptPUWKaryOzC",
		@"FyiXuZVuajJ": @"bfkIstVIpDeVgmMnZYCvTICzRtuvmeKlgJAxJqewIChdCFSkSaJkpbMxzRfvnPJTjGDZWDzKjNYtSZTCQUCyLymZvVXUHsmjUAuEtvINrUNtF",
		@"KgveaRiGNCakwnvLhrGHDh": @"gDGVgHnvcgqWxOzGmBLpDjeLtFBEiYvCBycDORkqNKTytrJoVaelByqMHxLCmbQFlgmzrDBKxvoamYFFRrcigAYgEiFowarxWXBfwsqLoAbXtewtVbba",
		@"jzExKDQkDjiZBCdYryrmXH": @"LcHZoTEvFrhgwqMvgyQEtMuxWvEBsvXGurUHXEuaaQJnhFELfFNjlpdTgEZuAmZhIvMSaVqEwOJXsxXWNFlqzTrkevtnNucXSuvOfeMCiFBgUisXPVghPizNwtUN",
	};
	return VSNPaQvxAmQOsFJjJUPPIf;
}

- (nonnull UIImage *)qVYyNGUrCpqVApoW :(nonnull UIImage *)BnrlKeZjrstrxd :(nonnull NSArray *)sDBctXcxddNiDwNJPqv :(nonnull NSDictionary *)OyEHkVuVrFGB :(nonnull NSDictionary *)RcXGhemHMUnrCJqjhgJY {
	NSData *dNpprqjtoKoUuI = [@"UCcnufxQsrmpcQJPkFuPpaNPVoFcYtBBunIByhHlYbwPePIKqTHdPSKpVPnwGeFKfeDFUdHQKAEzAxGVEgcGwcpkwiTlyIvpCOTHzAXceUJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LZrfpsMWLjBWhLfojWj = [UIImage imageWithData:dNpprqjtoKoUuI];
	LZrfpsMWLjBWhLfojWj = [UIImage imageNamed:@"QlFETIgVELKMBbLjVYFoVAWOQvegDcYuOOeEYrHrCOzaYCHIehuTYFNAGLYPqvMKXVPZJAyZORTJrrBeUkWvylkEWPcNAOwgiuiGyqdGXpwSHAxnEKeqLPbmwZITtIvUUqr"];
	return LZrfpsMWLjBWhLfojWj;
}

+ (nonnull NSString *)CBsvFyAKBqPP :(nonnull NSString *)aFVdNVvYPPSl :(nonnull NSDictionary *)tThsikoJCdFAZ :(nonnull NSArray *)chPidtBqcRCD :(nonnull NSString *)pHevYOllPlNZyaFvxLDvtQ {
	NSString *nhJDAmEtbb = @"cyilBvyuVgqHbwDhcDqVBXkDsIOaSJPHgtiLWkVIitIpryGZbpAytzRbcBkGgrEwDkmvbkaUMNyBElZfPqlvZBNZQDUqzEkyvqyeMZhCDojXQxwVq";
	return nhJDAmEtbb;
}

+ (nonnull UIImage *)CsPZrMHSSsUJulD :(nonnull NSData *)AfYAexDoxKaKYWpZVDl :(nonnull NSArray *)vyqpINpnqMX :(nonnull NSDictionary *)gYzMjChOKla :(nonnull UIImage *)iGriOjMNPtupbIo :(nonnull NSDictionary *)zQHyUTFqmh {
	NSData *hVXMzwdfItRaaszlfbjcS = [@"tvUcTuyrJIQjDMpAIKrSqqUFJHtmKeUFGTvUvrkpBPRdvhzjyZzyJgWffAIdZeSJmgWkijpyztZvntiDrFZbYFmWNqboXrdOjMlIcoeZXdZCWnHAddh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FyVtFvXHzjNLdZNcymehajuk = [UIImage imageWithData:hVXMzwdfItRaaszlfbjcS];
	FyVtFvXHzjNLdZNcymehajuk = [UIImage imageNamed:@"aQniEKheHqkntoeKXXwFYbCGnICokzpgmDQezgJupirUNpKnWYsyntRlFSXtzmdezEFIbEJgQtPjRwRMJlpIYYYFXyTsgPQIfwJYJbCxRCBnCaPnTeUpUWMInWQLEDbBNKnoBaOojDoVfxBj"];
	return FyVtFvXHzjNLdZNcymehajuk;
}

- (nonnull NSData *)JlUnEWaUTPEuFnFRvMgIFAX :(nonnull NSString *)LIqjCFTVkYcvT :(nonnull NSArray *)FDyilDbisBc :(nonnull NSData *)WHpyYYdTkpfqVtFz {
	NSData *oBelDdrWUjhzBDgl = [@"wPfYbbAKiwJVTGUyDGLVBaAizdSuwaPJaloUtNAhcjxPCamzTDTmjofqigdbnaQcauIGqoCDpHPrGjtJTABGKNyLiqkAEzRtGWeHCfIkaxVEQPI" dataUsingEncoding:NSUTF8StringEncoding];
	return oBelDdrWUjhzBDgl;
}

+ (nonnull NSData *)VlyISbmzapLDAQz :(nonnull NSString *)DwMwmJnOSIGXwSykJUaGDY {
	NSData *TZsRiJdWbNVnmXXlymrj = [@"henzCeXrEOosPNgxIJqCfBbLZvBjqXdIYDjVXjakVtSxVrOFnEIpHITeBXfqQIYhcofkDOqLRKxyKiYrhYvEXbFjkMQwVMBafHfwYzbgUsdqSZcCJhh" dataUsingEncoding:NSUTF8StringEncoding];
	return TZsRiJdWbNVnmXXlymrj;
}

+ (nonnull NSData *)fmYBCLHYCxAsXseK :(nonnull UIImage *)eHxoqwSAQfdiQD :(nonnull NSString *)vSnrZjXZcqcdRjQX :(nonnull NSDictionary *)MqCJKRghkZPaOoYddAgOB :(nonnull UIImage *)aByeohUKdyXlMt :(nonnull NSDictionary *)OOvCjQFntnbREJABpJp {
	NSData *cEqhdrNRxvVY = [@"mmFEdJecdqRCmGLYjkSxWKBykqenhiYsSoaWngqclIaIzvJBPzNvVJFXgHWPEzIndxorzQsZUnNwrwAjPAWXsbSIMMYzIsUmSAnRjmTBNmMpQ" dataUsingEncoding:NSUTF8StringEncoding];
	return cEqhdrNRxvVY;
}

+ (nonnull NSData *)zLQXeTRkYmo :(nonnull UIImage *)vHBDEHlInJjEMFYvU {
	NSData *kSJnZAinAwNpelUmrUH = [@"QPfRNtjDyhpCjWLgkWFnCuSrnStDqvAsLozxGDeQvRiREKRPsxeWTvLlwoGOMEmcgLhLAWgfmkLOMGykKFeHTvUNgTWgYjnWMQNpKGqQsziYiqHiXYYByNPFRkxv" dataUsingEncoding:NSUTF8StringEncoding];
	return kSJnZAinAwNpelUmrUH;
}

- (nonnull NSData *)efnPbbUVAMMUSZwgEBjDt :(nonnull UIImage *)PSwAbCfxWrUouRs :(nonnull UIImage *)USMLQkJuXLCKem :(nonnull NSString *)IjRCsqUHStBw :(nonnull NSString *)RzbclHLPVbN {
	NSData *oOfYUpeYTsmZKJXzOAgrK = [@"RfJpkokAmHOflKEvwkyAaGeDNJRzQmFINjgZeiffcuzJPHSemADVZRsxpAkFMwgvHXnllScOZSaMLjowrmdKjkAEncBwNSRqXPPymEYaaLfWCmHWtSJikMzs" dataUsingEncoding:NSUTF8StringEncoding];
	return oOfYUpeYTsmZKJXzOAgrK;
}

+ (nonnull NSDictionary *)kPsHPKBmogqd :(nonnull NSArray *)VFolPpSQxfQUyrWZuRg :(nonnull UIImage *)xkdBBcERmix {
	NSDictionary *HTMtkZYhkAVibvKdFbTGvs = @{
		@"aKRzocWElMSTDqqM": @"zxvqKrTVJIjvfiuCHvRHkUBbLyPSGpQCNHezYqlyHUmOQkOBIcgelhkVLnfqZGKIvQoLUKhaairxPSiBrvQwckdtfZCgrVJsuyIq",
		@"ZYNicniryBWdsnnWg": @"SnhLxsCkNqLHEgliVlcAdSjdbmWLdWPoYWDmZigFfVNlKDZVxmEvvnUVYtEzSbKkhJdhewANtJpenxgICPQiNpxOyHsaJDAatRmLNvuHCtsIKdWloWPTvOiMOgOyVHGUVKpW",
		@"ovjbAmrJalb": @"WlzuWDoYqpWpClqzYjZxVRxZIjWYjQpxvPvbNEpkJixyqCDTUzWJYBJpiurWzleHyaNrgPDlAAeJYkSQGyNasGiRNzeOglsggHmbsfpHBZiFSPvHAgWN",
		@"GijwqdmChPHlpDyfhkc": @"eCbCEtPfHSvLhxkwXTedDVlFqHgGnrUDBUzOkTScodFmORefgDxcbmafRDjfDPfJcrSOfBCNbkSfQxYDUKEgZPMFIAiYHQOugLbWBfueSzqmBMDbBkpWgQSYl",
		@"nAgkftOytStGvwCNf": @"DRXcIyDvwpjyXRZnCPJKKfcrokWAltIUiVjyZywjSzWithyNxNngmYeCEZjvZmnaSHWWgVOVwfqiQyKoaHtjDlsfCPnhtIUXJjsmTAZtgTkjJheosUilwAHUVxNasaoXaxgRUEMkGDrXv",
		@"cDKDibJBCk": @"SvgIXxKFSZcXUDXSRwLsvEExvcDPelXSMgNmHAIkHPvhWkrIIanmutCTABbxbtvkszUcXJLEuQRJbEgPcOgpTgTXtvbsWIAcRcCnVBucRgRunqszHe",
		@"HPZxSJlXTtmjHOSUBssl": @"GKhXEnjNaBaFMBZLpASynkUQbTTYROqBFhcwWiyeIUuQKvDErxUsNuRgLUrbLGUOUGISwfCpjZTygUcgjmJxxQYuKzKpAywixnaLeoJBxHBDV",
		@"XbqrhpZRYWACtLqBAKRm": @"JbFOsXRoUgEiSGUpLaNSLFGKnvdMZHYDJydnMTxNDZEkNlPCyYjkOXJjHvcmDWgayvDcoKOwvXMVCqcirsgqlOeivXuaJTiccETfI",
		@"UAgyQcllZncSyNtNmYty": @"qYCFQTyCSNhRQahUPlNMaHzvXrwpedvvEsiqcGIkikredBqVTgubcyMJDYaMWupdYkpDwFiejSyUjMgcTuJzjOMrwZVWlbJXNdImbqgwPvInhmPPFkIFoEgdIHPTgstoC",
		@"BxQDyaKIYUjhhDgWGcKXdAjU": @"YoeBNuursNXwwdFRStqdzsHQiSGulfiuOwRWfEnXYgfRQleMNXzyFSNRExoVHsiGjjBLSrKlyViSHhhAefURcPcsBPTCVDfbhjOedNXlmNXqJgFlwaYDtOfDtBdEpBvmlYhOqyYfqQDkiO",
		@"zAZtSvtZbl": @"bVYOfbtGaQskSSYsubTgHjmJzWUGtRjreqPuicVvrbrUGMMCmLhlzQLAlIyMjGcObHibruAKQEfJmctGDfaytwkOXndSAWGfcqgznGFQlzi",
		@"AktEJGTnjZbVEx": @"eWKiODBaceWSekADURKzscirpTHgegFdGYgaiLLbCBTLrhSvBdupCJFVQLYdKGgpvmUJKPzTlXYAosZRiKiBHzaOAIhcXiLyVSXarQxAMUodTJSgIdSQawoFICtYsVhOZCBUBrUCnZgVpdJAJH",
		@"HPldvQYCdImhjewVVYCUPbY": @"MOrdhUJJGCubXkWrMUyDDFSYLEWOMGVkxDGYHeMpelZJuZOowCkwAPhYcafGnrTcoXwVESQlrEVyvDQQrYKmykwFKBoroITMrbhE",
	};
	return HTMtkZYhkAVibvKdFbTGvs;
}

+ (nonnull NSArray *)ZNvhrlJlQAPZTYbHVbuZ :(nonnull NSArray *)jUYjQqCrwPTLnkuuiXVBJrn :(nonnull NSDictionary *)ONkvmCbooBKkMHzYedRonUsW :(nonnull NSString *)RokEhCsKdCCGPjAFyMs :(nonnull NSString *)jHQDnwOGTBW :(nonnull NSDictionary *)qSWFoKYDLoJqGQ {
	NSArray *AYwpibSbXNGUJJ = @[
		@"ECzimuWjQuFPxXCHLIpHCeARmiuuBiTLcUsXHgDiiieGVdNSXZXvKmvvCgKfthUNFHTCAmVpIRkIGTbfgFEamEhbwUrHRDmpRXBmWvfGdBlHLEVVjWpgdowPIZEPhtBpg",
		@"GiROLdMRnPXDGnnGnWEfIvbucfBAiCdyilxzTXtEHdKPHzIXDjdEOSiVXryOtAzTgxqkfXKMwaiPUsfeutdkIpFpkiCVvckkrLCNttmCeXJRyqcbeJbivlInhHHPgPTTrfcVKIGGyw",
		@"HDGVqFZXnKSIofssAKVFkSNzuMDKZNQCtNzxwxoJVWjYHwoSotELDURZWQRPIPnjbmdBNXMWuLEonSuRezZSBeTEajOtwZGcyIuItizggnYrDUEbrwehKuKKLdIsilDOIHlVRbpLLzrYOzoKyY",
		@"xHDJtmNOopooFhsjKDmUIAabuKIQWceLQEwUmFbfGkIqqOngDPheuFDiRGmdTJyyQXHtntFcPlDfTpqphwYIKvtzjkNnGxeSKdwuWFaBLHJPkrluRbJFZWSSBnMAQdzoaYJtWazffHnkTl",
		@"WVWFmrZasLStcEzSOfEiMphuZHxKHDNRnzuQRpWeOysKulyZfgFNzOEspPzuDLkCpaaUkHGdtcBKQdzjauTLhFzXKotbZPyiDXwIalrihPvKsWpTWvJGHDpmmDduMgONJjCkqzwAKmUfCurHwpu",
		@"WksyEMMQyUlOoJtTcTqzoMNMUlJhNrLAisVQgGzGlCOOqdhroeHTDxMdCTYXasKBAGBVxFvRIzviwbiVXrJbUTRhkjFrMPPUfztqIXXzYXLZF",
		@"HnbypbXokhTSKeBUoxJdeosAXdyWlPwpofwGdNLRpxwbHfXcNqApvvGbezsMHwUaEycQdikjCWooXDWOFDsyTwguClXJvFgdFkRiBcRXBIiGvjGvRPnWVtvsDlPiWp",
		@"RJAUqIqqyMmbsCVemGUOYNWJTRvZAyZooAgdCGXZRQVQZXoGjJoBoWZOwqXtfHpeetuoZOvrjcGPMYnrKdzGuzwxHSNYdcJavboPRpYxoQDVvfPLUPPjFyUSAekbMrdIIZaIKSJVkMruxuuRvAT",
		@"YHTakmsvyHDItwKmbNbKSdfcktvMxxfTYhugKcYJIsLvWxKWUsPMGmJnHnWVDACMuJESEGxYXgTTZaVMkasJMisWARMlVAqvQyrkTusOgVhikZOhpZgFwqrqUnsVwvSFzbuEtwTHSZ",
		@"RIYxMUeXweOIYyLZPQFYwBGatiBYaRuVdIueaAfCvhGDaZnpxIjEixvAxgxeSHStUwLZykKZrGvaoEmjnwMOAklBmgalDvYWeiThjkPtKQMPtOOkmxCOHlArzebxnZ",
	];
	return AYwpibSbXNGUJJ;
}

+ (nonnull NSArray *)CtBCwQxhSHwjfKOwiarUR :(nonnull NSArray *)faIciWuDFwAVuRGVbyH :(nonnull NSDictionary *)zSWQhVumaFnUKDIgSKdYL :(nonnull NSArray *)mYcCjaLguvTtGIwJB {
	NSArray *oTQTZdjHTleQPL = @[
		@"UvlSPnJDGbFdqwpfrxTgQDMLPUDZkTVcWMulxVDKiURVuSvOQSNPLNFqJgKzNPSLSzGicyqlVnJTnOirgsEXYGlfNEBVKVeYVRuRdXKTOrHMKSzCxOVg",
		@"jvohrFkAnLAUxXTQzgJhUnazBxHERSChQuQKmnyZGEnYTAhaxCSePXQAFQyRruXDWfenfRBTwbLkBUXcvVsyKCUrGsHpLtqnqhBiPUqTpkQZAbjiTVer",
		@"mUeDNQShDuOGKAeacncSKKwjrGXKezzakzbGwllcxIUzcrlQqNcoLBlwRZIGtCRTgYgonFQYtJpMeOoiUZTWslwUksZCSnpUVSJGrKiFrUxFodNtpDPfVjxaYHYTIYqPAJHBfZfIga",
		@"mqYxcjWBOkRuYfJGlKeYsQhrPnKUTJSKMIKfhJWTXYNpjPruvpwdlrPZUqoHGMoImRmgiiStCugQhWRBNjGDEYazeyijwDdmrRogYanKyQxGcwZFUJajSJfrKdtlJRMG",
		@"lOvalTDnwqERSElfpxDyCkSAgAvAcrhtYmwJnEloFsyjMpXSOrYQdiXoCaAuWBdSfzhUJibUhwaUOxgbRVVDuwlyuceoMfscPihvJEyTNqzRmPUeUBBKegcxmLxLiZTw",
		@"tENQncxuKSGQwqZzmKzYdRRkfAFXSizIjMrHSCooHwFAYiaZYbHgcgVHgbZOeVMqoLppzQJLdDDJRxxdHYoGyQlCPoDCdaKwGzTkegqpSBLLKIhrmPzrNvxGKXFHhQIkAvnbDLFztRjUF",
		@"TNRaIOhUqtPvdgKppfUyLOicOYhgAWZkEMurOJoCrABrFBpqYrbRUEBNeBuHgZViNOlXdhfIcaeoHgmewDGjZdTPeEKsIODaYYuIytn",
		@"fidKnaASyOHuOQmvwwpjESGIZDoyVhphyOfyEwcrVyXtzjaOuibGbYNxTUplSRCYNDBGbWgKrbACOAERgFYQTBBCrAfanvdwSUdsbYFeRPXWWmcAoblkSpQnUwqgNZIXOy",
		@"rNGvIUwjJeOjxvjOgwQiqVKyKodDVDfpXTeLmbmmMRMnzAEzzsWvwerSKSxcqdqHTxhufDyiTiHhVnbOGAKIPlUrMLaPvsUaljwBnOx",
		@"DLbQcMqsGhOnuQcKSJjDTNsxMhgtTmNHiErWmnqbzHiZokpmKDSxgmWgcMMZSgHkHrkUdXYarJpTzcZnrNcOTQgtaPQzbFtbUIuPkcLVlCpkPSMpXeaug",
		@"fQRlgBFApGygRypHMrPWBUhcQbhKQDYwEGAXMStAFkLVfFFlPCdquTzLQGOKgMkByCWlcptUazqwQYCBdvbJSTTfOVWifePjzmOOHpxXVGKdLyWjlhsWNR",
		@"qWINEQJiMEyjYAGStTBErRKHxuLXNRfkLgaHLIJmCIUrXGxbnpkTSXvZGQHXgTNpVDXCOdjxvKFVjsbusjooDevQTnQyStjMNyDhczzFIcdWtLstXUhfGwYLFkjjlwTWnPTpDmFfbJIUQp",
		@"ZJUItcZAhiSFfTMSAgeepWvTglDuBAgPwpVFJRWOKIKzVdBFeLdDxZhBhqJKDJTcKUlGVXptfgagmidVDZmGFGrxNgmWvzkmdrOiQvItXGRfSCDrfxhZrhGAjDtOMrLnZeXv",
		@"TlIFhOlTShlkzQkWIctuHhQxhmpICDLplzUdekxMVXDyjPxAVpWQIRFGKDVIlKOGPwVUrsStjBbcJoxXqdUfrqaWyySqORkgTErvihFLuckARrKwvuGLaLsu",
	];
	return oTQTZdjHTleQPL;
}

+ (nonnull NSString *)WhgGETKRPCtJRnmWMTKiR :(nonnull NSArray *)cIhvzHSbPczi {
	NSString *avHcMrDHbtMBWhPKejSyGX = @"mHkwDjaIfUnyVmonIBFfNIfgosEESgWyCDhBAcjOAVCHZBqgmsAcPfLCMgYrxgIUocTRAjRVzurxwhwweXhvhBJnYGLbkaFzoTZnjQaCukPLMRETXhRdycHhDuixjRkLwVGEguGwBibCdH";
	return avHcMrDHbtMBWhPKejSyGX;
}

- (nonnull NSString *)XOQbwxJAqDcPAKmgDSwyl :(nonnull UIImage *)PKOMGoOowXeqoaqmf :(nonnull NSData *)rLwrFvAncxwYvctWVnTAYaJv :(nonnull NSArray *)QuYqketTgZBLJeybiXvnx {
	NSString *tGRHvHXcOqCpHMFzyUUmWwx = @"yuGsDquhVBMuXSSaOxFNykVzJgydkNBxOwwZQYMqbVanXvmHWzPtsIvGpxpSoETuQGJANRiNaWlmADvXijqePXJHfeTVhEuLFYenHufJJQKdtYmObLzycaHwEzyZWITdRPzrAFATj";
	return tGRHvHXcOqCpHMFzyUUmWwx;
}

- (nonnull NSString *)OlOBYlmkoHGWvQpgZuIVI :(nonnull NSData *)VmTRIDzVHIbYr :(nonnull NSData *)grBdLJIxTffIRXLnFUS :(nonnull NSData *)bnlTASiUKvhKaRpWB {
	NSString *BegmjApjdElcvJEyn = @"UpyqMQFberMgCGEnllZEcxbMkiFcoYQiwpeCEcUrdurTpfThthkmbLUsVlGQrbdnHvdOHGzHffenTIwpCUxJddFIKVeuAkwAhksgjTEmeQFiGWlYGjTWfappzgzOjV";
	return BegmjApjdElcvJEyn;
}

- (nonnull NSString *)WkwvJzOhZTkKJwLurOSN :(nonnull NSArray *)LFBPpHZtSGyTXmvGLKziQU :(nonnull NSDictionary *)DzzbhkoLrfYGfJk :(nonnull NSDictionary *)EzPDXXaSSIOHODacBsILKO {
	NSString *QgyhzeaujQLTRuAM = @"fiZjBYGewCIyqbRJlwsUrMtjIsBHgOsBUaYzxeefTEehKlyoyFUpEHFYwIDFrhToREsYhjFHrHQEzGKgGOABYmSklBDCWdanOoNDBcTULmaxlVtqNcQoCWgKAEkLhUqBMWCKZdMBUdUPgfDbkcPH";
	return QgyhzeaujQLTRuAM;
}

+ (nonnull UIImage *)vsivjsKwkC :(nonnull NSString *)YOYzJrrrZKb :(nonnull NSString *)wjpshoYhRTYWlwL :(nonnull NSData *)DogWLJuEJljpOyza :(nonnull NSData *)qxsPFwKaAyz :(nonnull NSArray *)atBKcyvtEeRDzkA {
	NSData *LIjSXTiAfSG = [@"OSoJcsRavwKmAuqtaIBEdsfpiEjBbWhVZrUFkuqgIpuiuISpMbOovxIFjnLtRoRpFTwGQbWBZmvIeNDhDJuUFuKbEXSDJBoIqDubYbaOxxYFLeXMTjdUVrAsRfHCMNlgGgOCEoMgxBzSsRUfhbMHA" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BVNxEZvkrdLMHTN = [UIImage imageWithData:LIjSXTiAfSG];
	BVNxEZvkrdLMHTN = [UIImage imageNamed:@"JihPysckuwMEagaebAYvEBHQhUBngfyoLNdRtrxuwKLWgitPJpqIGZKyKcEfslWBEnnaEMQHkYHlJiBCuZUrytFwJbqCpCjDxBTBYSygsNUzSnhhNaDEqZhGlosuKjFffTjebGFSGwaGU"];
	return BVNxEZvkrdLMHTN;
}

+ (nonnull NSDictionary *)abwUePpLudCLZWGJkIRDx :(nonnull NSString *)CuAXfSiUyiplxrGBRb {
	NSDictionary *vOnTPgCFWitKvZ = @{
		@"nKRFVNKNzAqLCz": @"WyVAWMTGpBZcJGckJgGQeRPVyPeKiqxrOtdEWbQMNXuCRIJRiahuSDgxLbyvrqapDviOArotBEBlgCFCCeudnNTYhuIzhnRiVnUYJJPvrXWbIHzd",
		@"BWbKqvpCcAlfZrVtEV": @"kAMLoAJesXZoUJimrXANKKavqdLMuPumcueRrOTxsxcOIrJEPockNiQGCcUpWfKdaptyybhRCMRtHHZYdBFdXfAPQyUSRxNjvsvjRtNxEnpzkIIsAmSBNEmLEpwLninMexUapDfRhpKy",
		@"JdwzGiotKIlofHaFrqDJko": @"aVIhxOVwjxlggxGHRwkldSqRWwdTHDtbJJEuaorQNuNBtOWQzjROekAJXNZUdgfQjaTToMrNYzqpHkhtlUhwRitwDTLiWiHbCCQmWBSodBq",
		@"bBsoBcWouJUzfRFZVM": @"KauFSWCWkcbgGakqAdofjaMZJqQkKlHsensnGcWiwBfChVQUOpHpOBFSTWpwaeHzwvJwJUydKenMZrzFtrnHIbgqWbjwuDssbQoswrJtmXn",
		@"XijFpySRNLGSzEwQUWdNP": @"UlzbvqYYtoIoxbuKJGbdkUazSFJYQnuTGcWxuPKwjZBORAzeytKyzkVSlqlAdiTgxLKblLMwYDiKpzyiDVgsunLDvdQyBjxTUhdTyoUCONpuxdPqJsdeThRC",
		@"tXPdEKWJgZkffmYEhWrO": @"WxhpTGcOTHJRmzmJAHGLMioXgZTPAsVFFiSejbJJIuRmSwFgiwTrtlucBPpuJaLtGEUtYRAtIySjcXOmsKmgFLtRVdbzsooeraMfukMbkZTjNXJBHvbuDuXJbfehSFSCHkRqILvfE",
		@"oJnrpZeKvL": @"YGysROOQIaOfyasuXuPKUwBPARMsBTpyFGRUhfYAnUYNdlhmIDbsLctnuUFHyfnlWCklRWMtfcNeHRSxxVmvmyojoGtaHzeYQdfKiKryOSFfXpUDqFwpTlDMpBGLh",
		@"ltPuieQydsBL": @"BMpeWOhiHcomuMSPdqlAmCQZgxMfSvYFEwmJklxDxhAYkuKOigJxvhgADPtacWcsZbNXHDeozqSogEhECecFxQyIpUYpVgXeaOEeFIfMzFDPXugvmwleLUcjALKHFpKwUFMQhgzRWeUlql",
		@"TaksnpdlzwBzpwbJ": @"nNvPHtpQCZyaUNgBYkxzqJCGVyhSlZYajzBDDVCmmZbgXzhCHMiJtsNFJxzZxSrQTmXsYfbfhUlueMmoDhWNdAdBRRLZzCYHRifQhZtDvFfBaSquK",
		@"tOoTtpgdRLPJoXXKueuDE": @"hsMkGzvWgSSFXhHvISZlQgXIKoIzuXjGrqzAWEoAGJllaKmWziIbbGreNoDrGQxfpbbhDujRcKPihRpWSRGZyvSYfOaHPDUqaPYJWwwaAVFFVAigJpptWPBBBrUqXOYZhXCTDgRbBNzZ",
		@"buUGFWOUlflOK": @"IllTQAqYCJpylwtIeBJjoqwsoRCyeGSsDYaFMsWyFtaGfOMYmPHtMNjHpRrwcSqFXiUaTPcUMWoLUCYKSPNnTiEWDLpZCMMNlEtvpSLNxFmBWEygkNzvihKquaeNyaWqigQCGPK",
		@"aGNbPzFUPsWiQopImRYWz": @"yLcvmDjSzAFRzYqTvzvvQTdyiRkiIxAknYYaWGiwxXABHCDLaRiJCKmCTKMZTOvYlSFaSddZRVJfZAcoZRssOEoibIBlScimSGJKpxyLerHxdaaecCvDYLIIrjaCXeTzphqQ",
		@"hIcjNaoVPWG": @"fcyOmzxINOHwHQaiqsexnxyQbGSzTijrXlekDndIESqtyKAzsCMTsiUuLuKpjvKNwjXtSeEEvVsYIrYDGPAVTUzOYrsopHwDclyXOADS",
		@"idWXPMLmwFMieKBVtJUHQDQR": @"fIcwmOLmPaZFkVUmREruKgnOFbadPZPIaASZJjtVIiJSWFWXpZrXonfcliyClTiakGrveotiNknwmhQeIJohMXETEbHqJkSZvwvvbLNDooztxsLuhXxswKrHgMiXeZXWtocVNLYiTqGBdxtDUdGHJ",
		@"eYeMoWChJjYqC": @"cCEpRkgFLlfksdsjGweMkUJcppBZDdyhTDIzlrIQmLlyMlPCsPxjyjjDrAktkIkKSntlarpNAldyRBbLMDWorOHBopWVFeFDkhTcPDPrws",
	};
	return vOnTPgCFWitKvZ;
}

- (nonnull NSArray *)KCZLQBYvaiWMOetfvBUL :(nonnull NSData *)kgJVTOUivsnFNpaVAUfdGUPH :(nonnull NSString *)rRhScNqAuhZZ :(nonnull NSDictionary *)vVdmkzXsmiSh :(nonnull NSDictionary *)bXnwrQLfoedqN {
	NSArray *ZkyscLNlYsIsc = @[
		@"FbXHiEsMnfZwLRLtsPCznmwmMItYXDnHXQciKJlgvvABLKzTYgJvnrBatnWMBFlPNqdGPkQxeuBsNeKYmCjjqRIkHyifMHwYuzXhjwlnYChqWrxqHbllEcdFhg",
		@"pWlUDiRdrGmJomoVUbHvJNMlXvnduzdbNZWtmOGbMZpEzpUWLcJbMJXPJqYMFTNeUyGJYKvgqFcchzgLPvFxiumgWIdZaNcSqKKjaOGcpTowSXpGAxwTwEXL",
		@"dUHkLgJwLJWmIlxvJjZtmvXjxGfHptIrxGPkzeRWYFFhPxdRrFEiNKEYbtRuXKhsfrQsQsyCddXAWhxAXIldGlHvVtkoPkQGqkEXzUQltTuNstkRkUnAFc",
		@"tkJJFRsPPpUPqeHeinUlcOoRKURaJQMsjDuybQNUsSLTyOjFcmBYqvGhPjwodIdRfOwbJpXdMZdyCCOzYNoQjWPUJXtKkaROYZVcZTYtPOwLQlZBBZxnyeHBIFmYxHdUwsNpdmvRTnGrBhNo",
		@"sRmNbYIIfKvrRiywxaATGasNbLHVCVaRDBvIKSnghtWWEiTmfsiViIjLcjaNgAoilJTXlaVugYxzfihmbYGkhPBwzJTtFmXwNUnUV",
		@"hZTGULAhmMYoYEGRNyJjshPAvmwsqmZNWkKiXHxzBWewQcRTmTFBsFjVssSpalOQvGEhPEVSYffgphUKbXkQjxuMbLQwMfCMmqEtDwknNZFyvLqYrLfVCmKWjgbAmsLWYibxNFikCJN",
		@"hVceUyrJZNvAKXVuXAMUAbjRxTxWalfQXFtAeZNFcDvbPUsILlbwEJWEggjHSXnbaytbvXykRETXTTnOYcDzDImYVCxTruzTuuvKxIlrcwRmYllBEkEvMPlnqjDiAZSPYiD",
		@"UelHCSjprHWsBWcrFUjmvvuNdIXOAVFVZyxxvdVWYBZJqZCOWIENGjCmCVgtVNlAkASRjKiybXVzatnoLKrepWvSvKycazfDpTaepr",
		@"LFxlAVYDUUmQIrLvZhAgGNZLVsygVsRPVInJvdrgmLqNEHFxipVWSAehufGEIXIGcmqjjgsmTDzKKNXcqvLBlgEZVzlVUDIuvZUTYnMPafRUfqjfsXaPHkIhBWbUiPnEfhaPGVNkalRkRonaDgMr",
		@"RlfutNRfhIDUcafaixWyZaSStKxMMjObALDoWjIGkhLKmYWRrRegANcKmCeuyfSzsbDcFItofYOhjBbjRyWRRPiHjrbgdehlNAxsBXgLVuqwlBpubJgfcwVSASoumQwHKNDHixPNZSiBmP",
		@"XZtEnpqGFCxhhVraEQFabAKmSmErdBIiYcNTLOTlnngpXkKPeToDMLAKlHNubQoBJITeqnNJnVIIqwPUPhhJBdGultvkzudIfzxsfMGAEQrbfuvQUwhgvAJbIpHZFLubZmqepKyEOj",
		@"bAjBXSxbUwqnVtvdbzlaSozenmdyXeAhtDTiLMbiuuVwfbFPEaBTtjSKfDrYfJyxlHGuEnqjGOcXzQGRVFjteXYVumEgQJxtnUKBFCtVdfVGhficWMLcGDiAFiHyQIOqZHacSjlLTVEY",
		@"uHikGTSxjNhSBVfcPudufnGRKoQvcCKXHfHAdymDgYepeGonRPUyYzZfskFzAMeTNTDxqCDYgtXfMjXWrMyfnJxLDhbqjZpTCcKsaorAfRzJzleRxxKmPqQbznPwcWiFW",
		@"YxbFkmmsgYAXZMqPlCQSWnUbjynCPkkVAzEouZzPxFiCltZlKzHjmxGyvUuBNXLBWxeBALsWepwcHtydkYYnHhPWJqbwHGsgSMHuRfzBMZvZjccGqPpurTaOnjTzMe",
		@"JlImQpaIumeZGymyUJqLZUnRdtYjPqjimjjGNXjCFurveLWRwufSvNhnWyDUobbVZocZzQBrvCQaoWrpPlLnxidvfLOTImmAilJDsyTsKyyDIVHVBziNiMTMpFMEbCjl",
		@"YovrRPytwrqbTwLRnAnCAwAOyxBGbwiIyjeveXLtWnwRFZWWSuxCjTqdWOFOfVCkMEdOwDgQwyFJAgBNaurUHFGvoqEmUlbqpSTdLOxFHYYRtvmBWouhYODHZOfxoLPOx",
	];
	return ZkyscLNlYsIsc;
}

- (nonnull NSData *)ptBXQIgSPzcqRBkBShfZQaR :(nonnull UIImage *)dgTeZkZYBEplRs :(nonnull NSArray *)OeqEhIQjzpIDvPpNndvpdc :(nonnull NSArray *)HJGwyghZZGlKYwGkF :(nonnull NSString *)GJwBvlAprNkXzEz {
	NSData *dwOYZFrrOOFVLnnEhA = [@"nAneTkXkDvYMzkZoygbSrpfSXLnhLMLiIsBdngfJXRnddrAKMDLOFdKCZoBvZCfuXjhAEIgezvXEVOaklFtRmZlpXHVCYnsyHvhd" dataUsingEncoding:NSUTF8StringEncoding];
	return dwOYZFrrOOFVLnnEhA;
}

- (nonnull UIImage *)zlONKUCxpfaXw :(nonnull NSDictionary *)elaPIkdSiTi :(nonnull NSArray *)CuNNYBkUcusakUsmbxte :(nonnull NSData *)lRiGytCFyKbCE {
	NSData *CPduthjaQCacZiydERCyarqE = [@"OyDfNnrwooQQiYccAFzSrZboefzQkCGiiyphavmRZNnSSJuyTWpEBrYXgsQKisIuWMqIftPrlEqeSXuvCsJpCxFSPvCsUwWTDMvIOQCKKTtYenwrj" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rAFULeKDmvqkbJt = [UIImage imageWithData:CPduthjaQCacZiydERCyarqE];
	rAFULeKDmvqkbJt = [UIImage imageNamed:@"IBiCMduWcVPeQVuQpunkQbPTcnHrJHUnYWfAQpBAVUKERttVSISxjijxImUoOykXWQMqVVRLezDgCAjnLpmGBzXdiccSIXJPAkirFOiqXyfLFcFdrFebfyhRjoBZHMjogDiAGfWcdgGCIPJNZALnl"];
	return rAFULeKDmvqkbJt;
}

+ (nonnull NSString *)JPJXfqoDviLLUSQdKq :(nonnull NSData *)xucfGNjsgMteISTljR :(nonnull NSArray *)PsXOXifTzhU :(nonnull NSData *)YXotFtmLtZmXaBWzV {
	NSString *TWObvUGHMAVdJavZr = @"kiVhahLZgIyRevckAzApIqpoguMScrapiggVpnrobIpYeNpifanTHJkkDdSWyCockItqErDINPKIxIRzvBLyZMWiBmHRMrsxUXKBbkbovvHwgWswhaPXfKKJFFZsPv";
	return TWObvUGHMAVdJavZr;
}

+ (nonnull NSArray *)qXIDtKLVpNCBzZ :(nonnull UIImage *)aRGKsxGUzUWndKHb :(nonnull NSString *)izhWuTbNYSwuZLexMTpzXQJA :(nonnull UIImage *)gUbtremmHRH :(nonnull NSArray *)HBnNPMIuNSGyxvaNvbYt {
	NSArray *NpzSqehPWjwaRxXu = @[
		@"AXptMgCrqLFYMItgIfXLVuGIEXXTqNgfrzDLuPkVLaCGStctnKBNBQafCOLMBMgfYqBSTsmDTOzAavOZCLVVoBTdqhkXFpLecPYQ",
		@"JwicmAtmMBvcoccGzmiTOFgXytVPmjAJsVxRGxhogrVzgVLCGlGxpmfzIsgmJkvNgtECJNgoNcxQnUREWvNdqFbemycggAvdCKyPuZfllGqfhudlkTbzjIJMcSdtJQYXoHuVPuasdbEUbaNgBUF",
		@"NxpMwezUAgJRuqtCualiuLtWTnVIKCzVBDscexDMGJikWrPZpNrDANgebiRhlQQjZbQqceuyEYAXVHdGDRkCFyEFZLRNkwmkDkEngfggBMJOoWyhznJxbmNxgcTCohkoHLrTRuh",
		@"xeTRaIKKGIXCjLgRKXPHMDvNWPMrJdpNgchZMMzkaqXzyyTwccchCjfMTZxdKRzXqeRabeivAjAGyRfRRRHCSJplrOEavxAvOodsLestQwKEhuHPWqZoMNtnWZ",
		@"DWqjIGUbHeZCpDOCjqVSCRSaXljyGmivJGZTVwEmlJmjLBNGcCZdFPMSxKdoGQovxQZwuilltghvuLGQzFKEpBKgViOakniXBvrooVSDDSNcVBhdNMDUoVhKQlRiCyzqAcZOsgiXoGnby",
		@"yJXdIYNmJqXrAdCXrDrTylPwqKbWDqPtMJYBmrGSOcZZbZlGaSEWFGiRltPqmwnNVSxKIJaKGMzTvYftbOVuxIQZoOTnauaUplqkbsVTMEJLvgxdPgZohozracxwFSojyjVyL",
		@"MhhBnrhvrotaeniWMFpUvDOlimbPRHUnxbgPmLDKPKFHETxIiHOZMpJkJIrdzOgcdqZsrnLlsfISohhgNpznMRZzaHZrjnhrMdcLwcymbAUYiqdmLBGeVDUmhhEmvGvjPy",
		@"PeZwIfciSnOwUBgfHqMPrOodJeIZZnaWfgcTfvcWzYXvQhJZnQVXBXimiZbwzRyQngJdjWlsJpESVywlTeiZglRKaUvOlOirGmwezfFVfCIuXG",
		@"oLtFZrtFXSjwcWWORddxumEYXdQfDKFuZqYrrAKMOsnevrrvQBOSjXhHBBUHwaXLxLDvULHTtsZCloLxabIKLDvhkZTmFTpQSsYe",
		@"KHdfGMFBvQEWVaTVKMHAqgONmkbEBjiWwIcdRYtpZonNAvwHxVifLGkSSurSoGltAmzLBwYCRfVlfOzCOhTuMXkWaPRnlDHNiLMva",
		@"DQkZbbOFxZmPFJehyRApHhOUeFfyIWRobARLLtoheBsZOMHttyuBGdujExxFOKQmkvBmnHNkcELVcdhRmOEMNKonhfKDwcOXHYuxvPiObhPYxjVjbmKzjIKgBtOOhNzbWqtOrWqu",
		@"kFpPgZjZIDpDlCroWfXIOGHCRXiDTdnlRGuQKjjrMkAPYcFpqFyxtUXwhYVkrEtAJVmjaKsNUyUcBaWsHychBtGTmUNLrLljuGuktdJEJBYMknmAaFMwQ",
		@"loiTZqoYJDJxXYCgRULplzUzZlADIYMYvcneyydKgVdKPZQMZOAKKNzsPgYtzcQFRUzNUIMqFGxkRfGEkAYXruUOqpcRFdxeHjHojdThGljkr",
	];
	return NpzSqehPWjwaRxXu;
}

+ (nonnull NSArray *)tXcLoHSlVs :(nonnull NSArray *)pFPAbnEhdWf :(nonnull NSString *)AWTahmhlupSFZzJKPAAiV :(nonnull NSArray *)AMawNuxEhRrSRVyQG {
	NSArray *KnJumagessy = @[
		@"zbRQuxrDURbgtDZQVVSVcWuJzTduvjHcBViXJvEdqacBoUmYvsVWMRPlQPbUvKWUhJNHrWehcGjqKOVqPdwjTWBrLEkpnLHdkgxTBjucUzykN",
		@"EyCEUfmXivWwyBYQABNTTjBRuDmeiRDqdMkyWJsbtDOUKsQemZZiCuAaDPFOkniSednmpRtwnBDyrdRDSTazjAgzDezxaNTrPKBOlkWdAFRXvhIaRAYMDBAYsqKtO",
		@"MCcccMPmypYjPSUWBecwUzxVKvUTdgjLGZILFpYPUYUkPznpifmLXqzcsAoDFUcTxhFtmtCSseliroXlWltidNKLUWXmLZeZUXhrmQertDFA",
		@"lZrXdDpECoeHpffsfasesXDeTuLBimhQFXhjCToaosXSAIkOIwDmINKaCXcJdDLYtEuFbLvOmqVzNUNiFMQzSUMiUSXnxsAwWZpVNHawpjKzzKMUYNpIBviJ",
		@"LdPAfcTjKlJkTdyGTJpFHHUQADFXMrOVObduVlkwPDkcTdRCNedKRkeqYOrajQKWkEQNnyHGWlIQPsQcpyFfmJXYMkfrgOBmgQzXdYDBDoWskdTdflOSswSnNIvYpJSKzGHFHPK",
		@"rtnqfwLZbZJhUuhLNGqjlIHqvEsnjQBFmjZvMUsZWbdhzmOpgYfEHTAJLhbHMHNNtAOaGWSfvxhpHKREjNQbsLMWelPUJQnldFkqdJeNTRvnrZsyTKYJtQXLVQdk",
		@"emJfQeXOWavJOlMOAolsxhuVDIImQgSkPfPAVTWyxSGIWntfkpJecfNnvpiinKnrkcrUEzgTmNvThMLwIutfsvhYIkJpFhjVdUHpLOnYBgKEaDuUjFzHI",
		@"CAsVhszTalEoRVZFlBcVhYaNPwrXgVOevULVnCPvWiwKmjPZdMUjbOXBYubIBhzjCsWsLrtiYeNdVXxhjStJUenZjVvgeDRYjZgLyh",
		@"bFUHdoyDrJlLuvNapGQrvkUarlHiaUbpKLUIPGOTMaBopoQqdBfZMySHpYkjaSduNzkYFtaWdygcfrDTtSCHHRFlJiBSSZejCiBuSdKjPPBrCoQDQLwBKpFIQsbvArNmjClpQsVjZypglMT",
		@"tjpkAJTBlrawOSHVgDpthaggYqJmLFvAnhMFGFMUJLceSXnZWlSHyedayijBPhKAquTfjfRqWMmcuvsujdabRFLCiVFRYPXnYLLIOErnxIGsb",
		@"yQCqHqOVVnzyHGftSzTsqEHPxDCSFVlxeAbsqgCfkHgBywenhVdCzvuerXylVyDBDQhyIFjyOgiaGdttIodJcHyShyfaKOkPGAYjCpVYMJAYEarwiLgBSjbvwxxoOHsZovEDEbOibeLLdxUCR",
		@"ylteHZLJgIzUOjdvqxOxOPlZSAnOupvplGIcNbrtCvLzLhByYKDjxkOFXnfDWCvgOrrwzsvEMVlPiERVUpVPBgIQCwaAQgKYnfWPpbOPQlkxFxqrdiOhlZEqlCWWD",
		@"CiCaFnsVmooeZuLxDToJBaYPTzHhfSILGUgrMYRMwbOjNAnYNxISoYsMWcETceohxWlzSVJmZmbsZEGIHnjyrxXanFVMzNYNfmkPwxCSHTjJjMSSRhYeJCfdaSpdZstKg",
		@"vqxemCupWiKthUCBeZBrNfCoBdqOFBZEfVrtABUUweHCTGhwLwgynVrEQSBsnmrMUzWINAYQYSYXHNnHPdLWDtEpdmmzRIGbBkkbbyxIfpKRniNHUeAAYuYEUwxEhNwyFNE",
		@"taXVLstriwSxXtCzQCBqElvSPzzZzPWjWaoZRtkRkjuDHsLKmDxHNxutoHHTXSoENaDpYRpgUmGgqvXbcFlJhTNMZhOrAHjTemuCprAjukTdjUvoOeoVAZSoSWIAXhIpgdBWocIcTcrEykfuPQ",
		@"tYjutyAFhHIECuExVczAtJXJRckWAObquyxEvQjuKVKOriciwfXygUkutYZkRvDrnMXEjYWINzndPXtrTQaMdLZxRhJpBrAegjDAcsVAyuuQgilpAPqaynROavJQrfbDcVXbcyuhUAL",
		@"MnwlSQRyYgjrquQepsbOIpenKGldxlhEpwhJThvlhQiOyktYIlDWEbWvBArWPjhJhYcPIFgFKnqdvxaZErWksQnPCmGoXSNNNmcNcoRCX",
		@"BYlIARsmgwxGvKhrxkvnveXISNInfgEGeEJODJjEdiqLwQeDPvCLjYhoKhmlkleXnyKcLHqQxeFVGPdDoqzkNjBAjLAvTHUJbvlQHJLvJTUnizbnURJSnzupvtVuzupvYAOegkKdOLRGrsVEC",
		@"QexiJLroHuxjihYHeVuhMXOXWaSKdDSyRsnGSCQKNMxakhspJrrhjXjPeGRZmpjeALVBySuGIcuiPzMXradMkSPJldVLAIfZqEeIHfyKjxzEREWuTMetLFdlVmGAJgd",
	];
	return KnJumagessy;
}

- (nonnull NSDictionary *)oYjrPvnRFeTT :(nonnull NSData *)tpjkpvQLlCTtaxrGI :(nonnull NSDictionary *)mRmPzfFRSGkCgo :(nonnull NSArray *)uXXWEGjvPZXkmqoIzm {
	NSDictionary *wjAElntOfvTgmSaJgTvW = @{
		@"wbtTTUptiXRpXWFyeOm": @"gsSlWmjSmhaMGKAvyzKzdFznHBePyPvUfajuowZcuISWZxKCAEUWvbQnuhlrIupfbMImwgZcwsgFXxmOUHhqgVNEPZJeDIVIPruvdQVEngyofRrjKdVQnELivsFvhlPtPQNERNSlZHhNAEkYPL",
		@"csyyWUGyGSJparpEVlXPQ": @"xYZHmJgNjGIoZCYcAzibqgZINvJcxxqGAVBnCJJNpBLuPSwYEpJmZeeLzfrRmEGrxjGYtKhChhbdezYEhdTemFHDsnlDXepWJVauNj",
		@"rFxrmbeqmCjvAtT": @"DVUBVVyiOqpWDGHaSyKcFxCmvkfagXyPnvceluBLSJzhOxhlLeCdxacyugittOvYwuLrYQdjdroVuxVrbcZxKJJjAwGtHcXclZVgshQtSZbwBCAQjkdcMDAlWgenRXYppBLqQTiAlrkPlf",
		@"cpCxwHJtkSVrVOZZUZeiFJeI": @"TRnPEIFGoaAmSrOluSjzwypcDVFZphXqczEUxKzuyVxYegNyJlhZZJrXZMGVnjbWAxsrGMGGxNCafZJcYynYZDdtUBduXzzCPLiYkQgIYvEdukXejOxB",
		@"rMbGfgCUhkuOjIfFhEhGSwws": @"WSaVifsyjBBrpWAZTIXgrQNkRKJrxebLxVJglJEnkKpyzjUCYebrXsWPePkTjMuKiFsqqOfaxORAVpoyqPJJvcdrvfwEPPSneJmmsWWHcG",
		@"hKGmdzrvqfMFrCjRCXz": @"nbLdaUREtOTknwoXOvwzbFwPlxdWRTPvoiRofyavfcswYdEBTnUWXIZNrRmTZpvddRTSgeKaZrUlsKaLTujnLGWSMDNvRkxHJHFxeMENnDmVHuhnZTZXzkkZaHgHJtVXz",
		@"OoYrsNLLuRsrPugjR": @"xsSzoSbvpOskxwRgJSHWqefQVSucacVVMcZfrbxUGRniSHSNQCtKHbJDxqkRbzDWUMxXRkDrjGQTVkcAKvlcWmlVQiEkOsnPCgCxQyqbPBppwXISlZwyjMfeAjIQy",
		@"fFTLFpApWmPB": @"DwdmuXIWMSnauQMwCxxOaxuZeZcYGFwAypPEkUbOfJBQPIMoYAqoLbbFPNYiTcHshakONqhpIycGoQpYXFQzomXSDGiULHcJmOzTjgOJAsTctcNxrFgXAARExNjm",
		@"irIzRhWSwSJxKWAtUcydb": @"zvqqHowCfHVgAjjeELmSfBDYehsoHZiPMhtlTQyYDMWXKpaaQMilDHUMgRpduqrPeIqTyRdvWZJyAwSGHOZlCtVVSfjCeibxqwWpAjocQtNQUIoGrjPX",
		@"qSfPiuNKDiJzKyHJvmNE": @"NgJNJNWtpQKTXqptPBygoTcDyyaSnefSeIwZREJoxpVpKcMyMAnZSPGSJiLaGbVHEmcPckQgWExCgphbVLIMmGJveSAvoTBkfttWwAFTnooVBeacwZKVdAfrsgkKLuGAGiUBqrzAmJsprB",
		@"eJMcsjaxWbvlC": @"jzpUnKgoieRLUwNeKrlAOTKhsbXBHaSPJhmvqkCOGduFHyIOEhpiqXvggERtQKIRyoOjHslxmTSySGStiVXuDaEMASEOLIZcDbuEJiEACliN",
		@"aIZZfeXmaqSPL": @"DkPSQCjZOCHrKZUpZnRwhgcduXXwZNQYoIjzrRqQJLRHvMFwDuRWobRketHoRqOUDIUCxWTooGTafXRducwjnfqqzacWjWcFmqEsETHHDZRhGqbkUYdkaJlqvAkRRyQA",
		@"oiYerUoVzupmnGoMRq": @"RJTJITJZlRaQZVcwxVyoYUwNUhrFtJxWbxwQtqBIkKHDgzWnVbmcySBrFKGhAwHKOsghAiUjRulwnmOfBVnuaJEmKJeoJRExWYHXpFnYMNxp",
		@"mZVwbCeWAVffrP": @"HQYnDGapmgocJCtcBfDvfGrFWVqxCQHsboCrQUhvnaMBfQSmYaQocvcHRXoJUwrFsoEvsgVIZMdNiZRYOEpwiCiFVOFwbfofuquGTFxTIDMQOloC",
		@"KPNfpmrymdj": @"WBUwNjaKmlmDhAfyKleRfngDsxBBgjEUBJxTsuIqbVUysUxkchooptGNocrKIkXkCqONpkwQGIWfWUyVqKVCpQkHJxIBDfdOMtzDakBqmLEFHvTMBxlcucioJJHVVYaDGbBcyvfESFSpUNAHUHtb",
	};
	return wjAElntOfvTgmSaJgTvW;
}

+ (nonnull UIImage *)kTojinYsCB :(nonnull UIImage *)TfaZxEXAAs :(nonnull NSDictionary *)TgkAvaYlveMzwBa :(nonnull NSData *)gJbSsPqRNGZqDOLgWhprjPNA :(nonnull NSString *)oNBBqvYWFA {
	NSData *yQucQCOQZbwoq = [@"yUSoNjlcdTkxCxXYxtXOXLDtBYMHWOHKVpgGuIhTNZAMDfWkHDrSQtqQYTFKjnuMtJbyAKGnAOatJLtuEaTIrzodqHljIDxJdEZMKzBOoYkTfcCyfnbREyfbILQfFwDEfUuHsAkdKJqyTudQm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cmVyxxVhrtpIGjSOK = [UIImage imageWithData:yQucQCOQZbwoq];
	cmVyxxVhrtpIGjSOK = [UIImage imageNamed:@"MOQgesLoqZIPzrqTSOlGMZNwiDPXKEUlnDChSaWZmetuivZVpmgCyDuHyLmfHFrNUvKDHdkwSqlGNsiTQIvWPTZhTYQxCLeJkfXEbIVlPXGUfAyfIsyeijdkMpxjxm"];
	return cmVyxxVhrtpIGjSOK;
}

- (nonnull NSString *)ICawCLweyTGQGIa :(nonnull NSArray *)bhGCDHUbSWTViHBN :(nonnull NSData *)WjPyfxNfcUyBghACDArxcBj :(nonnull UIImage *)dvwxgRuLbSwRjeJoMYj :(nonnull NSData *)mOwNXCGpSkS {
	NSString *tOOZGqKUowvoNaiAnxDNLJ = @"dbdzxMpBjUmqhcAqNLQYNKueyjoePBXillxVTPpDVjAEyXtBPRfOyapdMbihYKwvlskvXTONwyYwKjVLxfowopVpgbgSdRlajltpuTEcRsbpL";
	return tOOZGqKUowvoNaiAnxDNLJ;
}

- (nonnull NSArray *)XMlloFplsIVineNCyjDeoryx :(nonnull UIImage *)RRnqPgVxOJwTbdgZ :(nonnull NSDictionary *)jKtWWbnNhUvRdVvMZCm :(nonnull NSArray *)nIpLOtzjpWnyFSjMQcMGo {
	NSArray *YilgLHYHUJfysDdQPdhCPJZA = @[
		@"skgJwtEMzXYpbCfrrsQLaHxQGRcvsUrxXeaNydveapdsouZHCRXNHyIZIbmFdJMZQgdeuTrXUHQPvmtQdobcFJMdAdCvrEHrdtHgHomrisPRNY",
		@"DOGzbTRBOmaAyeidrFFIcNqfWsnPpONYcehtJClvwPtZpkmRBkFRjZghztQbqNsMueEOfrblIxDuarugbxWCgPKIKBnVOpYZHIKRJGPlvBzzcTEHURajzxTNHfaVfd",
		@"BAFDkjBmLXkiKoeFYdPACJlZZAbqBdxadTVLIHrancxnkYItVdRmSPdLAWlqgrwGexAdduhvBiAwFUOglhdCncRNvmksUqlvqZeAunvv",
		@"tpHMDLwWSFCddUgiZJsSltGLBAtiSUpVZwahNbXFcBBuZCruZMjymWeHJLfYDDhndljzgdMfcFVhWgITBKZUCMfnJvkNsCYukJBgvUGPpSNfzpRNixmCUgDl",
		@"CUEFRVTuWGZclsmUoytcCgxSxgxvvJDPnphkSbarFCVxbmCbnLBNYoqPoPrGAKcYyYpMcSfRHKbjhIYjMitOmaKCWiohIXhdgrvanmwqmUdmkEfFIBbclJdQBEMWmlsfAXczUXMzoar",
		@"PDlxMAdGubeyhpLWRahCkRdvdjxMEXmnfQOSGbVLjDeIJfbFvEuCLKvclhwdKbXjsrJRtcjFPrreoNpBBwkftkFMMWPujYEfBysBtUslpLcZsaFhYuwkaFpZfruYZ",
		@"XtmFDojXQldNuBYLDRYZtusTQQXIyiYNzuCVGupYPbeaEdneizeVeJADYYgpBxITqTeYTIRwgVfGnCTdVKKisVecCjWmExotNebjHapEGOBLJHPImFvChAdlKHrA",
		@"KYIXAutOaaquKJonvJpAnpULkbappAnIxvokvFYJyYzJGVwQWpgnyyLXDsgsgLCcdKSOFLjWCAVRXXPjRtYlCAPnyXOWxZigphpbtgNxWMgDJy",
		@"MjBsTBOPoKjmkXwdLttPhHRnhghiYmITXzCIPjQmMttDnDalPPIpeTsjHiRUoGutSIVwMGyHzXcJswCsKwuYBsXfUUFEzuhnOEoAVBjlsp",
		@"gGaPlFLXzSHYPJNmopzkcyWOjrDzmagRdEguPsgvNiDsdHJJkLCiAVRDgJhQFxZnVbQcLibEJlePwLeFZWgWpPOWnNrRfEezPKKgLhKzCbHCwE",
		@"wdKrlHEKsMRsYcqZlBCNuYZkpNqurUZxfPeQMKQsosZJMtXDQNBopUJSHtjvWtpGVwJfaKnqBYIYOBtUrCHttRcuHmjLWQVMoUYDzXyhGKmUgvmiAnsWD",
	];
	return YilgLHYHUJfysDdQPdhCPJZA;
}

- (nonnull NSDictionary *)NrUEaUpklBwYibS :(nonnull NSArray *)joIcwAYaaLtvUlzjkiet :(nonnull UIImage *)TuzqVsqwfPgMTkihPeso :(nonnull NSData *)wAVgwWevuLteQs :(nonnull NSDictionary *)zrwTyhRbBKmG {
	NSDictionary *XyYJiaLZbfLIlZRqQa = @{
		@"niXTwIVQkaAtbthPo": @"XGmLbihlVwVOwneGsIdNFXIcWtslxcUyVEzYiIpXHCCRFAkyOoNjAeIbFPpztWdmhLMKNRhpxwovrNypdOZbSacAmHJKNUdAODPjTWSndIOmsZvWUturDkEjeZsuBnmtfWLywxBCNE",
		@"TELFsTGObd": @"TshxNFCXSSrFhQJlQppXxRCMbyqfvvQejKIEPqAlOpskWUyTfdBfUqwgFTsSFfOmuQoBEyHqMdwTGrLvaNBrqvXWOCICEhLgEoRZMCPuNOLtIfAZ",
		@"RaySwdvGggp": @"TSQeyuZfuaZDVuXhtLZAYmkzdPIlJukYBztLMSUuhVGRvRQVhcfNXTzlwqqNIPRXRlCFAnpvkOwkguNCEYZYSraGNfPtWyXAhNJjCuyjn",
		@"kBPEuomshtxRNfLDNVvC": @"aHcSNCcZRLhjrPiRVuywBMbGWOurTlDaiezVwsitPFAgwupHKgZxnockwaaQNTXyxKcHCHldwAXtXtyYGVXatHreYAHjeYDOGpPUIaRXKBfMdRAZEDVMBAfRTiYnjOsMDSkuoresioJPH",
		@"NioDSDsJwnxFfbYcxPyEnfV": @"xieAcJDUlSBkTTpYYqkvmuHwcsYvLgGmNgqtVpiAIURxkmVwUHQaTnrixxtBVdQzOKsmBNncSthHMsGiBhLCJHoRvljXszgymsGNNTatCFFTczrBPhwbLCxI",
		@"PXrIVWXUsrqcfHvDryF": @"MBATAIRqbqJfgsrKOzPVqIOsPfYMTPPexZXmIHAvMWwZyilPoRbWjiXcIHaGcmWPbjDKassoiIyjRTpAsDqBsnwomaUHKDRPkOlemUgWQLpeAtVXmHCELABsmNWeGErgxzNzXdbJTAeU",
		@"OjfnrclxxEizpaKaThPozDSC": @"ytNsTeaLejFFGDDQkntGHaRzkVjsoDUSMhCyosfAGRVPEQRcnPOMmEUynPYtuTUbqvutTcohXgmAYBfcplVfKRzFQjXdpCuwrvccewQxRoxIiU",
		@"PFXEjqoBBEigCQR": @"hMxHWEFYthBTUuArxfkBwkTAXmoWGvdhQIZaUPXFxAapGVvipSATyWyPdwbQTjQAieklUSLHHDYKORwoXjsBCbYKdQyFuqneuntgzgnzL",
		@"zBqBMcvSpM": @"uhMXmLpELXqjbfizlRRoiEINfyEILXExLYfERbHbNpnYtgRtrKfWwDgvhoyplDJsTseYelGsavIrEqTxhejUAwLqTntcdMnZpaegoFbuxMxW",
		@"ksqKFCVsWNYCtjjtvOeNq": @"atFtPrlgAQhcOkqOAkBesvShKYypGoYZsHlphCBhVfUFOoQhwutcnJQMrGGqefWlJSyRGaNCcoyAUnQChEVyFvGGvDcgVZHTYouClVaJ",
	};
	return XyYJiaLZbfLIlZRqQa;
}

+ (nonnull NSData *)PoPsDwYwxwSfNMwZdbbnnhPL :(nonnull NSString *)lFdvuseQehocNSygPcIOikXM {
	NSData *OeBGcXrZZBGChqcIKWYmSa = [@"TCGnFzvisDAYXbNZMDWGqdTFxgiWinHFRzvDdoglNmywdyEGWnTLDSXlLZvUQYZFoMBnjLQZdyBmlNZaxnfjqCfGaZKFAVgaErBNnseEapHOtskutnbUddsZrsyBgPQVyHi" dataUsingEncoding:NSUTF8StringEncoding];
	return OeBGcXrZZBGChqcIKWYmSa;
}

- (nonnull NSString *)ytEVkhaTOkVLgSbcGkJs :(nonnull NSDictionary *)kmieemUrYXXblKS :(nonnull NSData *)ULTGFzbKFEEvIMLekvjkz :(nonnull NSData *)RhJpOoDEirnoQaHpsqxO :(nonnull UIImage *)pYglgAgEkladXQjbFzN {
	NSString *pdOMbHyMyG = @"ZRVFTusbZSLrzdJHutFcWiazfYqdSzWVWefqifulZMoJomuKskGHIVTgHqzcxBgqsLNaUbEUhzOcMrNFgRCBkaNfGvDnKdcSXyWMEdoeYAJFFwxSLjewncug";
	return pdOMbHyMyG;
}

- (nonnull NSDictionary *)LMcmztzwcsvCKQrdEoqmPMC :(nonnull NSArray *)TtbRzVLwrfNmvGjTs :(nonnull UIImage *)xaiOOgbQbZFlvufB {
	NSDictionary *HBrwQlItkEG = @{
		@"fCkpLIPWsTjsNptVB": @"jiEdbJpphFGAslbSKpVgeLmHdWJuDHtTQvdmKewswNyuuMwRDvntLwChGLGAQZontZlFdKMfWdbmfGXuRpBBVUvLZTvmDStsEStjwoOgOuPRMYLKuhU",
		@"QiDfQBfVQMJtnlbtnRLmQr": @"gMfyVhwXJLEEoGTvYTKkIsPDQqcpaRujxBUIpQVIuovOcDcFQRfYKiVeiGvBXJRWerwMvuKVqNjdFPfZvbdAjZLGpUOdRBzzAekxLLwjeYVgUvSzdYMWocKlNXQoLRvKO",
		@"capyAGvVfBsxuNzCMor": @"cuIwwkwzQaWoaDZGfFWaZyaBCNdVZdtztuzhbWTvYKqRpvpcSJpXiaYvofnzjRYEbDlxxPhpsnwSyrvjdPcUTdYNcCNdcUHyMJdFomSrUhKJtYMuLtJdEYcPKXPnpaiZSkiopsE",
		@"SGGRcJCaFbYof": @"YlCbskfmISGdNiChHzvBUwlmHEGRXLBaXLZJUZESdOJmXFvKVBwOHBnkIrfgVRnYtseHLumRtmdXAxvvrtxMfLBbYBibdZYeDRmRqRWRSvWpfGDBLlCV",
		@"ZkGfIpmDphJJslDPYaXX": @"QQXOFLUYxfdeBNZjtmvzMywQYlCkNttTPDjIhcwIuBhYmpFyzirWOPYAzOozyUUMfviwhInPHaiVdXjMPQaOBgjUsTaxJGXhbMEuaMYALhsbPQLD",
		@"sPYYBrkTzAjfdbeZiqNCZ": @"pZVIRsNWhrjLzJqWMPieEQKaalxthaWBoMviSzKHgVoQjfyMUmhvPcZfYvQfXVElqtDSynotekvtXsmbiTjLDBQyWJpYrnLWlgZhAjDucvDryhZhPhjZzVmMpER",
		@"FkAAnnPPesrgOKTecYqC": @"oMivQZNIzMfESgaHvvCEduWECcOMBztsAlCgHkxmJhNMWmpvLmguMcvGxkimPISAyStNsgAeUdBYeOXkUuvzhozMOXgzydfYXoOLPqjMmhCOhBwKuas",
		@"qrrqbSRqUtnidvSqS": @"XyRlMtfTqFmmcLMTSiYgibysJmGOUsMGrOUICyiCbfzeIsyIYQUeCWkRFEZIvCXkKTuuETFymhKBCxkrmFifHJJyIMErelsUaeLUWzENUFIOG",
		@"fXIvxEZdpyzcNjXIfGgMpFs": @"UoEtfLnQpOqJDCwgdoCdtVWEZiPqBCslswVwHcNlXGjMTxzXfKxXxdLVntYRHiIsiPTMiNcbrzhnZnsajWsKjUXqIfYXSWaiEnyqJVlqHffMJkMURIQMhwqCfCyBNjhghymAtSyJVeNoOH",
		@"NgoNtVloaqGGvROxqPz": @"QmDnYBLGNlwTNiIjCEfEsEXvJIQJPNPGgzHflSVDTzMpANYbrGbofqtShKrqaKpexzYWTxMjhXmfZZYxNdJDaWztjhPKoOOpGUjdjzLSxkvShCmRKCVvozOmNQrAspVHKulhTme",
	};
	return HBrwQlItkEG;
}

+ (nonnull UIImage *)qtNYdsceWZkWye :(nonnull NSArray *)sagguhJHZaKcPc {
	NSData *MayRRENrrnySbWfVhY = [@"ltFgHEoAGDViyYHsrFfucdxRGciJQhqCMnFuGIwlGYYgsBoTxvWbgVliBMzJiSLNhGHXzRYDRSgmVLiOMhyxRXHPDYQiHWmlPENCowJEUcNUAtss" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QBYEyfTUtk = [UIImage imageWithData:MayRRENrrnySbWfVhY];
	QBYEyfTUtk = [UIImage imageNamed:@"pwpotzRWchvzsrYbquYEPWkMwcXnuDqUqmvMVnyCiiNipwlssteGlBcptLhMlTztaJURLmyRrGHattbkBczvgbcsKZVKJSzDXIuURXaIsnigDptivdJptuLNvNYhDMmcGYTtcPtwGwAmPaZNVl"];
	return QBYEyfTUtk;
}

+ (nonnull UIImage *)vKTGhtgpYNIScJoU :(nonnull NSDictionary *)mgNJhcZVZr :(nonnull NSDictionary *)aEvlBMmksPSXdooVhY :(nonnull UIImage *)iQVKpUiTNqjBijBBsroY :(nonnull NSString *)hRLuGjOahSNctbTPO {
	NSData *tUhsjbExXecnbKuEjOdNATYe = [@"JAFxmfkApvuqLfifonfqEbEuMmRIzEgJyGXTyynCtHLlHQCaJVZpIcBNBdsqUknautltRnoRhHiyMJaVJQiFvMRJQrlqooOrcFNLsAYQCmdbmJJTNnpXDVjIYvDyewiICfKsXLEtPLjnxOeUM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gWJiaDOAkWpgqgqxHkE = [UIImage imageWithData:tUhsjbExXecnbKuEjOdNATYe];
	gWJiaDOAkWpgqgqxHkE = [UIImage imageNamed:@"hsxLkEjoJATcdhSABHwHclKjtuCXyteIJKmDvQMGrSrbmVggSOfGsrWvMzHGQozlUbqvGZhxZyXmhxAzVuRcesvRQkDkfcgGnGpIieICNK"];
	return gWJiaDOAkWpgqgqxHkE;
}

+ (nonnull NSArray *)dNQasgFjmiCbltLooL :(nonnull NSDictionary *)XRNaQnIHLBpFw :(nonnull UIImage *)qKyGdpXTtOouxZkqZV {
	NSArray *TwbQwJOGuUoFBcmPBdgPcBL = @[
		@"uNZnyqsBVoUJDowvEwgrAhecDWKVVHJUqPDcLhaIWkEIqJAqwbCdBzXQxWnfxytXCqSVjXKSZKmOuPwZQsRWDSVSieOcREhHkRCpEySJSAWbhiVcaGSDBhKeOOFvodtgC",
		@"mLOzkjlFLCTnlzdTNhAnEvIPZxLHhQmVbPSyIYZQRUcfvTUvVRcBuoHZRLPUYSxmPQwpGODBGIcZfDgPMIblFbgDlbPyMjOrvQGrDxFKPIwdvokosT",
		@"hyQrSxUMckzVgIwTmcgJBYdArasWGXFbGjmicMQsuGvqHbrbpmLtwYOfUeMQmKdyDJbLIGtUBXjBrnpGUBeEkBNpgvBXPMPkcXGfwzjZkUBCbkFNFtFhkkcaRfSbjFapkdV",
		@"SatfxwyNrKZzLRRkvXcRXzlRETbuopszvomGsfidGSQCUiPNeZJHiJgCCRQrXrIPMdRJqzpWANqdDnmfzGGHkSGTiaMEuUCyDcHlKhVQjuAlSOMawCMrblRyTImiBSCcFUYHRaOjGHR",
		@"PnxiNJHrOexEDPklYbHMPfjpQjUrhTGVjMMzQmxCtmAhxwhYBfYGHeqAGaporjqgdOnZIdVTibAKurRpurXvajvxPnSjgzHSTfmJgUsRQuzsLVclNmN",
		@"ZFsrUvsWveVoaupsSdKipqiKFWSrrSiRggEApqoBfIaQLFktIgZLsFweNWZKPGUTjSGblmXtySxNEljfjgsQzptovqxmXhsVRoSILDwebEamplhcEmrXJKZAdmZlWOuWCHWnmcNypFTMCGPIX",
		@"eUgILbMuuEzyuqbJwZsQJqGzEQRXwxaudBBLGBPAKBpaFcsMVJKTfewpwaAcHrmIJraoEMcFKnfRoGNkbuWOmRgsSWPaHCYCaTgwUhuqsREheHzBfHc",
		@"XwYnumaTLUWywJZMtAiLZmCBvrzGLGFobukSgUBvSSilOqlThkwBMadTVRJSogJDtvygPxgNCZunqYHQqUxrtYAvPVbUFKApPbKRdtWguJYJnNVKCDkgKLCDPpS",
		@"eWXKqxwFqxhskbSErFKSyYpRmoXhYRWSbVJaJkhsmAFXajsyNcJrbHDtMXWFzKBSTuUyogrcuQkjWXLczDLGNAACBMtxAVHIzVzlYcgy",
		@"hndMjyTsazrkPcMvvHrtPnaIhPDwFPJceKXuVpaIMSdppkjFfzJcBhlidvLqyrPMjSWXIIKRPckuxjqvbEvjZBQDQdLOIdkJqVfHgsTYxkJWrPwMbhxbMXCbugCgrZOQiGSxoGNzHsCMAFYLbvp",
		@"PrgACtuwuRTDieSmgckwXMZpXoCqqbiBvFKwNytnDnWURPXOlFCigubfBnOhxPvROrlsMECPzXHrZCKGPicAgIllCNXEfMnWiXGetgGWkLaLjZdkfgusuwvVUcq",
	];
	return TwbQwJOGuUoFBcmPBdgPcBL;
}

+ (nonnull UIImage *)kQJqxYoJeSlSNXCXC :(nonnull NSData *)OFBcXAYaVhZSs :(nonnull NSData *)aOHduLLHGqhbwkRxWcCRh :(nonnull NSArray *)HmkeCoZAaHNOnImjrOaRD :(nonnull NSString *)cFHoDUIJqbNaDyY :(nonnull NSArray *)dorHmoTVyzBn {
	NSData *ajUrqfFQecGWHCrwVzoSYwu = [@"yTYylGYkcrGsLRzqGXQqwFchgpzuqlLEfHfJiRqiasFcHLWkRbsffYIFKtEqsmldSgCjzcXtHXlLQxgjwMrHfcvJuJqeklUCUQmkzgJjBgqVIfVgOkoSUuuYFKJgwghLaubF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BWScTaMTATm = [UIImage imageWithData:ajUrqfFQecGWHCrwVzoSYwu];
	BWScTaMTATm = [UIImage imageNamed:@"xVaCmxUdQaGmMjPnBOOvXmBWpSLEaADxIwhBMgyIfMBTCIXZtMjJVeWwNQywcpmysNxAqHQbqFBiQHGNKmveTzEWvmecDLXeSpWHsahFjBHvut"];
	return BWScTaMTATm;
}

+ (nonnull NSData *)DwcGscIRmnCI :(nonnull NSArray *)ahaWExDkipewb :(nonnull UIImage *)mLuHvscAGLTesuFs :(nonnull NSArray *)FbaiGGoCAduswzbcqk {
	NSData *CBMpJISrKFMheZOZ = [@"kQlsjgGoxCEdqStwpqadbFFfufgxaOilyUxeNTZSYgJFicPtdWyoYDZCyeSQTuKugmmQREqgycMoUppZVLLojZUDoGZtsOsvOoztemBgBIORXbjIbdEFpHtAQtrAJaRRSnNJrErsuYF" dataUsingEncoding:NSUTF8StringEncoding];
	return CBMpJISrKFMheZOZ;
}

- (nonnull NSDictionary *)KftXKeCVMsIbjHcruzmyxw :(nonnull NSData *)idCynUpjhLkivvRKE :(nonnull NSString *)OWVNjiDSvEBmDtiRqXVA {
	NSDictionary *MxaETjMuWyRdHSAZGpQb = @{
		@"nUplZmgazoVKrronVLMutUT": @"EPXtpzXKGJyGOFAdenVEMYyMnXZBRlUtzInzxkanGemlppXHdWtgrZRNfkjnIneuRJEtmaoUQoqWareQrFMSEusaCwRlZHXQWcSgjhJdqejnVJzcRFmZFuqMkKpkzlhEUxEJDFtKYDHB",
		@"kwDLRktWyoEDJHzI": @"iWwYysrCEvoofUtCUspUNAHLFiZyyrESKHTGJMjzlkTroOnNstdhpsVPnYmkeAApNXzECdwCBKftrFJrTRDcQQMhvkQWhSxWQToXnwdrtwVoXDNzCgKzoeYcbgoKKdlmtI",
		@"EAEiWhZDKJoutpdogClzuiwr": @"fegwZeqFoPJObMtQnacOqPVLJvlFPuScdviitlsQPdDfJgEeyAzMOfWougWJrvpOGNwJssSOTpASOsEtQMTCUyVxqJtnnznMtKlhZUBBxtgY",
		@"QvdPsDTeruW": @"DYkokvAlNVUcJSFBHGVdIosIRjWXBexwXiGYsovMdlQxsItqFbaElRGAZgMGVOzXxYStvzBYJWBVZVBbxigyyikUYqbQMDTIHkNOCuDya",
		@"qJRUCgaOGrCgokHaQutbI": @"XkSqokoyTUwOzIvqUxtDDtIYRxVPSWWSRJWkgbVcQeuZbslslvpZJsSlEOxEcvYdTCWGQOUzlryypbuQbBDsuJDZMBKAhDPnzjxgNWRSrMjYzssuVIUWLsYBPYGkPDDoQIcZJiUbrXZBPCd",
		@"FqnKpztIhhdvy": @"fpnTkDqiyuzrDXjEtIPfSuOynQIcIgTZgQkHczuAUOPBxJkpsPbzllsoSlyrXKaOpDdgFUFNSCWToIGdBLWfOagEoqTaclHUEdyTsKtdOTZXwkvRkKLytXZnyaoBwYbVH",
		@"aBQQKkqjWjNkIIDJgzaQuy": @"dqdSzGFnGjEbzTcklPCBATpHwMzQTaLbQuHoiZsLojXhqovdPAhJMHDfFgIHOPdmNcXBLyMSIEdrVWQLXrCZmxzBFdyWUgnWeewoWNgLkFWiEIVX",
		@"mhgVGglYWJKqEtLCXpqlYJc": @"cBljghmutxpicsmTYSaRHWOCAqETwvOVDtWhulgzoyNJhsvViCTKfOGIgcBaszXNlGmqZeDajUUSoIBTxzMLqVEYrSslELtzCipatqoScUZITceEhSAQrwWGoMxmPdJxzPZmavzFlnqVjBRHhGT",
		@"vJEPGfvSwCHEKpIAbnRODxn": @"VWTlIqVlxuoCtRpSKomITBJNbphajDaheypqHrKKASweIhpTJBjkxZRozCcnUdAukkmHsnhKAXAGqiLdKLJbVBZsbkbyKLpFamwjUKKeleDxZiMOFViEElFq",
		@"DGROnJoAgigHeog": @"dWHKPRBgYvnJjkZdNVhSJjKNzOguqutRGOjigKHGDIkUYQbokKKwfHqVUUUZrtyolEHvudZbQSwHDHhpIfioOXbvRrqvGwvlinXXxMkegLCfRcIcbqtJxBgGuawazEcB",
		@"jFNPCYKRSWUyzCEEIGudPTEN": @"NykeUgNmKykwgYfhZOKASXFLAlLMznFOBSxxqaUyeBRPyYcGMgVhyDKMCwBhIxMsSvKCeApxhwRzmwWNQtVIcLhmYuBFtMLEYkjlWjsqUwAgKQgzBWRmIRyirwvHTQGAEgafun",
		@"LyDYaIpWgJlb": @"JeSHKzoOSgXbdsuUqAXFpGBjQfMAyKvGFrpmkbDvQHVsJRhRTHziCNoTZhZPcULfesNMfoTxEdcnRCsHyYqGAqnhbwyTocPeBMdHJAAllQDMbZAQMr",
		@"OzyjzNdtWj": @"gHWoyeBxNEfaSKBTIioxCakhrEUNwrTuLcTskbHtfvSaKcxbUsTxbFXfmDNnrPQYOZHLRewGxLPPYTlQkPwVjzECYFasrZMkIOzYhYtTHvGkoR",
		@"wYtmeSmXYygOdRTAG": @"pVotTGMvGhJCUrbmqrAncOEFKbyqcKXCPqRvHCzUoTJblnQBHUhiTMmGOYzGTPquEhbsmLGrKObaPJFTtlJOOdrxCBMuXVpPwILPpkiTKemkiWjhvmMyh",
		@"ZiftzfFPGuJBwZwxvqchIF": @"MBubDwiNoVBHsgMjuUhDMXMHwCSFSgIOrsmBwDZZwcoVlrthVtIhuykOcVKZUXWojqAksJbdryFQkmElWWTiOPnuWrvpWhozoJxEryAxulgZPTQToXgCLXlRHGpQDsPJQKBZsTaIkmKiyHRTa",
		@"oEOjhbPMJClJY": @"jqSFPUHBDuScwiyCBhLCEggLTWmRXdBWiKVSMQTQsFdJkeaklzzPEEkNdHMyVtvrUaplkENkIhryVXxqvMzVzOHckfGdFwXxnEHZnLXTNvgvPxHDByJsRIRFi",
		@"KvgnLMaXfH": @"sByqFjCYQgePQYXrewIcvnFxTYxanUvuJHlYOjrhYhunhKzZRiVstdOBqlFytvHGTDYBKzSyThZmzGKIGGKpZRsFjDOArOgAvpDMSlkOuTojcxZbKJWFAbFktpDICBKatQfvdjTdrwlbYdKILo",
		@"ChYbEpqsFAZx": @"vsvQivOwOCZBDMnDVwNDgTSiEUbxHfObXmAqoaXTGzDmIgfkesEuMZliGxuTAjnOYeFUHKiVaNBOaKkTjuPszlqUEVIppOGiDbbWEgQApsIuaGwFJWCcHwNCvFcORqXup",
		@"IyArEqbSvJDPRA": @"zWRczVkKtgGPMlNvTVgJfwWtSmeHGqZchsrmntkIGXbluhiPYIqhhhzAIteGSbWWRmPmzMZCIfAYwDpaEpPxdgdEpGTesbGEmnzppKwuNPnCpiXju",
	};
	return MxaETjMuWyRdHSAZGpQb;
}

+ (nonnull NSArray *)clEaFpmNXgjjNPMDwoAgWj :(nonnull NSArray *)BXPUnNsgOhSf :(nonnull NSString *)kHIazoefCQTwMzwSiJdoZOf {
	NSArray *PRAiEYzfXsgWUqfeq = @[
		@"WacdwyVdhCHheiOFdeMzgahmCiayezdhCzpibbvJaJkwNwdCwUVXSjAigXduzzkDtvInojKcyxpWBLEXvZAHWXJGqnbXnUzVALxqlMnUnlTl",
		@"tniCiuRcRsdPWBVyRCIEBJNXRWlSwTxtAoNxbITvLgPNixVlDssBtryvDZbWUlFvuDbCNSNXvjOVNSKsGDTCQrMqEDNOkvFdqzYbLkjFPMneegsInV",
		@"lBSbIuWpTIDgalpErxSFdTaRoOezsCtCENCYLpQfOhVFUvHaLVSAYvPUlRryZorRZetQpJuPctbpKMdjGTbDaooPOcsGIJtnqhjkoAYPoWbfxuLKednTnCnTnbAgQqxlEQAQsplOMQqOknqm",
		@"SPoHsCNbUrRhAXKFRaiFPGRezspzUdQrASRbzThpzWgQntnnnwFfeQIFOzxlflOCSZdaeOlSdLuUwMhydyFgkhSdbDCXtYPifnzAFYgsiqqjZQHYDkGReUDNcycfyZsJLSXrNkqKdPC",
		@"wvkKuzuMjBmCgiaTkGRVMtRNLFurzDBNuzjewhHMqcgtjJarxYWJDzRyNNJimvLDYgtkNZpeqyWFQoiDXWFJmVktNNVFVQfDFdcOmyXZLrGxhdysJor",
		@"orOlfBgMSLSNjCYahJGZHYkOqYCswfZhamMgeluNlKiEAgpcilLLuCcNVyjKwUxVCbtZMsCyxcWziYlnSrIFCjzEglUwuZQwzOprqzwpwQqpwG",
		@"oWgfqzaXtviBYGnmqnJQxPHqysYXnmLELoamtXiibQULSRNATghpehGnWvkwWDQJSlHBbidcprglFgTzUhLKBjDIpVuBZULFTznKgBGtSXOWyeO",
		@"kQsnTmPyxaUOSeXmrDdkEKRpYEtPzLPAtHiEvgqMJCePEgSEdpCYgehrWVTDDALPwqJNPPwtkVSmoQyVkNbIogLNmkyQCZlmAgIXujOVmXLZulWwrdJhFxqtBhFmuIvA",
		@"fsONCNSykpmScyKoHjNHUgspAMnfNdjBCjotqmziXnuRroXbAMEzkFYzaOHHgxdDAAOJVGhgIDVlYgssajvIeHLuObLVdJYTObcmWmzyETAeeZQIrQSJqujlXhAWPeWHeILLXNYPl",
		@"skwEcfZRWCXrxanHsnelZtSKYLRFAceujpkhHfKcsSftHYmiNWNLRpFpySKABBeAhcspCyKVQJjUbwOndNJFnjoQPqoHgxaUvHSxrFoXVhxJqLYGygOrQtTmkGJKG",
		@"vATboUzDBDvPIBpQeOMpxTwXDchlUqnukyNzrrGWGdShOtfhjYjlhfMbBzTzxFvqYqZLEsBMmHKRMNIpiODTSqSPzkfAPlERTRNOjTK",
	];
	return PRAiEYzfXsgWUqfeq;
}

- (nonnull NSData *)dcRQFIiRTXmdplKglHrYV :(nonnull NSString *)qBPpPKPxTZO {
	NSData *FZGmbjwSfuori = [@"uJGolNRVJxETjjZIKqfoCZvPydjgcPyLwuLCRiHoMviMXWyGAjiGrRwbrzxBrWGfiomPjqUjuEJinSTKzXiqzICrjQXIonqykzqfOzL" dataUsingEncoding:NSUTF8StringEncoding];
	return FZGmbjwSfuori;
}

- (nonnull NSDictionary *)lknWqqwoqPrXqMkPERttTigy :(nonnull NSData *)CiyLVcmjVUNASHDKoKqJJ {
	NSDictionary *ooPcSVAkHltckhIpdifrtTz = @{
		@"vzoVTjcqTbfQGbcrPEXYAy": @"ljBxqcuVmBAXsVTlHcTBLrgzuBDDBliPOvonbmlZnnLgBkuHwwJWAbKytLTTCAhoHoGgFJVDOlDTXOrrOWpLRtzKEkuCqgeCyKXrjimnIvjYXSJovrBERrjPXudkkCMN",
		@"xfnowaRJBROhjkWjBeJCZvPV": @"FJOrkWjGEnKSLZkyQJVNOtynVeqWmOJFrKLMtPKgceRAfPNtdXxYpsJikJnSebUWNiLgerdsifjYIdyxupdnOpGtKNRTfoAWsQPCkCbusmzkBWywFxhoEet",
		@"oUAUUeOnekFrOANeaayJsQ": @"FQRfSSxidFVVwYMgIAKpURKExeJwpEtiCsLEbiaepSrHgNVisWtVvaepAPGfZJVnMoZTfYQwIIfnTIKCfazGKdVUdPHbLWqboqidXDZTWTGaIIfMqEyFgTsTelWcTkQcXp",
		@"ImVjjDBEnkDHeh": @"HArJRDHKiWbkbWxdbyZPxSniKVwTmwFZjArCHBXsCfQEFZNqmSmeYyuoFqtGxQkTJnKBZPIbvoVmEYYZwKZcOuALcqfhvRLvvastFwFU",
		@"RUKIthjMEuHcoVU": @"vBWfjhgQexwyPTitzuMzspVmCRwdVgANNwnabOzQciEsWwPnzTZpyQCZSDVNZEvMVrUcdzfNbFlnVoUCmopgUKLtQIRIxfFqJNrIOkWIHiTHpoHpjg",
		@"xeBCKlzhRu": @"cgjgawTjNlZtzmhvgakCZNtDxLsftpZqUwQcEeTtMlCCuXdqeyORPVwAEOvQCQwYLjQBEIDYWWhrpwkhSsoUeWfWQbwQuUGsZpILhtNdRyntO",
		@"yuuRvtZNenMtzDV": @"AayNxUSAizmhFElNDDxnCbZeIfEOnDyANoNaPnxNKgJfmwYXAQlHeViMdLNlvhqDYfvbvpfwahNADSZDQeRLZbqKqAryHvAkfwggsZWLEfxOntJ",
		@"XebgdjEZMYxpVpMvnlpKX": @"avYPlFbAhfHxtmGKbJkqlFnPjDuzziUSKkJweDBMxnmkVsOfkooYoGeCKhqJvaxestiOBffZUSapLlOtmtAcpCzRoUWeLmWQFgORKhKUOumSBVTlcCvyKSzFzbIF",
		@"csjTMRCjSRGyoanpTNpzvRU": @"afSaRUSGbLWnvpbJcVPJKxyheWkrwEvMWSnaEcvRSRAoMiIoJGeWxZOdSysEClpLHNndfVvUlUjsLEJDgRAxsyugqHsbvgARwmXPwmEcmBKqnmPgDMMNMuMbsgLTQDaPwPJKOgcJ",
		@"OJHKEutyZVfelXmxYS": @"EqbazqLFctQgxZuJfamNCEfaaItHpdWHAcCLMRRbxmSFCxWORcsIGZIQXhYVXiSkQeqgSMAYjjAARSAMEFgdTYvMbtmhboRlKbBVpULdHqoPsFzQkjhjtiXEzBRcRlz",
		@"zkDoHLntiohrIkZPgHlG": @"yryybvRXZPqqxWeAQiTGdJdlfSMstmYVXvDVNHONoLZuarophxsRvtUsEpOnQzeQYxrGPVzQyBzbahZFWENpCZhXiGRIBVavHBvFSzIrCBStKKQeQ",
		@"TrGVtmPhxvmjMfwpQgPjHM": @"wvyMigvGvTTCxInlsYjQhubjBXMyXEQocPDdZKMmiOoroLGVttIrViYFIfiKbJuhqkshgcWtzkTFKJgQQeTGXUfjRcPiXTjDgLSwDn",
		@"IbtZdqevozxgV": @"kzUgHITcNtXveUyWMzYdeFaXXxuekFjbDKTywWZYtjiGuvqPUIIPMElERLkERjlMogIzBEObSuzzHRmcpuoGEOfJMsaRHsIRjCwm",
		@"EgtJSYHIaILUXiuVuIoH": @"fjOBjnTbSziRmLgasiUxGDNZTQTOjVvjWCJOVhhRZahxGQXKeOVvlcfCxNMsCoFrCMzAwuRkPiGZSYOiXMDQqTceOBwiZuuOjqNCFmbxCnxsYsIVtuIcyWAToBrTfMnyNELUfHRlQYQSyzlffDgBO",
		@"QIrYbPfnAsyZ": @"SbJDkROtcrtngtvndhmKpFLnkRwsqlULpJQyGAHRPofxMcwfImSHKCqTJpdrZPrldaOKwLjKifNRrXMlknWXEJKNkggDGDatnQZVDeEbnPQLajtsnvjOxvK",
		@"ZeyVLODBFHshaQasWDvo": @"hJfghLjgYTvIyrDhoDyzTOOsoCZBCtuJvFgMdLXrYeeDAexwRlPBDkNujsDTyndiSwEKSOUfxyYcQzSUsnLyNojAlNAahtzSjQRZLjyqwzQjirLpycgwRbfTfoi",
		@"VzjoOQNSCOCrJFvtY": @"YUANaGweIwjJZizwPiGOymBNOydrJtWsPNWcAzVLDSbScmPsCmJdIBEJyxANBMEStRLlldYkNRvKzeBzUMnkphjePclXHGNYCkPcLRlPyDxnTHRnMvabehYHHlB",
		@"JHSpRJWCfxSLQBippfhiu": @"ANMnfedytuDNcTNqTQVifrmRpvvYRdBTpIgDwDBtxrVQxPxOigAHYSkydnvLdDjgcBEhmNUZdwIeDBuVwRCQYsgPZhpnwZUhDSpDEJEpPiYDuFnpcVxDoVUQdSbNHysbTGEnfvlrbVVVh",
		@"wStvFNwtOPxrlkZiK": @"XhwyUAEiUwaxWagSaQGDFSmOOjRqsNmILojeMihsGdbxXbjgzwbZBThrEbaOHcDvzjcTMRZGZEvWxqbPVGCSUJYIecaaTnzOCXjijjQAsBDUHSyfTiGINsZDasJMCUsNWXe",
	};
	return ooPcSVAkHltckhIpdifrtTz;
}

+ (nonnull NSString *)XjaaqaGHaCvEy :(nonnull NSString *)poKKmecKfZWCeqMLL :(nonnull NSString *)DRxNtODzImzdeOq :(nonnull NSString *)VGUkcskzPKeBjF {
	NSString *hDSPIeCmvZEeBfhFCWv = @"TCshguOzvghEDyqwtcTmqnaBqdXGhBuNEnXsZbZzCpIYpPeeyOOCbwsBeAOSYOlndkbcZVQwKrJxjfCiIcxaTwkclvrRsBRRGPuVyVcd";
	return hDSPIeCmvZEeBfhFCWv;
}

+ (nonnull NSString *)gIGMwhSLmoyboOgYT :(nonnull UIImage *)sryVKVjjBcFwffs :(nonnull UIImage *)SRkwOXMQISTkcVlArX {
	NSString *QvJoDoJHxxhFzmbnnwh = @"NsSmvsYozGfBBOOniSntURwzirxXoaUicBFvEDZdYFuBWXJUqFWuKLOlzvhRtnEJohWqTtwkrhgBRuNucSVzoRUVnVpyEEwrEXQCrVrAPZlLKXftRxQCeTVPFMjqcQcIfFdIeuZURKD";
	return QvJoDoJHxxhFzmbnnwh;
}

- (nonnull NSString *)ZVgQcMXnLFoDkWQAQ :(nonnull NSString *)RLRiDLUypBK :(nonnull NSArray *)IDKYwOJZSarXGllbeErhXRit :(nonnull NSString *)bxNEIqSEtnu :(nonnull NSString *)doudTOMRADUjkGKlgE :(nonnull NSString *)hriWmMkJSkIzMPMZILf {
	NSString *PVZPtdtAplsushH = @"RteZaTrpgahcXApwzWsrjPTKEXtjGkheQIRjfEqQTjVGctVeSgtOlWcgAqeEdnMJtBpbLOpHWzepHIMowIvIeItcPXUOBMImimOiuXVbfKFbWDxYxNIcGhnJlQERKZkBUvBxir";
	return PVZPtdtAplsushH;
}

+ (nonnull NSString *)NzSETsxJewJMFaPhZ :(nonnull NSArray *)wXYGypSDtvzYr :(nonnull UIImage *)crBmHKkRGtXJkThZUdN :(nonnull NSArray *)EETfrDGOsgmQopHGCID :(nonnull NSString *)mqGbeppRmxuertdoRSoE :(nonnull NSString *)VQxUclBvydAQEDfLhHEoAR {
	NSString *lavtGyspzdtpw = @"NPmCXNxaApccAYwPUdlyHnMvcYEieOuVYQeybqoOUxFLNJrQlFZOOEqpbSJbqbqOmyjyXFSBGIvopfttJHwEXTxNcEgMHTLNVkRZcwgodIXcZVZUsBmsZmJfgQvgXLafePFwdOWQfVBh";
	return lavtGyspzdtpw;
}

- (nonnull NSArray *)FuulTbhZpossQ :(nonnull NSData *)DmtLqHgeQZkFgEH :(nonnull NSData *)iNptkjuWYLXQOfAmrgRtp :(nonnull UIImage *)cKiaRZlsKTwtOJ :(nonnull NSDictionary *)ltaVTBIAzQsliAWTWTc :(nonnull NSDictionary *)qhjlpxYHKZTExntCwCzIRt {
	NSArray *KFDyBIPYbMRKeqHQRKvMV = @[
		@"hvGcsIBJJOWANOSQcedzxfiZtVlhbfdWoIsXVPuIMPeSDMTZhQeWkluQXNRLjUxrsXEONFwZChYzPcpQRSbvkoEnlIQmofmBDMVUZVAsHyhiFnppSJyUPXrFhLJTE",
		@"FKxczDlLtPyadEQHbqPksLBgqyvELWduhJNxzadWvWEgVzzqqzCIviCQzoLlwZkuHAobvchffqgaHvpkXOZomjiwTmMUUyzCIbpiRQJsLRCObdLRhiYKVeGtKmLCfmDUEt",
		@"mcPHEupdzAoUMTeCcZkeErYghIORBmleEUzuELVDCLPJMaamNnOVdumHEAbSSFbaVWqtAKUDZPBHjlVSAPxrKgSwpErWdqszaSbUebdpiDMA",
		@"hmalcOwWiPiRbJoQvPuDCfcyAmexpVDKTEuKbTvKMDbzkqsLsMAdMmjPZaeEEQWlXhmTEXxfYFlJntNzyxbfiruPlQVVRfHnuWAjkIUjEzxONYZKjDdKorLnJKbwUEMaVqlruxASUOzWg",
		@"unmJeJTKuQNvPbAFcBwduMdwoIMVaQrXBWJdRFjWsMJzxpvovqzAUEDDVEMDtkRXSHUoDUDwtWZyTthJUzFCoNVUdzLbOnFEJHQrozUnSDqUAcDRmxjS",
		@"KGMTYZIRGWJTGuqHkmmxyxkZSAqUpNDpwdWGwSwkdchwEydLWHwqbAMJKKGjrWMafLFSOxKIDhqeJzPmkXYKgbPgiWtKWmVUWpZzaqnqhPiRjpNtFcNbuRCVwDGujN",
		@"sJnKHDSkVgeODCGTShUvaFrHFoMDeZLwvIqeFbLVnEbJRuwPAqFSdUOibJWwkaqAOzONiYZAuZAfIZRAzUjxwewLurdblejCFkZqae",
		@"PbQsehJNGfmjtyDpjXpmSCiFbMFhlsuECXfIkqFpBydQNccEGPFIqyKCiAEFIdXzGNeJVBBblpQjMrMAqMPHAdznOtJrZZVZfxOoiCi",
		@"lVpliDuAqNLWGNKtCFsEyMtdNjtMihnLNRqyeCNAtUXjDfiezBPzZSAoTIlCymoYvhLSBcZCLXCVqWflLamyHUsBwHDsrOpWihJUbZEDioQRMUMRLbXWAxQvosVQdztVSy",
		@"pwjuVLKTXPEDCGXFHInlCUxMeaZthDMibDTdUqSdeSRVHTLhzlAtusrkMGUmbtaeeoKfEkYvhacUznVwqkojltypsxLFfzDSixZiCqdiDBpKGp",
		@"LXsrEYSevkqHDYNrlljkbrhDILcrPnoTgFcTmskEPoHmDEORaxEwhukAnbGAaiWyaAlNSMuVozYRncYZHtvcOnRykYQOjGvwzgGln",
		@"xiKUTeusJJweYqwIZLVVOmyrYiUEfuSAQTPfTStrQBQwPHMgivirjJPlXAaEpevRZATVbqVkZpSxGUrSWfHxSAiDBBTaKHteQbrPFpEqkQHoYqIfdSPx",
		@"GyRMZYEzbzuIShDZdDEgSwcpnHgMjqnsMnatqafEwhunazQXTNHdsXQoPRsZMYrDxviEfdgByVbpvQVEeEKKihaUAoKjxNLTgIzTrsS",
	];
	return KFDyBIPYbMRKeqHQRKvMV;
}

+ (nonnull NSDictionary *)TNzMpOAdCHix :(nonnull UIImage *)iKVjmubuwTeQhfVFUHnYHB :(nonnull NSData *)UQJSQYwiMus :(nonnull NSData *)pMYergrrTBxvBLYFlcU {
	NSDictionary *LBhKMtiqAAetkpQOkQWMlbtX = @{
		@"zMVUlWHZFcvjFwu": @"AgWhGKRMmoaIzUtAGMRBLjGrNVgeQrXCMFntfNnnvVaLtqLdzHJNpkNEVOnGjLWiOqumOhjdVlKceSNprBXBvWZDAslTfDMSWSBvGMOwTVwxrBYqHphrexDeYJFITjbiVuwg",
		@"wHsxUBDLJPG": @"ycFFGGXuvWoYXyJcDkPnMvxtRZcYlLHiFBkCJYfneBIUYOoLOeIAqlqSZlpdKdwyQysedmeBQXnpMoEulDHkDXwNDqmuuOROsFNHtExTOUJfqwBWYKHBNaPjTDEiCLG",
		@"jhLsbDfbIqMUHjNag": @"VVVOkSDVrgszNMndLFdRcbUXiQzDXEzBSZnNENtVHZbDxrDNyoBiWWcWyqkuTXOnkWZCYqBGUUEyBpgmLejYktFwbHkcYPzjPOxaBMyHkGeizIFMcRl",
		@"fSOexHShDNW": @"plAenrmAAZyYhCymeGAbDtvlGGxzQzWBNlIbwrpOjlmVDjKKzyogOszzjIYzXFrOYjUofVCKdAcoqLZNimhTnEGlKzBZPjjyUTHdIMpuNQvRnsaoMffUWIedbKNpHQtvSrKexzGlmHBt",
		@"ubAqcCFnzFwWhAzgKMHdYPw": @"LCVAjDloBJGHYoDlLyQxXsAEvktDbHxtAMeMmxKMAPcblmNXPgGjeBnWbPWkWLPxvveRFHelqMtnokZvZHJnxsZlDRGIQAJaqADBItxMdvmvATuVCamIUnkqqEYtTKfvEEzpSUeSaJKyBAVftXWN",
		@"eNImQfGkXTnhiKxBYz": @"LBsubxPVMtxqXoGMluuNTpTrhotycSPHPymtGYiFcKmZNGgpCLTzZniuPGLzfglauoGEjpYMqCUPzgELOfHzEjdIOVFXeKLqxDXPNjQAJctOBGeMZQYLZZRWVx",
		@"AnrzjSyjsBVkY": @"kFgMuLKIPeofPCtVOnHmslrQSPBySZLGPrFaJBQLtwRWfbdbQRRplDqeKEcEoCqylhtCuzDPFlDkjJOKibEaJyLeaHaCiaMYKIHugEKZCwFtHhFUlsivEGUqVjuOoemA",
		@"bXsTAcSMsvK": @"dyaxdaikMhNGSlBKOmByRTmFwgQsXvXLxYuiaABouQeffaotYiiMkgaKjHRNZPHtDfjgRzHqzAaBbFpVRxKsdgAiylrGeNdPsTktAEDEnK",
		@"tMntgcbkzbVb": @"ITxZeVqViOUwJUvQLWqnndSjqktusSbXOXlVLFoyDueKbXdjIilExrmuGnkejaPrMiSPZmVrEHtKBhJXoUgiDPveXSEedzmkDTtGuPuIvq",
		@"QCvXjfblxiDmuNmxoPkFhvD": @"uJwTKhwhaFHRpfjkaYKYQQPtHAEvwkEOUYFhKrQtHwaEjwVQjCnHOTtXTmmGyIfwlvdWzTxITVbCWtPvUjTDRdqmiyoenDnfWNvhAvleGiYkmOxyp",
	};
	return LBhKMtiqAAetkpQOkQWMlbtX;
}

- (nonnull NSString *)LuwOGzPdrPfcbGpZUhUB :(nonnull UIImage *)YNFRaYHmyXlPKYd :(nonnull NSArray *)pgrMtYCYnafPv :(nonnull NSDictionary *)cqVCtyCwqrA :(nonnull NSData *)MRiEPqVjxYhSexWYHh :(nonnull UIImage *)iPlXgJeHvLtE {
	NSString *edKTVMqSTE = @"HoFWNHaYBcrDnCWCcwGjdFyZPsVqFXsxMWxJjdbPVrTudbImzWSkIRYsZToPhFVkTDyUoUorFRYIDcQPmBtgkVLmhmjegAjYUyOjweatSXvhyFtOuqNExxcyCOMjDjZLPlQsEZfEUQiq";
	return edKTVMqSTE;
}

- (nonnull NSArray *)bhwyEYwWiDTyzvQuoBjeomm :(nonnull UIImage *)haTwQybDbQHDK :(nonnull NSArray *)IFetyOGciXCJg :(nonnull UIImage *)tvNClpEHvfPPvGvsFnYldHO {
	NSArray *sizkFoMeZqeNPwuohOuzgy = @[
		@"ZiZdpcNpQmDwywbvxdMayojmJgqbGBHPLovKUMQVsDkbyllNqDokaibWhIVtrEypvQqVOTUcQtObkmGEEaycMqLyLWEGUWiTBZxOsFoquatZbASWOlNretDfaCteOVansMKtqWmCabX",
		@"tSQDZXXUiuUwiGlXNIKiYKoebwpDfcNBPYzrqjSMVaKWiXShwcmxtJTcMzhvZOMIhabEoKYVnzrJlnRxOOPXMwdmpTZdNZANvUYzHmyEulCUffGWYyKfkJoFysefvRLSCDcObEAvNEFASxqaazZ",
		@"fQtyLIxvMKhITwogNzlKakGEXxOQsllIkoPtkuRZrviWEdnUxzzOHuArYTBRIwMMVFThnXjuugpeLszwuDgnvEkntkLPKJFXeWAqvUcqe",
		@"qQCnKCXZqhmHWoYVYATWeFVPgMKWbVdsSVUpAXmxAuPKNrEivCcDWeyZWoMCWAuXufYZvjAcDKMLjmFFfbCAwxNvogiOxTVREvQoqFqyXRADOQhmoZCNFijTYjPYBaumwZZNSuMUdc",
		@"KXUiclLliqRNFgZAsofyNIMrYlezLQDmuecPeWYSIbbkYBVgGKCZBopiMYIaxodNbcEHHBbpDgESgUFqopfzyHYHGyHmnFBhNoHSSbaZJMCbCxHSiDNlxqBJwFQBRumYnjaaaZrrIdagNaEmhxzD",
		@"rKysJttwsJOQGPjloEdNJalvYpNOKLgJHMlfKcbMrrCuiCdcrievxqYzCWMXaySGedSqTsLaSmcYAldILgYqruQIvPvOWsrFVlekzWuePZ",
		@"hFKsHcEAbYojhPeXxYelObfaGemqYmaLpduMNUvGGcoRdIPAPgYGaDIQclreiEQNqEBUWSQyOpPZLbhLsHbOPLwopTWblTgGkVXPystWHXVFlqnImTRUjEqIlQkQSqqPUzfazoxQV",
		@"GZLFxHGPKIbquhJnlMalfFbFEZJQsxdmIDnBdBpfySYUlXXNYWffzhctaSRKBXNGBFMOgKUCjDQDxLqlHdMgzjbypJtzgLcSaZDMPhUxzBVPHfT",
		@"VXVEeavypXeYuUewVFMHXVCDLXxdMVtISNRTveksnPYOvGNsQOPrgqeltZVxTLVqAuvkReNdaKaYMcIFgWzLjJeyHobpdbUMuwhmalYzFirOyvVBfjRBpYbrjKkoRgXIplegwgUOL",
		@"TnYwNjOBIXAFIuNoLVwIIyRAJQJcFWvFrcKZOEOYbgGhHYaGeNhgQtqxDyHBJemDjregMFiHLXcyDfBqAqEBxtHydwKWjilpzZdxSTFRkNNsuZxHbnANGmOtFQdCWplZSiTI",
		@"VibcwZOGVuatgONfamgjjhbjPdoXefuQAwRLMKQdNxrIpkunVOVoxzdbLZWChUECgAxUlWUaDlsyyNSBheJjXESbogvXeCdkFJLPChaisqquLUYTQDvYCwjTdmafyJwjymoxDVaSno",
		@"QXLaspCRKBRYnubrxmWWAImDgYpzKdHCICjZCOXAmDlQdawkuQHemHUVoDzPFigsxKPJvlmamtLvTBUefFkNoBiazRUTOVPlHMPFmPESFIwsjFaKmBpVP",
		@"QGgjJshvwwaHmpURfkyTGLfZAokTLzuMAsaWSGQZacabgpLOgdZuNDRPQwhqZWpnXJGkKBAWaEXAsGvSANPLAkgdcYbLTIVKKzEDSfqyQBruUZ",
	];
	return sizkFoMeZqeNPwuohOuzgy;
}

+ (nonnull NSDictionary *)fUUaqJEcSjFo :(nonnull UIImage *)opWPNhmqGxJtyxV {
	NSDictionary *uXpqUatKLEBQdja = @{
		@"qUmTgeGiXDs": @"xhhTYBJSruPhncXkemjGHhKlyJeRNZXZTHuzNOIIDlidUWaqOYHtxrjUDOpteUNfTAWYJXeDxSarXQAPYVdgKUAWeFtyiQibsslPqeMXet",
		@"lxqsOAMVQWYJVHCWA": @"gMITMZCCszwsgJPqdfFzObtiqCjdKbYsjXsjfCxAkcHTNqEMXAgrBkyPISgQOJAtHuCxLdQWvcATOcCcjycFXXoEPERzWKvWTAdABXdCaZEWmPPZNUZiWMMtivWzdCBPNgPxCZhMPS",
		@"qTGIYdbeVBqoPdec": @"ZqbkboGCFuhKOBPYFAahWVKIBlCoGoZwANXsAfTSOtGOeoqaoGmwzFHEBsnriocfPwBQilAwHAyoSclIGuUkxkAYtaHkVexYezSyRGk",
		@"bTbpMOIoert": @"DXZgasEGSPIUGisKfWAwccmxPeeNhdqYvynDUINZIMcUMytDjVBQlPCtQjkFQdbeBrdYuNlMFyXSdWEekucIwlotciVnvSfDVpsMEKtjteseNcqPe",
		@"LQxsMLGDSdquf": @"VJtZszESHDZBydwgqbSUexOwlxDcYoPUDfpvcAjpzdjJNDxiVKBbHLAllprzjdpnQYEjZFtBYNQFXaUTTpFIsdurfOMKXvLyrBBOG",
		@"yBmavoclcjS": @"GfubUObvmpbRFMuisivhcarSdBcBeCgLdyylmNdWhESAYnDlWBGaRdnCGBNQOXPinZveQuEPSHXAxRbbSUVVgpxWxgKZFpoEVccZgakhZoCUBbjxoYlVoqKgtCMVItfmPtVAyEZCpkwAhdLGqY",
		@"UJiknzjJvEkbK": @"MEnbLeUaUmREjKCUlsMdOSHLfFRykdoKUGPJxkQaZVAClqXZbejstdpRZmjDZFZUVdUwcbFcGSdHSzPJPfSrhoAtfbddrIieAbsfrtHXhNlaoeXXfOJGirkwWNMV",
		@"hydihOfWERGvsNMYPq": @"ifmqlAHWHJdgIvddddOiqqUNZWRamfHWllmnKMRWLBwqDCXZsjhHvXZyBFdurEIOzlmPFQVCqYTsubTEfINlNvGLQAapmkITviUnDEOnWKiBEcwjvRwFxkodvprmnyMAvlwmsjucWbkag",
		@"seIJpZqchEpERXvlnRhBu": @"ZLEQctspEduRlXnWzjWXzOmfKKDPXdPuTMbVhNJcvVHnCUUGMYBjKobNvVAKOXlRtzJoBjcEJtbgfwBozVzhsKoXhgwfUMfODXOwsHdgyYpuucO",
		@"QwtLrXFczehuwd": @"gPBfINxwhKqPrMkFmdLMRIDsIDySYKYmyyEYsBSGlYcCxDsjqcscMTqDEEJIWyobMLdMnusDYjfihwHtQBQEhnnBrDnzGnSJRFNnxNeL",
		@"aXpVPMjYRG": @"lCPfCxzFsxhrfUySIdbvsMeJPmYICYqpyBKQgeNpkRZpiPLHvnGEGKbcBytLMmLeQhKXtELhwKbAsVjRexYkMnUovsZUVTMZgJKkiWdoBmPhJZQwshl",
		@"vgYYskIfUQNJvDayri": @"HcqbywKNMKcQAwXVMENfReQlgGVzQwumHFpzhOSoRovoUPZiExAWgFLYlhnGyPlMJJuGJrJkMUaxuJlNbPCykogyPfVAFRFvjwEJYt",
		@"aREAwrsRnSlEo": @"uwNWsBIKnJcJINgDQttkLxDwlzHBIYEzHuPswcMQsbgIFIZpTjdpQElCrpSbUSZZahRSDZGNHlXdfQETuLRKrKVackzsSUEcMWPrj",
		@"INDqTMGBZISlCAS": @"xhrgdJdGuoJCCPdvgZPHqrItEusrOorvkdCwaEarQMufxUtfpSgiCWKcLievbKZOUdTCOXIxMmsgcugUweQZYDCSSKWJYIebfaabVLdRIgvSVlfZbqbsiyJO",
	};
	return uXpqUatKLEBQdja;
}

+ (CTFontRef)bundledFontNamed:(NSString *)name size:(CGFloat)size
{
    // Adapted from http://stackoverflow.com/questions/2703085/how-can-you-load-a-font-ttf-from-a-file-using-core-text
    NSString *path = [[NSBundle mainBundle] pathForResource:name ofType:@"ttf"];
    CFURLRef url = CFURLCreateWithFileSystemPath(kCFAllocatorDefault, (CFStringRef)path, kCFURLPOSIXPathStyle, false);
    CGDataProviderRef dataProvider = CGDataProviderCreateWithURL(url);
    CGFontRef theCGFont = CGFontCreateWithDataProvider(dataProvider);
    CTFontRef result = CTFontCreateWithGraphicsFont(theCGFont, size, NULL, NULL);
    CFRelease(theCGFont);
    CFRelease(dataProvider);
    CFRelease(url);
    return result;    
}

@end
