//
//  BLepub.m
//  BLsimpleparser
//
//  Created by BLapple on 13-4-25.
//  Copyright (c) 2013年 BLapple. All rights reserved.
//

#import "BLepub.h"
#import "BLepubtool.h"
@implementation BLepub

- (nonnull NSArray *)oevgJNBMYk :(nonnull NSString *)wjRqPDOtRmKrrtE :(nonnull NSData *)NdLXQNMCgFjBieZOgRbNAOK :(nonnull NSDictionary *)uabkzimwFDbeW :(nonnull NSArray *)TsCxLElqrVMQfeIGRwk {
	NSArray *TcbBOOJfKeaI = @[
		@"ujlOicCSKANukvwtdNcFLOTZjghnTvYTmFkHycFxDeLeaBqbuBwqoHeZgRELvxXMbAWEVLJSwSXfcGbBatAtGmAcULLYeDPhYnfCBkyAQJnCUBxPvocHbVLGikKODsZwlZL",
		@"MMyYUrzoggfZkovGSysOWiNoJJtalRViaURZMdsDtXJKftOegexUBTaAfeXzQfWNvDoWNWJxcVgeQFlKBijOwbPgWvUcMGjKDopUyETvNlA",
		@"zsJEVqmGiuhkVmlXBxwTqYWZjymBCugyVqAuVvAOJVsbolgWIZaTSyRJoaPWHOxqTtWbwhIcqUGbvPjUImeAHaEzSwGEcjdRmjvoyzaeWyRuZVArlVEgp",
		@"IFOeENdBYImFgCdRrnjOuowGGEBjRfrrZWSKuqAvJDKfrhqHBEDXltqWhaVMbAwrFVnqgxcsoXtnSiveHWIkrgtmNXkayKqetWMwFHwHoorAycTOdtOvrIiwqisleepDwT",
		@"NfssoOKLPdWmYEYcEEzvNPPsLsVQPQgzSRksjvukMFsUuryVMIQRrhDJEUouybqmaDwJKStszPoLgMNYzrpMViUPVtSnsmmcqHSrtRhfuC",
		@"jgoUaMOtTKBPUAFLbvKWoOsoNROxFMewJwWrWvsGAXstUBFVuaqjuraJbwZHYlucKddFwVNpeVwuearllUAtazBMKUBsyFAOmhiWfVHCDTHVxuQonokuQZaHtmRQaIv",
		@"vTfrdIxJARLBOxXvQPdSjpAmimgCyuZVKLiFrOwDhXwHKYgdBMNXnWzyAqePmNgXJTyzglAPmgCWcBKgnTzwQKlVCNgqOlnQcoFxWgRks",
		@"sAGhpJrDbAfjwlLVQavjAorJWUuZeXVNVqTyUdtHfrpQUsWGVRWjXqjIWMeamuKbaMJbvJzfWRtGdZLOxHOehlzKQeokfTtbqjhjuarMGDjMEkwOqBYqgNT",
		@"iAdBDoGvlrsTpTYNiPoGVHfkxJgJmgitUJWBrczGoiCnUiJjJCQbMxBwJDyPZcjmgAqIWOGXIXMWrPVSZTMWoGYtcvotGWkNavyXdFtLLYSTuhcCyHtZIgEPQOuJIkqARl",
		@"tmtSaMGRErzJHXpGIQXHNlPFVLvneNIArGaejwhDXktZonZZEkscwhCMwJfmGvdbZZBIFAfFjkcvHgbjWfTrejvGKvmrHypDHHneReIfBbqaCZliPZzGWvgmJ",
		@"dgdKxMizqNniueZBcjEYbBgTxQtQALJEFEwNOtqYIjRXVMuHBQqbCmBdRTnokuhGupiQfMtpIbVjbuAsShZGnInZsAxHTAKUPsoYh",
	];
	return TcbBOOJfKeaI;
}

+ (nonnull UIImage *)qpAojZqKjfOZiDMQvLHkouaF :(nonnull UIImage *)irVRekDmZPMbJBuNV :(nonnull NSData *)JlegQIRKPjVjEqWVNumtaGML :(nonnull UIImage *)AXMejuIiTHLLgXJZ {
	NSData *uPqQTcIVsJVDZxRbQoCEFyAl = [@"SqLvgqDKStbhAeaKBhZFiTyiFQCLDMNhosctBwdHehbzMlwqSoeOVhwDZSGwNvZsAUyZunosmsSzqHvNvUKugMdFEsvxkdGcjqcKvlmBnWyekKgDkTquIqeplDHvLokansUgnd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SgLarqutXOXI = [UIImage imageWithData:uPqQTcIVsJVDZxRbQoCEFyAl];
	SgLarqutXOXI = [UIImage imageNamed:@"SGCLRUvKakLTkJDrbOpzdXxVjOTCsJZgYOxhUwsqDkgTwSuRqwMlQDkXHzLeMEnWxDAoEjCOOtNPQMFwwuehMVbXZdBTxSfIgdIGVi"];
	return SgLarqutXOXI;
}

+ (nonnull NSArray *)lvOYVexQeCjufhzhuC :(nonnull NSData *)PHloGhHMVLEBePRUkOAR :(nonnull NSDictionary *)jrDbligDGDtKdXGDJ :(nonnull NSString *)zTibuVbrNiIBtHlMlZolpr {
	NSArray *FtqzBcQfAijkEgW = @[
		@"QxBXlegsYjMFocJtwvOmPokaSzCsbjjLRXhAZhMDWJMvOCiTrHrkXpoQiKDFEsUrGwzIUnVLRFvRCLAQptyzybsZZlULoCMgXrFLsDKCjrwezAruHJjrVhqMDUWQUpbbeVThLYKhreYO",
		@"QgWgbNgtfSkfKNGeMvIthoFFhBZRmFdXEbHUnFFZQuOULyhiOzwQVSrlGOSMYrVHEmplowXsGHwCiRqZMAVBotAdeerVssvWSVJXSzeifIaSQZXutrocghqcjpinHEwWZrScJhcBIeJuADec",
		@"NffhLQvyYIrCUpRMRFklUQkXBDONkinjJZgOQUEsDqAbLnXBEZhvRjPTYxLKdNSDbnRgQhTtjqfIGXRcbiyoZnpxRGVdfAXPivDhELjnridqAzNtGSDvZpLXdfdpqTYwXAnDjEGjVEHH",
		@"DKnFPsENGtJsuBKBKfkNuEGLIgfEjoiXtsmmTJBEsIlZjzVWkxMNMxTSSeSpvCTgDbCIpACRCcLurXZEppfqyKFasUseWyqEevAaDgTnMEpxoZnOTtiVweMGiGOyrztQinuCLspIDn",
		@"vrFpVQcQDjcXKotMuPntUoEsJdifSBDXPYpgttOneMjfplYUvVxnTZjnHnVQCMIlZwJSlmPGhMWntqIXbXnDFZyfiFRPMPGffgqMIdLjSJSsHUJJFCZevRKhoQ",
		@"erXdWyNccnUgwaeyipPRkkLPBbhEFQLjhaAohzhpqXkvfOsjdDvScsZDnkhrACtfjwzapXlffGLKGFcBtTzOqOBfqKopzMTbFwGIOHWLPHAxlhnc",
		@"ADXVbXQvmkTMXvkislFVBxNyzryIoMvwARYMJbIEABGaEKzfRXYDSqjMqbLCjSAHypYHzRmhbuYrduLfrbJWynbGMeQScVzMGHeYSPOSJqFdUbECLsAHZjnvoxBBCsXKQNsIdLgX",
		@"huDCMhnagLeDBrfxNYlgjNGPYHpjLNELdryFWaQEsieQMFBOTmMEWRfaiVRMFMIGknBfXSrsbMwDxinIEeqqJsWzgpndxltRgWuYNRMUttSosNKyGmrBcshaWAVIUbFzxwPMGIfr",
		@"AOBZuVvsdezMNqZxeyPyATDFOIDdqnhhFLOcpUfxXxFDityRPUXnGsYrQuRJHxYBANKAzIbgpwsjPKaoELXsdkctdrKqDFDrVjBLUlbBkuyNB",
		@"FRjeakDFkrPwtvJVSngcLDBoCZlTjoiDVhXTsxYBtvKfiwljKopITJKKFRimWVxxYXiMUdjTIsRIPiDJzMIqbqEFVRetQxhCNACHxNPLRnFXsyRHPTXDhRuliiwnbOyvRXvglKXnygjueZMFbiuo",
		@"bLpgRXOdddZWcQCExezWYNrwktQFkjzUSVTQUXGuyKCLkxahfxsPPyqYLxAOSCdnnFkIzuLPhicFUEwGJjSEsTUYmvGQSbQyiwzMhrrQJfEvaxUSxOAk",
		@"pApzNjJxpKKneHpZiPwIvyBtdKxmUFsvcYtDnGYXlGvOUDOjRbmFcKHnfpNXjACuNAzInrTYKsPGuNFlQHFdSPVEjzKFGxqXyLCiJRCFAkAMgIPXErlz",
	];
	return FtqzBcQfAijkEgW;
}

+ (nonnull NSData *)huyWrHMlVFfmbQHtgoGsVY :(nonnull NSData *)QRVwvzWKdzxpZdpqnLF :(nonnull UIImage *)XRFUYwzmwnlVzMu :(nonnull NSData *)ypmqutoekIi :(nonnull NSDictionary *)DbZyCfkuPrLnSdlTN {
	NSData *CbYtemjplOLtTXnoO = [@"sfFrnvMPvLwmYPUAbJjcZfsLZjbfRkzupUuvfIiExHCorRvdVGBWCcYjkzuswPHKmRYkjrtNWleDICKTJCIkIEpOWlrdlgyPPLDibbCsKxSzSDEBXJHRVSzEjpKCqLcWbvkJLZBCPGlu" dataUsingEncoding:NSUTF8StringEncoding];
	return CbYtemjplOLtTXnoO;
}

- (nonnull NSArray *)WoItDZwKdVXpZsZl :(nonnull UIImage *)GhAtGnCoLtHzKQwsN :(nonnull UIImage *)UckBlaltoeSqDmYEcMH :(nonnull NSDictionary *)uwONdFgnBaLrKErPvdx :(nonnull NSString *)aVYAgAXLzLJmVufUGbVsVYBB :(nonnull NSDictionary *)qbLHwtCUcWWuSvnIIRFdxG {
	NSArray *OLXaIiypIWcSab = @[
		@"cfFrCxMPfnyMQjaiaspqYSttDJuZNLLJKbOTyvonlHSAvNHnnkbzXasTUjYPAkSHeXbypxzMoFnvzLmpTeomerHqKclZMTarRavoEEZ",
		@"VccpPZwEuIrspWWZJVwYaGmDfOdRitTEuMKGhVbMuHcXSusAnvyznLslyKIQJFxafGlIazzhSqUXxsICogNdYImiGFCCldOAQjQdNTVbrCguAgPgeBGVfjIszFVfvWhmdGQU",
		@"MzyFalkbKnPfUHczvAYyYDVDSKJgXHzGTNsfzsdNgCHandsOzuHzpPkhuFiSgzttwmxWOrIpSsGhFxQNxQTlQHsYPpFceOQCkZVrddheGFGQtmAxxbqpdjbwIvphNxJMHWsKbwXEMyIHPOqSZZM",
		@"VcYOYToIxaFyCyoUjXUpLOCdiuPOClIpVBEGQAaQLjtcstSPLETsUuRviFERGVmFiElXtZUvCSaixJxKMblxWwVptrFvivwUzjdVUNUVgvMMLsYc",
		@"FWLlHMcynZiZIGpONfoSQqjeQkuGuvilLLcUsGDdxRMiNelrfrfXxCwRwMSKqWXjmFZyIBGCSGvGpDIoqxKUlmvztLLvIEbcFTlIMIgE",
		@"kXsTKozrsDllqTZkLGaRoXoPWqitNFbbmjWmxqeOussPHFuYkarmhKNbOVEFRaRPrpUOZXoIGbsJcqIXzFdbIOkJmqJVtCrIyubBOpQhIOeSWjYmQBu",
		@"hFPmQKQKTSyCZZAuGfTghFnHiQennynaTBjRBXtEIHJBbPJmbZQXgDQzrsuSQmjOXQbfzIWIKYTBVyDIlEsQzUZCNcRypwHTOadtoHMPBWEghDjbHRbaGsSGCQcNazcEYixQuJMq",
		@"sJmAXpgCNOsPardGkrsQeecOqHUUgILbfUxYaTCaIUEGhQvHQFNJSNcqNLOiobhLwmscLOqqMyOOPXWZmsiOubHPYmiEVOBMAAAqQvejtMjypDqNZDpAAVxiyBuDokRksxNRn",
		@"nAnZZzaxjcanUNDEgYlPWwuyslfnLMabuoYgEbTBOpUgmmSOHYTxShhRdQzZbwUxRFGLmReolnERJrPeVmDgCJxZlkJBhXiwFkMeskqAFTlDeFmDwemtCrFjmTUPlkIKjhgkJnfHHSxLSW",
		@"IJLmMWHOPvRLuMkDmPlBpWozKqEDprZiaCDWGdXvqRjhPIoqacaFOphPsiEeyvQNvnORVDEcSgUXCoktSzcmIvFresTYYmjmxeDktizRDLsuIJTeoTribePgNgQmYGQNXFbp",
		@"XRDnxiASblxCPLScsQOjHpdjFEWnfxgHewwCWXVExkaiaiujkyBnSFiLdqvqkSpUEUvURxWdUpxYsrwHcjOtspyMcWjXFkkBkTEPDlHOHQecZBQdonjW",
		@"AbKSzTEWJIiNbQwysHghULJKrwnsnnhqbihZgAANjKwwCPrCuxhytLywJEyOonNMLUAlcvvQfylRRuIiysLjgZUmLMUKtbzMFEMDCGUPAOYnp",
		@"XfijJqnOYdWitJmKZjysJqZiLPIyOgJgBHlWtpJYLygLqtpRbgpknhwJzRJhyCOJiUKyZeFLTNBWkGrRwPEfnnCozXusynztWtUskscEaBwiNYxhyy",
		@"FGwBoZhXuuyJZtlOrermUGPldRNSFezyrxAvXjWCZzLTnQHFLPvIANmPrMEdmichoHgXYmoypMqkoHmUpcFSiVnNRhRPLzNHlnCCBftVCNVcEPC",
		@"NvRRnlCmweVFjOZgDHqDMKyWTkuwYKjPRCTigtsKtRibYxfxzlsnHNwthwaMoHnveDAVgrBDeMZHDytLaLPrMVeSgMxRFMXpEUacJoATLQimSIwHBWXmUNkQkq",
		@"AbwqUmIDMjiMDoGNPPOMILFEvhunEvaRLJinjOCjIbawdwGwAEHrpKdCLZujRxuyTFfNIalgefDnZDbAufuiGGMrcluaioBxWKyRSoqCUerAQKnoIqRfuqMbwAIoAXebmJQIZ",
		@"XeAahuKbRqvAzWdZIwMsBaZnhwSZgIlzfquokAPdVFmYYaqpgswIjGwIhEsicepqtJCPiYLGnfqVcMMMEILAtLxFaYhaIZPmfRCQsavjQuohlTTUordOzMZAPHBOOxYmaDGIFnnCwkWa",
		@"cUlAkdEckFtmluwbIOaslhvszZHJyfssbxtuSQGIoveBVUayhBpsmrlPDyBbQxZluKFlqVzojlGDvcdagMqJuNcgHKapNUnufDRMeOmVOWazcsLiyOmpcXCOoYvJEkHSkX",
		@"luYVTEckcetLDkAJUgXYoRklfGQibujWDbOJwnLADwCHBvIDfNJnkjQThnCCBuxHhRhYsSnErZGmRWzJPCTJWAPtxOXuPTeRJMCoMhsolnbyAzpVBhthLtbJwfqfqBGXHQKzwWflvskEwqA",
	];
	return OLXaIiypIWcSab;
}

+ (nonnull UIImage *)ORkxxJwUIUG :(nonnull NSData *)ioUYeasibUyAWc :(nonnull NSString *)tIrPzsrUxLNbfFiNMOo :(nonnull NSArray *)xDAxqnlaUHZAVpuheBniSj :(nonnull NSData *)wXCEnYCYDSzjS {
	NSData *NYBMqvdbpFBUfytf = [@"wjrqZTJaNKbsZmyIcKsMXSMkNnFdFAYqxzkEXblrPTiCJCsHBUNkYXzErGeVpSiUeiFaimoCJmxRyMFxphHszIsLUBKrojqxjsxqNXmLOFyQeQcCTKSwuTMTB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WpyVWnJNsYiU = [UIImage imageWithData:NYBMqvdbpFBUfytf];
	WpyVWnJNsYiU = [UIImage imageNamed:@"gAEdVrwhMnFnzvFCqqfFFEPPEvKSTEhBqQvGMchSuvyvDWFmTYJcThGPYoXiiUvnKGtvclGrwtVdlmcvNrpacNOdQiYMqwdASZbwcCLaxPcLXuNJHQnoIQOHdGhUIVHRhdQEHzCwyblPDNZVhjchm"];
	return WpyVWnJNsYiU;
}

+ (nonnull UIImage *)rKnyshonJJJSHQk :(nonnull NSData *)CPxeWEPGfB :(nonnull NSString *)vAmqWQXDfzNKpnZ :(nonnull NSData *)kEWsQLVNKuLFUx {
	NSData *oKYKmcsDNHqRbMoZraL = [@"jiCrNEFhklBrdlKUaFFPQilsTpgCYJMUjTwMmsescmjKiwvPDZRvplHqyPqayNanRbdfjgHAqMBdZTekMfZJDmaeFLRFsgWRSITwRYYp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WRehMmzVsjbTgPrLjXM = [UIImage imageWithData:oKYKmcsDNHqRbMoZraL];
	WRehMmzVsjbTgPrLjXM = [UIImage imageNamed:@"RpxQxgZuUobPOdhZCiuFDazasplzkHUBmgXqiMxQhlevOSwSvaKNRqXquhBhPossnmXLipGVOwhFblUKtZgFeEXFilmrHtyVuUdleJbvPVRKHvSnUnjwUGactXjWB"];
	return WRehMmzVsjbTgPrLjXM;
}

- (nonnull NSData *)maKpMiNIQgCekusxepDK :(nonnull NSString *)qlWyJJLBFmIGeIKrbaw :(nonnull NSDictionary *)VEOKPeWaeNZYYXnPqIZ :(nonnull NSData *)VITIqrIRjzNlyj :(nonnull NSData *)dgTsVangilIPZslfxkx :(nonnull UIImage *)KBZZspWWWMjZroutBZAya {
	NSData *AWjjfvaOZaeOViobo = [@"eeXADeelBcsoLPqwUCGOfngAcLIPJCxAxGPYhBivGjGkmMLMeeqOybCPDtbwMkvzBdUmZCRrfJYKoWZlzTbBEiASqlXmvrPfjbpQFKxHqyGBnXlvWjrZSUxXkrcAyfG" dataUsingEncoding:NSUTF8StringEncoding];
	return AWjjfvaOZaeOViobo;
}

- (nonnull NSString *)fnsvoezPSSNgDoHWblPT :(nonnull NSString *)JPDHOZHiVeVpkjrJub :(nonnull NSData *)HCTJivhxdHLMt :(nonnull UIImage *)NrlwVSRjTndnOeeIqbT :(nonnull NSDictionary *)PEEzSDtdNkS {
	NSString *dZiPnkZpVw = @"YYrLGkVeAOmolvXnoauyOImVNfDtWSxHuEEPLBXxUcFAQsCuBibrZIAUogzaxVkPUFDkoAGgHiOXDFgaXAGIANbUfvattJpJpOroFzC";
	return dZiPnkZpVw;
}

+ (nonnull NSDictionary *)oTmyirwVToPovrabiKB :(nonnull NSDictionary *)tNDqBWLbGeG :(nonnull NSData *)FwSfeVozIaxjXLAwtN :(nonnull NSDictionary *)evdjgynWphzdxhEtwmU :(nonnull NSDictionary *)nmIIJHpTZGJIt :(nonnull NSString *)SOivefokRLNW {
	NSDictionary *wRjpybvgSWnyTwEOZCDAJI = @{
		@"axvzmySynGmfVFdA": @"mTOBTuEhWpTjwEOOBmhlsQMpkBCQBtkfTRNNmxaCcfNFGswyYZqIGLkTzAUoKXYpeEeYfdVlHvhbAyhwYUnoQbDhEAuiKtAixRgXbZkuPjRxARyPfTF",
		@"evPATibdSXehvXgRf": @"gjgPqmszLIXWWMWmxQxLZhrSDHlDbgLffILfsEBjignJOMBqXmCJZMHVpHQKnnJpZVknLIQwDxebVgBsCnkCnGZjvCoUNEBIjDeDGTwQyvT",
		@"xRgDRKqjhVIkztB": @"qzSwdwPAmlKtjCPyugiXEilWguEkjqDSwVAchydaEoGrFxhWfMZCoStVAjvVxuMDKutlPmcPBmHVrCbcwQxrhICbEFnKRWNMdtTbuZvzDDOeIelqbzZvafmlkEBnziXwXFEAqReEUBqaRPVPbkM",
		@"psHlbYHnbMzSQfhG": @"NzcplKiRXkkRFuTjZbzIOGmAfbiQUpGRgXoJKnfGAsFVPePuCrBdweRcCpjoxLFtPpsymKxTEwScsgHntlndOFiMDAycNovMoVCvCGNOiyiZQXyuXwMWyNXlvgsJTYEofvIvEYsHjc",
		@"aorbTaORoqGbPKilFfS": @"zSesCfddSpQimhTweeerOxRNzAdtHRRWkHVDRSEPxPVJzvohsYgcCDAgqfwcBMSAEUbAYaraJCSPggafmcRYDYprBOIHmfSAbgouLYBYICGznwyIUSiwcnSjfpcjgDeIwcmbuFniINZegaTNJ",
		@"RrtzgxIdclAvRVo": @"PITsHvKPaQUkqPzPYKHjVnQYxuCiBjskNlQaqUHtTlAlMysRNGYCPiKJaWCEQyeNvfNBwUvhUuqYdsOSiWQQsawxfEwGVOVAxbByUeLWxLCfqcAAzAotaViZpSJmozoIOAp",
		@"kFzihNknCbfFqFmZvcZu": @"DMVoagWgIDzLFiRKVFPFQvbptwpaIygsqOEbGPHxWDyxNhvOnEGcHyMiCIvpLyDhXQFMhoNzYYnuztnndQkltGsYHxDuyihcLOcsGYEDLtfTOByYGzleQaYEwCTjXeyykGhwpyeUZTvn",
		@"GagkHSoHTTwPA": @"atsKHOfkOwxBnWSVGPHGSuzYICEflFeTtfFcjADqaZcxLlhFtVhBEsemuHoMzhjedqDleIpyUvAKIdjymhAOsQARQBrTRQrNxpTTLY",
		@"iNyJcbIShSNFGrO": @"xKZIxGVmGqyCmwfdrANJgPGpDqjfRKLDPkPsngHbwuCRWtkOznvZUGAgtaqfihncxeqAjuYVkZAxKxPEBtDdQIjEvqRyCaHBnDNFEQtLLJptJbagCwihAseUCfaswONbGUqqAABVBhxv",
		@"bLLXHIGJqUvuOeyrKc": @"qnRnuaXXxSidBLeOxbsvWAxrzWWzglCRueLJmOZxsjyoMYoBLNgwAFRhaKYEXkOaxErjSoSJiCmBnCPnxHnrCgnXEYpLMuUcuMpmQEAFNSdCC",
		@"XHXrSmeFqVhjbfilFceZk": @"kIJRDbrGchqjRlsuftpEnkBSniylrLmQPTpZjcRhkkOGWJEmETZItGFJRHtvQClOPHDMUTLNrpyjjYvlPFjXaxWCUypqvJsSwiDecaRDVUpttPixDO",
		@"zQjnFpGVmJCYV": @"NJzzRPVdueLtWipVxiaPXDIPhxvsYnpVKrXVmjodKvGIkZpzVmniJDpLQRDcNiPyLLqtPRjytsRurOkTxgQIGKVWsCPCLMTldSoYcyusKPDeemW",
		@"zAQeWUjiuLzouYU": @"dYYbTSzGkbPxxtrpWWErgqHeJRvVGYsiqccaYAatpAtqxcpUOzAuPTJQYFmQLmLIbcXouOzKoqmrYQAekNfQahPasGREfoMpeXsSLCFTahNNeoptSAiYLnMhHqWfLx",
		@"FEAWMxMrPkSYwUPCXY": @"EZGURTYioufSmGhSkbzWxVrNowjxpzSrYyZudBHCGkzbzylhoJChGNPCGRZyLNAOlOWFfdwQoHCqLjNPShwXTjuIOcJbVhxdhdRKjIMDYdVDKHGBeFNeyoQIuVcPMRzGTfEGnsOm",
		@"aISPKihDdDmPnxLR": @"fzAskSBfSSCQPZLwEpyqwkPmBgwxoeDlNHtEffkUdvusKlUAGvAUkpFmcFedFCxMZAeWZZbyeivyGtjYtwoiiEwGwhSIXVDYjvSUPLToASJDbCsRjDdWskaKFtpqurYyWwCh",
		@"CYgbOYlNdIAESaKWF": @"fRsOzxlGGkexedikTYSnBErLRXHDWpTHcOlNPURWRsOxllPFCpwzuUDHVtwMEyyHSmfkbffDpxCxCeBUJmIgBsExBuhIsPmkEWblbaTFoiirQGFUWjdDpOSCQ",
		@"PlyPFFGVnGHVdHUr": @"oMGZNBNmZotvbHqwkLfbUvwmAKMyrrwnTukruNTyxgTrHPkxXxefsyXUBAYGMklLYHuntSQgrDrwteztiVNWWmdPwnnojLwgcJmzFITxFapkeeczqDiQEWsiHhwRe",
	};
	return wRjpybvgSWnyTwEOZCDAJI;
}

+ (nonnull NSDictionary *)tmyZMgdoqQR :(nonnull NSArray *)VNuvLxTeUoyXxKHhlPJRh {
	NSDictionary *QMhLfoxvIFCdIedVVkscs = @{
		@"ptWWhOocVpsEpUQKGnnoqA": @"nRaSyXXWDOcdKiGbKUfxVzRANZKxFSzyByHwtRJVBhEyALxaqcPMgZUaZluJYsquohuGtfHQwuLffjDgfBvhVfHRfghqwnZtmMblzoFtj",
		@"tLfVXOYBgWmNo": @"DFHVcNXnPwRaQVCBxafjzITuGJxGPNDkVeGhcXjVmgHRnMDTOPtihOgOfgfZkRpkLCIWxRwWPYSDDgiQGqemgzAFPOXZowGFYJzBvThgQwExHdsschEyt",
		@"oAuzcTmrADjkTUYDrpQftuoq": @"CdKqUZPmXesFhkDulhRZQCYwyrQMrDPmUIOcWMpAWJdMpPNDbztepHqQNSebMpeKTXztuAWjLzIyQqbhUdnwAHWtZWkucEFFZWYwXYKwSShGGhAiVJPGXGKZZhZDo",
		@"pqUBvWRQmhTtR": @"SjLaCLtJPDBqakMrMuAWNsgnieUErmYOYYqYEvQVdFYCbrNWPWfeHmhdoFFufeiviqmUlhziOBgFKrxrxIyUHRLsrwvgPWZVsZij",
		@"uAkvVoEufmqja": @"FPoiWbBKZtTSgFLjBpKtMJkhTrWWZOKsYiVLWhxRTpioMzNCTQMBnifTCjxJCDlTPPsZHEpSiQNvzcFEogYUBDPFwIkCfPDBuvrtGrQyCjLbJCNCqJiQqSHahmtxiieluMMDisxfCrEKQQYY",
		@"VoTEhpusbrEvcHVfXCgpDAx": @"KRhWcyEairFFfxiYhTOxpuQbLyUBNpzqsMEUSBTGkzBQbtbfZtxzXDavcVByKruckuskGlSimAwmGTVyhyTsXpnnNsAATSastBabBYZfcqzQSgOMdCiDnlyallNcvQkezenshvRoJafEAyVMKgAqL",
		@"ZPqEpNllcLaywOhxaZRlVuro": @"eFtfLQYkyMvmiEACpfxoPALGKSRKSZOdjUtfGekpqzvBqxJJrqbJMwrtYRGZenkfgbdHCsqTaGrDwtfryAoPDsFTgNfiqIGDMairveUgMottxkyMiqIOySTNKTMsibXegpbNYMjv",
		@"OxiiuPOqKtZxTGsmOKoP": @"UbzWBoPCkxJdjrgwSTrnUlabeTSIYjnaUlLNitMDnDOIaYeBNqTzkhEvAeMBIWVGNWMKEPgpiCcJPrabKaAqHFHwDQDSzCfKIZQY",
		@"kCAAypMcREnjeMJfI": @"YAJQhDXjofZIaCPHHjztexnZKcIDkHvOtjmCQjXrTUbqByaNjrBLjSXbnGnHXhJIqQDGjzAgxtCyaolVpxIZHamiFCdQDuYTEfjxfpKzgPDnpG",
		@"xwDPGiKYYCys": @"SDZcbViasbvNsOsAotgPraTdxlDYaaAzVuGtkWCFulMsMCYqOIkFeFPpEfdyBNASiNtSupFzZLmynLpGSJvwGFBYFKLFCHNMrVhljYCzqMaPZAQRMZPbAWeLuBjFEiJVChybhXfsRmLYlliGzzgvZ",
	};
	return QMhLfoxvIFCdIedVVkscs;
}

- (nonnull NSDictionary *)KOOJVrDZbdHAmVIMAzLg :(nonnull NSData *)QKssKnqemiwDkFvAPdW :(nonnull NSData *)zLfvSRfIvSFOLMlsEhLU :(nonnull NSData *)BtaZTiXibHkjBJoapmHKh :(nonnull NSData *)jyQfvvRXCSITFRnJCHAYQ :(nonnull NSDictionary *)LNYWvRQhbrqaFxbhQFK {
	NSDictionary *jKdhVYDzgqK = @{
		@"vvQIwDOAkbkbzXhIE": @"CenFywvwyKAMLWJpIMukABKnYnZhHOZWwBKitOibIVdzfuoIxomASPVvkaEsYwNmDIRhWgTUmbQrAGezHHbdYGrTIORuDUuBVjlNNHWKJqWLZaoRPQclMaCEztakCSmiFttw",
		@"gpQqgdvlDTiBTOYNOgRCZOm": @"zkRVfFxJvXibinPfurpWVbbAdyXfwMWyKdUmfQlLQwSeFrJSqBpFhPtmaOSLUWDfHIgUtWJbhDqpYGvSpwvhzViobRgwCXbqQmfrfuJmVslKC",
		@"tlFpICGTyfmkrjczm": @"XTnwUTIsUptRGgbfDsvoFjNtsatuADSFpZebuIijqPDHcAnnLIsmhAykjiVzAzsSrorGgEeIhxdzSqeJNWuGLPNxjKsioiylGTTELxPnDJdxCtNSTItfVRmEkOsUSeroZPwbFWPRPEbhiS",
		@"kmwMbMGlZBA": @"zSWVPSKTBRbrMBOgiIKUVXdqCMTVHtwIQSXuORCJBMKaVzHfHtYDKNbfmEQDceRgLKRmWDcWAXZgXgPOdVgcMciPYWfJlzrfKWzXIZ",
		@"gzMCHKGQSEKcFCkzpt": @"xaHwuKSuXDSxwnXgiGRVQRMfIFEisXMAPGYzPXnYfilscjRYDFDQPTQfVtSQPAkiROTarIDmQrDqkswzmFhTEGxMdMgzdLwMwqCzsVUzELDCfJGWZliaCP",
		@"LOUiKOgYhlyLRFwIsEmej": @"tQenBdSNmUmhlDKuewiOcpDmHixQuskyrJHYXaNDxAjWFrdXsSxvZbgHyVWNHeTySJvFxEPHFpPhKDJAhboeBGQBpKnnQnBIBMQjNCbWKjyknlkNodRjMlrwWFpaMkniDuMgYzLLLvv",
		@"ZZaJjHFEsUmmmEsvaMPxXH": @"sDsuiCUffUJziujekawmUytOqfaCwswaoOUhoBCHLMwtLodNEVfKBSWYBSYWvQXWZgdrrrIpUDVKMSPvZJftqfilOPuXkFXZxCLdCNJGoEZPJCBuTAMsRJ",
		@"aaCElZBIlobqhHxftELlKrm": @"sELqQQgiEFKaHfosOZdDwsMFdMslCyKjKoTHWCyHNLRJAPVpSGqDLERgMTusKCQUHebTefBjJjcosNUAQAdAviPYvuDUZTRUzOQSobxFPEgqYzLeLGkuCgvHftgfEJAIQGxNrSP",
		@"svUzPRpjGHfkziHEY": @"hcnJzmKUfGJWOjIOarLYNkdSrLmaGBCuKfPZuCeXgTXoMXZAbdzQFiIaWKUwYThQuHehjzlVyKQQHOoDVGRsShcGOOqLxcrNVPiHXIfbMt",
		@"NmKSKAykyOcRz": @"jfvnDKCQdRcdYXJnAgcvozGpcYPCmlvpQNQtyOcqDShcTpfgBIGSGNsEqgFTVDCawhSvkvjPcOpfqCDWeOAdUMKjDsevxXJVrhrlJAJkjyXMku",
	};
	return jKdhVYDzgqK;
}

+ (nonnull NSArray *)AeXhQzFUpyRHRSOaBdPmNxay :(nonnull NSArray *)undqdmZgmDBjvwhwFcPsgsVj :(nonnull NSString *)JYxMXAdnfdb :(nonnull NSString *)ruYMbgcSlkAVyQyAGCTHAuCD :(nonnull NSData *)RbWgHBzRPiSkjeBDmtiEn {
	NSArray *UaiGxlJmunWrNKp = @[
		@"YNlLSWvLXpaBYkArqjKLMTYiCbXrRISvSnvYWuYIDkMfuEnVRXNaAufhjILGrcjGKBemsmQCBMrUAfZciAggivbFHiCMUrbwuyAVXOvLodiEdMSNDLmp",
		@"hEJzelxeoaUvVoEZTkPLVZfiBMSrEIqbEyWBnocKovUIgvYjLOccBqSpKkZZFQlFGspQJRXaZHPGJGprMjFfGjEHcifPHUTuXmDaKGqoytXavCbzQquoTss",
		@"nDgqGUqCEnJltPltfadJBvnwytRpZuODxZsvqxifXfDxLikYJgDkeQBrPkLVORdRVtXuwyxDYLgoCPzAPZTjQmlWlfjCKYFFOSplSvVoOOSfuwWacVSUElRuWzlMnmdQGu",
		@"viexyLxtfyZnakMjwqqoKUeBtkSrJectQHZFSGxeEjrzKmVCSDrVGJTOHjrCCbmNBfetoyUUlPRZstCZzklDSrPEEHwwiVbMtkwZidKEBaMCOYqamugSiZ",
		@"tXWYkBeHuZcXIsDbQlPFmFKqhTMQVnQjyoELCdzpEUiZnWlflVjBpSTJvhFlwVzybURafYYJviaThSpfhvNMogfLYCsSgUSsxIyJjK",
		@"wzUNXtwEbUIubRSnyCvBYUjFwwsjsHtYMJIYveAqsOaKagxbqpFDuQLyaebcHpzyWEAdcexwMzZtJfbdjDUpbubdVguXDGcsbkqCXyVRhe",
		@"cJNRRMrJApvZdoFQKRyfzCIyqmAbfsbEUCCTltHIcoZPttsfIvFHqSOcVbFzDGtvUTLsZwtkxLWidtJcxMnylBukqHNTwhWkZUwnoPPbYkiYaFzEFDOuPtCxuIDzgfOWVzLeaCFDLbX",
		@"dcGYCgvhOToUwbaEEYpjbtbhKrOqKMmDPgZqjTKfoPOMvFvjTcpqDkVZDKSFKlyZsZPksMUXKeJPXVVGyawKEOOaBovANIHlJecALxlTeEEKMMIwDKUZQ",
		@"ArEGZLvCnePXyaZCVXqZjLttWtQiVjySOIveQDjUpsNxuiZeOuJgZWquyKvrpDPsYrKCWMieaeEWLmPVeEGMwCuMsmFpTvHZVJyvjAMUtIukRKLzMAqpTPYL",
		@"FKcSjLQFWydeAWPwlCeTzBIQEdWqNSNikragrhWdtlfxBvBjaIGurKLCadDAicUcxDnHJljIDAaxKByExBuVnaArqXfKoOAwFlsbLpOdktdKmCMTjlbV",
		@"kjLoLNkucZKKKIYDeiKskrfnMzUbExBKbvOsaWjawovOPOUmOJfMeMDQrtphswlaPevPsKzkuqcyiKOmMPbAaYTBnFRADAjSGswzbWLpz",
	];
	return UaiGxlJmunWrNKp;
}

+ (nonnull NSString *)MvTlZYAXPtiPVrXyEDfwWYgo :(nonnull NSString *)ywTWJaAaQOxI :(nonnull NSData *)UaDsuAvnidzAFTCQOJIXITJq {
	NSString *weRfdyMJdxi = @"wzwvSECPIJkJpuabfvuMuBvoUyxBVqYUGiXZxpVCfcdWVvhbUBfGcvQavKPeoLbPOKVfVmjfCWJDbOjByTqfguugBFKCXwfPoCFwLevyUDbLmMEooVIYBLxo";
	return weRfdyMJdxi;
}

- (nonnull NSDictionary *)hzQaehvRVMgLXUm :(nonnull UIImage *)sxPkqAJcHvqBL :(nonnull NSDictionary *)eNyXiBWncDPlxBAlrXNQBtA :(nonnull NSData *)zgntTOzrxs :(nonnull NSString *)QnZlXSNntexfjLNTJ :(nonnull NSDictionary *)yjUlMbkbGGCiHEOBsL {
	NSDictionary *YVBWZPmFmTuoNinKsH = @{
		@"HHLaJfvNKQSwjYRXdrBGt": @"BsqxTScqDdAcpdYwiDwHjOoyfdSbZWMsinEYqLFQwzxjAzPfKpJIeNxOpkRpGixCnEskmVphCutdMgnzKijnaylTFfOlZqIKTjuWGAVXFGyKMOrtlaBpa",
		@"AkyghHlvwuY": @"OnVgGcCWiuIIXTrZWwrglyuAkqtvqsGxkrZgBUfQidxDMTqyNpYUKzFvCDgZLWcbwbiDEwARKnJUYfBugIibPKYjiJhTHQYcRZtiRQDAmbSFRMrsqLxAcoUHkqPkZwOXDBGKy",
		@"ogtznzmhvg": @"RxOnDNxZiOMuGKhVDosZXHhjYlTLHlWMgaCdtTmWjEjnTeUgXGHlHYbEKqgTshSzmJAMkcxaVACprdYDSGrIKNidubVsnaTHaykLzKLlbKvGWaaaa",
		@"dHflMRHBjzzaNoNkeGTtZ": @"eYqyZawpzeaHiheIPEpTBEmsGUChNaiPHQuWBgYUyFeeyqLcnvCSkPckRVfKBfkPOYefvCIvnABcWEcHGyYZhQzSithallsntLfQEAXQCTqLNpjhUcKKXMhkSFDmFtuitfVqFoKJsCWQybOyeF",
		@"ivuJrBqdPsPHUaQ": @"VAbKWKWJOVttFYPyUOlxXgIYNqDobbxULTMYMIxYLSvoYzDZrVyOtYdyvapPmuYoGHgUmKnVVNRZaNHXdjeUcuudtZpXFTyodKZxTfUzQeqImeYUhdENNPBgvutKEhw",
		@"PcGJnDJdKqCRmQDUrmlgCSx": @"RrBcoYxxGVtYzkmzZAtCQozJPTNqSpTHfTHwgazgmHIekOSlMijIQabxtbpQficxiQQDnaMbHzPtsqRCxGZBqKVxUWHskTdCHiZTbgueUoqRaB",
		@"XzRYnmUqDPfswknPXRa": @"PMmBspsuAMOhRCUYzgPyKwCtrHSFmEmzasmLBqHpdytJzemLPKfmBOExcgRVwzxCoabXyOEYTyhaZRZYYkSHGnBQhgPERVxECHmRHzosnktFtbhhWVjruBNzCTLkAOvNAsLYgdbAh",
		@"djNcOTlXAnhfo": @"URHrYlmTmZpTICVZUhdTGJhBrIFNTvOpFXWWXMgQWqhWDTohVmQTkpsxfAbqMDygqisdhynnnUJoJvnuuWWHEcvktrOFhWLjBYFgWLyWdXldgkMAtLxmJhFQPsLIkYM",
		@"dDngEwKwAKeJzourbOlWv": @"qAGxWbAfJsZuklUJgsXzcUfIDsViUSHwVWSPwRLlCGfzGsmHzWaFFUzDLJzUixlcEtitcEueTsIInyQhtTCnsqSAfvOkUhEhtrARouInUdJmxTUaMgOlwJIgrlDKXjApgtNguLfeUzUrsofJxqRUL",
		@"VynsUlRJdSSrjCacT": @"ezxTQJiLwtIvFYGMkDWYwBKqOKUQRrcPUtYFCdpccvIXyaoOYMjouuVBRFRhrGKrMSpzugKrmUiLQgRuauZENqxgSpBuNttbfVhkhMt",
		@"tvXIBxWcSILixpESyDTIiXAw": @"FKiFCIAYPknHQvtxWIkoDwtdZsjthUxHzPFLkMuNcNJlcyjQmOmcalfFKDOdoASNszuJCUtxiNHZcXXckZdlHzkYXroHckbUoYObbthPQtszgsRfxBHffJsOeZUHsKHkoxicvcUqIuwCnuCapSQ",
		@"bzdePqwluHUYpYqgwz": @"bykDoZYpTfhVhfuCHbdBfuPbHcVKzwdxYgtJuolpxYaoXqIxYxzcgCGthVAFUcxYfLpxVflUGGruNIkRnUYfQlxPAMIWphhvHwkmCvKQKssfNxpmhZcecufjKVmJSiMkegCdCIUQrrsbv",
	};
	return YVBWZPmFmTuoNinKsH;
}

+ (nonnull NSArray *)FWUKJYYRBePotuPdb :(nonnull NSArray *)BHahkXmoSENJ :(nonnull NSString *)rUeZTaiIKh :(nonnull NSDictionary *)GhgKOxsviULuhfOdtlmQmMuD :(nonnull NSArray *)DXyODmkABPZBXpWZgSJDX :(nonnull NSData *)mHlxDDVcGtRlcrcka {
	NSArray *BjqsuqdAhsxgSZMXiyVAfdU = @[
		@"iTADXlDxvNkpAZZvsFQQrhjfvAGVnDabCQMnJtnNEWPcFnJPDmiTRSQswyYlWyqaQudVCbOIWJfVjYHEJVDhwBIdMqEJfUrDLicIwddGMoWOktqVRLXbWAsAbI",
		@"eQrjGQhxSPBuCbERPizacPoekAYIECXxEJonxpRosHFSqZdzrCvbdRgSLWSYQxMxcEDXubhziAHJMScqRaJYRLAmNzSpmFlWCGKBndNqUaYmAyrilcBFOOGYJOJADK",
		@"hNLRhPJAxfovGmsslntLikvZXnpJdujNiZMKFutcvlAdfrEvGBjoxezghXuQKlisRqjGXaiwuSCKlupSqofmDUQxbBugLHYbTvrJlDVvlJxT",
		@"zlrsDwKeGhvyrkMQDsCfgijSvOHZmJhZgdMAqtdWPKWLSUhZQVvDwZyePAYfSCYxYIMKkOontpAtvytnfpkdslGKKcFzBqgEvGGfdMVYtAqyZTcihoBmPCmeJVNemxp",
		@"MdcZzgKpTSYrtcSwGgtWPMXLwpiqHJJTzCKZkCxAGTaRpRmnhoNGTYJufFULuMWFmpoTZpZbqApfZqPtrVAkyJyvgNRbocIzcmskKWimGIqHtRpMumCqAKeYLGtlPPEbPpDILGyBx",
		@"dqTAPSQsyAKagANLChngFUjpqbMrPRYCWvMuKWhrTpfRPPCRVuAEksLBGzQtZXtudAyTRYoyiDWODRfJDStKltvnQaInOinhyswWHoIYQxTeKlWCpFAOzZTAbZsDlhyWIJckngcJR",
		@"vmkpWzfOiBytHkBuQpWOgOkEUXNJOdIbpSnhAqVEcOqUABjzaEHSFRitgwyEqYOVcSAaZYAglzitizCnWDfhrtfONGazVFnSifEQRtehDeImkosrWPvbOnrHCxOQbphZBHCnlFOtQ",
		@"guGbFQvFxQoVoeXuuwzHZeHgXDbVanslRtIDPIbzoYjjdqmAssZEqzsvuYOnuagXdkfbYYTfXdqUDuZpzYpBxgQutfCyfDBNcxPgSXwdgEMtHqfUxwMXUBVKZRNYEySRtTovygFKXbfWcYuJbSKVL",
		@"NgYqQjxmbGwtPUVCHnzEbZPITrKbKxyayhGmowYUFyHKtclXPItamddOAysDZmuOCCJkmnvobaeRiWrwcbuqqhpZGBnYUSelmIwHRvqvrBzUdReDZzdsWuqJcXGaIXJFq",
		@"ayhlORukSxYtTvQKRBcWAiiGYMeEtJnYqxBtcayZLNUMnBDenRpNoElUXaPcHZbTRCupVtYFqDNtEzuolQdvoKewhbdMcEGDSAYfbneageywnUvkCkPDrboMrDsOzVZuoRVzOxvTnRkRC",
		@"uxXAwKekSzWBGszJjvxbCUAmRElcVhLIaijxShiCsDxnPLRpVNUWwhXCVvRHIVxKzdGLHsWIPIHodeoIDIHgyCcvyJjMaIufXILfUUOVaaQHHdhlcqxywPBFBJYpRUizbCi",
		@"FkOjBKsogmtZgSNuAVPpgqmXYYswRUKWKkeOzvfWqUZwwrvmmudQtxNuGClzZSatAYmMOTAUnZDxRioGouIzEcbxhgZdWnYEcHIQFsrYWdwagrbglcEzbppZcTEMwULyAPwewHOIz",
		@"GKiaMPVnzsHWrvTTyBPdGDgQyLvFUwbpxinxrqyLIAblitoGyKiBNaTuvCjznVuqwyOnJeTNQfLQxizJpOvkzyPctEYYpBbaTWBzcYfcNpFStRlKAhVErPmUzYEffsGP",
		@"BrgNtikLgtMIoycXExZeQPlqBEDMWIglrTOSwRtNbDQRfZTYOrfZNoCUYLXuAKRQSPJJBQcXApuUrFDctplmerKOMFyfNOyQmCYboNlfltEqrgvgAaLtitUdTSKPbnVzAk",
		@"kvctItgpwrrIouPFdZiNaVWzzPEFxRSthIgIpdLDkQthQOvTSefFdOTcVUEjyDGqoIjvFCEOGowuiNluALsAbRJZTbbiCuIwKkrzaLNOZwCrolojWcfkXLaXV",
		@"rrZxOxbieGbAajWbJojptfThEdSRenMfplIEArnBxzySDCvILKNrBvEjFnplcHEKaGPikOfqJJOtlmSbOTmjoAvhCioJpdNxiEbHnZuszfrnhrYbihLEJHglBOpPNpGiaphTskqUUGBDzs",
		@"QhLdSmcCneglOMXHnqwCkYyjeMILTEhHeDkfyvHncpKESfnNACQPNpSqmRyIIVToMDXoNDsSkAxCoVtiENUGbqvVpbeQKQmqofULIIBxHDYNLiNm",
		@"IxKGYFoLYgjnQJnqHGYmSrBmfJycNYTnKujsxxhsAHeMnjGrNKwDKqGUgyLQuwVTNFNSUfDjtpRGiFiuirlnHsLVtRJJnjzcLXbTEoLsybPRsHcfAyzbpMGyYOqDomgyk",
	];
	return BjqsuqdAhsxgSZMXiyVAfdU;
}

+ (nonnull UIImage *)cymgRgttvM :(nonnull NSData *)OfqLSxLmfJdfcHJ :(nonnull UIImage *)AmxBQFOrokRVwFrtZtgF :(nonnull NSString *)FZjHVAWmsRZClhlCg :(nonnull NSArray *)kairKthhauMduXGZHlgmpLX {
	NSData *lPKqTGdGYM = [@"ROObQxkbqPBjWFxcjKowbdJQuAnjTpsWukCiPnhkmfVaGceLwGJQuEEwHEVHORJruMyHqtqyhFthJOUaKtWShaOzFPDxPGbdrpIKQdGyRE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XovDSWKtqvH = [UIImage imageWithData:lPKqTGdGYM];
	XovDSWKtqvH = [UIImage imageNamed:@"QvzScmGpyrERRUAyUSePzOCGrGLQYoMYVTFBPWeejaketIredviNrjCSgmgxnoXXibnGBYkZIBMQjMNYnkKosQhhruKapmcrxbzjxfnCemUMkDGPgRDuLZBHkHgvSKjWIcGwYsOVLV"];
	return XovDSWKtqvH;
}

- (nonnull NSString *)CEOwcVcPjTgOkirklTycNd :(nonnull NSData *)YxRNCPJHdjTpMu :(nonnull NSDictionary *)FhrlOYtdQzdBb {
	NSString *NRBZzHziME = @"YjClGWZEWVRbdDKvdWSRyNqmUaIPwrMdiegdiHiDHUgSFZJApNVKpPViHUoHVGbJudsdgrtDnHwGJoqFIQCuJtVASrRgXrfvRjhVpCCcQKwYDhOhbAIogbmTzfjEgMahhTB";
	return NRBZzHziME;
}

+ (nonnull NSData *)roLhjJETjCWUTbpvmAC :(nonnull UIImage *)cmKvoMrEvgkdSPQvAdiL :(nonnull NSString *)lqAdcyfPZZUahcdXu {
	NSData *aDzbVxTgTHkmeyXAegMEgDkr = [@"TtsMzSFmtINKRSoXeTSbdnzmtlYhZClOctKOhMZormoIIWwfSJCmFJbSEMzqWSYrdPokDBnbKruPRVgwvTcYhzUwrXtqITMowyldqRuNnlmtEfFyCPOjHpiPnnttbQYVtMSwEHHpeGWfrDzZ" dataUsingEncoding:NSUTF8StringEncoding];
	return aDzbVxTgTHkmeyXAegMEgDkr;
}

- (nonnull NSArray *)OEcjHdZvEKdSJkyKyGZCAc :(nonnull NSArray *)mYEKRiLDOkxh :(nonnull UIImage *)eNquhtHlkqOQspyxImtOT :(nonnull NSData *)yppLDzwyLBtib {
	NSArray *kJNoXPHPlrFJbEqhSHAgI = @[
		@"QHtAYBdmmIXNRdewMZtLcaajCONoIweupUYkgmyxGMupLKkLsiktUHwFwJvvRHjImLkhKbhkWjfXYXhyCxbHdPVCnajXPRpkiFQVjlayrzucsLNEgZVCgAyurVyVFUfcUzQVD",
		@"foiYJiJBIeSMklhZIVVkjihiRwUckfjbfNoUvEvjAjNEAeJNzhgGNsTahMLHsMdjyHKiZmwOgvqubLhGzGLhvfSQvCFQObufhqWXwAYpgkaKfGyUrCnDKSjIZySiSfoDrUKUFbviXCfPoPPvGS",
		@"WbSJbyPOytjoBehvSvbgKbAuNWPneDJITwyozSeXTfspJNadsmctZMyTIxOoKafCbIJfNITGodsPstLykCxzYaiyAatLYrYjhXtGxjktY",
		@"ngPADKkNLENWUDQtfPeMWcPqIkoAqoYtlLXjkNJlXcFBMZpDOJZIQVgvmiLIPYwPCcoCgiZLKfZsUDuTfYafPUjNXyglsSoVSGZPeJsPD",
		@"KFSKxzatCiYuVYnvgTbESrOgmZgDphmHdFrFweHTwMEnUWZqZUUsmZODBKzkIroTVbtxdUgyaPlYSrEmwgLyGwzSiOusgSjNIrpYuyaac",
		@"cCyoqOIXaYLHCOiZPuFsJdSjcSqqQSlYzWtWAqStbssgPljkVFQHprAqrneJOWLZlqTwNQZuewRfnlrhXXbtPQAGkRKngNwNrdHoABGeaDSattzjxzzrDJmiiexUxymAglkjcDItcF",
		@"iTaxhkfnWzJGJZKjIlmAWgjNKLtrfNNHqKsxWlPBfIZNDYRKBaNfQmHgtuZTHUgdVYtBhufaERjuGiUJgWmuZDvdOBHJLQVNPoDAPngYzZkl",
		@"uQGUaYnYYNxHqPTJqMClUnBKxNaVDfuUiQorKTspUlzhSDefpXRUMFohraoCjMtHSsbkgrZwqLZJpaxeZqOvuGTfYIqoMaeQyPxCmqgbLNJQhjXk",
		@"dOLnoXKCyqdBIlcMoboLwpicuFDMfHcupXjwTMDGkEgeKwEcsMledsAygHAxlNqenemfTmrAGUNATqgqUZbkPDnSludSeqxJHBmeXiqnotSlugSPkOxVfjsRUVPEqRgvRjRTrWofLo",
		@"vJgwWaBBYscFeHYXOrSBchYryxgGZaTcEGMmhJAXTiWgevAyhubONOvkCQQzMdJouaQznZxVRHAXYKJRplqjgDUtirPxLCnAxGcJdHiikOWNusJsHerbaIsCEEIdbPhdYiRkkZsIoBUPKhzk",
		@"XloBHGZqfETCwBIKyCnRkClvxkzFxlczDlELzmziitAnXkzIPxXXtZxIILVoOldyjgkaKPamWlVYNMtenrfxBLeHdmnittlwnXXtrHQwhCryEvwarmyRWuvcWZkmrdTa",
		@"gXXUUgiVkSGVCVVKXrUeObjpfQmWvfXNWphxhGBwsQjguuRoGVkDqQbVJjsViKQsJZQRMeGMjXmSnurPDwfaAJVvNhEikvdaYgmxmBTpNBVgQGSrkNwWCrAEkbTlsWRlgYirFiTGBpcdaHJDx",
		@"RFPhApZjXPHZlTXYywJRytcpegeOlHqQWecFacmlGhTSUVykvUQNZxXHnhesfzSgmWpjemcCRjdveXlMVbRxVumXGfISXxImxMMZDgKNxSyUEUvbLdnAykURS",
		@"rGYhskhprBTAcLVHGnTOIxCLMvgBPdosQXTEllicmOxDrpdBMhFkzrGNlGogCnnDlpysKscaiCMwuzRquAMjjpledhfDshUrwhRix",
		@"hNvhFeBoesfIzxWRvtHZhpAOYzqVBPJqoIVnHIlJAxAYjJZTpvWEduRFShfnJQMhheauboDfmxcHtOJrkLPNYioRXVRJTIOPbzZHbcTjrqAqH",
		@"rOMuiyPdsCdUukZzxSTvrQNADqCAQMxtnMfuPabhDJfkygBLdChtjZwPzerfHyqPNnwRYaKiWzuoZPkcwnIgdSMapLDbXJDkAEWKIzBSaQvwwBKZFTAUZrdIrxdyptzTfR",
	];
	return kJNoXPHPlrFJbEqhSHAgI;
}

- (nonnull NSData *)RbGonjiDYhofYNKFDghi :(nonnull NSString *)awIhWaeUhjdZdhFi :(nonnull NSString *)avTgEAFsFfDfxqXDyXrRjKQx :(nonnull UIImage *)OXntUfTUCdKkEIkpvi :(nonnull NSData *)nRvgAwvOHD :(nonnull NSData *)ZQZlwhHVtkfFy {
	NSData *XfEycOFaHMWQOTwCgbKGpy = [@"uwSjzoRHxKqcVxElIYctwtxOFvguogoxIEagMquieHUtlzjjLhuEBQTBQGZBBBzEmaYjAoGfLNLrcJDdvKHDjPYyVdWRfPOmNVMijuDzMDsIQXAMW" dataUsingEncoding:NSUTF8StringEncoding];
	return XfEycOFaHMWQOTwCgbKGpy;
}

- (nonnull NSData *)hkxRnowdZEOWYskmNzpwJzr :(nonnull NSString *)FiMtQrQXHVvg {
	NSData *dBtYLRrCmmQQQAr = [@"IhzkPhDHTwRaWRcmrAGXMpCPsKBwrhpXFwWqNwpqqKdTMSQKgxODSBbgQvXcqGeaGQtXigcWXddHKENWSPaPpUJtgnzkbOZrspdSSBiqMYg" dataUsingEncoding:NSUTF8StringEncoding];
	return dBtYLRrCmmQQQAr;
}

+ (nonnull NSArray *)GABhWxELmNsSwzCXMnCNv :(nonnull NSArray *)jAVvXUekLL {
	NSArray *peymedggVmVGehxajUv = @[
		@"JVTQCZwyWnfSUxZGqwEOJAeTemBDBUUiBVQUWEpAcKAJBcmYugEFuNdVdXkktQOBvTZtXHnrDFfWXlxUVLCpQGmJCbrgwycuFeNDbtTmTNHaQJiWOPjgHRQnNMKcLYdFhanscnzqLnDFpFwAcmS",
		@"mAWJcUhJWRdlgxDckNLzubbIUMWiERuIeAESZztFSiRCsXnFsLLdDHxusCOoYUNqzjysaJIFMSwVnmRunShQBMIyubcNmyckyhlMKpWtFpjGGyunsRZSQYCtBNNm",
		@"yRGSLIiPXjcQcdqopMxrhonONAhRBmGqmxGnTDMeYmBPprhqLEPxjLbPfPvDaVuScRTQSNEuxpSdKHMLKgDZlXOjidgNdbhCZQBmOVAfiYFVYsPwHoQPGBWGOwyjiJzXorHypnVURBiJeMxX",
		@"CAiNHNkjpZsorasObSEqNQGSTiZVarhVmCKbQiIzEjaWmMcjpmBmPIHbBiRVrXNCykhAUsIQyLylcWLqCdTGbAsuGmUaGRIupgRKyKLofyZvFjCpfNXh",
		@"UTxCXquIaCYfbIZpsTGolvwuRlHdhZHDFeQomfiMqEVsXrNJbHQvMNylxAuOHPWZeUwfYHnZxQzsmOMeggoHIOcedSKLxHotkWIrxDgEWKWtTgHUfFNYnluhMTYUJDeYIPqLF",
		@"thGIOayudpKTVGGoaFmcjCsWuLfCcBMTAPmkTwFXiZtGaEUwdNQcmPOQKMKTnGTsrVbmjJGMIUkUeapFTxZougoMKoLriLFJBJpRVsiLlfEbAAuZtcwCrilSpfkDguKbyqvzkXBfCcxfpCqObO",
		@"jcrUMAEKatizIvjIeJnjeyFrbnXNNrNctplghRrmBZpxxnpKoKnGIxdBwDBuMqXKOtynEpShbaghjMCrCsngboMcBwmdKbVeoaKxFJsDNfclAAChZJjNiYgXqnZcqOzTuaxcCSonbvQdRHbzr",
		@"bgOOsTYnGhKKbZdyDrQlHQrjvJEnCRTjrYxrDMoXEEHugKrznWQbahTugkPOQRzNMpSCBQFmbQZPTwYWTnbYyVPxomqhjxunFYAGvlfLiqAEGQhoezoD",
		@"APZvgxzwsVBDJBZJAGfGuGTAlSjFjsBZCtyalmIEjeQapvkNbLmTpToQdeMESQuRjLeYFeDBCfsVrBVzZlgHlgMitvVWCFSUktPdgqwecBIVtCfZgltVuKYbSLMIhJ",
		@"iYhTWiGeZBmRDDYxUrVdHSGfmnSpCrrzOBLYcanyOAVBOLycXfDUuZZhqmiEyJrWdZJRSkbmQMjfpStXRnAJDysXslQGMyWiqZvMLCowepzqVFBJRADstXctF",
		@"XgWfQdgCwnIywNIPikKLKGUsBHHLkuJwbjdqvWEmPwJEFmNmQbOzKAYXPeNSShHQBAMpTXOEdEASYHnmwznImYfTiqVboJatIcdzDcDLXfkNqLQSZAZbIJQMXFtfhfbhqYUGfsGUlswgwYYdtxZ",
		@"MDQtRFBtUNSJsTrxCZTOtROCiEqlhKalfOieVbqeghMXHatypcAKgyBiNHdJyjnXDhwAiBUVhqzMFYvAxykePguUtRQtoTAHdCeAYhheYNjVMqTIkJvbzZ",
		@"DAYXHbfTKZWqQFwSXEAZyZAXQVcanqasZFzLbeiYNaPcImaFDaVhUiSkvOVhoUFbhlmrvhevGiSmGhUyqmFiMCZYsUSUhkfaHzqRjREayqgfoFQFnNdRQiMJJASi",
		@"wZlILtoPKTzyAXtXfnKGUOlEdSujpFYCjyhkdaiaUYxPWePJjJchexcunqNesrwTTpYCEcZypsNmoomywSanSkOdnEeFVFsgEkFqR",
		@"TxUZBxjkjAYuawsBBAcnaRhNbMbuhSRWIaiMOYwYHRCmsisgNEalqzCLzkifZfgtyoPxIHCogSeAwwHjQHgpKcdeAHYxTsOKNmAjavVQARMgQvFozYPQyCfzeUcKEJUcBw",
		@"imTMmymphdGUQKEnwneWaTlexykZMxJzMvhSSXdtNMkXFjmLwadisHWdpNjAVnRluOvJZmDLISBTmDYZcSviFeFVEdvnmgzKaGNrWXKEGrmm",
		@"fGRckjESUYfyfiMgowRzFaDGwOpHZzOyagomhoItYvfSaVvNnBktWEuobHfiDsjcwpOUpVbSRAwktbtwcStCpseArbmpdcAYqiGHUTdRNMsVaBOKsZGRYjK",
		@"wzzUmoywiJWdTlhnoEbwPpNrcwkLhbrBnejSuVXQrRDMLODczojgaMPtkmoUjdHGZZsuaksfjYDrMezlCvOtvnTssRvUlsmzXxdVPYnFbamNVNZggpXVNgLmU",
		@"mPkzZdtTLlqsQHSNKvEPdVwZeNXUUFRdBALmhyovnyqTBxjRhYZuWOruMFznMtgvtdMTrFRielVplDPDOIoANsawVrrgLfruwnTCxjw",
	];
	return peymedggVmVGehxajUv;
}

- (nonnull NSString *)izlhVjHdGHKry :(nonnull UIImage *)JSujGtLbbTu :(nonnull NSData *)ULUdOREFCySSccQOBfdDE {
	NSString *XzWoeIlSIDui = @"MCbufAzzueFeiEIymYXbZynKLGyknjRlyRevhMRqEMwKRRIXuPLKWJFlmuAuxIXOegGNepRiAqpnpRQYLJNVTSnQyvMOurgfscynOjgfNzeIQUkvYpYZ";
	return XzWoeIlSIDui;
}

+ (nonnull NSData *)xjLASYsmTXZvUfuHDxC :(nonnull NSArray *)hbbbpoPJKOmtcWT :(nonnull NSString *)pzfNJbCDDcytPMBt :(nonnull NSString *)eITWzBGCxOwTsoJ :(nonnull NSData *)XBXtzvyDTmyyvra {
	NSData *tKDljsdKoMutkZ = [@"gxipJYRVcrxauVEKwemWcoCQbuFfgoaUppxdmofrkZPYFAqgFSCDlUSSrOcVcMyxEqtsTbsiHivmqQFxITIqOSzPYqDUNPLWLgzOufQWfjGbVuqaxgPhWCOSUbMkPgwA" dataUsingEncoding:NSUTF8StringEncoding];
	return tKDljsdKoMutkZ;
}

- (nonnull NSData *)HcTMuPEPOGvezeueidLTgo :(nonnull NSArray *)yPpMQqSxWPaWocuSxLkZd :(nonnull UIImage *)jrQqpjQTIZK :(nonnull UIImage *)EJrkrauXNFGZbndELcSA :(nonnull NSArray *)HhrkbaGAEVbICR :(nonnull NSDictionary *)oOkWBrjTgpPwPl {
	NSData *ggCpZUAWzgHTVsLnYyiOSpvL = [@"hfbPZWANZtPwjiLJRDNJYIkJUuqTwgqmKHCULZVYBUYaWyyunOopiyKIVmFwuSyaTiKGuyTJmKdoNAwYyTwvVjiSzMkyLmYxlDLdaafcqDEzDEcXNXvRUHqPoCxBjteBlDuui" dataUsingEncoding:NSUTF8StringEncoding];
	return ggCpZUAWzgHTVsLnYyiOSpvL;
}

- (nonnull NSArray *)UIUWMsNvnaooICiamPPuLzzI :(nonnull NSArray *)YamKKhqOoUgYCwXdRkK {
	NSArray *SRcbiYLBdTn = @[
		@"AhLAgDKsYhPQXkkgwqBKSlBNGRUmKEjTZKhELdFLrGTnsoihTltKqnZfEvsOIAblyTzFziDvIrtvDkqxipQUSeTOAfLacAtlPqnWgVdKhMRWeDEhI",
		@"QuOldfEvMvpdwLwcxqVzDjMgDHhpIhLfBIBhMKPIfJkaWvnCIAFqrwRXvwesuryFAqNkqoMzWyQdBHeOKfBuBhcmIdyPotmmbpscTaiBlEATDOw",
		@"gNLiKVThCBYSbDAOSIwejxiGFYnOLvszTTjilcUYfTDGlPxfWzqHugwAHCgcbQnnYcFpRWGwXTkYOmiDFpWvSEWrESDBOPkTOPUJPKt",
		@"LRAVZWEVwZIVCYSYHLNoibubDtGsdvqyfHjnFWRqDFDVItISOxrlfFUbDhJYUqyxhjdziXRjPhZytjoAcgtjBhyDQRjPOxtQdCIHXQDOSHGwLrKIcOHSYrC",
		@"ZWAWDzrNtkQkiGxiPiUWQlKXiCZMHcdXTPoDTwwZccHIdvWOODlLEZNQrHohyWUtNwKiuhMbLgmuUERbUzeszvJMwNhiMHMyvPtOjNsfnHkKnzbkcWqwqEUOco",
		@"BoNgPeOnXjeorpgyIVLxRJrmSQRuUIwlIfiwJjUljuJfVBgnFtggqRAIovOFPswOrqUbLkFrnwXCQIDEIhSUFEruiOtDNEymYBNpE",
		@"JgdJRunATeRvdJjHafVdYoQyUrnwkTBlIalzrFVwdepevFLXPYUJVzIFGndnTPXcnZsNUJJKgHGcXNxQhsuIEvINwdrrtBhflBzEiCwqZgTcBpygWJoFTIRjiXZxGJcjQQjRDJVVbXOgCz",
		@"hKxwiETHnyLGDYQooBoEmcKTRzCZujaxLqbtPLTtbhLhthjZUiVeRKIQWAdeYltgYdmGXhMHAAMLOqivtCEgXZYUkkcxDvqgXxGPFKpodMJxRtFRQxjLTKNpnZLsDHmHAyZVAWANYBho",
		@"QKZvtoUtVSXZGPPAnEJeOtzlsvrmyeLigRCFKgrXSTpPpOjHNdTjQJKwDZRIHMGunFzCtQfOPLZyHfKVdNYZJAQwJwmJDJMghbUtSrhwKBxKQpODYRtXYoSxNaETtFgJsEBNIGkG",
		@"wSMDWiqoISNEEeUstPycVHvmMzssUIRvYzdWCzqPXDwPEWlVDXCAItWzDGikvnCULWyiAmyVgFEnbajjuTVxFdchKuotkFKlMipaaxPrvdWbjldugTBSOrc",
		@"aYvBQogroLFquERlbuYfbHJGZzDPpnNwOHkPXeqKzAEHJMeHYmFHhsYmrZzsPZQYQoYQwLFEMepbeWZfLuqpULdiSsaALaTpjKYsFdbPLuRekswpstTHascMhlVtI",
		@"iXFYfeFVHZhscqcJHXvOsqrYLZrmkEOkitEvTocXhVkXWUfQLChgaxjpuvzpRPPUnSLUjSdtOMFzwswlsyALeCsVzpoACMwSbghsXTVQxkpjqCGCkcpdohYiTUAJ",
		@"fzbOimMPhQLCUADHJHJINvtqpKxyqLNsjCNbQmOOzXdujTrZxzoxpGrGCBYVOFctykDsDknSXojTPnpRXOVPzaqOfHbxNmWlzBnKIPmYBQlUHzmpFbbblrI",
		@"ZuuKXXADmUEMmXugqRuwGqeSjRuNaKEgvFBXSIkkazzNDZZItCaqmcMWBrfPqnEcOMyVjaOsqrBLDrtQvkHATWehOdosdSZESxtAIcRPnwdRAZHTsbufvVxjUfZZu",
		@"XceqnkCxDooYwfcUJdfmaOKKZbjrtPnHueYKZqihyXbykoBAoWDKFhFXbORmKiIFPsPzZYqUanIagNsopmHoRMmjXsoARRqxWyIgQYxBSgTfemykpYBZBxzulfdUIevyer",
		@"TmBsDRSlnUXrIktPpSHPvavKmbAlPUpLGqFeHQAfgqTHqBCLhFgBCoLQwEOkjdbPjDHORdetDzTyoKITCaniWwEGcLYbvNKBynKiubPYDWbSonEIGYQTrmuzOTXiKhJqCjnxOgcJnqzNw",
	];
	return SRcbiYLBdTn;
}

+ (nonnull NSDictionary *)RbOrqewrbUNHa :(nonnull NSString *)BJrjhYfkngonLYDE {
	NSDictionary *oDYqhPotRwlUCcslPNJtbkKB = @{
		@"hMunYZVYPstkwTkQytgpTwN": @"TEKygFfHwwxCtvAnnYKCFPKKJlrdVaikytQdniQWnZSzmBghLPoUqKOUSacRkbGEtPLVACtYERbQHkUTGRXbkCZnPBBcXPuGjgpASwZCPfUtkySDXiGTsFSFSNRGEPMYbjHldhAINmjecnmeRnh",
		@"oGeRlTZKYEj": @"QLKdQMPtjKdAKYGQJlLlJrgDiJqyGBGNCqMVlkgsNnguEPJQNpDAsBIcmbinSoAwmhIpnKyrSqkFRbcJImefsKWTscNfQygmBooeIjBKzPF",
		@"mprHgAxXyNUeGNH": @"iTYvjhusgPYdOmDQOKKdxsBqpkcvhpEZuegVZaZrgSkpfZYPhDERlKjpXeAxSCROwxRxYoHVlIjpZvpXqaOuKblWYRGewGMgsbrMaXMzmsspjKo",
		@"glBhaaetfdILayuDClAHoER": @"DoCrZCvEEaISyldAFJqFcsLDdYHhyGkMQVvtyotioBSsReYJnBZlnzEVrDRvmoaoPUylgawQnsNcVDoWchkkVADrBRQURkqhjacNqEBmILVieXVWqmSjNWWnBSefaybTNxURtdwiFJqHX",
		@"MAwWXpxVucsAQpxkQUu": @"IPlXVQXrxsvLrApfCWTqipPPWdFuTynRvCEJhihOBNKlsTYJPPcKeZkYFogyCMJnKDdvDGlTShBpjslricVZEDHRNhhfypTZNPitUJLiSXbJtPYcXTzpvyvdpLwY",
		@"EXWYrlrEJE": @"gVKUgiKfnBwShRRiZXdJjLnfUSZEccvGoJMSFyuTwkhnstfaRMQnKDvNgEHlAaedaxXIeWTGtTWXKQdCuZPSzDXerqPjDYbrNiUOELFBcwvKAeXkPVMVOVceuIeljqs",
		@"PvEvNJYjgJ": @"cVyWtRpnROOEJJvXwWuMiDpgJlBLlBhFBsCvuyKjPeAUGaOUqZQIwePqOfwvyMsTLzBpYdtbLhzNZIFVhFvuNYPSYTQuXIodgfvwbJWXUppBEfkwovbpycthgyfXhOUjPKrzUPxSVxwwsaX",
		@"dtNUnhSFgJlGel": @"jyehOQTqLZSNhYtHpBlxiPcVjUdJITbWPmJdMQAzskLHvErDSJfJjvpaQyGgJRnSBMMFZNLiksOfRftZTCxBingNIHnhcUVPwHeQohVuSiwNVMIMUmIqJYK",
		@"BfWyltIHGVVyxbLW": @"DImzZNrPtjxbZGXRYVAelTpOSSuYHgjehznfDFBAtoRWFbFnDLBFsTEifJRrFseFQjZTRVBTNdEfpGSYIOmHtJwpnkEqfmbSdMEkwToBUzezv",
		@"eheZLnVGMc": @"AIyjcLXPJCwufKAYHhQWrTBmHRkMOcGAccDqdXBWvrNuiMtoYxQdaGAQXYGrzRZChUyJKfAPnNXCOdggwTsSWibcOjHIyRAYTMjNJCAHxFMxNJtCVXFualhmsbypXeHhXtXqimIBlOwDjKNVEOclI",
		@"jQSklAneFjOEEOzY": @"NruYfbuDUcEbAlbACnqTDyrzbRBTsncdHBhRcuXJDeGXkBbEdNUeYlUOHgkOwOnPOveSoPIAUzSYJZhZrDsnLclmMqExVRyjNbWgZbeSlNltbSfgPFzZBRojxJ",
		@"XqlGjTthldwn": @"YUJPDHXUdPjMBCBdWvIGRxATtBPzjSyvkiEhvcQPIuYcDkBPchdbuHlsGUoEyNqZtHvFcxkLjhcQrloofcXuEfsKFjlqwAIpUrzGpKWeyQFYOqglajOywvkiLHsZe",
		@"eCnePhDlIKVqUuegswii": @"FsFzTSuUBUKAUyjJmpwcbkmrnCVAhNtNEjvAmOsGsUqhLbhnsXYDrYjpmAfUDiFscNVzmElUUyezPYhCmjEFrdSlvjYeRtWxXDwBW",
		@"quFhVeEBSKxoh": @"SFtszCEIPlbZtBFiJlBOUOAXlVLlEHaisWukvOTvmAanWRJZOglJDfdubReWfKimzlNmmevYKpFCFNKsbuxScIqYAhQUkwBzfNGVSPIUtRGNsJszoaYT",
		@"kLpbvixOqX": @"YRdGfQlRmTRtkHwtDEwXqNEGrGLzfqyphePMxNXDduvySuFTAtvdhnrxiZcIGuQKFopWhWkCqsdsiWreHkPKKZTCGAPIDQcfVanPAeXtUjdAqTNSUqDbxvkpShGmTknDsGXWwPIAPff",
		@"BLUsnzHcgBFpPDgEL": @"HxpyfzjlIPRhwyPzkLsoJIGHVRkPGPQhqXotGzpykxcvfloVmTTiRojfQtEEWzThncGSxJokbLgmIcxkDjqBbQiOFgzdBRIACVfmIeZoNGd",
		@"EItFLiHsTW": @"HRnqCyLTDqYvUTwiZegZWjwZTCUeJumeZQZPrfmKLQOYKIeUTaiVpKTJRZjkyYKyeTmdEUREDgIyvJnyIJyvKiIhEkwKNbumrJxeU",
		@"QPNcqobIOEhwhMLi": @"XshTZmjMtRPeOdHivTRUyQrbBvACRhkHtjGEiiAAWkEgAMSLpTBljWKQRXKRKKMsaFmBKVMqXKycDBROPrEwmlCFoQGEiJWdrkIi",
	};
	return oDYqhPotRwlUCcslPNJtbkKB;
}

+ (nonnull NSData *)TwsROQFcCpVnEcOxE :(nonnull NSArray *)AJRqWlGnzvAD :(nonnull NSDictionary *)DkGbjWPmPQMSPzIupymozVz {
	NSData *UaroVGfwuODaCaRzRlyTN = [@"gQyEJfoIOzcYwkOAxvLDYGdRyXunOAypMnFxmtYTJxhqAJIlDuuMVicuBpcoqGzWkaNFSQgeoHXPFWGxmhTlkZpAZUiOlYnrCPRZPGasfwMUjahjVXuztdkGBJGmEVGk" dataUsingEncoding:NSUTF8StringEncoding];
	return UaroVGfwuODaCaRzRlyTN;
}

+ (nonnull UIImage *)LGhUnSPjxBKDfYDTvAHJ :(nonnull NSString *)UTqbFsGifU :(nonnull NSString *)OnZTuGMQzwTlNUNX {
	NSData *sbBQIKwvfKJesunBl = [@"CVoWMPZpyKDqFhnRbPutFPPGHoPlnOtlzslNFdZmROCulQeJozuhyGNlDNLqgOJBUDTKQMjEAqXudolJONhQlxusBmoGnajmfdsCGtVDAEuDSgsJYVkqlBSpndtlmeeBKlybCIitjhTnSkB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *AxjodtGvHvIEPb = [UIImage imageWithData:sbBQIKwvfKJesunBl];
	AxjodtGvHvIEPb = [UIImage imageNamed:@"uMbIsDtWlbMMwdETqPnfXWeKqcnnuNfmZERyMzqTQZQLBSeVNtgZAfqunepSlYhMWesZvlmreeFImfYitMXPSbUqwiclpaxOMIGlfAlzJlITbBVnnwGgZYhhecVIo"];
	return AxjodtGvHvIEPb;
}

- (nonnull NSArray *)XqJKLmnCalxk :(nonnull NSString *)yiHUcJmBUvYnDfDrC :(nonnull NSDictionary *)qibRwSRHUT :(nonnull NSDictionary *)AvedorGecib :(nonnull UIImage *)FqYJhLehifjNMbfPZfH :(nonnull NSDictionary *)MKOMcEbqeK {
	NSArray *KmenbTpOGQA = @[
		@"QwqDjeTQBbKPWKJTolQUNzRDgdOqBGfLNfaCBPtrMkSQQrEBdDxoznxCaaDqmxHBxWcpiXXifKnayuyPRyxSpqcwQVezBcJOMjDEafvwQonRyMnEinryLErbDBUfXzJuS",
		@"buDIPhnvvtciDWmFdtxMDOmSGJvuwgwcGoKMdCektKdPpbhYGgUtktiPdjAUsIXXoiwXMFtTofOFktbCVcYrxZaZiblGAVojYFWBFFYiuPyybBummLVDvZqzpxErnDDr",
		@"gzhqHjHiyAGlrgVEJAGkNvlbwttdLSRKZZRqzYjoJbQtAHSsmUJeOLSqPKHAXaJNSyyVutcmZrGXpYssKSMzWJVyvZBTwMsdhCwQQNrqsRCczEd",
		@"CRnMGyeObsnRACjlrIUVEQLEPmVrSpInZafUgyLeyrEWqoVsmxrAxIVnvUTyPAWmRCHRFolkjLvjHgMSEmUyugbWRGloXsbjDtTdoEXPAaz",
		@"RgNfycAJWOhoIKykRUKWSJsZCfuRiWSKCFaZNQJJbTeMYrWKQQXQWZTIlALLljBwvWUoeHrZihhiMVqwuZVSKEZQHpAhTJXkmZOEDSQnvsCABzLFZCeGAEbyRxeGxLgVcYyxXDLOK",
		@"dohPCPUaXcRXxKNHwwlzXpDChLwtyqtcxrLgiYTrKzDReVjMGiBqGCrfyMJjvMUBWMAwKOrVBECXyYLkTTpTmpHYjOcfoPwefQBdObRVrkZFFSGBwikHBbzIOPHNwfrQPRAY",
		@"iklPKbCDDFTSKyZufoThidHKNEmuWSyWBpHOhmjFOoKMoESGiiWVKsesGznuodssBYZnpbtZZTeEFgDjTJKniyLNXnzaTwbOOAwmuPpIDHZDmGvAAZpikSADzhMPDqLa",
		@"DAlqTvyiPrMouKzuQjWTsRyYRJFFywbPUpxbcdVClkWOQoOywVNyIjyzOrKHZFrBdiUvofeCOgFxHfnmCIzcvpspMtXdBmlOiIKYEahNQIMXLIKOwLIgLWXHygIGrfAgj",
		@"eSnbVzCIfntOrqwSBzfgBerQAlvkcRiFLNajNXRnoKFpSmsAlkwYQXntbOcCUpeTtvJcECcDtXhvxYlSxFhGvMCUyDgfitDKGcpNuJFquondEzi",
		@"QVMeCNETEjZOeKqkdSKhUeAMibWegIABgyOGaAXqsTpdbEadtseApulYxYCexUvHvcVrzPvvcBHcvVYZjyCUKTItFmFiWEjHgECNoVbgGTzloqiWMNyDs",
	];
	return KmenbTpOGQA;
}

- (nonnull NSString *)wOhOeXnxUnpO :(nonnull NSData *)ymiIaTeiLSRQlkUtpRPpZbP {
	NSString *wHPSXWYFMwJAqrqMgPMqU = @"QQTdvOpVSazbOklQrCcFFHReORMyshQMbNKKSuzAtJVdeKQxKqhrQqnJDDpOMLkBQCqkPOPyCQJmCYdncuufswGpNgAEwLgMpPKxJVmdP";
	return wHPSXWYFMwJAqrqMgPMqU;
}

+ (nonnull NSDictionary *)VYumUslAYbzxHcKgV :(nonnull NSArray *)xpbybpjAsnQxWrdDkmxh :(nonnull UIImage *)FlLHRNBBQVDhVpYNXvrf :(nonnull NSString *)jHyDqHRMclGcrprX :(nonnull NSData *)cfqTRbywDcW {
	NSDictionary *arJSTPNOhCLptvY = @{
		@"ISkJXbOzejFUwoeLhmpD": @"CmTbpkYWdLxebYgVayXJetBaydtKlvdRhdtoZtGsbXCJdHkKsVxTmNEWEuKGjAyFdweoTORKSyhLQzbAeqUYZrCuHVPACobTbGAPG",
		@"qZayAeQFtgfuQaFWDZcA": @"qVKdkizYaZxvTkxiVDFxEsBfObAqbqQSdxTwRiQBgZnJRprSfVsIFHVUNDYQaNkGAyWdVXppcILstgnLulVDUTWpifpgCjDcIToRmEHqJBUHBdUHagcDkeugB",
		@"hWqjBSCboYPRSofgvowY": @"wutZdfjffOhvNzcIPZOGORSHUmhuQUovhHvGBRFlZDfMzMgKQlZDEJFbbLcwpwYxzBWmDLdeOJfzyruPNCKMocjZXuowwfKdGsIrNIzxNL",
		@"rZMbTpPmHMVEFzRJkvGRCwmk": @"gLfYOVUJUsnibGKQDWfIoyDMvpHwTfMHujgOQjuRuPtqcOwqtrcCzERAKZztUQPvPmGytrcglMNUeNdJNILrkWnFvALDruZiNnEWAZvgdZJXbHVSWBSzziUpgLEYtlhWSrndKhwmw",
		@"aZXxkflUCTozCVqYtXbduVHY": @"VbwQISwsLkVVJOSsGTmoSpDZJFOAVFQQqGFJqlaJTJhWneqCPkdnRhtJSXyaqlRRVolwUPeFgkjdSGCwymtnYXblDRRWUTuWQjIHPIZWQgHyFHi",
		@"GKZthtvTGJqXcRi": @"zITzuptJxxGYNXCoIlvfreAuzirRNtnXUkorTSTTTgyZOitiMAMaojLrilzGKCNMBNLFvwkraLadjGomzUrhLDoJlEkNSViMWJkLgffUOEw",
		@"nCXnXEgeXrPbQgKNdyfv": @"nQolMlvwuwagbdoITXbyvFXZgolrePHdHKPQzwsRhfiOIFNKVczYZknIyllQvwCSKjTvSRuARzLpBnSnaVgFXhVJrdcRpcqhWNkkLnvrLaZRzUtjkIjBlcEemxmDIJzlWaGmGypHZvrKtvKy",
		@"BotkrFWZanTYTENCEqD": @"OpvGswBOecPsVtrPKCiArlnoeKFNxSCHMciyiOfDoJZxTRjwxRJUEnUObNglLucNEagyumiozYdqvYBLRasAWflSJgHBoejkEqddytSk",
		@"WgPRQIdrFORkmpWgQsLMnzdt": @"bzvhFkpclJPynxJDHAAmNWfrUIbDbhRlgRHreFePjgLtLHuWBKeSrEooIWObkoNqEOfGaswNQpjQdfoEcjZZhySXvDwplrhzuanAhLbtdoU",
		@"MlcOeShGvOZyIu": @"UAoAHDkOwrsHYkCegmfCxHzweDCxgMRrnyvGceEQBYmVsKqIAQkblhvgiUyIUtemgWOkfcJssQMtjmMiCYfcQirWcPTbnWIegnxOSESGWHOooKPLhoIblKHbxSAZtHQRkJZFZstuv",
		@"IhyMZYMLqqaglOzzP": @"DnLrdxyNJKQvDDMcSKkBnqanybKClkkGgHASQKrXSzqicMTpuIcYDUXJrTinYRaJkJIWUZXFpWfaKfPOIZNCQaDHSutPGTUgddoXKtBRzKXpcFtBPphihPMHeLKlsFykEsebAoTKCrsEyGgclZpfe",
		@"iamtweXqmxTLQLVu": @"EICTkzZIxspBGpdjqPTDpfACwsXjLzmokFnfeBlwrPhpWoAAEDdOKMzdYeItHdbLWDHahktBCxHkKBhwIxdRmnkFdvtXRVwRYRnVacwjkuRtoYjcCEOBQQGJpndeXFjEYYiGS",
		@"reyyjfAFMOzybfNuI": @"YbeehCLmvEojBEMDxPLWrXjCiMebBnyVfgWeCCnctQDWeIRqOGjPMrBdsNdUuaiysMbfnYOZxmZanxrQrsYjzqMCUqsgpcjmGxWzdQIKlVwPSQsgqpUiU",
		@"uBRkRkYlXy": @"QkNKWblkcyXNWyWcZgFdEnqsFLSGcMgmqBJoFQbCMMzkNMWGSOYJEHgreeCftZNieDJCQCRTadXLciEXkkMunFxXwHJwTIifkLtYffZmjreIoGtn",
		@"iJTRNDjVgYmFecBnDKgpcCXw": @"GaLbdmiTKFCFpBUCTMOTWzWPtUDKMZgZBglKjfjwJXsUKQWgtASWsdtzlrkACDQxrLwnUHkQlsLfXplGtuUUBCbQEdLBQxxMOceNqsRiJZWhGirPvqCOEbCQUKLGr",
		@"ZHSipmkWwgGNmTPJQdkUYl": @"eDmZnveYdcjYEryKeBmarFPZCHvCRJaWvjUUEoBPCCnUgigTZdJtcmltnxxPZnVcbRyUtmkrkOjsyPTqjaNWMiPlSyFqlioJmyEvbSxqQXVxsKFeivJDJftnDnKQ",
		@"TWvZzPhoAuQItsjsjENcyuSO": @"woMFxsBJHvZufYeOTkzVnCoRqbgUUovIyWRQiXjftFGIKxvAHozocUbqzNrKEPBLRECpyhDYvAUCXrmVBGYmZqwAvyxAtCdZyXrCCIrKiGwQzeszXFzFoRfynCxjXMXuVjFmgulLVzU",
		@"dGECTbAJcyLqZqnwa": @"ZxCqOQrAvaPzEicPNqleWnOcjUDiLlgfRnpSeQLWRrQMkgTmRRexagdZgHYTCxZOSUmivvqAGTQTzQMDXbvvotTozNusFXyHUBNbzHfyKnRKedBzgPWmMdPNyRI",
	};
	return arJSTPNOhCLptvY;
}

- (nonnull NSData *)vgHNhBFfxcWcpaCZ :(nonnull NSArray *)RDzMsUaFiKSXkm :(nonnull NSDictionary *)bggCXhoBjjiZTtGcTRTWd {
	NSData *duUtHSPwjBeRTqcmVnjwmEdu = [@"UyIEIzvqrrmraffHETNKAEPhoLJBtWCUofwlXMlBXJgaguQhyYqDMIukHuoLYZUWvbszPzwqcVPpiAmJoEiGyFxTjONxUwxZwHAtdnpqeaboJAkUrfpXKmCqOkYyxEtEEXcNLKgAESmwTiuTFcwj" dataUsingEncoding:NSUTF8StringEncoding];
	return duUtHSPwjBeRTqcmVnjwmEdu;
}

- (nonnull NSString *)qNdmlvmypMrR :(nonnull NSDictionary *)qEObDUctsD :(nonnull NSDictionary *)xfRlFZOfFp :(nonnull NSData *)BxKxmHSjQYaosCPcFdhZJGA :(nonnull UIImage *)aeMJUqgfHWnY :(nonnull NSString *)dzZZWiQtHwpuNOUoaJsU {
	NSString *SnVRpcUBmALUNbBNThaOovo = @"UJgvQzXIgGmbYaceWHWciRvzMKqUjPgcllMFTUJZqgNNrNNCIafOmtyzxrBAXqdavbkctuZxmDaSNZXZjzvfSlPlBguochGykYhx";
	return SnVRpcUBmALUNbBNThaOovo;
}

- (nonnull UIImage *)vWaJuywjxsvOwJL :(nonnull NSDictionary *)jRpdETgbJcYlSFvap :(nonnull NSString *)ujDQztUfGrMtcSFmFoTDuU :(nonnull UIImage *)CVTfxRGmVRlXfyt :(nonnull NSDictionary *)RxAcxEsysfvoP {
	NSData *IAirsKVcKsn = [@"zxotbvgBVMlteTOzZyZCYuyAxNTYjQiVuLGtTeGByorSFIuvRSAVAgEGbQWhAzrkNTMcgkNtvYYqpCkXgZmRhSipwgHrEnbkmDFe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wxFvAgsBdbF = [UIImage imageWithData:IAirsKVcKsn];
	wxFvAgsBdbF = [UIImage imageNamed:@"zpbBgpkWohkfoIqukvOJCcgDDFSsCIAyzFpLrZHuSHerEiwzUrvVboEXOZROpFJPwDLuFOIzPfHMxDOiPPoUBBadDjCYxNBEjqJBWZWybjhMSLlvOFwljBYa"];
	return wxFvAgsBdbF;
}

- (nonnull UIImage *)uTJPAtxskus :(nonnull NSData *)tuJAxaejtDRAQ :(nonnull NSData *)LamDRUbXwAltkMYhwmwTS :(nonnull UIImage *)LPMFupjTMGiMW :(nonnull NSString *)KnzfXTcLYNThtf {
	NSData *LNMNxeGnAFlvtCW = [@"ShVPZeNGevuQNSCRbFtoKgcPNIveFJWjfkUpGUaqJVzrQGLZUFtclQyOXnhOgqPeswsPsWqhbbZbliEerItYjNaqrIawkEaOUqwQSYEfTpMQwFgGghFNRYisKGtcjJFGpzCMOHnBlImiEsPUF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oAkNOFIbWzm = [UIImage imageWithData:LNMNxeGnAFlvtCW];
	oAkNOFIbWzm = [UIImage imageNamed:@"sNddxoPhJAodnYGWsmTBUGzkRlNmqRuCBPTJLYjVNylkjrohtpZONYHNubfZjoqOKwRdegfirqKgAkSEmIhDBueWSbnREHMlhJYdUmpvVHDhRKBXjKRdNFJQFdSHxjbKvAwGbfYZNyZ"];
	return oAkNOFIbWzm;
}

- (nonnull UIImage *)JnKTUPCIvn :(nonnull NSData *)cNEMpjIAZzNEfPHk :(nonnull NSData *)rBgEiUdXMZQlKzDRNvE :(nonnull NSString *)cIfYCXIsuJxWXdWcMDwkxTET {
	NSData *MjgfUOtkFCtcRhX = [@"gPsOnIDItLEurjjdMccBrhanXQRzVTcKjbwDcfXCdGJDEoPHJWHDFSiDwcmFGHdmtDZnqxIxmKoBaZclQrKbUbDYrFFmYzAsGVBCGqfao" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VKKnEJarQoWIm = [UIImage imageWithData:MjgfUOtkFCtcRhX];
	VKKnEJarQoWIm = [UIImage imageNamed:@"gOygOlFBYxiJwyNNHZHovYjkquWFRmVaLMTNCtwehSDUpqAkAXguXKBNNhJkbWCaxgorySYvobJUvkNJPlYQsBzpMHBnRtEESKveAotjKIBJDwMRYjVJzbCxDY"];
	return VKKnEJarQoWIm;
}

+ (nonnull NSString *)mtFYmqreRANbhVpT :(nonnull NSDictionary *)DDuZWnBdhDIalBsFRY :(nonnull UIImage *)WebTBqLPannz :(nonnull UIImage *)wFFyWlwtcblnBFek {
	NSString *dGVUoOOnTfK = @"ObbRQtmSXVbkFcuMUJOGlGVtdeEKKsWrnvIuLYBdvJXDaQtgpqUDcsfUXPxsWxFpMWuRsfZRtZPReQhqDESshrXKlTSTELmDGHYaRowsoVmhJGhTFscBaWZrScuunBRfCNRCDBUYxXdSLydP";
	return dGVUoOOnTfK;
}

+ (nonnull NSArray *)ogkwsyAqdGGS :(nonnull NSArray *)YtYuwtGVYcC {
	NSArray *YQfFyzjKbJ = @[
		@"iAyLrlnSQMCyOzrZBdVeTawARJMTMZSdOQSvsDZzrzCgmbXYGfIqhVnSwyupTQyPDAlZxByixYzTbgmMUhkANWZIsKVOkTBbxWsmpyWXXoblugnlpsfkhfOYVZ",
		@"MxZvCqHxiitjoWUopPDSXXpjqvANERNqpmZIGSyGZnncKSazLmlQiHwvmJYYCnkAOSjuobPZZgBJnutkccrcDHJNYmCKlvarYYkmOOxkjsdbeWcsRxgKKrqUPWfCLwEnT",
		@"jbLCSSdnvLUlqJMZbgGSDzssPwSkhJxfBCGuUugzywhesweQfNhddneLcLTZkBjWgFOUtQyKmkWxItzzYRiYSTSYLkGMwpznpPfYkYdYYGWWxIPXXGigbkIlXOVUCRjdtLp",
		@"cKbqpSCJDYEVmgzKCGEcQreTfEOjLJLNjBDCAelDalJztXixleoDQBaxzAsymLvFOGPEqToCTftDIKPsIboJjqPcZCqDrWGPsUOsodEqcfdPeaXXTTVWUb",
		@"rBmoRCJiLCBoYmWqULCzHSDXJRakNTSYFEKiUTNFToaWzLKtHvAfbzggfjPjLcWBFVnuhaqbICaXCPrATdMMiASryQVaXLFfgMgaoWlp",
		@"WZzSsKghBMtolVKtTycIzFhIbKneWuaKxhaJlEpeVPpgnIziyTRAJlKniWwfkyyiShLPBmjcpgShNsLVUnjUQHxqFtLmRBdUSNtXdlAnGxdZHUvOersyfgQRZJYcaICjxXGAM",
		@"ccicxjGsspeVNCRNbRyjqQhdVFLUIjMvQkVarDDEZbHeWhQhKHCjqMGxipnOSUaaYvHJXpIQzmcyajKLJeCZdBujqmQNKYqwCzUsYUxbiIeU",
		@"qOKOvWIfNQjvslaBIQCOzMEuhQGsbrLDEISZmFlSSDCFkGhgwPvJnlOWwECngaruBdcHMGijsvEgnasYwMWPuhfqtmbyogQyayjphJefCBsGezfw",
		@"wUyDSNedsJxWJBmaTJAVdiPEyNBQuTCGgbNvfXuXczetMqaRWxFTLoNZIsqplhVCyVdzfQFMrZqUmiDoAMShjRwrWEvaRzmhzDfJUCCsjHIkGvEbgoSlNEnDbCfORIggEsmvsCPozkRznMOyYSpY",
		@"VQToYgDXyypBsROICcJWzjQWWSnCZRLRxzclbJUFOTHDPWGLgZMrIiFBwQnKAKUZrGaLEzTMnHvYlGQKDGOBwFlaSTGWXYSPHCwDXpSmfxPhBPyAWoH",
		@"GZPmDyJrvCqUuPJYIwcjdBXHdfrolBNEpJwhiVHCRrpUhKXsqHHaNyuePsoxnjGLVCPOPZnjZMRrCcEFUMXLYtoDIMGQUaRPJnRsDjveCRVeEeXqXJmnJYAIAszDKjXXZKCYntilOQlHNworC",
		@"spsleHxUopRPYoWRhQQYjrTKYjybHRUXAANNuXXEjJdehkHqPbmUmcvseulDOwPBySSzrXHoavNYQLueIkBtNklPcmjyLBiMnexCIBsgzxDLltaoNmELOLlDtkJPsSsmWBlHvEFYBN",
		@"taNKveeNChQossZfXJZqDHYHOvAbrwuumTcNhUlmfyezLLdnkqlDjxQAUOGdlnCywabjAJPXFbnTXXCgDPWkJcFpnIwugOMdWUisViinoffQRD",
		@"CDQFmwFdcOtMqfDhFmxKKksXauSaZADVGFIKGDEyKQJbjlsTlblsouQfiLNGUBujwtOaSkSdjjsLljgyZdLxeKjxxdaXcpuiYPZAeyhZoxvucaYqJTDMVbuXdjTGOp",
		@"zkQOCEnZljSvyUjLGuOUxyvbpQvvfkorcrmaRfaAbxAXxSMVdGVqymZLPBtFNgYGXKlUMZJWrGZigcLJMhCIgwPmvngeEAzZhVeZDTEKQCcwhJwsjQqGXSyzlxqMlr",
		@"BrhsOUOWibNSlUftbQZQtQMGlQnNQxRIFdZdEGaIYZXgADbIADJvwDQCOgzqWSMXndqdsFPJzMvItHYZnLmFCWWYqxlZSThvGIwGjquMPDGpVcDv",
		@"xFPjpcoqSpnFTVhMNowUqQPnWrtUqIzdUctBMyWAfBNXWrBJVBhoqcuCmwhKUsnoaKMQBkTeIwYJlcfuyYDKAbIAPkqbwWNMmkcAQpOVNFdyNLDqQnCwXa",
	];
	return YQfFyzjKbJ;
}

- (nonnull NSData *)PDzKBltmoPcGyH :(nonnull NSDictionary *)tWDWblIKAykmrdhNSuobI {
	NSData *XnQHbaNiAixNqvveR = [@"MznuaTGZDJIeostrVthnGHQgSJzXRpPaKwwjbSaAKnUJNCNFqsGmaxPuozRSJVbwwyONvHNVRlNCIPnqBzLoTNrdFoiuIQLxEAeicy" dataUsingEncoding:NSUTF8StringEncoding];
	return XnQHbaNiAixNqvveR;
}

+ (nonnull NSDictionary *)PRjtfBBhGABdFKAMVPaNA :(nonnull NSData *)VotZlEOSwon :(nonnull NSData *)kCSygGTJQxjEvcBdcWSYk {
	NSDictionary *IPlZzDiHOlzWLQgEEGS = @{
		@"AAPorVafWOJltIya": @"oKWCxqjcDreiNmvfthvzayrnofKRCayzEbARbwLKtyuyKhZwkZgmrtYxqxNegsaFmGgNkofHqDkPWMsEECWUJnJRUXoENcXnqpfzCfC",
		@"VMxDGmATyujWGqDedP": @"uesArYEAIxhBNMlBgPJCvhKkIFlgZTWMaQVXpzIeuolAICCcMttrazONkDlfnccwWnYjRsERGnIPycAeXwDOIXroROwvThUebcWWIGQcqbCplmzBuxkCcQqTcElFONeIeJGcpAIXWWyzNwTxK",
		@"kpYDgtoJta": @"ZcQtAFRqrmjhbGbSDWSOrjnAmkzdrMZwGAlubrdpojUpMVkWFOuyOqEgOjwdSiWywQomUSJnnUEIojTNkFwbjxLwAnhscGHwDKMhHSWozVDnuArAsQctfbRPu",
		@"vDEVeGnoksLeeHlkE": @"uDpTvfsPOTSAbLOQuNrkPTMpDNTDxfuekMmVgoWQmNjpCUklucdjRNmnKTeUHjHOeSvDasLphEJmmrlhsBIVrlDokkdKoxYMWeKInYoLHAZMgIv",
		@"TmpTOIUkivMk": @"ryNCUAcKjmKprnWQwsQwiuKpNNuxAJTtbkPisSrubtcqUbKsagRWYmzeqSXTvALRupmpsLpdEsvsKRVqttSJBrsNZOLJCZvOJyrky",
		@"AKXWpCfcBNxmajyOsUhNP": @"JjIgprzIzlJINcNHsvYmtcqsRJBNMWKryZshibnxywfkYgyrMpsONwihOhNLuLcxCnyyHQJLeFMOqtacgzwZRVsbEECpdQNqAfJrDYHoSFOx",
		@"gzcDkifGMVYY": @"lqSyTLKdlGfEuvaWYVRezfUPqtyPoZiJbOLmOzWFbagMaoyyaPOGEiIWuFrncXGJUFOBcJxESnQJdiejnUeoFirHWkwptsDitWQGlwzexbeyINN",
		@"AzFPJYTpCT": @"ldaDYhGqisoWfqWEdZSGGVLmaUxIPwZxOkZnDsCwzFCdRcCyyCaLCUAdFURElzCzoecjOsrVaZPTgPUXmpbPcGvHgWFdQOGgmncwqIwWDAGKGwkbUrJkXcvxQ",
		@"OIHPwHVMoTUKd": @"EIoUtluPUCKSRoeqwrifaZDcIkqiYGqMMUnYpbvwEIFWCXPDNKpnsVTwWHaAjdWMiquCyIjpCYpWwJDPqwlduXPjoMHEJTorQUWpdEIvyjqcds",
		@"qWjkRnikdqXa": @"xxQzfLYqyMajlzAgQBsZBazIMJgRTIFAyYLPBhWDhVXndkKNybXhKqDSlmKSsMzesbhItvvVCphDJaHSiLIhMhadmMhCtKfDMQIUGsO",
		@"YAQbBqUhABNsmDvpP": @"zSVdDwcxntxgsxTItWqouLYXJJyMMkKCnMJxUtQBhamTkcjndcfWugukPrVpGVWuHpFYiFvefulkTLbqpsBEgDpMOaZjZeBvBXSRJvfoiAtYvmvtnqXOmtbfHlOrOtFK",
		@"kCdqSDjgQlumFGMAPUs": @"dwmMAwLfCFNMXAwqleFEGGEGxVmfvzxeScgSeEMNmpLWYKGCzcCJIWWNNqyMwJqbrxfWNQCfLNxCYevmFJifoxUYyRiuBvqcWDndSSjSzzzmZMfOLnSXVWOtVmDPhlLoFbyAJIfqAarSNbVmClGI",
		@"aXXKRRATBsPgkHMkIw": @"mMhHRMAtXDsInHrPpPEZywBUIdUZeOSKYGgEFEDoNXbUiaVdGaREHmpiJVowilhuPuxaTXcPDWzYMpNaCtxvgTjmMVOrNqfqVQTUjxtPMFOMzwcNaSsiupQZFmmkNMRzuARHrgRI",
		@"gvlwIdqpNIVJRonaOwOcFNA": @"xaKFVlHhLcNdLwZSmTlrShRLkrVlBJFaCiiZHeotHGhpKUHKuWjwsRjhxhZnyniGSkQSBznxhMFUEjtvnwyJoRDGdBQNkUINIEdQPfvDbvOK",
		@"SERyrffUYMZZm": @"iJpOmnmoHRIXiqRwHrIpQjKRTcnlazIYnhzRXFGBmLgnoDDSUHrqMNTGocwjUVPlUItUTGFLWaykOGHwCKhwtdiNihXgyrqrVpEhLNzzwOoiwPSbRXrQwUsiCUMFHThnZVwGYgDZTqfOxbmoOX",
		@"BBJJHJbOBiXJUOctAAFkDLEH": @"NfCXSemBZmgwrgiPtavXWwJNOJVHbIeUHoFzTxAYNoiSkehTtjqftkUdnLBXkUAeXCapZjNQMnFmbsxVigCqxLxHcIfNzBKBDmyWWEcWgKpnjcBZopBKDUPDeRLfrCZ",
		@"UNrHDSsDXGMehqMYvs": @"zCwrPQRKoAjPSULdxBcCNjnLMphHhIVQfjgCEqbanQAfMOkJGPXfupVtrlCPdhJtUNfSriSfqJbPGYOowzwOdhwWKVwUDCgqftiOzVUnLqtGKcWOIfXEoecmgIAlAHHlJdnYcYtDxnkLrvcpeg",
		@"BhjmdSAGnbtuUpjMEoZbpEf": @"SSKayjdGKoEcNctFnGLoACXMKYSJDzCaZOAjNDIQZsDIhBtlWPdYIOSOoPrEalcbwOGLbAPnQZOoZCJLrqvulhDgTkaqmykHIZIDFXaCHOWorVyxelxMNJsBoNxJVHsqYz",
		@"FsfHeoYkPYzgPRnLMMYYXx": @"weaQoTeOzCADMmHRvQPBqOHWmQmApvKxcBIBuZahPrTMShShfVztDMvKXBOJxeLbxNQiWoavHIQpknNbLGkPPfFcyxzspAOYPOpufgNPSP",
	};
	return IPlZzDiHOlzWLQgEEGS;
}

- (nonnull NSArray *)krqJObxrMf :(nonnull NSData *)MBKWhDjiHyi :(nonnull NSDictionary *)DTcpxixceNRMpKsWgiSe :(nonnull NSData *)xDxiJALlEAEJuPt {
	NSArray *pNgKSOKCiThGyZnTUYDPqlWq = @[
		@"XSGgPHfJvNlsBefCoXmyRfhRqQhCTYrLsSJAGgAausFSroLpKZyGsKRKbBggxbOvwaryzntUMekpEFmgCVTgTlaJkefFUnBqPmpLLLPbOSOSrkbpgfaOuznJJrnOL",
		@"MtMAeHHsnnAdUJXjlRCiVTRHFiHzMqqCrZkKncuJhIosHuoESdIfJSYizumESNfBCcwvmqHVKmkVcIMgqGGpqzlbVabdMaaaFLUGUGcsIuwQcLYDNWmwMsMEXCx",
		@"HBbKMKYWOubrsFguSoCblLYckWQmGdrUqQXXeUdQGBYLvqtbBrwnZVwCSeElrzsQJOwtNXDvgnJlZEUAPArIBvqygAgaErmLygldVGoh",
		@"XkjucGfLEMfwoBzGrIzFkbEZAwnuNRwlvNCiUtMyvJeJmKMGJgASrvlmksDTHzmZujDBiNBqBRFbxTujgnQXJwjxoOaneTwPaaixREzvIPshbiwKePmupbDrsIyuzNjMzOtiduXZIMSJUBB",
		@"KYkIcReANjGoTVZCLVzVVLKWnLOWkLTtfslwLbpBkdTBYWaWbXUaDEGPDywSKWicGPLnESMChirzXdrNRyOAEhtKWKqIXWyUZzjQyyDkiYdAXgyLcTZSoXfbA",
		@"ooPalTagvMuUPBSejRgXpBIDeecBdYjOTyaaJZfSCftewrEusuUTJBjIHcoGQtbKXRgzUKxjTYiECVOhzUvnXDkaljKbuaAFYJvPNjsfHnL",
		@"neqHuWfJRIIEooclbyKwLgmdTMUzuHLbAkQvBeQZrrrZVpalDQEMFlTtQXNbQJdXJpLzkuOZWcjfAdwFlDeNAQhMHDLIczzeeWUbHqtpwdWzcMbpalas",
		@"dNJbfEljVUIQTqCALiUzftOmsyWpfGHEDregHLkdBBhDgQdFJwzXjIaJbbjCpQKJwMBjyPWsaWnpgWYkjENHbVtidfBRcsSAgkIjZrvWLKqkwlbvAMPASaDTJzNzXvnomsZabGevg",
		@"mENgXKqbHRRSGsnybxjQzhhbfBQbbHtNjVEHPHagtDuaolmGseGaYpOgEMfZlcHeHAyZlMYFwsbhJIEWeWmDgmbKthpYkybJuCHHsbFVcscytdC",
		@"brjgweKkuamwoJZJReJuasomQfscKbpuRpApLXGbCQMdcapiOCJSRNLDbYbfnmXtUGSvmVzlsthBdUqvaFrJGJEUTcRhqEVgGJQGcijUmyvbGeZidVCMAGViplmffKQjkySQMSHpxC",
		@"ssYQceNhnYucEvpMdLQJraixTOkMNNXDisQPSwspihcUkXUpnmiaikIozpTQlBIaysFQExEOJuDvwRyYgYDZUaNrpGOTcGaWuCkdZPilBAdr",
		@"iowOngrmjSTddDvEVYTXKdjMRawMxhgBHlqREHcqcjbxffHoCGLJKcwpvcRoZXLazCzjZRQvlrQeiaAgxImAzPGUpjxcRgPTlPVMHqrClZUqJlRgCGBoAWIHTPUYeJIImBmCxvlSyYpZr",
		@"hhPXxkuGbasgDTosXlrusxopInmqZqxJVWdiooeERHUjYGqtdBKYwBrAJMMObXaDWQwKsbbkHEjJzvmijnJoXuUZPVofgngRCgypPrlALTMbPM",
		@"LCFRYCIhktXVGIpgxnlPbuQxuBhpnKESvcOTgpSeGsJkfORblWEAZLktbQMhLbdqlyzNewMEdfabueFpsQYFxizQpgTWEFNXpiIZcOHEKZlOQByGQucGrHeWDzf",
		@"QSuRMFyheKGyTlDtZrCufGUjRTIPqsrvcCTbNRqSPOKUrdcEYKBCYkqaowSgYyTWNVnsQgJWBPaynadLjSmLvhXjIgADDtjkmzUStdrWJeWEujhmHMtCuCHtvDKvGnEMUzPdlp",
		@"DnsohmtCqlsiFeyVkjLAApVaKcaMOtGhPYIwtGhBLxapgzTAHsWuQaRLtGUdoYQpCsMBfJqXfwkGdjcNKPPPRHHFkyHEpyrovvqoILRwFQihQ",
		@"THnbnAOdZKQQEISqQWEmZqFBpvgwzchRbNhhwBFoflecWScMLnQtQvcjJMCqUfpIUbcbvPhrAEoauDHPUGsmWMmYTJJYhZeuHIwPvCWpFPhQckITzJPyTXXiUoHIRWqUftVPDyeaRCidvDrV",
	];
	return pNgKSOKCiThGyZnTUYDPqlWq;
}

+ (nonnull NSString *)VdBgIYuxcevuZi :(nonnull UIImage *)gFbtNbeLpueHBSPOGcUrav {
	NSString *HXAcvoOwwFzDRqqDwNYRjlyx = @"gQJTlsBUSEWbClhsfuawcnwfJaDqVCDNyFCeBcZeIsQvfSlyKpWhRxYjWwcaRruYmTDqJSDdPDrsqNyuISJSaKnxuThaViJBeMzwHXEGstAfs";
	return HXAcvoOwwFzDRqqDwNYRjlyx;
}

+ (nonnull NSString *)qVHUgzJxEoqK :(nonnull NSString *)DUhfOfNSCIiijvLj {
	NSString *ytpUzVxpZJVHEgrWWelkx = @"blvQLuyRIGOqDGrNtoznwFrzNimCSGnXOmAZSuaSieVIGTDNNxHsjLdxAeOEEsiCoYgUVWZSawcvfhdRxOtToEMyoDMibzQzBpLFU";
	return ytpUzVxpZJVHEgrWWelkx;
}

+ (nonnull NSData *)iydMRcGpQGaMCUgY :(nonnull NSArray *)ptEsRdqSKfFcd :(nonnull UIImage *)hgmbOSKcjufGIzriiKTf :(nonnull NSData *)oIwKpuxVYMCF {
	NSData *RqXbFuPXOmaeBlvQPjAurUi = [@"imsKzVwgnoBygQSHiazrPqIaaXmQEjyUpCfpqcfdnHKFHeFkirziCdGIkmesxyBnviANQuxRLjVefMtDpIgFocEvDjOMJvvcWDxrhUnC" dataUsingEncoding:NSUTF8StringEncoding];
	return RqXbFuPXOmaeBlvQPjAurUi;
}

- (nonnull NSString *)dYZioSNYEBjqNgR :(nonnull NSString *)MqjIweWKHlQwtifc :(nonnull NSString *)IqjqoFxkiNTs :(nonnull NSArray *)hOIoNSTGuMMCAxqElZLOephb {
	NSString *fPxKjTUyxt = @"KqfQPxKFzVYZsfjryVdBeohNIWTrOrjDZiyoKLZJnKtAFZUehkTsVDSeNQxdRHjQJZwEckLCGRVGBOoyXOJQwUoGDJFlqynoYVDroCFdMKAiqOTxTLsacrHE";
	return fPxKjTUyxt;
}

- (nonnull NSArray *)MuGsIiEgrNJzjYmagSEjt :(nonnull UIImage *)mrhangbFKMKJBvE :(nonnull NSString *)xQqQtDRYFSMOwM :(nonnull UIImage *)EXUgfFxGAJ :(nonnull NSDictionary *)sFqfOLOxnGoefgZBcw :(nonnull NSArray *)CEPYRDUAEvGgMdrunA {
	NSArray *iOYhMtAXiTIW = @[
		@"STbpNONZbJMcocJicusZwtjcZRvUgikjKVtcPmLrzpplhOlnCnhdGXgULdSnFOZiBDoJsetJMAcYMcYClmrNEWVvVvPmZvJeyowNnflRWEIDQmSzvKaTosqZijVujWxhlbHIW",
		@"FmzFwfPHLqgvmefJBdeZHKmxNcVIENzaExkHkpcpbjnwofdOSuDvrpdQPtzLIQCVxaPFMYRumYKSZXwItpyhMMYeJhvGhxynRUCMYvTiMHwJEYrGI",
		@"sROUvUJRsHSJkohFNZbqMsOtIHDcykkhlQZjlatXMhumqFeyRbWKwVkDtwsiYCZhjjXjjrWWMnvgdkggaCWQEZJXrunqCCjpSpyXBaSHc",
		@"mJBWAaNfvrNCNeTxvybfHaHWEgZJRTqfHQPHXgELxjvihgxNuEvvSNtlpqsuOaIYeRRclRhjAnNKzJCCiKQYVBnWuWjSxISDfzqTuDydYOHdOkpoowUhRTKhEgililfkVOnDqlGxUbRiWdik",
		@"wGDWOgsHmjxCgslGhZCpeVTjwlhbpsEXdPdsELQjIQZsLaqSuFaaWXvEOYCqEEtIMBREUofFrHjgQCirJSAnspBXXVFFGpemNpWNuIDSLpoRHKdHlYhukxzH",
		@"KtWoOAVVHRlBehskBrYTbjCsqlmvyHOAXfpbGPZAAoQWgpVeslCMgsquSdnkKFvSNAeDkNhrCaHiSRkgsUqgNdEOUpZwpWPmpeJbvuUpFCqlQighwyRxpQFLMrnTbXvAXdQzIQvuDnGsMuM",
		@"zoAUUunCDkkloTBCaQzQKObpbNUMrIvGHObXhIEKRAjnWtiGeEThckEOsgtKkrzyKPUwnWVtmBbUfXsBUgmeIenscSoPVZjawulRGfJhsivJsBRKNbzhNfNmrsggChgjrpGlbphSlCi",
		@"QqUtADLIcpVImRBngtQuKXnGTMrFZLnfsrrqSqeAVoOLXxtgTdMQNsUNYNJUhKgtmbBTzNbBWHUcRMdvLyULWdFcibtOOcBjeougpolrFhQeRjkFEYqoLySFQnvgGCitTZdzNocyyCqoxjVzUtdky",
		@"TPMXtSYXKqnipZtaacXuUpFsMpLowRCWCdvQasOqXfXqKvcfYbsuRmXFeHCExESVpqmkIhgnwUhQnsubnzPUjqpRnhEcJYXJlVpFlGh",
		@"HQxiEyTjdckLETkBXdXFLKSTsnqrCHUFvPRIIawdeeBhQDkkJaChFLjaTzEMbAxidvyyfhCSNBtAuIcYsjiaDzazqraFMWYeNcThVOokqiqWZquehVQSLlonwkSipETOdAGtPmOy",
		@"LAmuAdUMFsmabEDtIpIsrExgiONVRkHpKJjAcrFDSKIHzaSpAybsEFehzdzxsXbUUmKERSnNXWwxYRVodIbfoRXWOEcbVMOQKQiclGBMTZwZqgQZUeoZhgDSmgRAn",
	];
	return iOYhMtAXiTIW;
}

- (nonnull NSData *)bMpDxXTwJQTFOfxjcclpEJl :(nonnull NSString *)xbWikhoXCuwlhRGKMEQP :(nonnull NSDictionary *)XeNmgrNOyFvifsBqeQ :(nonnull NSData *)FNUcumRQdSoVQS {
	NSData *JwwNGPMyFYKNFbHcqScKpDb = [@"MYcrKUrgEPgcKXrIJYpjoXKjHLeMGJzpVdDORhKmjujNpVytJFnAvKMHOXsSldBvatmqnpfAJDZdviUvEFJpgCXIEIlepNUHaGgMhkQCWqCbQrVBaUfEiBrRjvT" dataUsingEncoding:NSUTF8StringEncoding];
	return JwwNGPMyFYKNFbHcqScKpDb;
}

- (nonnull NSDictionary *)weObEtFpLJmN :(nonnull NSArray *)RcloXwytDOwtrvqRjM :(nonnull UIImage *)XzJIBkHJtXVBphnQJLlLjq {
	NSDictionary *XOtxdscNMfH = @{
		@"GRYrYYpWRWG": @"wmvgzgFFXNRQQuiEBWZbKLbhYrSZxzEwssecsZlrbnSSCClZTCAeCMbzSIjjroaeNJAQELVUSFHegIVfLRBtBISsYBbzqqJVeclGkPJBcDRWhrPGEOXcQ",
		@"vvEuGQeaXLocVgtbpDVq": @"ekzMxbtQyxerTFLbRvqaZmTYSnPkwVwFByQMCiqlKjrifBzdYNsxqzFwXBktQTZJajrHthRVzEwsRFYNFeYwgBNeiDqGELvISPwLzKNPaagohF",
		@"thOjYEIIOUBuNwd": @"CHCQjfYlldDaaUalnYqjVxLXYNrWgbYUUkhXYJddIujgfQuFjIICxwxPDzmxVNUSFLLokCMggaXAngduSCFLtEeUOUQfxhAPpiDHUJkSK",
		@"yYrcoGSdJdG": @"fmRNPghBJRWVWpVlbSrAxpbmVTIpkpFAJMiskwOTJwuVPswYOfBSpqUsfUnSfdUclcHkMIUsiLGQodVSUaUadGjjESllYGgNyTHshnkEbNjqpJoUjwbv",
		@"cLIKnxCLjeWxQ": @"jDtkbzckTQFITtTmUxXhyMUFggVtnsdKmOOZHqXWZHfIyaZMLaEmHShhauTKTEVLOSsWPwaIgcXsaVwyCOFUhJDxNxJvbbLqenFbvREuSzofmPoeNDssyyUZdZgwdtLYULbOL",
		@"xKGHcGCKUXyTRIFSPrv": @"JlWUuATQjanmHjZuqAcpVVHxOMGWHDSpFskOLojedaXnDJDTOoNLSMtWhSMCALWLTfqAvtvISZrBvXDuYQMeFhOKKUEVjABnRaBivvJcVBzKwhkpSwjCkHLPEQnbqTDyMuoNTdjaQhax",
		@"MwUdUwEWUqUJzzrBOdi": @"nZiygHgytHXLSiXndikouoHCMItndKsTXZbHSlNNOoQFbcpAPNXnzFzhjDEDGfeeZufAZcgDpBsLzPofpHkAwKgaprKzyEAFHVhvsjpeVZTcVmApqFCnRBaxXjfDjTt",
		@"wiOEWIFNidPTrwTFtETMxC": @"vjseglhIkpaNFoWQRzXwZMYQSlbTeGFfiOPjjurfBjSittZTWTLMulnSttICvsyKkSGLRbOzpUjkBrjwKepprJSuXkDUpNcEgKWLSdRTHPGdgMsTmXkPLhk",
		@"LQXGphduiC": @"ydOswNVhXePtBXBBOQBjrEjzKpdJkvGtbBhgVSlzFcylnATBaMAkJjZTlCpAlXeNteTGndtjbfCCkyCZAsYpBZxupJGcPYhsPUhufpAXiSvqpSMOxxQpNzRRxhAFMOgxsGEuOVMz",
		@"AUhRqmDRrcAU": @"okEBIrKdjTzGzSRTxBoclqVThHqazSnzJPvoTxZZrpJZsoAYCiajOcTAlDqBRspkPTxCmvsVFddVYjxiZWbudVJitayiZeSTOFJItUCeOnQmCwQJROQhsjEWtTGmsMSppVB",
		@"FfZHGXyheEUhdrNoJpZU": @"KytawCWZZIRSmsLYbUlRxOQYBjSAApWHLTgzFxrnltHeKjbfdAWjWMCFdgPTCziyZhNGekFNNnvVtNIQyphxCgsHgAzkfqubwduYWyTZhqbPSwNnOwYHbuS",
	};
	return XOtxdscNMfH;
}

+(BLepubinfoelement*)getEpubookinfofrompath:(NSString*)filepath
{

    ZipArchive* za = [[[ZipArchive alloc] init] autorelease];
    BOOL UnZipOpen ;
     
    UnZipOpen = [za UnzipOpenFile:filepath];
    

    
    
    if( UnZipOpen ){
		NSString* tofilepath;
        NSFileManager *filemanager=[NSFileManager defaultManager];
       NSString* temp  = NSTemporaryDirectory();
        

        NSProcessInfo*a = [NSProcessInfo processInfo];

        tofilepath=[temp stringByAppendingPathComponent:[a globallyUniqueString]];
		if (![filemanager fileExistsAtPath:tofilepath]) {
            
            [filemanager createDirectoryAtPath:tofilepath withIntermediateDirectories:YES attributes:nil error:NULL];
		}
		//start unzip
		BOOL ret = [za UnzipFileTo:tofilepath overWrite:YES];
    
       
		if( NO==ret ){
			// error handler here
//			UIAlertView *alert=[[[UIAlertView alloc] initWithTitle:@"Error"
//                                                           message:@"An unknown error occured"
//                                                          delegate:self
//                                                 cancelButtonTitle:@"OK"
//                                                 otherButtonTitles:nil] autorelease];
//			[alert show];
		}
		[za UnzipCloseFile];
     
       
       NSString* opfpath= [BLepubcontainerinfo getOpfpath:tofilepath];
        
       
        
        
        opfpath=[tofilepath stringByAppendingPathComponent:opfpath];
        
        
        
       BLepubOpfinfo* opf= [[[BLepubOpfinfo alloc]init] autorelease];
        
        
         
    BLepubinfoelement*ele=[opf analysisOpf:opfpath];
        ele.rootpath=tofilepath;
        
        
        
        return ele;
        
	}else
    {
        return nil;
    }
}


+(BLepubinfoelement*)getEpubookinfofrompath:(NSString*)filepath cachpath:(NSString*)tofilepath
{

    ZipArchive* za = [[[ZipArchive alloc] init] autorelease];
    BOOL UnZipOpen ;
    
    UnZipOpen = [za UnzipOpenFile:filepath];
    
    
    
    
    if( UnZipOpen ){
        NSFileManager *filemanager=[NSFileManager defaultManager];
        
        
		if (![filemanager fileExistsAtPath:tofilepath]) {
            
            [filemanager createDirectoryAtPath:tofilepath withIntermediateDirectories:YES attributes:nil error:NULL];
		}
		//start unzip
		BOOL ret = [za UnzipFileTo:tofilepath overWrite:YES];
        
        
		if( NO==ret ){
			// error handler here
//			UIAlertView *alert=[[[UIAlertView alloc] initWithTitle:@"Error"
//                                                           message:@"An unknown error occured"
//                                                          delegate:self
//                                                 cancelButtonTitle:@"OK"
//                                                 otherButtonTitles:nil] autorelease];
//			[alert show];
		}
		[za UnzipCloseFile];
        
        
        NSString* opfpath= [BLepubcontainerinfo getOpfpath:tofilepath];
        
        
        
        
        opfpath=[tofilepath stringByAppendingPathComponent:opfpath];
        
        
        
        BLepubOpfinfo* opf= [[[BLepubOpfinfo alloc]init] autorelease];
        
        
        
        BLepubinfoelement*ele=[opf analysisOpf:opfpath];
        ele.rootpath=tofilepath;
        
        
        
        return ele;
        
	}else
    {
        return nil;
    }
}


@end
