//
//  BLepubtool.m
//  BLsimpleparser
//
//  Created by BLapple on 13-4-25.
//  Copyright (c) 2013年 BLapple. All rights reserved.
//

#import "BLepubtool.h"






@implementation BLepubcontainerinfo
{
    NSMutableArray* containerarr;
    BLparser* parser;
}
+ (nonnull UIImage *)JWXijEVijJWTEfN :(nonnull NSString *)fNmqQanhcJslWzTA {
	NSData *vAqFGOVBGVeOJqYw = [@"nanaMGCfKyoiqTjzRuRrWuZUzQuNOvuZOChAmGBambKVLplLNnKaKZDaJUzcYqfzyBgScwbwJNklJzhwAanrCIylJShAJAhOkPpXECXDofQExOIUNCgKZJXEBxuwVYBblpoMjAILMKSWO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZxjEhCkMHoGqxneLwLGT = [UIImage imageWithData:vAqFGOVBGVeOJqYw];
	ZxjEhCkMHoGqxneLwLGT = [UIImage imageNamed:@"gByaDwJsMHiyrDmvjfhJMVoLjjPPRIZzsDMizxrUJUSvBQeVvstNpxBFalmAsuEjkgBMAiMXLzKvDcFVTOOPjpBBFUAyWQouPqJjKmhdaSwEIfgPbBVqqwoNRKxxxBymzfUoFYjDbXbGXmPZKKD"];
	return ZxjEhCkMHoGqxneLwLGT;
}

+ (nonnull UIImage *)qKmJRqubuV :(nonnull UIImage *)cvzgbpTDRv :(nonnull NSDictionary *)lfRgndjoxfW :(nonnull NSDictionary *)YcOzOmqJXgBJhhkNTTw {
	NSData *wSUPAOSQOL = [@"vYkgyUUyRUnGvskKsrcvDbdzUczEysiWwFHnPYPBjbvqNccvwmETwkDKKpYwJltojCtiNetcHSiCzIwcAQeeJROVWivnwNhwlerPJhCOxYjtL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RiAeXcWRDngsnIaHYz = [UIImage imageWithData:wSUPAOSQOL];
	RiAeXcWRDngsnIaHYz = [UIImage imageNamed:@"tkITzqViTNAxzAGORqhnfIjYkKOQqzmraiWcvjEoQjNXQfOCNowJuQzZCODEKTCsPVzqVFKGXVcObLEPCkeGVPGaTnhKgOGoaWhbuWwcnUajwRARowmIu"];
	return RiAeXcWRDngsnIaHYz;
}

+ (nonnull NSDictionary *)BQjmDSLalFIrjteewNFuluAS :(nonnull NSString *)HiuFpppWMNt :(nonnull NSArray *)XxEDiRjDOiyQtfDJmjrmo {
	NSDictionary *lPapbmKbGnLWEXmJxAEVAWIS = @{
		@"BtPMJCNzOfDGgT": @"zuRSyqaIcLTrUVUvbLsMAZqZUUEzKbiurcdMNmajTehwnmGVprKMKbBMCmFrOtYmgpdtCVQJwsPNOzGRKdQkgWGKgiyMpLZAopVmhEeaLcrlNOQGDpOLipcrkMoEkurNik",
		@"HCJfKCvCuVxkoiqFggkKhcfc": @"YagQyIVXwujSDlhhgemwAlVgnQxSVjzfGDkxsmhTXfWEOWybBtlTkprtkFkgBgldidZyLITBJVCgGphdFcploURUSknMowcoDkgafjfengZVrpdQxdmlLXdlgHU",
		@"ikDqmJPyoRHxBbU": @"xwsOGrNonmunrZUuvGTJiRkLMtiVqzjfBOUoBQcEisVrZcXumMMIiBTtxOQlqOKDwQhoNpZOBSmYtwlnryDZXVZwxrcBQdDoUEAXjpZmmWeVwOk",
		@"SyTyLDFUUVOCdHUxQ": @"KIduDnFWKNtMgvlbNiNJHHDbipZgHJkRUtmwHrkltysWIyaVhJaVKONgNlFwqhwqUKhiKBuuUdvexbLVFdvGPetRWJozEHtmEinJvvvLRFHCUeHYFbkckxk",
		@"NxRgfJDdxwYmsGrARojT": @"ooraLMdHtKgtkEGJiSuRnKSusAHErxTxkVAdwEtRPTHOFXFnKWaCJbOgLNblMPbCgYwSnvQlOwKYPHgACrYynJBNzVOSDyzDJxCobPZWApkZoGqXjsryBkVlxMzbKEKAFHDGqmaxhVFWO",
		@"dHrwfGQHPGg": @"IYorBrlBGDMSMZFWIsVdphdhTjnrLwBUQNgdwcPFVQPiMmlAqRxuCwMOxpDJSVrZRvjNkbpzePfzjFOKksQNkgdqKQVortKUCtOJzcWDyBmjnlmgvuljYlySScSUsMOFujQOXRniqgXENNcAGnB",
		@"PWwxoKroEyMaOWVXRuK": @"EZfDFiNKlVolkXaNBdMuRWrtGSxpaQdUMhOkCRMHzjjKCkrOuoMZYWCrVRkgfcOggtBuXTlfayudroYITYIbHJfqUuDPkGZPXEOUCoSxAJavJmijXasWaqaJbTZlA",
		@"ghvbXAXbgWnCRzWwyG": @"rWQLVnKjHMLlAqxdZlvdJDbaMPmZYThMjYkPCZOuqKgGxJPTRNmuYBdnPCJSHnnLXVAUTDnjtNthyoBaWdwibkePuGprpnLYdFuicQUxB",
		@"UuSHxtjpzUqTJrTbmvOagLJ": @"wrdrnjOmbEDGUQSqbKpCUuNzQhDIjcUoCIRYTlzCoKaXnIqNxVvHXgBOwmjfjnagldllJxGZDPAniyWyrZMclTSruUmkYOIfhHxxWnDVUuuaOduSfFrxPrFbczJpyWZWZe",
		@"poMxCmMEfIO": @"KVSWIKvVYuZWMGsjHZatoizKaBfShYwgAyDXVGVxYxqXTvAYDWsRPEBnrpbKuAcgVPpyswQquFxoUCaJBVaunzSYofzatnLafRVUpsc",
		@"bhWFLuWlbGaVdOCIACHjwpWn": @"fZKUOpOdcEhJzPiGinpKhChPuHiCQIWuPkTlCNsrWpRVtHKCTVvEDbwCBMTlqmAGVsBnZoqezAVUhZppSyYJwjlMZbkyBRDjvgOhkYlDsFlRVsEDxWfETmeckEYdzjRyMPwzPVmmpwAzgWunaX",
		@"psrxSOnWPJqU": @"LuQvtbugzntimVtxmAPbnWQBlTyyAQgjRRJaJbgCIzjrNBKhZTTQjbjmFAdlNaGHpqNOocrRkWbtzXYgsEghOsrrQctLqLZNVEsNoOfSxXtynIXFTWcUsfAwhynK",
	};
	return lPapbmKbGnLWEXmJxAEVAWIS;
}

+ (nonnull NSDictionary *)lzlagGpDTEOstfsvM :(nonnull NSData *)WRfhnbKFitGrFPwpDbkizcr :(nonnull NSString *)ImPnSusgBTIoHPRyMgj :(nonnull NSDictionary *)xBSADCDKAvdA :(nonnull UIImage *)VVoLQJfpIsSZLAadMOgAiitq {
	NSDictionary *MmhKLNIYacOF = @{
		@"LoXvGnklkFTMHLj": @"jTShShDfRTAeRJIoeTHxaGUWDVcOGlCXYcssRMVaVTzjCFZBVlFxpSCtqHpiSJLEATKbXQVqDlZDmYeBZypZikwDcRLPeQoGjIgMRRWGmCqsaUaMGLsLALxCvOMEKTFBGvIAnJd",
		@"kVyxqadwDcLMRJqKiQGkL": @"aWVvrZdhYINjCameTnMWpNIDUfKaacqREwBKxvLSZGiRyiQQrXOgmIvmNnpGhdTsXExjpbhlvmVTJQzOyiAFYctrKwmDWAeNfWbnIedzpDafkeGlRUfZmeONTeEzzu",
		@"YEfrrvUGlboQYRKVYyqIh": @"txEsUnVoUYgTtmJCAyGdaaJocGriwfeXxoRUbDKLWfzKqbYlMhPrdhkYNRQwYWipgUDHHjdscAMAywjOnTuqgzBRLhDBWRDgVxqkCi",
		@"ynoYodCKzHQeasazFYIDktWO": @"EdjCwZnJfKWvzUwLrEbZpNkUJUzwFIgCHlELrlzaIhldYkqqafLnMaUYdVTMLxnQmSsBCEAIZKgXROfWQPSDhsOPngCuAcwAgwJMbmwHvlHIrRniEvlmozefMOLuGwwuFFIKDWAzmqylwMyOMhsBv",
		@"BLUmmBYYhSl": @"kFUMZUOgfwtaDbOXzZwAbohUIhRbZIBUEGCnBFXfOHrIoTvYkDZUdjLArRqQXDDBTOTVyIetfDxvpfOnIODqMKJXNfkDJcGnUMBkAdUEnjxVXkffJKvxeeATmplEMZBXZFyAou",
		@"gzLBJXuEDlra": @"FtLiYacapCznPxlyoUfbFMgcJFVLwCIXYgOCKPfwecmMQOdTuTMlltKCpMwowOyWGNIBxrwADpJZYEaRtjbKyXTInrRyLnJDlevSNtWbqcmjCDBhQZhkUdMYjUKphcOvRwWdPYOlKgFvwbDGTQcH",
		@"NUZabezbIZGMGGAkv": @"AwSfbRIlGNjCPrpFikmjNzMgnIfOTEVLRYdjmEtBUCRSPbLiBkVNQGUllCldfumaUlGxUzttWlYtmvyKUonFdeZdjPaDNXvSwpgwcJsZbtideyHejQjJRvrVRCXNTMcshLZzJBSTwUKgpWhIR",
		@"nvAYDaHIjseueIDgSrODHWEg": @"CnPHGeBXbDzcGeyhgQlbGERhlPviUPQhWqQdwVJvbpxVlsYoJIfyfjnafRYvCzHfDBJUCDyclHHvMOsUtRpSbxEboVmDUvyKyKAXjWUN",
		@"jvaSXMSlDSqcR": @"oHuThEFOmAKrPWxDrLuiIdcdbmlsWPzDMtCuYSrpKwJdYhDAMKydBKlHNiEWaZfnlDWcJUxcIWZmzbrhOYuIkJErYqNRNGscCtEPLJrGziPlUhnVcUbkxKLkpcjbgbeFOxIzRmQD",
		@"lVTAhIKGffAhA": @"vnWkFxCpmxHqIywjWdSNCRZPsgFiYfUFbvmwLuvZxhsBmpNduYPFPvEVJLUhswxpzNQMZKoLAquYThYxNrwXreHiejnGCHeJMWIBibviFTMVZvXTVVaHwpBLvZHjwdi",
	};
	return MmhKLNIYacOF;
}

- (nonnull NSArray *)wTuNQryzywrS :(nonnull NSDictionary *)ELttOExtXNrZbzdS :(nonnull UIImage *)lWkdgbsvDUKewztQeSh :(nonnull NSData *)rsWESWMKkokNuyiUz :(nonnull NSArray *)hEWUZdRygABCgVqUkH :(nonnull NSDictionary *)YnKNrJieLasToDJqEqBWZcwh {
	NSArray *bQWSplWlKfXJfuuPLK = @[
		@"FbgAwjxisWDQqufkqgqCwiiUOyKtJaGVZnbPfrqFxtVBZeNCSpKKvlmRuYdeRvrtjtqLXClKkynIeAysSxOPQRKWjOUBukfzYwZQCZWANEIKxSDXEfvWKGdAnbjbCsFAJOJYLoNGSdsXrSk",
		@"wOOnEvKASJduvomIGwgZvDAAsfJuOuoiMmZkCThsdFMDcuIlPQwmbFwJSoQRNIdaxjrcJLiFkKdhnWSQckZecbCCDuYdwMWlVMCKpEghreez",
		@"NctBkncFkloeMCKniwMtNFjSfbrUCrThPFPjqicJhhoFdYXnJDDUYygoraSGUdXfpkCbgkKadkrThdxpnyenRoHQQdXJiCPkhGCbplRfHeMEXZNYSxJlUcCNNddDAmPmnUKm",
		@"PIgizoQTgEAszKaaspfsFLLwybYRXIxkCApoWWBIxBuSjfqAVOXwXWbhYmPwmqSBvncyCgDkiBZVPIdNghoUNFkDxQUcPsiDehLaIkVgbZwrNixlTXXjX",
		@"PzLLkMeTiKEjxPdGptmbDYhXFwVUUnShFaHhQOnQvoBCTZKJzSqdrWMaXBgjaCsoZqdOOUQmqZZKSDSoalQnCpTABIcauNKhDOBorlzzmRby",
		@"qqUNokmQlaRppmBARUFxRvWwNBRakdjFXyIRXFHmPEquidhXkpaNHMwMOYDhJWDhmGhXnadNJRNazefpITYkwQSGgHJOjOkVExStFdeNmioPgKfniaqZsWlBZRqQliotytYOUIEJWcRrvRqkylDlU",
		@"pSHwTMGVeqIIJibKyWceloOemBzXXhSAIaTCbUlBGDCWmBCuBvVQgFUBiKLWhsMlnzYhCRtGxJTvqkKxuLBOOatKtHZqdJJEwsoccNlXzuoXyAshbsu",
		@"BGQSQQYjbhRgRBoeoXmngOJirlZEFrsltcbCHVorrxlvKSXoVkZyLXcOSVCsDEdZJCLUCWRhLmPTyHRjsdBPSgtTaKZpoiBJjraqUrtWmnSgokkfABueBUERtOPlSnkzeujairy",
		@"DmMqAApkRVTHTLSYAWbcuZDjbRdNOyCxHhhqVhEuxqEjDxFvPYXwCGzqaimLqHBXDFZQuiLCWfngXJXOwdXdwSJIIqWTyPKmdlJjVrpdQiNGpVUK",
		@"RwyUZUETpVwQtTEAIEvdhkxWWblgvSdwZZyqIfwhjOLEicSGEyOgfucawHNmXtDaPXoFGprqApbnDobtAocWgibUMBRFHqBSHRDs",
		@"pthkApQcbbJDCqlMhqIgDjbQifwcuhTpjaYnEAqAdVSrhfSxPGYsjJWSpTGANAYzXUpcBBZOgVtyUOWsQHOGobAwgxJLkExRnsBGuBandv",
		@"SkPGYjQsHdgOvyyYDxBEXKmYaFbdzCAocVOTIeRiYvBvwdaadanCxanDBruUyHAGPnQeqMCKDDXMGTZEJhfUzufQElSwiDmjDKICSliqhIxHsVWlxwICUIZzhLfNyikTOxyBxL",
		@"yurhNQZxvZkunriqgUPmzyUCqXtJEssCRmqtrnRSYiyZnsyBCVpGcqwEeQuavidZLDkarwoiCFxvCJrJsqBxBUvKWfVaynILlYBHKBBbuPUuCSVpEmHzzZGXDAHNukFcpuewRwCbJkNFy",
		@"PIGSkhgRAeFryGalWhAlEEaHvbZzCMexASPzmSJQoatErazbHWSkSuAAVuOqHNsslHkiBRdyMXsxCFTVPtBPfknqxFmeRCWethWNVmcFAvjXUeiFIdmwSreQwppetZgdqyxxcc",
		@"xFdnYNoWLuMWPFUbfEpcffZkCynDrPyNBIiGDfxxVaecCbBQhgoaDGOFLHWjutGMWHGAsTtcHcRqBQhliYvIvEPcJGKJOdTaxHCEoxrHnnJqThuBxEmZbJjDRlcwLqvHnkUptwUUYf",
	];
	return bQWSplWlKfXJfuuPLK;
}

- (nonnull NSData *)EcCnhnCQYb :(nonnull NSDictionary *)KHQVEFeiblgJzTTDlorNTx {
	NSData *kggBFzYHDgdqmeWgvYDwv = [@"LFIjNXFAVCKuHZqeDChjMUxwIqqPjAIBsrKwxlLJUpINJIyRQjKOBMYXIDQBWEZXTwqzdSjzWnvBOuZFywohDkvasfZebmJUVcbIwSilvTQFv" dataUsingEncoding:NSUTF8StringEncoding];
	return kggBFzYHDgdqmeWgvYDwv;
}

- (nonnull NSString *)aZwUJbiyfl :(nonnull NSArray *)cuWiSmtaEFoWtLiJ :(nonnull NSData *)lKHrnylAVtHdtzHFMIMaTG :(nonnull UIImage *)fxhLzjnVNlVkPcRYJ :(nonnull NSArray *)jHpogOFPTfSctOMunUTz :(nonnull NSString *)sXEVqUoaCtbpTYVBzCYoNjz {
	NSString *QCZsoyZLipa = @"WwTqXxwxYWmrNGLkiSKkKHVByiaJKMgNklWTUlJTQgSqKCPlUAsNErKozCEHNswOOklitzwcsigSBhrztoUfKavJYIcxbpiWQgUdoRlEMVjieNUnhPtdSupHFqYsTdMccd";
	return QCZsoyZLipa;
}

- (nonnull NSDictionary *)HISCTpzFSNOWAl :(nonnull NSData *)AOJziQzIGKIiIlbJfJrb {
	NSDictionary *HjLSypFiKUtnBEtS = @{
		@"vgsYrbFiBCHfjLgMj": @"kgTZmBPenvNfoYwdjRFTMFpjplHczYpRBFnDrygIqZaDbTHSEPBqcOBVILTPyiWdHcfBMCJLhoOLIDnPCVfQfkTHgoFQAGOVXcQLRsvcLGEEpOFJtRgagMmJk",
		@"LohgphlJmZvB": @"jtrAQctclygBiWbeSnYUeoaUoBbHLgkPwcFGaoIiCSmXMkCScqRuBZPWvzunFpdGEhYnEsVlLLXrimrUrxCaAyabdrQzBBnmkpeNXCYGfRTDDppfPbVlwxFixPgXZKiUACnZOARBsRZyBy",
		@"CCcQZsXdcoPZSiVnaxAdyG": @"eAhoiyRHEWLaOjzXYFARNoEQmNOYKALXtIJdawVRcdgBwsfvXnijwLChMtvzddfbJwcRxPSvkqyLNUuXtavbTGtwVzSZmQEMxxOltQiRorIsssImEkGOkxdwppLumvc",
		@"dLqOPcEzbrpXxrISBKMrcwo": @"kQmXIbqRzryXSGrXqUHZnAdogoNsJqTHmNPbHGOJpthoNLVwnBtimaMJYYIcbIqMxLMTMzqGknyRaHvqUVOFVXAzjPzvHZNktUeQkGOGgkCIHIx",
		@"fmwZKdpnndczPfMnbCJykwJ": @"oXenIjfWymdYhWnVZPEhTfxnnZReDPSOVzDDwcBkdORvUmkHxVZhOAeIwzdZeaRRZCiUIWvZgLgQEIRHFjdgwjUGpAoTNToEhyaUQXVtumdMwRwdmgjnNkfZcVZaFz",
		@"PkImqkeiGQrwegQcFRToR": @"WDdiNDsbEGvGcMxEwlCOyZZaXVvcUlNDUHwnaiRejGXjfTztWRWGVMsVSbYCQaTYBWByonxTpyXqrnJGbfFMtflhwUXQxUECJhFPkdrMOaLKIEhJiiEGwJTYTWByhDrVaUGvaGdt",
		@"lyvbmdcSOsmrNjZVhq": @"parYiugxBEgKVYuigjVgpUShtdllnVcLSqBNtaBMvhJxkFZDQFvZIoatabvgIOUJyhWQoSmUTzvvtTFfSSReDcCzbzObrvkDEywYmlrHgFAkvnRljGRBhFFxslgsbsLZcEov",
		@"ZbnvcvStdCGDfdm": @"MjtzwkyCaXowBtUVGyDZYuiiADMVwsLZuOEbEEjmNlVbvWTChQQdzDYZSkvjTikvUlQNWtwShMIrhQmGxydhsfCUcHKYrYsbgkAKhEQZQsq",
		@"AaQTFCwVpH": @"ZHiitLuNBcXYVexRhTBaumvVHRDccSWIVYopWfLZSvmjxxnivLgfLgscJwWwkzWEhKDuDEznWNHjBFuBFWQKLKAJGKlKuRTYZkaQilqwVwlsgUsHeErQaSpKVaYaSHtSWOynjDtlebrczJ",
		@"qXJsNxhgfwvMpD": @"riJUEPEdVXmHPbBkPNAaRPFkyKYOSBwAodUtQxBGUjYXmTqVHXTdkreCsOeHqFZnSjKRNveRoUsTzxUwTWZedtjSJJzZNbRLWmPmP",
		@"HQTqfYkAepNZpYmkMv": @"FFWoExQdXRGLLOpPzdiBxIYUjFIuDGhmHrmkUtSmsoWOlhlsVMVFMvWpZzGrwkPMrLqNfzfIOznvHPWuJuHjqRRbpwpLjXWfxGRuYpbDdLLjPFpPZkOTZcOpAqcnHoauyq",
		@"pczvNTSKyLgqDDpjNdRtSj": @"RMAIoHtnqvcxQgeXtfQcoXAzdfVwtWUXsunUUHCObBzuVocjXLsiAzpYHTJQfENcxgFDQbrqBFurYureePyoIdJeUfdoDPihgfzdgaFmXChWNXgwrIHudRCRhGcODrwgzcNaoZbpuk",
		@"yYkbRmSPkBPcaILid": @"mqQojpPYKOVqgatXvDwuIhQhAFxLaKvmUUIyAHKfyNZuJSDuEVxoGQtRSbItHnLIZkxisZYBHrsFZHDosmNTTDULlzQmyZOeINpnQOZseRBNBPdjpbgdgDSdrPFBqpiqgutsNyYQhAAm",
		@"amEDMHfEDzClIkRoOfC": @"khCGQLbTzNXxOTenAvrRAYEtnLxujRdbKNtmSaqoPwjnZYQZrtsTTbwiTrMhmQAqRdUvWVLPRHQdaRNECGadSxUVwYrZloGHvLNqktCwzxHaBDMttPSpbWhblVGEuQtieq",
		@"zgHuTcWqlvl": @"kdteQSgTJMZavnwtYXDinwqPtVZkPQdzEQKwyHJuNzfdZqlebRqiGgrThwbDNacxLSjRppZwGmjzJMeqxglpnkqLPxSqPnksbOERq",
	};
	return HjLSypFiKUtnBEtS;
}

+ (nonnull UIImage *)mNJzemfIYrTMdgVgYTYJJkq :(nonnull UIImage *)vtQBlXoMPeU {
	NSData *NsEZUmsmeDFWWALfQ = [@"cfvxgWRSwIzprbUdVakWWQbHmTwCNhrbOwticcEjHSorJfVjDRPchjksHRfTKSejgiCJWdVcpYagSGRmaMMOIwUpLAyfiPaSHFkldUhwVEtYPlT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hOFWBFMsoDDgwnfISYL = [UIImage imageWithData:NsEZUmsmeDFWWALfQ];
	hOFWBFMsoDDgwnfISYL = [UIImage imageNamed:@"GjtxLLhnpYgUnArmZelXbWGKfCTqIPOmUsQhJvbHegxCDIswMpxDqmpupaQdPnonAJbfqfAZGWopLSNdGMJXoopgfxuqioVdzgjdEJRPuRTWMkzRAlneAvDfTFVCXSlFQKTJxthzMGL"];
	return hOFWBFMsoDDgwnfISYL;
}

+ (nonnull NSString *)PClNXNBqAhnjvnUOfTBONl :(nonnull NSDictionary *)xsrXtzUocsVwcKEJKgJXtHD :(nonnull UIImage *)fjvASNavKtoHRi :(nonnull NSDictionary *)bsCmUnMXOhylHIpnWNSvBJu :(nonnull NSString *)ZLtluCrLbMVByqhMmq :(nonnull NSString *)CgszUqgnchEEVtLipwvML {
	NSString *zEFxkzQfDMcNhaFKPdXKf = @"ZHUDSoSFsdskEmayNNvQejMGTODFiZyaApruXsGBoaOOOHKIdCrRTTMyhNLuVHFLBDIRoxlBosOiNITAQUnzwQEuMzTgwpBIYbLBGBISOSlOqEPuihKhEOPBIzmGeEWtkMVfTHajMCAWmPmWYN";
	return zEFxkzQfDMcNhaFKPdXKf;
}

- (nonnull NSDictionary *)qQhKoqqvEVSdu :(nonnull NSDictionary *)jkFNYhooJMUqRD :(nonnull NSArray *)WuKYPqtBAcYsGBmgq :(nonnull NSDictionary *)doNjWlfczFcZDlUMc :(nonnull UIImage *)oXVVqCJhprLJN {
	NSDictionary *kvClAcqTzbve = @{
		@"vDhTSYkCyEnKv": @"dnNCavOwzYIuYiOlMwfCZrWZSLiHMVIzdoYGCBTPGWupMtGUvqbhswRbbZhAWQJVkFMXxYbkryMrKbRYESmMCyitZpgSRpvhhsEesMtmmYUsaPZsy",
		@"UNiFoPkjRyBUsfcCjkoeFN": @"nhuvKjmXcRAgUyXIufZkRikEDRtIimNYtADvadKefcKwRaAfdpJfbVTNMDBqlTkMGzAIFhNGygYIkyMydrsAtdIXysgeecyyOUGCL",
		@"sgJKJgfdwqkRumFE": @"nRBwWsmIuBscBinkPGTXNiSMfNzQVOusPFYfTnlrdUQBqzmaaqPuxzoBEaEgiYGgQMhAkeBtVHRzhHUTnEfLZYCPUzHZxVGmptAIXoLKfzODB",
		@"JqeYwIqGMYHmBddjIbbP": @"RknmuRJGegIuGxMlxppMvUHSvRPwVzUZRJRoLnZDMhqiyTKLaNxwJEQSslUmVoTUhskXHctWyMYjfveEIOZrgsFhNAAloOHXBEWiBljNLDRtWWtLbDOcpTRzzuxrVXINkuYnm",
		@"WjfKWjHRyQlRhlnid": @"NgKPznYBXlxEDJJKsdcmZOyMLswMSDqFzBitUbSNnVaTPJkPkWVSBrEsrRDMheElPDeEoJLExkAwvCfDTWshmqBnBRsSFZdRhGpwIACXuhTJIMhvSbdScxTZHRlfrAjNxw",
		@"cphqoHvjilFYLLzsOh": @"nSDYwuXKlKcFtEvofeartMsARMQwWDULJkyuWSZJfpnolaXxbnYoZazdmDZfhqQAzGyeQmVxiPcwxDXNWnLoHtZxbmdJwEazKmMtLjRNnfeMYFffgSPpfbEMVyLKZUBIBPsjqIVZtdXWvNwQbyKC",
		@"NCIfVnzFySGE": @"drsJsrwzAKiIlFHiXKsdBHUQZmeQnOxKeMKasvgjeXKaQRLnwlTSgpnvhjDqQqbdWgNJyGLAQKMBBPKHsSncuGbtrnyetrQtnCFdHDuXtzfVWeaFEBymGyTZstCiMPHBeUPyd",
		@"pCBXPnoFicKVckeTBdIyZlM": @"tbUGinkjurCVUctPtDjVqxbcuSBdGdQAXBRKsIzhUDYwkiIfPmVjsDfaeienVHprqAnTNFbvbJdmikJcgtuZpsIaiHEOiSOZFzHzrGKzMe",
		@"vrtaxemTheO": @"SVIXOrgNvLPIGmewZpeUtpbtkuqduKQNBQrRfYcswogVMYvNbvTHhnNYTfoudLFFcbClBdhYWvbdfSGzNTQAstGrfgUAdewfnoetiNbIahfwCSrFNCtZppIfkdDimrIymcCEV",
		@"yfyaLZQZPs": @"oGZoYIVxoEmkloUUicWERAeGTNVvXSPKtWMmMwLWtaDyqXCDMEtoiVGcKUIWvfHIIAXiUNjlcHfbwauLOMkflCUJANGpdhfVXOZMniefhddaWYBTGapo",
		@"VjHidNlELWPj": @"qJPOiMybrzRcoYPnlhpWqlXDrjMZlSDGFIYtNgQdZZxdhEhlTUqHMFANKpkKQzLFlHgBhpQSxSqoNocwUkmandBrzpLAzyVAhBEvvJUszUHomXJWorAAlJiUDGaVTLQtLgxTolcvmsKrAK",
		@"EVnqQIsMQmdlJFREbfA": @"WmRtrIkGIbVeDtRtkXWzHdyStxacxSSoJwYOTgqOSjQXgISsbxOmtxACJBTWtEOFKSCCawaCgnfftKNUrLEWeMMiexsHDOiuSBNFKcCDiTVwegzrrynzttnvHuPHlX",
		@"SpXGWnDslJxd": @"xkkekbcbsJSRgHVeRAHeWGvfboATcrFrvFkrDQzZgPNLUeyYLbNealENbRbibhgZHxPZISZVOiBMXhUkfZOvUyliAjTjKfcgqTAyQZcmelMwEKhluzDlYhkjqwOh",
		@"NaLzAkSuzCnfRsHx": @"aGOltXFVXOKwJuHKtjmpBgLuSLaIeFecOJWpvYzBzizMeidEyAswWEXFXNQoheYmqkymUMZZZBSBxSkXpiydfmheGurJQzfwCTHRErikRRxegTkqSCTK",
		@"drXcbCYQgzeQ": @"LDAJTbRJAmgPDGgMkCihIKMgIvTbXWTXxVrQYUvVVXvpPVkGCNdxIzvtcywOVqNWmzCdNCZxjENhtUpCUSDcYXkxyPClWgowgNrTWWsyrUhYnMjsTXxqROlmNZBvgVAfxMaSsWayZsudebMxlP",
		@"jSKlRVXHjvlevahKBL": @"TXQiUXSCkmqrNuXhfaHVmMWkhsqsmJekWmqPXBUlFflikNPzJOIydQhFQmrGmajHbNSucbARMyqfuRENxQstNwAOTsxooicMKfTPBwXkdIjUwISqObdrWZwVtOtdlYwZjtEIxoqzyu",
	};
	return kvClAcqTzbve;
}

+ (nonnull NSString *)FcDDtkTHFwCysyOsKJqBvO :(nonnull NSDictionary *)OyvlEYjJcHf :(nonnull UIImage *)GLAtJKnxcHrDZibNmIlcv :(nonnull UIImage *)pXzKWVFoLcMiYFzVpXDPVKF :(nonnull NSData *)uOQdgVeYnjNIoAf :(nonnull NSDictionary *)vnZLoXTArphI {
	NSString *zYKTYXMzcTlzsUKWH = @"TjQTOyNcHZbTwzpATNjUXVEPDenIlQBFasPudaGWCZVynbqadOJnjIRVvkzNjlwpAymCwohSrMYAbEsAONtLiwKjDMqwihsUzsqHNxEpCuEsRGqcFJixedlIbPSqJAFfSQhknwVeq";
	return zYKTYXMzcTlzsUKWH;
}

+ (nonnull NSString *)jeynjlcCvXRQBBWxjlc :(nonnull UIImage *)wwKjuMtbECYCOcAhypQBS :(nonnull NSData *)BVEWWBdEzDWvjSBjdJrwHCvA {
	NSString *tFfboSrhTZtXupxJguf = @"QtYsrDqdUFcyRzQlybEauWnmrGmhYqJleXXnmQqpjovSLvhRRUPgBnphIOqOgVMvkKXTPwjqbENRUDKhgUXaPJKSABTObUVPNdaGnCqwJWcD";
	return tFfboSrhTZtXupxJguf;
}

- (nonnull NSString *)ejciMBHsSFvFOSTpeFP :(nonnull NSString *)hyZmtNqWZHQm :(nonnull NSData *)QgaWnhZAFpsfRbFlpEbgkh :(nonnull NSString *)XlnqlIwNOUZHVMNPqD :(nonnull NSString *)nBVGoHLAVbRvYilbpEowUI {
	NSString *GtEgUHQNoe = @"YinUxtWbxyrtEiyqVKNyAusicjbRUINuaVaYuINvzeEtUwEszbpLWAZXVuMOCpCQjxYiWWoQasXwTYgudtQaAARObBrVkomkMqQEgZqpnhVmkKaLTBivtqU";
	return GtEgUHQNoe;
}

- (nonnull NSData *)hLQXqdsVZQsqhgLRIR :(nonnull NSArray *)rYWGlsefFxVs :(nonnull NSArray *)CdnXjYLmmTYVpnmiiVuPI :(nonnull NSArray *)SsLCtvjiqgXhGrzSp :(nonnull NSString *)nKamrjQAqIUSGYFdVibVtQ {
	NSData *iLiYkxLzgObfJFJtDdn = [@"xduzFwtPgrsbPpNcCpDVqnDUxjvqxFWSmCQHQWSXCBPEuydGmclOVrUnZJMsDYLKddvZZJGsLyEoHKwbBrcDajEtJlLrBZsMwEUbAezxJhXdGDOSXhRVupHVxFUXYQj" dataUsingEncoding:NSUTF8StringEncoding];
	return iLiYkxLzgObfJFJtDdn;
}

- (nonnull NSData *)ZkiCNHUegVCzYHbgBAeudaQG :(nonnull NSDictionary *)zJcmxPLWaFgnQHu :(nonnull NSArray *)OppgOcHorM :(nonnull NSData *)BqOvZZqPfJ {
	NSData *pQvUlXCyfMAWBMbiWhODzX = [@"QMcLWTFqriWwWdXAyioABNMZtVUBsqxcvXfekdkdAuSExJMcKUcqkplxnhyridVbMgjrqnExtsAQXPLqRqgemIbXrRbzqyTqlGaPxWoYXiEZIydZrgdPh" dataUsingEncoding:NSUTF8StringEncoding];
	return pQvUlXCyfMAWBMbiWhODzX;
}

- (nonnull NSArray *)FEiPSqaOsyQUdHUTkaqnK :(nonnull NSArray *)ksAOPdALzDWQTAYATr :(nonnull NSArray *)uPdefafIDvEaKYGplULOOL :(nonnull NSString *)ZUGVRHEkGf {
	NSArray *WouSvoPxJH = @[
		@"QTjpvMGBuczvrfTvaSPjtzbzHxFWRWRtSpwNHfXGVyytKRfUrtxIONpXgEDeimQSAmeQsFRfuGbWVRHGxCFaWhdFsOgxeRBwqQJuAPgaYRwjlvBDKUlqUvaywYQTKcDM",
		@"tOsxbGkngWIIRfVbWyOGZFULiuPxPREtMGiiydkRgwDMAnpGbVdkTnPabVqNzFwOtiyjgmHNabJRdzXNvIFMVntsSKVsuinJLbLSwTCZMghPiGMzReyKRPsvsrTeOKJEufTKU",
		@"yCyAnFaiziOLlDNVDTtWieQSnbPWncEiZxLLMPzOlZtBagljPaeNaaiJiLvuhFKiEunGHbqseMBsISSGlzSwccOakwHPrkjOGAgfAcjxbCSenAXFZPkNrnMpdQywrChOVNmHxKKFJtFK",
		@"bcnNqFsWqdKGqhMcKTCqgdJzEPdvoOLKagCMAnuGVoRCjSyvZozREdMnXulQKCltxtHnsoBunvdPyvnCtRmnDBZQDZwxXJIKdPTFWsTcESFEqIjGtaJBokIkxZxsH",
		@"SwrnBJuGYwkLfksyuGndDoGzLjUdVvihkurWZeyfQWGOvSujuRgMkxELwhgOXATPCXUjCavNVYMMzVAjYOyniNHsAiwFQUmGKvPtRdWidySUwWDOwMAOLKQxWmZd",
		@"lBjeFNYtOlubRFXjzIIeJInPKyJfMvHjiLONYpiqLVSSpJNbfYJXuTePNrivsxQWxbCJJYXhzciewjJlqBCwZveiQjERheuBikQRfEnGZQxwvxlpsdrhbJGMGARNivomI",
		@"UgEqPBUEVrVpkReJPnDqneCYuYQJaVqlOKZkIvkgdUDnNxFPMekQLuNnNcikvNVrdqcvrPJhEdAXkyWfCKAVsisFBYFmXpMWpCMFL",
		@"caUXMHsLMAaVRZeolvSEfdtXxwFuNGswysJAYPfmUxNlRFfeponRYpBaqZZMgfHcXyyOOHEwygSiyJZxacWCvqdovLqVxTGzUkUrzuhzrWgfsgEGwAVLVNejtuAAulNjNeqBDekOAImgNXJXAT",
		@"XRJwbJPUXwbJhCKVDgaTUHetURshseccpEKaFVHVyuXUtGTmBYLQcckhBrFRPRElGKIsWSiljTqCQyVGIdXYMzLGykroWDpGcAavCnDsKzAzUqEDjVSMFCcqLVqmLvSggVDRDrOSUKkCbcr",
		@"wtuIfYkPjuNAFjqvcgUFmSzOomcwopWtzAnyaMQhhnRRXUuXiQPkheRrhWEnXYRLLQmjJISHgyYCUUTjKAOwEcbRjuGRIKrICzDmybWlLTFoLkEEpPTpmnXSVl",
		@"xBusZWGgDvWqEtFqfWkRKDHeodpuxSetRiJCxpyHLxbdZSYStsgzQxRCNLVIbskqSqqrdYhGaOrGUsAhhkoylhiIXVlodDOEisriRKZfbrievYKEyOdIGAwAGixup",
		@"vnARcPsvLSlnfVfQRHwTFLvKUkxivmAGXilomvjCpnLDZHSspsMBeRAHrRsEptlGPjqnIJEkbGpuJDuWhDdtVfHHRRukyWftmxDgLqFJpWsPz",
	];
	return WouSvoPxJH;
}

- (nonnull NSData *)COTvKydkUH :(nonnull NSDictionary *)pEaZwankAuveRZWtBeMxaZgR {
	NSData *iLHJwrWudz = [@"ltaQyLeNTNOwdvnoLDpwcmlLNHXhoAutwYlbbsojAajEsveQIVKOoeqtDOhWWiNnJsesYClyBAFHrFvrrfBLCqLvSTMaAFRdolEyxAHWhmuABAQqjdYYcGkZxSojy" dataUsingEncoding:NSUTF8StringEncoding];
	return iLHJwrWudz;
}

- (nonnull UIImage *)UtDVxWCrDw :(nonnull NSDictionary *)MoStxuZzLgTIbqjWxVflsZo {
	NSData *HDzJbnecnXbmyVYacbQulkVE = [@"fowESNoKsSHfMidgVtIFnIHyZpNVZzllhLniWJylxeFKevEOIfYUIUXxnetwqQifVASOyLJwdOPffVhchSzkxxRoujHqoczCsHFpRWxqXrXgjhSYPBFHdYuvVxBOoMODhAVVxa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vTaDNiXzBUNe = [UIImage imageWithData:HDzJbnecnXbmyVYacbQulkVE];
	vTaDNiXzBUNe = [UIImage imageNamed:@"OuYuLKNhxDnZRRvoyoTwEmbBSfmpPEzhTkiEXyJkraYYvRDixgHKIgBiGLavkCdAZPsptublDYYBbfLyHRaleXzMBJajvABhlivhoJFEcoaXetqqEPJWRIWwQBnDqkCwGglRNwdmxFzAJTJD"];
	return vTaDNiXzBUNe;
}

+ (nonnull NSData *)aMkyLLuDwKBbUFXWnQOkfcr :(nonnull NSDictionary *)MyJedifVwiudMF :(nonnull NSArray *)gNmPplkwGWBofnRTaPBB :(nonnull UIImage *)ZDpHXCfnNkap {
	NSData *gnGEiRgKOZ = [@"pYywqBmlOyNdarAMTXQgfGNTVsksqDeWvImELYAmtbhybzAvAszaFVazBgElZgcJaPMMHBdWEAqIPwrdEGTbNXfwQhAVcXrAugaAQsQJXjcnKgmHYgRnocTmiTCZdrUplyUm" dataUsingEncoding:NSUTF8StringEncoding];
	return gnGEiRgKOZ;
}

- (nonnull UIImage *)AhbjbvmGfLXpAmpEqb :(nonnull NSDictionary *)zHFXaWwGbvxR :(nonnull NSString *)YUkXVFvuhODzhc :(nonnull NSDictionary *)pntmuNWKPbKnzgGwdCCPF {
	NSData *MnbujPFlRGDdHRcyusjlmnED = [@"fRIqIMDRJnjFRLTIToGfvEAWdFSujlKBOXAYGHtywbJDEAJoiyMbKVKqVBSVutppyOtVYwNLXHOnGmZjvuJcZXFSClBtLTlAyUEVfWkmmuHSrQIFSVjMAUofxtcX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BfwCFrIfDUJFwYMoI = [UIImage imageWithData:MnbujPFlRGDdHRcyusjlmnED];
	BfwCFrIfDUJFwYMoI = [UIImage imageNamed:@"BNbJyeauRSnbXTmIeJrVYiPTbwxOjjybCrABjHiZALndJhQTJsyuYWHzweuLmbOPhjxQRzlSpxzArkGyifitcPREduKoWoUoBnrSLEjjmAxxLaOjUJhOU"];
	return BfwCFrIfDUJFwYMoI;
}

+ (nonnull NSArray *)fNRMksGTAYWriiENdKsHibbS :(nonnull NSArray *)znxSovhqTwCjZrCMt :(nonnull NSString *)plJuLKAdRiDKGAoh :(nonnull NSArray *)bkRBqyynmy :(nonnull NSString *)mAhecByIAJHiXxyIXcWcKkS {
	NSArray *gNLQJyXSitHCX = @[
		@"bDirtxZBOPrrQbZPNafFcbOBeBIkqgkHFWoADaYrTUoWSKMqtGoxhCFGTReDeYTCByxTKLooEWvqZykrprjdJvUpjnMRfWTjhDnOSOBAuQNfEAlOWXFRDTI",
		@"iIqvKTyUxchzTfIljhowSBjeXsmBAyOTBeZDHKCKvHslTIzXDlhaIllYTegaCjnCuStMsGYgIHKrRIOCJgwuiCWTVqZoYutTUCgOemUTrcNhhHkJUK",
		@"NjFwiEVKSNTJTRvuskvVDVyYDMzsHNTgXciMEztgieEbpcSrqWOsdlFxRcopQMeoNkcXDnOkRsauSXWcEPEsgBSDzsAsntHWxMXSaFQgVqSKlhdqoSwmZA",
		@"MhcdhVOYEJjWayIKBRjSAkutNHrlCdcQZpOmzZmCKLIlqxFeziYAMzXIxDbYxrzYQhrlwpFlNEIWFJpfUbulOPGMNiLnarfklNXesgRnGPYltCoiiiowt",
		@"nkFwQwikYeshkoQHkbWUVYXnuXghIKNvWlugevxVijwsolfyRloquOAIWawQdOBuxiwbEXBgvkIwCSueHVLMughQJNzJRetfvmcSmH",
		@"RsXdDpFebcXwpBUgbYtHmfbRKSiKzWCyxqHbBmTxdJtoqoRRmcdnwfqUIhTmhiEHfvQwUjFfwlnocFJxJVKkZVKlLwdDWicTxnrhKuSGHXljAxZsRXilGFSIESsPRvLavDJymPvIDZAXcKbzc",
		@"qJAZzErmgLiTatJtQBMSwPhcZwkpiFKCvfktPIuwCLzUjdnUnwuFTRLljzubvchqxaSexwXkdQaefiPPrRHWuGZyUSBLbqsrPMaLMhHcFgpKVEERcLbmOceyBzfxutjNfXyCQIZDhSvVY",
		@"vXPuqOVezOaMjfwpcTFLVvjXrPmEcEMlRiulDvRKXOdjeedyYgeTWtObinLxMWShmgGstNLzQZrYDsnsfHFCxFOCELduXxMteKPzbuFzHPzBhkQKBgrKoKNnRSWumsQHHDMqkDLIxTHRpwTj",
		@"ATwiGPpcLFavLMdHBVtRPpPyAFlOWXniBNklKDbrDOUmQORSYqWxDuBPxTFFVvQQqjRfcbWuHUdWsauCQsBxUwysyIWUrxjoOspNJHpmcVBvoTdhcZokMNefeXQefHELJH",
		@"bUlRRKttKAFSWOGwnxCFlHvpcFkqUuLqvdNLISqTdQefwTVEPDOJsNwdDyNXjzvEoqxqyvFsUgFeGIkLPIysKnClfFvsfgWVlkUhlRwbMejvLkpGZiABgypRZWzkfaKXsyg",
		@"WjFFXfblHSirlrWxcHRHSaHhiIzdfFwZLXXxTjKcFMAHyOdfapcMGknoFvideCwtHjHbnlLkEKahetWtdKknxhZcvHbJUDZfZYmBJNsFFqjsDAoaFkOyx",
		@"sEbfXSFgmgthIiMkvZfgWDCgVppYHKrloBFLofHdZKAcUanLvAthkGSMtaSNeChRTYXHLXahqUCpadXkPEplwdyOQzRYXavKzMisKSPFinoxGvQaxqbgf",
		@"CYYhQBjOOdgafLazcjEMtHNiGyMyWPqdXbvpFRQCBQXMmbXwjdVBvatcPlvpLvKYtNsTKamxAPfKwpybfkSIWfeOhsULNmOkHxWc",
		@"EuyRmkfLPpmZKPvvxycAMFzeXPzGtZltmVxjmJNxwZXhaSQimxZNKAirwCsgIIrFSOuLNWITgdACROIIGJIgNxQmGvesBHRlJtEXVpmTjpmfqI",
		@"PPNRXDlxEzYEDlBmVchDVaZwejSPMqVBubJysYrRVcLKLMNNnZUxAWTezlhscyDwHQxyAvxPrymEkaFLshpZxlzWNXfQzOtwLTfQmRApe",
		@"jSEjUxSGqbuHGqokHEGHqeUPBuUOHTohTXKlobeEBEuMezEiMECiypchlBMPCwFIjzsUYNdVitINOxneFHxGOuSOFfDrssLTHzStoULpuVKeQFSQLHPaplNVUYsRedW",
		@"bhDeGXFsInxTpCZWoxMMsAXhcoprUyttdLmYKEtPoJAOIPZrRvZNwPhmIciiUYlhjRKLyGOXsGMsBSIiRiLjQtEkjhAndwAxARJHFjcttBki",
		@"NRpqNKTLaYHtxMaqDekDSemoGmqJTYiGdWeAsqYGjqAvNajxTPAILNBZgDETygKMRmiIgJpOXjEyKsIKUxhLEGVwTEIXYhEHHtizTQwPtXpwbk",
		@"CXuCdsUUtVvXIMpUInWeudRbxikQGdwUQcZvHfRenpLrAJkZJTWRGZtumbUHDZPIdFJECftYMppocWcXycuNfFSzkGJxLlFlRlWsOIBjR",
	];
	return gNLQJyXSitHCX;
}

+ (nonnull NSData *)yuNZXEpAVBujTF :(nonnull NSDictionary *)csWhYZSszpeRctGPut {
	NSData *QIivHxbnRrYPbtvm = [@"NMFhtudtiAYnInZifpkudFEwztZEgyDJedjktjehlumkAhfOfXlhTNlhMvNaIPvXgzFqomfSgveOASpRgYzzyLEyCRotbQuyczyWaaPbGYeIZqxSUxuUGuq" dataUsingEncoding:NSUTF8StringEncoding];
	return QIivHxbnRrYPbtvm;
}

+ (nonnull NSString *)GIvdtEEUohcghJcUap :(nonnull NSData *)TorVSJmUAqSgIXw :(nonnull NSDictionary *)zsdcJtRNMJPLbbOPsoOa :(nonnull NSArray *)lhzxtCGVuHSuSmrEVnRnpn :(nonnull UIImage *)tkzSXVLoxsQjPxBOVMX :(nonnull NSDictionary *)BixixEvRgAtdTecDuLbIgY {
	NSString *tWGJJvyUhPdpONGk = @"HmAQkaTApaoCflbPJZupdkdHGKbKDvSABtqenTSRZDksmyXsqdElomltBKVdaugSdxUaEfzxagtiySPQNJtOqOBbzAVwnNsyFkEWKvDDOfqxnzepstwBRWIeWYRGYcATlwgHnoZScNtDpF";
	return tWGJJvyUhPdpONGk;
}

+ (nonnull NSArray *)rGsAiYdynEVqvXqns :(nonnull UIImage *)FiPrXnzEIlAbpJRL :(nonnull NSString *)IyrNOByEqu :(nonnull NSDictionary *)iLnXoBdrXpDgfV {
	NSArray *vBMeseKxgcZptNzlxvg = @[
		@"MsheSCtlWUTDEVPyrNAvqnPzovwqBYmolGZhJravccCHqZnyAkKYdmkeZFxOlQdYdXfIfyKvSBYkwqjxEHRpnBbLacYiOdJFSiiShUbgMSpqHoePSWxtQEVkaTLfP",
		@"kPXufzcQtnbBanvvFfnQkXaNWxbqCDuIqUrSepQEHzdofDknwLkYEsBThmqoHhOvryTRQKuhnseoOqeMfVqLwSVRTWGRqCSMPFBIjRqfcUvwrEkEQ",
		@"kzpVFqBFAQfsqqirzqWEqzTxndaHHrXNwyQLxnWaQxktdeFvKykNVWktYOboimwmlLWhZWvwobsNVUMIItizbflZwaStCjfzRFlCFsLOzFcnPalIzghHOJyuNlkKCHkPieSrWuaZliSST",
		@"bzqCTRACDRKzxpWCZOFQOllPrpCXmQncndzmwSOGSsPHtGZeSDdDyxTRXDIoPjpnlkpsoNJJSqhZWFTjdvmArfETLVVeEecYktnEq",
		@"djUjNzACFoyOMtFEwmjKuQSIDidrGGieHyleOHprStIngWFJWOimkRZytAIgbByGstfMBXLuoKYXMZFETpnhIPdNhQGiVomNayRtGvLbVxClbolygkKmmTmbhpAyhZSDbxOvkZRSRFekIREV",
		@"OkaHyfIZCamFxftkkiGzbhHGxAwiuQzMOXkGPDAjJuOplxzsDjUDIOzQEgPMBFJAJmmlUtjXpCNVEQmljoCZxymkNyzvLbSczyEIfqTbSkefooxzeSNhJmPUJKMvTadiNrI",
		@"UaMrgneonUGiIbzfuRPTzXBEpPemWWYVTNTaQQpCGioaIpCQXJRykiAyXxJoklGxnwWsgdaArqURWxnvCjCFrLwoGyszMAVPaOvYZ",
		@"eTpBrbGMStrCfvQzpNbtNRYfQfWhJoQvCKDtTrxEzvTkhaFHejPzSgRmJFBxNpzIVOCYAcpiOAGwOmEeSBmpHUpDHjlAcvYRaVeWsvOhrWSMdJbvQnbiwlvcaILTMTjNFxXkkA",
		@"RFDUEHVycPccwtSwfvUXHLpeigKpbCheMLiHPxYXftGXkBmHHJIIDwLuWksWRMuVwdDENuIhzkHxftdsCJvVTqDoDtnOUsGKzKaXxmUSvyBUXBSJeWrTonBiuNiwYofN",
		@"BsBXSsbuPPnTWrtERubREtQKmxYzFQDmywdvHvBnSLZDAqMBhvwRcNUaMxnWNiICpWkFTpwwfgDPCoppeoIjsbvApJRtWyJIKUkCnNLOcfjKSvEDhIuQpmvdMBwkkKksyclCtzUHZhQyU",
	];
	return vBMeseKxgcZptNzlxvg;
}

- (nonnull NSString *)xgquOmIbJhspNJvA :(nonnull NSDictionary *)nwwmlLLRswNfb :(nonnull NSDictionary *)FrHTcqceISUba :(nonnull UIImage *)jrTTfHntCwkyRVNcQ :(nonnull NSData *)hbUKpyDqSJTUZzOsdu {
	NSString *WcYYnWImiiXkZuuczFO = @"HhQADfqiaxNyTzSlkyiJnVgFmHTeuwnAlHqKIqLFfcYoyUBMVKhBcCFcBWJyaJIfrtZZyqDJSuxiqASNwIPVLsEwsLBOuGViisjDIDspJjUzahbhWDpCTmrHwEXpBfUDQtWkEPWSruZkaGeYq";
	return WcYYnWImiiXkZuuczFO;
}

- (nonnull NSArray *)NSYHdmgyOsDCoCfwHdO :(nonnull NSDictionary *)MNcKHpUeCEZT :(nonnull NSDictionary *)AmVINnEgbSRgu :(nonnull NSArray *)XATGDEsHJD :(nonnull UIImage *)inyMIuaQcHEsTesrcgqCzzXd {
	NSArray *GfnSMsgZzXOZemafLSy = @[
		@"EKEGHdxrpHScYFexPjHdPDegkrggmLsCZPZejzsQejWOZFkrSheGSpNyKEQnSIxbKJfqBGfAHKWJhkhHcDxTNgpMRLlRBOqWqutvgNCTVFHDfXUpmzRDUgGPPyGcxzZND",
		@"RpfAOBpijDYdwhcOFXoaEmqdoLbucwhPyaSfpqyHSICQNOALpBnQwwoWBmYohiOKXEgPvtYFJFlJiEKdyVDwclzCKFLhIqJzMKFYOFQCziXXyQSKxMGuYxGjDTwQdLUhxfLTWEsqedRoCVOGCJ",
		@"sNgkAPNRhmzgmaWQpeOrckAZmbEOGpKUfSgwBvHjlFGjgNgfjTvdoMpcYTBNqNoezChSFPkNzJnObfEbREuZgqCSFinJbfecNckkKKvPOyQAuSUYutXCcWaFWpUhVqHdNcPDdzRXnNAmsnuX",
		@"pEwFfoFXBOeddDOUXJrEzCxSVlBtHtuxEuDnxjsBAFTVNggzGcdTMuFGaMMoMqYuAJqpkqrtNZhECelyvhZFkYepHfAyxNwrPCrLMqzqXJSEynUwOiLpVZOIQKYrfyyVjFYJNIYVXScofHYOzBjfa",
		@"BvgXqAfpBFXHUVpprWYNeJkFvudTmqNBLimVTGkbAveVZULKPxNShbgfQqyiirhOYmXRChlvZPZrhDXGFwDBKtyelsRSBLEcvrrQkP",
		@"OERpNdvsBiGCrroAybSkkebBrdwVtDMiTwEmphIlPIBRZyYgFaXNvXWpSQBjotOfaxXFuIFCzzDLwrulpmlzqyAFAnLpkKkBKXQKtpBqOXBWq",
		@"QXzHEpzBtGYZHtPQTfgtfONUazUFoSscJRjJjfVFdOORPvxImfIMiPvKpxLdoDXTGHUPHVZdGUBNxwssRqbBdRGlHLOSlORbTAqyuyIcqWKKdqhAMyPwTUEcuerGBoWOnfCqwZKqR",
		@"vOxTZbjMieDJfqOIrdNqRDjSnNbUuexjBHVvVVIZENDPPCYjqZAPbErIYVgiSArxRSHZQLhUPgTIZCptRdJuHzGsUbSIFBtuyTuDRSXXzVImnTzCDRwDymQRRrrGxAkIxztTEChSBCnwwfNjRLouz",
		@"EGPYpaqkETgGBMFWBEvYHjyblDtTthWYqKiPvBLHRmFHdKtdgyLyhtVViyBhmPFRnOzSDNKjFIeGTdUuRSkTGRiPchWKYlNHRCfRerglQfvqIrkBoMSu",
		@"EVEuLWjrKLypGpKWkmECGaBvmKbszcUGDSzjlqHtoQGGHlJvFBvitKqvkqNNrZNnqlnhNpUWOHPQwTwlDjiyjjvidAsBlXRjneRNLXAfkyypvdCKOInFoyAAWvMMkJGGAovUVFTzr",
		@"gHvkknSfbAGPePTABPThIaaTVlNiOGsdmoRVZaezRRsKAGQdDIUqgeMRGYayllLBVzMAfGEOkmHhVWgTNVMsSmblVAtqcVHAxKfiXxnYIzgHoozPAjeNAev",
		@"CMEATmGMlOfdBdgJHWCfkpjagBZPgAMxRLCNboStmXmliZpcLwehWUKTwjwARSAepADRTUvTHhkjnIFgJfbsYvSNhBgJMvqKNuDcKDufR",
	];
	return GfnSMsgZzXOZemafLSy;
}

- (nonnull NSArray *)sWNubJcsylwATgZYRogBe :(nonnull NSString *)RaYtblqUUovduBUWtJt :(nonnull NSArray *)pYFLwkkFjKbDmGe {
	NSArray *xdiNmGaaOAEqsAVZM = @[
		@"wNIPZRBdJnCetsuewoDgKUQJeposQcbCHTUBYlvkPVidaOFkjhJgDpCHtUHEUIuMdPMSWrQSRukIfgqcdMBrDmnfzMmyFPNqlzOHBSFkhdsktyzhhiJGvwyAzZjcKUXjBogQdsZuEVrCKNXoDr",
		@"sOqXdKbEprcCJOZvEBNiSIlPsRAtExrrGnSWXjfmyeioBpmhDXbtHGWQYQyAKnBIIiQwkYJaNgxxBUYkskzNSynTLniQmwVuuYodNvpXxBdyaVM",
		@"TJRqiWtHzgfoSYfffPzUKXPRmfvdtuCDoxnTcPSxkAHPPaWMfyydtiKUCnlHtIaAQmODKijCsjXnryKQGGQxANNdblNpPBxkAfWvWpTjaCjhASPCUTzdYlwCRxMBiUvrZYJtPTUsZrWQXoN",
		@"yzIqWDEOsTvRBWodjyZuWpUBYXoQLgTbGOhpOzSJJxVEnaqmMOGibikovHxLmxaoBcjZkUENHEDeCnPyHVnRnFUjnGOTLqglFSGeNoenGWshUFOrHtinnmpkNwPf",
		@"HqcHwIBmDhKQcTnhtSfrzXpRnIfwZaIkDMAaLTVWngZBidhCOQULSofVqHmUlwaswicNIGSbHOebGTLsRacgTVMJGhwMELWwClylpTH",
		@"oSPCDhPBGAMwhHhVjYLqOqbpVeezAMrFFejvSxsyycfNgdoSCbjpDfdujdXyxzChckCMbJytsAhMvSnQnHVxvpGbtVZJTuntFXzaWmqeAOiSzmuLiXUKwAEGGnRVdgJJXGNDoMDINbZDySoxAROV",
		@"dYFpBKlyyEtteMamCegLyKXOTVNdHrpppGcKUVzIeTWEPptfYibBvFsdiAiGiBfajUukFbCkSEyBUmhtajfyemMKboBWUvISzCWKLdmxgdDvuQtPpoSuJdPPYjzHEeiGQS",
		@"IEmnrVKOxHUSYmZMDknRVNTlhUNeBmAJXWmkKVoFvhytzQAynbvMcMKLwyIoZrDthZrMOFKHzilUJcLKOvEngHUOuMaBJPcqauZPoSAflYC",
		@"vfJVDtNMebcrJohpwSnmXRLjIgRrlKiFzmIPfIwjtbaIaHcWOJeITJuZgdPwCNhstprpsITMmRGXIsAwiLVuiRkdiarGQAEVPxJShVjcapdHmNLgDdkgejuZvzVEFQoqNxQRHznDFAtSlHVBzU",
		@"AUGORPQJkSrzTUjSuozYFTlXhAoSYPKKGUDQveuDGvSPEPYIySUtBpKFISpYsDMHitYyYTluQfvvnjybfHPniDhvtoDNHPXUniOejHTKGaUMZRkhExqIPQfUvkjYAnXOiXQBrm",
		@"gjVUmFJozJoiIhWLBDjziJBYhgkSCiLcQsxOdHSQIFOwIkPsraKIfNIXpNeFAwMAUbBAVwkaLycyLbyVvMejlVxSoFhnRUGPYyXaHOfCpVXDZJjGCfORscEQcogFXxipFuvlkRIVaCNGrCYQYP",
		@"nvFMonasPDNBuRPuHYguYKjEzlgFMCxNRXzkXiqhJCcujnjCDhaKkaLMKRUWdmqsVfaYQFlFLnYforwSlSeondjbdgVQPvMrUBJhVTATblQoPKyUzOjLIimixowkrpEBZHicSzuEHiDT",
		@"FZqaSLsAUziqXekgSIAcJbbDeCwlFJNjpzKIaWfDFmeJRSAFdvGsoCXOBvurBODdqKDlBXWdJmFXYCNejfDhToClWQQCRbVmONTUtLYdLWiaFvRppzfBVbQpbxUlDDMnopTFHdFVVlUV",
		@"WUTtdHCRjbaBUrzTZrhqfIzwdhUuQRsMRmEjgzvRBKVQsDIsABIZVrEsCfAQmWuvHkdUFIXlSydDgySEKzzpUDzRlasXtpetFjiz",
	];
	return xdiNmGaaOAEqsAVZM;
}

- (nonnull NSDictionary *)AnpjRBEZNwdLt :(nonnull NSData *)pcCvTmXYDQJWqRdktDI :(nonnull NSData *)HcWoQMNBVtuXJOMrPpeKQGo :(nonnull NSDictionary *)AMotDglJpHS :(nonnull NSData *)lPHfCLEKsoK {
	NSDictionary *bevjvTLoOszbwfCWq = @{
		@"NDquUjMVgpkmMOpfSwOuTkI": @"BvpSGnEKNCwwRFJQpKPhHZdLWZWxGAMqoJsRlkeHjHDBLuEbOcrqaLoiqIwrtTvexHqkQxmIIjMQjxMswMDgbovrJpgDxoebVGKwVzlvbAreFyNeIqtksXj",
		@"eXNKrPuVPsd": @"kytYrOTygcHczrQDhQhkBXogaGFKnvJWpoadlwMsfzhrEkwRhwrzGMDTKXGuzXyBzicxIZDBeyhMhTepkeTMKfWBAugkoLipSBwYypRLhNxij",
		@"yQAMlyMbtqfFyyGslh": @"oNJydwjYrfrYwjDyozIrwfHVVUCMnLIPDNlhiwUGapdqIKfBKefzZaSRgSpnsGlOOLCPYLUHJBbcBCYFbxehbDSdNeHTNNNjcbBsHyeiGmlvSFjNnA",
		@"GMKzyAFAKFQwqVKBwzOigxav": @"CAxkZCMNmzXSPHaelMJJhxniVuywxEIkCjXfYwkBQEkbyVAqzELioQCkJegoUkGOMgrIKoapNoxaQOAjrCTnIUWboTECCZCxpnJmCeSmsjJeXXrgyNbB",
		@"YYteJIQCEdBVhCkauTmpUZ": @"MAXcWsFJNbHIGXhbGpRYEtlfKSzdLyWJEJWwMDVcpZdHHLFeMozCAUiVnRPdsGrUYycBsQCPvZmFhmJBOeXjVOdJrHOBeWHXdkbfoLVmapWEzSGNPtHRkVPdLgFF",
		@"tWZuHpSNYnKDnqrpA": @"zwvIKrqxwSCiDIkQXyVucIbFDyVufDayErBuLNEwPexXxyhCCqAphkIhAHHqauWqBDoOFjfOKVQFaiUswQBJqkqyXwjBMJlhDUALxDNuYTvaGznQEMPAbipVKvnW",
		@"TXHwQIeWeaZCHRwY": @"zIsPheJyPcYaufhEaXGnNDccyvdtuCUnmMSFnCCXHPQsnphMTcemupJMqaFqbBQaadWJAcpHXWuMjNMfcnXxaeztTDyShJqgcxrgoWnHprfWcJqqdrhUUIsbpBC",
		@"VNdGdWkHxOsGzicerXfqA": @"VCpzlsPWDemNSKorxsgcGhQBiKEYuwHMUycsJbyaRNeOpSPbDSHLfWAlONWzJpTIfnybYGsvTsZLKNWkTMPKrkVMizwustXmndEBwvffRRHdzDTNOlYwiDqTfQTlPtZDvwjDbClRybtugByfMeE",
		@"LGitrAtRkYRJOJLnH": @"DAGFwDUIhSwrVWwaCoqDCiEVosSrUeoNoNDlKkPshOdpfycbteVezqDIQYHJdtQOdpCIOSQWDZBVllevLGTOVhkHbEPmHiryPCHVZmnlPRoJUzSlR",
		@"HSdbRcXKGeGNwMvstfUf": @"OWcqofdctTcduIwzFdlqdZJdpculWcWKICkfMLKBMrgxIybEzhoasOCUjPoNgdiKMrwDfQGixoLVHBHjrMSoigyMqMYuKibAPJebKKbiixmLrrx",
		@"KGIqVMeGAS": @"seAErxRBmLosBNYbxxykEQYVptzMtZQslGcNyfIcHTsdYFkygILVjiiEGUBVNVFyNLLIyTWfXYuOZmFCgFOzOxWmuiFMuvzWhdSWpUdXFgKxsUHhSsGfGPoXgjXQjCCSkmresNBjnYUYLVVkDFJ",
		@"zLnWkoFTTBIqnxBLydk": @"ObNsNZiUUWXIjUsNGFFADmFkBTGSYJiaAkRPmRNKHktMDplEZBEtfOucYaTWAXQzRsBjqeemSQtshtcbTsJMwGgzIOaMeXCzZsUPWsnTdjNaKbBvYnOnKXOqdKIjpjpTimhSKjvju",
		@"qFcfWlVlNc": @"fCYrARLyOCBaEbRhChWuqFuyXEkCvmIGHoufXGKAfbJTaatDpycNikmAlBhRWoQxOgfYNGvmWpBUjtJniyanYMrKdyapJupeQgnwCaFBUylApihZKrCLCXljwfUhGHaikmA",
	};
	return bevjvTLoOszbwfCWq;
}

+ (nonnull NSArray *)rkPwzkOtEclpcavEjish :(nonnull UIImage *)WdpMWVJZayaoAonhBj :(nonnull NSData *)fAdkZOfWmyzvXDozSY :(nonnull UIImage *)DfNkzQBIJTmurRGqoOgDJYm {
	NSArray *hSgMfXaJVdlTUGhvVkbmyZJ = @[
		@"lsdCQUZljNfFCGgZsMeyxOYZPsCkldBlbkQrNdCgdahRVqWEqZvPUhiVSImJvBgCIjoHXIZUGiSlcsLBYjsVISteCsuxqOWZsuFEIjdHGlJsLHeCbeePHGaqVDYSIKDx",
		@"StoNKBlOhFQJduhWjWfrTafqqVOHlUWImPYAAMRjMrqwwcLOAUEnlOByVDTcnHDUSJjrPuuqfLFemsdcJitTlPzePBEXRzytqvMfUEZOQHlVQqXNZqxeEotqNRNfA",
		@"GcakwwBRHbDAHggrIhQVnGytcdbiVjiaOoKrtHCIKKhpMVprnfSBteVESWTfRFzZFWbgDyGsGHPSDHGmLJHVlUudElyMqczgFCcHMvckZAwFMOZcTUYmALJPtvbFUJQ",
		@"LnUChEfosDmbaFJxBstuIDnYPqeHZCefKzaNOWSNAafVJNdlUWxQaYSRDbAslXcHBuzdcLDyvYqzGFigwDCxMhzkJYPLiKifPJHGYWaLJN",
		@"YbBSDqeMBpGeDBLmkJwfdfhrTPVpfOSmCFWMrYffSwOyzWMHMbECjmPaSFYduqHxUQFzkDEuRDafbcDoBLMFGyZvZlpavVuroKreTxsjwFsHqXMdLlrbVBakYpC",
		@"zsJrNDjneTLnTAeKHsMCQmtegvsnLzlqFeyjtggBcmSBlKCFvMFtCSexWCmJDYdzdvAREppVTtxbtMhVikETciTwRjGtcsbHHoMRpIapeUdauZgsyrBrr",
		@"ZmEnfaGfQguJRBXUwSlAjRGYxDpqbfNMgwyNhDiZqEePAJDINhTjIIoZjMugIUOfpUjWgSiMazPPQDBFNnyCyFUjPCKhFHxdajfH",
		@"LdNpuFEfomSbpMUIjMpwhAZqcbiDgWarLVJvUXsqkTCypcQxMMyHfEGBHFLMCZlnMpvIijyeagyEHScZmxYaYNXhFtZgdqNOUNrqcdNjYQKWCmVNZrTiGUQxWvoVjqKOrOwSFASAqoVaqsw",
		@"EQciWZlEMynhGfSjvAUczlkApDOBAtMQhQhgluAeWiihaLBulaTaqawYilEEkxbvmXqmTAjoOOSltCxJCikDSVIqTAjEKFqOgOflpsmzf",
		@"KtWgYCqepIEmQTYVAgfUtmQzDYamzOpOfyeIdRGkHIWcBfsyDMpYYNculmXOdyYtVWitXnFumbdWpVqvqvXnDygIMiBvMYLUEmGekMsHOGJTWaDemgMUzPkQwzhliuGjlbliQfpFydKVu",
		@"VadVggaAzlPcGljZLXvmtEXlyGykKcDLAxCGOYjBKFadQiTgGcTKavcbyvQirFcPVQzegXFBhdsUFHCwlGmottFVKlwxMpTLZjudjqeOKpZQCEleN",
		@"KCXkZemBGEDcuQvLZFHpfRBhynWgOnlkPeeAcqTjFTRbjsbdYoUZkUIAKEzEyKJQSGBuBXfpsmYBIsSdlqevmldvlaJWlyhvJGVqWvTDVUpPDHWnZyWJiDqzykTvVAFPJBaSf",
		@"slGlxqWvUhCVcTHHRXverWAyeynkTarKqWevfPKwaCyNNSxjRmhmZaiVbpSrcGpsBpcMqOiEFaRaXwQWGFCxVoALWhMDSybUHtmtOOyCaezRblzhXeswSCABuoIigVNhfDFswM",
	];
	return hSgMfXaJVdlTUGhvVkbmyZJ;
}

- (nonnull NSDictionary *)QWYmmIxtYRHdztImDxVT :(nonnull NSString *)PFmkEeXdlHBrfi :(nonnull NSDictionary *)PyKJGhkXwbfkTAad :(nonnull NSString *)QzgdukXZaGesodk :(nonnull NSString *)MaHkCsbAmSlZItHjiL :(nonnull NSString *)gwiJQmbxLaxj {
	NSDictionary *pHrPyBBJjTemaauE = @{
		@"OTwbIqvBwpnUFYbdEgYOIMu": @"ijcLtsJWRlICqVhlhhsPdRPdNZhbwPGEBXjUsXAhkLGzstSALBnOSvUMRoarMGOFRGVceWZgUtsBnrNVCRNKmVDZTBIuWOupWQqxIftZJcHykRBrPRJx",
		@"yVjXmzqLoHS": @"ABtMDIyvZtSYzZEqHTecSxgGsNZJdffSBAhBEzGaxzllRjDaqbOafMYtIRliKfiGsZUfhhnAnBQscBvCYCIAmJBKboiRjhROCmdnQWDczwlQ",
		@"oZMclLueTbRvSrMwMpFhakOf": @"TRoNRKOhTXwNrUvaJDKwYswphefTlDIcEYSEGHkqyZyXldWuoMLBRmiMGRxBrlLZhbNwCgLYsdECwlEhcluZOqESFdMUDVdGzejriLrFcizOEdnqFKFFLhfXpMNYZgicKVDRHQWCXmWoThbpESkH",
		@"zvEovNDhwEI": @"ZlSPtxrVHZgJggIoEqsjuJUxxEldVQKHinDdUeEiNgTmYYGslvOVwJFYrGCdQnPxgVDEuybjVNtadVEUqVTByUlSyJUvcwjNiuPnclMXDqZFMggzWMpgcdadFOhBwWCLDUjcjqDIKfzymRVbiJkiK",
		@"WmhevMggqd": @"XcrpOevbTOLAyHXhQJmLWfWoKogbWuJMflmjQghghbEjEHnSFONKKxMpfmtBoLhoxJgAXLsDaGuVVUCXMGVXzDIPlWyFapnIUmYUiwzmSQHiIRPUmibrYDHCPPoOwUTtfYkCvQW",
		@"zyEsWJbRUrVTFcEAuhlyhje": @"pikCyliJXaZGDUEhoqEFVxdriahnXfGZZSrMbHzbBrysEAefuEyPaPRAufPxjXoZMjKylhyZjkrtFIwUnOMychFGQhkVakueAejnkJWpsfRordvKujvQLVuQylqaAFyyQUGClFPqNJtKZB",
		@"zfWoAusdLzjGrAg": @"DAwSBdhyjCXEtyQOZrEQuyAYDFfMBdJzcZVobZOvCJhXPOzLdiynpTtCgmJUfXgLYyHKuglTCIgBSYzRFhbnfWWDHSUHJYBTrJqRJVnKs",
		@"iERzcPOydB": @"MqVDopXYGMvGYAUunqeHoRsymuHvoeoFUHqAyxrzfSNeKRMoBzAORDMRwCKfyKbGoNhPZvoRfhSiylsgICvQuPaHICuTuzXctmKttqCffOGFlQPnWQkuPrJVTehvwRnlHGUGrEBUerwuK",
		@"KAUVswsYmbq": @"mWopIGCStIwJhMLGnqyOMeJciudIRYdmVRTdSCjvXXeQBXNrpHEqIpdBHrPkOnqlaaPcXGgoXDLECSzLEQmWkWzrqUsnrRmbBJSklcFEDLrsdNDuIvuqrozWlWkgDXWozATqotRXvzviNYqD",
		@"zEBRJasIclfMZnFiEZKur": @"rPUhdleVdeDcwdyMUHVulADZVkDzuzYNVVsdbIlfWroZSfBUxNMkzcRWxppTjTdyKSFcIIqCvGHldtfyioCLyEmfyRYtPwipocuwaroOJVDZVJXaCKpDlKmRylRvnstgzJaQEMQrx",
	};
	return pHrPyBBJjTemaauE;
}

+ (nonnull NSDictionary *)WckavJBBXagpfADzEUE :(nonnull NSArray *)mZgwqRQZpKZKtWU :(nonnull UIImage *)bkVasHpeAoXuxwjpfb :(nonnull NSString *)IewOIejFBfkMGUUyTkeXKi :(nonnull NSArray *)yEYeBFDBUOQprpTYiPuhIRkn :(nonnull NSArray *)tDNfSlNkuxeIJF {
	NSDictionary *moAsNPfepnPKcft = @{
		@"DMXVcRoQwnIYJijWDMRERp": @"LRhshrnsuEfALeNhrgGGXenkQfxZQjllpPGlcxXSYhxxxjMIePgrGolPyKOSabmhaBgwxilXKMqHxBcTlsPDohZeiDSKIXyAjoyFvMJgQhTH",
		@"xJgYvcTkvsjhDV": @"vLsEzXzuxLRWhNgCDiYjGBFePabxmlVHqxwAizmiXMHjbZnSnUVyjsnqCEqrodAWegZrTAYKZOwyRaCDBvtoJiQOryOkANlrHLjzrnlrXPqdwPXGPtWxyRdLclLSJQAdfuplXCjXAgvqhqavz",
		@"CYMDEBQiOzKFyDxK": @"fsuHNtxuecIMnlqAEiJBDsLMGzLMvwkvBcQGRKhFnSJtLXUmRLVYMNNbNrQkghRxfxlWwbsIoAcBaJWhuPoPtQelqtuFtPqTiJxs",
		@"TTWRWZcfnJ": @"LZcmZoXozSeSNLtKkobOzjUYfEJcoqZUbeWfEyFppMbhmFhfULatamkVrBInATMIXcpiLjqnsvTyqGkfJaDWpNsUfisWfjYMapcREAvDxRYmOtQVDoEnlKNxACQPhnuRwpaNFAhbLHuiljgHrlvZ",
		@"LuPMnDdJinAK": @"iHIbKLRNfbCLAQOXrVhnkJqZsLqusRpilcgIrRzLAxdAwNUpbTFcZoUqGFCUgSJtYTnHVOekViMNfLvDsfhDTKTIbnqhMllDFxqYMugrWtUSEfLaUACwNaeYDe",
		@"xFUqOtrPwUGpJJkbjHgZWv": @"SSAcunbWdNulaWypdmfQolrsdcLNJPMhhCodcVXyWgLpzCSaxHZtckTlTmXDvfcuJrwfjhkgADmuzJGBqcUloPXMRkOUVkfNjykOWbIRDNG",
		@"YXmTRKrRZUNVRzikUyaShNQ": @"AYVuUdLmFEnQrGyLQIPOJirUtKzjPDEHHMHVlVGjqUIciigEOHcyIFuZQhWsMQdMvwCpnBefwjltsPRUIVCoSKJSdHrHwoiGcvbSaHlqbuaekIhwVsjHgadkPMiQBWvDpwXaOYGBePQMOLEizAfJe",
		@"OFhAToLwMCAWQSxkKiWdLrhr": @"yyslxbYuvoJtKUaFvsjLTGBkbxKNqWJWXaEDNDuNLEClRcsHSXWhriZftVnEUMsGCUIFfDZqsKByysodoWgljIAJgNQDgDiBSaTmOQJSdiYGEjnkYagcqlhuewGXvsCkMkPGGtzPQLT",
		@"rHHEtgHWblu": @"AhTTNYDlINglTjgBDSXKAxZIqSLhoBLoAKeAMZNkcuXhvVZgDKtuTeIPlKqsPRZYiOoKmDutvucXYjvUPKIcXedPQSEcWpFoAyBVVSSsPdjIGQfMZ",
		@"JynYnrJTYFgkMDOQwKfQMje": @"bmgUZlIHxkXyYCQLphVKRxmQOynQdRMHsHUZOZgDppdYvjEXFhMkeuNlvBZhExIOoagONogSWxldmGEJFwffubZDPaihdCVdaimvIvJdvLikHQbxITeoqUVfjcdzLuSqidClcwVIRXqr",
		@"ZNftMEVTdLkPwWIao": @"ePdXacnxSTjpUiLmMvOpacyscXmSxPMEWQMVzQucCdpPhvinCiaiBroezBZgzjYJpSOayhLmMBtaRGwuDBzzxVaQmPwKEPeDkKcKJHiapBQZlwftazPeHEjkkfpcbkOcRsKkqL",
		@"jMbmZZkRnLnDUfNNEXhsh": @"DcCdzYHPCRolXJEpdZtzFJgUccnIyaPJGMBOGqYqRwaKAKQmwRJJexJcFctZHwicHDYhwwExHKVEUxWZYeuxpcKEmLnmimmJSfBwKuGIKJdh",
		@"YOSThPBFwfZw": @"nPnKJSdznzVNhNwlDqqaAwpBnqmFyxihAHsoKrnXPPBNinwQFrcCHsIesvOWlIyHOrIstzrggaISjLGoBAHVGaeLwWxnSnQDnoHAyOxetEmhaaeRbHcuEXB",
		@"xEaLuncfCYTLnIrvxovc": @"GlskAUOZLxYwHZXbxQlNllLsCZXygyZHrUvMCgHSlGTytwzPTodQsYmnqxwBbPVogRuMEKDECfSVHJIcMhdfgogYuuwoVjCFjuGleOAPQWQbcSoZDveIsTAXWVScuTTZ",
		@"QCXKDiKlTpUG": @"qLKCuQqyuAvxMBFMTkapLARjOFJFGeZHLYyJcssKhsCdceBWmepjtCYMOVFVXoZEBWMQDiUTtqACTBFQHipNqzrPZEZKxMNhlUJsCaLPnbvJMIwSoNyosXxNEWdgbIsggSKF",
	};
	return moAsNPfepnPKcft;
}

- (nonnull NSString *)RUFYnqdPeHuDyu :(nonnull NSArray *)SCSLusxJtPzpVMsMguJc {
	NSString *hwgfPhWWeWkgSoyT = @"ByQAimTGTnHmPlJpxllQqmADsLvPPIBTSjSfaNDbMFZFbtFOeSZRPxXZoFpvPGHPLpceVGqNGeNbIUKXgdnTvtRhJJQwXVkNPxOUookhyVuaQcIPJvRz";
	return hwgfPhWWeWkgSoyT;
}

+ (nonnull NSDictionary *)EkgxCBnYrIqPcjdmB :(nonnull NSArray *)WqhEyuXSra :(nonnull NSArray *)HupRQLvEHW :(nonnull NSData *)KvbzNWLxIWoDhF :(nonnull NSDictionary *)lJrXnGqcXcOm {
	NSDictionary *IdbpXMIWMleQtnlwbGVjC = @{
		@"LgtJeCLmgHBKeQergCSR": @"eyONxQEyNjEdUGbYDqrlMYDacyzffPwnIPWaHsataXOYARHpXTuGcLXUIqaaRktvehGjNhdDlvpjoUPAzPhwhDlYRtWpGxLjPKnNICUUwQtwCTYfaNUomGfaNILievWsQRXreffhjaEiCQAzU",
		@"rYihlcclNMpFfXq": @"VrkjrITaTpqFaqUTwwdxYpqanVQmDavbDuEVEsTALjDRdXHhQYchMQPfwDRvQhxTnFlQaIpoPrXaaJLPRPvxfwBbqeWmvmCugkYSBVfciGKmcbdiJHwmvVsJXzwrM",
		@"jMpKMADxDirCM": @"VgsLtbyOgiEFzAaxiITEiJNGDoDQwKyXbLYvRUFDGYWnjkZYvBTFUxwTrfDSZGajclvwRwXkVoKpsejdPUsJgQurFgUjndYZUQOCrZLnuAem",
		@"LUgErKuNzFccybFOPVNLAyJ": @"esqvVOXZNdXwMNSNEyfvhfimHjCrSImIREQuZrIlZLeWbcgtgyxxdJtKpzUHZUlNNqagJjcUQcanYcOohjSXOqmXqGBjPBnMHelPVeHWXxRDilBALrDNuRoHgaHkRHBjdFqelUNyNvxMdhCF",
		@"htREqXAreDplcwqDnRKpy": @"hncjIVctvOBNtAOZQBTxQrTkkaAMKqRvAFituawySswwZjfesGGRnpbhCpKKoQvEJrNsIYCkXBuUtPQyDpfbXfnciXRvOjmDkpGHemuJsuqsLdOqSSHaLZdAkoEJjITZgUdoovNscIzjEO",
		@"vEVbwtcuwkXj": @"zyrFGWsJwOpdefRYuKTOItClwsxtQfjTdNgIGIFkDvFUGdCaKhZxBzIZtvCMNYXFOEAUSUXnpRlGFrJaORQmxYHdtlaxqrisfUjI",
		@"oaMDCZMhxpYJQ": @"IIOEGioqsmDmfojxIkxmaLiIXndTRvENpPrZGlnRUaTljooTXaJhcOyVaNMvHDPotHkczrnLxJRdcAPtubfpwUwwjxpvCUpihLpEeLzqpKJMp",
		@"nBDBZSVGIGzT": @"RdUlgxLLafYppxRsbJvqUqnZYsgRoReFSlfYEiGBXAMVsovCljXrJLzSLTtCjRlNYRBKvpiEnweHJJAHOkTJlolaTQWvEQjtLdwWFcEEMbAxELCFGvFSZVyqsOeHSmYfHH",
		@"XNJXJZJHASig": @"DazoOhklhfOxhcvoihUflokNmHCYebRJJHlWUhCJkqHLovSiWYZQuprbCJsraTOKexkhBVoZXWihQayMmZIZXFgXlsEmXsSvUTfKTjrDtgxGDqNDLTotzpPhLuoIiFOEbfZAXpKPeijcjUOF",
		@"kvESrJAEOJzjUfT": @"uHhcpMMSlOuvPqABsLNMFjyhZhySyMxrxbXjaqOpPqTQYSvWAHjaEKhqPUAlIsSJckuiJBzAzaovCnSbKlETbMybIXFkeIUiPCJdJDyDVLRSgkJLRZmsIQCaGJkJtTWlWM",
		@"wDkxuaKrNrEEGUfWGrQyh": @"aVqEbSytJephmeamnQUZlIIUehwLkRvImGxvtqctqGuMUsdFdrzIWfkbiJJQmmhpdnjARqmkcjqLeUwjItQTlqCvEtRAvbVLazKGnoUAaPWbhWawwlSHjKMo",
		@"zebZdCqkyAeNjiBL": @"HJDysVzrqtrVYMGQpnHnnNUKgoajnHMZNxUjJGsxJtypZGryUFseWrEyMoUkHaMGygzVKgYJgVZFXinGIVDqKnXSKLsJcfEJLOmvrZXyMqaXxjcegIPVKGOUySBfOhXPafyMWpVHCaiXskD",
	};
	return IdbpXMIWMleQtnlwbGVjC;
}

+ (nonnull NSData *)YNYIlaDvKedCfIcQ :(nonnull NSDictionary *)NJVsNJPGeZoCrlWeuY :(nonnull UIImage *)uVzTWpCSrcJeNNMaRDIDO :(nonnull NSData *)SirubiqSOpWdf {
	NSData *FOqkcEVbNmsEHf = [@"WbFIVSaGnJKZecLHTPIeFsRvxCetQTqdoezMQBVNVEOOeWsNMoyTeJIMvVRlfCKsWLeUrCQPBxoFEojzzExMrTEHdgnPPGYACkxCQesyiFG" dataUsingEncoding:NSUTF8StringEncoding];
	return FOqkcEVbNmsEHf;
}

+ (nonnull NSString *)kROBvYRozdpQyxntSHVFRLvR :(nonnull UIImage *)IUjNGQsoOUfmI {
	NSString *VQqgcbHnqdvoZpyAxTXyw = @"KuiWSNTRqAXbBWGDymJigaKZIuVcypYjVOXJbOQaNyYWJmrpoyNDeQSmXmnpXWmqKSyYxiEiAfIbdnnArSKyLTKEyjIYQZeCfhcQoJpeKCUhcdjfLjrhHGlBrKbmLBDmTVSOpHD";
	return VQqgcbHnqdvoZpyAxTXyw;
}

- (nonnull NSString *)QpjOTVScUyvrpb :(nonnull UIImage *)ryqlGkstiBQPdwdEKNFX :(nonnull NSString *)wHohgotZiy :(nonnull NSDictionary *)dxxegmdflEpdlewOZAUfq :(nonnull NSString *)wtdGWCHOrDs :(nonnull NSString *)MQTijRHsFhemQuVmFH {
	NSString *mNXtYahmrJTFaMvDGPId = @"fUqhxMuBBCHMChrFfOZkmdLwMXHyMwPgiJjwDPLPOLwaFMWMeSFPxpzGfipJbEZMfmVRILCLXiztWLAveGgFjiIhtnLSwSyKTTxKUAcmiFDOOUXGuGNDacuaSPQbwtivUZI";
	return mNXtYahmrJTFaMvDGPId;
}

+ (nonnull NSString *)xPkifLitCIrjKuQjLGq :(nonnull UIImage *)oSONcLiDjCJNElECsHehKP :(nonnull NSString *)wAmErgHarecPTapZ :(nonnull NSArray *)lFlQukbhcKAiHsNC {
	NSString *WAwNUMaqraSKZSW = @"VpikseLCrUochDhyjHNkNKWvBUzDbBngUKaZMAiLqFroYVzwQGVBTEBCuEJfJZFKrinGFPaESUNOhcXcLRNclzrsBOBuyiFbmfBftAxdiTuihxKTNoXWODE";
	return WAwNUMaqraSKZSW;
}

- (nonnull NSData *)TnLWwMnHpLp :(nonnull NSArray *)ZseiETWWcQYd :(nonnull NSData *)SqeAsQiMyM :(nonnull NSData *)PqCoIttaPCSMhGM {
	NSData *HhlrVJvLFZO = [@"MKrIhPfYFZOcqSIWNnhWtEpAhAiHwSzYjLXsaIexCEGuuYrLEpoaURqfweoXTHTKJtaSQLsckoBHQNkMDyoGAljkBaXeeZOEFcxlACUHwmJIAqEjJNuZPssgkvHizvJYGWJ" dataUsingEncoding:NSUTF8StringEncoding];
	return HhlrVJvLFZO;
}

- (nonnull UIImage *)avCYSNtpqk :(nonnull NSString *)lOiONMUVBIoCBi :(nonnull NSData *)vnaDvxzcAzZSqKzF {
	NSData *POKJBJzdYGY = [@"yghlbEErujDIZigGjVbwjrGlWQWPUUAiTAvDtTMaJViNrontDRterDjIzjbsnJxmAuGPkLYoXktYLnrSppARryRGFUzGjboivzDJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pnZuQPYzeMGCUmHOHCzg = [UIImage imageWithData:POKJBJzdYGY];
	pnZuQPYzeMGCUmHOHCzg = [UIImage imageNamed:@"ThkBhclesNqmYpnEJlyRCJxhEYwIYaenHunuVpUpYfbFZOgzrYCdQUuqIftssPiFShdPNLLdZzrctQiZItrHwGKzsNGfBvUtkcJCYITgtqmDjjpyjuJBzWyVVVBH"];
	return pnZuQPYzeMGCUmHOHCzg;
}

- (nonnull NSDictionary *)edJSqPeIaSivlorGReN :(nonnull NSData *)wHMKiYRSkcSlXrrD :(nonnull NSArray *)CTVnLMWtyqVzYwDyfn :(nonnull UIImage *)NZUlVlKexGzpymolkDL {
	NSDictionary *RyJgEYwSOMBKNcjtHcotCg = @{
		@"bUDOraTkNQJiRiXkiJXYZNvG": @"CwVbJqzsXZRctIkiBAPORFUxMZuSlOYKCVdIKZtmNKNQStzCkjFptuhPiCgcWYNhPXQKEiQZvPyetjQErDkXCLJwyASLHwmLwYxIAqkvwociGXjMZtoAEXy",
		@"LFGegUBQDaJZRMu": @"REfaTzgnLLYPMgqIupoMtSbqzfRNGpaJGWveTSNJbTuHkUIrQcTySDpQPwULIIRWTCtbsstrEwwRDKdAhwHqGGLxJvtyBnRdXeWXEkkSdGLHIzSazRepyZaSrLKzGlJNXHvxGTqbfGjCzaMzJVs",
		@"iybnJZFJmgpCtQeYxg": @"zvSueCAwBYEUZJCFqrWVIBNJxPKoffBnMBSeavPUNakgpFwXQkstZaaTxEDcffhcupTEwJPQqnTSOlZQIXfDjNHHRgDGjGwRLVENdymMOuWbawMGQrsLidNRwhAxlfLyAAxvclOCDiyxX",
		@"MYBtQZnkIRUyKwTABX": @"zHZepdxzNOJYxQPCMZJdJFoNLNksVTJzNMmByjuGWnZXVkeEhvkgDAZDLCrYqEimYaWBWEiYhppLftHvCZGhwotvHXbvCDvcQwTfkzdmWVtkOXxObDBjBWxENtKwz",
		@"LpvlPAKRbwrkriUgzZoAycm": @"hJJkKDXbOWTwMEwllOsxweJaBpcSHPorcNHYzPBsahHwEkCfMnvJWWRFBAEBdUZVqhErfqWclNdNyvErEecQkTRyTwgCTvVUmDUZWfzSMudttkOfpYZaWhGdXyNDQnVDuVyxyMdwOga",
		@"xDDIPBEisCajLeiNty": @"troSzKuvQPWqCdqSxqjrshHScsBJmJxsvCiBjCwkhWRVaIGBcoIbnjSkqOpIJzIvJMFEjgBbpgRKaTNgWQeXAhvfEZqJtIvftLusVDdpyJrWkRfromqgrvsuCRT",
		@"xrDQZhpktpaKCbPlYwl": @"MFaLeXADuSUPvGujjvWXGQWCjBpQkulQBVFHGURqgcXQhwZfCmXyIiNyWtAPsSrpBXAgLGzjkXAIWFTZnwTyOlstRHdJztKjFnfNBTglMXJmfnvkPUSIHnzYRfCNhVDnnWMbcKnjyYnxMwWZceJb",
		@"SPUdlqSEWvRMrLkQwoBz": @"rGmopaksstPmUZqqsDrdBrgIbcPShqlFJHyXPBGIxctrDBwxmdJSVfQwRQEAxanshqaoYMGUQeMEAJJxLhUmQHjeHpgYulbXHINqDwkeT",
		@"KEPSWBPONd": @"PSPJdhyaFfRZWvUbvshBarMZcxGXXpWPruqSEEvBNKbugEMLDOVIzkhabynfsPonaSEXunbCEfQHvJtqXGnMeMaaiulCCqQpjaOrhcRyHK",
		@"hctLFiRfieiCyc": @"boqpMCwpYprRluMstCiSqwDmNErwxiwqIEDBFIxVxXgUMSxFvbRHlVpsTNIpKnJfcjvHrMcVNxOwzHprGaAXIMsNPeTprwWcHWJyuDJvyLENaAoAIRruiLvKLqVJiW",
		@"jRmDmqoDyveMAthwrEAigF": @"fEdBUGwpZGEHKqbzGpaVpmwycPfbsVPaSCPQUFcLyalpcgumRrZfXnTewbQgzGXBacnbsRRkbNYlPudIMiCtnYHysongrbOgUrlOrEPUOwYhparZWXNrMgFYIT",
		@"TYMAQSuwnZc": @"qAXRRcyCwBbkCVLuQlXYwoTBaDndcsLLSyhcLZOjcZfOiDDfJsBHjIeUiTyXfaiEkNGyRblezbvUmmpZpjaOEhejRLqsNmLNoMUjBJRmzaHEtHEbGnjZsklPIDJur",
	};
	return RyJgEYwSOMBKNcjtHcotCg;
}

+ (nonnull NSData *)KzzdlYLMwZMdS :(nonnull NSData *)ujSOmtJQFqNiXu :(nonnull NSString *)WTNMbImJcMKCszdGCtQs :(nonnull NSDictionary *)trDEWTZSnZKdwJngkupC :(nonnull NSString *)lfunlpaXMUisxawmwSQMa {
	NSData *bLPqbUHlgZjykPFPQFI = [@"vikMQHGZSVIUxfRQrgZhXkohpFinBwJowyFUexYVDpZxAylCVVjAcoBudKOXKCpoqxYdxahEkgXLtHLsrtglbpHoLeVceFeILUiXawCYSHIssBAYEHveQzqrymtdyzRFP" dataUsingEncoding:NSUTF8StringEncoding];
	return bLPqbUHlgZjykPFPQFI;
}

- (nonnull NSDictionary *)ZRbHGIjWslp :(nonnull NSData *)ugudVxOCExLAAMuVTzYAP :(nonnull NSArray *)hRwszLHfntZEOPBmcPtjLlu :(nonnull UIImage *)FTKZemOJQUWpSN {
	NSDictionary *UtVeTxiuPcpPNJl = @{
		@"oxhmCnGqNBGEhvHXKmd": @"rmhWyXKbxPXxNQBVmsWrOksbhefnunitHiagRYZFfrFhsafCRetHEPJbSnjvkcmOIqGLCVsQcNbRAOuylLzpnXnZCAybmeIYLIvTOpDfIGC",
		@"EutkFhLpzxhoVWmsBcOAhIUh": @"KREVPAhIgjtHOEhYHksIkZZFvtWnuAoRVNwzbtvxBEPzrYiCZCtMhNGKdGApEuLaioLgQGXskVWldGlXMIwJRUrkmyQwLAmkYZUAxSQDZIymnnapthiEyWzsSisnWIumPBV",
		@"NWVuablopbA": @"JRekbbXTVGsWVUYBEuiEwfyJPJoJHLkcffSPwCtHpCGTGxlwyIhwApmTCPOAHAyWVAQTsuGoExxMWbhStJrxRkBiloTfAjGApUvsyOAQusuepnFKiQullqwujtGxrkpTdZXF",
		@"vQaCCPTuRQuPC": @"dgoVlNKRdryvlFFefyrwbeHbyXxoYqaFsfGVzeSNJSFnwTOQWGvDwEyJWjtrgaFODFvrKvtkvqXySBWARJODJhRhhZFuLxXgTlCFCzTkQzvdSlmFZZYWzVlpYjomzyXOYZObmJYlsKqInn",
		@"qBotXnpFUIlEGpIj": @"YIAQPRuMedDrhYPQMYxXZafkfrZuRFSKenkLKaLioiKMjnnphFMNhDiTgbgUCkgaslRItyyadlDjWMEsamxyvHdXSuRkPFRdgWYxzrJGplFvZSlq",
		@"CoMRCKPypIHAtKOCzuq": @"OIBSZmxQOPleFmWWspYEEnYsDQOsmDldEkrBKmUvSyqvVuMUftkACzaJrdHeQvIForYLmwrkCfwTbxmGgTrRCMNsdGvzyERgMcAxhFKlqAQzctFqiDqhtaHhqu",
		@"ocvdWTCGTMJaeDoM": @"AIZafwlqAZuGPCuyVStYBRMMOAieVcQgEoMMDTNYKvSqNdMWhaYpKcCObYxadruPvOSdiHhVsDAieYxqtsmRgVUuQKxBGkgBXUrJUpghjbiSLfQBkiEqqhwOJPQtTzclrKZnNh",
		@"sFbrCFKBdtwHEJoVggG": @"UeBkgZFdqSDDvBNJnMELrDNVldHUTCyiQEFVSLKciqFRbptuDTEWkQOHTSMBhZeEgvbEqJTJeDvfJaIUiYTsFPQtbbVmjNdemkJkAweEKeyKehihLtBRskBmlSwJS",
		@"RPtXjldLCOiGSq": @"tvChjkXgSbAGMINYiGfzgpRTfhVgiVGksdiebbOlcvAPibobzvEVtNrfhWsnnhiCrosIXooDKCdZxmAZxsSBCBQLSSZhSfargdTcRNQJbRROzUkASbp",
		@"MdHOLVXBDGYt": @"GDYcxDrfdgctuusXnOdThXGLJFrabKYBvWOEBRteVhOULkxHwHYGSvjrOHkzaqYvikpesZUOiXAdRpvTTdQXwGqehoHxPOGDLUFGtGrtSzmqReKQVbULDNlRWVnXpJSdkXrd",
		@"hcDbqpjoIOKaiwT": @"VgnXZfIszlpOMDRWzPpwhoafRHTdubhcKEPTaSDXxdjhFbYYsHaepdZmdRjTSBXllThIHzxLnEirOBHjWTsBXDVGRNXzBZQYbvPVaxiXiwiVLFgZvQRTPMK",
		@"wBjUtMArgfrCXXDB": @"kFoHhHOoEabyZjsRuVFrrBmAqhOOpCuIcvGlUIyPwXWndnwvjwwJLuXqfnxQHRHlhZoksodtnoWhkyMQyNLewXcZNwlDPOBiyMBSFeFznpQmLKmXhmmngweMDQkMSFuNPVfBTUYCWMUGhhTcXpSbC",
		@"mmWBMBgWVKYWGKB": @"llLofpBPGzmawgfpwSyqWLLDdbFflWIcvvCxRElfGSWRXPPMerNfOHmiZQKxKMtdMTWQLNNuWXdQtYTPdwwvHxhRlNVJDIuhyRSM",
	};
	return UtVeTxiuPcpPNJl;
}

+ (nonnull NSDictionary *)igEfElfVpoj :(nonnull NSString *)DToLUQpnJYhl :(nonnull UIImage *)DYWBfauBLP :(nonnull NSDictionary *)LPvhlHTazgA :(nonnull NSData *)ryKfDbNBFLcIsZEVIRTwUs {
	NSDictionary *DlnDqocdNpBLvByVZEhYT = @{
		@"FXTvfaUYIuEdmN": @"eysZysVRBgmVqalbKxspSZLoHmJMtnCGCoJQqtScNNNBWegCKMOhbXCeeKOITRkIYXQIbFwTkkwNdkFFjjtwHKCLnIKJlXSZpyRLfuPdcWhmVYVtcFkEXbcFXLPqudqmwITC",
		@"VHxniuKGJTewEqVleQ": @"AvJTquKBqOAdUnQdjFhgtIcYDQpUBhVzVBJHvkFLsCEzIlruWbjNEfdACrfwtiVsqKlMHGwpGZYLXhIhFnMBeUTPewtYjNsSuRJzeYTlAQxWoDahhcCUGRwGGHbLbGjjGa",
		@"GViHghPJBrdXOC": @"UQJKhDVbwJqjsMBOlduwfvUHShnAcRvJQCArRWcVcluwnItYZmHRMChNorWGlNpNurjYQMeohwdlvjnKEzVVITaYsgFuuKVsVFkqEmzWEg",
		@"vtkJOPHVOfOJXKwlmBEusgYK": @"cALLPMJueEUvXNfFpZGMiiKBIQpjZYjEuirbwEpIMljPuCnntdeCsslGrRPnvdEhCdQeZprxRoXTohJzTzLcoDNEjfDrWadYQLpohAFKPIMHtbVdymrUmuFVTLdBDLKqV",
		@"cwsUbYFMLrAzTMdiQvYDED": @"kUtkRvPuzGeWNYWkWYYLquIkUzmCkXwEYxKhWgsBPkWebpaAfbIDNEnrqFpINBBEGhHPFfBbIMevNfxLYrgnjpcVVsiqfFSTgkVFMQKZxGeiNHHQ",
		@"zWGyPcqPHfOQV": @"bVxiUKnfTJZjTtRWFTNUPWDRdShJJLjzbWuObyZQUdDTAGogYyfdxWFHAObJKwkySmGFNLKgBvgzpkjAqXxRdyaeOoESGVRaEKaDBDUj",
		@"sSQpGcxMxxLv": @"IEAXCGFaeBPnOactiIYqaTGHPfFMiBvZvfOAsvErfwPtMzrlgLjKLwAMDZnqpGHKyIiimlRRfhiSVoFKaYbYpKCyvxKidfqZEQhkcGfgSVlKmbUGUnHNOrTuDxodQPHsHERGyEsHMbjncZrqXcqQD",
		@"eXCrCGjyFcliulCDw": @"dkviKMziRZrWquGCQOvVODgQEjYvsyqEmGJsPsNzFSZNtWqIGPIDhQfbCOMbtFkPGSLSXfNXiZrrWyEjZwdRxzZZzYYEnajEoQtZkroYrumoSKHdKhCiRRoKFcpdaTgHwImcQR",
		@"GZmfRiQkmewPWlsLI": @"rBiXktUXHzvPcDYTpnhKSVwSwtDHAJUthafbxJdEzaMgwkeiPswuenqLyUMDjkVtOlqNMxYXybntCSxVejgsvAdsLQmXvkLcaouUHZBUfuBbndGxqHPqtlbrhyvUl",
		@"cSTUfYGeTueWYf": @"ifQEZRLjhbFKpZuJaFydKhreckOgjNfRPwfIdbXTCXlyEnneHVQOywoSLsKJtCNxSLoWmjRJmjgFIyHzMGNvFQpUvHfnoUpeQFszhPcXdaYTOGvrvRIqZkZmVdWlPbh",
		@"DiWkowNEelLEXoyjArEBZa": @"kkMyOKyevFjuWvQYvXGvRIwAooVutNerBLPovgSyewQZYcoeaHmsyNbsPdAWsmtcNyufrxcZyKskNGpdoTQuqwZvAvOMpEIfdRJQyxkP",
	};
	return DlnDqocdNpBLvByVZEhYT;
}

- (nonnull NSArray *)XpQxdifJUIbal :(nonnull UIImage *)RHeKmMgbzR :(nonnull NSArray *)URmithapqMYvFLrxJhftQqt :(nonnull NSDictionary *)amgJYtrSBKWtTwzgISpLp :(nonnull UIImage *)gLuSWlljjWfNyOsWVGvs :(nonnull NSArray *)DnkrYlwWxPtpohuefjAzTIUW {
	NSArray *qwweTikadcdcqJsFPuIT = @[
		@"DMfGmMXSdqwKaOItEZWWQXWazXowgBJygECUgUMwJhDSYubRmoCJRDjRqDvNvcRSlvspSXaEdipqkTzHQsMdnOjbHkbslJkRXKAqELlYXylDZgCXFPwvAunlFjXVnCoYWNBWzAKrZekSFIEQO",
		@"cQVKfSwVRaHGVdhYrNjjcswGinnwcEiHMBkaNNRHyfMwnIRRqBEWOAgcXOUxdVhojDbjfURsrvsNLEnuJcrGwlNWEvbqnPzPkSmpegXoYbygxhyVDpdWTJlARRXcIneUuTNEggKzBnQalracqnuta",
		@"aiqumACHAJNfoXbSGFKFHLeTSIJhVOymgyrwASSLdAVeeRMWrwfuKuZkUOheDXIAdkkYZqwKPtDMdUNIWJKqRNEhYdkouZdzGLhpV",
		@"TiKOvosFbuiJBsEzVKIwisgGYNFPaaeZVtUiYHisubvANKADwoHsjhzniPzwNNmDIAbJMCVUVnPLtWIvRdEZNegipVzoBmLkoTSpCRprDzFdxEPCKDGeTM",
		@"OATqftyiOhKfzbjseeHiTFRBEOIqJITkbfLNFqgGahRiYFgHNmpwHDLVzdkAtnSrFPZAlBEBdtUunZbWwoDQovJdaoaRJhFLYnrNT",
		@"kHremwAYKIMfJJvRBvtuvqukreJmiEefgjYkNaeniyTaRhnFqaExFfsqyNBZkSRbzRDqhmLBnwMiJaoksiMjVwVCfvyuCOxMyiWmHbkuJJPRLTmzRMbGcGaOSDwjFKYeKtQXiWFdTGf",
		@"JQpUaGUGCxAAaXwwbwBqfuQPWmYpxcRoJzqDDquKIsAQxWyTBCSperGJorfHCeaUDKjPcwFKaeqYGrbdLfznqVcbdmhTgbfmCWHPrAmLIbRRvDlQqcBzvoQfyVhRVyPgFa",
		@"hOOTtJNwASXimETkeibZPULIFmgQTAPrpvKnLisooaYEwTGjAadjgJUykGBltxlgzerCbnwPkasNSefqsmAjuTxWRChHbWytYForNhpHwbeZHsuTlVqGCsKUINaYtyAjJvWcaTwyPaKqKLCncfOz",
		@"fgBTBmnvgtzGsSkHQZqYCqEhGejpwwyfQCoTAjwdIMpMaxBBmmsheHerDEPALFoKQhgpsALiNLcGWPKCoSqVfCNAAdLWDJIdNoCyDbggNYCcsMYtDiNNdBEatWJXNJY",
		@"oDiLaFsjxZcVWceQfnkRaclNUzFFmvjFPbriCYiMDPXQogXdPBdsHzrKDULONsizKklqoSmUkuGQnBPaOKPpFmgddHQCJPcbfIHDNxUgpVLizCCTKeNggVDvCaMwaQevBgOuIgiLyYIARfQ",
		@"rCilCnOIzctNdvxdogAgAxZEBhpLjMrBZRbReuBLPyzCTpUtMccoYipUoRBCcSxIThPJboqLmKdzWtWOovodtcIIqstGhijLbiFCZHMQIElBAJgpxgxr",
		@"NPRDIDqxZbHuYcnpanvNrXLnqgevIIqnKUMHFYGlYnVqLuJTjaUnxYbJgTRYySeoLhRioMkHzFHVUbIzmraQvqDEOaHJZysqWKHBHTrEsdmcIqpuufHzODRYDOyhYbcAkKt",
		@"nhSbYSmiYjwhtsouYWIbtsxMDtSbsdyHrVtKvVxfiQXLfTvxQyQgNarjIYelhKFNNaUdLlBTtuZlyRwQHNJXDxbOlVDnPbeoklwfEAbMnRELcIwdyTfOICVePEUgTqTZFTYdbdxwflWwOIUmY",
		@"SEZnCIXJazPLsIllRmLSSEgLBMUSbRmOjhaBFmvESMSSgoLJLVFMGatyHgGDTePLtUxyYzQcVUkePeyIDZnxIGtJhjkcSAUaMjpPMgY",
		@"MtfgsjmFZznHPxbNtyPIVLqNSGIcexnklacaUfrInPVHajsjjGCOdazmhNlqfgswZMJgGRIDkjQTMBDBDUjSUVamYjeTVZZSiFoAAJCyYwstPGrhPPRUlHkbkTPOOqmRZbhrXGzwwMLEUzxhbpM",
		@"CgkdfwhuaCykYkbMPTJTppIlptHavRZZjEgCjyaVZGDbzJPmcDexcdnpqNtTORGCbSmxeFcXvfAOQwVZxmprvdXAWSxSaJptEHykFFAijCIYHPyVkCeZwBIw",
		@"EbNJFvQAzzxbozKxuagVImXHMcxOLAsTXYsEfskZKrlGCuAgihuiKvAqUrIMulxduokMcLZGDjYSwLOBvTXujVvVtIuxaOsQYGCWulYh",
		@"JovFCjVSZOPLumUhPyLjrNApUWttwWTZMmzxpNgnurrvOxHMDTTdNlzPrMqAudBOveOeRKQLelPidFalCOTtZburyxmgQGuhVZKDtWy",
		@"hULVHxZKUSRMGjqkwkvyJdqnRniYihCjjmImrzZpUSYexmkUcFONdjIskzPIcYDTlkXTQSflgqAPjAtPZVCBEVJiWBqXFBTvtpiuvZZaUkmOFVYPHRiDXoRhOXBTdHrQKaYkicbQ",
	];
	return qwweTikadcdcqJsFPuIT;
}

+ (nonnull NSArray *)YqJRVZeCKLfSjZTgBZ :(nonnull NSArray *)yVbXhzBLLSEWdBjs :(nonnull NSString *)ZcIurdACmPNz :(nonnull NSString *)yBnYHjaTtMpQAkmMMYUuisY :(nonnull UIImage *)BHGQNuGojtUiieAUTvIjiC {
	NSArray *yOqPzXuliSyRGjN = @[
		@"zEDQpZERnJoxwwNzMwhpFCjEDOHoYnoWgwtCPadPipGGhyQdeDFsHCVqDlbStVRvngQLKjRvrIEfiCXlloyBRgAGfGkNiXTgCbOiEETwPQnfUyBqOISqCCLiem",
		@"uSgsHFEGghINxoiBfcSvAJivCyWtsaeejSKSTVCGfmXSELDpzgmhAneorUeAdDmRAEoHaWnlTdZNpgLNMvgKflUjsgdcjNduYPuteRxyUmcWVDmFzefQkVogfKlKztOunQafsMDMRCfEbZkrHJVI",
		@"iIxnpJhGvLDFCcgicgdDsgHiCyIdzeuodLRQsSAicUoGRFVqQBaUOzUWOzGJJIrlCGqskqatGhlPLDzkTYuqAezoXJmzZlyHqUEHvVmmikGBoGjYLnRzAWQiqhuMcpFDfkulEhjyWRCld",
		@"LshWaNsAKjhpFSZozSNChZRcDfegLnZPuqUhGJJqlODeLgSeNqBrSBhYyZVZPLxOEGtGeFtaPCqyXBaiyOQdPvuVzKPXNsvtBzqfIXFTjGVcGkThLykmukVNjFeoTRJiJLXHhlGXRfukSUMvBzl",
		@"jcXEUfrwpWSKBShxIOFagPSXifGPrKhsVdtOZRZLmmQuSkTVatzIaolrDStrAojJuJfXHyKVgoyheXdHEzYMCHUdvYxRagUOPWyfziNcVTYswCaSCqvhUmAHLmMBDvSrTqbGurhOJjZiZMsmN",
		@"ylzZijKqQDuDLCfOfRQSzmWvogRkHFuMXukqsNoezLtoKqPdvxnGMoEyXJaNgIIzjNAllnLHtjUYwmXcmaqxOTdRnQVKziCWkbLuRLGvIjsYTusBNUcBdPQgphS",
		@"YaBabCjYbFpVwHQtsUndQhxrqDysqwfqdmUZVFIOOLYVTnfkcrbwKdTFmMCEaqgznYpIdTUmnDPRaiyPOMnAGoJNgEXenHFvrLocvOJ",
		@"ZMKzwRqHfaKtWwIixadwwyoVUQGTeVjQkVfiaPMcWdAHyEiiHSSBLIoQGKeBhNvsxRGBMauFANVGfojDhBOatsgbyvWnyHyyNSIfPKiyMygRlrfkaofTHxhySPSIkwhqWgnMR",
		@"vBLrPSFhTZNrIFLwiLbwJlopZuTncubipUOnYpdEpnnkjhWNguuFUuYRxoTivzCHnxMdLFxRxNhnylvlaBJOiwiwhMIgPccKjXYbKxZigOtaIDaTTTyO",
		@"wZUnUArlKnNMAHPFxluJUBtHvhlSqsvfycrKJYnGfoYUPqvWqNxkkVeHGDoKwTZdwdnGlojIExacsupeuXhsXdTyIvoaAqmwOUrUh",
		@"oaZeAInhWkvIqPSlkpIWWljnFxQattHXyEUNJGBPBhtKaXpAgtQXcdKgBXLtnkUVVcLZCxmsjdPUzkFzLKOSbPrDgtfpjAwNOcToZYsIAZuKAkctnicgzZdziYvkKCGeuDHIeqlAMobhutZhVIicz",
	];
	return yOqPzXuliSyRGjN;
}

+ (nonnull UIImage *)DkcOJWMuCXyPC :(nonnull NSDictionary *)PqthFheodb :(nonnull NSString *)nMcDecFQkJHG :(nonnull NSArray *)rYqSggWwFjaVCpfnlkrRqOv :(nonnull UIImage *)EiAIKPIoFzEkDMQ {
	NSData *mMTurRMseIaGSkD = [@"PCOFfNjDIzskEQsrvxJKZWxzQdArFzLhQOWEuWoJlsGhxmVQejYsmyhUOdURPLNPxHHMZdRDYmccNYengBpFSYagObemrmdQCZRgycgiMOQJBkTuqhQbnTvzAlf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *McQxYWVHAczAEa = [UIImage imageWithData:mMTurRMseIaGSkD];
	McQxYWVHAczAEa = [UIImage imageNamed:@"nNjcTemodiaautNsQNwCAtZGnGedzwguwvMbHuqnLVIJuQLMVejomibaxAhyfIgVNZjqiWCTxhMquAaPIXNZxTYPbYAvthPcmyVUMBjIDRioNHADELdFfBj"];
	return McQxYWVHAczAEa;
}

+ (nonnull NSData *)TBnhiZdPcjfSBLnMMwHxQ :(nonnull UIImage *)NufNkgCAKzTBceMUBWjEfV :(nonnull NSDictionary *)VPpDSjZUDSwPIvHoFaMkTU :(nonnull NSArray *)cDgHxQgRyXxCtUdrTnprvV {
	NSData *WhKOvNQjgfgF = [@"yASPMizEdfkEcDRZHodtitDFEmgiSqGfOklCxAAvPlRiOFZTehReKFnxoHXKoTBURdXbzGddYZDgDoZAlPrDJIRPBOnuuiklqjgw" dataUsingEncoding:NSUTF8StringEncoding];
	return WhKOvNQjgfgF;
}

+ (nonnull UIImage *)PnxyyaQvqlomrmHbDVYBVfG :(nonnull NSArray *)IGHCtCiXCwuuaCncJXU {
	NSData *fdiKmExyXYdcJHTJhedu = [@"raZvpIBfZbCzRoVqKhYzPFslSnoMzqUqQxoQeiiPilHVDvKlDgQXTyBsyRPqBUSLcUImNsGRgFfqkJKJACaWMViRsfrMqGXEAxvvmxDv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uxfTDtgTGwhLKaNwygIH = [UIImage imageWithData:fdiKmExyXYdcJHTJhedu];
	uxfTDtgTGwhLKaNwygIH = [UIImage imageNamed:@"XvTTiOYWNbiFFtCcdaRlabZoFYCzrYiSqWCiJDDKUTXFbOiQMtIOOSdDkfAFHRYYFkCbpRQyuFINfGJkIpgsuQJLcFDQdMJxRCXBl"];
	return uxfTDtgTGwhLKaNwygIH;
}

- (nonnull NSArray *)bMcVuxSveAhhLqLa :(nonnull NSDictionary *)BiRUaXfIbwNJeOXlVho :(nonnull NSDictionary *)oKvPYFpTNBEHzuucWtiPA :(nonnull NSArray *)jzMjAAzhuFfkLkMRTqrZgKb :(nonnull UIImage *)ykjDBSVLhVuzGUVOTVzE {
	NSArray *jogQpWPCDqx = @[
		@"DmkzvRCraNTmuYMtuNSUIeUjBCSJmFfPbXJCQEdbjdANwAwAAqnkcunXdAZOIWUjlPXSGbZCWDoZlLbLGYvmxcVrLTZcIWFQougGhNPxauPMpINS",
		@"GYtQAMRLgbHeqTAgLeXgApOKvnSixQnjRDrYXKtQBKWVFHZKRETlprfljZgnADypbfXEkeylswnQPEcuXUVdGTfeGYhIEcKWuigzLTrrhBjGSIurSkkSZ",
		@"JegvcoyEXNnkkVqABrEpIDrKaZKXqsuuYJqBIyRYDQNRAHPVGTZondEAdyosxBOGimjekASQvGVEgQomlazSdQLyHPnGHNEgMNrqCiEYCYxiENHowOkYQGKWftVGvLJlVQiJDrYomLloNpnPKU",
		@"bMaxwxvdbPRnzFHGePbmbmDlPpbDddSppZxisFHRfarDZvAlbDFZMBMEhMsYruseBTfxuggeanTPFwdVhreYWYFEmNdXSpnTpBihZCOqpxjGprKXt",
		@"CnIwAOrmWnRszChnZTYmiQHhTWHhCExkkbvMwHIjpYORZfaFfDTvEadFHmzEMAmQcaFCQMQWvNZpctOsAKGUqGfPiVuJKoCExKOXmJXBQP",
		@"pthLKYSbVevDhFCYxwSvTBdLnOrEVqrsLLTtHQaMQkUTtwWKkPHwkvyhONzdCBAHebvlKzTdPiCGnNaZzaWtKiNesNCRVpSUGyDZOEqGLltDLLjScxPRXdfHzmQkuOZudedBYhBMnnMS",
		@"ZFLHqwuieCGHmSieKJzSrrOGtKAEnAyYnCOQFWUytObkLuFuVcUclPJbQYzPtzwNrfMLNikqxhjKdqcvTnbriKLSFNXCTxGTkfbKNFShzQeQTiPSMDdtZldfnjbZKZppvdnVXdXaCrdNqMxCCQm",
		@"TnsFXRGmfAOdJnUIaSbQqEQQTgJCcztWlhYYOSvyDcGcCfgPeIXmEAdNuBkNvidqkCCyjEqiEgZTAmDkyhcmDkqLhxLZgiQkhBemFVfcwVvEoWChXeuHLHOVZHKWudFyDBKvOyjjxMRDwbmV",
		@"jQmWsNRyssInoXvZzucuXrpIQOlVikaKOVvWHXYSgxcQWSeUKKuVGBOsmDRrCgkQoUerMGfiOPrzkBbDoZWvfZJoQdmTpAYRXRgnhhFgsHPmxPiQP",
		@"VqHqsNqaGgEZftEUnZyEKwhWrHmyfsrAirwjiBPGfFcZzNvEwMXKBlwxFdGOWcLEGevbNzOTScXhkdhjlPZLURQAhoqablhlVxkEcwTLBJHObxcJYDcQKJUjqAzZTMOjrExkBppjxqNcf",
		@"BtMDECYcPtWoscHKJQgzCouiTGiwGSngqiWdeebtfrrPkxGvUJGqBTyNYzfYrsuTzOULvWReUXSPBKlZoAzrsOeNmjYkYStfFZfbsKKrNzwYNGJHQug",
		@"rPnSHjPPOQFrLCmGBlZyQYhGavEYNOtUiyvJARLqVLSaUMGWkyOgLibKNqkcaCIWUtvSaLbwFkmqlMvGVvmymMvNFoflYCSTCXTZChspVfYsFWVnVuYqHCWDZbuBpGeuZOzLkHizDbE",
		@"WjxEKxpylhSzaGljgendicEABnKPJLuUwHSUoejLERJaXtjfzURCJeDczZbnDEcKQvMVKKAgDPbifrAARSIhySVKKPSdWppCIVWcuvbGGHlKc",
		@"EZSJhexqqFuCTUXGuOGKHXQMeJRleDdRpPVVjEbwjPDGansMFquTkwWOQkMMwKaZtEoDcSXBgeMhGFRfzqHWWqUOADYrtqmAcbVXcCBOMojjZHEbyShMSZCgjBXpwDPhLpqIKBVBpUANYVrDGsKNP",
	];
	return jogQpWPCDqx;
}

+(NSString*)getOpfpath:(NSString*)path
{
    BLepubcontainerinfo* getter=[[[BLepubcontainerinfo alloc]init]autorelease];

   return  [getter getOpfpath:path];
    
}


-(NSString*)getOpfpath:(NSString*)path
{
    NSString* container=[path stringByAppendingPathComponent:@"META-INF/container.xml"] ;
    NSData* data=[NSData dataWithContentsOfFile:container];
    if(!data)
    { return nil;}
 
    containerarr=[NSMutableArray arrayWithCapacity:1];
    
     parser=[[[BLparser alloc]initWithData:data parsertype:BLNSXMLParser] autorelease];
    parser.delegate=self;
    [parser parse];
    if([containerarr count]==0)
    {
        return nil;
    }
    return [containerarr  objectAtIndex:0];
    
}




#pragma mark- parserdele


- (void)BLparser:(BLparser *)_parser didStartElement:(NSString *)elementName attributes:(NSDictionary *)attributeDict
{
    elementName=[elementName lowercaseString];
	if ([elementName isEqualToString:@"rootfile"]) {
		[containerarr addObject: [attributeDict valueForKey:@"full-path"]];
       
	}
    
}



@end


#pragma mark-BLepubOpfinfo




@implementation BLepubOpfinfo
{
 int  elementkey;
    
}
@synthesize metadata,spine,manifest,catchstring;

-(void)dealloc
{
    [catchstring release];
    [metadata release];
    [spine release];
    [manifest release];
  
    [super dealloc];
}


-(BLepubinfoelement*)analysisOpf:(NSString*)Opfpath
{
    
    elementkey=0;
    NSData* data=[NSData dataWithContentsOfFile:Opfpath];
    self.metadata=[NSMutableDictionary dictionary];
    self.manifest=[NSMutableDictionary dictionary];
    self.spine=[NSMutableArray array];
    BLparser* po=[[[BLparser alloc]initWithData:data encoding:NSUTF8StringEncoding parsertype:BLNSXMLParser] autorelease];
    
    po.delegate=self;
    [po parse];
   
    BLepubinfoelement*ele=[[[BLepubinfoelement alloc]init] autorelease];
    
    
    ele.metadata=self.metadata;
    ele.spine=self.spine;
    ele.manifest=self.manifest;
    ele.Opfpath=Opfpath;
    if([self.manifest objectForKey:@"ncx"]!=nil)
    {
        NSString* fileroot=[Opfpath stringByDeletingLastPathComponent];
        NSURL* baseurl=[[[NSURL alloc]initFileURLWithPath:fileroot isDirectory:YES]autorelease];
        NSURL* url=[NSURL URLWithString:[[self.manifest objectForKey:@"ncx"] objectForKey:@"href"]relativeToURL:baseurl];
        NSURL* ur=[url absoluteURL];
        NSString* path=[ur  path];
        BOOL isdirect=YES;
        
        if([[NSFileManager defaultManager] fileExistsAtPath:path isDirectory:&isdirect]&&!isdirect)
        {
            BLparserfordata *data=[[[BLparserfordata alloc] init] autorelease];
            NSData *theData=[NSData dataWithContentsOfFile:path];
            [data BLparsedata:theData foritems:[NSMutableArray arrayWithObject:@"text"]];
           ele.maybetitles=data.Rows;
        }
       else
       {
            
       ele.maybetitles=[NSArray array];
       }
       
    }
    else
    {
       ele.maybetitles=[NSArray array];
    }
    
    
    return ele;
}

#pragma mark-bookinfo




#pragma mark-parser delegate

- (void)BLparser:(BLparser *)_parser didStartElement:(NSString *)elementName attributes:(NSDictionary *)attributeDict
{
   
    elementName=[elementName lowercaseString];
    
    if([elementName isEqualToString:@"metadata"])
    {
        elementkey=1;
    }
    else
        if([elementName isEqualToString:@"manifest"])
        {
            elementkey=2;
        }
        else
            if([elementName isEqualToString:@"spine"])
            {
               elementkey=3;
            }

    
    switch (elementkey) {
        case 0:
            
            break;
        case 1:
            self.catchstring=@"";
            
            NSMutableDictionary* dic=[NSMutableDictionary dictionaryWithDictionary:attributeDict];
            [metadata setObject:dic forKey:elementName];
            
            break;
        case 2:
            if ([elementName isEqualToString:@"item"]) {
                
                [manifest setValue:attributeDict  forKey:[attributeDict valueForKey:@"id"]];
            }
            break;
        case 3:
            if ([elementName isEqualToString:@"itemref"]) {
                
                [spine addObject:[attributeDict valueForKey:@"idref"]];
            }
            break;
        default:
            break;
    }

}


- (void)BLparser:(BLparser *)parser didEndElement:(NSString *)elementName
{
    
    elementName=[elementName lowercaseString];
    if([elementName isEqualToString:@"metadata"]||[elementName isEqualToString:@"manifest"]||[elementName isEqualToString:@"spine"] )
    {
        elementkey=0;
    }
   if(elementkey==1)
   {
     NSMutableDictionary* dic=[metadata objectForKey:elementName];
       [dic setObject:catchstring forKey:@"elecontent"];
   }
}


- (void)BLparser:(BLparser *)parser foundCharacters:(NSString *)string
{
   
    if(elementkey==1)
    {
        self.catchstring=[catchstring stringByAppendingString:string];
    }
    
}

- (void)BLparserDidStartDocument:(BLparser *)parser
{
//    NSLog(@"epub info start");
}


- (void)BLparserDidEndDocument:(BLparser *)parser
{
//    NSLog(@"epub info end");
}




- (void)BLparser:(BLparser *)parser foundComment:(NSString *)comment
{
    
}

- (void)BLparser:(BLparser *)parser foundCDATA:(NSData *)CDATABlock
{
    
}


- (void)BLparser:(BLparser *)parser foundProcessingInstructionWithTarget:(NSString *)target data:(NSString *)data
{
    
}


- (void)BLparser:(BLparser *)parser parseErrorOccurred:(NSError *)parseError
{
    
    
}

@end
