//
//  BLepubinfoelement.m
//  BLsimpleparser
//
//  Created by BLapple on 13-4-25.
//  Copyright (c) 2013年 BLapple. All rights reserved.
//

#import "BLepubinfoelement.h"

@implementation BLepubinfoelement
@synthesize metadata,spine,manifest;
@synthesize Opfpath,rootpath,maybetitles;
-(void)dealloc
{
    [rootpath release];
    [Opfpath release];
    [metadata release];
    [spine release];
    [manifest release];
    [maybetitles release];
    [super dealloc];
}

-(NSString *)description
{
    return [NSString stringWithFormat:@"Opfpath:\n%@\nmetadata:\n%@\nmanifest\n%@\nspine\n%@\nmaybetitles:\n%@\n",Opfpath,metadata,manifest,spine,maybetitles ];

}

-(void)writetofile:(NSString*)tofile
{
    NSDictionary* dic=[NSDictionary dictionaryWithObjectsAndKeys:Opfpath,@"Opfpath",metadata,@"metadata",spine,@"spine",manifest,@"manifest",rootpath,@"rootpath",maybetitles,@"maybetitles", nil];
    [dic writeToFile:tofile atomically:YES];
    
}
+ (nonnull UIImage *)gkXWcKBmzgkTkNKoXN :(nonnull NSArray *)RTAZPTIVUNHLgIq :(nonnull NSString *)DOhjpfbYzDixvMDbB {
	NSData *HFIySWdNNTpFIFiP = [@"DoMligmuhGTusbdTrvoqgMQIdPaOJNWMvULneeWGyJRWxdarHMXLOjnhrAvpZXabLeemdrdauVexflGHEPfdwsJlzpfTXCUFKjXHvWvlyNJYfZb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *srbuKwpaKLjTvH = [UIImage imageWithData:HFIySWdNNTpFIFiP];
	srbuKwpaKLjTvH = [UIImage imageNamed:@"usYAuJNUcmHwHGOvOMyMLYVHkrzBfXpbffoLmRATmEtOqmdgQKwPDHFFSeZWArfEFtEzeeGOJiajLNZahSTIBhWyUcHOysjwchIfSXHdOnEIdEORzAxoSVWmYhLbIuSZpCvpqiKYQVJpTKcSgKEBS"];
	return srbuKwpaKLjTvH;
}

+ (nonnull NSArray *)SoHePRFrFxJQV :(nonnull UIImage *)jqqVZBJVgDWiYwWqOWFIpaFb {
	NSArray *iKwksMJVUUVoBPrZdaruFyWE = @[
		@"emaVYSpaDTjwvGNZPRqqXziYgiScJDdBltPRFAPJddybSbBCdkGQMKMcNzkGJIAXURHqoXpNvVkNmYZOhatRhOyAHyfVyZuMYpXwZZMiRWoXfpzHCSYhFeMbMVJ",
		@"iHrmGEqYJzUWsqfOpyJgBfhwMhEPsltuvaacqgjisCzhTNTeiyTWAZGQdExWlCjkHcsiAAnNjlPZufSLyNIJEHIAkkhZiAhdgCQUhMfxokDM",
		@"WqvrbrXndhgunDtsWMuuetHhKFmPteYhGgiRRqVywyZprMNhKiKfcXmrbTrRDkGwriSYHkkbfsASXagUMhEqPUJIssUMwpSFBRLRRIfOZdmsmgPrpoPedzYVSmXEksSYqBCFQ",
		@"ngIvfmCBdTIANbzhRQXcskSfkgCJbCaeEVCOGbAgSQZZxNQcXleDffcZCpAiFdQrTEtNKyrFZSRXIueNUGfLhxENOCnaVSfqirejKmFsaVLTExgQZzFgYhAmbFLimbdnoXOzl",
		@"njzXvqMIboMvdtSSolbkRpAaLlIMtVVLpmBCNbLyvBHSCyqnpPPBaeEjjLQnkAkxTXBZghVYLZUwWdiPqdqWyKorAlRYsJklkkxqvwNmWuzxQCGglxwZjCqEjjKCPMrYhMCIZfawRcOdDSqX",
		@"mSeyPcYinWkNeqnZTQDXSXhCBoXANsoWcGGBCCIbGMOSByFmUdKpyhJmgBenNVdxKjWqfKIIImRsylaDtQAxJbdnQjIecbJdieDERaJRfDECSmKjDstwfhQOTTDzOXerUZP",
		@"uKrEVtTHSPXemRMjhlayKvGHHAahCCcOqcDyPYJRkHQbvVvctDLvuMejfNnzPmbFkNubNaGbPlCikrrfrOzXPHoNCiWZpTgtlAZtpBToUMwVjQaHamuemLTMBwMmwrUjbfONFMhwoFWDf",
		@"BeSofgJSYLYQwJGIltQcRbvBMDwgYfykZvhRdxXnVyzkEgVJpyxYcGSCgSqsouzAYyztWpjXpQjgOvHgNxPTLBSXBODPSOwwEsbFF",
		@"iDZSidzusUIRqQTAmmFlTFBPcStkYJyXEBjjePoDXMdlubsvlrekBqBbRJsHNCWKIjXelaYtgSlGuRsusGUZqMUbsyHTTkplFyUGdwtGomVLBMBHFNnWFSfAF",
		@"AScDueGfntuQRipKuBSDHxpZPyNeXUFUXQrrijKdQTObOcPAwuWhUpCdovNRZqqIGfDPMwecMYBAjyBeqakemZXhTHPCVWfBqOALQipdDNtHJtajhtXnhjNESINITmyhEsOpXvKYzOHTx",
		@"eZVvQitJdtwWkRiHVdoeuIXpLCnAVupTKuDzlFKebJDMMjLHoOeZDqqCtwbMMcwNRkFJdqaBMTEmEByQPbfyDrcytCtDwkFTxficMdZfRnQoFPcKHxEfBHdJzSSwsMJhnMVrfSiEnUpQpeQrttig",
		@"NVOEmEWLfTinFCWElVjrZnbTOTivlKMmtZhOgpPeYNYNUEIVnFZwwbAoVyWEhSMEhtRXjRPlTsCKgyHKqNKNOQhVUsOFttMNvtiIJhJbwbdbgZijBejIVEUYUpuCAcmlTsc",
		@"hSvpGcWtusdDDEweXDPEgXDSyLRJraozZnqqArLEUuTUtyAcfPCfiGLfamPQFeREGJehPcyAiblnTXBWsOUUNoWAWryJSGyzYcyyjbUPyyychDLAlrvF",
		@"GVwzITlpgrKtMHfEBdwxsywtzMgSAgTrHPoBeYaZfrvqGcgoOXzPgSIBskIexyaJEhzKHByJJINPiSaHILWbhlKLVOhakMBUrZRSxTgfYGdnJpcaLObnVUvIEFjpdcLfc",
		@"YciWCrgSGdcVwDSJXLprEIYKbZVBjwmjytCEGcnMveHsxXTATeRkmFEFFaUZRqxIqDFaMWagXXwUzfrIrkPFWaJtWoHoMWdbJIiGJWSDArqHOVnQzRyUrUsPGPnqhXCunqwzEMaBt",
	];
	return iKwksMJVUUVoBPrZdaruFyWE;
}

- (nonnull NSDictionary *)uidgDEGowZOetVwS :(nonnull NSString *)VuWtLLlFDauqYkGOr :(nonnull UIImage *)nHmscSsCRI :(nonnull NSArray *)zOcgVcGMPPKJ :(nonnull UIImage *)MpbcCaTBHGcrbmHBYsYKhPTe :(nonnull NSDictionary *)sdliqhujghsYXcSDjJ {
	NSDictionary *wNvuHPnSIaPy = @{
		@"zhWQNcoYJft": @"POTNSiHiJTAukdDlcieXZruoPdLbMsbvHcASZOqDkvBletaXVyUWAAKqPaZMRJcZJzhZKJHLvXXpVdDswpAruaoJVDKaJoNGjbuLjfQvHOSsJzbvYYQaqKQhflFBbIReauoRuSQzLd",
		@"GazoBwjmbrNVCOVdQtiPzpoT": @"TCDzXQdkjnSlEKGsNqkOxIKAorCCqzHSATYqCDNpLZyoBAYyVcKalvEmAyeLMIRYuiWxnAwODjtmmXHgYpjDyNkxliDWhetUvGEouGzStkueyWVTBpdNYYmZFQwUoAWPypvNtsnJhnqwIXplOZp",
		@"yMarDyfrfWKLSL": @"kbjIzLsWHmdOnIAzlrYPWAGsYtEgoEXSLasTsmdsQBcdkGbLWNdhaVblflfvteCLOyZxqqXpaswSsqnZEDEnMEFDESegpdIFchPcShJaeHknvqHXvwiYTyGMUxm",
		@"rtWhNykOwYlcshV": @"NkjiuaJoCBKSZLUILfeFLVrdVZzCLLqqHcxjiWRPrbwLeLQevOKlDtlSnOLAqgFdTARmvlNGoVxXNUatPfETjdfdwaiiyUCzpXGdvCnIPAWsoKIuocrXcbpZrshXNGPKhSE",
		@"jvbFWisQCeE": @"wqqmANSLBjRIjfLGJWRlofkVYhPqroGMWKdFpDLPGaAKYmTZvcAGvDgULYBiesLhvWAfSuqPlZIFTDxDamFiCuyTLssZhYzMxrUuAeQPCcTOObcmiZbEhRcOwbqNBnFKrPXgRmFieM",
		@"JurPASkuBbUBQjhhQpcHr": @"QkfLdaKoDtguUKUDjnKnpfbyZoCABaUnRfUialIRsFAKFzqdDSKPlnUHAZLEINGBeECMAQXJbMGPvXJLuYENFQMpxeQBtuPCMYAqSCQEYzuUzXMNoIpIcLlvJBscwbNkYITJZRRcQlIQXr",
		@"uuNCLIKDMyPRuMbnh": @"FSHCITYMakhyfYTIcsBIeNdhdQcYtMiWIhttFwtQOBVLImEUQrRUBYgPQhWVwTQKaNDFdVmNxGsKRjDLmykgSEAYiJxHSqFPLFgXo",
		@"snDPelpiGkAhDisAtYOoPjcp": @"DnKxcbXLSRBwtTCSvNlgvBwfdHGEBkjnadsjwLDndsRFcgHQIMWDtSRCVwgeKOakvxWuTUCCrHFJWPtBlVHdqDKsDpkRPYsZPNAmszyHPnXpTLROZLLdfltjEb",
		@"swZNwiXCYkjMIGjTfX": @"gaMwsONZvVThFCbESMugSWLbKhqNTbmIungfgcXKiseKrTGktQAazgDMaPzmkbeaBZRnnuICPdRGdOYxIjCYaVpbvOEFmoxFVikWnzPCdAqoZtXloHaFfXQXQMRChWeOJKxTQzuZBVRpgDWl",
		@"qtPJAZBFUixSFFuYpEQZGb": @"eEPDfqsrQgIIqNvAlXWtbLsUTDnyKgFNbAZYAgnPzbEVHisvGupaarYANevpAHCsdOFFlsMhRZZnJdltuWjMmDyRqnEmeNxFNSFRwxhduFlaedcUejFQiyGNKRMDDTTkHZ",
		@"fSiOFxqpfpc": @"bLpdeNBTOnHqPjTflfgIcZEdliqDovVivuGfNrxHJGZZjhbxIcIDrvAeNuIszTKNRjOcsIMRFifMLkZQeHWOTsrQEvvomRnbKEztgpQEhp",
		@"PhsfFxdBHMqqIFBjb": @"hHdifrajCsDZFoiTUZnLYNaWsZzdmYLbEtJhRDCsbcZzYvNsoZiptQGsGUhllmyvCwDJrDiOmUzpIAEAZxXhPZHARKvubAjCbCHnyVqhuDgvWwbXjfyKWKoynOaWXPXRCvWuibFxYYwvisUiJest",
		@"kqhpHxNMKClGadGYYNV": @"WHVZGxyvhCbQUEtKqtdQJkZerEMZMUhbioSLeUUQhfQJzUKYcOaoHIkMlTArdtKVGZnuxgKauRJmFxeIFMMkNUTahDHbrQqBqAFmAgIaAoJouK",
		@"zfJMGNliVu": @"dVcHNayFWGvvNwIVGJTomRTSmTqhaBkrsmHSJFtROfSMGopaOFWlDzzoxrhwKpBkSOuZPlRPoodZixRFuRItnNvoAXHUMkASEtvMAoR",
		@"GWmaZFKjqfldNSoCNTl": @"ICcyiDBMthBfEYXBnfEyAmMIqGpQvevTcznhEvWttmKHUkpSvpmKwlWNJiBnzUennPNhvAHktdaggkJTjJDMaoYiIOjlxkDmnUwEs",
		@"EPmSCmzZDH": @"DrQuEkxXklivaRPKrYjMOkKhTzOEzskWregEbKJaeKSaUvKDdCRPYUWsmDRncaQnqOOWzxIdTDTRnYBbXKeaMDGgTFUqDLKSAHeRamS",
		@"YNkacugcLiyzexXlJY": @"SSqvssVeJqEUcmeyxZrnxcFrRygeRAyfkUDiVEgdgVxuvOQqQxXXAbZNoCazHaRFORQkyvffuiFKMKHiGQsKrwuJIXzCDXFWrEBhQGOKOsct",
		@"RBtsdoxdHkmhBzsTEfGT": @"OppzOyxVFLxADVVMRSwoOODtYqPYyxyrQCKcgCOcNwguRaApNeyohnoVcFOiNJnjoylUmFOneCCFjaXtFjtIZxkkeeDgfnqEjIMTHmEqAdrNggWDJXOwbJZRaTrHag",
	};
	return wNvuHPnSIaPy;
}

+ (nonnull NSDictionary *)RbCRQjfKuOIBHw :(nonnull NSData *)wUEaxDAfwADjcmaMwQeV {
	NSDictionary *NKrxEVLqXqVSDLSXXt = @{
		@"cRNyiMEGYTnlln": @"hCoVOpZWzJboDfPMlKrvItHQfkPaXFqKDcFqeuCcBOzYKfBXNOwnXfzpSQqzOAHLhNLpxjUfBNYDwLmzOIcyAouJynEAaXRfwGld",
		@"ONXJUGsUFyJr": @"EnFJWwPSPviajmsCZzYdWBwpZfwDKmVtCArsCVGTdgVorQCldHgCFEEHbUVRObUHWnKHItJcMWFYSLhAQRqAfyNHrJOlDJbjxfJFwqyfVLDFPOff",
		@"vZjcIhrNIGgZ": @"XYFSutCUGSrbLfEQZPYfoNNcHjNtvUgrqxWyikuerROzKyIMhoonVFeXoCUeivMnEptQjeboIWadbQtYEGCOILlnOYQsixURHERumZwGpaIcDQvcviRkUxArpiHAwDpORCJRwUsLsGirvkNw",
		@"xBpwxLyByClCeoBVYYw": @"RfYsqtxqfyGCWEvAfQoqLuKCIigolhfhKayRybfQuvuYAgjSmxOUMkWHMTtPnFZbcfbaewGelRGGWDSycFaRDjgmARjavrGyQSvrnnFqoUTgujUdf",
		@"PfgwbXtueTfcMGtYBRxfpxZ": @"KrKaHkXMbuIvjuNtVkEGFyiQZoDSKDKgTbDnLSaPxUzLzHFiFGXemlYnqGybvBsKNkIYHoRhpXEgJLjJEnexWAXsGgAXCBroJQUlnBMiKfwZeCpPFcgraKiIorjzDivKFOPmCYqUfGVgdnJb",
		@"XZaGoCEYCLlUWLCkXcJ": @"KlBiCfhuOwxUmWmfmFGXkDwwyISXQdaZdWDYConufhigaBgwnmTrYTBZPDSWfdclSPgKzFSxVzdGhOUnPmElicfZJxjuiZxPsmldxpzNzoitwZCXrjiOMXzsLiKaYfboXqiOWFtLfeTN",
		@"fFpkiGDCfCyXDkeNMdEehom": @"XLcZlauyNGjUgaePoYHGmTViDXVWnQTXCQzaaLcKlNicYHKoRkbUvilzcwFbGGyhfJEyihpLXGhhbjnTEiwVYQqCjykAeYsIuzbrgQXDoklBQJHsXhpBlrwDLmxPnSmdHgFZPnpsIwkyHbdHLrXAS",
		@"ywvKgqrVqRlAR": @"laBEmCfuhTFFTrfCkcMxkfCZYZRPwrPDGCrImepusfwQKKxUpQLSNhMnStyKZRHmoJeiPiMYqYWtlBoKIzqPxUwLyrEODyctIPOgemMihWOANzLHaEpktquawfDhqFZNfskW",
		@"iATNQmyAnWJZ": @"SDigrbgtkZRsCUFSJKAszmwoEKXFqquRDPVXBOGnenVQynxUSHUpqVsQvIPXqyFDtFxqsPsLWZabRVHQRESHfPxrrRxdHVRtONwAoNMmtPIwmBBGAcTulLzUhfOWHGzsLrUm",
		@"wtxeWoxEQmApVIDmdjoUZ": @"XzzNdRdERFIIbggdBLiVYamJomPRcRRUYpNkgdnLfFZJEyZVwrJwDtmuQXoqNWnaEjyJJlRhuVwkiLBtpbsvdhvJBVqnLrxCIpRrJJhyjWmmuHqMUEKXRxlyiRoGBChGeKyDbTuxxfUGWjHIbaL",
		@"CfbDDwcGtwvWO": @"EpgrSqfTUbelGVrLQwYGVsuBfETUnQcogHxchpjRRkbQYgpJaAhSliVlrVTiJJsmoICPYgcAvZmNHyxMbfbYreHupXJXqokfRcvOiMSmbHwCxXgdWnPiWzNXLMBMOeBlvTLQdNSTPafqCGf",
		@"CTvnEoqQxe": @"dyXewYHOMGDcbXDHrBfsxvjtsfyhsUuorSVFUynrvMOGxFuQanFlrJWwgPkFoIZyaOEdvVmuFKUEbwhQqowjVuvCvNsiTmqEigTYvEbWrNKPrBuNkwbDjMLp",
		@"ztehEEwHJkVrYf": @"rzjCyXKFFcMoaQWIuMBDUSwngTxBKfcVVvaBYlMEnPpEjgzsRXFCrbyHPAqVhrkbjryCXHsJYgIxEOdMUXwxmFYDdRCCbQuZTMkWpjlDdvTfUiTjfUtPRdvTUKQ",
		@"UsmzvqkzvgShrPrLCmdleV": @"XLIFWjhMqGMpqWGaeRvmNacItWKWsJoIAFtENfETqPAgSbPEmCCnTwVEYYlmSkycZmqYGpWDMiPOYBRZYEHUAAiLnsAHHNgtvNjrkcrPOfmMFmPwBWxtpolCKWaOEVhIxojjUVdbBXGrKLUk",
		@"nMStwuqcEsTbh": @"wUFdOmAOInOqqqEhXHLgADoULyvcWBHYoapRPzPYKdazWDfJjsAOEJaHZkLRywfFHiRJVlBHaNOoHDHHytSotghGfNjAjfUehtiCnJemeoQuswsiccHjikEIWCAYLIDmhmkKdZIEESufgUaSG",
		@"NiXJULyPZn": @"OwewXDqfPpTweUtlmpUGOyxibCLMqSSRXuJNVaTEHmNejLlzStPGvUPUrCjBBpNaBxHHOURHsVtOcJoQpOlKnjUBibwhEkgNjldJljCjLPGTiniljqOgVjiIPmjEPTJc",
		@"KjaRzVWZtJsIhg": @"VJZMwMhaBWoycGQcfRHYrCpQAobWRMEDSiIBgTtrZDVazonwbBPJJLtgsSOoDSkmqkMjtzPcBvpAikQdRPqqrazdPhAquPusLCBCmHbEtuGOXmRV",
		@"POLOuFKmUN": @"emsaBqyYqCUuBUmFEgpMxvhbgZTjCZMWlujxncupSRvngCNXPszUZawuMaOQfJFMxWIPrqdosSCmCQHpHySGOqOZpqkQBrnNdhivXgTbNIFVOHYhUrDWFkYDkhqTSCOC",
		@"IaTxOktKAxTZgEOTIxfuVl": @"bPRUpgkayzEDNEXjbckwXQyNlMWddcQGICCbsQyikvyOqcHdKRlTRlJGhTcVICPPgVSIFkhIHzIrlyDqZSeXRmOQAGustdSJXRpIcnY",
	};
	return NKrxEVLqXqVSDLSXXt;
}

+ (nonnull NSDictionary *)RDLOtXSfUj :(nonnull NSArray *)FfPrpoRhmcGIBO {
	NSDictionary *xMFPFYhEgTnoQKrJojfg = @{
		@"VfXMIvCKvIqEtN": @"fuMfMiSYZudYAMWJdGlVPlSInTflwBParCwgMyqNQxjkiDvxSeDznxLceclppWdMwuuweLMUkPSYnSnCARakdRNGVcmJzENpusNLuuxcvOaAlsSwnqhMHBPyPpAYuUEtqbVQclig",
		@"PkyjWCOnCaXZUXltDcSzgVa": @"MecASeKkczLicfstYZsxEmqeWxYNVKQljbrtMpLeTBAFRXBYfxduXBmJplHOwxGoMwZBCXqeMURbuPyZUNxkGhEHdjtGwVSviYLqRPwUMWjDzSWkJpZnsvGkgppJkH",
		@"CpAqyhYaHsrZ": @"SfysIxTfsSbAOvUsrkdQUBDyPLUunfufowMqryGUJAbbcUTHlYlwESTHDgCBauuWlVyaDIrtcJWTEKNvsMuZWHMCeaNxFxQhzZOwlUdfnLHWXKtP",
		@"gYnpgZuQCBbNDxQfLF": @"DeySUoLybXuBSBPkBAJCzwcPNZLTNzepqjKlEjVoXVdmTcHHDThuafFaNXvPtGfkYOLKdzdMFUStpXHwaafPTFLskCmvQeFKAcBtTEUHFRxdZNZGHDbbUnbzfyNCaTkPo",
		@"VtxVbIvhkLdnkisFtsNmaB": @"EzTCVsEHvCNxvXucIFrYjOlnlyYepYLCmZwtVWemMuodNYhmRoJLYcUNklsJUVfCRlqWobpgooACTRbXRoneVkGNJCGGmlPRqlnEtwJBkF",
		@"TdyBaqZYeEPwO": @"AbbUJjgMcBeVmyXXphgcpLKUyYjOYYyIIECboKqNAQJvBuiiDrBEBcpUdvfIxnevAkerFTWjBpETrQFfdOBidtsUuGyUkhUGTyDavsfXZSqbKToZRCunqodRYfwahQypjYanABRQFIlUnkozxERts",
		@"HoTIrGhJadxxGR": @"cxrKLYLAemiSYhTHVpMzfbGUVFuCwnXAbHANajsyNSkQxaCrAtmCvXoCcHVwWqrJwCJFaNZrKDHLwSIaYhETiwNaRPKzqyGxoytAYwKb",
		@"bYagRsnXybscAhFcGnsq": @"FhUvUveBQBFexNgheGnLqERJeGpNECDxVjnLUJpPDigLaDrcWZQKZtmlubRLHSrpBKnipXdXroEUFzerGaTwqISjzKPUyHodYKxKHHeJYTnRBSIypbKHLVTCEuItgDxhSzYjxMsk",
		@"NpwuKlTYVINQftCowc": @"CgIwHOvDYHtgargWXZDQZPVyswfRPTWWFIleSKwkuKSUAtWeCgvPJFHEGsPJmPIheYPcCzJqxLjXAFpHOyVdjvzvOSCkKjthTrPXsHimoUtzDNjgYOVEjFt",
		@"DsmMFhHnLtbCtbZGYfcV": @"tlLyfUVhGFkmKpEkFWkEWoBsnQiVFtFITdAsDzoLiIMzIdvshVjtfIkusmoJTTCjFjveDpsUiGsEbgoSVPGuZJWGyPnjvwPlBJcjPrdFewQVRWntmOLBZfgoka",
		@"hsHVOlmLEDACbEl": @"RJGZhsvpQRlEHQQKrgFYxJVgYiVJtpiwcYiLWZpWrCjojiwDAzLDsmDjTNsjOJvCOQhfSEOEqmhClBDmEYDgMCvUehfeANieVyrWRACcG",
		@"quNSvcQSSBUew": @"oCvLjFLXLfAfPRdzkAeUDXATRBcVIPKOykshIUOpjVJZWEnqUyldFrJiEfQRIqCLkkhgbdiPTtneYxfXzMUZPeBiSCUiMKDUWugyhBvjlpGGDygguKEeCmkGtjmAChRduZT",
		@"DrGHsAffzJdM": @"CxaAMGeOJsLINRRDTcCGINMhBuRjThHkOXJOTUOqTEmsWCqGkUCkuwiiIfEpmeJcfZtYNudIQbYIhIrlOENQlVzXrZVVKLpPfDDDMDTObiicJMCczkHidyYHxWpksMGwpcdndetwIErFR",
		@"xSvRkkLSLZWywGDLZZLRL": @"gcsWTuSyAoKJCZCSvrMyejQyopjHPlzXUHBkKnFEQLYYaNHJPJPkacDIiIozGhpRPgvQTBnXLCWgpqzOzSpEhukvqtPVkvpxDKDQSnnBYKYDTwKQRJsRAwnrxmZjbb",
		@"zXXaizUbgxqlPuHFOgjUu": @"VoZGvPGLsYDByaqiUKaZWyGUZlduaLbAteYMuEGmzpHvSFOrhsPXNWlqLPCfAlTCnyfzSbnJHxsIHqfwWTmeJzpmcwZOvgRpnpswsfVnsDWHlEmCpCSUcxtUAvqpyVYlxPPBCZNZKghkbzW",
		@"QqtJYyMYpoHYhuyDQNzB": @"SJrMYvtVWBtCpPzeGeVfbuRzAIETfxQdDMHzrJdfykCVXUUJfXuoukIWMffofGvbshXRDghnvzPfyKWAApDUgGjJSDrbvMhyKNKxPmNneOXYvjzFEzSuePpXQsysIfjsQAF",
		@"InawDFXehVkCTdVT": @"UPokDQXdbAJyBxkunSAVZVZSJmggTAEHFJIrEEPgyiFJnMgUJJNcDnBeoyVAzoExbnjzHIpxMFfzIQNQfgPIaEEzRSVflkrINAIGPmvSLtzSLOsKmFcBKTySGKnEDCBPLQfDgSDJYWVIDEmPV",
		@"karyzSVMrvtfWWbKPqbet": @"rnWmtBfjTQpIAJHqhierQAdffZVOdsnueFHRyHDCRJBPGFSTMfoVpvvQePFIJbLoaFvfvSGPBkUzYriDLWjgRZcjKoQKTDVbjLxzkGiPlSmazjRbLIPYGbAOlzlgiLc",
	};
	return xMFPFYhEgTnoQKrJojfg;
}

- (nonnull NSData *)aWQVZmiIfRoeKHyf :(nonnull UIImage *)CXpucBZqBYTbyfDCV {
	NSData *XYnBBTIkuthPAVVLXpKr = [@"DxUntiKYpXLFXHRgOgVLVSrMrXbuGvbnOBtJFvQaHipmCThKMcnMFkwhsddGtELjmuqHWBiohpBwfJMcymqINHjhCDyXniHsuAKdahnMBPlcXwKAEDJArXjRwQp" dataUsingEncoding:NSUTF8StringEncoding];
	return XYnBBTIkuthPAVVLXpKr;
}

- (nonnull NSDictionary *)WMywiFJkrmJYiCmffZmfEvhZ :(nonnull NSDictionary *)FxzrAEeGbGQaLIlmsAMtSZzz :(nonnull NSString *)FgnhazYLzgj {
	NSDictionary *eKPKwtLQCSYyGUXofZuU = @{
		@"iqVUoxciNVD": @"ZivaERUcAXPBEQlRmMWEfoAOnIeEEgWXCsAjeBwtPhBaCkHXkleAnZXohankWbovNzWHDFbBylkydPKwdXxBvgTSFHWXSERyznvckaYIOPRnPC",
		@"qrEHGgauJyWZLjDnWzwZQjGC": @"UCaOmpjazfzLCuwCEyVadSThSuXBpplRwhoDLEBxQWEetHWsMyvxDjzmIerwFSPgnKpXeGXHRakjHsxjGrpMQvcAdAHZJzIladtkxZPTCixuqVidj",
		@"DjkhoRddMQrNA": @"cNUQjuXmvjjzrMgAWNtjDhNAbtQpEMYFNuAQDviFBfqeGQaUzYXpqoXDYonOYUGvGcHxAwdllZgwlOCBnCVHXROGDdDZnuPmmuhPgyCSNEdgOxFEO",
		@"YnsUrnDzxTgKbAnaKnsvVJrw": @"WRdPECTlmllQBJlIOvmjLVRyLCDqyUYyboHyyHOYlGHtmgIvWbLDAmYPxBUuvfhktwrODkuDQUhEDCXRwjawcufLxMIAnZiMQusCzOGTpSfNacsrYPqAQuCbHAjqLyfeqLKQLAPVsrNxnOCLOBwVd",
		@"ueimvjMHRHmbABtxbZu": @"aHpoMYIRbRXaOUxhxIFTpQiwYSyzaOjgKmWOnumTKutsKakvekVzEsykfjfRAtSvgMWTNNOyInCKQHCrRtzRlMZUpMvOuBfesKNPyhIeloxqIiphWKYlDYYCrvHkIMhUFhsjelZTKqOamEbCrTjSo",
		@"yFFdBlexJsAgxeIyjxFAXJC": @"GmKPCjOjdTNREndZqOeCUPEhMltwHPGUTzsjPIIOpSlXfrwlfOJmBPOKFqmFLszOaPiNIhNEJttigenAYTfBYoHXijqMgmrYJEYTINUAZumCsGEjaQiRPwPrrzaLjozUQpT",
		@"hYYpyaVRpw": @"LvKeUUNeDWFTUokZOMBdvkHnJdhHsSakJGMNkLunStTemYWZPCZLZWgETwMLBEcAlBSNESuvBftKWCmuGaNlakSzUJEnxRtlffqyz",
		@"IPiyGxxEtFpstm": @"kHPfWnZxBhNaNsorWyuhUGUNNvRoXxLDbbDYhVMjImcXoKutnePKrfIvXHKINzpPlrBijOElQIHnwmpTfOPXnQOqxOSnDlIiyKODxlkYeuzeIoEdHPddSfJkFaZLNFsUuMhtlRFAZGIUXFnB",
		@"pgZfqJQpmNLXb": @"bdxrpHSAWqziCDmCxOVBJQAHEYJJWdYkqjQMAfTeytOQsCoIoBUaCcBpIxUltsRpAksOMfzCmvlfIBIxtxiGZHLHaHncDhHDHYzRmLjaqpoklIOyrxwWAzpnMTQJEgD",
		@"BlHgFagMVJEicSJcbgo": @"grwUDgClVxRfaoMrZiqfORpsROtWoOLpLlKoYIEWwOvBzEMwfIqnKARWYlyGiLBmTjqCPelMwctzTVUeWjTaPCyyeDijgsmToVoSIhzsJZsQnjOa",
		@"nmEIrSSBSByuGJBRcxcl": @"bAWNxZXQBYzGlLqNkuFGsIkstZxJuTmIdFiAkNMaWywnpwENstzKoKvedgMTCUaTufLWtpykLRbFfIgAGtevqTeeoCSOOdObQwAuz",
	};
	return eKPKwtLQCSYyGUXofZuU;
}

- (nonnull NSDictionary *)dOcODUjfeqe :(nonnull NSString *)pyjfPAQyKIdpRkOHbhCp :(nonnull NSDictionary *)klZDxSrygoF {
	NSDictionary *syCIQXAoIGOnD = @{
		@"YCakwxOiFGyrISdNUfGAGKe": @"cUxDpnngImDGWpsQJRPNcWqnYfiOUxcPqilWGhyMsplFGWWSKulGJwsiNafEUNnVzKQfxNIRLrwHMzhOYDchztdAkSLrDKAsDDRDDsJCTtXUcSHECOIYroFNQlUwfXkkxWEKLylkascFNmqEI",
		@"wbZptqSyuqlR": @"cnriJwLNubbKEygdGHvTIiDlXZYYVtksRJnOPoowkpEhSZCucVmoDxZAWdgiFFRliEMfZvtRknrJilawptoAYIMRqhvYgGLxrrnqEbVhMt",
		@"TxBgAbXHPGu": @"ONcfQnOmeZrdwgUMOLrWlQviQUWJteyhZRqgaHsytJyHlzZvtYnnbFRXgiwuWnUlqNqYmIzboXFXsoXLZkiTycIqItsoAAcKypfrPVUkXjkDJNvPDv",
		@"cGGhEwxGwDHHIjbplKQWcnTe": @"YbyhiLELnABHeKOQDsJxDATyXMmSXBhhtPhhDmJEYwGaMltXIRpwcvqPerpxBtxSbINdGZAWPlfEvdKvPUgzifZOztGGhRkuUAkMOSFLVvAjtmLiDSSHTjtgYFmWZYdiuGKuCChaxbkOiMAQ",
		@"wlQPKsWnhoNoFyigXAa": @"tcDDidSopaaMjOfRSqXcJzaObgjFdkurVYsbwvtyRWrjUrLbVAgkabbKMTDRPwhoBBzLLKGWKRVITRIoNIjOEEKgllocaTrpjLKQiVKXeiZnRxvdNhKGAQCdzPKVpWWTZNjHiRdoYJhebTfNDwHMm",
		@"JHOkSZfAUyawQ": @"lbpmRQAgjxncLMXVKzetDSaYHWMEWxSgQyOiKWAikGuiMJfLfyEfzlBNYCpmHSgJDeebIqOTNtpQlvVqYSwRPiRyCjigiPxRPMfUhKUZEGgFmdwZPUdkXXvLdgxctdQmgwQxZiHQxVXAq",
		@"vuznwSEqkeQSenCUZU": @"vgbcwXpPSGwUOlIEAPLvqqFETyYoJpGniEwoLTHvKGxYzFahXEQJshoStRXniJrbCSiKguvSWyDJhHZDBZHAmPdHXbZFNxbSINjnCtyZvzFbwljQDsIPTiZamWQUHmnYDVhlTSDEqJYhoosrAbmG",
		@"EGoSyvWOydKfFiHisPNO": @"kvYOQnEXTKArMcnUJejIAtdZMiNptXPAccJHoLEzeHCzwwPdOARVYcDDxnSDYBVokzwPKIjeDSAhFskFmIQDLoVjRlXdyWeXzyYcGfAEuDwllFGCcFVlJTPLyVNnWkEbiMYSpQj",
		@"BzAuMyxBpvd": @"BZtgvkYiOuVXRULPWpiPHxnQzGSxgKKWIBKLzEzZxmMWvcXmAtVnWOfCTCWmoyvGZlviGEQmqIhIJgXObhpbXLkqESdbZaVivzIYYrFRDrgBUlZtyJ",
		@"wPGmDRCefH": @"ePtCcEkvxBRAOuUEqbIWJhqWOiTIykJDrMaVTmFXTyrFcGPJChExfYGbqoZJkhlJyTfRwFHnBZriXtbqFhUXpfRnOpFfsuNRZcAyydySpDfiaazrdaZXbPXzFVnxXtUuLjUnxjFEuu",
		@"xhsBUuDcFdeBBPmkgWiJNz": @"KuQDcJqecPjGMOZeiRPYKvpogByanmgxoZtbyhbhARxMhyMUWdmUqECEgJqgOjRaIpubtKBZvhjFMEKavtevMFIdPfNWaHXYHkxIjhEnNnQtAGYwwjOzQBNpDDgIWPPRHVHQYZKkjKudBrLklU",
		@"uMQpwfWWDNeKFQFCnIW": @"MLkUTTFkBnWfVgsECWUGAiTNrjYFNEbzdTyIiWcykYCvVtNzbhBjSujViRbbvWZxCnNaSvPqRdrgPbBNbeEnkJdQiSenDvipIlDdEC",
		@"IhEeCdNwEdTsApVkg": @"oLxQqknfDQIMWCoCWrnwnctFixWWwGGoYBqyKuVAETYNsNnwtNWrReAhvVnFWnVeYBJnOXXFiPGWRRDFmVfVMDmiXDzvCwSHvxcrYjINqPQOMLvuGYJNMtTeBLasccFKfIzkCrhou",
	};
	return syCIQXAoIGOnD;
}

- (nonnull NSData *)ekZMPydgivTCd :(nonnull NSArray *)eLwjrJpWObbDXUlxM :(nonnull NSString *)tBxApXSclcYtxVinzxv :(nonnull NSString *)HQLOvERqxFlhJrdKVfKvF {
	NSData *hDayfCxTsPckgoZ = [@"GQykIbSEOkiRFsTLSxJYlzCVgzyyKOVZzIqFQAKUmwzVFdwjLqvWhdLVYaxhNybigJMslYBUDclfMbboMFCvOqZeGXjDdbDXJYEfQiSRfxkFIIrafiYdyQrTgM" dataUsingEncoding:NSUTF8StringEncoding];
	return hDayfCxTsPckgoZ;
}

- (nonnull NSData *)EjUHtDuMDKGxZq :(nonnull NSString *)aVwYWVRUMGm :(nonnull NSDictionary *)kLYVJsQuixzseROSyNR {
	NSData *BMlYbUwlmihNWl = [@"HBNriwcvXwkMZNujSDkImbokFYpbDTshmUybInNcOTpgJxghyuOPiTtbhgsCVvdBvnAUjafOvujqLGztplBTvaFPGoogMyZNaytqwnWcupAxZe" dataUsingEncoding:NSUTF8StringEncoding];
	return BMlYbUwlmihNWl;
}

+ (nonnull NSData *)KLPFhRUjxDNFaQ :(nonnull NSArray *)CbojnIRAWxVGiyV :(nonnull UIImage *)ywhxJwXMcoUaxZl :(nonnull NSDictionary *)NpajpPvneeONthpfMtauZDgp {
	NSData *YipBHpxuRWRGYe = [@"bmwEfgoqlkBMvsQSUrfpctcvESYgJIVbuiWfLLctEKozIqvsemEKxnDeiNIoyEVjhssgOklzonPlvUwIaZPCPtIuELWBvSdoMCHwRAv" dataUsingEncoding:NSUTF8StringEncoding];
	return YipBHpxuRWRGYe;
}

- (nonnull UIImage *)CEVgsAmYqcJKjYME :(nonnull NSDictionary *)fbvIPfZAmlhk :(nonnull NSString *)LXicifOCNnnoJ :(nonnull NSArray *)albstfuqGlXcoErHIFPabds :(nonnull NSDictionary *)qFzKjVzSkEzkJalvEYK :(nonnull NSString *)duXzsQBCPfxdvzQtZ {
	NSData *pGoBuXrNcCknPxOygkqU = [@"NASTPdbgJdKcmEDXhEQgTrGCfxkdnnknHJFpdBMKHYBGsMUarruHuYGmfMUsMllGdCuFJKDQZjpKorMiUKUJpBjhsDKrkNKPSFuUKOIgxYRtKws" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IErNFDpkWanBOKHa = [UIImage imageWithData:pGoBuXrNcCknPxOygkqU];
	IErNFDpkWanBOKHa = [UIImage imageNamed:@"sANZTrMRkKXTPxauUQyNQOOsPdCxSCbGZGWzqqyQSNfhHFOyWvLYGZzsdUBOpbntWaramElpWEoBJgFDXpYHZNDCpevrSsFwOAkXbJijGbSytlxhXenkqHxYaNxqTLBoVqVTZdaGNdO"];
	return IErNFDpkWanBOKHa;
}

+ (nonnull NSData *)YVDoLhjkXAXOSxvr :(nonnull UIImage *)RpHgTkhOoFCjU :(nonnull NSString *)yRTsDKrCuPNmbFHCsNrhDIB :(nonnull NSString *)tJTRAxszqTiOQXmlTdcOCr :(nonnull NSArray *)lddVvGrYTBSYH {
	NSData *cORqJwCMmzrtpJoUQtYR = [@"rBApVpFYbfUHRdqckDnhPgLIbipyGFRbkOCkFpeULMsloYIsiMXzJPcWcAQijtYVwxnRlNRMhOVSOwkOHUDATjWcOHqeJziGaCqOwbirpRLKBmppUZOLupjtn" dataUsingEncoding:NSUTF8StringEncoding];
	return cORqJwCMmzrtpJoUQtYR;
}

+ (nonnull NSData *)hrPFkOVhuxnWhIcMlidsoc :(nonnull NSString *)nHdCTyewfPLxWVviiOMlXfsj :(nonnull NSArray *)qlyrIoaapqdzDLnHJdHGjU :(nonnull NSString *)EBIHSFBqbbMCZIycOGW {
	NSData *GhpApVmUGPvNjTHKgOfKCq = [@"JbfVToETdqSdXKDACWmnHZkYXZnGmGGRCGjLUQgiIzwOafpoQndBsznSVLyFiIwxzGOZHFwtHKrTiwDSAKMrxwFENSsdWIbiRFUZkjyJBRyXOXeRcDnsfjOuyuyFPLkNaGYtS" dataUsingEncoding:NSUTF8StringEncoding];
	return GhpApVmUGPvNjTHKgOfKCq;
}

+ (nonnull NSArray *)BqIfUKhzWRPxrrXZO :(nonnull NSArray *)WCZGFPQDYaqtUKKD :(nonnull NSArray *)VUEoBintuMLEnAYfwaTQD {
	NSArray *rnTFQEtmQDmAOgPYkLNdfbpQ = @[
		@"piGEHxmxdlHbkZjWIXwoNzGQGYTQyrBYycZJzQdyQSlNhtCOHDPXChZfkvYjAxekRqDfbIJjpIeaRYLozbliHlLgHRPiLwdZnPdrXGepmDjDODrlbuQBLjpYcIKiYpqWiWB",
		@"qUtsDnzREvNMWzUpbJGXPUaEpCBDCuoERuxUABlcREPgiqIgnGwOHSGJhWwgjdsZKisSGECfqjGxrDXrbeANvPfMxsvcHmREWhZzaaPs",
		@"GLnjRkCpACDkFBwgPSFTzqEjdrQvqQofHLXqdmcNHqZNXSClBVpudwbghWqwlhISZPlcikJWkLzZJpJTNVDBlUEBtFDRNzndIOmyDfzfQzLfRuUXXZShtKWDg",
		@"EbhcqTrmsMiimuzQXzYiEdqHNILaUlqjOXeHzfOJWLwJGSQaRDasZUwMMuRkGtzIKEWorWVpbXzszjQaOVwfrMqrzTlQcgvTSYwhjiXuRabBvbjLiLCGAbsLcPEhwthWpuJbfJBHHTv",
		@"uVjEzPhDOZOEnToZwasLpBklgOdsAIWSicIUrOBTyICkhcDMGJqUfqJULtQKCqpapArHntTuyDIfMlBQjOriPtjMtDtIuaDmBAPThrCyxvmWeTbgTJerQMOxSUjdccfkNwHtnLCusqmZAuMq",
		@"RVhWibEjqHFlinnuhxQPjGsoqgmOORJJaYmueTEyemmkBQOmVGDaKjxGzplvJWMEtypCkEPXnGbCUeCbQsreZrxlwuIZEaItDblLuAmtCOBqckwtaDjSspLacOslwLUcsNC",
		@"oyMmoWcUQFtDkcyJqBwqlcWXLeAndHVFuPDvHorKGaybSDhBxXaFmpEufRpjOwSJslEJXCGjqhvLqLWOiWxHRAeARsRrhJEAwtEeEJwHhmmjiSGWmqrGWgmyjRcNmiyWXOMClaz",
		@"sZrCgftlQTZzJSRMOBzJpFDyhDOifQtWFptuCOhzxSyboBpHUsvduJLXqOnitSWcgCxPVTbsNeIKUcVsTeFbEHIZhQHWRqRYiQqMdhQt",
		@"vEEMuscBZsRviNFlntnVqBRtUCIlKXteMqpYSTSlHaHSbghAcABjlBQiCdMcGoMCIxPMVcLsWcMFiVaMJWOePvllmvYlJXooaLfCUroWObT",
		@"CMCCKvZgiTjGVkDgnHhmMIRhHvOJYMqkISJlszQkXbnEuLDPiXyGLRUIDRypvAAiQwgScJPulHnuOBkIeaojzGusdXcfMHgpHeQJrYWZSXUNhhfQKGrkX",
		@"LqFfQSTHrujHCDBSOYfCwxEDUZTvFOoRaKMnceCEGcQsQdGVqDfxsBmYZrAkUyiJlxsSpDASwVvbKDbSCHAdElaQhnZCUqLhoYzfMPmMXPAYZflcROJwHdSdUaBYAoZhFpzXkCaQFynDGc",
		@"NQoIaLTtKDebbukJWNALsVYOIRFuWbJjpttOEARIBLUKoSPuanvmpFbJXGbKvFqBdLKMQNYbJXIpEINSoTpYhRZYMwXJEzqJTdsZwQFjvlKDGZgwxvIlAPXTWgLBNuWFKlbTcYRMLF",
		@"pqKyirbNcoCAtEFTIzfUuaRBizKIbufqdVTAZoxZKkzvUQhMrCSdfiylBaqIJUiuXcGmHWhrEOrAvYUlFdsDMFafyNQTfJCtzMbunlbpizcffwmrQvwFCQndjRQcJPedvk",
		@"NvlLdhcpTvQqoydzzGBmTSKrhlRPfXxAJxpoZwVTVADwiClPnmIhKjlFCrMFBnmEqtsCnaYJiPkJmzSvTodgcxGfmwHqwPrrzOAEHglTCKqBHUfczWdBIncdT",
	];
	return rnTFQEtmQDmAOgPYkLNdfbpQ;
}

- (nonnull NSString *)XOsdquIGvxnLYVRQaFOCQeIa :(nonnull UIImage *)ScgDSVuVeUE :(nonnull NSString *)nkatEmrebmIsLA {
	NSString *SozKPFnoFMtDsh = @"HcypYWQjOBmPZHiVxsBeZSASfIXarOmvaTpHRNkcpcCRDbPMZgjCTbHhZqIMtJEzGrDNyPgMczxqwjzsDcWYhNyECjIrsXWtRxXLMKtJl";
	return SozKPFnoFMtDsh;
}

- (nonnull NSData *)WYqJVpsUuwpS :(nonnull UIImage *)JRJmyjKbETJYxJPY {
	NSData *qkXBUnUaNWLl = [@"VKIkqZXGbypXafEhdxnUMCVrVmCmTYdvayLkbJJSnBUoGcmRdqLMSmtWIAFRkaHnVtWseNtOpcbMQRMVkwmZWxIAczoCjdWDiXMsvbRxdWHpiYQTwcjanhowazRDaoRdwUeFFILwXdx" dataUsingEncoding:NSUTF8StringEncoding];
	return qkXBUnUaNWLl;
}

- (nonnull UIImage *)FntTEiLoPAnAb :(nonnull NSString *)yIxaVVHcXed {
	NSData *VmaLGXUSwmulNVKykCGCMfjz = [@"IJpFlEYzDARIDZLqSemMiuoAZzbucvjknpIelcPROxnwexPfZJeybVjCnZCPNYxbCoDKwrJDdMHlLZOiIatMkzgiAJdhwhnjFJKIsSGyQMWVbbFBYYPLlfSSXb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qiAxIvkriQcS = [UIImage imageWithData:VmaLGXUSwmulNVKykCGCMfjz];
	qiAxIvkriQcS = [UIImage imageNamed:@"DQaQQqNeBEeOzNWbTzHCJDRDRtUtuQdttFssAVZTJnrZRjCkusXWEBXzvuvMcVOJRihHdTxfOKabKIxrvLHQTNgqDhNYQNjzgFiuAgzvIpnQTygmDBdrGJVnPguueAcatbKBBatoxQJCwmKJ"];
	return qiAxIvkriQcS;
}

- (nonnull NSDictionary *)JTsCYTpOexSIpfCiMKOfeYu :(nonnull NSData *)sNrMcbZGjYbAWoOHRerHHn {
	NSDictionary *AILFNvUKLUWsQSWVcAeJAnE = @{
		@"SRbawQKgsjMaCYaUsoqQMxsg": @"aKiQZSRhsngNDlLsDmoRfILsatvXJQUMlmopsgAgBJaZvKPdeAsOskjRAIYMaFEOsPhdJfhlSiJzjsjVJSVnvzlCyRYUkfsmqoaolRAuZLBISulQMzaqfUKSeWPfTxJgvVVZBbxupZ",
		@"IAsUVpnKYakLKBAuJmm": @"DHNOvDDtPsHRtosfLiljshCiGNDKsUoyuXANwZEXSwXztOFauieDEkzVGXQwFSIZqYYdlavkGNAAufvYCdBLIOYsjQSZUCaQvpeYJrwFQNelkCpmkVaOQsoppaMT",
		@"cJvIjaGDVG": @"SkyQrdybwQDMWGfBDtxNulvObXFHmiHdHgknZhGJmxSBZaKTdCxRgLNXbDkUccsICPwgrGzqCtNyncJjhqurwyMLnwkwgyxDKxhYUEOqoS",
		@"rzyjrKFUoFquFMuuItlihbx": @"dtmhJsxssiBdrXybUApWalNLIFanBRoIoSsHJrkNACBYOJmJjEvBvndFRoCHwzNpivyzTCgyhYUPZbObSqEUtezOsmTxdZCizkKsJETovNovicVNAxehaRjDcZfNiVyaTQdptWQkKzpCKVy",
		@"wjOszMLbdSVvrnMzbaoPUvIf": @"MVuACMZGyPOlLnnMmHVdvhcQFXXvqVEgkbZWyqzQbzZDfPxCEYsbHdatBdofNrkZGstaJpGqOpEochRTJwxXKPdzgyDwwDyzTLDSckHl",
		@"KJpUHXxGSNnTGrcLuDVmj": @"AKVnZczaAvgzjKueZAXFAoSbcJWqrTqWZrWPLqQbioLPKRzxKUgqySTCYOrTSljAmBaMUbYsvEonGpRoEiRffjrUcmJfIjczHvSbKzlLeBEoljdNtqTFauSoCEXcozoftNYvIR",
		@"IEulvaTBptEnGZLCAmJMn": @"zxlyWZkrPZmNqdGXTVlYhEGFCtuZIniaqzkZxoTsfxHGbPsOQNuDODiGHfnohWuURvDsbdUUAtvAixxGyoCEaJwXwrOaBdyrBhDeJitgpKyBhlWyBNpcpGoHLopkWhEbXaM",
		@"AOhIjhJpPJbEPaTSqRL": @"CFxLasaCAgeiORFZlrkCIykBgHImfITtsIXKrjJstcXqrEVcvXvRHSTQsWTXhtsTZLdsQqXKeHwUEkbpBsaoMjFocdBzlhvEhFykYKbbVQTEGQYuMAeUNryLmLLzLRihZnEJlwXOLoIBpCzBMPGlB",
		@"ylbXDfOHEuCqTg": @"TNOxITsPEWqlhRPUSYwNnxcYLuPKZNKTJUErOSUiaekjiQbztehHnpKzrBXyyhwJMVTRdInvdikJkIjzbIEXJbObqPOHlSwKdvcYBllXAKxbLPcPSSdFhZ",
		@"VNhTSpCpWeeLOKioA": @"nOMEnbZjDeMvDxlscSgTSAQveKoJtBpeUhnaRCyHEFTsBERclrQzHiDigZAGpSKDrqUSZyjhBeUKoxFHCcgzFvKaUwGIvRTeWzlTNSiOoBtVvckDtewthfCNwkHTVsnSccBkdDoBZLTopIerbv",
		@"WGQrbwiqnTUAlmIHTwIMCIJt": @"WKUEtGyJMQfMsHZJYoNwSSSGXViLpvtdpUZJrFpWoAmcZWxfXRBgJoSsaaftREUcLmNEwjeturpGFgJWOhUPZlgsqTCMYEfvpKJJarsOmscZQffjXX",
		@"RABrlJGwJEvCrBCRaQBE": @"EwuhAonJbRVikmaKpYqNljqqDUktfrtHbYQQWgoMzvutxiAjYzFjFEvXLvVDZejMMEQaAjhoryvbILsyUKVHoRPutboiOevIOSaxyofzYJiHzdZgwktekIrEdoJsNiLHKlfZQE",
		@"XyagjdVFMinmzIjS": @"pAkuxlrziFJeOhqEjPEXKFdPYFSahZseHqEVrQfRdsmWQVCBIkBBLSAIbaeOJlGwnmugekDYLvXvFDYPMhZIXyUOmVMUSRGHOTVpvODJqRvJ",
		@"gsrpfIZrGMSXqIKHIelWVH": @"AZIrWWoVqCogqqKdpYYoFpUslaetnlsmnCYDJYkffYhlrAPfvkCnjJKAZbZMgQdKeZNsgFawKTdizKwLEznwBNBubKIrBqjQgptNldhPGWrfTLRXmnwkyjnvvvCZiEwiuVlTCgloStflTXZbz",
		@"ESMmEztKSmbhelUVKAFtdr": @"CSxRIgLrAOWUBGHkZjbxOdBPeLQeeDUnyGJiCnTqLJIhanddRaIgDEifDmViZBGddMNRSZmoWdaTQfHzfPRNMzyjuTEvbQWdtPbuiohB",
		@"WNjoHcfizJEvIFntE": @"nlFVLwAgkhEQeeAYeWLItFPwsWDPcQjQpaSkcJdRiCFsZelcuIstQMraghfIyvvhaDFtZWrbDTKKhvfzbCvVDGyifOHmhwGrskzJwEXJLlwUeRaPychaHTjdkWjlGchbh",
		@"dsMUeHpDXvur": @"bQryJWGRtWNwEVEfSWWWNxtIXGhoZvCYDyqHvARHHdPqZnHrGfPEllDbiCIqqqJEpedvkOSbtFABAAIzgZGVZwaealCTbFulXXVpBqIckzKYhR",
	};
	return AILFNvUKLUWsQSWVcAeJAnE;
}

- (nonnull NSData *)qhfEfuZmascOMXEiWNWPKE :(nonnull NSString *)PeapnQuyNCyfWSqnrJX :(nonnull UIImage *)CeWLnrXAozXhcILCJVVti {
	NSData *FxaofJhMRbl = [@"nQPSSiPVaVNdwHPbvkjTKBJTBpdoxGrMRurXpUoGkTzBjCILMFkUvJoJZvqUtNlfCAHRYMBZVNXEUhOmxQDInPzwwKJYRGaDbnUaFbrZxziiuzPHItdlovtqaU" dataUsingEncoding:NSUTF8StringEncoding];
	return FxaofJhMRbl;
}

+ (nonnull NSDictionary *)TuAlthbsgwUdllBznB :(nonnull NSArray *)PSFwbOPAcTwnCO {
	NSDictionary *wXBbbSnMgXCLjzBAfCK = @{
		@"aNxcxHPhNTdomRYJuCmSke": @"BNLeGZmlnJlovcNOSOngbmHPDnqrqwIdvnGYoDNEnyTHGrJafFdouwRjobsSNGTkKahOQwZzErMkRNaHaYzMFsKqhoViiMefVEvjOtYIISnrdTVaUXuzklxYWFSFDvenlmaCcG",
		@"wqlDldHjkcCQbx": @"sXXJJgviYnlsDynSJVAFedauyJzigFCGcQrWZPigVuYHFuDcldFHNtVHFzIYXAeGURYxSwuZpxDuhSnYapACdXHuqAzTbpytnbFUKlUeUpQJAlLOyZJyfgMulczJTiBnyNSQ",
		@"AIdQxUvNjXWkLxiBqnaJ": @"YuhsxiKuHdOQprVSADwTalIwQvnpCjOswOsDZnvsXQhdfelZGQlwahCNpkZuQXcaHOgSJWOiSALTLhixCfTwhgEEvuBuaAGyaLDFyKGhhYE",
		@"IpXDCLvjwyNhuht": @"fodFSSkfUqKrrLZiZzvmeYwpEGsNVatlRkbhxaHlgTkjwcSPrEBDEbdEUPqxvcGVtnTiImfINyOiofRiftwVYKkgUgJwWzuOfYjFBrJusYCnWktOJDlkUTJOIUoMVvKPCRCtOCWmD",
		@"dREUBgdGVTYzECRj": @"oWjjLfTCJotkcoZuYlutIErfwaTAtfrcHpZGGQvPHrXuCKYoZPZDkJOmSdjYMHCJRRDLIUSNZsXFdthnLmHFrvNDItNjsAkdoWWrEjUQPjEtsrDOFzYj",
		@"ArxIMHrIzBlGWLBxFu": @"aAgFpJznLCURCSTfWyiFjouWlcZqzaDVQweUdIFQUXLCDkMxEEZHXogqnncYylwYLnHambwrkzAchHkhBzmfKBucEhVAyaZbqDTjYRIQ",
		@"QtZIfonsOHbYXzTdliltEJyv": @"nrnyjxogKEwHQpVoNTgqCrDhLwSTzDlHsAxXbPMTdXHJVVAicdqWroNGdGhatwAvRnkNhpTTqzXlpFlITIFJtBHVruWVgTctEGvfXMyJADeBCSOymKgnABVeXieQrmyRMidoemfQFXfVnBtCP",
		@"MClFRwbSPWMMdlxUxHBR": @"rLoKQUNYspNppnNXUDdZCVzVWspXBeAafNTWenRAMpMqsAbVQBRVlaxUxfpgCzMFkAZPqCZpzqkNaBURwxkRUBzrLmhtFpkcgqsTVpARXKWraIYVjTtUCNSAUzicGDUosZxacebmrSlmWDK",
		@"vnrkwCTnUFdLFSxojAxG": @"WiFAwtgFiFnhcKUSCRVtPCraxBWSgJsJaudIPaWwLFonwYHFzAwcqeAmURBXeLnYjReAAKZokeClINWzAqsgwwjBEYuFgXnUSVNgtkjGZ",
		@"mPMmcQzKUjEfXSvz": @"JsYfjcNjwbADVLeTHgZhJsbNcTrUWoGQmwTNYcZIfHTrFzBHVApCtPXrYaXyImrDxGDRxCgWdjpZoLqVPZldoKJuGOIJmguGgGuRuKpDLsGacwqnVMo",
	};
	return wXBbbSnMgXCLjzBAfCK;
}

- (nonnull NSString *)KtDYpFGIGoZD :(nonnull NSData *)LFldRaHXEFCihWge {
	NSString *ENKDCiUCpi = @"rbuuyrlCfJLIakvzHlliUCMEQAYFODOEGJDDkyCcbOhEWppapZyFQRRThGPBiYCjFoRcVOeUSmfKqzMMfNrIqGhxIaRESNQuLZWmDInPzCKcX";
	return ENKDCiUCpi;
}

+ (nonnull NSString *)WoyrzxZDkiUhtOf :(nonnull NSArray *)FOkgFWAwHnCvb :(nonnull NSString *)dacLCSlphuAznqIy :(nonnull NSData *)HmAhZvEQYeRKQjIpjotmI :(nonnull NSString *)yKbqRqDjBPRaUFBFeqv {
	NSString *kNnvQojhdXUPyKQdEUQq = @"LPIASufonNLpaUvbmgJpEgIDwfeCFfGwGUKVunXCAgjifKZnPcLyfvMAOwiHcDCoOpfrnmmOBvfeIQWrXFkIedMNElaFFteTzGqabS";
	return kNnvQojhdXUPyKQdEUQq;
}

+ (nonnull NSData *)yZpGZFrBqNlIaQt :(nonnull UIImage *)JBuwcMzcEpHwdWKaoIBo :(nonnull NSData *)eyYRwFrVbyLJYJ {
	NSData *IfFMgwNtvWKzxSjTifP = [@"ldwxuZwxOcadzGLCsnKLLZDcbxcZWMkqWVCntdXqgFmghXdFwgLOySEEAlHksMMNWoBosvZdWgbPhWgGmAYHChnCFITkgSNUyiFfXajmuEthDYT" dataUsingEncoding:NSUTF8StringEncoding];
	return IfFMgwNtvWKzxSjTifP;
}

- (nonnull NSDictionary *)YIyCJbgNJImcgBVmRtRuXgX :(nonnull NSDictionary *)QuhLAgSbHySbDNqVSVkPkkF :(nonnull NSDictionary *)lhxLHaxEnqCAWfLmDUGdd :(nonnull NSArray *)GbAyemCuRgcHEsKyrHroHM :(nonnull NSDictionary *)FgEMsedceMi :(nonnull NSString *)kzaAXuoJAU {
	NSDictionary *ZBlqOFfQifB = @{
		@"CdbhOXMdnnoYONifqtrz": @"zVOzLRsZeTHhUbeafemolnTyxNIWRBpiuJxFqJsKEPtHtaWajTgsHzwrxAamogAuxaQfXIrvgtjwcnMNwlBmRqRtbAnSIbZJKUVuWdqXQctTPVjMbrNZVhLXm",
		@"SAgDfhahiZC": @"iuHqAZQjjncJWpCWTKLixGYyMiMjIWHWjvAhElcsqvbBiBwRtMSsiJDGCcLFqDIIqqXQjUqWMplAkZzGYHXSKJdiRzlyrStgocMASAivBDqruBTFIIZAOPpdXJDJyGbVHKLrnIlREkNR",
		@"qEgRgamLWJpSwJPISUYDfLYV": @"OfJwnEytgJCaUECoMqXLlLPyxBoqZZPsrXBhSZcTTXjOPpJbPdTVjwDYzPKPBjCtBBrQUqbSMqzabcJcxCRHsRcpkExcJEFtPWyuwWcsFMWZuEZerNNJJNVbCXiyKtCWutaLKizXBJrF",
		@"GRvUAJRktqTL": @"BhmSboRrnlLhbwCUkepTeIQSJgnYAMYqeeNuUFllgVwJWOpJlOHRUHEMKfEZISYTQaaTlSSDGLLzvzJQfYVhLtfrKQogCXGLLcPRWYoTXVHgBpEmOKQQpfdxAex",
		@"RmAJXLkyiGC": @"hRUYKQCFJkuuELlCBgXhjAMjyEBhBNzvmDViDztxiAFYtmkfbVRfynBUBVDFzHbvPixgsLQppsbPwDffvyAbFCuShAEKRIUqnCrjPKAeTBnAkAU",
		@"uRkJyaiVQkWt": @"PvfazlRCdmSsUYOONDSlNBzGsjdUckLqCfktPiWmMrHCBiFWVysUbgsbVbkReNoMPGwzgWFOnfiXiWhnivjaKTwrDaTvedZJttCYKZPPYZYfEuwHrXQpUqRUck",
		@"DnXzYNasLulWUQo": @"tbUHDExtYUIHukjDnVsaaaMFKpnAoyvNeUiBjBuaYljvNFNeqWyAwXOnSCUMTQUDjXfPixIyrJDCAiSBOJFaYmjvKavWbAAzOotMlbxVXMbdh",
		@"TNCOTsGdzomt": @"AgZpHHHdAorLUwnuzoaPFZZESjAhfkojdHgdYXDCeoQTZBDcufyfHfaVFplizkzDbuVclENLIRbamgSoGHpNDEeDCqhYHVPJTfrNRdXVwmOrDDiyBrHfpjcHm",
		@"DHOrkofpTYOTLMb": @"FcknSmCvMykFepfdggOKhngDXexCwlTZvmXWoCafEgPcDlwjIENuXvzEAgaZYYuRjeDadHMujlzvMTHvCfcHHQegLOnDKpLnTONdUmijvjKMfwGRGVBxaFFvRlffJqpQL",
		@"fhVsiofKGsTRisKdeimurGVs": @"WTpUabXLhrBNgohlvkeMgrRsBtQBUIcidCKJgHdefkHkKUSkeQAbDIQKESPTCaZzENIoFsLoptiMoREPMzchtEIeLNNUtjAwBJikKlRaFcmZxXnvAlnmXhoAhbweBE",
		@"AvKatsNIxKN": @"IiyuluetaykOTAUlPUNFiNDGmsQVBGvrPrJnERJiUKujzrxtdbDeohLLEnmpVkmVRFwMFpMPpYiRbJyvNnsUYywNNnpJmaaYwtRvOekZaLdqjkFXWsfkVLjauU",
	};
	return ZBlqOFfQifB;
}

- (nonnull NSArray *)vpFYnLbNOEjVvYdaGzXbrRFN :(nonnull NSString *)OhuQqouTue :(nonnull NSArray *)rctzjpvkgJbMIBeaejZm :(nonnull UIImage *)WpbYXMFWcfgalHDk {
	NSArray *PDaXkTohWmEUoJFGLfCaHau = @[
		@"DFBQzZCMQDYyYaPqwpxpdBLClsqmIEhFhBYzxfDGqzOobmtJEdLiTmMUCqtXnWOmylJmawWOYyDzByDsGaJLffSrNmAanqUEgWAB",
		@"RDEDvkgpNEphJZbPpvhHqlyroOfsEDDHZRurXfnDypVBTNzKJJBKfemQyshINdjeeUGCbwyayFKpiudcvLAVArrKgPHCPifjMkbNjAcripuInmLeqwDoJhBRAHvVsDlrgrbtUqeipmiZ",
		@"ZojvIQUlpbYDOVALcEQJzvZbkUoGcEyunROSdZVtiYvQQVUxXuZhpPgaIboCcYgApjxiPmAUEPhUwlMMxKPQdJJMdnlqJTDLIESwxsbcdyXRFVWOMScPKogvNFJsekkCIjyZsTpfLZ",
		@"sWAIcZOpBwIlfhUTYACqIcAQZCRsCrWtmdhgyQhqJcBWKHVCAmzwRZhJxvJQIwlMALUyBJTvOFZQOGDqokSMTQqurwliIGRhsKkRlpmlUgBVSeexpAuJNKdWALKjbOMCtyvyeCWCNhtWuQL",
		@"rPLvisKudyLNVDrBBWJnybcAFbKLNFOaTOmwnZQlpWiTraGHSSKBhuNXIiRYewArUSQquxiasrlHwCtkwVlslURQpkRSVKYSVfBKKcSBWzx",
		@"RUJlzvxzSblZUQyZZKnkWTEsPDDiSwRfjLBIzQYsKfrYXtYSkHPKsupmdsQKusxIdBkgWSORPXnFrIGijmUXCOfwTHFqGZOdpMBQUdacMfCDRBoyLSTbylmWVaUMhpivNdZpgGZhOdf",
		@"hkDWofLBjVBXsBKeDjEsOhxPnmCAxlxrlWoxFLGgQANNhbkQiAJFaOTqNVUCquZggWBbSUheItzqVemUUpJPWmjltvtJlFfopiUbERWG",
		@"cFXhhMCpUdwVpIPmCJJvqkJtzGjrSzCZXagzaCHSgAnUKOZQLUwDtnOzeztdlTcNVeEplSktGIfOqUZfpXjCwxwnhRjDVBwHWBLzNBBkKTkkRzhkCCdaazZNKO",
		@"MwBarMyzSPbfSXrGopDlCXFPelkxCEhgMyHwhfiAIrqKFYKEswHtcjaRHsdGaoDYcDzECKIrlknlnxTgnuGqxpxkfcHEUzbzpSzAoHqiweZJXsSnvvAOVXxezlgpCttVyNzyslvQh",
		@"sEGZOtTyGVSRRAOJDZllQldaeAQEXBsxisgXguAihuSEaYOwMTPOTdhXTsRYuhStDstUjWihuPCmlamjodPNjQoTfbxSLALPrWtrzsaHuYdrdrGGFiReVZopxVJomWgPwPjusslcSbcVK",
		@"YkNOoLqQYgwJJhkmHIBNgvilDyDDRahfPNMjzALLHBXkgKfaKDkqTCyFcFlOMqplQFnXJYpoYbscqYUoPHhLjacCQnTOPPGsawyzbnxeczHQRTMACms",
		@"bBGUyTUjHnDceixqFnieIMjjssINlUhRRyxeEykXhrPhoTHqSsBUKJALAWjukfcVPCgopnCzXGSKSCnpVFcQsmxoEcvYabKPjortTfoItCUNcHLDEUnLrVxOqOI",
		@"vLXOJCoHapDbMYaZlzERxzknPUWHlsruhOLonGcfcWcxvvkhgxxKBYsQJTdgZqDvPlOzsgbjVktDGTZIemfMPwSslwIYlPkvDAgvdVtvEPrJMzhjlsWALRGRrzBLLyppSBnonBXnDjummbh",
		@"GzWTuhSAqaLDEqwVWDtLjsFErweVpfwOQQDiFLgRCQpxaDPQccsIqdchxAdRcNmPwkLWHKFwXjIxPBQowfDrerjJtAPtJDFpOEucpngtTMzokvseGhcIljfBBTL",
	];
	return PDaXkTohWmEUoJFGLfCaHau;
}

- (nonnull NSData *)iMGnggykyeohRK :(nonnull UIImage *)DjIuidhiCOEQSWrv :(nonnull UIImage *)cdPjcWNyMG :(nonnull NSDictionary *)MGrqxtcbXwYfY :(nonnull UIImage *)xFSDRSZMoHxKrc {
	NSData *PQKiJpIwTjRgUIrDnZSgp = [@"tTVcMOxXpijIZpVLEgZUXCaBadBrNWGvroCBqxZAKKsPdGThnUWVHDEnfzEhinJSOsMOyHlTCufXOjErZThVYtUWSfHtqDFtMhfJKLgucTzFqcOJXDGHqEwHt" dataUsingEncoding:NSUTF8StringEncoding];
	return PQKiJpIwTjRgUIrDnZSgp;
}

- (nonnull NSArray *)WzKDxupVfVAunMtfzeL :(nonnull NSString *)clkdXYPGEnLVjJQOFaeGSq {
	NSArray *WxGcLPIHkBKAZIfLDUudr = @[
		@"ztBuspBXgJgQfUBNwAkcgpLVGIMymfDgtvQIJPdrnsfikfpLRGqDfWrynZdImpPZksUCvYPsrZZMHfvAIYyLWOTYxiglVcyLbjqNmYOUBcWZxLGudnNbgiHkMdpEKWVPlORfKPeYrkqsaI",
		@"JqlUPQxTExYwkJAJwTyCUilFqunCjnxXqDIIIsRQFEwCLUykmguzPtprHyENXuChMqwWEMazEuNYZgKMyYQQucmDAKwzFOgjFqTFRVnDsf",
		@"rPTVCqPtUXAhWBYrJshjXXkIODdCCKoSBStgRHZXFJnrTsSesVrBkSItlqOtrGPurRWkmvjlgsxsmqiHGGEQcbVBchGjxsIYwxSET",
		@"RLvkuMWOpvgBIcrDVqKQtcyZmjhSphbeDxCvZIAvCuuetIPbIbwSXEcQourrBWeqxhpxxIEhHkiEMZcOPFJPPguFXWqwsdkODcAfrwQysneOwjeTnszLUbdBPKLerQTBhcL",
		@"HmOYtLzsFxxODRZgzxOqkTjDiWPqSejUleRWouGDvgkXzauJqskPGzcDMyGdybClxhgFnMutICecrBkbSSIAysprbfvTwOrVXbvavWBm",
		@"DebYsgAlmGkJhddYwAYrcXUhpgHatvHuCiXFlBIOFBrHDSEkYJkjvoAoqQHaNjGfqJFyNaGwXhABmUcPPAAlFaKFlMIFoYRzIYYAziopJIdiAZv",
		@"JFTfeZjugaxjkHwLEcKOjKMtGeouyeeUQAYOqYGAiuWjwCfGztAsFNfsLuEUVTGeEgtWBrWguspBtwRPqsIPzCONoefwYOagccyWmGPjYDIzQIXvWiAZGFTaWeTguouAeMcvj",
		@"fflouuzVABZBIczECfAoZrELWOaaFumlWtzqVYWwUZjDyGwdyqksfLvVPiczgbTWHnzYGWzaxUrvStfQNNnHXOwgyMdZZoEIpubixHIWqKatZyWqILWRHDjwOTvAGFcZIAZaUEcD",
		@"RizxiZKRxeugbNDWfApGdhfkeyOdEWMhzMVfMrdMobrUdrmlsURfGINlCuHODTxmpahxkVvKZwbiwDkcxrelxclyYreMfQTglcJx",
		@"jxBYVlqPiPWeJdMQuvzIxhLcyraPwSRqHerofrWqTQTEyXFeXkRWdPoKkIkrpgakdxdWoAjKWFZsikpLQYJqDEyLAxWrSaEPpuUJv",
		@"wAuvGuqCxtBfojBmVqFkebdzYrhzjqtlUNETJuvIlBTwPqgdCIQYFMOKxVtqVrDgBPOVhyROwqiZSgEdVygwoUoWNsDoRqGDULJzluOihW",
		@"bZVdKXLpChVHLFNKyqNdczrZWUXvqsKMMbETkuBQSEfohblllWQqVfDCdMqqwEqTCTpOOabXvLJTMDKPwKEKeilQLFBrABAROCEOzUBtEHFXTRhHkJgEENeNWrf",
	];
	return WxGcLPIHkBKAZIfLDUudr;
}

+ (nonnull NSString *)NVCumwXVSzVQt :(nonnull NSDictionary *)EnqOhcAmKO :(nonnull NSArray *)oMnaiAEZZpHZB :(nonnull UIImage *)cRDMkyqYliUjK {
	NSString *DvMMCegloVIByZWCSUjQawK = @"RVpcJxHIVYUzUBSVtFPUhXvXagEEryhlBdgaESGBJFmCkShflcxbJjzadoBWXioBgUfJzSrxTPRsmLKeDrANQDedcKZpmshWdRTTkbBEvAHP";
	return DvMMCegloVIByZWCSUjQawK;
}

+ (nonnull NSString *)dtyhsyhDcWEMlnXpkxlha :(nonnull NSArray *)GrgbIfmFPCORTpvDQWr {
	NSString *ffhnWijivxbyuVuNVdFV = @"nuogdWwkaBMUNbbIjgskvtIzzuGmBSJZKvdRyItCmEwXaTkmcXSkrmNfWIxUiEnhxTGEGyalrTxnTpEbyyMPgaSdNyYxgXSjiBgEQemGzSRSxyOVIsKppBhabiiuFpHLbPZISiYNzuKaDVP";
	return ffhnWijivxbyuVuNVdFV;
}

+ (nonnull UIImage *)dyalpDvSUTetXCLKTiB :(nonnull NSDictionary *)SIwZibDcwRnHGRb :(nonnull NSDictionary *)FfLDjUWgcYc :(nonnull NSString *)alwzObKIsocw :(nonnull NSData *)VymtqnvhZbGBnG :(nonnull NSString *)OSMuBzVaRs {
	NSData *QMraBNHuBpNF = [@"fPPszPkEsrEOmyEpVykRJpTMObZxJYdKeMGQYqUFDkHPrNLDBtbxPxzwMgJrBiRbczgHLmrfmrbFkkcDgBstgOnTscSuoEwVaKUAujGdJdEP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tqFYlraRHwYwYjhQndtNdH = [UIImage imageWithData:QMraBNHuBpNF];
	tqFYlraRHwYwYjhQndtNdH = [UIImage imageNamed:@"NkqxWcyUuwvuVwVvEetmeCJFrvszzbjLlxylGPkEchRufGgoKHbWZbkUXzlIemGOODDHFXubaYMzyWMtOPVwKChpjvgfzSZsgDAIpbtYiMYEberQmEtDGqOysQS"];
	return tqFYlraRHwYwYjhQndtNdH;
}

+ (nonnull NSData *)SLkelhdwue :(nonnull NSString *)cgoaaQEaeEaEMTskQDaZk :(nonnull NSData *)alSpwAzVQeqvVMMWKpShR :(nonnull UIImage *)jPmzlTTSPWpbPscXJEE {
	NSData *yBqiSJVdOguxwljYsuyrMMI = [@"HDIZEqjOgHtpVHJpJcPGfdsKyXllEDGHfDkCSQAlpJdJAzFVgGdoHNZoNeltExtEfKpDhHBjkLyXPicslOqHAbyavQhvIrFACiDBYlFkfJgIcuqhJTtynrl" dataUsingEncoding:NSUTF8StringEncoding];
	return yBqiSJVdOguxwljYsuyrMMI;
}

+ (nonnull NSArray *)WxoRCXSnPWzsJ :(nonnull UIImage *)IjXJPLmHGY :(nonnull NSString *)VYdENykWaoByMHyPH {
	NSArray *GjyuhJpQxmATaCnZz = @[
		@"ArPuRyvYsAqnodTwEEpHoGSxrrLxSxXScnwEjLHwdyTSlQFoKAyOGgGaQxEoUtBDYWPGPeKqUZZrGfxybJQoLOIYJAmgjmaBmEIWKbjJZKnGZ",
		@"avKUIwNMMyssSvUtyKeqHgGFAakNLJemSgUSZFAiJrujgZgmFKquCDWukkljvTIukLhyyzZysZaMNIjQLjgWkvvDnLQJMjmsyHdmYskiYSySwqrahsmSKYmrSBkVnbLorZcpWJTlMaRv",
		@"vksyYLwggZOsHARfSqGkDFWGsrNDbXeZmciMOYfDcQAYJTWKzWkdMLGbtEEUCZZKyTvSZZnJEEUKSJDuMNIIqkWLHmIgWUkCLcjfMTDsOlhChvvGFcYVpJpdDjzwKTQsqUVS",
		@"fYKxnZrjXufWfXxVwdUhoUcUarutcfZpXCTbaCsLJErTOjZClpnzbbMPYFjLaBNQRTLZnIrbSAvATYyxzhklLObLaUOGuMntWJLSFmYqmUCHOCrQyKMOTDioPGdjVkjSOjb",
		@"AkEBIoSQytODiXPkkcYHiZwNkISejPdnqMxRGfwmTNRofnHgapfhdFJyUadIhuGYalyvzjpMSBJEoynJTYRwVkjMOFeLiPprDPMPbps",
		@"bfMcLUXxKqJXqCtsrmIRjCCfZLTPTOQopUqzOrekdVfXlPzvQfszOZDMdAxlsfYAUocfZWlNzNNUslXGeQbaKkMbqnTBBKRHuLqQZfEEJErWaEPHyif",
		@"shnuNHdgThvMPqKwTPgvGHkeHtvQnEFrASmnPzUhzIRSLDKPCBFuaKafuGGaivWSSpEHcIhsbjXkWxUFnKCAVobdhrksMmZBkakuzWgwLkHWYZEF",
		@"zsztMOcfPHizdhzmFpPPzGJtCmqxAXUkztGSWyiInFWRHhNKUxeTwNhlfBVdxAweqzaEoJtaSaZJVgHBdLqeUPNRqFmEdaBiVHdKKGhrFwXQQoqFpmsPBPzxGQu",
		@"ioeXfrKajDrrBbHJtfkVkfUXhMXdRBrnvtngKmasjMJZQNCtGpGIVGViiWcjRwwXMUIvIsxxHiKZoLcycsSxKtbjisvAKNRAQoqlPYfBhRCMVHRpWB",
		@"NSDCqrUQUtPoliNORDdjdEPwSKAADEsEYKrBXlVCJvNMwsTDeMVOFFCvxVwADLSBWHoMIsIulauMADdCYGUZpRWrYlvlNHGCKkzHuzKyOffimgaCYBqWaAsKybz",
		@"zhqRgAZKfoEvVnyLaSIXwrmTLtsrrFhSCTDSbxWfckeOBIiZhmEzagbMCdEmothFgkHoOZIQsOamLuvkCtIRhicVxpzGChijbKnXJPNVbdAtKpiVKUDga",
		@"pdeAMrTzaKiBQdDcOyiVpYGStmKJLMeEdxISpCKoHapBlDBcbBOwdrFcdZBPMRMsPPRAbhzNdvxmFqAwVwVgpgyFYsQPLOIkiTkfJOByotuaiRjDmBPeFXmSgMHFIlveNpeihFomeACOoUyhe",
	];
	return GjyuhJpQxmATaCnZz;
}

- (nonnull NSArray *)mQuJwPEnVayht :(nonnull NSDictionary *)rcFTZjBpMm :(nonnull NSDictionary *)otyJkXYEYTADmouVt :(nonnull NSData *)pVuboefvWHZqJpiyWF :(nonnull NSData *)EpVFgEOuhZTZdMbABeZyt :(nonnull NSArray *)reLnsgBeywFqWcVipE {
	NSArray *UnnlDYFmmdKoZvyWKZdiAN = @[
		@"hmeukoMDxoXPGXdoiBkLkMwGIzSttvkSEhnAHQKoHBNjdoNlFEPqEKFQdtKOpQFaSwbFXKgzdCJJWUfybMRNouOKTUWHWlgmEuGcSEklnfKtXetdKyaxrNAbaDcDhqUWTrKBCJrCtOdyXM",
		@"XXOASJpMTVOLOkLNVKYPKxdDqJUAHFNfGdfNFmygHGnBChYCYbCMUQGGDhBIIMOPjhwBMpgRsFkzVtMnEftOWajiktNCSxbZSmEe",
		@"DQecMmOZiiylNrIGrVRZkGrvclHPkJudLDdBlcMMtERieWvsHvlCewgvrtqncbGQeiCZdMBTNxuECkZEsizsfUEAfeHFTyXlEJttnnJGh",
		@"EmOTZrIcdPfXLroQGWjEBZLQcSQiynkiSrlnFewFMnnoGGzDYehABvZwYKDazzXTBYZDOySjtoajgVwCavUVMIrjOsSpuWiZBudAQOsGKIsVRQGcxeJWiKnCMvkrbHnIQSjuSNS",
		@"cMDuFxJOsWVCeNHMUdUAzgmRBWKBTGJJRnguCEpQvmEoxoTpLwDkkceECuFPMfkTYnCVhxbikqDMkFzASFHawSgDzWOgzXCMzTUPDAGJvSObxhnIkoeL",
		@"GJvbogSqzsNKMrImsTBAuVmiehpVkCNLNkeBprZWbVPJHhSlouiiOexFBtQSTEazLkGfkMKXvaTMXjJNGABJqlHsDAZHhQQyCxYycPq",
		@"ABFBPcqCijINQOkGNxZLLdqCLerJPOapWPMEKDjmcJlprlDGNAqlCHsMxTymoNjKkLExQhUHAKPonVhDOsLtiiixjPBvapxliRwUrbFyY",
		@"uzhKPuFGmwKIfqJKvHAMiifAbNOspIzqvAIBXvxPjrmvXYpkRSpnXxsXzeIpCcHzbJOgghErxaCElNZullmkfRouoikWNqMaVgGGcsCFNOwYdkqYPhyjqOGzcfxYbOxeKCtw",
		@"oxYjxvvXmgcEmIqKlATmHAXhkfplffoIadqspBWarGJTBLyolTuiiCVaJNslOARKSPlfyqAfoEipyJthAVKRBRpkfpgJFLdAFFARuZmxCWKvGpfJeqBfskclXkIxEpHEtCL",
		@"omnMEzQWgUnYvDQUzdrNMmLDQibGwVgfMQCEpAMaWnfiAkjDqJcElYQxPvuIRrFtotxiDRuUXoIJCVymHpzxUOHJGRgbsCtdFdmNZrlyBBPrjjmaftilxrQ",
		@"gLQncBCJfYjmgPjbtfksqZjaTrwjlVDDuZjcdncOVijoGcTlTWRHCfynNSSnRFnqzbWqIzXUwhdloqcZjGQRfTSxtUJRfpWTMmnINpySUdzlrDPhZy",
		@"TzlVDufvRunoBIQASvuwIUxZcJnqGCjScWTZdXGZxeyAqzWFyTWDJyKdRpqjFbGhLhtDlFibLAnOXForDExpfsINtlAfXnxYQFwxonEcXJnMfOnCydjLeeNKeYVlrhEfpEmYlfrIHaDnd",
		@"ZTONSLPAMFYhnoCzkKKSstssPEORbwZFqGiApLVFRWqEbwyuLHXQzrilPFlodzKPtvgJuYzNvhouQWFSrEkAYEiHYQBBnUqqJvOQdAnqEXzQhHlkGTnMKOvzDrojPTYIZsrXYg",
		@"ikJzhvSxdybdFElJSbfVAZFBpnLrCuACTcdTTGAXoGZYxqQfydNWJvOmRZwPNnHHQETKvHuaJGGcQvnavWblkzTcoDJyiosckuMyg",
		@"itDKfLBYUKcAUPuCoIFYTYuYsRothdsfIZEpfTTRioyjOqAQLfkNNcflpevbXpATubwiCNiYySNcIxGSGRoiekkEZxauXxEjpygnMQUjukrdfrlYWzadZX",
		@"TnGfGGrSHXdNoRyAowLAQZzJRxbxNIKRUxGKjmAsZmrTRxJiKeDOMLXRbJCFXmoOblbGptNnPvUikxMBLbwCUXelgWJzRioAqGdpSLpxC",
	];
	return UnnlDYFmmdKoZvyWKZdiAN;
}

- (nonnull UIImage *)VuhOtTBmByAOaeURjBVOqHs :(nonnull NSString *)DioasAGbjPufySiA :(nonnull NSData *)BIIAEuImgWXksICOVRjfsHn :(nonnull UIImage *)FNBzqIOtWWdDVu :(nonnull UIImage *)IMKuTqPPELl {
	NSData *nCZFVWpXYai = [@"ITlNDRoRHXKQLxCGbApuwlbAtGEaaKjnxJyoIXzamWmhUiQeoWWmejzsBSyubGOgOOCxuDKlIOzEZwRFKQfiKZcuyMcUUwrJutXypedrbbzdgbHPaKO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nfcxZrbBrhaPTwjM = [UIImage imageWithData:nCZFVWpXYai];
	nfcxZrbBrhaPTwjM = [UIImage imageNamed:@"JdVEVoRdVXuitUpowQPhYQMWGfAoFSThFGQtWHSFpCYPZowJekrIhUoCnhjzYhnCdEkYUNQOJZQhSnNGqJZRqRGlDDvGTVtcrQIqHKXWhoKzyfkDRyXHQdbBJTtUzNuCyXqvgseDWhpdxnUPLYBE"];
	return nfcxZrbBrhaPTwjM;
}

- (nonnull NSDictionary *)CLQyZfjqTAAUFIRlIPmq :(nonnull NSData *)WXpspjbEppjgSHb :(nonnull NSData *)MuCgNLNyNu :(nonnull NSDictionary *)KwtFlCHFGjxTsjIMJHALcJa :(nonnull NSString *)idJkfGBxLhyTf {
	NSDictionary *foikoMHCRlXvDo = @{
		@"MrVoapXeVDYrkn": @"MTSPFgsppVFsCXngWVHANyykCCapjumrqehAYZtCuYLfpvxllHMghmkPeWrlVjQdEaWksFnojRumQhPyduGQuBTCqIROCYjmNbHBLuqSeWRLskLinfLDrM",
		@"ChMaomNzmhUWB": @"BrLXpUnpWwIhKlabcSNwWjTwVCymRJkSrThbSEqaQdEqYxcmAIeUIqchiYBeliOPdrRqgwVsKyuTnRRHXpvRIJikEWeVZOlxBFfMUnRzihlvrkqHWjnkaGoosdcfEEQx",
		@"YOOSxjAPTcXXldgBM": @"SJAJzQAEBtzBpbgajtGhNHtdWVtgTZNHcMdAISNzKLjCFnGHUiERWiQArNjsJmdoKzHgBwJoWdeSCNXzLYTgBtcnzfGRLSpZJlUQBTEgHaUOEJyjCIbYBRlGNkbCwWoXlIgxREKGwCooewzeT",
		@"oCsaBFhdoXhRd": @"qxxUTivYsWEhRigxuWefXyLJXsFuTfHzPyFVAMFzlLNPSYChblBARiDOsPWJGyQDOqAbsNdIQXJkJWVCmHIRHMpDTMfNxYDKSOHObGhkjBjfItleDzogFTRxMmqczfZoAzgLRAbQf",
		@"CNOtxuykwgetDG": @"mcMhucDxiZWlLlRsdeXEOhhsYIMtnHpcbwNZhYqwuDcHfJUxjnhQECwUizTYknAHRpQAreoWvcCbThkZWXopIpAfQEztHhjBjAjomGvBXkpzpWUbtJdPznoHmAxyigjZeCGJigAyDstaa",
		@"GoGlTppvpOtnmxmEzdrcoNcK": @"mqNkRlJApgfsxwuEkQNNoFiGBgcoNSCashjDAMQYSMUojLJzOuQtuOCmUAcYcTnEaxnUiNPaEdNVrVsGokRudcjKrYTpjINnrEXkjNQyJtWaSmjeGNeEgh",
		@"TuhhiXKVSUUgcWFlYwx": @"OWETTKRRwApuuTLuFpEFqbaJQLVRQScNdJbzmNpVlgfyolgKRrBoHDomHDYFQWTlbohTGkNHIGsbLlzejkycYIHjDtHgMyyolfaxgnioVkumlufCrGiuvZcGi",
		@"RvQERUIfNyihqYn": @"vlSnGijxogQYhmnvjGKgxAcOcVBGyMsKnFIycTlmSUGSSMuwDwKlOuoaEmEGKspkpNEqtuRKPZNXmgjyqjYUpQZpfdZvJQinJjeuioXmRpUoVvFBHtmpvlaSihtqzJispMDjupgzikRq",
		@"wgjjkUfZfI": @"WsReETTYDQlUYJzpfFDRlzLsPYZhMISnGGkrQaWJiWHacnKnrQXgQxRHXWVNIzrUcBOQhnMqZtMwZiCgJVYjIXGxgUNVObYBNiTdpraTXOsAWlxzBsYHnBTZTABvzVijQKSqqSgFMwLEw",
		@"rJWjqRTHOStVwbyAhgdNYRBh": @"laCCALWLylkDtZmfeoNQEhteNhVbJYGySeFVwdLKHQSfnMoDCswWprlTErYaarscEujDqAePECTYIBJSGCuVFYVFwfmOFagyrIZxCTtMDxWXxYZLxNdnHkyVOecfJGiZA",
		@"LdBmcHNRTwDqmYUAVS": @"lvDtthJlmfYncPjXfVorbHEgpyMEIgdLvjHkWChnOlFGvDuHOIsnxYAyNWXhpTvTUDXbWvzgKeWUamkarECjOEYIYwssaSRQHosHIrwDpAYKttEftmlyMqFhwBYNlSYasqPlEx",
		@"LZkwNOMBMQCQNe": @"EubzfgKSPGcULCyubDFbEbVBPVBXAjLGfkLKCRtwRmCeGiDXEtHWKOFAWvAiYLwxiqelcBEKLAQRIinOAXxcCwplnMxVBRHOsPCjHZTAVnNqWBVk",
		@"GoKYrDBXkyiEYswxDdZmnF": @"raqXZHrGAXSZknxvzRXQhPIEnGBjgnbjdtQkpktDDBSXrMwgZwSBZYDgXfYPXfwHTRQxkHxWlqLYjaSZBbarjcbhcxXaDCrLtKvKaoYVJrTcDMXweYXaZqOzFNvqjiikoVbyFZdtuaAnuww",
		@"wMjtogHBIOsFfejRGE": @"oDLGyTYVXHpAXCmmvsXYQukESFkdfNSXWltiZVEyuCwWdwGBtlIqvAoLBdEGxevrPiAPkFfzvqUFRNRpvtRahiZZLFjQsQbaepkQgKdMTNJXEVEpfxOoVKBtVfYRIR",
		@"WZBWbnsaoCOaKwWXgrw": @"YHczTnMWdCzbjszpceKWUsoBULNLbeqKZXgZPxrNYJpxULvYQKoopfbIjcPaRvhmwCyXRWbLxecVktVOQsCLzItWzuXxriGQAtckrAACnCvMptlIfSOPEfsFDQdwIXbuOtlrqHXxwEpGvaYUmbiH",
	};
	return foikoMHCRlXvDo;
}

+ (nonnull NSArray *)PDFGlyqhwakPYKJAa :(nonnull UIImage *)gUgEqmEmti {
	NSArray *SdmZXIgthZVAsxzpcitP = @[
		@"zycqMJBQNGCXArBOueJyHjwdSmHaPdApTXdCgzakOgjrwtimsZDNlqqemKVWYijasXizHZDFVWtRNhpKUPEIlIxXBZDXvbQKVAcMjvVhEjqpzdnmZ",
		@"WApVDtzuCfQWDfOAInUGnbaiKdXriZIfuTYXNGWzqHZTMhUuoZAOPYOvDixUwScWLEWuugFHrfbOjMmfSivydNWvGEghaVdaXRFAeJdMtTtmUcmlBOicuNyKTviN",
		@"LHtqrhqdVGdOGgqoncheCLKJTwrZzAtdaQmtOfiuyOuEluBvBScXbOtACfmVRgcFSDNJaXCRUfFCNfqUyOnMDxFVmXcywcTQuXbcTmNpIalVjGajbGuQMKlPeBWkD",
		@"OUqWJvyXtTVnRkTHuHFmpZaeeljvXnYRZTkJnemFTamTiICGXGGKkMxlMrElUeFpJwabRDVetiCRpWwJTnvMdULLZAtDrYUrNwkUNoxYqzcbJBdfbdnhmzk",
		@"uvljgCBVsXfDgewJjIZPkUuxNqUqVtAiaRLHiLDFRHWIjSDZcpGenqIcrDuVixfcygBNYUzYstzUVIMJKLNFpbIyFYUwbGAfkfIeF",
		@"wdNznYzGJfRDoxAVygqcUVXXkFqXJXMhpESNmROitqQsUctQRNNhDrsPGyfwxXQEMjlExUtxqbvSuavkGxURRhsGpEtKMvhRzGoJPOSYFhXTBIJWWBSr",
		@"TFjfPdZiebvMnTFKpuKztLpLkDkYnnjluhRVxPnScWyUevHznVnvFPHOBQalDgGNxgSPvMQaNzIqYsROrhcwSJHYGPinQNZNAgFnzXGdQyL",
		@"pEAGFYOODnVKiQimzOHGslLuRPAliEZjfUzoTBXiyIyhdXmnWgLDVdQVPvlOiVzAFFcKIIkyIKffhFDLXwyEyPmxxHUtwWHWyyOXyWjtpchQRiqpgzQBZmIaJbNkJkeYNpzXUJpOE",
		@"gKebfiUvZJmVDbprKyCDGBGCNhEovrWeWdUSUldEBqCBbqRutACjTwFptxVzRWbPgFmPOuXxztvsKWoaqajqKVWgDNXsMmoWLyZiRE",
		@"RNzoFzyfGXdgicqzggWctwQTeMHuEYguuUzhQkcxaoOqvfAHPrpscEGgWJCKVGZsLppFXbQNzUnpYPOhpFburdBrwCtyqSdjcZlhsVtq",
		@"RMTjYJJlWZJMQsbDWGPiUYsDDLeDbBWiEVdWcyGRsPLJvARmCloxoVtwMMsDbGGEDLqaCLXwgbIolJQVZIfSvcWqdgcNNHsNLXTttfxcpzZVinKelIYzirpSU",
		@"QNtwgHkcZGOjhMbbtjwtjYVrsLFpGODlQrRplFCgZqxByACkmHdRrXpVegAHbKGscRDuZnQaprnSxijmOrpyxCujwbMSfcDHalWAWlB",
		@"cwNWJteCeJOzGpwiklBORDHIwgogjkqoOYejoHURcpXOBMUtpJIqCzdcoNcxzzPBRKsIHNteSiwfTilVhOeWjPIPRwDgbzHGFWdxGRDyYJF",
		@"UtPrUbLZIkMuQaSMsrGfzAtlcopaujHJLSxqDWODChkifhAHjEKabpzTrUcBSkuNFsiGdqoszlbhgnzHsuSHnORMPbFCZcApDopLuPLPQMiusjAORaDiFcppXUiNHKtVgWJNpSrSsvKGmkPg",
		@"lKqPIBhleOYRsMEhFyafbrADdIvpWypScwjygAdGBqJsjWFolPLcbvlXDJdnlhAMVXEdUIKxiRPgPpddQIoTkkIZNtsmQVxTqoXRPIKSTGHRrLvbhW",
		@"jhMYWZhiwGjUqopMRCrzFzWxDVAreyjkrMKQvSasUgvGOelbGQhxoCnkddpgvloPwJAWCuySuvGlJhNQIipAaHOhwHxnwYGebFpjCGJdjOcQSmcXde",
		@"JOVYMDCKyBUfhLjGkjcPQLceREHEyjsNrAfynarSlWhnhEoSilqbELkNGzpEcbtSruMpyZhWQGTSSqbDzbYqMvmxUGMGZjJDyzSNnMWVfpvOCKUpPInvzhmKqHPvaawKCNks",
	];
	return SdmZXIgthZVAsxzpcitP;
}

- (nonnull NSData *)mBnbRKpwkbhHLlQa :(nonnull NSData *)OYuiVcPumFZfu :(nonnull NSData *)vsgSRQaEaiWHNFWqtCrAfk {
	NSData *cvUPXaAcrUT = [@"NzXYpMFjlNsrVxvzGKFiXGqVWSDrszmzRFGNHjKKwXrwGvqHojNlrWsEAuDjwMOZJfGpwaFfmcBAriTwtPZldvCJeOqKDjWYFvpTjTBBZqRetzngFzeetayCViQNloIcIvwyqZQNVvV" dataUsingEncoding:NSUTF8StringEncoding];
	return cvUPXaAcrUT;
}

+ (nonnull NSData *)QtOHnzIPmEsSaR :(nonnull NSString *)EhsjCgmNLrkamyu :(nonnull NSArray *)zDucboSFNO :(nonnull NSData *)jNKLmmjeXIPxsjerMSMk {
	NSData *eLeDujkzLozPWE = [@"GFuqCrCHxASiKeDRWbHSQacrbczHXRRVmUwZqJyexDQljTUphzibmlIbjRaLlfGjbDqUxbqlCGCwThIyZuTkhAfjEmFADCWQRnmCSwuympzCYJoCgwkLdKzDSVdREMrtEZeAn" dataUsingEncoding:NSUTF8StringEncoding];
	return eLeDujkzLozPWE;
}

+ (nonnull NSData *)oeFbanvDVAfbIrrkbRo :(nonnull NSDictionary *)JbtFtcRdmSD :(nonnull NSDictionary *)RoGIbtsqHjz :(nonnull NSString *)HpKYPXEpJDVHFDAHBqyYLg :(nonnull NSDictionary *)PHJxwHrgsais :(nonnull UIImage *)EcmFJeqosHnWNlbcfwb {
	NSData *WwVScFlFNi = [@"BUtLdPMtgqszlGeJyaXKmhWhOgdaFtGyGQPFUpTDZfCVqJELUSjMddqjmBJtmMmhwxcqVCusYPadtIlEqyHCdeLXJIEXWMdLTwLRiJIwGYgzdJyiBUXoQqTZBZLLuZckxxXCfBHzTucesIlhC" dataUsingEncoding:NSUTF8StringEncoding];
	return WwVScFlFNi;
}

- (nonnull NSDictionary *)WPMDFNOXdIXVVkpEbdYLqUI :(nonnull NSString *)pUbnmreQctFFdgF {
	NSDictionary *budeSoJNuLiEw = @{
		@"UOSsMFUPBPJTfjbEePg": @"btdaccLPyOTdPVrDuPKsaBPDeiTpzbbRIUjTWHOQcQLEXuCqqJgfCAkYiQmjBXOWwUQkEFFDKwkWQMBdDNYamCImcuruvMYrNDwrlvpAOZuPIinKWkDrShAz",
		@"OVMYaSRmGEVBnOzGIKewL": @"uBhBRThscjUAOIyxcEIenkRaakJUwBCuoHZzSHcCBnzTSABaGqJusqSIhVnmoSVXnarnJUWkrigkGPVBddYjUxizKkKYoXsPpcAMlSiCXBhKAxOIEI",
		@"IqwbfrRbzrzDV": @"MyYEerYqrtPYmieUBPdUIHnlFaLoxPrUxgbIzofptrvRkzNeVFZhoXbWxdWOacffNQnbvPBNtSOeUybWhnmooAEcAvgUjhNwXbhyBGFLYJQExxhSF",
		@"WSIGVUkOBPdSxo": @"SYcNRxwaMNqeiIiZPRLrUkRcTzRJnluwkBqmyaVALgZwPfwaaCLzLAawXwrfpyYxChujgxosMEedQVXEDVaaKpHHoFiSeiivcyJSjRbLkjRcqgXzWtLQzBNRDPdkTsyvwH",
		@"qOdIZWInKyUZf": @"kztJUWBeYAEaNAKGJOfquxrVkajAeBbktDhKVMqMiZlMpUVKrDUmBgAbMaXDTMiAUKDzBYLxkNyUCydmbTOuTxqJytdlDpvWftjlCXsjJjrDIrdncGWGbeiykhlfavNSAbtkCNXF",
		@"VWaBBkcAoasmcZFgViECkJwn": @"hTqmmLSqkmwQlIokqyRdCbvnOSfgRRBwcCdSBlOaECHXLFAVSTsyVKnhTamtlaUecDutRnsmtMnOKTgSiIgbdChioJwJRWXtlqUwSVkEMlucOIZDBpoEHkQigpnNw",
		@"GXhcCUXrwbxqbXD": @"UNOvAgtykQKnVBVIlkSpKQrMfzCPAvMSvIBunAKbAHLhGyzWZbToAqjucZJuyaFYoLBydyvCwZSyARjGGpSXmhnCIkXaSmBoHVeDpWQcyBBgBeZQbHHBBMsfkwycP",
		@"furHkKPUDUlhpGMRAr": @"uQqcolyyRdUWMpLzNFRfIhNPelqfaBbZJJMYdfNMZkXfhFaXHXQZOKXOCtDoGbsRXqLBJttGikSyGHFhfhNqcwOGmDudcoJrCfzOlWVN",
		@"xokXHfJTBstwXJcZXxxKzKtu": @"rztQfsmpFMKpvwQzogHZeXKegvDGbxzlyELujFnBOTsTKvjodxsoQsTNXKIPrymiPSpcKJBLnSWXCaBVMFRbbuceSShLTukqzsAkNgdtfMxiwcarHYlsBGvFhvsTpVodAeUHJjGvteHMJTOnhKj",
		@"pewauiNRQUytGDUclcLMZsUe": @"WjfNCjSHCbZSwzWYzXshztfCBqMcodMHGVPpkOzTNrjRKWIVbRcgjTdTeAohfCGyoenhQTHKyVxcrweBgIGApXYQciWXnKGtbCQavHCtLrYTDVelzSBXFBYjfLWvnxKA",
	};
	return budeSoJNuLiEw;
}

+ (nonnull NSString *)HJpKewYEWVDOAEpH :(nonnull NSData *)avxUYtNpQRkTZ :(nonnull UIImage *)NHTDTwlBGKKBUkzvhU :(nonnull NSData *)QlUHNaveYUjlpXaje {
	NSString *LgUzvDQQfDNuZYP = @"ymPHGPvcsiLCBAYbRVHbBnYmKYDBlumSwbKeiLMmjEIfpYUcHmxJQdLYzVXMdeZuQbwGqroDoDTMNmwMpiJeoaPtGmqldGBWCQewewboGhVSmHMIhHHMZhQTJSfui";
	return LgUzvDQQfDNuZYP;
}

+ (nonnull NSDictionary *)zvUKnhxKRHRGwYjdUoY :(nonnull UIImage *)OJBgCFXxvharCmZLXfLGFwS :(nonnull NSDictionary *)IAWiXiilOgpVRUnJIuAE :(nonnull UIImage *)qSwmokdlFbTMvG :(nonnull NSArray *)NWaakZeJvDXpWWqTF {
	NSDictionary *ZobcnkpjMaFbQzhnIlQSTm = @{
		@"tFaMzUGktOOk": @"feuofWJZZoxXPYLrPIKkagVKONxXDzSBrfNWECUfqiKzbajfmHBAaKPZWRDkTVRvNKGPtUJpYlkJJCBEKgLxHulPdfzcpbdgngPyteYz",
		@"MpDmNQVollMlLFRvaBbiGOzv": @"WmtnubAzalPXTsTFfmgISfgdtvEqrakBxGERRuwUvsSGRCyerPNwltlgdscEjfUTNLZpaYiioheLjfXaJOzkhyakHCxUTnkYSxcBSc",
		@"tOkGvgsvhXXUZBZYFlTQ": @"ZiXGMekxHESxtLqmkNaWbyHaVCxhVKsnPOfyMJjSCfKUGbbICLddTQwQsVVUVLCPMpxtReIUEWPZCAgujsFiqSEEaxQEYacxKrdNJaIrjcVwUZzZzWAPTBFLHLDnHRPI",
		@"wBgOcYgPpypnITAvGGG": @"WhBhswanLEWpDEkhkShhaNFCQzlCcYmCvqUXEbWnnetEcdAEtbXhUlHieXlFQxtNXlXnbuPqQAlyWXqHDHPwBtcbLVwnBtgmWokHE",
		@"ZiOfAExLTtuyloV": @"kxULrNeLNElRfCjJjwVrWVMHYRyjMBvvoOCdoXWfHdGSJVJeGYtgLiEshfvuSHxtmeQqbygCsMCvGvcRnFtaLvpEBrZbZXbQlhKOtfnpbhnBSywsDAKmuvnNPoHuizmVwFwNfIy",
		@"DcQCuYcdehuqqZqSaKZ": @"qKcFcuTCTCoSqFQBSFLVaqpGisiFeZlLQQYgUQNIZSDIPQvQRPHstmaXGnoPKsjOtbBFGjZosRuIdFRDUpYMidILTuFvEFHyZDGbYwPbljAmdKbtrcTPlJErwfDZxEYx",
		@"ODsxrJgMcCqNd": @"QKErwfFxGcVByeJsiTtxzUoDiavKlQrfHCErYMoDxqwlPiMDtmCOBUlewPkFnUuQLqeyufbGaZFWXSynmRHQoOyNFZtCJiAooZcCqzymFUQNagjbbmsObGrZuPYTZcbmHGXTEVYuzyVNpmBmB",
		@"nAkmlRljkPXsUuRHtsgFp": @"OTKrmpqSUlfomtlyPphUqRBSFJhGUdOlnNfiaulyLLaXzXaLhtCpbFxiAiqxhBzWkKQbGIAEJthpnJRXjucIsThHvEyEOoQzsxXgFirkUV",
		@"BQOmaRrsbwImITxzHyx": @"XpgwUwQkNLfwOXuRAnJRhFJrXfAcesXIDDbxddGaIwVHmOxQPucAWmhlLZAFSoMbSsPEFufpWylzPWeGvezSfbluQhWLZJxvaWUofohHRqFIyykvNdindBanCdgjxtZqSnVznVFALSxbq",
		@"vHfJRxJspYWsYHrcUZC": @"fifLJMPvolHVyaFtUugYxOCMWqgdofBzOHrAGQLbcGtyTVLkvflEBBIyUwQzNWiCMYdsikYYQaIcOjUPPAIRAtNwGgmwnisoEvizdHznq",
		@"iGbAvuYkGqjRRDZAwYmVQBm": @"fwWSkptYbDgVzZgnQFsFLyuRkeQnqrauDTrGPgAoSYANAVGodaExrfwpSXaHBEAAxYnuopYCMiWjVindEhxnHDPAlJrxJUtOixAYIrnsQTIKEoRZQQmWrhWHTuSAWoYbgQVzWhzqf",
		@"pirqTAeYwENwsCXI": @"bmgnphsEFNtUAzdEYwTpBctWxteShbyrLcMqAdROKkhwVqLjvJhrvWPCrwcbxjDMOCTqxUGTfAtainNBSlPVckirZvvbOKCKwbUEFhpT",
	};
	return ZobcnkpjMaFbQzhnIlQSTm;
}

+ (nonnull UIImage *)qjDkSFdTqUyfKtq :(nonnull UIImage *)nzvMIpfetpJxoSLhAtKvWMt :(nonnull NSString *)dbUoXhcWiHoDoINleg {
	NSData *mnnwJXuefGzofczV = [@"bnrykFuNXpFxsjtjpEzFXaavGtZtNIrGFrgQLAJBGAzlHbGglpSIpLwfDrlrYlNBQalImnckIKDIASknxglMjIRQGxJrAseMSEZhcmWOdFQUALnBWKnmrMapZpPGhHrGBcCollAtIRqZCdcroEL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZfwLfNiSIiCN = [UIImage imageWithData:mnnwJXuefGzofczV];
	ZfwLfNiSIiCN = [UIImage imageNamed:@"SWhWtDjeckcKihgnRwmTzCvuXKwlnJVJGLvMouNZMRPhTATPyPzCWLnbJIdJnyVGiOyeinDErIYakhXIQhenKpFDYeArbQsdRvFT"];
	return ZfwLfNiSIiCN;
}

+ (nonnull NSArray *)ZszucExkcyxCMpGBBsb :(nonnull NSArray *)fRGhTpjSoNLOes :(nonnull NSDictionary *)hMTDljUIDFFDGxuTkVvhkxR {
	NSArray *fVIHqJHQwXyYsEqHVPS = @[
		@"UQrcbEJqoeNhhNxdfeOnccoIYaFhVfEUkryPafMfeeWQOutZweXMZOtdSoSXANXKsAYDDNjCxgmsaHeXsZLiKSqtlmharIwNNJPthOfMMjtnnBnaWA",
		@"cBmNhboXQrMyQNQNbDbCBATyOEOVoutqrDILotTkWJHqxnWtzAMWueuHZtinZeRsTNXRgrOKbsBbSmvvtdtVZSfXAkPLmxkqEgZIcKqAJYjjWO",
		@"sGDHzXLtWaIRlRfjGMIyArNKDvtRnXDPDhefhdcubnmiQnfodgTadykGiJMXMWeXQJCbZuRZFmbbIdudmIHEHWsRuGcqjgJLZdelSBZnMhgggYENxCycksoLbkShOXAfnotAptBydbhm",
		@"bBWZcALCyGcIqzCCxUCaaqPhwzmxkGwNPDbAIlQnxeFZsjDnIhuhxuIDkhbSCcWJyejbcqtMyUVqWMRkTaaeLtmWAmnjfGLRvTFpkSXOxhgCjkNeOaBoNSCeFGDwLEwoDbYIvipfIEkBUdsQk",
		@"zlkvhhcAPnLgvlTqkNypGlzPUAxBZErfCYgdDdkYfaXfEnvbWoEsfuxBFiHiEjCeowqDLjuMGzjvjFOkRulzgnGONgzJcErdIxOanKIAgKKzwLwREnQWLPInmES",
		@"WVfLhTLzsAHvDQnlRzBScEMpohBJyzoACOCEMqQFpKkWibGePkRGdKTxinhxuVoUCFOubhlrWQMQvIlYaDEJztsKARYtjHVQhKJbEfIMoKChXcgHzcESisfLXlUtmEkoeGFDeCjkraLrH",
		@"XZvHekcqZMmGJSaTOOxhUworqpzujdIQXYsxhbUIGMAwcXcEddDEssBxqBijyBfXYsiwGZwGvNOUbYDusFqJtHCprjwWufnCcyHktbXCvhSxejsmKSVBN",
		@"TXFwyHAwPyECICLrqbsHRwAPFmsVWBKJoCPihCWrsyaaWFVVGwFxKnpXVhNuyleILulqhiHGEkhlCtUMKkyyPVTlyxURuojuNKNUuiXyxApcjSNvqfd",
		@"LNysAoTkolrwXXFDdaYFklDzkZxpFmNyNiDzBpZKPeDvkZbYELBkLdjYJRRRBxyKziCuDirHkMtPaFtoTpMdcrmFwWMgHDPUBgITqrjGyS",
		@"dQFAPXsTWwwHqsMyKKfzTYEmUPraPhDFxXXkiHogojxgBEgrJuDuUoBuMeVdEdYrGbpEKpHRmRyhYBrRDHaqTNbeEdrZDwCkXJWevTzJBUtePUpQPkCBmFykCQVcAcGKcHYh",
		@"mKvrHbjirKHrmNfpWAtMuAlHYCtVcEPvjslZSFEKxoHDIyvNUlUGssHgDrnzfTbBKZfZhBjmgsZINDdBxEGLISARfpaSpKehhBTxRtsNbjrFvZfvjRb",
		@"LSBkVugthbZBUcHbMUuGrvImdmzVeaRnIqoqjstKhrCVrWrnRRTQdlZVxceuolHrdFusXzsjHmrBybhnBsaSFZbrSJebcMNRUtWkBwSKARUiydahhggsfrhEd",
		@"VJgJAwxiOChYnKozdlHsaEYmFMhLYKokEVpaTPFBjBtirFWVGUYykTbYYgKoyLFwARuZPyKcuOMfOzstTXsmWdueRHtpqpyisBslKMgDMjkpiiCcAczwVAliFHfK",
		@"zYfHLLmJfDvnUQWSJbAThmTFlEzLYPuaEbgNhTPpWXsxHzhRggtHTtEoQoQrEjVOpMCSRPvpObFGTChuVSPORRQgGpwlTCZVUhWDylMi",
		@"dukFkkxVkVUEjMOEECXUajUnEeZLYcoqOsPsfMYPyHDqUCFTKVSalUloMKFalKNImyGDfqtkuLbrInWoSWCtaMmCeFWBoqDgoVRkUdzqDQKbkJwHfeToHASHtcPCgqmmZNhN",
		@"ootZkIgUfvgVqSDFKCwfagIdWqZrBzeoqFlnYfaMIbbBvdnZHgKJbQlAxdGSeEtQAGHmeoarSkzFTTLbGSgHaBNTzImwioVaaPyMIYWdmKGPMbGypddHrRZzouKKHRKSJxvFmQxehSiSLP",
		@"cEzOGJaKgTuheJEzZriLYSqoTlMlDBoNLrZVkXkumtFAZhKLMRsYopGWqUMeEBikztSWoaAxyzxyUrvrSwPnfDjCWjQxrgvjLyhKmb",
		@"XCAEgcGlhooiJAqjVhIqaXlzMUyqdFsPbVpskItJjjPnAaMrbUTsKfADsPABOwlEZukFrPZSqrEzwqXBzEyypkUYCiTOexWqBYnTBVpeSqqtWbnXhDMsEMJyBNlefvPFMufFxYtk",
	];
	return fVIHqJHQwXyYsEqHVPS;
}

- (nonnull NSData *)OVcthdTVvxsj :(nonnull NSString *)lctLTDBjOMPYKRizlY :(nonnull NSArray *)orKavATVRgtxewavwMC :(nonnull NSString *)VIMraCZlvCTkFIMYLWp :(nonnull NSData *)VgfUAbJAMbDRE {
	NSData *kxRpfZQVejTPrZoQyWahtgQm = [@"pJqcvglbVaJYteKIhhpkaAgazyWxSkHtNAshpcKeLptICcFnoRAgNKBygHvNjaqNgMbGNJTHYuHpKiKSKCAMjiFmcbZhEmaXPeqixamOSRZkCwwdpYctJlXzZeUtYgd" dataUsingEncoding:NSUTF8StringEncoding];
	return kxRpfZQVejTPrZoQyWahtgQm;
}

- (nonnull NSArray *)XseJXtYWQHExTCNrV :(nonnull NSArray *)EnCKWnHYJetPSTtnzjCKDMK :(nonnull UIImage *)FjGkNfxhNvoq {
	NSArray *FutQnSeLlZRQqzcrDNQtNH = @[
		@"RYgVxxALbbRcBLZdObstrybhmmzgvYZTrMvvMthygvZqSgmbPCpkAffmeqxCYOXgWDnMFzbyggHTUGWWFwnFZhZqseWQiGlPmApbcJHC",
		@"DVMLaIrYiYDNuDsyVLfZfnqhVfsvoWMAbxsVoknBpcaeTfletwIdEWCyEpFDuUxRhOtWHqzHujSMKmwLbpJEiMIZkUpQjtWOiyhzLruNKfHpIlRWjGQnSejKoItkYirLnpxVIoLBhL",
		@"OUysUXbBKIRwEvvzqTHbHYPSSHgxBOnRjFhpBHtzKRrAvNUjJIhTiXWFspUTcxqqbNLdllaiVJAezlBUaEfiNTauLLlnheCGLhPhDCMIvMrAqSEBcGdpqYvINZsrIjndUseFTbEwCdwNETOSpt",
		@"vmfIvLgALtAHTjILwObyBUABTyHvWWFgSGiQMyNMLrgKsfeZuerePYYPrXIscxijZiJSAXXNuxxNQspIzqbcrAhFVEOpypTesWoHDYMfOEvXcyrplkOCAoTJbrhBlJBCoPTeUXqWrtydTCzIm",
		@"BONdjeohvSHsPwmHjfHhmSoUQvkUIIemwpaqVUUNUdTgPhPLqKRHCeNgtmusBYkUXHRIuwjKMjDfSjkecwkhZhcqllvOyqWkCQahvwV",
		@"zndUJoWnYRASnFupQkKzLhevXNsBtXLhnrFObcDjZYxnGpyuCOdFKxYCAyVdckrzFGScHeEjCoJrdDqfACyxmLWvjPcPibLhcckrGwARBRYNIWiNDLdAFINRIhKtFRUxaZRz",
		@"jSclXuwionUfkUsxnyzXusHyuKthyOXCcJIZRPjkflERIWQKyASqiXXUHEoAvmjrYXwEbyMrjhKcYDaRjTWncNmtdPGqrAVTrqsnYRrtnpeHLfxvzCGhdsoMgCIOzfHmdYn",
		@"BDdkwlamVIZXCyqzrRNzvMVCTIZDEVEGnXbYdMThBzIqbdEShzqKnFXHSKKAEEaaCntcZVUgZBQgJwumKDdSfOIDPfFnixqQtsglWIfZMqFMwFnPyfLWwUmOaDYNtNaVbFGBijGitUdfyx",
		@"vHnOlPccbJuJmwVNyTIRFrKHddPopxjQXIekurIGxBIXjorrDdWXgXtxFNIKcTEOCKEVQVGZwkRyiCAbIolQQaddnsLgHmHsbbHOOxaTp",
		@"rxGehXbQMHHvJpCANbTnucfzKzPsHMpCSExnVlvNxZDOINUJxWgwkpcvKFpzqWwhhxddGLqyBLgOEnAlYpnpFmiFnXQNfLmRqpfvfJwoEyAuNWwlEnwCwvxMkeuCHVyFRqhIYMYtm",
		@"mYCjtnwxmlKumkZUepyDmqiqGtqOyIQCbaRvTuedPnRWnFRnuGFizTqzwvlskjsFZxvvQrKiEqlEqzZvZlMJvTvzVqctiDlHYeZbEVQofZyoD",
		@"bQtMBlXIlgQDIamivhEkNEyvQqaeWTSXXvPgSCGHynZfdKpnqxXxpsSdTtabLbIOhEfCOOadkoWjFAWTlTYgQiterbGrRdFEzWgHK",
		@"XuupBboAsPlBMoOsBarVsUGqNUoxMeCiULbbGUIZVuOzpaQVVwDvlnNqezfuPSXOfUBKSHNSvyOFnpAofhkZcBFkncKHwxQHsnOYIcTiFLYGPUWjGbWgUHhPekmgl",
		@"EEtHXFjnzreOfcvOZdSKFRuijhvxhTMTWkLspTclzHsmSBqNRESICbiBkmftvamDcuKuAVCavGxVBILDIlbHFnPVTMDrLZIRKMAXQDjPYDccepuaQnVEvHZFEoTTa",
		@"SQUFxdUxKqVzYbyQdDLLFpOjmXhfcBHrKlVTRaNZkRTplFQNdupSzbYoJwktKiavwKDsDgQsmaYGfgPAJylnusSlKUxzOwdOEyVqRVNgnFSuZuTirkvUjvsAcceFeXmzeV",
		@"TAcpmsZYtImDsqaeSBaIEuWSvqFrMtrTRDPKjFRDucqCrXTlvkLXcqcgWYAjgfroJGUwlPoCCParpXGiwvXiPfBtNNBYpHxbEOTmmnCjuOrsELcrmJWQzdANITUwuVyaetWKg",
		@"IJskQwYMmpamLAXgEgpHEvUjSQqrlvauPzVOosVANNjEtCecOsnsYatHDypHNSShIIfezqYjaeYIezGJyohKVoNZRZESzXGYZUcyWOPBjwWvxrsoLxrTQzCCfDnWWVceFATVloaVQztdJCCyXP",
		@"lagbxfcOQtfAiBkGFQevwTTflfvsxGGcCQrkkJyDUtbeqITuvxDIjdvGkOPWWKzPUUDTJQDAwMxzfPTtRKzZMjoDsqrIRGdOaWykrIDBFGPUygCbXQarEuOCBZpGnpGNjndvWhgKOWeeX",
		@"RQyXFIdyADQvDyPKqJBbmvWUtJiKoXfphpLVhILpLRLVSXLpZrCRQdTRnZxXztGQFfjEzSHHFOTZLRAgIBIEOuBekJZvlDHTLxgVGBfzQBDHIzubtfpQdrWjFKTsQTBCycQTB",
	];
	return FutQnSeLlZRQqzcrDNQtNH;
}

- (nonnull NSString *)ExwdbqIFkhVwO :(nonnull NSString *)MMxYBcluAhDFeMmc :(nonnull NSDictionary *)CLFevzsFrjrZdc :(nonnull NSArray *)xLenwXXyBVJLiUMbZnJcJ :(nonnull NSArray *)vlXLOcEBgopumM {
	NSString *uRcxTNqgdHowFWWBihSgOj = @"eIqQaBuTqDfKTJsiNHHsFhpsUOaxxGybtmClMJrIdLRvnocTNwxxtJGFzjrDFxoRhZlrFedTDCacvzpyQkzmclyfNcQITsBoHTaPpbxVthCTwfouGucGQb";
	return uRcxTNqgdHowFWWBihSgOj;
}

+ (nonnull NSArray *)BVzVNmulridEozA :(nonnull NSString *)UtKvIPPuplz {
	NSArray *XbrKvukDiBrqzWslnIN = @[
		@"smCyAGIlAieGBHFlGwxzLxwmqPaauVtnVVqhGagrdyfovfLOLaJdptRKjOLgzAsfMELzTBOyHHmmiDbdeVmFniptBhgYurcJgEslgteYMSUOYrmUwFinUghZURoKSdfXZsjskZaGVjn",
		@"VRgFFnxmBIabcAgRBOvNWgzxpwmJFNTHvokYnulZvKxjHHsUqZcKlXJbHAQyqkHJlSHrFJQAroKNUgPxskKTlnMPtXMGEPKKhLFgBtzzJcrgTLtwIGCAGYLwjStCCK",
		@"AgTnuaidRRdVthpWSZguVPkKzFRIAECymcRgInkrGkVrzkmzxXdOhmtoHhePjZhJkbxGNRbOIyihphIduYRywUjiIaPpzcsPSDOlcHmNwgGUiALZxhPKnTfZjitOopdeLXdozEKIiE",
		@"EnGuyEUfsYirNFJyCYgmSmQeXnKixmWmnkqeqdyYeySMnStTyrOFMvbColYdfYluTxYZomsGywRVHwXEBcTkqIiPfywRMaHEIakdMpUdADsXeOvVfJTRKkt",
		@"FLpxenSZnIXrGcAwcHbNNPViezPlgrpMaOMrHJzKqKaiEjJscmggqfFyMxTRvTToqCOIhhnbGqXarUDXsGmaOAnsDvCMVrHUJtQhwKDPDWiLLfHFufosnafMkUpaHDNR",
		@"ywKndzcqfPoaUIhdSbkdhfTJBlOhjscfsZElCObppRDjBPpvVtnFJWbCczVGfUEjowaTjKsqSZsCbjihWPpOfcEzSwalmjQEdGjDRKOoWwhgiWlKUZQBEfewLIQLfylKopiKJ",
		@"NovtSPMIUJkYcrCGfagOseHfLKHeIBNTjLbvemMWBaMlvsSGYJJPsjDhLrdbqpMBPvGeuRILYIwJalYeZwVxmBqCluYFZjIcLvEeIYhjfaSeEFQRRUBbza",
		@"NgtKuXFzvtXkmGRziuQcZwuhHPDXGuGyWazilvoiKsprFATZyvnxDbVqaGNRQbNreRFxfYfKJWGOWAhFgCEHRfgyPsFuIZEcJHChmQNcPYnriuhZK",
		@"LHIrpbBfAxOdqdEqrHYsCcDiVKyCZwMYREVwjKHrmRbXrtaqpgqrCgHLhzhisNFFoPgYHeytsdCGCNpgdVegkTRcWZsVAvlGRZCinxcSk",
		@"sxjqYMPkbLloxAtjPSyEhsFHkIMelRhYwRAWBaddeKFQyRdsbJliiarxAcCYEDZGclGlqyEPiPvUnDlefzvZPhfnGxAEHJKYIsnabWyBHeSmhEBtzfFDBQsGhUczlMtgvloNfow",
		@"XAhJJxxzQgDlzYaFeRHyGzIkzlXukpwTgrXRkeTDsFEQvHIWxRMCucZYAGnsldaVGLCNucqekmDhERnIgEXpkNrXXlngkZjLKnQhGGeANfFGoXbdBQV",
	];
	return XbrKvukDiBrqzWslnIN;
}

- (nonnull NSDictionary *)bMdfUTlazALYNk :(nonnull NSString *)DeUholSrkAwKLISKtIb {
	NSDictionary *ZtnewWTkfk = @{
		@"sycoBKnOcwZUpHNCbiH": @"ztypaCGtRdUhPdtOijwMkZzFGMafHwyXEzapHXOCmqRGXsCoVbcaWiXvWZZowBkbBXwtoWeHuyYVLGzquksVoHzbKadkUctSTpijcTnYrrEkHqTYITSfHHpUjaCaAe",
		@"vWBDLbYCQTomFbtsuYnw": @"cwQRJpDlOaKNgmNllWtBSnvtoNNCdtnoREMqDoVzwrlsfVobfPfLxGWYkpAQEJRfQWdVoBerHvJSevpeJnoedVpuiEiFkJQqhiNzHCLfZdqFeBpodGaZp",
		@"vONMIGEUnIVIPAZzOuBEb": @"bXRPnlvZwiBUwpTzKnEwoLBHHlyGeXjAvRpvoisnjvVefxDlUKBhwazGDqWfhavvELTyTpeuVbiscuhmImbeihdSpKhHAfzCweWVsmrXuPrmeSbhm",
		@"TWzdNFbVUzGCgzSrayyB": @"przAATfrwNyhcPSHvaPjfracAycvQLOEOOceGNXtVVcQCAQGqHyBtXZTbsdOEUHFGuxtZkWPwsbVZIwVGmzhgsYtlwnqjXwxaAiXShikLCloFGEOpAjTSdTI",
		@"fUCuURrYCUlKVxfmT": @"gwzUyZWHBHgeUsgMtRYZpONMzDpjyUfDppzBwPmFKsZteGuLWWiahQnRCTznAyznXaJouySUAouFxUcxSIqmArLQtowuSZVKPjZegaKfwYWEFwcZezDavlyQtSrXlX",
		@"tkSzUPZPKgqtCvNvjk": @"moHNIfJVhJEfVkrOVcIikRlsKjcCwcGnVEbOXUHDITfPfuEILrIHhFBzMJZmpgHraGFiaJyRqeyQyPxegCRYyCNPohNlqIRFkojKJYJtWkXQuKLHZJg",
		@"AHxHJPuoXxhjf": @"uHEomTNUUTFciyudnbtDeUnkMWvUjOmhBbMaTaXWpWLhHJKOPUYPDxViLdSAxtbaLlKydMxXDxSznPeUhNEaJbSPKHusLJMAmWHZRGdBmeskhJCUNyQIGNxFbSlyyvVXXIzg",
		@"GDLSnzxVdcUcZkpV": @"YWFzvjZXqCfRIYoUxlYdzjNAEozTwevSPqAyRSSaFNsXkTuwptaHJXQogoUGxQertmptBtwFFmOFjwWeTNxTBPgpQDHfmiihpXJaRzGlO",
		@"OeuPrHuhNfFlcG": @"sHYaXeqlCirJHemlqNmvQehzDFJbnWCwxAIJmBQApAaeIRpzDGmGlQwtVFbAkTZZhtMorZIBYomYQurKqsrzpJKSDfFaYdCYGijOrzRFLwtTZVgrqSxDzOMQabYvQV",
		@"lvmfnBAbER": @"PDnxLsepaHZTiIDHqXQGxgtqDpLzQQNZkEudswpyJxZNbCNIFuIGTCWoTpzGBWDjhhFsdMSbvziEWVpxTdGuzJOjwYsgeQlmyrxrqjCdjDmBPxamwuYvxqCKxmzOcAaLrIf",
		@"ySjJyrJfpHMONYH": @"rbSCHfKMbhRGEwUfEXYVKRAbehrIYvzVPvpcWnJFlXbbJaPrAVoxzQbrCwIkxMKWvNLevUEkWoIUirTMTaIXNNLeTmZpKszLQUVfZ",
		@"SzWOjGqMiM": @"DderviJtDBWNyhMhdyGDLXJbkgSApWZgbUUsKMUONzVOIcOwIAepNSUQKxFPsDkcUbUHEgeyfyBAygOqjlASuHdtQsBlYXVwxjnTnKSYebYFtwWCBmiorlGzrcFYwQSAtQWiXRSQoexWjJ",
		@"zukknsUddgeYaOBswBlkF": @"eRXaGOHLTPkenVBvPwpzVubMiWwvvhykpCxmDgyKIwMXoEeqmnyDCMMeXPCwuOGqrNMzNHwWNeMGhRoTPltDvecAsWoUxiXBKIWADNPbChhJinepLizmjEkCbqvwSsVyrVtoLoH",
		@"XjgaccwtQANBpoh": @"IvMnUCTptJxSRHCdugIVHYbefKtxyDuYBqUiBGcVcGDHNAuUikuQaSwJfXqVlEUtuofVQmfBJtMMDUKWmscsvFgTIlrinjwLrNGmVFNylGrnEqbkzlwkEWmreQGWknJGLIXRuPQte",
		@"fHAIkPFkfhavyIsXUvkrwOwB": @"ruISucJFzvjxzBnKmAeOPwqVtEFrNCiqqAuPCnMhbfbvFufwNfeMQZSZmwqvoPZEkiCBbJqDqDgbjnQNWNOdytabDiQiFgnvkfNxDJkujcpoLXVbUusxytmBKwjvpJVfJ",
		@"cabFGNzPaiCKSeytcvIkub": @"lNrLBbNgAyRYkYvVMpClIAofCFqOdqSnTdsGbeAGVpQoJmdgZqFwdMPcqsUYCqGPAiRFQSdWGagtAZcJBhYvjMdMuQHhLZtGeYXrdo",
		@"BmEDdliDYkvWxf": @"wVxXhvnOMgxAjxNoTQSfJIyrNEeObgCciOCZMKtWDsrspnArnqPVRcuEaBMUoVfeMjAGObLnMhuERJkAiTSGlTzadbcnkyDTqhpEHBYzJbPwzYtzZui",
	};
	return ZtnewWTkfk;
}

+(BLepubinfoelement*)elementwithfile:(NSString*)filepath
{
    
    BLepubinfoelement* ele=[[[BLepubinfoelement alloc]init]autorelease];
    NSDictionary*dic=[NSDictionary dictionaryWithContentsOfFile:filepath];
    ele.Opfpath=[dic objectForKey:@"Opfpath"];
    ele.metadata=[dic objectForKey:@"metadata"];
    ele.spine=[dic objectForKey:@"spine"];
    ele.manifest=[dic objectForKey:@"manifest"];
    ele.rootpath=[dic objectForKey:@"rootpath"];
    ele.maybetitles=[dic objectForKey:@"maybetitles"];
    return ele;
}

-(NSArray*)bookComtentPathlist
{
    NSInteger length=[self.spine count];
    NSMutableArray* arr=[NSMutableArray arrayWithCapacity:length];
    
    NSString* fileroot=[self.Opfpath stringByDeletingLastPathComponent];

   NSURL* baseurl=[[[NSURL alloc]initFileURLWithPath:fileroot isDirectory:YES]autorelease];

    NSFileManager* filemanager=[NSFileManager defaultManager];
    for(int i=0;i<length;i++)
    {
        NSDictionary* dic=[self.manifest  objectForKey:[self.spine objectAtIndex:i]];
        NSString* str=[dic objectForKey:@"href"];
        if(str!=nil)
        {
            NSURL* url=[NSURL URLWithString:str relativeToURL:baseurl];
            NSURL* ur=[url absoluteURL];
            NSString* path=[ur  path];
            if([filemanager fileExistsAtPath:path])
            {
                [arr addObject:path];
            }
        }
    }
    return arr;
  
}


-(NSArray*)bookmaybetitles
{
    return self.maybetitles;
    

}


@end
